### ISSUE TITLE
`LightningModule.to_torchscript()` causes false positive deprecation warnings

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#10092]
### To Reproduce

```py
import torch

from pytorch_lightning import LightningModule


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)


def run():
    model = BoringModel()
    scripted = model.to_torchscript()
    print(scripted)


if __name__ == "__main__":
    run()

```

```
/Users/adrian/.conda/envs/lightning/lib/python3.8/site-packages/torch/jit/_recursive.py:614: LightningDeprecationWarning: The `LightningModule.loaded_optimizer_states_dict` property is deprecated in v1.4 and will be removed in v1.6.
  item = getattr(mod, name, None)
/Users/adrian/.conda/envs/lightning/lib/python3.8/site-packages/torch/jit/_recursive.py:614: LightningDeprecationWarning: The `LightningModule.model_size` property was deprecated in v1.5 and will be removed in v1.7. Please use the `pytorch_lightning.utilities.memory.get_model_size_mb`.
  item = getattr(mod, name, None)
/Users/adrian/.conda/envs/lightning/lib/python3.8/site-packages/torch/jit/_recursive.py:701: LightningDeprecationWarning: The `LightningModule.model_size` property was deprecated in v1.5 and will be removed in v1.7. Please use the `pytorch_lightning.utilities.memory.get_model_size_mb`.
  item = getattr(nn_module, name, None)
/Users/adrian/.conda/envs/lightning/lib/python3.8/site-packages/torch/jit/_recursive.py:501: LightningDeprecationWarning: The `LightningModule.model_size` property was deprecated in v1.5 and will be removed in v1.7. Please use the `pytorch_lightning.utilities.memory.get_model_size_mb`.
  item = getattr(nn_module, name, None)
/Users/adrian/.conda/envs/lightning/lib/python3.8/site-packages/torch/jit/_recursive.py:584: LightningDeprecationWarning: The `LightningModule.model_size` property was deprecated in v1.5 and will be removed in v1.7. Please use the `pytorch_lightning.utilities.memory.get_model_size_mb`.
  item = getattr(nn_module, name, None)

```

### Expected behavior

No deprecation warning, since user did not have these properties in their code.

### Environment

```
* CUDA:
        - GPU:
        - available:         False
        - version:           None
* Packages:
        - numpy:             1.20.3
        - pyTorch_debug:     False
        - pyTorch_version:   1.10.0
        - pytorch-lightning: 1.5.0rc1
        - tqdm:              4.62.3
* System:
        - OS:                Darwin
        - architecture:
                - 64bit
                - 
        - processor:         i386
        - python:            3.8.11
        - version:           Darwin Kernel Version 19.6.0: Tue Jun 22 19:49:55 PDT 2021; root:xnu-6153.141.35~1/RELEASE_X86_64

```

cc @justusschock @awaelchli @akihironitta @rohitgr7 @tchaton

**Comment by carmocca** [comment]
Hi @awaelchli! Do you have any intuition of how we could work around this?

I encountered it yesterday (opened https://github.com/PyTorchLightning/pytorch-lightning/issues/10447) as it completely blocks #9939 which I wanted to finish before there are any new deprecations. I thought https://github.com/PyTorchLightning/pytorch-lightning/blob/d515bcac969c2a485ada673e302bfac51f142331/pytorch_lightning/core/lightning.py#L82 was supposed to avoid this.

looping in @justusschock in case he knows.

**Comment by awaelchli** [comment]
To work around this, we would have to introduce a variable ourselves on the LightningModule, and guard the deprecation warnings.

**Comment by justusschock** [comment]
We could try to patch the `warnings.warn()` with `@torch.jit.ignore` [(source)](https://pytorch.org/docs/stable/generated/torch.jit.ignore.html?highlight=torch%20jit%20ignore#torch.jit.ignore).

Other than that, I have no idea, sorry :/

**Comment by carmocca** [comment]
That would be a great solution but unfortunately does not seem to work. I opened a PR with the flag proposed by Adrian.

**Comment by carmocca** [comment]
Changing the milestone to a feature release as we've fixed the issue with a hack and removing said hack can be considered a refactor

**Comment by jharris1679** [comment]
I've just upgraded to lightning 1.8.3 and I'm seeing something similar to this but it's now a RuntimeError that prevents me from saving a model:

`compiled_model = torch.jit.script(initialized_model)`

raises

`RuntimeError: LightningModule.use_amp was deprecated in v1.6 and is no longer accessible as of v1.8. Please use Trainer.amp_backend.`

Is there maybe another way I should be saving model artifacts?

**Comment by aggiejiang** [comment]
@jharris1679 Hi, I met the same RuntimeError in the same lightning version. Did you solve it?

**Comment by jharris1679** [comment]
@aggiejiang upgrading to 1.8.4 worked for me

**Comment by awaelchli** [comment]
Closing the issue for two reasons: 
1) The deprecations that were emitted here were removed in Lightning 2.0 and prior. 
2) PyTorch won't be able to address it since they no longer work on torchscript/jit after PyTorch 2.0.

`to_torchscript()` will work as long PyTorch supports it, and anyone running in the issue described here can either suppress it or upgrade Lightning.
