### ISSUE TITLE
Validate environment variables in SLURMEnvironment and warn user about incompatible settings

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#10150]
## 🚀 Feature

Check slurm environment settings and print warnings if needed.

### Motivation

If SLURM srun variables are set incorrectly, the processes can hang and the user will not know why.

Examples:
- https://github.com/PyTorchLightning/pytorch-lightning/issues/4612#issuecomment-949937617
- #15141

### Pitch

In the SLURM cluster environment, check for example:

```py
if os.environ.get("SLURM_CPUS_PER_TASK") > 1:
    warn(
        "You asked SLURM for multiple CPUs but we are not sure your machine has multiple CPUs. "
        "If your process hangs, consider setting --cpus-per-task=1"
    )

```
### Alternatives

Do nothing. Users will keep submitting issues :) 

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

cc @borda @awaelchli

**Comment by awaelchli** [comment]
No!

**Comment by tchaton** [comment]
Great idea! Let's do it.
