### ISSUE TITLE
[Lite] Custom runnable methods

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lightning#10193]
### Motivation

`LightningLite` is an abstract class, which defines:

```python
    @abstractmethod
    def run(self, *args: Any, **kwargs: Any) -> Any:
        ...
```

as its only abstract method.

If the Lite user has more than one loop to convert to lite, he/she is forced to create separate `LightningLite` instances, one with each `run` implementation.

Users might need to override different functions, perhaps because your code is slightly different and you don't want to bother adding flags to cram everything into a single function.

In that case, Lite could allow the following:

### Pitch

```python
class LightningLite:
   # class attribute
   # should this be a `frozenset` instead? we want this immutable
   patch_methods: Set[str] = {"run"}

class Lite(LightningLite):
    patch_methods = {"fit", "jiraffe"}
 
    def fit(self):
        ...

    def jiraffe(self):
        ...

lite = Lite()
lite.fit()
lite.jiraffe()
```

### Alternatives

If we keep a list of our methods, we could avoid requiring the user to set `patch_methods`. Maybe too hacky though.

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

**Comment by aazzolini** [comment]
I'm trying to understand what is really being offered to the user when we tell them to implement a method in a class that derives from LightningLite.

What does the user get out of this that the user wouldn't get by implementing their own class, or keeping the method free?

For example


def fit(lite):
    ...

def jiraffe(lite):
    ....

lite = Lte()

lite = LightnigLite()
lite.run(fit)
lite.run(jiraffe)

**Comment by carmocca** [comment]
So if I understood your proposal, you are suggesting the API becomes:

```python
def jiraffe(lite: LightningLite, num_epochs: int):
    model = MyModel(...)
    optimizer = SGD(...)
    model, optimizer = lite.setup(model, optimizer)
    dataloader = DataLoader()...)
    dataloader = lite.setup_dataloaders(dataloader)

    model.train()
    for epoch in range(num_epochs):
        for batch in dataloader:
            optimizer.zero_grad()
            loss = model(batch)
            lite.backward(loss)
            optimizer.step()


lite = LightningLite(strategy="ddp", devices=2, accelerator="gpu")
lite.run(jiraffe, 123)
```

where:

- The accelerated function must take `lite` as the first positional argument, which replaces `self` in the current implementation
- the accelerated function is passed as a Callable to `lite.run`, as well as any necessary `*args, **kwargs` for the function.
