### ISSUE TITLE
Call for High Quality Lightning Lectures - Community Sprint

### ISSUE THREAD

**Issue by tchaton** [Lightning-AI/lightning#10239]
## 🚀 Feature

Dear community, 

As PyTorch Lightning mature, we believe it is important for the Lightning Team and its community to improve the Lightning onboarding process.

In that regards, the PyTorch Lightning Team (@Borda) built a https://github.com/PyTorchLightning/lightning-tutorials repo containing tuto-books (notebooks as python script). The tuto-books are converted into notebooks, fully tested on GPUs and injected directly within the Lightning documentation.
Learn more with this blogpost: https://devblog.pytorchlightning.ai/publishing-lightning-tutorials-cbea3eaa4b2c

The tutorials can be found there on the main page of the documentation: https://pytorch-lightning.readthedocs.io/en/latest/

@phlippe, PHD from the University of Amsterdam contributed their Deep Learning Course from 2020 and it is now rendered within Lightning documentation (released officially with v1.5). Great thanks from the entire community :)

However, the Lightning Team doesn't want to stop there and we would like to encourage the community to contribute more high quality course and collaborate closely with us to implement best practices while doing so.

We plan to organize a tutorial sprint to create high quality tutorial / course and would like the community to share ideas and collaborate with the Lighting Team in this project. We will soon share a Google Form for the community to share their ideas and possibly to contribute. 

Here are the requirements for a tutorial to be accepted:

* The Tutorial should present a field of AI in simple terms, not a single method. The UVA Course SSL or Meta-Learning notebooks are a great example of such works.

* The Tutorial should contain high quality animated visuals, be engaging, well written and simple to follow. Assume new comers.

* The tutorial should come with a short description, thumbnail.

* The Tutorial should contain a YouTube video going through the notebook + attendees asking questions (Lightning Team and community). We might live stream the event and use the recording as its explanation ;)   

Note: The Lightning Team Editors can help there with visuals, thumbnail

Here are some high quality notebooks we are planning to work on:
(This list isn't exhaustive and we would like the community to propose ideas based on their skills and interests). 

* [ ] Lightning introduction for engineers 
* [ ] Lightning introduction to distributed training and challenges. Ultimate guide.
* [ ] Lightning best practices
* [ ] Lightning introduction for researchers 
* [ ] Lightning and Video (PyTorch Video)
* [ ] Lightning and PointCloud
* [ ] Lightning and 3D Rendering (PyTorch3D)
* [ ] Lightning and Quantum (Pennylane)
* [ ] Lightning and Probabilistic Models (scvi-tools)
* [ ]  Lightning and Forecasting (PyTorch Forecasting)
* [ ] Lightning on Kaggle (Flash)
* [ ] Lightning and 3D Images (Monai)
* [ ] Lightning and Temporal Graphs (PyTorch Geometric / PyTorch Geometric Temporal)
* [ ] Lightning and GANS
* [ ] Lightning and Style Transfer
* [ ] Lightning and Image Synthesis (https://github.com/CompVis/taming-transformers)
* [ ] Lightning and Reinforcement Learning (Single / Multiple Agents)
* [ ] Lightning and Online Learning
* [ ] Lightning and Sequential Learning
* [ ] Lightning and ODE
* [ ] Lightning and Federated Learning
* [ ] Lightning and Multi Tasks
* [ ] Lightning and HPO (Optuna)
* [ ] Lightning and Precision Scheduling
* [ ] Lightning and Arts Generation !

# Applications related

* [ ] PyTorch Profiler + ORTModule + DeepSpeed Sparse + OnnxRuntime.js + Triton (Exploration for optimized application building)

Bonus: Notebook translation would be a massive plus and would help to democratize AI in the entire world :)

- Chinese
- German
- Czech
- Hebrew
- French
- Russian
- Spanish
- Japanase
- Hindi
 
If you are interested, please add a comment below and assign your name to the proposal(s), your level, share about your availabilities and your confidence into your contribution being impactful from 1 to 5 :) 

Please, apply to this [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfJJ2C6sOwuTPeegrzsizBNcSWb8dgurq_tQGqfjIGFMXNR7g/viewform?vc=0&c=0&w=1&flr=0)

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

**Comment by Carlosbogo** [comment]
I am a native Spanish speaker and I would be glad to help with the translation in that language.
Should I start somewhere in particular?

**Comment by felixdittrich92** [comment]
@tchaton 
This list needs definitly also some lightning + huggingface transformers parts ( for example how to fine tune huggingface models with lightning)  🤗 
wdyt?

**Comment by Carlosbogo** [comment]
I'm sorry, but I don't quite understand what would be the necessary steps to contribute to this repository with a translation:
from what I understand, it would be helpful to have the notebooks translated, but are there any of them already being worked on? If not, where should I upload the ones I translate?

I have looked around a bit (mainly in this repository and in [the tutorials one](https://github.com/PyTorchLightning/lightning-tutorials)) but I haven't found any specific place where the translatied notebooks should be located.

If there are already some translations being done or maybe a person or a group working on them (even if they are not related to the Spanish one) it would be very helpful for me if you let me know about them to be able to work together or to take them as an example to improve my efficiency.

**Comment by tchaton** [comment]
Dear @Carlosbogo,

We are still polishing our ideas around translation. We were thinking to use automatic translation and use a translator to refine them. @Borda Anything else to add?

Best,
T.C

**Comment by tchaton** [comment]
Hey @yifuwang. Let's keep this issue pinned, so new comers can find this issue faster and propose their contributions

**Comment by shabie** [comment]
I can imagine doing Lightning + Forecasting if it is up for grabs or collaboration in any sense.

**Comment by Ashish013** [comment]
Hello, @tchaton. I filled out the Google form and would like to contribute to the Lightning and Image Synthesis notebook. I've reviewed the attached repository, too, and maybe I can begin working on it or is it already assigned?

**Comment by tchaton** [comment]
Hey @Ashish013,

That's great, yes please start working on it and share the PR in Lightning Slack for review.

Best,
T.C

**Comment by vwxyzjn** [comment]
Hello, I am the creator of the [Proximal Policy Optimization (PPO) Implementation Deep Dive series](https://www.youtube.com/playlist?list=PLD80i8An1OEHhcxclwq8jOMam0m0M9dQ_). Pytorch-lightning is a fascinating project, and I hope to an RL tutorial using it sometime next year. Just posting here to keep track of it :) 

cc @tchaton

**Comment by mathemusician** [comment]
Is there any interest in using Lightning for Music Generation?

**Comment by tchaton** [comment]
Hey @mathemusician,

Yes, 100 %. If you are interested, you can start add an advanced example to Lightning Tutorials :)

Best,
T.C

**Comment by SaulAryehKohn** [comment]
Lightning is quickly becoming a standard part of my DL projects. I have several years of experience doing weakly supervised learning and would be interested in building out a tutorial along those lines for medical imaging. Open to collaboration too :)
