### ISSUE TITLE
[RFC] Deprecate `auto_select_gpus` from Trainer constructor

### ISSUE THREAD

**Issue by daniellepintz** [Lightning-AI/lightning#10535]
## Proposed refactoring or deprecation

Deprecate `auto_select_gpus` from Trainer constructor:
https://github.com/PyTorchLightning/pytorch-lightning/blob/7a9a08c5d3ca4699fb439f691c40e1320b37507a/pytorch_lightning/trainer/trainer.py#L209-L212

### Motivation

Users can achieve the same functionality by setting the `accelerator` and `devices` flags - we can simplify by only having one way of doing this.

cc @justusschock @awaelchli @rohitgr7 @tchaton @kaushikb11 @borda

**Comment by kaushikb11** [comment]
@daniellepintz We do have users using it. For instance, https://github.com/PyTorchLightning/pytorch-lightning/issues/10456.
It could be pretty convenient when users are running multiple experiments on bunch of GPUs.

**Comment by daniellepintz** [comment]
@kaushikb11 can this same functionality not be achieved with `accelerator` and `devices` flags?

**Comment by rharish101** [comment]
@daniellepintz Currently, I think that if we want 3 available GPUs, then we need to specify `devices=3` and `accelerator='gpu'`. However, this means that GPUs [0, 1, 2] are selected, even if one of them is fully used by another process:
https://github.com/PyTorchLightning/pytorch-lightning/blob/ffb1a754af5301608c71955c12468216e920af51/pytorch_lightning/utilities/device_parser.py#L76

However, with `auto_select_gpus`, it chooses 3 GPUs that are available. This will be [0, 1, 2] if all three are available, else it will also check GPUs 3, 4, etc. until it finds 3 available GPUs.
