### ISSUE TITLE
Deepspeed + SWA results in no optimizers

### ISSUE THREAD

**Issue by ChickenTarm** [Lightning-AI/lightning#10628]
## 🐛 Bug

When using deepspeed_stage_2 with stochastic_weight_avg the `configure_optimizers` is not called resulting in the training thinking it has no optimizers
If I uncomment `# stochastic_weight_avg="true",` then I get the following error:
pytorch_lightning.utilities.exceptions.MisconfigurationException: SWA currently works with 1 `optimizer`.

### To Reproduce

```py

    import os
    import torch
    from torch import nn
    import torch.nn.functional as F
    from torchvision import transforms
    from torchvision.datasets import MNIST
    from torch.utils.data import DataLoader
    import pytorch_lightning as pl
  
  
    class LitAutoEncoder(pl.LightningModule):
      def __init__(self):
          super().__init__()
          self.encoder = nn.Sequential(nn.Linear(28 * 28, 64), nn.ReLU(), nn.Linear(64, 3))
          self.decoder = nn.Sequential(nn.Linear(3, 64), nn.ReLU(), nn.Linear(64, 28 * 28))
  
      def forward(self, x):
          # in lightning, forward defines the prediction/inference actions
          embedding = self.encoder(x)
          return embedding
  
      def training_step(self, batch, batch_idx):
          # training_step defined the train loop.
          # It is independent of forward
          x, y = batch
          x = x.view(x.size(0), -1)
          z = self.encoder(x)
          x_hat = self.decoder(z)
          loss = F.mse_loss(x_hat, x)
          # Logging to TensorBoard by default
          self.log("train_loss", loss)
          return loss
  
      def configure_optimizers(self):
          optimizer = torch.optim.Adam(self.parameters(), lr=1e-3)
          return optimizer


    trainer = pl.Trainer(
        gpus=1,
        precision=16,
        accelerator="gpu",
        strategy="deepspeed_stage_2",
        amp_backend="native", 
        # stochastic_weight_avg="true",
    )
    
    dataset = MNIST(os.getcwd(), download=True, transform=transforms.ToTensor())
    train_loader = DataLoader(dataset)
    
    trainer.fit(LitAutoEncoder(), train_loader)
```

### Expected behavior

Should be able to use deepspeed_stage_2 and SWA unless there is a fundamental reason this shouldn't be done.

### Environment

* CUDA:
        - GPU:
                - Tesla T4
        - available:         True
        - version:           11.3
* Packages:
        - numpy:             1.21.3
        - pyTorch_debug:     False
        - pyTorch_version:   1.10.0+cu113
        - pytorch-lightning: 1.5.2
        - tqdm:              4.62.3
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.9.9
        - version:           #61~18.04.1-Ubuntu SMP Thu Oct 28 04:16:28 UTC 2021

### Additional context

cc @tchaton @SeanNaren @awaelchli @carmocca

**Comment by awaelchli** [comment]
Closing this old issue. DeepSpeed is not supported with this callback: https://github.com/Lightning-AI/lightning/blob/c21b6de3c732af85414060dc3a643801d89ba71b/src/lightning/pytorch/callbacks/stochastic_weight_avg.py#L143-L144
