### ISSUE TITLE
Lightning Tutorials shouldn't be on the landing page of the documentation

### ISSUE THREAD

**Issue by kaushikb11** [Lightning-AI/lightning#10632]
## 📚 Documentation

The collection of lightning tutorials is brilliant, but it shouldn't be on the landing page of the documentation.
When a user opens https://pytorch-lightning.readthedocs.io/en/latest/, they are most probably looking to learn more about the PyTorch Lightning features, rather than tutorials such as "Introduction to Pytorch" and so on. 

We have a separate section for Tutorials and it is quite visible with a slight scroll down.

cc @borda

**Comment by tchaton** [comment]
I personally prefer them in the landing page. This brings them to the user faster and increases engament.
I believe we will move them when they have been around for some time, v1.6 or v1.7

**Comment by ethanwharris** [comment]
One option here is to just also include some of our docs pages / guides in there too. I think the PyTorch docs have a special callout for a quickstart type page...

**Comment by kaushikb11** [comment]
It could be a separate section like what PyTorch does. https://pytorch.org/tutorials/

**Comment by edenlightning** [comment]
It can be in the landing page I think, but only under a section that eplxians briefly:
* What is lighnting
* How to get started (links to relevant pages)
* Further reading (Links to LM, TRainer, API reference)

**Comment by shabie** [comment]
> ##  Documentation
> The collection of lightning tutorials is brilliant, but it shouldn't be on the landing page of the documentation. When a user opens https://pytorch-lightning.readthedocs.io/en/latest/, they are most probably looking to learn more about the PyTorch Lightning features, rather than tutorials such as "Introduction to Pytorch" and so on.
> 
> We have a separate section for Tutorials and it is quite visible with a slight scroll down.
> 
> cc @Borda

As someone who has tried to learn the framework quite recently, I really support this. It is quite confusing to be introduced to PyTorch which is not at all I was looking for.

**Comment by awaelchli** [comment]
I agree with this too. The landing page should at least contain an abstract or an installation section or link to installation instructions or a quick start or link to the quick start.
