### ISSUE TITLE
Generalize internal checks for precision plugin type, training type, accelerator type 

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#10821]
## Proposed refactor

Internally, our checks against the type of Accelerator, Precision type, strategy is not robust towards custom instances passed in by the user. 

### Motivation

Internally, some operations in the optimization, logging, etc. need a different code path depending on 1) Accelerator type (cpu, gpu) or 2) Precision type (apex, native) or 3) strategy type (ddp, ddp-spawn, ...). Currently we have this pattern: 

```py
if trainer._device_type == DeviceType.CPU:
    # do something only for cpu


if trainer._amp_backend == AMPType.Apex:
    # do something differently for apex
```

### Pitch

Change these to

```py
if isinstance(trainer.accelerator, CPUAccelerator):
    # do something only for cpu


if isinstance(trainer.precision_plugin, ApexPrecisionPlugin):
    # do something differently for apex
```

This has the benefits:
- User passes in custom plugins (subclasses of our plugins)
- Encapsulation: Protected members _device_type, _strategy_type, won't be abusively accessed publicly anymore. They remain an implementation detail of AcceleratorConnector
- Minimally simplifies AcceleratorConnector logic

### Additional context

Discusson started in https://github.com/PyTorchLightning/pytorch-lightning/pull/10596

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda @justusschock @awaelchli @rohitgr7 @kaushikb11 @akihironitta @ananthsub

**Comment by tchaton** [comment]
This seems cleaner and easier to debug. Let's do it.

**Comment by carmocca** [comment]
NVM my previous comment, @justusschock will take it

**Comment by carmocca** [comment]
@justusschock Do you think you could finish this for 1.8?

**Comment by justusschock** [comment]
Definitely!

**Comment by awaelchli** [comment]
You failed.

**Comment by awaelchli** [comment]
Sorry, couldn't resist with the stupid comment 😄 

But in all seriousness, I think we completed this in the meantime already. It seems all enum types got removed. Or do you see anything left?
