### ISSUE TITLE
[RFC] Revisit Usage of MisconfigurationException

### ISSUE THREAD

**Issue by justusschock** [Lightning-AI/lightning#10918]
## Proposed refactor
Replace Misconfiguration Exception with more diverse error types.

### Motivation

Currently we are using the `MisconfigurationException` for everything even if they are not directly related to the user's configuration. This means that the type of exception has no additional information about the kind of error. Python has some builtin exception types for that like `RuntimeError`, `ValueError`, `TypeError` etc. To gain more insights from the actual exception type, I propose to not use MisconfigurationException any longer and replace it with the other error types.

### Pitch
Have Lightning raising appropriate error types instead of just `MisconfigurationException` everywhere.

### Additional context

If we want to have some Lightning-Unique Exceptions we could still do something like 
```python
class LightningValueError(ValueError):
    pass

```
for the necessary error types and then raise these. This has the advantage that people could still have custom error handling also depending on types and statements like `except ValueError` would still catch those but they could also decide to only catch Lightning Errors.
______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

PS: Not sure under which part of the code to put it, since it probably touches all of them :D

cc @borda @justusschock @awaelchli @akihironitta @rohitgr7 @ananthsub @tchaton @carmocca 

EDIT: current usage of the `MisconfigurationException`: https://grep.app/search?q=MisconfigurationException&filter[repo][0]=PyTorchLightning/pytorch-lightning

**Comment by carmocca** [comment]
Fully agree!

**Comment by justusschock** [comment]
question is: Will we consider this as a breaking change or do we expect that nobody except us uses that? grep.app only shows usage of that from other frameworks/other languages unrelated to lightning.

**Comment by carmocca** [comment]
I believe we can deprecate it doing this:

```python
from pytorch_lightning.utilities.exceptions import MisconfigurationException


class ValueError(ValueError, MisconfigurationException):
    ...

error = ValueError("this is a test")
print(isinstance(error, __builtins__.ValueError))  # True
print(isinstance(error, MisconfigurationException))  # True
raise error  # shows as ValueError
```

where importing `MisconfigurationException` is what shows the deprecation message.

**Comment by justusschock** [comment]
But that way we would always at least once trigger the warning because we internally import the MisconfigurationException, no?

**Comment by carmocca** [comment]
Yes, we would need to hack it so that doesn't happen.

Or not deprecate it.

**Comment by calebbuffa** [comment]
Is this still an open issue? If so can it be assigned to me?

**Comment by carmocca** [comment]
Yes!

**Comment by calebbuffa** [comment]
Agreed, so in option 3 we would want a deprecation warning if an end-user imports the class but not if a developer does, correct? Also, did we lean towards lightning specific sub classes (i.e LightingValueError) as originally proposed or using generic errors?

**Comment by carmocca** [comment]
Yes, let's go with the 3rd option. This is my suggested implementation:

```python
class _DeprecatedException(type):
    def __instancecheck__(cls: Type, instance: object) -> bool:
        return any(cls.__subclasscheck__(c, stacklevel=7) for c in {type(instance), instance.__class__})

    def __subclasscheck__(cls, subclass: Type, stacklevel: int = 5) -> bool:
        mro = subclass.mro()
        actual, real, *rest = mro
        if cls is not subclass and cls is actual:
            raise TypeError(f"`{subclass.__name__}` should not be used for checks.")
        if cls is MisconfigurationException:
            rank_zero_deprecation(
                f"`{MisconfigurationException.__name__}` is deprecated. Please check with `{real.__name__}` instead.",
                stacklevel=stacklevel,
            )
        return cls in mro


class MisconfigurationException(Exception, metaclass=_DeprecatedException):
    """Exception used to inform users of misuse with PyTorch Lightning."""

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        rank_zero_deprecation(f"Using `{type(self).__name__}` is deprecated.", stacklevel=5)
        super().__init__(*args, **kwargs)


# protected to avoid future deprecations
class _ValueError(ValueError, MisconfigurationException, metaclass=_DeprecatedException):
    ...
```

```python
def test_exception_deprecations():
    from pytorch_lightning.utilities.exceptions import _ValueError, MisconfigurationException
    from tests_pytorch.deprecated_api import no_deprecated_call

    with no_deprecated_call():
        x = _ValueError("test")
        assert isinstance(x, _ValueError)  # this needs to work for proper instantiation
    with pytest.deprecated_call(match="Please check with `ValueError"):
        assert isinstance(x, MisconfigurationException)
    with no_deprecated_call():
        assert isinstance(x, ValueError)

    with pytest.deprecated_call(match="Using `MisconfigurationException` is deprecated"):
        y = MisconfigurationException("this is deprecated")
    with no_deprecated_call():
        assert isinstance(y, MisconfigurationException)
    with no_deprecated_call():
        assert not isinstance(y, ValueError)

    try:
        raise x
    except MisconfigurationException:
        pass

    try:
        raise x
    except ValueError:
        pass
```

Where we would use these custom protected variants until `MisconfigurationException` is removed.

The work left for you @calebbuffa would be to update all usages of `MisconfigurationException` to use these new alternatives

**Comment by calebbuffa** [comment]
Great, thanks for the help! I'll get to replacing usages of `MisconfigurationException` with `_ValueError`.

**Comment by carmocca** [comment]
Note that not all of them might be ValueErrors, TypeError, RuntimeError or a different exception type might fit better depending on the case. I just wrote `_ValueError` in my previous message for conciseness.

Choosing the most fitting exception class is what's most important: https://docs.python.org/3/library/exceptions.html#base-classes

**Comment by carmocca** [comment]
Also, only when we instantiate the exception you should use the `_*Error` class.
For `isinstance`, `issubclass`, or `except *` checks you should use the Python builtin class

**Comment by justusschock** [comment]
Also note that we might want to also add a custom implementation of `__repr__` definition as we want to show them as plain python errors. 

E.g. we want something like this:

```python
class _ValueError(ValueError, MisconfigurationException):
    ...
    def __repr__(self):
        str_repr = super().__repr__()
        if str_repr.startswith('_'):
            str_repr = str_repr[1:]
        return str_repr
```

**Comment by calebbuffa** [comment]
Right, that makes sense. If you don't mind, I might ask for feedback at some point before I've finished to make sure the implementation aligns correctly.

**Comment by justusschock** [comment]
I think the best would be to open a draft PR so that we can directly review the code at hand :) Of course if you have any questions before that, feel free to ask here:)

**Comment by calebbuffa** [comment]
Quick clarification question, as I work on this this has started feeling more complicated than it needs to be. Primarily, multiple inheritance past the 2nd generation of parents (which all new exceptions would be) introduces a lot of coupling and new code inheriting from deprecated code feels like a recipe for refactoring/future breakges. It seems far simpler to just create a decorator (`@decorated_exception`) that decorates MisconfigurationError` while all new errors (i.e. `LightningValueError`) simply inherent from `Exception`. I might have gone down an unneeded rabbit hole and missed the point, but would someone mind reminding me why new exceptions need to inherit from a deprecated exception?

**Comment by awaelchli** [comment]
There is no need to make something complicated here. 99% of all uses of MisconfigurationError can be replaced with one of these three types: TypeError, ValueError, RuntimeError. We already started doing this in new code!

Examples:

TypeError: When user gave us a list but a dictionary was expected
ValueError: We expected x > 0 but user passed in x = -2
RuntimeError: During execution, we found that some configuration was wrong and we need to abort. 

Deprecating the MisconfigurationError is definitely not the first step. First we need to replace the usages. Only at the end, when only the definition of MisconfigurationError is left can we deprecate this error class.

@carmocca will correct me if I'm wrong.

**Comment by carmocca** [comment]
> Deprecating the MisconfigurationError is definitely not the first step. First we need to replace the usages. Only at the end, when only the definition of MisconfigurationError is left can we deprecate this error class.

@awaelchli The reasoning behind creating [this DeprecatedException "magic" ](https://github.com/Lightning-AI/lightning/issues/10918#issuecomment-1227344372) was to not break users who had `except MisconfigurationException` in their code.

>  why new exceptions need to inherit from a deprecated exception?

The above is the reason

> introduces a lot of coupling

What is this coupling?

> new code inheriting from deprecated code feels like a recipe for refactoring/future breakages

Yes, they would all be removed after the deprecation process is over.

> while new errors (i.e. LightningValueError) simply inherent from Exception

This would not be different to what `MisconfigurationException` does. The end goal to use the more informative and native exceptions (ValueError, TypeError, ...), but what's tricky is how to get there whilst minimizing breaking changes

**Comment by calebbuffa** [comment]
> What is this coupling?
Coupling is just introducing dependencies in the code such that changing one thing can/will break/change downstream tasks. 

But thank you @carmocca for the clarification, I'll keep going with the current solution

**Comment by calebbuffa** [comment]
Any chance I could get feedback on my draft PR?

**Comment by carmocca** [comment]
Looks great so far @calebbuffa. Left minor comments

**Comment by carmocca** [comment]
Since this didn't happen before 2.0, closing as we don't want to do this post 2.0
