### ISSUE TITLE
Missing weight params when loading deepspeed-stage2 ckpts

### ISSUE THREAD

**Issue by Atharva-Phatak** [Lightning-AI/lightning#10964]
## 🐛 Bug

Converting deepspeed_zero_stage_2 to fp32 misses some parameters. I was finetuning bart-large using deepspeed_stage_2. I converted to fp32 checkpoints(using zero_to_fp32.py) and got a .bin file. 

When I try to load this model using model.load_state_dict(path_to_bin_file) I get the following keys missing error. 
"model.embed.tokens.weight" ? 

I am using huggingface transformers.

### Environment

- PyTorch Lightning Version :1.5.0
- PyTorch Version : 1.10
- Python version : 3.10
- OS : Linux
- CUDA/cuDNN version:
- GPU models and configuration: V100 (16G Single)
- How you installed PyTorch (`conda`, `pip`, source): pip
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

cc @awaelchli @ananthsub @ninginthecloud @rohitgr7 @otaj @SeanNaren @akihironitta

**Comment by rohitgr7** [comment]
not 100% sure here but can you try loading `path_to_bin_file` and checking the keys for it?
is there something `<YourLitModel>.model.embed.tokens.weight` inside it?

**Comment by Atharva-Phatak** [comment]
Nope did that this weight parameter is actually missing. The lit model itself does not load and throws that error.

**Comment by rohitgr7** [comment]
can you share a reproducible example? like some sort of minimal version. I'll have a look.

**Comment by SeanNaren** [comment]
Could you try using our custom utility function on your saved path instead of the zero_to_fp32.py script?

https://pytorch-lightning.readthedocs.io/en/latest/advanced/advanced_gpu.html#collating-single-file-checkpoint-for-deepspeed-zero-stage-3

**Comment by TianHongZXY** [comment]
@xwwwwww Hello, I have the exact same issue when using deepspeed stage2 to train T5. I try to use the zero_to_fp32.py to create pytorch_model.bin and then load it, but it seems that parameters are not loaded at all, have you solved the problem?

**Comment by xwwwwww** [comment]
@TianHongZXY I find that `transformers` would automatically assign these shared weights to the corresponding parameters. You can just set `strict=False` when loading checkpoints.

**Comment by SeanNaren** [comment]
make sure also to use the utility function, not the zero_to_fp32.py that comes with it: https://pytorch-lightning.readthedocs.io/en/latest/advanced/advanced_gpu.html#collating-single-file-checkpoint-for-deepspeed-zero-stage-3

**Comment by TianHongZXY** [comment]
@SeanNaren That works, thank you! But I found there's another bug that when using deepspeed stage2 to train a `T5ConditionalForGeneration` model from transformers, follow the steps you mention above and load the checkpoint into a `state_dict`, two keys `model.encoder.embed_tokens.weight` and `model.decoder.embed_tokens.weight` are lost, which should point to the same value `state_dict[model.shared.weight]`, I'm not sure if it is a bug from pytorch-lightning or deepspeed.

**Comment by ShaneTian** [comment]
> make sure also to use the utility function, not the zero_to_fp32.py that comes with it: https://pytorch-lightning.readthedocs.io/en/latest/advanced/advanced_gpu.html#collating-single-file-checkpoint-for-deepspeed-zero-stage-3

This page does not exist yet.

**Comment by rohitgr7** [comment]
here is the updated page: https://pytorch-lightning.readthedocs.io/en/latest/advanced/model_parallel.html#collating-single-file-checkpoint-for-deepspeed-zero-stage-3

you can search the heading too in the search bar to get the updated link: `collating-single-file-checkpoint-for-deepspeed-zero-stage-3`

**Comment by oscmansan** [comment]
For some reason, `deepspeed.utils.zero_to_fp32.get_fp32_state_dict_from_zero_checkpoint` used in `pytorch_lightning.utilities.deepspeed.convert_zero_checkpoint_to_fp32_state_dict` returns a subset of the model parameters in the state_dict. I solved it by loading the checkpoint in `.../checkpoint/mp_rank_00_model_states.pt` (for ZeRO Stage 2) and adding the following to the `LightningModule`:

```python
def on_load_checkpoint(self, checkpoint):
    state_dict = checkpoint['module']
    state_dict = {k.partition('module.')[2]: state_dict[k] for k in state_dict.keys()}
    checkpoint['state_dict'] = state_dict
```

**Comment by TianHongZXY** [comment]
> For some reason, `deepspeed.utils.zero_to_fp32.get_fp32_state_dict_from_zero_checkpoint` used in `pytorch_lightning.utilities.deepspeed.convert_zero_checkpoint_to_fp32_state_dict` returns a subset of the model parameters in the state_dict. I solved it by loading the checkpoint in `.../checkpoint/mp_rank_00_model_states.pt` (for ZeRO Stage 2) and adding the following to the `LightningModule`:
> 
> ```python
> def on_load_checkpoint(self, checkpoint):
>     state_dict = checkpoint['module']
>     state_dict = {k.partition('module.')[2]: state_dict[k] for k in state_dict.keys()}
>     checkpoint['state_dict'] = state_dict
> ```

@oscmansan  Did you solve the problem that embed_token_weight is lost by this?

**Comment by rohitgr7** [comment]
can anyone share a reproducible script to check this issue? I can investigate what's going on in here.

**Comment by Mogreine** [comment]
Have exactly the same issue when pretraining [DeBERTa](https://huggingface.co/docs/transformers/model_doc/deberta#transformers.DebertaForMaskedLM). Use [lightning function](https://pytorch-lightning.readthedocs.io/en/latest/advanced/model_parallel.html#collating-single-file-checkpoint-for-deepspeed-zero-stage-3) for checkpoints merging. When loading lightning module get the following error:
`Missing key(s) in state_dict: "model.cls.predictions.decoder.weight", "model.cls.predictions.decoder.bias".`

**Comment by austinformbio** [comment]
Same here. Error when loading reconstructed checkpoint .pt file, using a BERT model. 
Missing key(s) in state_dict: "model.cls.predictions.decoder.weight", "model.cls.predictions.decoder.bias".

**Comment by davidavdav** [comment]
I have the same issue with a `strategy="deepspeed_stage_3_offload"` saved checkpoint, revived with [this script](https://pytorch-lightning.readthedocs.io/en/latest/advanced/model_parallel.html#collating-single-file-checkpoint-for-deepspeed-zero-stage-3), 
```
RuntimeError: Error(s) in loading state_dict for Whisper:
        Missing key(s) in state_dict: "model.proj_out.weight". 
```
This is a [Whisper](https://huggingface.co/docs/transformers/v4.25.1/en/model_doc/whisper#transformers.WhisperForConditionalGeneration) model. 

I think the issue can be opened again
