### ISSUE TITLE
Property `TPUSpawnPlugin.tpu_global_core_rank` may be replaced by global rank property

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#10986]
## Proposed refactor

Deprecate `tpu_global_core_rank` in favor of `global_rank`.

### Pitch

It "looks" like tpu_global_core_rank in the TPUPlugin is just another name for what is known as the global rank. After #10896 we should investigate whether the two are equivalent and revert back to using the unified global_rank property exclusively. 

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda @kaushikb11 @rohitgr7 @justusschock @awaelchli @akihironitta @tchaton

**Comment by kaushikb11** [comment]
Yup, let's go ahead with the deprecation!

**Comment by kaushikb11** [comment]
Currently blocked by #11330
