### ISSUE TITLE
Custom ClusterEnvironment breaks even after defining `master_address` and `master_port` abstract methods.

### ISSUE THREAD

**Issue by kaushikb11** [Lightning-AI/lightning#11025]
### To Reproduce

In https://github.com/PyTorchLightning/pytorch-lightning/pull/10103, we have renamed `master_{port/address}` to `main_{port/address}`. We have followed the deprecation cycle as well, but this breaks the code as `main_{port/address}` are abstract methods. Not a desired behavior.

```python
TypeError: Can't instantiate abstract class CustomClusterEnvironment with abstract methods main_address, main_port
```

### Expected behavior

If `master_{port/address}` is defined, show the deprecation warnings but don't raise the error.

### Environment

- PyTorch Lightning Version (e.g., 1.5.0):
- PyTorch Version (e.g., 1.10):
- Python version (e.g., 3.9):
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

cc @tchaton @rohitgr7 @awaelchli @ananthsub

**Comment by awaelchli** [comment]
Yes, as I noted in the PR:

> Yes. User with custom cluster environment plugins won't be able to instantiate their existing plugins due to the requirement of main_port, main_address to be abstract. They will have to rename master_port and master_address methods immediately.

The renaming was not included in any release, so we can still make adjustments if we need to. There is the option to remove the abstract requirement and re-introduce it when the deprecation cycle ends.

**Comment by awaelchli** [comment]
@kaushikb11 we are now already removing the old methods and completing the deprecation cycle in #13458. Sorry we couldn't discuss more or do something here, but I think it wasn't really a major issue for any of the few users that did use the custom environments.
