### ISSUE TITLE
`Trainer#tune`/`scale_batch_size` with mode="binsearch" does not work properly

### ISSUE THREAD

**Issue by cschell** [Lightning-AI/lightning#11299]
## 🐛 Bug

`Trainer#tune`/`scale_batch_size` with the "binsearch" option does not seem to work properly.

### To Reproduce

```python
import pytorch_lightning as pl
import torch.nn
from torch.utils.data import DataLoader


class LightningModel(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.model = torch.nn.Sequential(
                torch.nn.Linear(1000, 5000),
                torch.nn.Linear(5000, 5000),
                torch.nn.Linear(5000, 1)
        )

    def training_step(self, X):
        h = self.model(X)
        loss = torch.nn.functional.mse_loss(h, torch.ones_like(h))

        return loss

    def configure_optimizers(self):
        return torch.optim.Adam(self.model.parameters())

class Datamodule(pl.LightningDataModule):
    def __init__(self):
        super().__init__()
        self.batch_size = 1

    def train_dataloader(self):
        return DataLoader(torch.zeros(10_00_000, 1000), batch_size=self.batch_size, num_workers=2)


trainer = pl.Trainer(auto_scale_batch_size=True, gpus=[1])

datamodule = Datamodule()
trainer.tune(model=LightningModel(), datamodule=datamodule, scale_batch_size_kwargs={"init_val": 20000, "mode": "binsearch"})
```

### Expected behavior

1. `trainer.tune` increases batch size, until it hits the GPU's limit - as you can see in the console output I've added below, this works: a batch size of 80,000 succeeded, but the next larger step, 160,000, did not
2. the algorithm then uses binary search to find the optimal batch size - this apparently does not work: the algorithm goes all the way back down to 80,000. I would expect the final batch size to be somewhere in between 80,000 and 160,000

I can reproduce this behaviour with different model sizes, it's always the same: the result of the binary search is always the last succeeding batch size of the first step.

### Environment
* CUDA:
        - GPU:
                - NVIDIA GeForce RTX 2080 Ti
                - NVIDIA GeForce RTX 2070 SUPER
        - available:         True
        - version:           10.2
* Packages:
        - numpy:             1.21.5
        - pyTorch_debug:     False
        - pyTorch_version:   1.10.1+cu102
        - pytorch-lightning: 1.5.7
        - tqdm:              4.62.3
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.10
        - version:           102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021

### Additional context

Example output of the provided code:

```
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Batch size 20000 succeeded, trying batch size 40000
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Batch size 40000 succeeded, trying batch size 80000
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Batch size 80000 succeeded, trying batch size 160000
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Batch size 160000 failed, trying batch size 120000
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Batch size 120000 failed, trying batch size 100000
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Batch size 100000 failed, trying batch size 90000
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Batch size 90000 failed, trying batch size 85000
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Batch size 85000 failed, trying batch size 82500
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Batch size 82500 failed, trying batch size 81250
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Batch size 81250 failed, trying batch size 80625
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Batch size 80625 failed, trying batch size 80312
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Batch size 80312 failed, trying batch size 80156
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Batch size 80156 failed, trying batch size 80078
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Batch size 80078 failed, trying batch size 80039
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Batch size 80039 failed, trying batch size 80019
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Batch size 80019 failed, trying batch size 80009
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Batch size 80009 failed, trying batch size 80004
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Batch size 80004 failed, trying batch size 80002
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Batch size 80002 failed, trying batch size 80001
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Batch size 80001 failed, trying batch size 80000
Finished batch size finder, will continue with full run using batch size 80000
```

cc @tchaton @rohitgr7 @akihironitta @borda

**Comment by tchaton** [comment]
Dear @cschell,

Can you try to manually use `80001`?

From the binary search, it seems to me 80000 is the largest working batch size. 80001 would fail as indicated there

`Batch size 80001 failed, trying batch size 80000`.

**Comment by cschell** [comment]
80,001 works fine, also 90,000 works fine, but some the binary search stage doesn't get a positive response. Also, if you set `init_val` to something that's too high (like 160000 in my example scenario), the binary search start immediately (as it should) and then goes all the way down to a batch size of 1.

**Comment by rohitgr7** [comment]
there must be some issue then.. will have a look.

**Comment by mkirchler** [comment]
As of version 1.5.10 this bug is still there. It's especially problematic when the `init_val` is set to something higher than fits into memory, since then it just iterates down to a batch size of 1. If not, it's equivalent to a very inefficient version of the `power` option (as cschell mentioned). If there are no immediate plans to fix the bug, maybe it'd help to at least throw a warning (that would have saved at least me some time :))
