### ISSUE TITLE
Fix typing for Logger files

### ISSUE THREAD

**Issue by daniellepintz** [Lightning-AI/lightning#11370]
## Proposed refactor

Fix typing for these files:
https://github.com/PyTorchLightning/pytorch-lightning/blob/7eab379da2fdca542849ed4ad313d0851c2271e3/pyproject.toml#L61-L68

### Motivation

As part of #7037 we want to add typing to the entire Lightning codebase.

## Additional Context
Make sure you do one PR per file.
Start by removing the file from `pyproject.toml`. To test mypy locally make sure you have it installed and then simply run `mypy`.

cc @borda @justusschock @awaelchli @akihironitta @rohitgr7 @edward-io @ananthsub @kamil-kaczmarek @Raalsky @Blaizzy

**Comment by learn2phoenix** [comment]
Could I take this?

**Comment by daniellepintz** [comment]
Yup go for it! Just assigned it to you :)

**Comment by daniellepintz** [comment]
@learn2phoenix are you still planning to work on this issue?

**Comment by learn2phoenix** [comment]
@daniellepintz Sorry, have been ultra busy. I will push the PR this weekend.

**Comment by daniellepintz** [comment]
No worries! Just checking in. If you do, please do one PR per file :)

**Comment by learn2phoenix** [comment]
some of these files have name conflicts with library names or other modules. Would changing the names of these `loggers/*` files be an acceptable solution? If so, is there any specific naming convention that needs to be used or would something like `<current_name>_log.py` be ok?

**Comment by learn2phoenix** [comment]
yes, they do show up like the following:
`wandb.py: error: Source file found twice under different module names: "pytorch_lightning.loggers.wandb" and "wandb"`

Also, `mypy` reports the stubs to be missing for some modules like `torch_xla`, `comet_ml` and says that they wouldn't be analyzed. Are we ignoring these errors?

**Comment by daniellepintz** [comment]
I see! @awaelchli wdyt?

**Comment by awaelchli** [comment]
This was completed as part of #13445
