### ISSUE TITLE
Warn when running an infinite epoch and overriding "epoch end" accumulating hooks

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lightning#11554]
## 🚀 Feature

When the user configures `Trainer(max_steps=-1, max_epochs=-1)` an endless epoch runs, so overriding `training_epoch_end` or `validation_epoch_end` with `val_check_interval==float` can be a problem because they will keep outputs in memory indefinitely.

### Motivation

Many users are not aware of the impact of overriding these hooks so infinite epochs open the door to "memory leaks".

### Pitch

Raise a warning in this case informing the user of this behaviour.

### Additional context

Proposed in https://github.com/PyTorchLightning/pytorch-lightning/issues/11480#issuecomment-1014594779

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda @carmocca @awaelchli @ninginthecloud @daniellepintz @rohitgr7 @justusschock @kaushikb11

**Comment by VedPatwardhan** [comment]
I'd like to work on this, could you assign this issue to me?

**Comment by tchaton** [comment]
Hey @VedPatwardhan,

Yes, go on !

**Comment by akihironitta** [comment]
@carmocca I was thinking it also applies to the case of only `max_steps=-1` being specified because it means an endless epoch, right?

**Comment by VedPatwardhan** [comment]
I had a doubt while writing a test for the change being made. In the `test_config_validator.py` file, inside the `test_fit_val_loop_config` function, if a warning is created, then the `BoringModel` class is instantiated, could you please guide me what that class is all about, and do I need to instantiate the `BoringModel` class for the warning generated too? Also, what other properties of the model do I need to change before calling `trainer.fit(model)`?
Thanks in advance.

**Comment by ananthsub** [comment]
Here's one suggestion to test.
- Create a new class that extends the BoringModel and implements the `training_epoch_end`.
- Construct a Trainer which has settings configured for infinite training. 
- Call `trainer.fit` and confirm that you see a warning emitted from the configuration validator

You can follow the pattern for the `validation_epoch_end` and `val_check_interval==float` scenario described in the issue too.

**Comment by VedPatwardhan** [comment]
Okay, I'll do that.

**Comment by VedPatwardhan** [comment]
@ananthsub could you please help me understand what's going wrong? I think I've made the change, but many of the tests are failing.
