### ISSUE TITLE
Issues in the LightningModule animation

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/lightning#11661]
## 📚 Documentation

I love the `LightningModule` animation at https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_module.html

But I think there are two issues 

## 1 

I think this should be `nn.Module` not `pl.Module`

![Screen Shot 2022-01-29 at 9 11 28 AM](https://user-images.githubusercontent.com/5618407/151668987-90eae5c1-f3c8-4647-85b0-7172238cd48b.png)

## 2

And I think this should be `classifier` not `model`

![Screen Shot 2022-01-29 at 9 19 50 AM](https://user-images.githubusercontent.com/5618407/151668966-37eccba3-db6a-4766-b5df-62cdb435ce6b.png)

cc @borda @rohitgr7

**Comment by ananthsub** [comment]
Similar issues were raised here: https://github.com/PyTorchLightning/pytorch-lightning/issues/11241

**Comment by rohitgr7** [comment]
I'll ask Eden if she has the draft version of it to get this fixed.

**Comment by rasbt** [comment]
Oh yeah, seems related to #11241 . We can close this one, but we should then mention the `pl.Module` issue in the other Issue because it's probably more efficient to get those two fixed at the same time.

**Comment by rohitgr7** [comment]
let's track this one since it covers both. maybe more. I'll review it with the updated API, once I get the draft.

**Comment by rasbt** [comment]
Just commenting so that this doesn't get closed. I think it's something we want to fix :)

**Comment by awaelchli** [comment]
It looks like this is resolved, the animation is not there anymore. There is an updated one now on this 
page with the new syntax: https://lightning.ai/docs/pytorch/stable/starter/introduction.html
