### ISSUE TITLE
Rename `finalize` to `teardown` in Logger API

### ISSUE THREAD

**Issue by daniellepintz** [Lightning-AI/lightning#11677]
## Proposed refactor

Rename `finalize` to `teardown` in Logger API:
https://github.com/PyTorchLightning/pytorch-lightning/blob/86b177ebe5427725b35fde1a8808a7b59b8a277a/pytorch_lightning/loggers/base.py#L319-L325

### Motivation

`teardown` is the name we use in other classes in Lightning for the purpose of doing any final processing/cleanup.

Similar to https://github.com/PyTorchLightning/pytorch-lightning/pull/10939

This was discussed in https://github.com/PyTorchLightning/pytorch-lightning/discussions/9004#discussioncomment-1213727

cc @justusschock @awaelchli @akihironitta @rohitgr7 @edward-io @borda @ananthsub @kamil-kaczmarek @Raalsky @Blaizzy @tchaton

**Comment by ananthsub** [comment]
These have different semantics today. `finalize` accepts success/failure, while `teardown` accepts the stage (ie `fit` `validate` `test` `predict`), but does not give an indication about success/failure. How do you plan to bridge this?

**Comment by daniellepintz** [comment]
Hmm good point. Maybe it doesn't make sense to do this issue?

**Comment by carmocca** [comment]
Closing as there's no clear proposal
