### ISSUE TITLE
Use W&B Dataset and Model Artifacts in Experiments with `WandbLogger`

### ISSUE THREAD

**Issue by AjinkyaIndulkar** [Lightning-AI/lightning#11769]
## 🚀 Feature

Allow experiments with `WandbLogger` to use `wandb.Artifact` for using/downloading datasets or model checkpoints.

### Motivation

The current implementation of `pytorch_lightning.loggers.wandb.WandbLogger` does not include usage of `wandb.Artifact` to use/download dataset or model checkpoint artifact when running an experiment on Weights & Biases. This limits the ability of an experiment to use other features of Weights & Biases, dataset versioning in this case. Additionally, the documentation includes a section about downloading a model checkpoint from W&B artifacts but it is done before an experiment.

### Pitch

Currently, the only way to do this is to create a new Logger class which inherits from `WandbLogger` and initialises a dataset/model `wandb.Artifact` object after `WandbLogger` starts a new W&B Run. As a starting point, `WandbLogger` can be updated to use a dataset/model artifact when a W&B Run is initialised inside `WandbLogger`.

cc @borda @awaelchli @morganmcg1 @AyushExel @borisdayma @scottire @manangoel99

**Comment by AjinkyaIndulkar** [comment]
I'm happy to contribute towards this but I would like to finalise the scope of implementation before I can start any work to create a PR.

**Comment by awaelchli** [comment]
Hello
Adding that feature would be great. Which additions or changes to the WandbLogger API do you see are needed? Can we download the artifacts in `WandbLogger.__init__`? 

Alternatively, would a callback make more sense perhaps? Artifact management is a bit on the edge of the responsibilities of a logger in my opinion.

**Comment by AjinkyaIndulkar** [comment]
> Hello Adding that feature would be great. Which additions or changes to the WandbLogger API do you see are needed? Can we download the artifacts in `WandbLogger.__init__`?

Hi @awaelchli, my initial plan was to just use an artifact. Adding the feature to download artifacts shouldn't be too difficult. We can add it to the PR as well.

> Alternatively, would a callback make more sense perhaps? Artifact management is a bit on the edge of the responsibilities of a logger in my opinion.

Hmm... You are right. A callback indeed makes more sense here. We can also add the functionality to log artifacts on W&B via this new callback class. I just see one hiccup which I am not sure if it's a trivial implementation. Is it possible to reuse the `Run` object (`experiment`) created by `WandbLogger` for this new callback?

**Comment by manangoel99** [comment]
Hi @AjinkyaIndulkar ! Manan here from Weights & Biases, thanks for creating this issue. We actually thought that maybe instead of a new callback, for loading model checkpoints from artifacts we make an an addition to `pytorch_lightning.utilities.cloud_io.load` such that it automatically fetches the artifact and loads the state_dict from that when the path to the artifact is provided. 
This would be quite similar to how models are fetched from S3 which have `s3://` as the URL prefix. The prefix in our case would be "wandb-artifact://" and the new snippet would be to check if the URL possesses this prefix and fetch the artifact from wandb if it does.
I would love to get your thoughts on this @AjinkyaIndulkar @awaelchli and it would be awesome if we could collaborate on this.

**Comment by AjinkyaIndulkar** [comment]
hey @manangoel99!

That's cool idea! I still second the idea of creating a callback class for the W&B artifacts related operations. The class should include both dataset and model artifacts in my opinion.

I'd be happy to collaborate on this.

**Comment by manangoel99** [comment]
As @awaelchli mentioned, we too would like to keep artifacts outside the `WandbLogger`. Could you elaborate on how creating new callbacks would work?

**Comment by AjinkyaIndulkar** [comment]
sure. The core idea is to reuse the `wandb.Run` instance, `experiment`, from WandbLogger, otherwise we lose the dataset/model versioning element of the experiment. This idea is quite easily to implement within WandbLogger but since we are creating a new callback, I'm a bit unclear how we share the experiment property. My best guess is using the `trainer` instance in the `setup` method.

My first draft of how the callback could operate:

-   sample callback initialisation for dataset artifact:
    ```
    dataset_artifact_callback = WandbArtifacts(
        name="test_dataset:v0",
        type="dataset",
        aliases=None,
        use_as=None,
        download=None,
        **kwargs
    )
    ```

-   sample callback initialisation for model artifact:
    ```
    model_artifact_callback = WandbArtifacts(
      name="test_model:v0", type="model", aliases=None, use_as=None, download=None, **kwargs
    )
    ```
  
We could use `kwargs` to pass arguments for `wandb.Artifact.download()` method.

**Comment by manangoel99** [comment]
Interesting approach, but if a callback is used, it would tie the artifact loading to the `Run` object. However, wandb provides an interface to load artifacts from projects without creating a `Run`.  I think maybe keeping artifact loading independent of an ongoing run might be a better idea.
Wrapping all the artifact functionality in a single class makes a lot of sense but maybe instead of making it a callback, we could keep it independent of the trainer.

**Comment by AjinkyaIndulkar** [comment]
Yup. we can load artifacts without creating a `Run` but will the experiments show which artifacts were used?

I want to mainly integrate `.use_artifact()` with PL. Downloading artifacts is actually optional in my mind. If there are other ways to share W&B context of `WandbLogger` with this new callback that I have missed, please let me know.

**Comment by borisdayma** [comment]
Would calling `wandb_logger.experiment.use_artifact(args)` be sufficient for your use case?

**Comment by borisdayma** [comment]
In that case maybe there is no need to add anything else for the logger as it is already feasible, no?

**Comment by AjinkyaIndulkar** [comment]
for the scope of this issue, I say yes. Both options are good but I guess creating a new callback class will allow more features, which will be out of scope for `WandbLogger`, to be added in the future.

I leave the final decision to you. 😅

**Comment by manangoel99** [comment]
@carmocca can you close this in favour of #12764
