### ISSUE TITLE
Move `_*_AVAILABLE` checks to their respective files.

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lightning#11826]
## Proposed refactor

Move all the variables defined here that are only used in one file
https://github.com/PyTorchLightning/pytorch-lightning/blob/1e36cffbca3f92855d82907370544fade1656da6/pytorch_lightning/utilities/imports.py#L98-L134
to their respective files.

### Motivation

This encapsulates code and avoids clutter from the utilities.

### Pitch

Move:

https://github.com/Lightning-AI/lightning/blob/50fd12f841bc10ec093e80d0acf3e3b51cd927fe/src/pytorch_lightning/utilities/imports.py#L28-L51

To the files that use them.

The rest I don't think should be moved.
______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda

**Comment by Borda** [comment]
@carmocca could you elaborate more on why this is needed?
I would say having import change in one place makes it easier to find and this `imports` is a primitive without any dependency so there is no risk of cyclic imports compared to your proposal...

**Comment by carmocca** [comment]
My point is that if one of these primitives is used in only one file, then it should be defined there. For example `_JSONARGPARSE_AVAILABLE` is only used the CLI:

```python
$ grep -iIRn "_JSONARGPARSE_AVAILABLE" pytorch_lightning/
pytorch_lightning//utilities/__init__.py:44:    _JSONARGPARSE_AVAILABLE,
pytorch_lightning//utilities/imports.py:108:_JSONARGPARSE_AVAILABLE = _package_available("jsonargparse") and _compare_version("jsonargparse", operator.ge, "4.0.0")
pytorch_lightning//utilities/cli.py:32:from pytorch_lightning.utilities.imports import _JSONARGPARSE_AVAILABLE
pytorch_lightning//utilities/cli.py:37:if _JSONARGPARSE_AVAILABLE:
pytorch_lightning//utilities/cli.py:131:        if not _JSONARGPARSE_AVAILABLE
```

Moving it means we contain all the CLI-related logic into a single place instead of leaving "breadcrumbs" in our utilities. The utilities module is slowly becoming a "dumping ground" for random pieces of code when some of those pieces actually have a logical place to be.

Also, as a naive user, I would first look for this in the LightningCLI code than in a generic utility module.

The same argument can be applied to the other variables mentioned in the top post.

**Comment by mikcnt** [comment]
Hey there! Can I work on this?

**Comment by carmocca** [comment]
Yes of course. You can pick any of these and start chipping away. The linked "Merged" PRs here can be examples if you'd like some guidance

**Comment by shenoynikhil** [comment]
@carmocca You can strike off `_TPU_AVAILABLE` I guess from this list. And `_XLA_AVAILABLE` seems to be fixed too.

**Comment by carmocca** [comment]
Thanks! Here's the leftovers: https://github.com/Lightning-AI/lightning/blob/50fd12f841bc10ec093e80d0acf3e3b51cd927fe/src/pytorch_lightning/utilities/imports.py#L28-L51

**Comment by heytanay** [comment]
Hi @carmocca, can I work on the leftovers?

**Comment by carmocca** [comment]
Yes of course
