### ISSUE TITLE
Support tracing different methods with `to_torchscript`

### ISSUE THREAD

**Issue by rohitgr7** [Lightning-AI/lightning#11821]
## 🚀 Feature

`torch.jit.trace` supports tracing individual methods. We can extend this support for user inside `to_torchscript(method='trace')`.
https://github.com/pytorch/pytorch/blob/bf233aa049c4b479fd6cb19f9b8672bb2d42b0e2/torch/jit/_trace.py#L638-L643

### Motivation

https://github.com/PyTorchLightning/pytorch-lightning/pull/11428#discussion_r788470309

### Pitch

```py
def to_torchscript(..., func='predict_step')  # default will be None -> forward
    ...
```
or
```py
def to_torchscript(..., func=self.predict_step)
```

### Alternatives

Let user override the complete method to support this if they need.

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda @carmocca @justusschock @awaelchli @ananthsub @ninginthecloud @jjenniferdai @rohitgr7

**Comment by awaelchli** [comment]
TorchScript is no longer being developed, so I'm closing the feature request.
