### ISSUE TITLE
Support loading jit checkpoints

### ISSUE THREAD

**Issue by rohitgr7** [Lightning-AI/lightning#11820]
## 🚀 Feature

Support loading jitted checkpoints using `LightningModule.load_from_checkpoint` API.
https://github.com/PyTorchLightning/pytorch-lightning/pull/11428#discussion_r788470858

### Motivation

I think since this is possible, there is no-harm if we can support that since jitted checkpoints contain the weights and can be loaded like this:

```pt
model = LitModel(...)
traced = model.to_torchscript(method='script')
model.load_state_dict(traced.state_dict())
```

### Pitch

We can simply load the checkpoint using `torch.jit.load`, but one issue is how do we determine whether the checkpoint provided is a normal checkpoint or jitted one.

This is how pytorch does it:
https://github.com/pytorch/pytorch/blob/bf233aa049c4b479fd6cb19f9b8672bb2d42b0e2/torch/serialization.py#L699-L711

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda @awaelchli @ananthsub @ninginthecloud @rohitgr7

**Comment by awaelchli** [comment]
TorchScript is no longer being developed, so I'm closing the feature request.
