### ISSUE TITLE
[RFC] Move DataLoader ownership to the Loops.

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lightning#11845]
## Proposed refactor

The highest-level loops - `FitLoop`, `EvaluationLoop`, and `PredictLoop` - already own the data fetching and iterators, the latter two also subclassing `DataLoaderLoop`. It makes sense they would also own the dataloader themselves.

This would reduce clutter from the `Trainer` and circular references like:

`trainer._run_evaluate` -> `trainer._evaluation_loop._reload_evaluation_dataloaders` -> `loop.trainer.reset_test_dataloader`

This would improve the customization experience and make it more powerful.

We would keep proxy properties in the `Trainer` for backwards compatibility.

### Motivation

The data connector and trainer data components are due for a cleanup. Customization is really difficult since neither of the components can be easily modified. Loops are a great vehicle for this.

This should be able to greatly reduce both components, as the dataloader structure would now be mirrored by the available loops themselves.

### Pitch

- The appropriate loops have a `self.dataloader` attribute.
  - `Trainer.train_dataloader` -> `FitLoop.dataloaders`
  - `Trainer.{val,test}_dataloaders` -> `EvaluationLoop.dataloaders`
  - `Trainer.predict_dataloaders` -> `PredictLoop.dataloaders`
- `Trainer.reset_*_dataloader` methods are moved off the Trainer to a `loop.reset_dataloader` method.
- Functional utilities are used inside the loops.
- We would also want to move properties like `trainer.num_*_batches`

No changes are required to the base `Loop` API. This refactor is similar to the one done in #11621 
______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @justusschock @awaelchli @akihironitta @rohitgr7 @ninginthecloud @carmocca @ananthsub

**Comment by justusschock** [comment]
I like that a lot!

Just one note:

> We would keep proxy properties in the Trainer for backwards compatibility.

I think that we should never remove that. This is not only for backwards compatibility, but for quite a lot of cases, you need to access them (e.g. to compute their length or whatever) and having to go to the loops might not be intuitive from the user perspective (even though for us it would be the logic place to look at).

**Comment by carmocca** [comment]
Yes, I'm not advocating for deprecation, just saying that we would keep

```python
@property
def train_dataloader():
    return self.fit_loop.dataloaders
```
