### ISSUE TITLE
Test AMP and Apex checkpointing

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#11885]
## 🚀 Feature

We currently don't have any tests that the amp/apex states (i.e. scaler) are saved and restored correctly (I couldn't find any such tests). 

### Motivation

PRs like https://github.com/PyTorchLightning/pytorch-lightning/pull/11638 which change the loading and saving behavior risk introducing bugs, especially when complicated logic is involved to remain backward compatible. 

### Pitch

Add tests.

### Alternatives

None

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @awaelchli @ananthsub @ninginthecloud @rohitgr7 @borda @akihironitta @carmocca @justusschock

**Comment by Borda** [comment]
I think it is quite an important extension to our legacy checkpoint testing... #11403

**Comment by awaelchli** [comment]
Since the apex plugin is the only one dumping state in checkpoints, we would probably close this one if we decide to move forward with #14416

**Comment by akihironitta** [comment]
Given the comment https://github.com/Lightning-AI/lightning/issues/14416#issuecomment-1231138294, shall we close this issue?

**Comment by awaelchli** [comment]
Yes!
