### ISSUE TITLE
Rename `profiler/` directory to `profilers/`

### ISSUE THREAD

**Issue by daniellepintz** [Lightning-AI/lightning#11972]
## Proposed refactor

Rename `profiler/` directory to `profilers/`

### Motivation

The other directory names are plural, like `callbacks/`, `strategies/`, `accelerators/`- let's do the same for profilers. Part of https://github.com/PyTorchLightning/pytorch-lightning/issues/11908

cc @borda @justusschock @awaelchli @rohitgr7 @carmocca @kaushikb11 @ninginthecloud

**Comment by Pragyanstha** [comment]
Hi ! I would love to work on this issue if it is available

**Comment by daniellepintz** [comment]
Awesome, thanks! Assigned you the issue

**Comment by Pragyanstha** [comment]
@daniellepintz 
I have a question.
From what I understand, since this change would be backward incompatible, what is the recommended way to give deprecated warning for ```pytorch_lightning.profiler``` API ?

**Comment by akihironitta** [comment]
Hi @Pragyanstha, it'll look almost the same as `pytorch_lightning.plugins.training_type.*` (which reroutes to `pytorch_lightning.strategies.*`).

https://github.com/PyTorchLightning/pytorch-lightning/blob/6bc0e1da6329c42ec3b7c6fbf91eb059b9124207/pytorch_lightning/plugins/training_type/ddp.py#L18-L23

**Comment by Pragyanstha** [comment]
@akihironitta 
Ah I see, so we keep the profiler directory and do the same. Thanks !

**Comment by bonysureliya** [comment]
Hello i would love to work on the issue.
