### ISSUE TITLE
Update PL ecosystem libraries to the stable Accelerator/Strategy API

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#12026]
## Proposed refactor

Create an issue and send a PR to repositories that depend on the outdated "TrainingTypePlugin" API and update them to the stable Accelerator/Strategy API.

### Motivation

As we are releasing an updated, stable API for Strategy (formerly known as TrainingTypePlugin) with Lightning 1.6 we want to ensure that we notify and support the community about the changes. A smooth transition will ensure that early adopters can profit from the improvements the new API brings. Since the API in some strategies has changed dramatically, we can offer some help.

### Candidates
- [ray_lightning](https://github.com/ray-project/ray_lightning#pytorch-lightning-compatibility)

### Additional context

#9932 #10416
______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @justusschock @awaelchli @rohitgr7 @akihironitta

**Comment by Borda** [comment]
I think it is related to EcoCI feature request: https://github.com/PyTorchLightning/ecosystem-ci/issues/24

**Comment by ChickenTarm** [comment]
Hi, is this still being worked on?

**Comment by ChickenTarm** [comment]
Sure I can give it a shot. Is there a good source to start with for this: what are the required aspects of a strategy, changes made between 1.6 and 1.7+ for the strategy api, etc?

**Comment by awaelchli** [comment]
@ChickenTarm This is an old ticket that I created a year ago and it got forgotten, sorry! The main motivation was to update the apis used over in ray lightning. There are some overrides for Accelerator, Launcher, and Strategy here: https://github.com/ray-project/ray_lightning/tree/main/ray_lightning
These would have to be updated with the latest imports and apis, but the work would be done completely outside Lightning in this repo.
