### ISSUE TITLE
The name property of wandb and comet return project_name, while other loggers like mlflow, neptune, test_tube and tensorboard return run_name.

### ISSUE THREAD

**Issue by shenmishajing** [Lightning-AI/lightning#12157]
## 🐛 Bug

The name property of wandb logger return the project_name of current experiment.
https://github.com/PyTorchLightning/pytorch-lightning/blob/33fc3f1e117f007d317421c9921175dc84673d7e/pytorch_lightning/loggers/wandb.py#L442-L450

But, other loggers like mlflow, nepture, test_tube and tensorboard, return the run_name of current experiment.
https://github.com/PyTorchLightning/pytorch-lightning/blob/33fc3f1e117f007d317421c9921175dc84673d7e/pytorch_lightning/loggers/mlflow.py#L248-L255
https://github.com/PyTorchLightning/pytorch-lightning/blob/33fc3f1e117f007d317421c9921175dc84673d7e/pytorch_lightning/loggers/neptune.py#L607-L610
https://github.com/PyTorchLightning/pytorch-lightning/blob/33fc3f1e117f007d317421c9921175dc84673d7e/pytorch_lightning/loggers/test_tube.py#L215-L225

### Expected behavior

name property of wandb logger return the run_name.
code will look like:
```python
    @property
    def name(self) -> Optional[str]:
        """Gets the name of the experiment.

        Returns:
            The name of the experiment if the experiment exists else the name given to the constructor.
        """
        # don't create an experiment if we don't have one
        return self._experiment.name if self._experiment else self._name
```

cc @awaelchli @morganmcg1 @AyushExel @borisdayma @scottire @manangoel99

**Comment by manangoel99** [comment]
Hi @shenmishajing ! I am an engineer at Weights & Biases. Thank you for bringing this to our attention!
