### ISSUE TITLE
[RFC] Where to save checkpoints and profiler output in case of multiple loggers?

### ISSUE THREAD

**Issue by daniellepintz** [Lightning-AI/lightning#12177]
### Background 
Currently, in the case that the user does not specify a `dirpath` to `ModelCheckpoint` or a `dirpath` to the `Profiler`, we write our output to the Logger, when there is exactly one Logger. However, in the case of multiple loggers we just write to `default_root_dir`.

The exact priority followed for one logger:
1. if a `dirpath` is provided, write to it
2. if not, write to the Logger

The exact priority followed for multiple loggers (or no loggers):
1. if a `dirpath` is provided, write to it
2. if not, write to `default_root_dir`

The purpose of this issue is to make sure everyone is aware of this behavior, and to see if there is a way to improve it.

### Discussion Questions
I'd like to discuss two questions here.
1. Can we confirm that this is the behavior we want for when we have one logger?
2. What behavior do we want for when we have multiple loggers? I see a few options:
    A. Write to `default_root_dir` (keep current behavior)
    B. Write to first logger in the list of loggers
    C. Write to all loggers in the list of loggers 

cc @borda @awaelchli @edward-io @ananthsub @rohitgr7 @kamil-kaczmarek @Raalsky @Blaizzy @ninginthecloud @otaj @carmocca @kaushikb11 @nbcsm @guotuofeng

**Comment by awaelchli** [comment]
> Can we confirm that this is the behavior we want for when we have one logger?

I can confirm. From my side it is clear this is a good default behavior and would prefer to keep it this way.


> What behavior do we want for when we have multiple loggers? I see a few option

**I vote for option B.** This gives the benefit of versioning. The default root dir does not get polluted and you don't have to "invent" a name for the folder. Option C is not practical IMO due to the duplication of large checkpoint files.

**Comment by daniellepintz** [comment]
Thanks @awaelchli for your input!! 

I like option B as well! I agree option C seems impractical.

**Comment by daniellepintz** [comment]
Would be great to get some more opinions @PyTorchLightning/core-lightning
