### ISSUE TITLE
Update Kaggle notebook for TPU training

### ISSUE THREAD

**Issue by akihironitta** [Lightning-AI/lightning#12350]
## 🚀 Feature
Update the kaggle notebook (https://www.kaggle.com/pytorchlightning/pytorch-on-tpu-with-pytorch-lightning) linked in our doc page (https://pytorch-lightning.readthedocs.io/en/latest/accelerators/tpu.html#kaggle-tpus).

### Motivation
The notebook seems outdated. It pins PL version at `1.1.8` and pytorch at `1.7`.

### Additional context
I saw a tweet saying the user is having difficulty in using PyTorch and Lightning with TPU on Kaggle.
([lang:ja] https://twitter.com/KJNLP1/status/1502757756893544449)

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda @rohitgr7 @kaushikb11

**Comment by Borda** [comment]
@kaushikb11 ^^
