### ISSUE TITLE
offline mode for wandb logger works incorrectly when resume mode is used

### ISSUE THREAD

**Issue by PgLoLo** [Lightning-AI/lightning#12502]
## 🐛 Bug

I experience a bug that when using wandb logger in offline mode AND resume=True it is not actually offline. Without resume=True everything is OK.
I was managed to fix it by explicitly passing parameter `mode='offline'` in addition to `offline=True` to wandb logger. Thus the probable cause could be [line](https://github.com/PyTorchLightning/pytorch-lightning/blob/c6cb6341e7e319191a83aa52bbbd4448ba0a372f/pytorch_lightning/loggers/wandb.py#L340) `os.environ["WANDB_MODE"] = "dryrun"`
I assume, that to fix it either `dryrun` have to be replaced with `offline`, or just remove environment variables from here and explicitly pass `mode='offline'` to `wandb.init`

cc @awaelchli @morganmcg1 @AyushExel @borisdayma @scottire @manangoel99

**Comment by manangoel99** [comment]
Hi @PgLoLo ! I'm an engineer at Weights & Biases. I will look into this and get back to you!

**Comment by manangoel99** [comment]
@PgLoLo could you also provide a code snippet to recreate the error?
