### ISSUE TITLE
Dimension mismatch error when reload the model after adding new special tokens to Transformer tokenizer

### ISSUE THREAD

**Issue by AlafateABULIMITI** [Lightning-AI/lightning#12612]
Hi all,

I train one model and reload in another structure of model with 2 separate steps. And in my training set (dialogue dataset), there are some special tokens (speaker_ids) that I need to add them to the tokenizer (I add 2 tokens here), I did this as mentioned in https://github.com/huggingface/tokenizers/issues/247#issuecomment-675458087:
```python
special_tokens_dict = {"additional_special_tokens": special_tokens}
num_added_toks = okenizer.add_special_tokens(special_tokens_dict)
```
and after I init my model, then resize token embeddings with:
```python
model = Generator(lr=lr, model_type=model_type)
model.bart.resize_token_embeddings(len(tokenizer))
```
I trained this `Generator` successfully, but when I tried to load it in another model structure like:
```python
class Model(pl.LightningModule)
def __init__(self,  gen_checkpoint_path: str):
self.generator = Generator.load_from_checkpoint(
            gen_checkpoint_path, lr=self.lr, model_type=self.model_type,
        )
```
it gave me the mismatch error: 
 ```

Error(s) in loading state_dict for Generator:        size mismatch for model.final_logits_bias: copying a param with shape torch.Size([1, 50267]) from checkpoint, the shape in current model is torch.Size([1, 50265]).        size mismatch for model.shared.weight: copying a param with shape torch.Size([50267, 768]) from checkpoint, the shape in current model is torch.Size([50265, 768]).

```
Mismatch size is exactly 2 which is the number of special tokens I added.  Using `Transfomers` built-in save load functions like:
```python
from transformers import BartForConditionalGeneration

model = BartForConditionalGeneration.from_pretrained(
     "hf-internal-testing/tiny-random-bart"
 )
# embeddings are size 1000
model.resize_token_embeddings(2000)
# Now they are of size 2000
model.save_pretrained("./test")
model2 = BartForConditionalGeneration.from_pretrained("./test')
# This works fine and model2 is indeed 2000 of embedding matrix.
```
It doesn't rise an issue, probably there is an interoperability issue between `pl` and `transformers`?

cc @awaelchli @ananthsub @ninginthecloud @rohitgr7 @otaj

**Comment by rohitgr7** [comment]
`transformers` simply ignore the keys without any warning. After loading you can check that the bias is 0 for this layer which means it doesn't load the weights of that layer as expected.
https://github.com/huggingface/transformers/blob/198c335d219a5eb4d3f124fdd1ce1a9cd9f78a9b/src/transformers/models/bart/modeling_bart.py#L1251

**Comment by AlafateABULIMITI** [comment]
@rohitgr7 Thank you for your explanation, but do you know some temporal solution for this? Otherwise, I can't use my trained models and have to rewrite the code again😮‍💨
