### ISSUE TITLE
using gpu cause cudnn error

### ISSUE THREAD

**Issue by kimmy966** [Lightning-AI/lightning#12652]
## 🐛 Bug

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [100, 113, 10]], which is output 0 of CudnnRnnBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

### To Reproduce
I can run my code while using cpu, but swich to cuda cause error like this 

### Environment

- PyTorch Lightning Version (e.g., 1.5.0): 1.6.0
- PyTorch Version (e.g., 1.10): 1.11.0
- Python version (e.g., 3.9): 3.8
- OS (e.g., Linux): Linux centos
- CUDA/cuDNN version: 11.3
- GPU models and configuration: GPU 2080 ti
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

cc @justusschock @kaushikb11 @awaelchli @akihironitta @rohitgr7

**Comment by krshrimali** [comment]
Hi, @kimmy966 - thank you for reporting this issue! It's possible that you might be modifying a tensor instead of returning. Would you mind sharing any script to reproduce the error you are facing? I can help point out what might be going wrong.

In case you can not share the script for some reasons, can you please check: (on using `torch.autograd.set_detect_anomaly` to debug this error): https://github.com/pytorch/pytorch/issues/15803?

**Comment by kimmy966** [comment]
> Hi, @kimmy966 - thank you for reporting this issue! It's possible that you might be modifying a tensor instead of returning. Would you mind sharing any script to reproduce the error you are facing? I can help point out what might be going wrong.
> 
> In case you can not share the script for some reasons, can you please check: (on using `torch.autograd.set_detect_anomaly` to debug this error): [pytorch/pytorch#15803](https://github.com/pytorch/pytorch/issues/15803)?

    def forward(self, input):
        logit = self.model_series(input)
        return logit

   def configure_optimizers(self):
        optimizer  = Adam(self.parameters(), lr=0.0001, weight_decay=1e-6)
        StepLR = lr_scheduler.MultiStepLR(optimizer, milestones=[2000], gamma=0.001)
        optim_dict = {'optimizer': optimizer, 'lr_scheduler': StepLR}
        return optim_dict

    def training_step(self, batch, batch_idx):
        x, y = batch
        y_hat = self(x)
        loss = self.loss_fuc(y_hat, y)
        self.log('val_loss', loss)
        return loss

    def validation_step(self, batch, batch_idx):
        tensorboard = self.logger.experiment
        x, y = batch
        y_hat = self(x)
        loss = self.loss_fuc(y_hat, y)
        spearman = SpearmanCorrCoef()
        ic = spearman(y_hat, y) * 100
        loss_dict = {'val_loss': loss}
        self.log('val_loss', loss, on_step=False, on_epoch=True, prog_bar=True, logger=True)
        self.log('ic', ic, on_step=False, on_epoch=True, prog_bar=True, logger=True)
        # tensorboard.add_image()
        tensorboard.add_scalars('val_loss', loss_dict, self.global_step)
        # tensorboard.add_histogram(...)

        return loss_dict

    def train_fuc(self, start_date, end_date):

        model_id = str(GetWindData.get_next_trade_date(self.eval_end))
        logger = TensorBoardLogger(configs["model_save"], name=self.model_name, version=str(model_id))
        checkpoint_callback = ModelCheckpoint(monitor='val_loss',
                                              dirpath=os.path.join(configs["model_save"], self.model_name, str(model_id)),
                                              save_top_k=10,
                                              mode="min"
                                              )
        # early_stop_callback = EarlyStopping(monitor="val_accuracy", min_delta=0.00, patience=3, verbose=False,
        #                                     mode="max")

        trainer = pl.Trainer(
            accelerator='gpu',
            gpus=0,
            max_epochs=self.epochs,
            logger=logger,
            log_every_n_steps=1,
            val_check_interval=0.25,
            callbacks=[checkpoint_callback],
            )
        trainer.fit(self)

hi, I share my training code here,  by the way, when I set (torch.autograd.set_detect_anomaly) to debug this problem, there cause a new error .... thank you for helping

**Comment by kimmy966** [comment]
> Hi, @kimmy966 - thank you for reporting this issue! It's possible that you might be modifying a tensor instead of returning. Would you mind sharing any script to reproduce the error you are facing? I can help point out what might be going wrong.
> 
> In case you can not share the script for some reasons, can you please check: (on using `torch.autograd.set_detect_anomaly` to debug this error): [pytorch/pytorch#15803](https://github.com/pytorch/pytorch/issues/15803)?

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [100, 113, 10]], which is output 0 of CudnnRnnBackward0, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

when I add (torch.autograd.set_detect_anomaly) to my code , this error happened

**Comment by rohitgr7** [comment]
is it possible that in your logic, a layer is modified already by the optimizer step, but there is another call of `loss.backward` that relies on old weights to compute the gradients?

or https://github.com/NVlabs/FUNIT/issues/23#issuecomment-528418501

**Comment by kimmy966** [comment]
> is it possible that in your logic, a layer is modified already by the optimizer step, but there is another call of `loss.backward` that relies on old weights to compute the gradients?
> 
> or try this if you have ReLU layers [NVlabs/FUNIT#23 (comment)](https://github.com/NVlabs/FUNIT/issues/23#issuecomment-528418501)

thank you, set relu layer param inplace = False save my model~ hh

**Comment by rohitgr7** [comment]
> Yes I have Relu in my layers, but I don't understand why I can train this model using CPU without any error occurred?

need to investigate the actual issue. It's related to PyTorch I guess, but still curious.
