### ISSUE TITLE
ModelSummary ignores nn.Parameter

### ISSUE THREAD

**Issue by ZhaofengWu** [Lightning-AI/lightning#12736]
## 🐛 Bug

I don't know if this is a bug of a feature, but currently ModelSummary only reports member `nn.Module`s and ignores `nn.Parameter`s that are directly created. I believe these parameters are an important part (and sometimes, a big part in terms of the number of weights) of the model so that they should be reported.

cc @borda @kaushikb11 @awaelchli @rohitgr7

**Comment by awaelchli** [comment]
Hey @ZhaofengWu 

Happy to see you find the model summary useful! 
I looked at this very briefly now. With the following code I get:

```py
import torch

from pytorch_lightning import LightningModule
from pytorch_lightning.utilities.model_summary import ModelSummary

class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.param = torch.nn.Parameter(torch.rand(2, 2))  # 2 * 2 = 4
        self.layer = torch.nn.Linear(2, 2)  # 2 * 2 + 2 = 6


if __name__ == "__main__":
    model = BoringModel()
    summary = ModelSummary(model)
    print(summary)
```

```
  | Name  | Type   | Params
---------------------------------
0 | layer | Linear | 6     
---------------------------------
10        Trainable params
0         Non-trainable params
10        Total params
0.000     Total estimated model params size (MB)

```

We can see that the correct amount of parameters are getting reported (10 trainable parameters). Perhaps the size in MB is wrong. 

Are you suggesting to include the nn.Parameter as a separate row in the table?

**Comment by ZhaofengWu** [comment]
> Perhaps the size in MB is wrong.

That's probably just a rounding thing?

> Are you suggesting to include the nn.Parameter as a separate row in the table?

Yes. It's a bit confusing that the individual param counts don't add up to the total number as well.

**Comment by ZhaofengWu** [comment]
But definitely not a huge issue and probably has low priority.

**Comment by ZhaofengWu** [comment]
Commenting for activity

**Comment by qixiang109** [comment]
I believe this problem still exists in pl version 1.6.4

`import torch
import torch.nn as nn
import pytorch_lightning as pl
from pytorch_lightning.utilities.model_summary import ModelSummary

class Example(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.lin1 = nn.Linear(32,64)
        self.lin2 = nn.Parameter(torch.rand([32,64]))
model = Example()
print(ModelSummary(model,max_depth=-1))
print(pl.__version__)
`

shows only lin1 but not lin2

`
  | Name | Type   | Params
--------------------------------
0 | lin1 | Linear | 2.1 K 
--------------------------------
4.2 K     Trainable params
0         Non-trainable params
4.2 K     Total params
0.017     Total estimated model params size (MB)
1.6.4

`

**Comment by ZhaofengWu** [comment]
Commenting for activity

**Comment by yeonju7kim** [comment]
Hi! @ZhaofengWu [ZhaofengWu](https://github.com/ZhaofengWu) 
I want to be assigned to this issue. It will be my first contribution.

And to make sure, I have a question.
When the code is below, is it the proper result?

``` python
import torch

from pytorch_lightning import LightningModule
from pytorch_lightning.utilities.model_summary import ModelSummary

class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.param = torch.nn.Parameter(torch.rand(2, 2))  # 2 * 2 = 4
        self.layer = torch.nn.Linear(2, 2)  # 2 * 2 + 2 = 6


if __name__ == "__main__":
    model = BoringModel()
    summary = ModelSummary(model)
    print(summary)
```

```
  | Name  | Type   | Params
---------------------------------
0 | param | Parameter | 4     
1 | layer   | Linear        | 6     
---------------------------------
10        Trainable params
0         Non-trainable params
10        Total params
0.000     Total estimated model params size (MB)
```

**Comment by ZhaofengWu** [comment]
Yes, I consider this behavior to be expected.

**Comment by awaelchli** [comment]
@yeonju7kim Feel free to give it a try. 

I still have some doubts on the definition of when exactly such a parameter gets displayed. It's not clear to me how we can differentiate between a parameter that you the user created vs. one that is e.g. in the nn.Linear layer (weight, bias). Usually models are deeply nested and not flat like the one above. 
One could of course only collect the top-level parameter definitions, but then someone might ask why their super important parameter defined in their nested module is not showing up, but the top-level one is.

**Comment by ZhaofengWu** [comment]
@awaelchli So, first of all, the default ModelSummary has `max_depth=1`, so a user shouldn't expect their super important yet nested parameter to show up by default. When they do set a larger `max_depth`, the question is if we want to show, as in your example, nn.Linear's weight and bias. The simplest answer is yes -- the summary will be more verbose, but when users set a larger `max_depth` they should expect a more verbose output. Another option is that we hide all parameters of modules under `torch.nn`.

**Comment by awaelchli** [comment]
I think we can do what you are proposing. 

> Another option is that we hide all parameters of modules under torch.nn.
I wouldn't do this, as torch.nn is just a special case. 

I'll assign [yeonju7kim](https://github.com/yeonju7kim)
Thank you for your interest.

**Comment by rhiga2** [comment]
If the concern is that the layer params reported does not add to the total number of params could we just display the difference under an `other` category or would this not work?

**Comment by awaelchli** [comment]
Sounds good to me!

**Comment by rhiga2** [comment]
I could look at this issue

**Comment by Borda** [comment]
> I could look at this issue

Perfect!

**Comment by drscotthawley** [comment]
What's the story on this? This behavior persists despite the issue being closed and the PR being merged. 

trying @yeonju7kim's code we don't see "param" listed, we just see:

```
  | Name         | Type   | Params
----------------------------------------
0 | layer        | Linear | 6     
  | other params | n/a    | 4     
----------------------------------------
10        Trainable params
0         Non-trainable params
10        Total params
0.000     Total estimated model params size (MB)
```

In my code, I define `        self.cb = nn.Parameter(torch.Tensor(cb_len, latent_dim))`
but "cb" doesn't appear on the summary list.  
(It's also not getting updated, despite requires_grad=True and  is_leaf=True)
