### ISSUE TITLE
tuner.scale_batch_size does not update DataModule hparams

### ISSUE THREAD

**Issue by tsuga** [Lightning-AI/lightning#12768]
## 🐛 Bug

`tuner.scale_batch_size` finds the suitable batch size and update the batch size of the model AND datamodule.
For the model, `tuner.scale_batch_size` updates the batch size in the model regardless of `model.batch_size` and `model.hparams.batch_size`.

However, for the datamodule, `tuner.scale_batch_size` updates `datamodule.batch_size` only, and keep `datamodule.hparams.batch_size` unchanged if hparams are in use.

So the tuner behaves differently for model and datamodule, which could be a trigger of confusion for users.

### To Reproduce

https://gist.github.com/tsuga/289febb6cfe8c05e6c41cce043147174

### Expected behavior

The tuner should updates `datamodule.hparams.batch_size`

### Environment
* CUDA:
        - GPU:
                - Tesla P100-PCIE-16GB
        - available:         True
        - version:           11.1
* Packages:
        - numpy:             1.21.5
        - pyTorch_debug:     False
        - pyTorch_version:   1.10.0+cu111
        - pytorch-lightning: 1.6.1
        - tqdm:              4.64.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - 
        - processor:         x86_64
        - python:            3.7.13
        - version:           #1 SMP Tue Dec 7 09:58:10 PST 2021

### Additional context

cc @akihironitta @borda @rohitgr7 @carmocca @awaelchli @ananthsub @ninginthecloud @jjenniferdai

**Comment by awaelchli** [comment]
It makes sense to supports this now. Previously, this was not necessary/possible because we didn't have the `save_hyperparameters` support in DataModule. Now that we have, we should modify the[ `_lightning_get_all_attr_holders`](https://github.com/PyTorchLightning/pytorch-lightning/blob/ae3226ced96e2bc7e62f298d532aaf2290e6ef34/pytorch_lightning/utilities/parsing.py#L302-L326) function to support that. 

Can be a good first issue for new contriburtors, or you @tsuga if you are interested.

**Comment by tsuga** [comment]
@awaelchli Thank you for your attention. I understand the historical background of this.
Unfortunately, I'm new to the code base hence I'm happy to get this done by new contributors.

**Comment by tanmoyio** [comment]
@tsuga I am new to the code base, if you haven't started working on it already, then may be I can try. 
cc @awaelchli

**Comment by awaelchli** [comment]
Thanks, very nice! Yes please go ahead :)
