### ISSUE TITLE
PyTorch Profiler docs are out of date

### ISSUE THREAD

**Issue by scottgigante-immunai** [Lightning-AI/lightning#12760]
## 📚 Documentation

Tips on how to run the PyTorch profiler in the [lightning docs](https://pytorch-lightning.readthedocs.io/en/stable/advanced/profiler.html#pytorch-profiler) are only relevant for the legacy profiler.

Details on the modern pytorch profiler (which integrates with tensorboard) are [here](https://pytorch.org/blog/introducing-pytorch-profiler-the-new-and-improved-performance-tool/).

These changes should be reflected in the Lightning docs.

cc @borda @rohitgr7 @carmocca @kaushikb11 @ninginthecloud

**Comment by awaelchli** [comment]
Thanks for letting us know @scottgigante-immunai
Are you interested helping us improve these docs?

**Comment by scottgigante-immunai** [comment]
Unfortunately not something I have time for, sorry! Appreciate all of your work 🙏

**Comment by aseemk98** [comment]
Hi @awaelchli ! I'd love to take this up if possible!

**Comment by awaelchli** [comment]
@aseemk98 great! Feel free to send a PR with the updates. Are you familiar with the PyTorch profiler?

**Comment by aseemk98** [comment]
@awaelchli No, I've never used it before. But I'll go through it.

**Comment by nikshrimali** [comment]
I am interested in working on this issue, assign it to me if possible!!

**Comment by Borda** [comment]
> I am interested in working on this issue, assign it to me if possible!!

cool! :rabbit:

**Comment by Andrei-Aksionov** [comment]
Hey @awaelchli 
I quickly checked the docs and they look ok.
Given the time that has passed, I assume that the issue has been fixed but was forgotten to close.

**Comment by awaelchli** [comment]
Thank you @Andrei-Aksionov, yes looks like it, hakuna matata.
If anyone finds typos or incorrect references, feel free to directly open a PR with the correction.
