### ISSUE TITLE
Fix saving of config.yaml when using multiple loggers

### ISSUE THREAD

**Issue by Schinkikami** [Lightning-AI/lightning#12803]
## 🚀 Feature

Currently, the `SaveConfigCallback `saves the config.yaml file to `trainer.log_dir`, which for one logger is `trainer.loggers[0].log_dir`. 

However, if multiple loggers are specified `trainer.log_dir == trainer.default_root_dir`. In this case the config.yaml is saved ABOVE the version_dirs, which prevents running the experiments multiple times. 

Ideally, the config.yaml would in this case still be saved to `trainer.default_root_dir/{version_found_at_runtime}/config.yaml`. 

### Motivation

If I have a directory structure like this 

```
runs/
    experiment1/
```

and initialize the trainer: `Trainer(default_root_dir="runs/experiment1", loggers=True)`
the config.yaml is safed to

```
runs/
    experiment1/
        lightning_logs/
            version_1/
                config.yaml
```

If  I however specify multiple loggers (e.g. `loggers = [TensorBoardLogger(...), CSV_Logger(...)]`) the config.yaml is saved to 

```

runs/
    experiment1/
        lightning_logs/
            config.yaml
            version_1/

```
, independent of the log_dirs of the loggers, which hinders multiple executions of the experiment.

As I'm not sure If this is intended behaviour I marked this post as a Feature Request.

### Alternatives

As the trainer (as far as I know) does not offer an attribute to the path of the current version_dir another solution could be to save the config.yaml to EVERY log_dir of the loggers.

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @tchaton @justusschock @awaelchli @borda @edward-io @ananthsub @rohitgr7 @kamil-kaczmarek @Raalsky @Blaizzy

**Comment by carmocca** [comment]
This is caused by the logger's design, it's unrelated to the `LightningCLI`

```python
from pytorch_lightning import Trainer
from pytorch_lightning.loggers import TensorBoardLogger, CSVLogger

save_dir = "my_save_dir"
trainer = Trainer(logger=[CSVLogger(save_dir), TensorBoardLogger(save_dir)])
print(trainer.log_dir)  # /home/carmocca/git/pytorch-lightning

save_dir = "my_save_dir"
trainer = Trainer(logger=CSVLogger(save_dir))
print(trainer.log_dir)  # my_save_dir
```

cc'ing @daniellepintz @akashkw for comment

**Comment by Schinkikami** [comment]
Yes, this is a problem of how the `Trainer` and the loggers interact. 

One potential fix for now (I'm using that myself right now, with an overridden `SafeConfigCallback `subclass) is to instead safe the config.yaml to the `log_dir `of every logger, as it is done with the `save_hyperparameters() `function, that saves the hparams.yaml in a similar way.

It should definitely be fixed, as it hinders training with multiple Loggers and the CLI.

**Comment by tshu-w** [comment]
https://github.com/PyTorchLightning/pytorch-lightning/issues/12028
