### ISSUE TITLE
Add additional parameters to the `DeepSpeedStrategy`

### ISSUE THREAD

**Issue by SeanNaren** [Lightning-AI/lightning#12820]
## 🚀 Feature

A user on our community slack found that a few more parameters have become available for DeepSpeed including `ignore_unused_parameters` (the opposite of `find_unused_parameters` for DDP).

https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training

Integrate `ignore_unused_parameters`, `round_robin_gradients` and `stage3_gather_16bit_weights_on_model_save` into the Strategy.

cc @borda @SeanNaren @awaelchli @rohitgr7 @akihironitta

**Comment by akihironitta** [comment]
@SeanNaren I saw @rohitgr7 add support for `bf16` in #12508, but other parameters haven't been added yet. Should this issue be kept open?
