### ISSUE TITLE
CometLogger ExistingOfflineExperiment support

### ISSUE THREAD

**Issue by rabyj** [Lightning-AI/lightning#12829]
## 🚀 Feature

We should be able to reload existing offline experiments to perform new logging (e.g. log new metrics on different datasets).

### Motivation

I need to work offline due to connectivity issues, and I need to be able to reload experiments, since I want to add new metrics after the training is completely finished. 

I was able to reload with online experiments, but I though for sure it was possible offline too using the same flags. This feature seems absent from the source code for now, even though it should intuitively be there. For now, the result is that my data ends up into two completely separate offline experiments which I'm unable to merge.

#### Motivation sidenote 

I cannot achieve to expected result (everything logged into one experiment) with only one [CometLogger](https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.loggers.comet.html#module-pytorch_lightning.loggers.comet) object through my whole script, because currently (1.6.1), it seems the logger calls the `finalize` method after `Trainer.fit` is finished, which stops any new data from being logged into the `Experiment`. This is a problem for me, but seems perhaps intentional, so I won't submit an issue. Otherwise, there would be no need to reload for me in the first place.

### Pitch

I think `CometLogger` should allow reloading offline experiments via the `offline=True`, `save_dir=/path/to/existing/savedir` and `experiment_key=previously_generated_key` arguments, thus not adding any flags to the current API. 

An experiment key is created even when the initial logging is done offline (it is for future exporting to online if I understand correctly), so that key should be used, otherwise we would need a new flag to tell the object we want to reload and not create a new experiment (sub-optimal, it would affect `ExistingExperiment` support too).

Similar to how [ExistingExperiment](https://www.comet.ml/docs/python-sdk/ExistingExperiment/) is used under the hood, [ExistingOfflineExperiment](https://www.comet.ml/docs/python-sdk/ExistingOfflineExperiment/) would be used.

### Alternatives

This feature could be entirely avoided for now (it should still exist eventually though, imo) if users could terminate their logging whenever they want (e.g. completely after training), if that's somehow more simple.

### Personal note - First issue!!!

After coding part-time for a few years, this is my first real issue in a project external to my bioinformatics team. Please point me to any contribution "faux-pas" if I do any.

cc @borda

**Comment by rohitgr7** [comment]
This will be good to have. Would you like to contribute this feature to the `CometLogger`?

**Comment by rabyj** [comment]
@rohitgr7 I reread the [ExistingOfflineExperiment](https://www.comet.ml/docs/python-sdk/ExistingOfflineExperiment/) doc and it seems it actually can't read the offline directory, but can take an experiment already uploaded to comet-ml and store offline further information to be uploaded to it later. I.e. it lets you prepare a local .zip to merge or modify an already uploaded experiment later.

As such, `ExistingOfflineExperiment` does not actually let us do what I pitched, and I don't think it's quite possible until comet-ml creates such an experiment type. It seems the `ExistingOfflineExperiment` name mislead me, it still requires an online component.

I'm unsure how we could reach the proposed feature, then.
