### ISSUE TITLE
Unpin `deepspeed<0.6.0` in CI

### ISSUE THREAD

**Issue by akihironitta** [Lightning-AI/lightning#12881]
## 🚀 TODO in CI

In GPU CI, the version of deepspeed was pinned at 0.5.10 due to the same issue as (or a similar issue to) https://github.com/microsoft/DeepSpeed/issues/1878.

Its patch (https://github.com/microsoft/DeepSpeed/pull/1901) will be included in the next release, so once 0.6.2 is released, we can try updating the following line:

https://github.com/PyTorchLightning/pytorch-lightning/blob/bb81802bff29fa06399d704688df256813e05ad2/.azure-pipelines/gpu-tests.yml#L56

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @carmocca @akihironitta @borda @SeanNaren @awaelchli @rohitgr7

**Comment by akihironitta** [comment]
Blocked by #12979.

**Comment by carmocca** [comment]
We just fixed this!
