### ISSUE TITLE
CSV logger does not support multiple data loaders (AssertionError: can only test a child process)

### ISSUE THREAD

**Issue by ZENGYIMING-EAMON** [Lightning-AI/lightning#12888]
## 🐛 Bug

 When I run trainer.predict, CSV logger does not support multiple data loaders. 

### Expected behavior

CSV logger record multiple data loaders into multiple .csv files
### Environment

- PyTorch Lightning Version 1.6.1:
- PyTorch Version 1.10:
- Python version 3.9:
- OS (Linux):
- CUDA/cuDNN version: cuda 11.3
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

get error

assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process

cc @borda @rohitgr7 @akihironitta

**Comment by ZENGYIMING-EAMON** [comment]
Any progress?

**Comment by carmocca** [comment]
Can you provide a reproducible script showing the issue? You can adapt this file:

https://github.com/Lightning-AI/lightning/blob/master/examples/pl_bug_report/bug_report_model.py
