### ISSUE TITLE
Add `LM.fuse_model` method for `QuantizationAwareTraining`

### ISSUE THREAD

**Issue by ORippler** [Lightning-AI/lightning#12899]
## 🚀 Feature
By adding a `LM.fuse_model` method, the user can define operations that are to be fused in a much easier way compared to the current way of explicit, string-based definitions in `QuantizationAwareTraining` callback.

### Motivation
The current way of specifying model fusion in `QuantizationAwareTraining` is really annoying, requiring the explicit declaration of which operations to fuse. `QuantizationAwareTraining` relies on `torch.ao.quantization.fuse_modules`, which requires said, explicit definition.

### Pitch
Add a `LM.fuse_model` method, which defaults to performing no fusion at all.
By overloading `LM.fuse_model`, the user has the complete power to fuse his model in an appropriate manner.
QuantizationAwareTraining would then call `LM.fuse_model` instead of calling [`torch.ao.quantization.fuse_modules`](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/callbacks/quantization.py#L254-L255).

This proposal is inspired by the approach pursued in [torchvision.models.quantization](https://github.com/pytorch/vision/tree/d07da41dc533f27bb1c6ac5b147073a7f7ca9675/torchvision/models/quantization), where the same thing is already done.

### Additional context
Thoughts @Borda 

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda @carmocca @awaelchli @ninginthecloud @daniellepintz @rohitgr7

**Comment by carmocca** [comment]
Instead of trying to add a hook in the LM that's specific to this callback, I would instead look at adding such hook in the callback itself, or allow passing a Callable to it
