### ISSUE TITLE
Inference with `QuantizationAwareTraining` model inconsistent

### ISSUE THREAD

**Issue by ORippler** [Lightning-AI/lightning#12900]
## 🐛 Bug
I am having difficulty to reproduce results of a post-QAT pre-conversion.
Use-case is that I want to conditionally infer either on GPU (post-QAT pre-conversion) or CPU (post-QAT post-conversion).
However, results of these two models are inconsistent, and post-QAT pre-conversion restored from checkpoint behaves different to post-QAT pre-conversion, when supplied to `Trainer.test.

### To Reproduce
https://colab.research.google.com/drive/18Qw3S6dBHaekLujn1jtyueGP8yQSAEjo?usp=sharing

### Expected behavior
Consistent resuilts pre/post restore, and pre/post quantization

### Environment

```
* CUDA:
	- GPU:
		- Tesla K80
	- available:         True
	- version:           11.3
* Packages:
	- numpy:             1.21.6
	- pyTorch_debug:     False
	- pyTorch_version:   1.11.0+cu113
	- pytorch-lightning: 1.6.1
	- tqdm:              4.64.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.13
	- version:           #1 SMP Tue Dec 7 09:58:10 PST 2021
```

### Additional context
* I am also unable to reproduce results of `trainer.test` with a manual loop, refer colab issue.
* The `make_error` flag points at either a potential error in my implementation, or an additional Bug, and seemed very obscure to me

cc @borda @justusschock @Borda

**Comment by ORippler** [comment]
Inconsistencies are still observed in the supplied colab notebook, therefore pinging @Borda

**Comment by ORippler** [comment]
Inconsistencies are still observed in the supplied colab notebook.

**Comment by justusschock** [comment]
@Borda you wrote that originally, might have a look?
