### ISSUE TITLE
Trainer.predict() as generator

### ISSUE THREAD

**Issue by Borda** [Lightning-AI/lightning#12910]
### Motivation

Recently I was using Flash for some image segmentation, and the case is that the predictions are almost the same size as input images or even larger if output prediction/probability for each class in your multi-class semantic segmentation... then running predictions for all dataset atm would need to implement custom callback with saving to a file, but what if I just need some simple postprocessing such as conversion to RLE... anyway the predictions are grouped per batch which is also not very intuitive as you get all at once when the full prediction loop is finished

https://www.kaggle.com/code/jirkaborovec/demo-flash-semantic-segmentation

### Pitch

Extend prediction flexibility for ML practitioners without the need to dive into PL and implement their own callback

### Alternatives

How about adding an extra argument to turn loop to a generator with limiting that it can use at most single GPU

```py
fig, axarr = plt.subplots(ncols=2, nrows=len(sample_imgs), figsize=(10, 5 * len(sample_imgs)))
running_i = 0
for pred_batch in trainer.predict(model, datamodule=datamodule, generator_mode=True):
    for pred in pred_batch:
        img = plt.imread(sample_imgs[running_i])
        axarr[running_i, 0].imshow(img)
        axarr[running_i, 1].imshow(pred)
        running_i += 1
```

### Additional context

cc: @awaelchli 

cc @borda @tchaton @justusschock @awaelchli @carmocca @ananthsub @ninginthecloud @rohitgr7

**Comment by awaelchli** [comment]
The trainer method returning a generator is an interesting idea. It would probably not be too hard to implement this for a simple loop like the Trainer.predict. 
Note however, for all spawn-based strategies, this is not going to work so cleanly because the main process does not have direct access to the outputs of the workers. It would require a queue and the order in which these outputs come in could be mixed up (depends if order matters). It would certainly require substantial changes to how we process outputs here, but in terms of the loop itself this could probably be already be achieved with loop customization.

**Comment by carmocca** [comment]
I think this is a cool idea. But being cool is not enough justification for addition.

The framework's overall design always pushes for encapsulating the user's code inside our abstractions. LightningModules, Callbacks, Hooks, Loops, ...
This is the opposite direction. It reduces reusability and control.

As a new user, It would also make me wonder about things like:
- Why not also for `fit`, etc?
- Can I modify things inside the trainer, LM, or a callback per iteration?
- Does this replace the `predict_step` in the model? Does it run before? After?
- What if I wrote that loop but now I need to run something in a different hook? Do I need to write a Callback now?

So if the motivation is removing the need to write a Callback, I lean towards not doing this.
If the motivation is to speed up simple inference, I think it falls under the uses of Lite.

Still, we could think of these questions and come up with a proposal. But to me it should be a separate method (`trainer.predict_generator()`?) to properly disambiguate.

Also note that the existing `predict` method already has: https://github.com/PyTorchLightning/pytorch-lightning/blob/5bb265e18b25f20494fe7fc34de5ae136428721f/pytorch_lightning/trainer/trainer.py#L969-L970 (albeit requires that all predictions fit in memory)

**Comment by rohitgr7** [comment]
you can do this using a callback?

```python
class PredictionWriter(Callback):
    def on_predict_batch_end(trainer, pl_module, outputs, batch, *args, **kwargs):
        for img, pred in zip(outputs, batch):
            ...

trainer = Trainer(callbacks=[PredictionWriter()])
trainer.predict(..., return_predictions=False)
```
