### ISSUE TITLE
Distribution not moved to correct device

### ISSUE THREAD

**Issue by david-waterworth** [Lightning-AI/lightning#12943]
## 🐛 Bug

I'm attempting to port a variational auto-encoder to use `torch.distributions`. I noticed that when I define a `torch.distributions.Distribution` as a module parameter - for example the `prior` in the example below - it doesn't get moved to the correct device. I'm fairly certain this is because you call `module.apply()` with a lambda in order to recursively move modules to the specific device - unfortunately a Distribution is not a module but it does hold tensors so this strategy fails in this edge case.

### To Reproduce

```
import os

import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer

from torch.distributions import MultivariateNormal

class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

        latent_dim=2
        self.prior = MultivariateNormal(
			torch.zeros(latent_dim), 
			scale_tril=torch.diag(torch.ones(latent_dim)))

    def forward(self, x):
        assert self.prior.loc.device == x.device, "incorrect device"
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    test_data = DataLoader(RandomDataset(32, 64), batch_size=2)

    model = BoringModel()
    trainer = Trainer(
        gpus=1,
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        limit_test_batches=1,
        num_sanity_val_steps=0,
        max_epochs=1,
        enable_model_summary=False,
    )
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
    trainer.test(model, dataloaders=test_data)


if __name__ == "__main__":
    run()
```

### Environment

* CUDA:
        - GPU:
                - NVIDIA GeForce RTX 3090
                - NVIDIA GeForce RTX 3090
        - available:         True
        - version:           11.1
* Packages:
        - numpy:             1.22.3
        - pyTorch_debug:     False
        - pyTorch_version:   1.9.1+cu111
        - pytorch-lightning: 1.6.1
        - tqdm:              4.64.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.10
        - version:           #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022

**Comment by rohitgr7** [comment]
anything that is not `nn.Module` or registered under buffer will not be moved to the device. Here the `LightningModule` follow the steps of `nn.Module` so even if you do this:
```py
class BoringModel(nn.Module):  # <- using `nn.Module` here
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

        latent_dim=2
        self.prior = MultivariateNormal(
			torch.zeros(latent_dim), 
			scale_tril=torch.diag(torch.ones(latent_dim)))

model = BoringModel()
model.cuda()
```
`model.prior` will stay on the CPU.

I'd suggest doing
```py
class LitModel(LightningModule):
    def on_fit_start(self):
        self.prior = MultivariateNormal(
            torch.zeros(latent_dim, device=self.device), 
            scale_tril=torch.diag(torch.ones(latent_dim, device=self.device))
        )

```

**Comment by rohitgr7** [comment]
then you need to define it under `on_test_start/on_validation_start` as well. To make sure they are saved in the checkpoint, maybe try registering them as a buffer so that they are moved to the correct devices as well as saved to the checkpoint.
