### ISSUE TITLE
Inconsistent example_input_array handling

### ISSUE THREAD

**Issue by denix56** [Lightning-AI/lightning#12957]
## 🐛 Bug

ModelSummary expands example_input_array. So in case we have dict it will be expanded to the arguments.
On the contrary, TensorBoardLogger does not expand and gives example_input_array as it is.

cc @awaelchli @edward-io @rohitgr7 @kaushikb11

**Comment by rohitgr7** [comment]
good catch!

would you like to send a PR with a fix?
this is the piece of code you'd need to update.
https://github.com/PyTorchLightning/pytorch-lightning/blob/eebba9e632a53a2bc945ddec430aec45f315b9d1/pytorch_lightning/utilities/model_summary.py#L260-L275

**Comment by awaelchli** [comment]
Hi 
I actually don't understand what you mean by "TensorBoardLogger does not expand and gives example_input_array as it is". Can you give an example?

**Comment by denix56** [comment]
Your example_input_array is

```
self.example_input_array = {'lq': tensor, 'gt': tensor}

def forward(self, batch):
    lq = batch['lq']
    gt = batch['gt']
    # some processing
```

In this case TensorBoardLogger will pass the dict to the forward method as it is.
The ModelSummary will expand the dict and forward will receive lq and gt arguments.

**Comment by awaelchli** [comment]
Right. For tracing with TensorBoard, kwargs are not supported. You will need to return a tuple instead:

```py
self.example_input_array = (tensor, tensor)

def forward(self, lq, gt):
    lq = batch['lq']
    gt = batch['gt']
    # some processing
```

We should include an error message in our TB logger implementation.
