### ISSUE TITLE
Expose hooks to process input args in precision plugins

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#13000]
### Motivation

#12983 attempted to fix an issue where the evaluation step methods in the DDPStrategy would call the `LightningModule.x_step `methods directly instead of going through the `LightningDoublePrecisionModule.x_step` methods.

This introduced a typing issue where we can't guarantee that `self.model` implements the `x_step` methods.

 
### Pitch

Treat #12983 as a temporary fix and refactor away the need to have a precision wrapper. 
All the precision wrapper does is [process the input arguments](https://github.com/PyTorchLightning/pytorch-lightning/blob/3d74c90e8802f91dcd6dc1492123eb5b87c49db9/pytorch_lightning/plugins/precision/double.py#L51-L55).  
This input processing could be done directly in the strategy. 

Before

```py
    def test_step(self, *args, **kwargs) -> Optional[STEP_OUTPUT]:
        with self.precision_plugin.test_step_context():
            return self.MAYBE_WRAPPER.test_step(*args, **kwargs)
```

After

```py
    def test_step(self, *args, **kwargs) -> Optional[STEP_OUTPUT]:
        with self.precision_plugin.test_step_context():
            return self.LIGHTNING_MODULE.test_step(self.precision_plugin.process_step_inputs(*args, **kwargs))
```

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @justusschock @awaelchli @rohitgr7 @carmocca @akihironitta

**Comment by carmocca** [comment]
Sounds good to me. A relevant PR that still needs to land: https://github.com/PyTorchLightning/pytorch-lightning/pull/10079/
