### ISSUE TITLE
Training process terminated with exit code 139 if add_image called inside training_step

### ISSUE THREAD

**Issue by semaphore-egg** [Lightning-AI/lightning#13011]
## 🐛 Bug

A call to `self.logger.experiment.add_image` inside `trainer.training_step` terminates the training process.

Similar code inside `trainer.on_train_batch_end` or `trainer.on_train_epoch_end` works as expected.

### To Reproduce

```python
import os
import torch
from torch import nn
import torch.nn.functional as F
from torchvision import transforms
from torchvision.datasets import MNIST
from torch.utils.data import DataLoader, random_split

import pytorch_lightning as pl


class DataModule(pl.LightningDataModule):
    def __init__(self):
        super().__init__()

    def train_dataloader(self):
        ds_train = MNIST(os.getcwd(), download=True, transform=transforms.ToTensor())
        dl_train = DataLoader(ds_train, num_workers=6)
        return dl_train

    def val_dataloader(self):
        return self.train_dataloader()


class LitAutoEncoder(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.encoder = nn.Sequential(nn.Linear(28 * 28, 64), nn.ReLU(), nn.Linear(64, 3))
        self.decoder = nn.Sequential(nn.Linear(3, 64), nn.ReLU(), nn.Linear(64, 28 * 28))

    def forward(self, x):
        embedding = self.encoder(x)
        return embedding

    def training_step(self, batch, batch_idx):
        x, y = batch
        x = x.view(x.size(0), -1)
        z = self.encoder(x)
        x_hat = self.decoder(z)
        loss = F.mse_loss(x_hat, x)

        # =========>>>> work as expected
        self.log("train_loss", loss)

        # =========>>>> work as expected (though do not make sense)
        self.logger.experiment.add_text('my_text', f'abcdef{loss}')

        # =========>>>> following code fails
        # =========>>>> Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
        self.logger.experiment.add_image('my_image', batch[0][0], self.global_step)

        return loss

    def on_train_batch_end(self, outputs, batch, batch_idx) -> None:
        # =========>>>> similar code works here
        self.logger.experiment.add_image('my_image', batch[0][0], self.global_step)

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=1e-3)
        return optimizer


def main():
    autoencoder = LitAutoEncoder()
    trainer = pl.Trainer(
        accelerator="gpu",
        devices=1,
        log_every_n_steps=10
    )

    dm = DataModule()
    trainer.fit(model=autoencoder, datamodule=dm)


if __name__ == '__main__':
    main()

```

### Expected behavior

According to [documentation](https://pytorch-lightning.readthedocs.io/en/latest/visualize/logging_intermediate.html) logging images inside `trainer.training_step` should work.

### Environment

* CUDA:
	- GPU:
		- NVIDIA GeForce RTX 3090
	- available:         True
	- version:           11.3
* Packages:
	- numpy:             1.21.6
	- pyTorch_debug:     False
	- pyTorch_version:   1.11.0+cu113
	- pytorch-lightning: 1.6.0~1.6.3
	- tqdm:              4.64.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.9.11
	- version:           20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022

cc @otaj @awaelchli @edward-io @rohitgr7

**Comment by rohitgr7** [comment]
> # self.logger.experiment.add_image('my_image', batch[0][0], self.global_step)
 
is it terminating right at the first call or after some time? I tried your example for 1 epoch and it's working for me.

**Comment by semaphore-egg** [comment]
It is the `add_image` inside `training_step` that causes the problem.  (I just update the sample so the problem-related line is now uncommented.)

The crash happens at batch 2 or batch 3, which is almost at the first call.

![Screenshot from 2022-05-09 18-14-55](https://user-images.githubusercontent.com/56214204/167392559-83958bd9-c6dd-4b2d-92f4-2b2d8e531610.png)

**Comment by semaphore-egg** [comment]
I use gdb to trace the problems:
```bash
>>> gdb python
(gdb) run c.py 
```

and get the following report:

![Screenshot from 2022-05-09 18-35-55](https://user-images.githubusercontent.com/56214204/167393409-a6f7d174-9c53-4ded-a6ad-c88497e5ee54.png)

**Comment by semaphore-egg** [comment]
@rohitgr7 I just find a closely related issue that has been closed #11925.

**Comment by rohitgr7** [comment]
yep! I did uncomment the line and ran it and it worked. Maybe some issue with your matplotlib installation?
Also tried on [colab](https://colab.research.google.com/github/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report/bug_report_model.ipynb), and it seems to be working there.

**Comment by semaphore-egg** [comment]
I get three servers at hand and two of them reproduce this crash. The third server and the colab work fine.

The crash is not related to the python version (tested on 3.7-3.9), GPU availability, or lightning version (1.6.0-1.6.3).

Seems that there is something wrong with Pillow. 
`Pillow > 9.0.1` breaks tensorboard writer and reducing it to `8.4.0` solves the problem.

Will investigate more tomorrow.

**Comment by semaphore-egg** [comment]
After some checks, find that the only problematic Pillow version is `9.1.0`. 
Pillow == `8.4.0`, `9.0.0` and `9.0.1` works fine for me. Other lower version is not compatible with `torchvision==0.12.0` so not tested.

Wrapping the logging code with `with torch.no_grad():` does not stop the crash.

The behavior is rather consistent across all my servers and Colab. The crash happens near `step 2` or `step 33`.
The servers crash with either `exit code 139 (interrupted by signal 11: SIGSEGV)` or `Segmentation fault (core dumped)`.
Colab kernel breaks and requires a start.

**Comment by roytseng-tw** [comment]
Thanks to @semaphore-egg 
downgrade Pillow version from 9.1.0 to 9.0.1 solved my problem.
