### ISSUE TITLE
PyTorch 1.11 testing in CI fails due to timeout

### ISSUE THREAD

**Issue by akihironitta** [Lightning-AI/lightning#13103]
## 🐛 Bug

<details><summary>links to recent runs</summary>

- timeout (stable):
  - https://dev.azure.com/PytorchLightning/pytorch-lightning/_build/results?buildId=72469&view=results
- timeout (lts):
  - https://dev.azure.com/PytorchLightning/pytorch-lightning/_build/results?buildId=72443&view=results
  - https://dev.azure.com/PytorchLightning/pytorch-lightning/_build/results?buildId=72438&view=results
  - https://dev.azure.com/PytorchLightning/pytorch-lightning/_build/results?buildId=72413&view=results
  - https://dev.azure.com/PytorchLightning/pytorch-lightning/_build/results?buildId=72404&view=results
- timeout (both):
  - https://dev.azure.com/PytorchLightning/pytorch-lightning/_build/results?buildId=72453&view=results
- successful:
  - https://dev.azure.com/PytorchLightning/pytorch-lightning/_build/results?buildId=72465&view=results
  - https://dev.azure.com/PytorchLightning/pytorch-lightning/_build/results?buildId=72458&view=results
  - https://dev.azure.com/PytorchLightning/pytorch-lightning/_build/results?buildId=72419&view=results
  - https://dev.azure.com/PytorchLightning/pytorch-lightning/_build/results?buildId=72407&view=results
  - https://dev.azure.com/PytorchLightning/pytorch-lightning/_build/results?buildId=72391&view=results
  - https://dev.azure.com/PytorchLightning/pytorch-lightning/_build/results?buildId=72388&view=results
  - https://dev.azure.com/PytorchLightning/pytorch-lightning/_build/results?buildId=72379&view=results

</details>

### Expected behavior
- No timeout, or
- find the cause of longer runs with PyTorch 1.11 that can be reasonably explained, e.g.
  - due to the number of test cases running
  - due to some issue from PyTorch 1.11

### Environment
See Azure Pipelines configs.

### Additional context
Docker images used for the past day:
- pytorchlightning/pytorch_lightning:base-cuda-py3.7-torch1.8@sha256:2d9c266bba1ea82ffb5768d522cc94f559c73886da997fd6f93c6ec18acbf037
- pytorchlightning/pytorch_lightning:base-cuda-py3.9-torch1.11@sha256:ae7455692a4cc3ab1906fa20ad08b5f33ac898c688296e9d3acf1f4771941658

cc @tchaton @rohitgr7 @carmocca @akihironitta @borda

**Comment by akihironitta** [comment]
[for the note] This CI job with LTS failed due to timeout:
https://dev.azure.com/PytorchLightning/pytorch-lightning/_build/results?buildId=73031&view=logs&j=5ea502cf-d418-510c-3b5f-c4ba606ae534&t=ad0b8e2f-da1f-5a7c-b4de-96aa939719e3
```
2022-05-24T19:03:02.7512860Z tests/strategies/test_collaborative.py::test_multiple_peers[2-0.25] PASSED [ 57%]
2022-05-24T20:29:59.5773896Z tests/strategies/test_collaborative.py::test_scaler_updated_precision_16 
2022-05-24T20:29:59.5899782Z ##[error]The operation was canceled.
2022-05-24T20:29:59.5912172Z ##[section]Finishing: Testing: standard
```

**Comment by carmocca** [comment]
Closing as I think this is no longer a problem. Feel free to re-open if I'm mistaken
