### ISSUE TITLE
GPU load imbalance

### ISSUE THREAD

**Issue by YanhaoWu** [Lightning-AI/lightning#13135]
When I tried to use 8 3090 cards for training, I found that the first card used more memory. Just like this
![image](https://user-images.githubusercontent.com/79640383/169970961-1a642b64-7c5c-4aba-9fd7-6280e0e588d5.png)
Due to the limitation of card 1, I can't transfer my batch_size increases. Is there any way to balance the load on multiple cards?

I used the following code to start the training
```
model_sem_kitti = SemanticKITTIContrastiveTrainer(model, criterion, train_loader, args)
trainer = Trainer(gpus=-1, accelerator='ddp', max_epochs=args.epochs, accumulate_grad_batches=args.accum_steps)
trainer.fit(model_sem_kitti)
```

I am using pytorch-lightning==1.1.8

cc @justusschock @kaushikb11 @awaelchli @akihironitta @rohitgr7 @borda

**Comment by WYHbxer** [comment]
> What you would need to know is what is occupying so much space in the first devuce only. I assume it's not the model because each device should have a copy (probably the 2GB you see in the rest of them)

thank u, i will check soon

**Comment by WYHbxer** [comment]
> What you would need to know is what is occupying so much space in the first devuce only. I assume it's not the model because each device should have a copy (probably the 2GB you see in the rest of them)

H，I tested it by debugging. I found that there will be seven copies of the model on gpu0 and one copy on other GPUs. Is this normal when I use DDP strategy?

**Comment by WYHbxer** [comment]
> What you would need to know is what is occupying so much space in the first devuce only. I assume it's not the model because each device should have a copy (probably the 2GB you see in the rest of them)

Based on this finding, after I checked the code. I found that if I change the code
```
self.model_q = model(in_channels=4 if args.use_intensity else 3, out_channels=latent_features[args.sparse_model]).type(dtype)
self.head_q = model_head(in_channels=latent_features[args.sparse_model], out_channels=args.feature_size).type(dtype)
self.model_k = model(in_channels=4 if args.use_intensity else 3, out_channels=latent_features[args.sparse_model]).type(dtype)
self.head_k = model_head(in_channels=latent_features[args.sparse_model], out_channels=args.feature_size).type(dtype)
```
to
```
self.model_q = model(in_channels=4 if args.use_intensity else 3, out_channels=latent_features[args.sparse_model])
self.head_q = model_head(in_channels=latent_features[args.sparse_model], out_channels=args.feature_size)
self.model_k = model(in_channels=4 if args.use_intensity else 3, out_channels=latent_features[args.sparse_model])
self.head_k = model_head(in_channels=latent_features[args.sparse_model], out_channels=args.feature_size)
```
the GPU load is balance, just like 
![`HIR{7EUO{MKT97 @O4FM(3](https://user-images.githubusercontent.com/79640383/170486885-db473f73-da39-46a0-afb9-5138dfffb1c7.png)
But after I canceled this operation, my code became very slow. Even if I increase the batch size, I can't reach the original running speed. Why is this?

**Comment by carmocca** [comment]
Why did you want to set the `dtype` manually? Are you using `Trainer(precision=...)`?

**Comment by WYHbxer** [comment]
> max_epochs

well, I'm trying to use the code of this paper: [https://github.com/PRBonn/segcontrast].
In his code, he set the dtype manually. I found the training process very slow, so I'm trying to speed up the training.
I am not using Trainer(precision=...)
thank u for your reply, and is there any way to speed it up?

**Comment by zxk19981227** [comment]
i also met this problem, but i only have four 3090 rather than eight. The training strategy of 'ddp' occupys about 10 more gb on gpu 0 compared with gpu1 2 3. Is there any solutions?

**Comment by zxk19981227** [comment]
![image](https://user-images.githubusercontent.com/40291547/181246311-737637c0-7000-4f69-87b7-36e8c40f791d.png)

**Comment by awaelchli** [comment]
@zxk19981227 Could you please confirm that you are using the latest PyTorch Lightning version 1.6.x? The OP posted `pytorch-lightning==1.1.8` which around that time had exactly these issues we had to fix.

**Comment by awaelchli** [comment]
Closing because this issue is stale, due to lack of responses and reproducible examples. If problems arise with newer versions of Lightning, please open a new issue with the required details, thanks!

**Comment by RomanKoshkin** [comment]
Same problem here
<img width="583" alt="image" src="https://github.com/Lightning-AI/lightning/assets/26285991/fb79b189-4db2-4120-b745-28f6cb1a314c">
with 
torch=1.10.1+cu111
lightning=1.9.4

Tried every possible strategy, get four copies of (apparently) the same model on device 0. Any clues why?

**Comment by YanhaoWu** [comment]
I found that if you do not use .cuda() before trainer, the problem can be solved some times.


&nbsp;


伍彦豪
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Roman ***@***.***&gt;; 
发送时间: 2023年6月28日(星期三) 上午8:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Lightning-AI/lightning] GPU load imbalance (Issue #13135)





 
Same problem here
 
 with
 torch=1.10.1+cu111
 lightning=1.9.4
 
Tried every possible strategy, get four copies of (apparently) the same model on device 0. Any clues why?

**Comment by RomanKoshkin** [comment]
<img width="595" alt="image" src="https://github.com/Lightning-AI/lightning/assets/26285991/f0fe020f-8b25-4c4a-8f90-5ee719b0761c">
I works now after installing the latest `lightning==2.0.4` (which upgraded my Pytorch to 2.0.x, triton and deepspeed).
