### ISSUE TITLE
Is there a way to save a checkpoint with a time interval and also at the end of epochs?

### ISSUE THREAD

**Issue by fishbotics** [Lightning-AI/lightning#13227]
I started the following as a discussion, but realized it's likely more of an issue. 

In the `ModelCheckpoint` class, it seems that I can't checkpoint every N hours as well as after every epoch. I want to do both so that I can load my model for inference mid-epoch, but that I can restart training with a model saved after an epoch.

You can see the documentation note here: 
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/callbacks/model_checkpoint.py#L128

I tried this by doing 
```
ModelCheckpoint(                                               
    monitor="val_loss",                                        
    save_last=True,                                            
    dirpath=dirpath,                                           
    train_time_interval=timedelta(minutes=30),
    save_on_train_epoch_end=True,                              
)                                                              
                                                               
```

But all I see in the checkpoint directory `dirpath` is the best one and `last.ckpt`. I would like to see three things: the most recent checkpoint, the best checkpoint, and the most recent end-of-epoch checkpoint.

Thanks!

### Discussed in https://github.com/PyTorchLightning/pytorch-lightning/discussions/13226

<div type='discussions-op-text'>

<sup>Originally posted by **fishbotics** June  3, 2022</sup>
Looking at the code, it seems like I need to choose whether to checkpoint every so often or after every epoch. My epochs are very long (40 hours), so I need to checkpoint more often. But, I'd like to be able to resume training if a job dies and this seems to only be possible if  I use the fault tolerant training or saving after the end of an epoch. I'd like to do the latter. Any ideas?</div>

cc @carmocca @awaelchli @ninginthecloud @jjenniferdai @rohitgr7

**Comment by fishbotics** [comment]
Going down the rabbit hole here, it looks like the call to save at epoch end is the same as the call to save `last.ckpt`:

https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/callbacks/model_checkpoint.py#L309

this then call this:

https://github.com/PyTorchLightning/pytorch-lightning/blob/83436ee3dfd0d4079e0f8e704ba76aca672af19d/pytorch_lightning/callbacks/model_checkpoint.py#L638

It looks like this might be possible with multiple checkpoint callbacks. Can anyone confirm?

**Comment by carmocca** [comment]
Yes! The correct solution is to instantiate separate ModelCheckpoint callbacks with their own configuration and pass them to `Trainer(callbacks=[...])`
