### ISSUE TITLE
Erroneous UserWarning for unset max_epochs 

### ISSUE THREAD

**Issue by adamjstewart** [Lightning-AI/lightning#13257]
## 🐛 Bug

When I use:
```python
Trainer(fast_dev_run=True)
```
I see the following warning:
```
pytorch_lightning.utilities.warnings.PossibleUserWarning: `max_epochs` was not set. Setting it to 1000 epochs. To train without an epoch limit, set `max_epochs=-1`.
```
However, `fast_dev_run=True` implies `max_epochs=1`, so shouldn't this warning be skipped?

### To Reproduce

Use code like:
```python
Trainer(fast_dev_run=True)
```
in your code with warnings enabled or captured by pytest.

### Expected behavior

No warning message.

### Environment

- PyTorch Lightning Version (e.g., 1.5.0): 1.6.4
- PyTorch Version (e.g., 1.10): 1.11.0
- Python version (e.g., 3.9): 3.10.4, etc.
- OS (e.g., Linux): Linux, etc.
- CUDA/cuDNN version: N/A
- GPU models and configuration: N/A
- How you installed PyTorch (`conda`, `pip`, source): pip
- If compiling from source, the output of `torch.__config__.show()`: N/A
- Any other relevant information: N/A

cc @justusschock @kaushikb11 @awaelchli @borda @rohitgr7

**Comment by akihironitta** [comment]
@adamjstewart Thank you for submitting the issue!

I don't have a strong preference, but I find it reasonable to raise the warning even when `fast_dev_run` is specified because one will have to deal with the warning anyway once `fast_dev_run` is disabled. :eyes:

**Comment by adamjstewart** [comment]
In my case, this is inside a unit test, so `fast_dev_run` will never be disabled. If `fast_dev_run==True`, we only run a single batch, so warning about setting `max_epochs` to 1000 seems odd.
