### ISSUE TITLE
Loggers in trainer not documented.

### ISSUE THREAD

**Issue by jzazo** [Lightning-AI/lightning#13315]
## 📚 Documentation

Hi! I think you documented recently [`logger`](https://pytorch-lightning.readthedocs.io/en/stable/common/lightning_module.html#logger) and [`loggers`](https://pytorch-lightning.readthedocs.io/en/stable/common/lightning_module.html#loggers) for lightning modules. However, the same interface is not documented for `Trainer`, and it feels natural that they behave the same, doesn't it?

I think that `trainer` has both `logger` and `loggers` as properties. Shall both then be documented? Thank you!

cc @borda @rohitgr7

**Comment by akihironitta** [comment]
Hi @jzazo thanks for reporting this!

I might be missing where exactly it should be documented, but it's already documented at the following page:
- https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_module.html#loggers
- https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html#loggers

**Comment by jzazo** [comment]
Ohh, sorry, I missed it, you are right. Apologies.
