### ISSUE TITLE
[Docs] The link for lightning_lite.rst is not found

### ISSUE THREAD

**Issue by Keiku** [Lightning-AI/lightning#13319]
I can't find the link for lightning_lite.rst in the following document. please confirm it.

> The transition through [LightningLite](https://pytorch-lightning.readthedocs.io/en/stable/starter/lightning_lite.rst) from pure PyTorch is optional but it might be helpful to learn about it.

https://github.com/Lightning-AI/lightning/tree/master/examples/pl_basics

cc @borda @rohitgr7

**Comment by akihironitta** [comment]
Hi @Keiku thank you for your report. The correct link is:
- https://pytorch-lightning.readthedocs.io/en/stable/starter/lightning_lite.html.

Would it be possible for you to send a quick PR to fix this? It'd be greatly appreciated.

**Comment by Keiku** [comment]
I was busy for a while. Thank you for fixing the link.
