### ISSUE TITLE
[Docs] Missing "mnist_examples" folder in lightning/examples/pl_basics

### ISSUE THREAD

**Issue by Keiku** [Lightning-AI/lightning#13336]
`README.md` contains an execution example of the program in `mnist_examples`, but `mnist_examples` does not exist. If the code exists in any branch or in the past, recover it.

I wanted to solve the broken link of `lightning_lite.rst` together with this problem, but the PR https://github.com/Lightning-AI/lightning/pull/13331 of only the fix of the link has been issued.

cc @borda @rohitgr7

**Comment by akihironitta** [comment]
Thanks for reporting the issue. I believe they are moved to https://github.com/Lightning-AI/lightning/tree/master/examples/convert_from_pt_to_pl. Any PR to fix broken links/directories will be appreciated!

**Comment by Keiku** [comment]
@akihironitta Sorry for the late reply.

Should I move `convert_from_pt_to_pl` to `pl_basics` as `mnist_examples` or leave `convert_from_pt_to_pl` and remove "MNIST Examples" from the `README.md` in `pl_basics`?

**Comment by akihironitta** [comment]
@Keiku I think simply updating the link would suffice as it seems like @Borda restructured it in the current way on purpose.

**Comment by Keiku** [comment]
@akihironitta Do you mean to keep the "MNIST Examples" in `pl_basics/README.md` and change those paths as follows?

* Current command
```bash
# CPU
python mnist_examples/image_classifier_1_pytorch.py
```

* New command
```bash
# CPU
python ../convert_from_pt_to_pl/image_classifier_1_pytorch.py
```

"MNIST Examples" is duplicated, is that okay?

**Comment by Keiku** [comment]
@akihironitta With the latest version `1.6.4`, `pytorch_lightning.demos` seems to disappear.

```
⋊> ~/l/c/l/e/convert_from_pt_to_pl on master ⨯ python image_classifier_1_pytorch.py
Traceback (most recent call last):
  File "image_classifier_1_pytorch.py", line 28, in <module>
    from pytorch_lightning.demos.boring_classes import Net
ModuleNotFoundError: No module named 'pytorch_lightning.demos'
⋊> ~/l/c/l/e/convert_from_pt_to_pl on master ⨯ 
```

**Comment by Keiku** [comment]
After adding the following, I worked.

```python
import sys
sys.path.insert(0,'../../../')
```

**Comment by Keiku** [comment]
I'm making a PR now. Please wait.
