### ISSUE TITLE
Not working with python version 3.9-dev

### ISSUE THREAD

**Issue by martinosorb** [Lightning-AI/lightning#13347]
## 🐛 Bug

Pytorch lightning fails to import on python 3.9-dev (3.9.12+) due to the use of Version on an inappropriately formatted version string:

```
File ~/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/pytorch_lightning/utilities/imports.py:90, in <module>
     88 _IS_WINDOWS = platform.system() == "Windows"
     89 _IS_INTERACTIVE = hasattr(sys, "ps1")  # https://stackoverflow.com/a/64523765
---> 90 _PYTHON_GREATER_EQUAL_3_8_0 = Version(platform.python_version()) >= Version("3.8.0")
     91 _TORCH_GREATER_EQUAL_1_8_1 = _compare_version("torch", operator.ge, "1.8.1")
     92 _TORCH_GREATER_EQUAL_1_9 = _compare_version("torch", operator.ge, "1.9.0")

...

InvalidVersion: Invalid version: '3.9.12+'
```

### To Reproduce

`import pytorch_lightning` on my setup with python 3.9-dev.

### Expected behavior

The version check should not be based on `platform.python_version()`, as this is a string and apparently it's not PEP 440-compliant. There are better ways to get python version in a machine-readable way.

### Environment

* CUDA:
	- GPU:
		- NVIDIA GeForce RTX 3070 Laptop GPU
	- available:         True
	- version:           11.3
* Packages:
	- numpy:             1.21.6
	- pyTorch_debug:     False
	- pyTorch_version:   1.12.0.dev20220517+cu113
	- tqdm:              4.64.0
	- pytorch-lightning       1.6.4
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.9.12+
	- version:           #42-Ubuntu SMP Thu Jun 9 23:42:32 UTC 2022
 of `torch.__config__.show()`:

**Comment by awaelchli** [comment]
Hello

> There are better ways to get python version in a machine-readable way.

What is your suggestion concretely?

The only other way I know is through `sys.version_info`. Could you check on your system with python 3.9-dev that the comparison `sys.version_info >= (3, 8)` holds true? If so, we can update it to use that.

**Comment by awaelchli** [comment]
Would you be open to submit a PR with a fix?

**Comment by martinosorb** [comment]
The correct way seems to be `(sys.version_info.major, sys.version_info.minor) >= (3, 8)` (per comments [here](https://stackoverflow.com/questions/68978170/how-to-compare-python-version-against-sys-version-info)).

Will try it out.

**Comment by martinosorb** [comment]
See PR. I could only run standalone tests.
