### ISSUE TITLE
Enable PyTorch 1.12 testing

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lightning#13348]
## 🚀 Feature

See title. This needs to be done before the next feature release.

The 1.12 release is planned for 06/28

### Motivation

Make sure latest and greatest works well
______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @carmocca @akihironitta @borda

**Comment by Borda** [comment]
Is it already on Conda test channel?

**Comment by carmocca** [comment]
I think so, this is what the PyTorch team shared:

Following are instructions on how to download different versions of RC for testing.
Please note: MacOS M1 builds are available now (both wheels and conda), please evaluate them.
CONDA CPU:
Windows/LInux:
conda install pytorch torchvision torchaudio cpuonly -c pytorch-test
MacOS:
conda install pytorch torchvision torchaudio -c pytorch-test
CUDA 11.3, 11.6
Windows/Linux:
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch-test
conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch-test
PIP CPU:
Windows/Linux/MacOS:
pip3 install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/test/cpu/torch_test.html
PIP CUDA 11.3, 11.6
Windows/Linux
pip3 install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/test/cu113/torch_test.html
pip3 install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/test/cu116/torch_test.html
PIP ROCM 5.1.1
pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/test/rocm5.1.1/
Libtorch:
CPU Linux:
(Pre-cxx11 ABI):
https://download.pytorch.org/libtorch/test/cpu/libtorch-shared-with-deps-latest.zip
(cxx11 ABI):
https://download.pytorch.org/libtorch/test/cpu/libtorch-cxx11-abi-shared-with-deps-latest.zip
CPU Windows:
Download here (Release version):
https://download.pytorch.org/libtorch/test/cpu/libtorch-win-shared-with-deps-latest.zip
Download here (Debug version):
https://download.pytorch.org/libtorch/test/cpu/libtorch-win-shared-with-deps-debug-latest.zip
CPU MacOS:
https://download.pytorch.org/libtorch/test/cpu/libtorch-macos-latest.zip
CUDA 11.3, 11.6 Linux
(Pre-cxx11 ABI):
https://download.pytorch.org/libtorch/test/cu113/libtorch-shared-with-deps-latest.zip
https://download.pytorch.org/libtorch/test/cu116/libtorch-shared-with-deps-latest.zip
(cxx11 ABI):
https://download.pytorch.org/libtorch/test/cu113/libtorch-cxx11-abi-shared-with-deps-latest.zip
https://download.pytorch.org/libtorch/test/cu116/libtorch-cxx11-abi-shared-with-deps-latest.zip
Windows CUDA 11.3, 11.6
(Release version):
https://download.pytorch.org/libtorch/test/cu113/libtorch-win-shared-with-deps-latest.zip
https://download.pytorch.org/libtorch/test/cu116/libtorch-win-shared-with-deps-latest.zip
(Debug version):
https://download.pytorch.org/libtorch/test/cu113/libtorch-win-shared-with-deps-debug-latest.zip
https://download.pytorch.org/libtorch/test/cu116/libtorch-win-shared-with-deps-debug-latest.zip

**Comment by akihironitta** [comment]
This will be closed by #13716.
