### ISSUE TITLE
Disable Progress bars for Train/Validation/Predict separately

### ISSUE THREAD

**Issue by CompRhys** [Lightning-AI/lightning#13358]
## 🚀 Feature

Currently we can turn off progress bars by setting `enable_progress_bar=False` but this is an all or nothing solution. 

### Motivation

I am using PL trainer to make predictions in a small customer facing prototype, the progress bars make the output look very different to the previous solution we are proposing a drop in solution for. We can disable all the progress bars but it's useful to have them for monitoring training even if we do not want them when calling predict.

### Pitch

Additional kwargs to disable progress bars for `Trainer.predict` calls

cc @justusschock @kaushikb11 @awaelchli @borda @rohitgr7

**Comment by carmocca** [comment]
You could create a new `Trainer` instance for prediction with the progress bar disabled.

**Comment by rohitgr7** [comment]
> This function would basically gather all the initial kwargs and update them with the given kwargs

just wondering how it will work in case the kwargs states are updated during `trainer.some_call`. For eg. logger, callbacks, etc.

**Comment by justusschock** [comment]
@rohitgr7 there are two possible options for this:
either we say that this is expected (so we don't care about this) as for example when you call .test on the new trainer, you'd want the checkpointing callback to already have the correct checkpoints for best model etc. from the preceeding training

The second thing would be to reset the original state (could be done for example by dumping an initial checkpoint, which we then load again)

**Comment by carmocca** [comment]
@justusschock We discussed adding such function in the past. I think it makes sense.

Do you mind writing a proposal in a separate issue about it? Closing this as I don't want to sidetrack the original question.
