### ISSUE TITLE
Cannot get access to Slack

### ISSUE THREAD

**Issue by MarcSkovMadsen** [Lightning-AI/lightning#13406]
## 🐛 Bug

I cannot get access to Slack. I would like to join.

### To Reproduce

1. Click the link https://pytorch-lightning.slack.com/signup#/domain-signup
2. Click *Continue with Google"

### Expected behavior

I would expect to be able to join.

Instead I cannot because `...@gmail.com` is not a valid domain.

![image](https://user-images.githubusercontent.com/42288570/175757733-eb9578d6-06a9-439e-9bb4-e2b4b8055aa2.png)

cc @borda @rohitgr7

**Comment by akihironitta** [comment]
@MarcSkovMadsen Thank you for reporting this issue. Could you try this new link?
https://join.slack.com/t/pytorch-lightning/shared_invite/zt-1b6lkirxt-9b3ehI0P_31YIqQ4_Dum1A

The old link in the following web pages will be updated shortly:
- https://pytorchlightning.ai/community
- https://lightning.ai/

Let us know if there're any other places where we need to update the link.

**Comment by JackCaster** [comment]
@akihironitta How do I get access to Slack, the [link](https://pytorch-lightning.slack.com/join/shared_invite/zt-1dm4phlc0-84Jv9_8Mp_tWraICOJ467Q#/shared-invite/email) I found in the [forums section](https://lightning.ai/forums/) still expects a verified domain.

**Comment by Borda** [comment]
> How do I get access to Slack, the [link](https://pytorch-lightning.slack.com/join/shared_invite/zt-1dm4phlc0-84Jv9_8Mp_tWraICOJ467Q#/shared-invite/email) I found in the [forums section](https://lightning.ai/forums/) still expects a verified domain.

Hello, we have migrated to [discord](https://discord.com/invite/tfXFetEZxv).
