### ISSUE TITLE
is_last_batch isn't documented

### ISSUE THREAD

**Issue by alealv** [Lightning-AI/lightning#13471]
Hi, I see that `is_last_batch` trainer property isn't documented in https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#properties.

I was lucky to find it [here](https://pytorch-lightning.readthedocs.io/en/stable/common/optimization.html#manual-optimization).

I feel it would be helpful to have all properties listed there.

Thanks.

cc @borda @rohitgr7 @akihironitta

**Comment by carmocca** [comment]
Thanks for the suggestion. Would you like to open a PR adding it?

You can modify this file https://github.com/Lightning-AI/lightning/blob/master/docs/source-pytorch/common/trainer.rst and perhaps add a docstring for it here: https://github.com/Lightning-AI/lightning/blob/dd9fad42d5cfdd7b9f4ab8a84c13794f0bb58ff4/src/pytorch_lightning/trainer/trainer.py#L2577

**Comment by bibhabasumohapatra** [comment]
added a PR, my first PR in Lightning. let me know if anything more needs to be added.
