### ISSUE TITLE
load_from_checkpoint has different validation results

### ISSUE THREAD

**Issue by lanlanlan3** [Lightning-AI/lightning#13485]
when save ckpt, it has some metrics like val_acc=0.77.
but when load_from_checkpoint, trainer.validate(model), I got val_acc=0.02

code：
from main_pl import LitModel
ckpt_path = '...val_acc=0.77.ckpt'
model = LitModel.load_from_checkpoint(ckpt_path)
'''model.eval()'''
trainer = Trainer(gpus=-1)
'''or trainer = Trainer(gpus=-1, resume_from_checkpoint=ckpt_path)'''
trainer.validate(model) # val_acc=0.02

env:
mac m1 python 3.9 and linux python 3.10
torch 1.11

**Comment by justusschock** [comment]
duplicate to #13484
