### ISSUE TITLE
load_from_checkpoint has different validation results

### ISSUE THREAD

**Issue by lanlanlan3** [Lightning-AI/lightning#13484]
when save ckpt, it has some metrics like val_acc=0.77.
but when load_from_checkpoint, trainer.validate(model), I got val_acc=0.02

code：
from main_pl import LitModel
ckpt_path = '...val_acc=0.77.ckpt'
model = LitModel.load_from_checkpoint(ckpt_path)
'''model.eval()'''
trainer = Trainer(gpus=-1)
'''or trainer = Trainer(gpus=-1, resume_from_checkpoint=ckpt_path)'''
trainer.validate(model) # val_acc=0.02

env:
mac m1 python 3.9 and linux python 3.10
torch 1.11

cc @awaelchli @ananthsub @ninginthecloud @rohitgr7 @otaj @carmocca @jjenniferdai

**Comment by justusschock** [comment]
Hey, thanks for the issue.

Can you give us your model definition or a minimum example of the boring model to reproduce this?

**Comment by rohitgr7** [comment]
please consider opening either a discussion or an issue. Answered [here](https://github.com/Lightning-AI/lightning/discussions/13482). We can continue the discussion there. Closing this for now.

**Comment by justusschock** [comment]
Thanks @rohitgr7 didn't see this
