### ISSUE TITLE
No tabs when a Lightning App only contains one Web UI

### ISSUE THREAD

**Issue by MarcSkovMadsen** [Lightning-AI/lightning#13511]
## 🚀 Feature

When my lightning app only contains one Web UI there is no reason to add a tab at the top of the app that takes up space.

### Motivation

- This would simplify the UI
- This would provide more window space to the app it self
- This would make the app look more professional.

![image](https://user-images.githubusercontent.com/42288570/177009976-4e89ed42-cdde-4a04-9bff-53cc343415bd.png)

**Comment by lantiga** [comment]
Yep, definitely on the radar. Thanks for bringing this up @MarcSkovMadsen

**Comment by awaelchli** [comment]
@MarcSkovMadsen This was recently enabled in the frontend and will come with the next release, if it hasn't already. 
Here are the [docs](https://lightning.ai/lightning-docs/workflows/arrange_tabs/arrange_app_basic.html#enable-a-full-page-single-tab) and you just make sure to return a single element in the configure_layout at the root.

**Comment by awaelchli** [comment]
This has been supported for a while now, so closing the issue :)
