### ISSUE TITLE
`WandbLogger` not resuming with resubmitted SLURM job

### ISSUE THREAD

**Issue by SpontaneousDuck** [Lightning-AI/lightning#13524]
## 🐛 Bug

I am using the auto-resubmission function of PyTorch Lightning with my SLURM cluster. My code does detect the signal sent by SLURM and successfully pauses and resumes training with the auto-resubmission function. Training resumes at the correct epoch and global_step but the `wandb` logger starts a new run at step 0. Is there a recommended way to accomplish this? It appears like the logger will let you pass `version` or `id` to allow resuming. Should I just use the SLURM job number (`version=os.environ["SLURM_JOB_ID"]`)?

### To Reproduce

My `sbatch` script:
```
#!/bin/bash
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --gres=gpu:p100:1
#SBATCH --cpus-per-task=8
#SBATCH --time=08:00:00
#SBATCH --job-name=test_training
#SBATCH --mem=32GB
#SBATCH --ntasks=1
#SBATCH --output=slurm_outputs/test_training.%j.out
#SBATCH --error=slurm_outputs/test_training.%j.err
#SBATCH --signal=SIGUSR1@90
#SBATCH --requeue

source /home/user/.bashrc
conda activate test_env

# debugging flags (optional)
export NCCL_DEBUG=INFO
export PYTHONFAULTHANDLER=1

srun python train.py
```

`Trainer` configuration:
```
wandb_logger = WandbLogger(project="test", name="test1")
trainer = Trainer(logger=wandb_logger, gpus=1, max_epochs=20, deterministic=True, enable_progress_bar=False)
```

### Expected behavior

Resume logging to the original WandB run after resubmission at the correct step.

### Environment

- PyTorch Lightning Version (e.g., 1.5.0): 1.6.4
- PyTorch Version (e.g., 1.10): 1.11
- Python version (e.g., 3.9): 3.10.5
- OS (e.g., Linux): Linux
- How you installed PyTorch (`conda`, `pip`, source): conda
- Any other relevant information: 
- SURM version: 21.08.8
- wandb version: 0.12.20

cc @borda @awaelchli @morganmcg1 @AyushExel @borisdayma @scottire @manangoel99

**Comment by SpontaneousDuck** [comment]
Got it! Grabbing the Job ID from the env variable allows me to resume.

**Comment by carmocca** [comment]
Closing as there's a workaround. #5342 is kept open for logger state restoration
