### ISSUE TITLE
`LightningModules` without a `log` method?

### ISSUE THREAD

**Issue by SimonCoste** [Lightning-AI/lightning#13536]
[See additional comment at the end - to be closed]

Hi, I just installed torch-lightning (using `conda install -c conda-forge pytorch-lightning`) and my `LightningModules` do not seem to have a `self.log` method. Here is a MWE:
```
import os

import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


model = BoringModel()

model.log

```
which leads to 

```
AttributeError                            Traceback (most recent call last)
/users/data/coste/ReweighedEBM/main.ipynb Cell 13' in <cell line: 48>()
     [43](vscode-notebook-cell://ssh-remote%2Bdigitale/users/data/coste/ReweighedEBM/main.ipynb#ch0000012vscode-remote?line=42)         return torch.optim.SGD(self.layer.parameters(), lr=0.1)
     [46](vscode-notebook-cell://ssh-remote%2Bdigitale/users/data/coste/ReweighedEBM/main.ipynb#ch0000012vscode-remote?line=45) model = BoringModel()
---> [48](vscode-notebook-cell://ssh-remote%2Bdigitale/users/data/coste/ReweighedEBM/main.ipynb#ch0000012vscode-remote?line=47) model.log

File ~/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py:1207, in Module.__getattr__(self, name)
   1205     if name in modules:
   1206         return modules[name]
-> 1207 raise AttributeError("'{}' object has no attribute '{}'".format(
   1208     type(self).__name__, name))

AttributeError: 'BoringModel' object has no attribute 'log'
```

### Expected behavior

No bug. 

### Environment
* CUDA:
	- GPU:
		- Tesla P100-PCIE-16GB
		- Tesla P100-PCIE-16GB
		- Tesla P100-PCIE-16GB
		- Tesla P100-PCIE-16GB
		- Tesla P100-PCIE-16GB
		- Tesla P100-PCIE-16GB
		- Tesla P100-PCIE-16GB
	- available:         True
	- version:           10.2
* Packages:
	- numpy:             1.22.3
	- pyTorch_debug:     False
	- pyTorch_version:   1.12.0
	- pytorch-lightning: 0.8.5
	- tqdm:              4.64.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.9.12
	- version:           #193-Ubuntu SMP Tue Sep 17 17:42:52 UTC 2019

### Additional context

I just realized that my torch-lightning version seems to be 0.8.5 even though I just installed it. Why ?

###  Edit/Solution

It turned out that I used `conda install -c conda-forge pytorch-lightning` to install PL (note the `-` instead of `_`). Installing things correctly leads to a recent version (1.6.4) and no bugs - can be closed.

cc @carmocca @justusschock @awaelchli @borda @ananthsub @ninginthecloud @jjenniferdai @rohitgr7

**Comment by akihironitta** [comment]
Closing this issue as per your comment:

> It turned out that I used `conda install -c conda-forge pytorch-lightning` to install PL (note the `-` instead of `_`). Installing things correctly leads to a recent version (1.6.4) and no bugs - can be closed.
