### ISSUE TITLE
How to get the output of the previous iteration ,and use them in the current epoch?, thanks

### ISSUE THREAD

**Issue by emilyemliyM** [Lightning-AI/lightning#13552]
## 🐛 Bug

Dear author,

How can I  get the output of the previous iteration or epoch ,and the  I  can use them in the current epoch?, thanks
I want to use the output of the previous epoch as one of the features of the input of the current epoch (in the order of the index of the same dataloader).

Best regards.

- PyTorch Lightning Version (e.g., 1.5.0):
- PyTorch Version (e.g., 1.10):
- Python version (e.g., 3.9):
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

**Comment by lodo1995** [comment]
I'm not sure I'm understanding your question (and I'm not a Lightning maintainer), but have you looked into the many [hooks](https://pytorch-lightning.readthedocs.io/en/stable/common/lightning_module.html#hooks) that `LightningModule` provides, such as `on_train_start`, `on_train_epoch_start`, `on_train_epoch_end` and `on_train_end`?

For example, you can use `on_train_start` to create two instance variables, one to store the outputs of the previous epoch, another to store the outputs of the current epoch. In `train_step` you can read the variable of the previous epoch and update the variable of the current epoch. In `on_train_epoch_end` you can move the current epoch variable into the previous epoch variable and reset the current epoch variable to empty. In `on_train_end` you can cleanup both variables to avoid consuming memory unnecessarily.

If this is not enough, maybe you can provide more details about what you are trying to do?
