### ISSUE TITLE
Disable Intercepting Ctrl-C

### ISSUE THREAD

**Issue by vedantroy** [Lightning-AI/lightning#13560]
## 🚀 Feature

Allow users to disable pytorch lightning's ctrl-c interrupt.

### Motivation

I have a custom cleanup process for Ctrl-C, which allows me to handle wandb. Right now, when I press Ctrl-C, pytorch lightning handles the exit process for me, which is not ideal.

### Pitch

A boolean flag that when set to `True`, causes pytorch lightning to rethrow the interrupt.

### Alternatives

Currently mucking around with using the `signal` package.

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @carmocca @awaelchli @borda @ninginthecloud @rohitgr7

**Comment by akihironitta** [comment]
You can plug your logic into `Callback.on_exception` hook
https://pytorch-lightning.readthedocs.io/en/1.6.4/extensions/callbacks.html?highlight=on_exception#on-exception
which is called at:
https://github.com/Lightning-AI/lightning/blob/61c28cb428a13c2aea6d7f3f55e0f00431a4ea4e/src/pytorch_lightning/trainer/trainer.py#L657-L662

**Comment by zouharvi** [comment]
For anyone in the future stumbling on this topic, this worked for me:

```
    class PropagateExitCallback(Callback):
        def on_exception(self, trainer, pl_module, exception):
            exit()


    trainer = L.Trainer(
        ...
        callbacks=[
            ...
            PropagateExitCallback(),
        ]
    )
   
```
