### ISSUE TITLE
CI: Enable readthedocs to build docs on pull requests

### ISSUE THREAD

**Issue by akihironitta** [Lightning-AI/lightning#13572]
*(this feature requires the admin privilege on Read the Docs)*

## 🚀 Feature
Can be configured from https://readthedocs.org/projects/pytorch-lightning/.
See https://docs.readthedocs.io/en/stable/pull-requests.html#configuration for details.

### Motivation
- This feature ensures the exact same environment for building docs between in each PR and in the readthedocs deployment 🚀
- (@Borda might have some thoughts on dropping CircleCI https://github.com/Lightning-AI/lightning/pull/13547#discussion_r915523547.)

### Pitch
- Enable building docs on each PR following the instructions: https://docs.readthedocs.io/en/stable/pull-requests.html
- Drop CircleCI job.

### Alternatives
Continue to use CircleCI.

### Additional context
https://github.com/readthedocs/readthedocs-docker-images/issues/186

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @carmocca @akihironitta @borda

**Comment by akihironitta** [comment]
@Borda @ethanwharris Could you take this? (as I see you two are the maintainers at https://readthedocs.org/projects/pytorch-lightning/)

**Comment by Borda** [comment]
@akihironitta does this support building multiple docs built from single repo as we have it atm?
Maybe we can hold this till we fuse both docs :rabbit:

**Comment by akihironitta** [comment]
Had a look at the readthedocs documentation, but still not sure if one repository can have multiple documentations...
- https://docs.readthedocs.io/en/stable/config-file/v2.html#sphinx

---

> Maybe we can hold this till we fuse both docs 🐰

Yes, definitely. (I'm not really following the plan of docs fusion... are we going to host both of them in readthedocs or in gh-pages?)

**Comment by akihironitta** [comment]
@carmocca I think we can proceed forward with this because we'll keep hosting the pl docs on readthedocs after pl and app docs are fused, AFAIK.

cc @Borda as this is something only the readthedocs admin can address.

**Comment by carmocca** [comment]
CircleCI has been removed now. Can we close this?

**Comment by akihironitta** [comment]
Looking at the change in #15460, we will not be using readthedocs.org anymore.

@Borda Could you close this issue if it's no longer relevant?

**Comment by Borda** [comment]
> Looking at the change in #15460, we will not be using readthedocs.org anymore.

we will, but readhedocs does not allow build multiple packages from single repo AFAIK
sp, we still keep rtfd.org and building our own

**Comment by akihironitta** [comment]
Could we consider moving forward with this? Enabling docs build in each PR could've prevented PL docs build failure which is currently being fixed by #15511.

**Comment by Borda** [comment]
@akihironitta just set, could you pls verify?

**Comment by akihironitta** [comment]
<img width="771" alt="image" src="https://user-images.githubusercontent.com/20610905/200460489-4a5eb863-76e8-4a59-a1a8-56fd7e65ba0c.png">
