### ISSUE TITLE
Not able to run a GPU task when transform to Pytorch lightning (GPU mem usage problem)

### ISSUE THREAD

**Issue by charlesxu90** [Lightning-AI/lightning#13588]
## Question

After transform my code to Pytorch Lightning, the code that I originally could run cannot run now. The primary reason is that this code requires a huge GPU memory. Originally, the GPU capacity is enable to provide it. However, when transform to Lightning, the CUDA will always out of memory when doing the same task.

I think the GPU memory usage of Pytorch Lightning should be finetuned. Because the primary reason I want to use it is to manage the GPU memory well, and reduce my time on it.

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @justusschock @kaushikb11 @awaelchli @akihironitta @rohitgr7 @borda

**Comment by akihironitta** [comment]
Hello @charlesxu90, thank you for reporting the issue. In some cases, there might be performance degradation with 1.6.0, 1.6.1, 1.6.2 and 1.6.3 as investigated via #12713, but if you're using 1.6.4 or later, this issue is irrelevant to your case.

To investigate the issue further, could you provide your environment details and a reproducible code?

---

FYI, we have parity benchmarks against pure PyTorch at https://github.com/Lightning-AI/lightning/tree/master/tests/tests_pytorch/benchmarks.

**Comment by charlesxu90** [comment]
Dear @akihironitta ,

The current version I'm using is '1.6.4'. I'm running a GPT model following the implementation of [minGPT](https://github.com/karpathy/minGPT).

Previously, I could run with a batch size of 256 on my workstation. However, after updating to Lightning, it almost halve the batch size.

Based on this observation, I think there should be plenty room for improvement.

BTW, I'm using `DDPStrategy(find_unused_parameters=False)`. I'm not sure if this influences or not.

Best regards.

**Comment by akihironitta** [comment]
For the minGPT by @\karpathy in particular, there is a fork adapted with PL by @SeanNaren. https://github.com/SeanNaren/minGPT I believe it's definitely worth referring to the implementation.

By default, PL enables a few features (logging, checkpointing, etc.), so these might be possible causes of your issue. In general, for debugging performance difference between PL and PyTorch, I'd suggest checking the list here: #12398

**Comment by charlesxu90** [comment]
Hi @akihironitta, thanks for the advice. I'll check this minGPT implementation.

BTW, do you have any suggestions for Reformer or Performer implementations using Lightning. I'm trying to implement such efficient attentions in GPT.

Best regards,

**Comment by akihironitta** [comment]
Unfortunately, I'm not aware of specific PL implementations for either of them.

Feel free to reopen this issue if the issue still persists or to create a new issue if any different issue arises.

**Comment by charlesxu90** [comment]
> For the minGPT by @\karpathy in particular, there is a fork adapted with PL by @SeanNaren. https://github.com/SeanNaren/minGPT I believe it's definitely worth referring to the implementation.
> 
> By default, PL enables a few features (logging, checkpointing, etc.), so these might be possible causes of your issue. In general, for debugging performance difference between PL and PyTorch, I'd suggest checking the list here: #12398

Thanks, this implementation is much more memory efficient. It can run the same model on my local workstation.
