### ISSUE TITLE
Hard Coded Ports for Lightning Apps

### ISSUE THREAD

**Issue by oojo12** [Lightning-AI/lightning#13599]
## 🐛 Bug

Currently we hard code the ports for lightning apps with the following snippet:

`APP_SERVER_PORT = 7501` from the constants.py [here
](https://github.com/Lightning-AI/lightning/blob/933848dc05a0698eb5cd5a39216fd175f5e1b920/src/lightning_app/core/constants.py#L16)

### To Reproduce
Try running more than 1 lightning app at a time

### Expected behavior
You're allowed to run more than one lightning app at a time

### Environment
-->
* CUDA:
        - GPU:
        - available:         False
        - version:           None
* Packages:
        - numpy:             1.21.4
        - pyTorch_debug:     False
        - pyTorch_version:   1.9.0+cpu
        - pytorch-lightning: 1.6.3
        - tqdm:              4.64.0
* System:
        - OS:                Windows
        - architecture:
                - 64bit
                - WindowsPE
        - processor:         Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
        - python:            3.9.7
        - version:           10.0.22000

### Additional context
Believe this can be fixed by using the network utility [here](https://github.com/Lightning-AI/lightning/blob/933848dc05a0698eb5cd5a39216fd175f5e1b920/src/lightning_app/utilities/network.py#L19)

Hypothesis:
I think using in src/lightning_app/core/constants.py for the APP_SERVER_PORT and then src/lightning_app/cli/lightning_cli.py would do the trick

Reality:
It seems making those changes on my local branch was not enough and then you get a site cannot be reached error. Is there another place a change needs to be made?

Code:
https://github.com/oojo12/lightning/tree/bug/13599_hard_coded_ports

**Comment by oojo12** [comment]
@tchaton is there someone that can help me with this?

**Comment by awaelchli** [comment]
This has been addressed in #15819, closing 🎉
