### ISSUE TITLE
PyTroch Lightning giving different shapes in training step and validation step with DynUNet from MONAI

### ISSUE THREAD

**Issue by YerePhy** [Lightning-AI/lightning#13596]
You can download [this notebook ](https://github.com/YerePhy/help/blob/main/dyunet.ipynb) for reproducing the problem, in the same [repo](https://github.com/YerePhy/help) you can find a requirements.yaml file.

**Comment by carmocca** [comment]
This is caused by the model being on `eval()` mode during validation!

**Comment by YerePhy** [comment]
Yes, you're right, sorry!
