### ISSUE TITLE
Lightning Docs for installing anaconda version of lightning does not work

### ISSUE THREAD

**Issue by StatQuest** [Lightning-AI/lightning#13627]
I followed the code here for installing lightning via Anaconda:

https://lightning.ai/lightning-docs/

conda install lightning -c conda-forge

...and I get this error...

(base) joshs-imac:~ joshstarmer$ conda install lightning -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - lightning

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

My version of Python is...
(base) joshs-imac:~ joshstarmer$ python --version
Python 3.7.6

My version of Anaconda is...
(base) joshs-imac:~ joshstarmer$ conda -V
conda 4.11.0

cc @borda @rohitgr7

**Comment by awaelchli** [comment]
@StatQuest 
Do our docs somewhere mention the installation using conda forge? 
Replace

```
conda install lightning -c conda-forge
```

with 

```
pip install lightning
```

and this should bring you one step closer :)

**Comment by zippeurfou** [comment]
Yes it does @awaelchli 
<img width="847" alt="Screen Shot 2022-07-12 at 7 36 36 PM" src="https://user-images.githubusercontent.com/4520383/178556880-d5e9b509-f421-403d-a15e-061c5eb778fc.png">
@tchaton mentioned removing it for now until @Borda fix it :D

**Comment by awaelchli** [comment]
Unless we actually plan to have an image on conda forge, I suggest we remove it asap.

**Comment by StatQuest** [comment]
Great thank you very much! :)

**Comment by Borda** [comment]
For tracking the progress: https://github.com/conda-forge/staged-recipes/pull/19715
