### ISSUE TITLE
An important Question: Why does pytorch lightning cause 2x GPU usage ?

### ISSUE THREAD

**Issue by chuzheng88** [Lightning-AI/lightning#13666]
### Discussed in https://github.com/Lightning-AI/lightning/discussions/13648

<div type='discussions-op-text'>

<sup>Originally posted by **chuzheng88** July 14, 2022</sup>
Assumign that my model uses 2G GPU memory, every batch data uses 3G GPU memory. Traning code will use 5G (2+3) GPU memory when I use Pytorch. However, new training code use 8G (2 + 3 + 3) GPU memory when I use Pytorch ligntning. I do not know why ? or new codes are wrong ?
Some new codes described as follows:
![image](https://user-images.githubusercontent.com/17675722/178939905-0575560c-c778-4cf4-a548-59b91b8a4db4.png)

Can you help me ?
</div>

cc @justusschock @kaushikb11 @awaelchli @akihironitta @rohitgr7 @borda

**Comment by akihironitta** [comment]
Let's continue to discuss this in the linked discussion.

**Comment by chuzheng88** [comment]
@akihironitta Ok, but nobody continue to discuss this discussion.

**Comment by akihironitta** [comment]
Hi @chuzheng88, thank you for your patience. I'm replying to your discussion now.
