### ISSUE TITLE
pytorch-lightning 1.6.5 not available on conda-forge

### ISSUE THREAD

**Issue by devanshkv** [Lightning-AI/lightning#13686]
## 🐛 Bug
PyTorch-lightning 1.6.5 not available on conda-forge

### To Reproduce
```bash
conda search pytorch-lightning -c conda-forge
```
which shows:
```bash
.
.
pytorch-lightning              1.6.2    pyhd8ed1ab_0  conda-forge
pytorch-lightning              1.6.3    pyhd8ed1ab_0  conda-forge
pytorch-lightning              1.6.4    pyhd8ed1ab_0  conda-forge
```

### Expected behavior
PyTorch-lightning 1.6.5 should be available on conda-forge?

### Environment

- PyTorch Lightning Version (e.g., 1.5.0): N/A
- PyTorch Version (e.g., 1.10): N/A
- Python version (e.g., 3.9): N/A
- OS (e.g., Linux): Linux
- CUDA/cuDNN version: N/A
- GPU models and configuration: N/A
- How you installed PyTorch (`conda`, `pip`, source): N/A
- If compiling from source, the output of `torch.__config__.show()`: N/A
- Any other relevant information: N/A

### Additional context
None.

cc @tchaton @rohitgr7 @carmocca @akihironitta @borda

**Comment by akihironitta** [comment]
@Borda Is this due to the recent reorganisation/fusion of the repository?

**Comment by Borda** [comment]
Resolved via https://github.com/conda-forge/pytorch-lightning-feedstock/pull/91
