### ISSUE TITLE
AssertionError: If capturable=False, state_steps should not be CUDA tensors.

### ISSUE THREAD

**Issue by franchesoni** [Lightning-AI/lightning#13695]
## 🐛 Bug

When loading checkpoints we get
`AssertionError: If capturable=False, state_steps should not be CUDA tensors.`
This is a note to my future self

### Expected behavior

Things break with pytorch 1.12, which is expected according to:
https://github.com/pytorch/pytorch/issues/80809

### Solutions:
- load the model without the optimizer (manually)
- change `load_optimizer_state_dict` function in `pytorch_lightning/strategies/strategy.py` to:
	```python
    def load_optimizer_state_dict(self, checkpoint: Mapping[str, Any]) -> None:
        optimizer_states = checkpoint["optimizer_states"]
        for optimizer, opt_state in zip(self.optimizers, optimizer_states):
            optimizer.load_state_dict(opt_state)
            optimizer.param_groups[0]['capturable'] = True  # ADDED franchesoni
            optimizer_to_device(optimizer, self.root_device)
	```
- wait for 1.12.1 or downgrade to 1.11

**Comment by franchesoni** [comment]
This is a note to my future self

**Comment by rohitgr7** [comment]
I read somewhere setting `capturable=True` can close some slowdown.
