### ISSUE TITLE
lightning ai website has wrong installation instructions

### ISSUE THREAD

**Issue by StatQuest** [Lightning-AI/lightning#13708]
I'm not sure if this is where I should put this issue. If this is the wrong place, please let me know!
Anyway, https://lightning.ai/lightning-docs/ has instructions on how to install lightning via conda, and this is bad since there is no version of lightning on conda. In theory this was fixed last week, but it appears to have come back to haunt us again.
<img width="1312" alt="Screen Shot 2022-07-18 at 9 22 57 AM" src="https://user-images.githubusercontent.com/10169836/179520825-f9395eaa-e454-4ca8-90e0-34eb3888e265.png">
.

cc @borda @rohitgr7

**Comment by rohitgr7** [comment]
hey Josh!

Might have been missed. Mind send a PR to remove this?

**Comment by akihironitta** [comment]
It seems like no action has been made yet for #13627.

**Comment by rohitgr7** [comment]
let's fix and close it.
