### ISSUE TITLE
Promote the `LightningCLI` out of utilities

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lightning#13737]
## Proposed refactor

`mv src/pytorch_lightning/utilities/cli.py src/pytorch_lightning`

### Motivation

The tool is much stabler and our recommended CLI tool for PL

### Pitch

Move the source code
Add a deprecation for the previous class
Move the test file
Update usages across repository

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @justusschock @awaelchli @rohitgr7 @tchaton @carmocca @mauvilsa

**Comment by tchaton** [comment]
@carmocca @awaelchli @justusschock 

Let's add move `LightningCLI` to `pytorch_lightning.cli.LightningCLI`, so it is more discoverable and the import path looks better.
