### ISSUE TITLE
from lightning.pytorch import strategies import breaks.

### ISSUE THREAD

**Issue by tchaton** [Lightning-AI/lightning#13730]
### To Reproduce

From master.

![image](https://user-images.githubusercontent.com/12861981/179722999-f2c0baac-66ee-452f-ad20-73e3af0e1058.png)

### Environment

- PyTorch Lightning Version (e.g., 1.5.0):
- PyTorch Version (e.g., 1.10):
- Python version (e.g., 3.9):
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

cc @carmocca @akihironitta @borda @tchaton @rohitgr7

**Comment by carmocca** [comment]
So this is caused by a bug in the wrapper generation logic. In lightning/pytorch/strategies/__init__.py it puts
```py
from pytorch_lightning.strategies import STRATEGIES_BASE_MODULE  # noqa: F401
call_register_strategies(STRATEGIES_BASE_MODULE)
```
which shouldn't be copied
