### ISSUE TITLE
Add Lightning packages to collect_env_details

### ISSUE THREAD

**Issue by luca-medeiros** [Lightning-AI/lightning#13747]
## 🚀 Feature

Currently, collect_env_details.py does not gather info about `lightning` or `lightning-app` packages.

### Motivation

Give more accurate info about the environment when writing issues.

### Pitch

I would like the function to return something like the following
* Packages:
        - numpy:             1.23.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.12.0+cu102
        - pytorch-lightning: 1.7.0dev
        - tqdm:              4.64.0
        **- lightning:       2022.7.18
        - lightning-app:     0.5.2**

### Additional context

Quick fix:

```
import lightning
import lightning_app

def info_packages():
    return {
        "numpy": numpy.__version__,
        "pyTorch_version": torch.__version__,
        "pyTorch_debug": torch.version.debug,
        "pytorch-lightning": pytorch_lightning.__version__,
        "lightning": lightning.__version__,
        "lightning_app": lightning_app.__version__,
        "tqdm": tqdm.__version__,
    }

```

If you assign me I can send a PR.

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @awaelchli

**Comment by awaelchli** [comment]
Hey @luca-medeiros 
Agree this should be updated. Would you like to send a PR with your addition?

**Comment by luca-medeiros** [comment]
Thanks for checking it up @awaelchli 
On it. I will CC you once I post the PR.
