### ISSUE TITLE
404 Page Not Found Error for AppState Doc

### ISSUE THREAD

**Issue by oojo12** [Lightning-AI/lightning#13753]
## 📚 Documentation
Clicking the app state url here - https://lightning.ai/lightning-docs/core_api/lightning_app/ results in a 404 page not found error.

According to the [index.rst](https://github.com/Lightning-AI/lightning/blob/master/docs/source-app/core_api/lightning_app/index.rst) this file should be at:
```
.. displayitem::
   :header: The App state (basic)
   :description: Learn more about the state and its manipulation.
   :col_css: col-md-4
   :button_link: ../../workflows/access_app_state.html
   :height: 180
   :tag: basic
```

However, that file is not there and I couldn't locate it. Was it deleted?

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda @rohitgr7

**Comment by robert-s-lee** [comment]
checked today and the issue still exists

**Comment by Borda** [comment]
this page is no longer with docs
