### ISSUE TITLE
No Content on Pages Lightning Flow API Doc Redirects To

### ISSUE THREAD

**Issue by oojo12** [Lightning-AI/lightning#13754]
## 📚 Documentation

When visiting the [Lightning Flow api](https://lightning.ai/lightning-docs/core_api/lightning_flow.html) docs there are a couple of link redirects with empty content. Is this intentional? If so it'd be nice to replace them with a message like content coming soon.

- [ ] https://lightning.ai/workflows/add_web_ui/index.html -> from looking at the doc it seems that this should really be this https://lightning.ai/lightning-docs/workflows/arrange_tabs/arrange_app_basic.html
- [ ] https://lightning.ai/glossary/scheduling.html -> seems like it should redirect to https://lightning.ai/lightning-docs/glossary/scheduling.html
- [ ] https://lightning.ai/examples/app_dag/dag.html -> seems like it should redirect to https://lightning.ai/lightning-docs/examples/dag/dag.html

Am I correct in these assumptions if so I can submit the appropriate PRs.

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @borda @rohitgr7

**Comment by Borda** [comment]
I believe that these issues were resolved as we refactored significantly part of our docs
