### ISSUE TITLE
Problem with logging figure is being saved and crashes when there is no figure

### ISSUE THREAD

**Issue by TalKachman** [Lightning-AI/lightning#13768]
## 🐛 Bug

When using weights and biases along with pytorch lightning logger. The logger function tries to log in an image where there is non or non is referred to. This causes the script to crash

### To Reproduce
A gist with minimal example
https://gist.github.com/TalKachman/726638a8c8e28bcdf34cb39f67a338c0

* CUDA:
	- GPU:
		- Tesla V100-SXM2-16GB
	- available:         True
	- version:           11.3
* Packages:
	- numpy:             1.21.6
	- pyTorch_debug:     False
	- pyTorch_version:   1.12.0+cu113
	- pytorch-lightning: 1.6.5
	- tqdm:              4.64.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.13
	- version:           #1 SMP Sun Apr 24 10:03:06 PDT 2022

cc @awaelchli @edward-io @borda @ananthsub @rohitgr7 @kamil-kaczmarek @Raalsky @Blaizzy

**Comment by TalKachman** [comment]
Ok small updated, I found this old issue, it seems like pytorch-forecasting has something to do with this

https://github.com/jdb78/pytorch-forecasting/issues/79

**Comment by awaelchli** [comment]
Hello

I saw your message on twitter. I didn't know you were using forecasting, but yeah they don't support the WandB logger. 
The error shows clearly the call to `add_figure` which is the way you would log an image with TensorBoard. 

Forecasting should add an isinstance check against the specific logger. There already exist issues for this on the repo:
- https://github.com/jdb78/pytorch-forecasting/issues/89 
- https://github.com/jdb78/pytorch-forecasting/issues/983

I suggest you ping the devs there to bring awareness.
