### ISSUE TITLE
storing artifacts in Lighting App Drive do not show up in Admin UI Storage Tab 

### ISSUE THREAD

**Issue by robert-s-lee** [Lightning-AI/lightning#13772]
## 🐛 Bug

I have an [train diag eval Lightinign App](https://lightning.ai/robertslee/apps/01g8enrq990mwz5zrcbw9czt9d).  The source code is at [GithHub](https://github.com/robert-s-lee/lai-train-eval)  constructed as below.  

```mermaid
graph TD;
  LD[Lightning App Drive]
  T[Train]     <-- push, get --> LD 
  I[Inference] <-- push, get --> LD
  D[Diag]      <-- push, get --> LD
```

 The content of the Drive is not showing up in the Admin UI.
<img width="1784" alt="Screen Shot 2022-07-20 at 4 58 01 PM" src="https://user-images.githubusercontent.com/6315124/180081206-dfb20348-00a9-4da8-9e7f-45ac36cd9293.png">

### To Reproduce

- Run the app on the cloud.
- Start the training.
- Deploy version 0.
- check Tensorbard and Gradio and confirm new model has been copied from Trainer to Tensoroard and Gradio use
- Go to Admin UI -> Storage

Trainer logs confirm the new model has been created

```
[root.trainer] 2022-07-20T20:58:33.128Z INFO: /content/lightning_logs/version_1
[root.trainer] 2022-07-20T20:58:33.128Z INFO: 1
[root.trainer] 2022-07-20T20:58:33.491Z INFO: wait completed python train_script.py --trainer.max_epochs=3 --trainer.limit_train_batches=12 --trainer.limit_val_batches=4 --trainer.callbacks=ModelCheckpoint --trainer.callbacks.monitor=val_acc
```

Gradio restart logs confirm Drive is working and new models are in use.

```
[root.eval_ui] 2022-07-20T21:02:51.917Z INFO: python gradio_script.py --host 0.0.0.0 --port 41729 --model_path lightning_logs/version_1/example.pt {}
[root.eval_ui] 2022-07-20T21:05:11.541Z INFO: python gradio_script.py --host 0.0.0.0 --port 41729 --model_path lightning_logs/base/example.pt {}
```

Tensorboard also shows the new models

### Expected behavior

Storage show the files in Drive

**Comment by tchaton** [comment]
Hey @[robert-s-lee](https://github.com/robert-s-lee),

You need to refresh the page. This is a bug from the application side.

@edenlightning

**Comment by robert-s-lee** [comment]
@tchaton Looked at it this morning after I restarted my browser.  The artifacts did show up.  I will try refresh the next time.  TY for the tip.

<img width="1792" alt="Screen Shot 2022-07-21 at 8 01 41 AM" src="https://user-images.githubusercontent.com/6315124/180209470-1fefd168-a9e5-4d32-a8d9-bf33d5405f1a.png">
