### ISSUE TITLE
The webpage documents make my computer stuck

### ISSUE THREAD

**Issue by hughplay** [Lightning-AI/lightning#13776]
Thanks for the excellent documents.

My issue is that there are too many videos on the [`Trainer`](https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#trainer) and [`LightningModule`](https://pytorch-lightning.readthedocs.io/en/stable/common/lightning_module.html) documents. Every time I open one of these two pages, my PC is stuck, running out of CPUs  to load these videos.

Would you please improve this? : ) Thanks.

cc @borda @rohitgr7 @akihironitta

**Comment by akihironitta** [comment]
I remember there was a similar issue reported before. We had larger ones before, but @kaushikb11 replaced them with smaller ones that we currently have in the docs (e.g. https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html).

I'm in favour of removing all video embeddings and having links to YouTube videos (not embedding!) instead.

**Comment by Borda** [comment]
I believe we have compressed them already, but feel free to reopen if the issue preserves... :rabbit:
