### ISSUE TITLE
Error when load_from_checkpoints when LightningModule __init__ have tokenizer which is not hyperparameter

### ISSUE THREAD

**Issue by CaffreyR** [Lightning-AI/lightning#13784]
## 🐛 Bug

TypeError:__init__() missing 4 required positional arguments: 'config','tokenizer','transformer' and 'dataset_reader'
### To Reproduce

```
class EncoderDecoder(LightningModule):
    """
    Encoder Decoder
    """

    def __init__(self, config, tokenizer, transformer, dataset_reader):
        """
        :param config
        """
        super().__init__()
        self.config = config
        self.tokenizer = tokenizer
        self.model = transformer
        self.dataset_reader = dataset_reader

        self.use_deepspeed = self.config.compute_strategy.startswith("deepspeed")
        self.use_ddp = self.config.compute_strategy.startswith("ddp")
        self.load_model()

        self._last_global_step_saved = -1

        if self.config.fishmask_mode is not None:
            fishmask_plugin_on_init(self)

model= EncoderDecoder.load_from_checkpoints("my file path")
```
### Expected behavior

<img width="582" alt="image" src="https://user-images.githubusercontent.com/84232793/180198487-a3776bce-4853-4ab1-8470-1241c4ce0f6a.png">### Environment

- PyTorch Lightning Version (e.g., 1.5.0):
- PyTorch Version (e.g., 1.10):
- Python version (e.g., 3.9):
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

@rohitgr7 @akihironitta

**Comment by rohitgr7** [comment]
you need to call `self.save_hyperparameters`
```py
class EncoderDecoder(LightningModule):
    """
    Encoder Decoder
    """

    def __init__(self, config, tokenizer, transformer, dataset_reader):
        """
        :param config
        """
        self.save_hyperparameters(ignore=['tokenizer', 'transformer', 'dataset_reader'])
        ...
```

I'd recommend ignoring `tokenizer, transformer, dataset_reader` because they are not hparams and pass them again while loading the checkpoints

```py
model= EncoderDecoder.load_from_checkpoints("my file path", tokenizer=tokenizer, transformer=transformer, dataset_reader=dataset_reader)
```

**Comment by CaffreyR** [comment]
Hi, @rohitgr7 . But here is another problem. See, I use opendelta to fine tune my model using lora. But when I tried to load, it seems wrong since it seems there is state keys missing here. Apparently, it seems not save the LORA weight. 
```
def opendelta_modify_with_lora(transformer, config):
    # pass
    LoraModel(backbone_model=transformer, modified_modules=['[r](\d).SelfAttention.[q,v,o,k]'])
    LoraModel(backbone_model=transformer, modified_modules=['[r](\d).EncDecAttention.[q,v,o,k]'])
    delta_model = LoraModel(backbone_model=transformer, modified_modules=['[r](\d).DenseReluDense.w[o,i]'])

    delta_model.freeze_module(exclude=["layer_norm", "lora_A", "lora_B"])
    # delta_model.log(delta_ratio=True, trainable_ratio=True, visualization=True)
    # Visualization(transformer).structure_graph();
    return transformer
```
<img width="543" alt="image" src="https://user-images.githubusercontent.com/84232793/180211099-e6d89167-9ef5-49ec-b2ec-d64735ea3baf.png">
