### ISSUE TITLE
`trainer.should_stop` doesn't stop at `min_epochs` if it's set before

### ISSUE THREAD

**Issue by rohitgr7** [Lightning-AI/lightning#13789]
## Proposed refactor

Consider an example:
```
min_epochs=4
max_epochs=1000

user set's `should_stop=True` in the middle of epoch 3
```

Result:
```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> (epoch 1)
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> (epoch 2)
>>>>>>>>>>>>>>> (should_stop=True, epoch 3 breaks)
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> (epoch 4)
...
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> (max_epochs)
```
1. The epoch loop breaks in between at epoch 3.
2. Training continues until `max_epochs=1000`.

### Motivation and Pitch

My suggestion:
1. Training should not break in between since `min_epochs` haven't been met.
2. It should break right after `min_epochs`.

Motivation or Reason
1. Breaking the loop in between is fine if `min_epochs` is met, but if it's not, it should not break it in between and should complete that epoch and continue until `min_epochs`.
2. If the user has been forced to stop the training, we should not run for more than `min_epochs`.

Thoughts??

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @tchaton @justusschock @awaelchli @borda @carmocca @ananthsub @ninginthecloud @rohitgr7

**Comment by awaelchli** [comment]
This sounds like a bug. `min_epochs` and `min_steps` exist primarily because of early stopping and its implementation relies on` Trainer.should_stop`. Looking at the test `test_min_epochs_min_steps_global_step`, it looks like so far we have only considered this for end-of-epoch cases but should let early stopping also work with multiple validation checks per epoch.

**Comment by rohitgr7** [comment]
@awaelchli 
do you mean that if early stopping triggers to stop the training during an epoch, we should stop immediately?

And if user sets `trainer.should_stop` explicitly we should continue the epoch and next epochs until min_epochs/min_steps are met? (my suggestion)

**Comment by awaelchli** [comment]
> do you mean that if early stopping triggers to stop the training during an epoch, we should stop immediately?

No absolutely not. There would be no use for min_* if this was the case. As I wrote, these flags exist because of early stopping in the first place. 

There is not difference between early stopping setting the trainer.should_stop and the user setting it. The min_* arguments need to take precedence. 

To stop immediately, the user can raise KeyboardInterrupt. 

> And if user sets trainer.should_stop explicitly we should continue the epoch and next epochs until min_epochs/min_steps are met? (my suggestion)

Yes I agree. This is the intended behavior so if it's not the case now this is a bug.

**Comment by awaelchli** [comment]
Btw, the should_stop can be renamed if we believe this leads to confusion. And if needed, one can also introduce an api to stop the loop immediately if we believe we need that.
