### ISSUE TITLE
A spurious TODO in TorchCheckpointIO

### ISSUE THREAD

**Issue by Turakar** [Lightning-AI/lightning#13797]
Hi, I am currently working on an asynchronous version of `TorchCheckpointIO` that utilizes `multiprocessing` to save the checkpoints without blocking training. During this, I stumbled across [this TODO](https://github.com/Lightning-AI/lightning/blob/ff5361604b2fd508aa2432babed6844fbe268849/pytorch_lightning/plugins/io/torch_plugin.py#L56) and wondered whether it can be resolved, i.e. whether I need to duplicate that logic in my implementation?

cc @awaelchli @ananthsub @ninginthecloud @rohitgr7 @otaj

**Comment by otaj** [comment]
Hi @Turakar. The TODO might not be required anymore (we will need to test it of course before it gets removed).

However, you might be interested there's an async checkpointing in the works #13658 and @rohitgr7 is working on it to hopefully make it land in 1.7, which should happen on 1st August

**Comment by Turakar** [comment]
Thank you for the link! If you do not want to keep this issue open for removing the TODO, I am fine with closing it.

**Comment by rohitgr7** [comment]
let's keep this open and explore the TODO. @Turakar do you want to try it out?

**Comment by Turakar** [comment]
I think it seems to be related to DDP and I have no experience with that.

**Comment by awaelchli** [comment]
The TODO was resolved. Closing
