### ISSUE TITLE
Wrong error message for ModelPruning callback

### ISSUE THREAD

**Issue by aminst** [Lightning-AI/lightning#13817]
Hello everyone,
As I understood from the [API References](https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.callbacks.ModelPruning.html#pytorch_lightning.callbacks.ModelPruning) for the _ModelPruning_ callback, this class takes a parameter named _parameters_to_prune_ as an argument. However, the error message I provided below uses a term called parameters_to_tune, which is not a valid argument to the _ModelPruning_ callback. I assume _parameters_to_prune_ was meant, because the other error message available in this file also refers to the term _parameters_to_prune_.

The wrong error message is defined in the file pruning.py:
https://github.com/Lightning-AI/lightning/blob/8d14554383632f4cdff337b3d8d1b226cabdd1d0/src/pytorch_lightning/callbacks/pruning.py#L470

If my understanding is correct, I will be glad to make a pull request to fix the wrong error message.

cc @carmocca

**Comment by awaelchli** [comment]
That looks like a typo. A PR for this would be very welcomed! Thanks
