### ISSUE TITLE
batch size finder not running training steps after first batch size

### ISSUE THREAD

**Issue by brunomaga** [Lightning-AI/lightning#13851]
When trying to automatically find largest batch size, only validation steps are taken. Eg:
```
model.batch_size = tuner.scale_batch_size(model, mode='power', init_val=1, steps_per_trial=3)
```
will run:
```
validation_step(batch_idx=0) #part of the sanity check code
validation_step(batch_idx=1) #part of the sanity check code
train_step(batch_idx=0)
train_step(batch_idx=1)
train_step(batch_idx=2)
Batch size 1 succeeded, trying batch size 2

validation_step(batch_idx=0)
validation_step(batch_idx=1)
Batch size 2 succeeded, trying batch size 4

validation_step(batch_idx=0)
validation_step(batch_idx=1)
Batch size 4 succeeded, trying batch size 8
```

etc. thus this will return a batch size much larger than the one that fits in memory during the train step. 
The issue is in ` pytorch_lightning/loops/fit_loop.py`:

```
    def done(self) -> bool:
        """Evaluates when to leave the loop."""
        # TODO(@awaelchli): Move track steps inside training loop and move part of these condition inside training loop
        stop_steps = _is_max_limit_reached(self.epoch_loop.global_step, self.max_steps)
        [...]
```
The variable `self.epoch_loop.global_step` was not reset to 0 when attempting a new batch size. In this case, it will be `3` on batch size 2, returning `True` as the value of the `done` flag, and ultimately setting `self.skip=True` in `pytorch_lightning/loops/base.py`.

cc @akihironitta @borda @rohitgr7

**Comment by rohitgr7** [comment]
this is not an issue anymore :)
