### ISSUE TITLE
Lightning cmd app generator is not generating the project template

### ISSUE THREAD

**Issue by abidikhairi** [Lightning-AI/lightning#13878]
## 🐛 Lightning cmd app generator is not generating the project template

The `lightning init app gcn` is not creating the project template

### To Reproduce

```bash
lightning init app gcn
```

#### Command output
```
INFO: laying out component template at /home/flursky/Work/projects/lightning/gcn
Traceback (most recent call last):
  File "/home/flursky/.opt/miniconda/envs/dgl/bin/lightning", line 8, in <module>
    sys.exit(main())
  File "/home/flursky/.opt/miniconda/envs/dgl/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/flursky/.opt/miniconda/envs/dgl/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/flursky/.opt/miniconda/envs/dgl/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/flursky/.opt/miniconda/envs/dgl/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/flursky/.opt/miniconda/envs/dgl/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/flursky/.opt/miniconda/envs/dgl/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/flursky/.opt/miniconda/envs/dgl/lib/python3.9/site-packages/lightning_app/cli/lightning_cli.py", line 218, in init_app
    cmd_init.app(name)
  File "/home/flursky/.opt/miniconda/envs/dgl/lib/python3.9/site-packages/lightning_app/cli/cmd_init.py", line 15, in app
    new_resource_name, name_for_files = _make_resource(resource_dir="app-template", resource_name=app_name)
  File "/home/flursky/.opt/miniconda/envs/dgl/lib/python3.9/site-packages/lightning_app/cli/cmd_init.py", line 42, in _make_resource
    os.rename(os.path.join(new_resource_name, "placeholdername"), os.path.join(new_resource_name, name_for_files))
FileNotFoundError: [Errno 2] No such file or directory: '/home/flursky/Work/projects/lightning/gcn/placeholdername' -> '/home/flursky/Work/projects/lightning/gcn/gcn'
```

### Expected behavior
Gets the same output as [this tutorial](https://lightning.ai/lightning-docs/workflows/build_lightning_app/from_scratch.html) as well as the template.

### Environment
```
* CUDA:
	- GPU:
		- NVIDIA GeForce GTX 1650
	- available:         True
	- version:           11.3
* Packages:
	- lightning:         2022.7.18
	- lightning_app:     0.5.2
	- numpy:             1.21.2
	- pyTorch_debug:     False
	- pyTorch_version:   1.11.0
	- pytorch-lightning: 1.6.5
	- tqdm:              4.64.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         
	- python:            3.9.11
	- version:           #1 SMP PREEMPT Fri Jul 15 09:45:39 UTC 2022
```

**Comment by krshrimali** [comment]
Hey, @abidikhairi - Thanks for raising the issue. Can you please cross-check that the path: `/home/flursky/Work/projects/lightning/` exists on your system?

**Comment by abidikhairi** [comment]
Sure
```bash
[ -d "/home/flursky/Work/projects/lightning" ] && echo "path exists."
```
**output**: path exists.

**Comment by krshrimali** [comment]
Thanks! Unfortunately I unfortunately can't reproduce this locally but it's something we would definitely want to fix. May I also request you to please try in a different directory? Just as a final validation from my side. :)

cc: @tchaton for visibility.

**Comment by abidikhairi** [comment]
i switched to `/home/flursky/Work/research` then i run the command `lightning init app gcn`.
still the same error
```FileNotFoundError: [Errno 2] No such file or directory: '/home/flursky/Work/research/gcn/placeholdername' -> '/home/flursky/Work/research/gcn/gcn'```

**Comment by krshrimali** [comment]
Thanks, @abidikhairi for checking it again. Someone from the team will take a look as soon as they can. :)

cc: @awaelchli

**Comment by abidikhairi** [comment]
Hi @krshrimali, after investegating the lightning_app packege on my computer `/home/flursky/.opt/miniconda/envs/dgl/lib/python3.9/site-packages/lightning_app/cli/app-template/` i found that it does not contain the same template as [the lightining template-app](https://github.com/Lightning-AI/lightning/tree/master/src/lightning_app/cli/app-template) i tried to install lightning from the github repository using `pip install git+https://github.com/Lightning-AI/lightning.git` and it worked as expected.
Thanks for your help @krshrimali.

**Comment by krshrimali** [comment]
Awesome, thanks for sharing how you were able to solve it! This will help other users as well. ⚡
