### ISSUE TITLE
lightning.ai UI empty on ipad

### ISSUE THREAD

**Issue by williamFalcon** [Lightning-AI/lightning#13915]
![image](https://user-images.githubusercontent.com/3640001/181617561-3b3df62d-155b-46ca-afdd-29d633ebef75.png)

**Comment by williamFalcon** [comment]
@alecmerdler

**Comment by JatheenA** [comment]
@yurijmikhalevich  can you check on this? It worked on my iPad, but perhaps I missing something. CC: @nohalon

**Comment by yurijmikhalevich** [comment]
This is fixed and live.
