### ISSUE TITLE
Run app cloud CI e2e tests on PRs from forks

### ISSUE THREAD

**Issue by manskx** [Lightning-AI/lightning#13927]
## 🚀 Feature

Run app cloud CI e2e tests on PRs from forks.

### Motivation

Currently, the cloud e2e tests require secrets to run and because the secrets (e.g. lightning_user_id/ lightning_api_key) are not shared with the forks, they run only on PRs from lightning branches only.  This is necessary to allow all contributers to run e2e cloud tests on their PRs 🎉 

### Alternatives

Ideas:
- Move tests to Azure to allow sharing secrets.

### Additional context

cc: @Borda 
______________________________________________________________________

cc @carmocca @akihironitta @borda @tchaton @rohitgr7

**Comment by awaelchli** [comment]
Let's do it! We would like to start merging community PRs. Example:  https://github.com/Lightning-AI/lightning/pull/13531
