### ISSUE TITLE
In subclasses of LightningModule, make self.trainer.datamodule visible

### ISSUE THREAD

**Issue by finkga** [Lightning-AI/lightning#13940]
## 🚀 Feature

Please make self.trainer.datamodule visible in the LightningModule __init__() body or provide another setup routine that is called after __init__ where datamodule is visible.

### Motivation

Models should be instantiated in the LightningModule.__init__() function. However, the number of classes available is only defined in the datamodule associated with the trainer. Unfortunately, self.trainer.datamodule is not defined until after __init__ completes. This means that the first available place to reliably put code that relies on the datamodule features like datamodule.classes is in the configure_optimizers function. This leads to messy code. Fixing this would help keep code clear.

### Pitch

I would like to have the datamodule associated to the trainer after super is called.

### Alternatives

Alternatively, providing a place where setup activities that depend on the datamodule could be done would be helpful.

### Additional context

As an example it would be nice to do this:
```
from pytorch_lightning import LightningModule
import torch

class my_trainer(LightningModule):

    def __init__(self):
        super().__init__()

        self.num_classes = len(self.trainer.datamodule.classes)
        self.model = torch.nn.Linear(in_features=self.num_classes, out_features=self.num_classes)
```

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging PyTorch Lightning, Transformers, and Hydra.

**Comment by akihironitta** [comment]
Hi @finkga, I think it's impossible to reference your datamodule via trainer because your LightningModule doesn't know about anything outside the module at the time of its instantiation until it gets attached to the trainer.

However, you have reference to your datamodule in `LightningModule.setup`:
```python
class LitModel(LightningModule):
    def setup(self, stage):
        num_classes = len(self.trainer.datamodule.classes)
        self.model = torch.nn.Linear(in_features=num_classes, out_features=num_classes)
```
https://pytorch-lightning.readthedocs.io/en/1.6.5/common/lightning_module.html#setup

Let me know if you have any further questions :)
