### ISSUE TITLE
Input type handling and scikit-learn conforming for Trainer.predict()

### ISSUE THREAD

**Issue by qmihau** [Lightning-AI/lightning#13981]
## Proposed refactor

[Trainer's](https://github.com/Lightning-AI/lightning/blob/master/src/pytorch_lightning/trainer/trainer.py) method `predict()` could be made more intuitive and more reliable at the same time. Currently, if someone calls `trainer.predict(dataset)`, following a fairly established pattern from scikit-learn API, it results in unrecoverable state of the trainer, since regardless of the type of first input, `self.strategy.model` gets overwritten. 

My suggestion, which I'm very happy to work on, would be to:

1. swap first and second input, so that `.predict(data)` becomes what many people would expect it to be;
2. add stronger type checking before changing any internal structures, to make sure we can recover from wrong inputs being passed

### Motivation

As I mentioned, motivation is two-fold. Better error handling with easier recovery, and `.predict()` behavior being closer to usual expectation (especially that predict(model) is meaningless without data). 

### Pitch

I'm happy to work on that and submit a PR. I'd like to keep that minimal so it should be easy to incorporate.

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging PyTorch Lightning, Transformers, and Hydra.

cc @rohitgr7

**Comment by awaelchli** [comment]
Hi @qmihau 
https://github.com/Lightning-AI/lightning/pull/13892 will address 2) for model. We will soon also complete #13445 which should help. 

Swapping the input order in predict would make it inconsistent with the other Trainer methods, and swapping them all would be a big breaking change for all Lightning users. I would suggest to go with better input validation first and see if there is more feedback from users regarding the other points.

**Comment by qmihau** [comment]
Thank you. Somehow I didn't notice #13892 when browsing for related issues.

**Comment by qmihau** [comment]
Thank you. Somehow I didn't notice #13892 when browsing for related issues.

**Comment by carmocca** [comment]
@awaelchli Can we close this? We would not swap the order

**Comment by awaelchli** [comment]
Yes, if we are happy with the amount of input validation we do, I suggest to close. 
@qmihau What do you think?

**Comment by qmihau** [comment]
Absolutely. My humble closing remark would be to just consider the option that you don't necessarily need to swap the inputs if you check types and you got the data but not the model, in which case you still have compatibility with the established .predict(data) pattern. But most of all, I'm happy that it will not go into unrecoverable state, thanks!
