### ISSUE TITLE
DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.

### ISSUE THREAD

**Issue by adamjstewart** [Lightning-AI/lightning#13989]
## 🐛 Bug

It seems like parts of PL are using deprecated parts of PL. I'm seeing the following DeprecationWarning in CI:
```
/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/pytorch_lightning/utilities/argparse.py:345: in insert_env_defaults
    return fn(self, **kwargs)
/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py:488: in __init__
    self._callback_connector.on_trainer_init(
/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/callback_connector.py:89: in on_trainer_init
    self.trainer.callbacks.extend(_configure_external_callbacks())
/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/callback_connector.py:262: in _configure_external_callbacks
    factories = entry_points().get("pytorch_lightning.callbacks_factory", ())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = {'array_api': [EntryPoint(name='numpy', value='numpy.array_api', group='array_api')], 'console_scripts': [EntryPoint(n...ame='projector', value='tensorboard.plugins.projector.projector_plugin:ProjectorPlugin', group='tensorboard_plugins')]}
name = 'pytorch_lightning.callbacks_factory', default = ()

    def get(self, name, default=None):
>       self._warn()
E       DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.

/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/importlib/metadata/__init__.py:430: DeprecationWarning
```

### To Reproduce

Should be able to reproduce by testing any Trainer with pytest. I'm not even using callbacks:
```python
Trainer(fast_dev_run=True, log_every_n_steps=1, max_epochs=1)          
```

### Expected behavior

I would not expect to see a DeprecationWarning.

### Environment

- Lightning Component: Trainer
- PyTorch Lightning Version: 1.7.0
- Lightning App Version: N/A
- PyTorch Version: 1.12.0
- Python version: 3.10
- OS: Linux
- CUDA/cuDNN version: N/A
- GPU models and configuration: N/A
- How you installed PyTorch: pip
- If compiling from source, the output of `torch.__config__.show()`: N/A
- Running environment of LightningApp: CI

**Comment by carmocca** [comment]
Hi! This must be caused by a dependency in your environment that defines an entry point with deprecated code.

Can you share the output of `pip freeze` with the environment that reproduces the error?

**Comment by carmocca** [comment]
Thanks for the report! We missed this because we are not testing with Python 3.10 yet cc @akihironitta

**Comment by carmocca** [comment]
Since we don't have CI setup for it yet, do you mind running your reproduction script on the https://github.com/Lightning-AI/lightning/pull/14052 branch?

**Comment by adamjstewart** [comment]
Will test tonight. Is there anything holding up adding Python 3.10 to CI?

**Comment by akihironitta** [comment]
@carmocca @adamjstewart Let me prioritise enabling it in CI this weekend. Here's the tracking issue #9980.
