### ISSUE TITLE
MPSAccelerator not available

### ISSUE THREAD

**Issue by Birch-san** [Lightning-AI/lightning#13991]
## 🐛 Bug

> MPSAccelerator can not run on your system since the accelerator is not available. The following accelerator(s) is available and can be passed into `accelerator` argument of `Trainer`: ['cpu'].

Raised from `accelerator_connector.py::AcceleratorConnector#_set_parallel_devices_and_init_accelerator`:  
https://github.com/Lightning-AI/lightning/blob/2415834aaf4f215ddb0d618bf415405d670f9114/src/pytorch_lightning/trainer/connectors/accelerator_connector.py

Availability determined here:  
https://github.com/Lightning-AI/lightning/blob/2415834aaf4f215ddb0d618bf415405d670f9114/src/pytorch_lightning/accelerators/mps.py

Check is wrong due to platform check here expecting `arm` (my M1 Max reports platform `arm64`):  
https://github.com/Lightning-AI/lightning/blob/master/src/pytorch_lightning/accelerators/mps.py#L27

<img width="897" alt="image" src="https://user-images.githubusercontent.com/6141784/182491317-91f86bcb-76bd-480f-b75a-d6761f313e24.png">

### To Reproduce

```python
from pytorch_lightning import Trainer
Trainer(accelerator='mps')
```

### Expected behavior

Program should complete without raising an error.

### Environment

```
* CUDA:
        - GPU:
        - available:         False
        - version:           None
* Packages:
        - lightning:         2022.8.2
        - lightning_app:     0.5.2
        - numpy:             1.23.0
        - pyTorch_debug:     False
        - pyTorch_version:   1.13.0.dev20220802
        - pytorch-lightning: 1.7.0
        - tqdm:              4.64.0
* System:
        - OS:                Darwin
        - architecture:
                - 64bit
                - 
        - processor:         arm64
        - python:            3.9.12
        - version:           Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
```

cc @tchaton @rohitgr7 @akihironitta @justusschock

**Comment by Birch-san** [comment]
I've written a fix:  
https://github.com/Lightning-AI/lightning/pull/13992

**Comment by mimisikai** [comment]
I caught the same error running the same testing code. Reinstalled the package. nothing changed. Can you advise it? Thanks.
