### ISSUE TITLE
grad_norm of finite scalar returns inf

### ISSUE THREAD

**Issue by fshart** [Lightning-AI/lightning#14020]
## 🐛 Bug

Using "track_grad_norm=2", the grad_norm was 7.954177007826992e+23 while the grad_norm_total was inf.

Stepping through grad_norm in pytorch_lightning.utilities.grads, 7.954177007826992e+23 was the only value in the norms-dictionary.

The 'total_norm' was computed as inf.

Tracing the error, the tensor in norms was float64, while total_norm is float32.

### To Reproduce

```py
import pytorch_lightning
import torch
class TestModel(pytorch_lightning.LightningModule):
    def __init__(self):
        super().__init__()
        self.pos = torch.nn.Parameter(torch.tensor(1., dtype=torch.float64), requires_grad=True)

a = TestModel()
a.pos.grad = torch.tensor(7.954177007826992e+23, dtype=torch.float64)
b = pytorch_lightning.utilities.grad_norm(a, 2)
b
{'grad_2.0_norm/pos': 7.954177007826992e+23, 'grad_2.0_norm_total': inf}
```

### Expected behavior

```py
b
{'grad_2.0_norm/pos': 7.954177007826992e+23, 'grad_2.0_norm_total': 7.954177007826992e+23}
```

### Environment

- Lightning Component Trainer & LightningModule
- PyTorch Lightning Version 1.6.4
- PyTorch Version 1.10

### Additional context

changing
`total_norm = torch.tensor(list(norms.values())).norm(norm_type).item()`
to
`total_norm = torch.tensor(list(norms.values()), dtype=max_dtype).norm(norm_type).item()`
solved the problem, where max_dtype was set to torch.float64.

Unfortunately, pytorch does not provide the numpy utility 'numpy.find_common_type' to typecast different datatypes in norms to a single one to compute max_dtype in any situation.

**Comment by carmocca** [comment]
We can let PyTorch infer the correct dtype by delaying the casting to float to the end of the function. Opened #14051 with the fix
