### ISSUE TITLE
Validate `LM`/`LDM` hooks which should never be overridden by users and raise error

### ISSUE THREAD

**Issue by rohitgr7** [Lightning-AI/lightning#14029]
## Proposed refactor

Users should never override the following hooks and we should validate them inside `configuration_validator.py`.
```console
'clip_gradients'
'manual_backward'
'save_hyperparameters'
'all_gather'
'untoggle_optimizer'
'toggle_optimizer'
```

not sure about these:
```console
'to_torchscript'
'to_onnx'
```

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging PyTorch Lightning, Transformers, and Hydra.

cc @carmocca @awaelchli @borda @ananthsub @ninginthecloud @jjenniferdai @rohitgr7 @justusschock

**Comment by carmocca** [comment]
I also think that this goes against Python's dynamic philosophy. There might be some brave hackers out there overriding these with a valid reason.

**Comment by awaelchli** [comment]
@rohitgr7 Did you see anywhere users getting themselves in trouble overriding these hooks?
I agree with the others that putting these kind of restrictions in place is perhaps going a bit too far.

**Comment by rohitgr7** [comment]
> @rohitgr7 Did you see anywhere users getting themselves in trouble overriding these hooks?

yes, me :p

I override `save_hyperparameters` for some debugging and spend 30 minutes finding where I messed up.
So thought to open an issue and get some opinions.
But I agree with all of you... let's close this.

Thank you :)
