### ISSUE TITLE
Each iteration of LightningWork.run() takes incrementally longer to run than the previous run

### ISSUE THREAD

**Issue by robert-s-lee** [Lightning-AI/lightning#14070]
## 🐛 maybe this is an anti-pattern discussion

When a `work` executes, each iteration of `run()` takes incrementally longer to complete than the previous ones.  

1) very fast and is executed in a tight loop, after about 55 iterations, the work seems to get stuck. 
2) in about 5 seconds, each subsequent run takes slightly longer than the previous run.

Why is this a concern:

1) is not a typical usage and could be classified as an edge condition and a known limitation.
2) requiring millions of runs could face slower runs.  if each run is expected to take many hours, then the slow degradation would not be noticeable.

the graph shows  the degradation from the latest `master` and `2022.8.2`
1) 0-second work duration with lower graphs that has a sharp upslope around 55 iterations
2) 5-second work duration gradual degradation in performance

![number of ms to execute successive run](https://user-images.githubusercontent.com/6315124/183264143-7a5130fb-e13f-4127-a786-1cff3a52f59c.png)

on the cloud, the 5 second work goes up to 10 seconds, and some warning messages below.
```
[flow] 2022-08-06T19:47:08.795Z 2022-08-06 19:47:08,552 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /v1/projects/01g2dm2e8mzdm25dw80cq7dyvg/appinstances/01g9t6q05ty57nvw00agpjgn00/works
[flow] 2022-08-06T19:47:08.795Z 2022-08-06 19:47:08,552 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /v1/projects/01g2dm2e8mzdm25dw80cq7dyvg/appinstances/01g9t6q05ty57nvw00agpjgn00/works
[flow] 2022-08-06T19:47:08.795Z 2022-08-06 19:47:08,552 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /v1/projects/01g2dm2e8mzdm25dw80cq7dyvg/appinstances/01g9t6q05ty57nvw00agpjgn00/works
[flow] 2022-08-06T19:47:08.795Z 2022-08-06 19:47:08,552 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /v1/projects/01g2dm2e8mzdm25dw80cq7dyvg/appinstances/01g9t6q05ty57nvw00agpjgn00/works
[flow] 2022-08-06T19:47:19.623Z INFO: 606 last run took (ms): 10470
[flow] 2022-08-06T19:47:29.956Z INFO: 607 last run took (ms): 10333
[flow] 2022-08-06T19:47:40.865Z INFO: 608 last run took (ms): 10909
[flow] 2022-08-06T19:47:48.617Z INFO: 609 last run took (ms): 7751
[flow] 2022-08-06T19:47:58.984Z INFO: 610 last run took (ms): 10367
```
### To Reproduce

```bash
WORK_DURATION=0 lightning run app 07_app.py --open-ui false
WORK_DURATION=5 lightning run app 07_app.py --open-ui false
```

```python
import lightning as L
from lightning_app.utilities.enum import WorkStageStatus
import time
import os
class Work(L.LightningWork):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.seq = None
    def run(self, seq:int, *args, **kwargs):
        # print(f"Hello world from work {seq}")
        self.seq = seq
        time.sleep(int(os.getenv("WORK_DURATION", 0)))
class Flow(L.LightningFlow):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.work = Work(parallel=True, cache_calls=False)
        self.counter = 1
        self.seq = None
        self.starttime = None
    def run(self):

        if (self.work.status.stage == WorkStageStatus.NOT_STARTED) or (self.work.status.stage == WorkStageStatus.SUCCEEDED and self.work.seq == self.seq):   
          now = int(time.time() * 1000)
          if not(self.starttime is None):
            print(self.counter, "last run took (ms):", (now - self.starttime))
          self.work.run(self.counter)
          self.seq = self.counter
          self.starttime = now
          self.counter += 1  
    
if __name__ == "__main__":
    app = L.LightningApp(Flow())
```

### Expected behavior

ideally, a flat response is desirable.  
- What should be the expectation if a run is executed millions of times?  
- Is this anti-pattern of flow/work?  
- should the loop be inside the work if millions of items need to be processed and not orchestrated from flow?
- the reason for using the flow was to have multiple works that could dynamically expand and contract  

### Additional context

cc @tchaton @rohitgr7

**Comment by tchaton** [comment]
Hey @robert-s-lee.

Can you try master? This PR https://github.com/Lightning-AI/lightning/pull/13970 should have solved this.

Best,
T.C

**Comment by tchaton** [comment]
Hey @robert-s-lee,

Thanks for reporting this behavior. I marked it as p0 and will investigate it.

**Comment by tchaton** [comment]
Hey @robert-s-lee,

I found the bug. There was a race condition on putting the data within the queue.

Thanks for the reproducible script, this was super helpful ;) 

Best,
T.C
