### ISSUE TITLE
return support for torch 1.8.2 (LTS) in PL 1.7.*

### ISSUE THREAD

**Issue by paantya** [Lightning-AI/lightning#14086]
## 🐛 Bug

not support torch 1.8.2 (LTS) in 1.7 PL

### Expected behavior

You can run training using torch 1.8.2 (or 1.8.1)

### Additional context

this is still LTS and many enterprises use it for their sales and prod

Also that version 1.8.1-4 is the default in ubuntu 22 https://packages.ubuntu.com/search?keywords=libtorch&searchon=names&suite=jammy&section=all

cc @borda @carmocca @akihironitta

**Comment by paantya** [comment]
slack discussion:

https://pytorch-lightning.slack.com/archives/CRBLFHY79/p1659913395596189

**Comment by paantya** [comment]
@awaelchli 

Problems were yesterday when we installed pl 1.7 -- torch 1.9 or greater

+ in slack scalazi that pl 1.7 works with torch version 1.9 and more (link above)

did not launch today, I can check tomorrow if any changes were made)

**Comment by paantya** [comment]
@awaelchli 

The dependencies seem to indicate torch >=1.9.*

![image](https://user-images.githubusercontent.com/2975813/183629277-f170a293-738e-4302-8bf3-1d1b516ea123.png)

**Comment by akihironitta** [comment]
#13155 dropped support for PyTorch 1.8 (LTS) because (I remember) we'd like to keep the window size of four PyTorch versions (currently 1.9-1.12).

However, in addition to this issue, there's another user asking for PyTorch 1.8 (LTS) support (https://github.com/Lightning-AI/lightning/issues/14094#issuecomment-1208477633) after PL 1.7 release.

@carmocca @awaelchli @Borda @rohitgr7 If PyTorch 1.8 ends its life as LTS very soon (for example, within three months until the next feature release), I don't think it's worth adding it back, but if 1.8 will live as LTS for more than a few months, I believe it is. Do you think PL should support PyTorch 1.8 again?

**Comment by akihironitta** [comment]
> The dependencies seem to indicate torch >=1.9.*

@paantya Yes, but you can force-install PyTorch 1.8 after installing PL:
```console
$ pip install pytorch-lightning -U
$ pip install torch==1.8.2 --extra-index-url https://download.pytorch.org/whl/lts/1.8/cpu  # for CPU
```

**Comment by paantya** [comment]
after install:

```
Installing collected packages: torch, pytorch-lightning
  Attempting uninstall: torch
    Found existing installation: torch 1.8.2+cu111
    Uninstalling torch-1.8.2+cu111:
      Successfully uninstalled torch-1.8.2+cu111
  Attempting uninstall: pytorch-lightning
    Found existing installation: pytorch-lightning 1.5.9
    Uninstalling pytorch-lightning-1.5.9:
      Successfully uninstalled pytorch-lightning-1.5.9
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.9.2+cu111 requires torch==1.8.2, but you have torch 1.12.1 which is incompatible.
torchaudio 0.8.2 requires torch==1.8.2, but you have torch 1.12.1 which is incompatible.
Successfully installed pytorch-lightning-1.7.0 torch-1.12.1
```

@akihironitta Interesting crutch, thanks I'll try


this makes sense, do you happen to know how long torch will support 1.8.2?

**Comment by akihironitta** [comment]
> do you happen to know how long torch will support 1.8.2?

cc @carmocca

**Comment by carmocca** [comment]
I asked if there's an updated LTS schedule for PyTorch and got no answer. I would respect our support window. If there's enterprise interest in an LTS PL version, then they should contact us to discuss it. A solution could be to include critical bug fixes into the 1.6.x branch, but not support PyTorch 1.8 endlessly across versions.

**Comment by paantya** [comment]
https://discuss.pytorch.org/t/pytorch-lts-release-schedule/153282

**Comment by carmocca** [comment]
@paantya If you have access to the PyTorch slack, this was also asked in https://pytorch.slack.com/archives/C3PDTEV8E/p1651758244430409 and https://pytorch.slack.com/archives/C3PDTEV8E/p1657621331393819

I also want to clarify that we chose to drop support for torch 1.8 after seeing the lack of a clear PyTorch LTS roadmap

**Comment by paantya** [comment]
@carmocca 
Unfortunately there is no access, thanks for keeping up to date, it's cool!

there nothing was written about new versions of LTS or something like that?
or the guys just do not answer this question or do not know themselves?

**Comment by paantya** [comment]
while there is a suspended state with the version, I will request what we need https://github.com/Lightning-AI/lightning/issues/14142

**Comment by akihironitta** [comment]
Closing this issue as there seems no actionable item regarding PL's re-support for PyTorch 1.8? Let's discuss any particular feature requests in corresponding issues, such as #14142.
