### ISSUE TITLE
Validation Dataloader progress bar making a mess

### ISSUE THREAD

**Issue by H-Sorkatti** [Lightning-AI/lightning#14094]
## 🐛 Bug

Validation Dataloader progressbar output is interleaved with the training progressbar, causing the output to be a complete mess.

### Code to reproduce:
```python
class LitModel(pl.LightningModule):
     ...
     self.acc = tm.Accuarcy()
     self.val_acc = tm.Accuracy()

    ...

 def training_step(self, train_batch, batch_num):
        X, y = train_batch
        y_pred = self.forward(X)
        loss = F.cross_entropy(y_pred, y)
        self.acc(y_pred, y)
        self.log("acc", acc, prog_bar=True, on_step=False, on_epoch=True)
        return loss
    
    def validation_step(self, val_batch, batch_num):
        X, y = val_batch
        logits = self.forward(X)
        val_loss = F.cross_entropy(logits, y)
        self.val_acc(logits, y)
        self.log('val_loss', val_loss, prog_bar=True, on_step=False, on_epoch=True)
        self.log('val_acc', val_acc, prog_bar=True, on_step=False, on_epoch=True)
```

```python
model = LitModel()
trainer = pl.Trainer(max_epochs=3)
trainer.fit(model, train_loader, val_loader)
```
### Output
<details>
<pre>

Epoch 0:  85%|███████████████████████████████▎     | 859/1016 [00:27<00:05, 31.35it/s, loss=0.223, v_num=77, acc=0.875]
Validation: 0it [00:00, ?it/s]
Validation:   0%|                                                                              | 0/157 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|                                                                 | 0/157 [00:00<?, ?it/s]
Epoch 0:  85%|███████████████████████████████▎     | 860/1016 [00:30<00:05, 27.81it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:   1%|▋                                                        | 2/157 [00:00<00:21,  7.07it/s]
Epoch 0:  85%|███████████████████████████████▎     | 861/1016 [00:31<00:05, 27.64it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:   2%|█                                                        | 3/157 [00:00<00:22,  6.90it/s]
Epoch 0:  85%|███████████████████████████████▍     | 862/1016 [00:31<00:05, 27.55it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:   3%|█▍                                                       | 4/157 [00:00<00:21,  6.99it/s]
Epoch 0:  85%|███████████████████████████████▍     | 863/1016 [00:31<00:05, 27.46it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  85%|███████████████████████████████▍     | 864/1016 [00:31<00:05, 27.45it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  85%|███████████████████████████████▌     | 865/1016 [00:31<00:05, 27.46it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:   4%|██▌                                                      | 7/157 [00:00<00:11, 12.99it/s]
Epoch 0:  85%|███████████████████████████████▌     | 866/1016 [00:31<00:05, 27.46it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  85%|███████████████████████████████▌     | 867/1016 [00:31<00:05, 27.47it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  85%|███████████████████████████████▌     | 868/1016 [00:31<00:05, 27.48it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  86%|███████████████████████████████▋     | 869/1016 [00:31<00:05, 27.49it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:   7%|███▉                                                    | 11/157 [00:00<00:07, 19.63it/s]
Epoch 0:  86%|███████████████████████████████▋     | 870/1016 [00:31<00:05, 27.48it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  86%|███████████████████████████████▋     | 871/1016 [00:31<00:05, 27.49it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  86%|███████████████████████████████▊     | 872/1016 [00:31<00:05, 27.50it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  86%|███████████████████████████████▊     | 873/1016 [00:31<00:05, 27.50it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  10%|█████▎                                                  | 15/157 [00:00<00:06, 22.79it/s]
Epoch 0:  86%|███████████████████████████████▊     | 874/1016 [00:31<00:05, 27.49it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  86%|███████████████████████████████▊     | 875/1016 [00:31<00:05, 27.48it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  86%|███████████████████████████████▉     | 876/1016 [00:31<00:05, 27.48it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  11%|██████▍                                                 | 18/157 [00:01<00:05, 23.93it/s]
Epoch 0:  86%|███████████████████████████████▉     | 877/1016 [00:31<00:05, 27.49it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  86%|███████████████████████████████▉     | 878/1016 [00:31<00:05, 27.50it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  87%|████████████████████████████████     | 879/1016 [00:31<00:04, 27.51it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  13%|███████▍                                                | 21/157 [00:01<00:05, 25.41it/s]
Epoch 0:  87%|████████████████████████████████     | 880/1016 [00:32<00:04, 27.50it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  87%|████████████████████████████████     | 881/1016 [00:32<00:04, 27.50it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  87%|████████████████████████████████     | 882/1016 [00:32<00:04, 27.50it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  15%|████████▌                                               | 24/157 [00:01<00:04, 26.60it/s]
Epoch 0:  87%|████████████████████████████████▏    | 883/1016 [00:32<00:04, 27.51it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  87%|████████████████████████████████▏    | 884/1016 [00:32<00:04, 27.51it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  87%|████████████████████████████████▏    | 885/1016 [00:32<00:04, 27.51it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  17%|█████████▋                                              | 27/157 [00:01<00:04, 27.41it/s]
Epoch 0:  87%|████████████████████████████████▎    | 886/1016 [00:32<00:04, 27.51it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  87%|████████████████████████████████▎    | 887/1016 [00:32<00:04, 27.52it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  87%|████████████████████████████████▎    | 888/1016 [00:32<00:04, 27.53it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  88%|████████████████████████████████▍    | 889/1016 [00:32<00:04, 27.54it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  20%|███████████                                             | 31/157 [00:01<00:04, 30.15it/s]
Epoch 0:  88%|████████████████████████████████▍    | 890/1016 [00:32<00:04, 27.53it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  88%|████████████████████████████████▍    | 891/1016 [00:32<00:04, 27.53it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  88%|████████████████████████████████▍    | 892/1016 [00:32<00:04, 27.53it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  88%|████████████████████████████████▌    | 893/1016 [00:32<00:04, 27.53it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  22%|████████████▍                                           | 35/157 [00:01<00:04, 27.82it/s]
Epoch 0:  88%|████████████████████████████████▌    | 894/1016 [00:32<00:04, 27.52it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  88%|████████████████████████████████▌    | 895/1016 [00:32<00:04, 27.51it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  88%|████████████████████████████████▋    | 896/1016 [00:32<00:04, 27.49it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  24%|█████████████▌                                          | 38/157 [00:01<00:04, 25.69it/s]
Epoch 0:  88%|████████████████████████████████▋    | 897/1016 [00:32<00:04, 27.49it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  88%|████████████████████████████████▋    | 898/1016 [00:32<00:04, 27.49it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  88%|████████████████████████████████▋    | 899/1016 [00:32<00:04, 27.48it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  26%|██████████████▌                                         | 41/157 [00:01<00:04, 25.26it/s]
Epoch 0:  89%|████████████████████████████████▊    | 900/1016 [00:32<00:04, 27.48it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  89%|████████████████████████████████▊    | 901/1016 [00:32<00:04, 27.48it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  89%|████████████████████████████████▊    | 902/1016 [00:32<00:04, 27.49it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  28%|███████████████▋                                        | 44/157 [00:02<00:04, 25.56it/s]
Epoch 0:  89%|████████████████████████████████▉    | 903/1016 [00:32<00:04, 27.47it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  89%|████████████████████████████████▉    | 904/1016 [00:32<00:04, 27.48it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  89%|████████████████████████████████▉    | 905/1016 [00:32<00:04, 27.48it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  30%|████████████████▊                                       | 47/157 [00:02<00:04, 26.64it/s]
Epoch 0:  89%|████████████████████████████████▉    | 906/1016 [00:32<00:04, 27.49it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  89%|█████████████████████████████████    | 907/1016 [00:32<00:03, 27.49it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  89%|█████████████████████████████████    | 908/1016 [00:33<00:03, 27.50it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  89%|█████████████████████████████████    | 909/1016 [00:33<00:03, 27.50it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  32%|██████████████████▏                                     | 51/157 [00:02<00:03, 28.54it/s]
Epoch 0:  90%|█████████████████████████████████▏   | 910/1016 [00:33<00:03, 27.51it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  90%|█████████████████████████████████▏   | 911/1016 [00:33<00:03, 27.52it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  90%|█████████████████████████████████▏   | 912/1016 [00:33<00:03, 27.53it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  90%|█████████████████████████████████▏   | 913/1016 [00:33<00:03, 27.54it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  90%|█████████████████████████████████▎   | 914/1016 [00:33<00:03, 27.55it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  36%|███████████████████▉                                    | 56/157 [00:02<00:03, 32.77it/s]
Epoch 0:  90%|█████████████████████████████████▎   | 915/1016 [00:33<00:03, 27.56it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  90%|█████████████████████████████████▎   | 916/1016 [00:33<00:03, 27.57it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  90%|█████████████████████████████████▍   | 917/1016 [00:33<00:03, 27.58it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  90%|█████████████████████████████████▍   | 918/1016 [00:33<00:03, 27.59it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  38%|█████████████████████▍                                  | 60/157 [00:02<00:02, 34.43it/s]
Epoch 0:  90%|█████████████████████████████████▍   | 919/1016 [00:33<00:03, 27.60it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  91%|█████████████████████████████████▌   | 920/1016 [00:33<00:03, 27.60it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  91%|█████████████████████████████████▌   | 921/1016 [00:33<00:03, 27.61it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  91%|█████████████████████████████████▌   | 922/1016 [00:33<00:03, 27.62it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  41%|██████████████████████▊                                 | 64/157 [00:02<00:02, 34.82it/s]
Epoch 0:  91%|█████████████████████████████████▌   | 923/1016 [00:33<00:03, 27.63it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  91%|█████████████████████████████████▋   | 924/1016 [00:33<00:03, 27.63it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  91%|█████████████████████████████████▋   | 925/1016 [00:33<00:03, 27.64it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  91%|█████████████████████████████████▋   | 926/1016 [00:33<00:03, 27.64it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  43%|████████████████████████▎                               | 68/157 [00:02<00:02, 35.00it/s]
Epoch 0:  91%|█████████████████████████████████▊   | 927/1016 [00:33<00:03, 27.65it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  91%|█████████████████████████████████▊   | 928/1016 [00:33<00:03, 27.67it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  91%|█████████████████████████████████▊   | 929/1016 [00:33<00:03, 27.68it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  92%|█████████████████████████████████▊   | 930/1016 [00:33<00:03, 27.69it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  92%|█████████████████████████████████▉   | 931/1016 [00:33<00:03, 27.70it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  46%|██████████████████████████                              | 73/157 [00:02<00:02, 37.48it/s]
Epoch 0:  92%|█████████████████████████████████▉   | 932/1016 [00:33<00:03, 27.70it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  92%|█████████████████████████████████▉   | 933/1016 [00:33<00:02, 27.71it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  92%|██████████████████████████████████   | 934/1016 [00:33<00:02, 27.73it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  92%|██████████████████████████████████   | 935/1016 [00:33<00:02, 27.74it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  92%|██████████████████████████████████   | 936/1016 [00:33<00:02, 27.75it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  50%|███████████████████████████▊                            | 78/157 [00:02<00:02, 38.79it/s]
Epoch 0:  92%|██████████████████████████████████   | 937/1016 [00:33<00:02, 27.76it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  92%|██████████████████████████████████▏  | 938/1016 [00:33<00:02, 27.76it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  92%|██████████████████████████████████▏  | 939/1016 [00:33<00:02, 27.77it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  93%|██████████████████████████████████▏  | 940/1016 [00:33<00:02, 27.78it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  93%|██████████████████████████████████▎  | 941/1016 [00:33<00:02, 27.80it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  53%|█████████████████████████████▌                          | 83/157 [00:03<00:01, 39.68it/s]
Epoch 0:  93%|██████████████████████████████████▎  | 942/1016 [00:33<00:02, 27.80it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  93%|██████████████████████████████████▎  | 943/1016 [00:33<00:02, 27.81it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  93%|██████████████████████████████████▍  | 944/1016 [00:33<00:02, 27.83it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  93%|██████████████████████████████████▍  | 945/1016 [00:33<00:02, 27.83it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  55%|███████████████████████████████                         | 87/157 [00:03<00:01, 39.56it/s]
Epoch 0:  93%|██████████████████████████████████▍  | 946/1016 [00:33<00:02, 27.84it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  93%|██████████████████████████████████▍  | 947/1016 [00:34<00:02, 27.84it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  93%|██████████████████████████████████▌  | 948/1016 [00:34<00:02, 27.85it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  93%|██████████████████████████████████▌  | 949/1016 [00:34<00:02, 27.87it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  94%|██████████████████████████████████▌  | 950/1016 [00:34<00:02, 27.88it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  59%|████████████████████████████████▊                       | 92/157 [00:03<00:01, 39.71it/s]
Epoch 0:  94%|██████████████████████████████████▋  | 951/1016 [00:34<00:02, 27.89it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  94%|██████████████████████████████████▋  | 952/1016 [00:34<00:02, 27.89it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  94%|██████████████████████████████████▋  | 953/1016 [00:34<00:02, 27.91it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  94%|██████████████████████████████████▋  | 954/1016 [00:34<00:02, 27.91it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  61%|██████████████████████████████████▏                     | 96/157 [00:03<00:01, 38.05it/s]
Epoch 0:  94%|██████████████████████████████████▊  | 955/1016 [00:34<00:02, 27.88it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  94%|██████████████████████████████████▊  | 956/1016 [00:34<00:02, 27.88it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  94%|██████████████████████████████████▊  | 957/1016 [00:34<00:02, 27.89it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  94%|██████████████████████████████████▉  | 958/1016 [00:34<00:02, 27.88it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  64%|███████████████████████████████████                    | 100/157 [00:03<00:01, 31.27it/s]
Epoch 0:  94%|██████████████████████████████████▉  | 959/1016 [00:34<00:02, 27.87it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  94%|██████████████████████████████████▉  | 960/1016 [00:34<00:02, 27.85it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  95%|██████████████████████████████████▉  | 961/1016 [00:34<00:01, 27.85it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  95%|███████████████████████████████████  | 962/1016 [00:34<00:01, 27.86it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  66%|████████████████████████████████████▍                  | 104/157 [00:03<00:01, 29.25it/s]
Epoch 0:  95%|███████████████████████████████████  | 963/1016 [00:34<00:01, 27.84it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  95%|███████████████████████████████████  | 964/1016 [00:34<00:01, 27.84it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  95%|███████████████████████████████████▏ | 965/1016 [00:34<00:01, 27.85it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  95%|███████████████████████████████████▏ | 966/1016 [00:34<00:01, 27.86it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  69%|█████████████████████████████████████▊                 | 108/157 [00:03<00:01, 29.06it/s]
Epoch 0:  95%|███████████████████████████████████▏ | 967/1016 [00:34<00:01, 27.86it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  95%|███████████████████████████████████▎ | 968/1016 [00:34<00:01, 27.86it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  95%|███████████████████████████████████▎ | 969/1016 [00:34<00:01, 27.85it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  95%|███████████████████████████████████▎ | 970/1016 [00:34<00:01, 27.86it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  71%|███████████████████████████████████████▏               | 112/157 [00:04<00:01, 28.44it/s]
Epoch 0:  96%|███████████████████████████████████▎ | 971/1016 [00:34<00:01, 27.84it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  96%|███████████████████████████████████▍ | 972/1016 [00:34<00:01, 27.85it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  96%|███████████████████████████████████▍ | 973/1016 [00:34<00:01, 27.85it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  73%|████████████████████████████████████████▎              | 115/157 [00:04<00:01, 27.54it/s]
Epoch 0:  96%|███████████████████████████████████▍ | 974/1016 [00:34<00:01, 27.84it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  96%|███████████████████████████████████▌ | 975/1016 [00:35<00:01, 27.85it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  96%|███████████████████████████████████▌ | 976/1016 [00:35<00:01, 27.86it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  96%|███████████████████████████████████▌ | 977/1016 [00:35<00:01, 27.87it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  76%|█████████████████████████████████████████▋             | 119/157 [00:04<00:01, 30.15it/s]
Epoch 0:  96%|███████████████████████████████████▌ | 978/1016 [00:35<00:01, 27.88it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  96%|███████████████████████████████████▋ | 979/1016 [00:35<00:01, 27.89it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  96%|███████████████████████████████████▋ | 980/1016 [00:35<00:01, 27.89it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  97%|███████████████████████████████████▋ | 981/1016 [00:35<00:01, 27.90it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  78%|███████████████████████████████████████████            | 123/157 [00:04<00:01, 32.56it/s]
Epoch 0:  97%|███████████████████████████████████▊ | 982/1016 [00:35<00:01, 27.91it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  97%|███████████████████████████████████▊ | 983/1016 [00:35<00:01, 27.92it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  97%|███████████████████████████████████▊ | 984/1016 [00:35<00:01, 27.93it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  97%|███████████████████████████████████▊ | 985/1016 [00:35<00:01, 27.92it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  81%|████████████████████████████████████████████▍          | 127/157 [00:04<00:00, 31.99it/s]
Epoch 0:  97%|███████████████████████████████████▉ | 986/1016 [00:35<00:01, 27.92it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  97%|███████████████████████████████████▉ | 987/1016 [00:35<00:01, 27.92it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  97%|███████████████████████████████████▉ | 988/1016 [00:35<00:01, 27.93it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  97%|████████████████████████████████████ | 989/1016 [00:35<00:00, 27.94it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  83%|█████████████████████████████████████████████▉         | 131/157 [00:04<00:00, 33.21it/s]
Epoch 0:  97%|████████████████████████████████████ | 990/1016 [00:35<00:00, 27.94it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  98%|████████████████████████████████████ | 991/1016 [00:35<00:00, 27.95it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  98%|████████████████████████████████████▏| 992/1016 [00:35<00:00, 27.96it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  98%|████████████████████████████████████▏| 993/1016 [00:35<00:00, 27.96it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  86%|███████████████████████████████████████████████▎       | 135/157 [00:04<00:00, 34.11it/s]
Epoch 0:  98%|████████████████████████████████████▏| 994/1016 [00:35<00:00, 27.98it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  98%|████████████████████████████████████▏| 995/1016 [00:35<00:00, 27.98it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  98%|████████████████████████████████████▎| 996/1016 [00:35<00:00, 27.99it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  98%|████████████████████████████████████▎| 997/1016 [00:35<00:00, 27.97it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  89%|████████████████████████████████████████████████▋      | 139/157 [00:04<00:00, 30.46it/s]
Epoch 0:  98%|████████████████████████████████████▎| 998/1016 [00:35<00:00, 27.95it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  98%|████████████████████████████████████▍| 999/1016 [00:35<00:00, 27.95it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  98%|███████████████████████████████████▍| 1000/1016 [00:35<00:00, 27.97it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  99%|███████████████████████████████████▍| 1001/1016 [00:35<00:00, 27.96it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  91%|██████████████████████████████████████████████████     | 143/157 [00:04<00:00, 30.84it/s]
Epoch 0:  99%|███████████████████████████████████▌| 1002/1016 [00:35<00:00, 27.97it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  99%|███████████████████████████████████▌| 1003/1016 [00:35<00:00, 27.98it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  99%|███████████████████████████████████▌| 1004/1016 [00:35<00:00, 27.99it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  99%|███████████████████████████████████▌| 1005/1016 [00:35<00:00, 27.98it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  94%|███████████████████████████████████████████████████▍   | 147/157 [00:05<00:00, 31.41it/s]
Epoch 0:  99%|███████████████████████████████████▋| 1006/1016 [00:35<00:00, 27.99it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  99%|███████████████████████████████████▋| 1007/1016 [00:35<00:00, 28.00it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  99%|███████████████████████████████████▋| 1008/1016 [00:35<00:00, 28.00it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  99%|███████████████████████████████████▊| 1009/1016 [00:36<00:00, 28.02it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0:  99%|███████████████████████████████████▊| 1010/1016 [00:36<00:00, 28.02it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0:  97%|█████████████████████████████████████████████████████▏ | 152/157 [00:05<00:00, 34.45it/s]
Epoch 0: 100%|███████████████████████████████████▊| 1011/1016 [00:36<00:00, 28.03it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0: 100%|███████████████████████████████████▊| 1012/1016 [00:36<00:00, 28.04it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0: 100%|███████████████████████████████████▉| 1013/1016 [00:36<00:00, 28.05it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0: 100%|███████████████████████████████████▉| 1013/1016 [00:36<00:00, 28.05it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0: 100%|███████████████████████████████████▉| 1014/1016 [00:36<00:00, 28.07it/s, loss=0.223, v_num=77, acc=0.875]
Epoch 0: 100%|███████████████████████████████████▉| 1015/1016 [00:36<00:00, 28.07it/s, loss=0.223, v_num=77, acc=0.875]
Validation DataLoader 0: 100%|███████████████████████████████████████████████████████| 157/157 [00:05<00:00, 36.75it/s]
Epoch 0: 100%|█████| 1016/1016 [00:36<00:00, 28.07it/s, loss=0.223, v_num=77, acc=0.875, val_loss=0.210, val_acc=0.940]
.
.
.
.
</pre>
</details>

### Expected Behaviour
```
Epoch 0: 100%|█████| 1016/1016 [00:36<00:00, 28.07it/s, loss=0.223, v_num=77, acc=0.875, val_loss=0.210, val_acc=0.940]
Epoch 1: 100%|█████| 1016/1016 [00:41<00:00, 24.29it/s, loss=0.141, v_num=77, acc=0.906, val_loss=0.154, val_acc=0.955]
Epoch 2: 100%|███████| 1016/1016 [00:41<00:00, 24.78it/s, loss=0.1, v_num=77, acc=0.938, val_loss=0.143, val_acc=0.959]
```

### Additional context
```python
pl.__version__
```
```
'1.6.4'
```

cc @awaelchli @rohitgr7

**Comment by rohitgr7** [comment]
hey @H-Sorkatti !

can you try the recent release?

**Comment by awaelchli** [comment]
@H-Sorkatti These are known issues with the tqdm progress bar when running in an unsupported terminal. 
This can also happen if you write to stdout somewhere (e.g., print). 

If it doesn't help, you can also try the [rich progress bar](https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.callbacks.RichProgressBar.html?highlight=rich).

**Comment by H-Sorkatti** [comment]
@rohitgr7 
I'm on torch 1.8.2 LTS so I can't update to pl 1.7.0 without upgrading pytorch itself. Something I'd like to avoid.

**Comment by H-Sorkatti** [comment]
Ok. After using a virtualenv, it seems that PL 1.7.0 does not suffer from the same issue.
Resolved.

+
@awaelchli 
RichProgressBar is slower than tqdm by about 30+ second an epoch on my machine. Significant slowdown if you're running hundreds of epochs. 
---

Thanks for the support guys 👍

**Comment by rohitgr7** [comment]
then, I'd also suggest trying with @awaelchli mentioned.

**Comment by H-Sorkatti** [comment]
If possible please continue supporting LTS versions.

**Comment by paantya** [comment]
@H-Sorkatti 
https://github.com/pytorch/pytorch/issues/83064

**Comment by H-Sorkatti** [comment]
@awaelchli I was using Jupyter (classic).
I've since used a separate virtualenv (not ideal) to update to torch 1.12 and PL 1.7.0. So no more trouble.
Issue resolved. You can close it if you wish.
