### ISSUE TITLE
Trainer with "fast_dev_run=5" doesn't produce WandB logs

### ISSUE THREAD

**Issue by DrMatters** [Lightning-AI/lightning#14091]
## 🐛 Bug

`pl.Trainer` that is instantiated with: `fast_dev_run=5` doesn't produce logs to WandB.

### To Reproduce
Code with proper wandb reporting: https://gist.github.com/DrMatters/7b331961e7b8fa1b83fd976afba04b5c
Code with missing wandb reporting: https://gist.github.com/DrMatters/1558b8954262d5ed3d8ec6a414687c94
The only difference between these two files is that `fast_dev_run` is enabled in the second file.

### Expected behavior
It's expected to see some graphs in the wandb.
This is the output of the working code:
![image](https://user-images.githubusercontent.com/22641583/183447401-c27ce6bc-b18a-4900-b90e-3c26027aa52a.png)
This is the output of not working code:
![image](https://user-images.githubusercontent.com/22641583/183447479-84850c2a-d005-484d-b2f0-457aa198b2a3.png)

You can also check [my wandb output](https://wandb.ai/drmatters/simple_project) of the code above.

### Environment

```
* CUDA:
        - GPU:
                - A100-SXM4-80GB
        - available:         True
        - version:           11.3
* Packages:
        - lightning:         None
        - lightning_app:     None
        - numpy:             1.23.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.12.1+cu113
        - pytorch-lightning: 1.7.0
        - tqdm:              4.64.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - 
        - processor:         x86_64
        - python:            3.8.13
        - version:           #185-Ubuntu SMP Tue Mar 29 17:40:04 UTC 2022
```

You can also fill out the list below manually.
-->

- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
Trainer
- How you installed PyTorch (`conda`, `pip`, source):
pip

**Comment by awaelchli** [comment]
In fast_dev_run, logging and checkpointing is disabled by design. This is documented [here](https://pytorch-lightning.readthedocs.io/en/1.7.0/debug/debugging_basic.html#run-all-your-model-code-once-quickly).

**Comment by awaelchli** [comment]
If you wish to run a few steps and see logs/checkpoints, use the `max_steps=5` Trainer argument instead.
