### ISSUE TITLE
pytorch lightning 1.7.1 doesn't find neptune-client 0.16.5

### ISSUE THREAD

**Issue by arunpatro-meesho** [Lightning-AI/lightning#14148]
## 🐛 Bug

PL 1.7.x cannot detect neptune client. This makes me revert my code back to PL 1.6.5. 

### To Reproduce

```python
from pytorch_lightning.loggers import NeptuneLogger
neptune_logger = NeptuneLogger(api_key="ABCDEFG", project="MyWorkspace/MyProject",)
```

### Expected behavior

This should work fine. 

### Environment

<details>
  <summary>Details</summary>
   * CUDA:
        - GPU:
                - Tesla T4
                - Tesla T4
                - Tesla T4
                - Tesla T4
        - available:         True
        - version:           10.2
* Lightning:
        - pytorch-lightning: 1.7.1
        - torch:             1.12.1
        - torchmetrics:      0.9.3
        - torchvision:       0.13.1
* Packages:
        - absl-py:           1.2.0
        - accelerate:        0.12.0
        - aiobotocore:       2.3.4
        - aiohttp:           3.8.1
        - aioitertools:      0.10.0
        - aiosignal:         1.2.0
        - argon2-cffi:       21.3.0
        - argon2-cffi-bindings: 21.2.0
        - asttokens:         2.0.7
        - async-timeout:     4.0.2
        - attrs:             22.1.0
        - backcall:          0.2.0
        - beautifulsoup4:    4.11.1
        - bleach:            5.0.1
        - boto3:             1.24.48
        - botocore:          1.24.21
        - bravado:           11.0.3
        - bravado-core:      5.17.0
        - cachetools:        5.2.0
        - catalyst:          22.4
        - certifi:           2022.6.15
        - cffi:              1.15.1
        - charset-normalizer: 2.1.0
        - click:             8.1.3
        - cycler:            0.11.0
        - debugpy:           1.6.2
        - decorator:         5.1.1
        - defusedxml:        0.7.1
        - entrypoints:       0.4
        - executing:         0.9.1
        - fastcore:          1.5.16
        - fastjsonschema:    2.16.1
        - fastrelease:       0.1.17
        - filelock:          3.8.0
        - fonttools:         4.34.4
        - frozenlist:        1.3.1
        - fsspec:            2022.7.1
        - future:            0.18.2
        - ghapi:             1.0.0
        - gitdb:             4.0.9
        - gitpython:         3.1.27
        - google-auth:       2.10.0
        - google-auth-oauthlib: 0.4.6
        - grpcio:            1.47.0
        - huggingface-hub:   0.8.1
        - hydra-slayer:      0.4.0
        - idna:              3.3
        - importlib-metadata: 4.12.0
        - ipykernel:         6.15.1
        - ipython:           8.4.0
        - ipython-autotime:  0.3.0
        - ipython-genutils:  0.2.0
        - jedi:              0.18.1
        - jinja2:            3.1.2
        - jmespath:          1.0.1
        - joblib:            1.1.0
        - jsonpointer:       2.3
        - jsonref:           0.2
        - jsonschema:        3.2.0
        - jupyter:           1.0.0
        - jupyter-client:    7.3.4
        - jupyter-console:   6.4.4
        - jupyter-core:      4.11.1
        - jupyterlab-pygments: 0.2.2
        - jupyterlab-widgets: 1.1.1
        - kiwisolver:        1.4.4
        - lxml:              4.9.1
        - markdown:          3.4.1
        - markupsafe:        2.1.1
        - matplotlib:        3.5.2
        - matplotlib-inline: 0.1.3
        - mistune:           0.8.4
        - monotonic:         1.6
        - msgpack:           1.0.4
        - multidict:         6.0.2
        - nbclient:          0.6.6
        - nbconvert:         6.5.2
        - nbdev:             1.2.11
        - nbformat:          5.4.0
        - neptune-client:    0.16.5
        - nest-asyncio:      1.5.5
        - notebook:          6.4.12
        - numpy:             1.23.1
        - oauthlib:          3.2.0
        - packaging:         21.3
        - pandas:            1.4.3
        - pandocfilters:     1.5.0
        - parso:             0.8.3
        - pexpect:           4.8.0
        - pickleshare:       0.7.5
        - pillow:            9.2.0
        - pip:               22.2.2
        - prometheus-client: 0.14.1
        - prompt-toolkit:    3.0.30
        - protobuf:          3.19.4
        - psutil:            5.9.1
        - ptyprocess:        0.7.0
        - pure-eval:         0.2.2
        - py4j:              0.10.9.3
        - pyarrow:           9.0.0
        - pyasn1:            0.4.8
        - pyasn1-modules:    0.2.8
        - pycparser:         2.21
        - pydeprecate:       0.3.2
        - pygments:          2.12.0
        - pyjwt:             2.4.0
        - pyparsing:         3.0.9
        - pyrsistent:        0.18.1
        - pyspark:           3.2.1
        - python-dateutil:   2.8.2
        - pytorch-lightning: 1.7.1
        - pytz:              2022.1
        - pyyaml:            6.0
        - pyzmq:             23.2.0
        - qtconsole:         5.3.1
        - qtpy:              2.1.0
        - regex:             2022.7.25
        - requests:          2.28.1
        - requests-oauthlib: 1.3.1
        - rfc3987:           1.3.8
        - rsa:               4.9
        - s3fs:              2022.7.1
        - s3transfer:        0.6.0
        - scikit-learn:      1.1.2
        - scipy:             1.9.0
        - send2trash:        1.8.0
        - setuptools:        63.4.2
        - simplejson:        3.17.6
        - six:               1.16.0
        - smmap:             5.0.0
        - soupsieve:         2.3.2.post1
        - stack-data:        0.3.0
        - strict-rfc3339:    0.7
        - swagger-spec-validator: 2.7.4
        - tensorboard:       2.9.1
        - tensorboard-data-server: 0.6.1
        - tensorboard-plugin-wit: 1.8.1
        - tensorboardx:      2.5.1
        - terminado:         0.15.0
        - threadpoolctl:     3.1.0
        - tinycss2:          1.1.1
        - tokenizers:        0.12.1
        - torch:             1.12.1
        - torchmetrics:      0.9.3
        - torchvision:       0.13.1
        - tornado:           6.2
        - tqdm:              4.64.0
        - traitlets:         5.3.0
        - transformers:      4.20.1
        - typing-extensions: 4.3.0
        - urllib3:           1.26.11
        - vtax:              0.5.0
        - wcwidth:           0.2.5
        - webcolors:         1.12
        - webencodings:      0.5.1
        - websocket-client:  1.3.3
        - werkzeug:          2.2.2
        - wheel:             0.37.1
        - widgetsnbextension: 3.6.1
        - wrapt:             1.14.1
        - yarl:              1.8.1
        - zipp:              3.8.1
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.9.13
        - version:           #1 SMP Wed Mar 2 19:14:12 UTC 2022
</details>

### Additional context

The error is: 
```
ModuleNotFoundError: You want to use the `Neptune` logger which is not installed yet, install it with `pip install neptune-client`.
```

I do have neptune-client which cannot be detected.

cc @kamil-kaczmarek @Raalsky @Blaizzy

**Comment by awaelchli** [comment]
@arunpatro-meesho I can't reproduce this. 

I have installed:

```
neptune-client-0.16.5
pytorch-lightning master (also tried 1.7.1)
```

Could you please double double check that you are reporting for the correct version?
```
pip install -U pytorch-lightning
```

It was supposed to be fixed in #13988 and I had already verified it in #14114 so I'm not sure what is going on here.

**Comment by arunpatro-meesho** [comment]
Its working now. Thanks!

**Comment by weiyaw** [comment]
Not sure if this is expected, but PL is not detecting `neptune-client` installed from `conda`. Pip version works fine though.
