### ISSUE TITLE
support profiling and hooks from pl17 from pl 1.6

### ISSUE THREAD

**Issue by paantya** [Lightning-AI/lightning#14142]
## 🚀 Feature

support profiling and hooks from pl17 in pl 1.6, in particular hooks/steps for creating a batch (fetch_batch ) and transferring it to the device - I want to be able to get time for these steps when profiling.

### Motivation

due to the fact that in PL 1.7 there is no support for torch 1.8.2, I want PL 1.6 to have useful functions that are in PL 1.7

### Submission

Get the opportunity to profile and measure the time at the stage of receiving the batch and transferring the batch to the device.

### Alternatives

for good, I want it to be without alternatives, and it was simply implemented as it is in 1.7, tk. we support 1.7 but there are conflicts with the torch version -- we want to keep the lightning and torch versions fully compatible.

### Additional context

a question about profiling where the missing steps in 1.6 are indicated
https://pytorch-lightning.slack.com/archives/CRBLFHY79/p1659645752234179

support request sticking out 1.8.2 in pl 1.7
https://github.com/Lightning-AI/lightning/issues/14086

________________________________________________________________________

#### Rays of love for lightning ⚡

cc @borda @carmocca @kaushikb11 @ninginthecloud @rohitgr7 @nbcsm @guotuofeng

**Comment by paantya** [comment]
while there is a suspended state with the version, I will request what we need

**Comment by awaelchli** [comment]
I don't exactly understand what this means:

> support profiling and hooks from pl17 in pl 1.6,

But [here](https://github.com/Lightning-AI/lightning/pull/14069) is a PR that will add profiling for the batch transfer hooks.

**Comment by paantya** [comment]
@awaelchli looks great!
will he add to PL 1.6?

FYI: this is not about the new, but about what is already in 1.7

It was previously discussed that if something is needed critical, then it can be added in 1.6: https://github.com/Lightning-AI/lightning/issues/14086#issuecomment-1209232760

> I asked if there's an updated LTS schedule for PyTorch in their developer Slack and got no answer. I would respect our support window. If there's enterprise interest in an LTS PL version, then they should contact us to discuss it. A solution could be to include critical bug fixes into the 1.6.x branch, but not support PyTorch 1.8 endlessly across versions.

**Comment by carmocca** [comment]
Hi, with something critical I meant serious bugs that block a large percentage of users or security patches. We would not backport features into previous releases. Note that this was a suggested potential solution, but there's been no decision on whether we would do this.

Does your company require using PyTorch 1.8? Is there a specific reason why you cannot upgrade?

**Comment by rohitgr7** [comment]
If I am not wrong! PL==1.7 might not break if you install PT==1.8 again manually
