### ISSUE TITLE
AttributeError: 'DistributedDataParallel' object has no attribute 'test_step'

### ISSUE THREAD

**Issue by esraashabrani** [Lightning-AI/lightning#14146]
## 🐛 Bug

I was trying the K-Fold cross validation example and got this error.

### To Reproduce
Run this code as a python script https://github.com/Lightning-AI/lightning/blob/master/examples/pl_loops/kfold.py.

### Environment

- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
- PyTorch Lightning Version (1.6.5)
- torch Version (1.12.0+cu113)
- torchvision Version (0.13.0+cu113)
- Python version (3.8)

**Comment by esraashabrani** [comment]
Any updates please? @awaelchli

**Comment by elifdaldal** [comment]
I am having the same error. I'm running Python 3.9.13.
