### ISSUE TITLE
Allow apps to control when they become 'openable' from the website

### ISSUE THREAD

**Issue by ethanwharris** [Lightning-AI/lightning#14163]
## 🚀 Feature

Currently, the 'Open App' button becomes active as soon as the root flow / frontends are running. This can cause issues if your app relies on some works to have started (and perhaps done some processing) before it can be properly used (e.g. Flashy app has file servers that need to be running before you can upload data, some apps run streamlit from a work, etc.).

### Pitch

Add a `ready` property or hook or something that the root flow can use to optionally signal that the app isn't ready to be opened yet.

### Additional context

Currently apps like omniverse have a progress bar inside the app that it waits for it to be ready, but this means that users have to wait multiple times which isn't ideal.

cc @borda

**Comment by yurijmikhalevich** [comment]
I agree that this would improve the experience a lot, plus it will free Lightning App developers from having to implement their own progress bar.

**Comment by awaelchli** [comment]
I believe this was recently finished in #15921 :) 
Please reopen if I'm mistaken.
