### ISSUE TITLE
on_save_checkpoint runs multiple times on DDP

### ISSUE THREAD

**Issue by jordanparker6** [Lightning-AI/lightning#14199]
## 🐛 Bug

on_save_checkpoint handler of the LightningModule runs once per GPU when running on multiple GPUs with `strategy=dpp`. This can have unwanted side effects when saving additional checkpoint information.

Is there a way to make this run only the master? 

Is this the expected behavior? I would think the former would be the more common use case.

### To Reproduce

```py
from transformers import AutoModel
from pytorch_lightning import LightningModule

class BoringModel(LightningModule):
    def __init__(self,  model_name, save_path):
        super().__init__()
        self.save_hyperparameters()
        self.model = AutoModel.from_pretained(self.hparams.model_name)

    def forward(self, pixel_values):
        outputs = self.model(pixel_values=pixel_values)
        return outputs

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)

    def on_save_checkpoint(self, checkpoint):
        print("Saving model latest checkpoint in HF format..")
        self.model.save_pretrained(self.hparams.save_path)
```

- Lightning Component (e.g. Trainer, LightningModule):
- PyTorch Lightning Version  1.6.4
- OS (e.g., Linux): Linux
- CUDA/cuDNN version: 11.3
- GPU models and configuration:  8xT4
- Any other relevant information:

**Comment by awaelchli** [comment]
> Is this the expected behavior?

Yes, it definitely is. 

> This can have unwanted side effects when saving additional checkpoint information.

What for example? Can you give an example?
`on_save_checkpoint`'s primary use is to modify the dictionary checkpoint before it gets saved. Whether all ranks do something with this dictionary or not is up to the implementation in the strategy. Example: Sharded models may want to save a portion of the weights on each rank. 

> Is there a way to make this run only the master?

```py
def on_save_checkpoint(self, checkpoint):
        if self.global_rank == 0:
            # run only on rank 0
```

**Comment by awaelchli** [comment]
Closing the issue as behavior is expected. In general, all hooks need to run on all ranks. 

If you are looking to save only on one rank, this can be accounted for by:

```py
def on_save_checkpoint(self, checkpoint):
        print("Saving model latest checkpoint in HF format..")
        if self.global_rank == 0:
            self.model.save_pretrained(self.hparams.save_path)
```

**Comment by jordanparker6** [comment]
@awaelchli  Thanks for the work around.
