### ISSUE TITLE
The speed of dataload initaliazation become much slower when using multiple GPUS

### ISSUE THREAD

**Issue by SEUleaderYang** [Lightning-AI/lightning#14196]
Hello, I was recently training a model using multiple GPUs and met a problem that when I initialize the dataset in the setup function, the loading speed become extremely slow. For example, the dataset I load in one GPU, the time of this process may cost about 3 minutes, but when I use 8 GPUs, the total time to load the dataset may cost about 3 hours! I know the setup function runs once on each GPU, but why does it cause such a big time difference
![20d813629d8822f9ab610b4ffc654d9](https://user-images.githubusercontent.com/55042050/184503703-936e310d-04c9-4c1c-b8b8-99cef0f9c9ea.png)
![408ce2c3dc9949137fbde34c85a75a4](https://user-images.githubusercontent.com/55042050/184503705-385e62a5-e52e-4df0-be81-38e4198d9b41.png)

cc @justusschock @awaelchli @ninginthecloud @rohitgr7 @otaj @kaushikb11 @akihironitta @borda

**Comment by justusschock** [comment]
Hi can you actually provide a dummy dataset where we can benchmark this? Have you looked at Disk I/O and CPU utilisation during the different approaches? If you do parallel loading, every single process uses the same amount of processes. i.e. when you specify your dataset to be loaded by 8 processes and you use 8 GPUs,  you essentially start 68 processes. If your machine then only has e.g. 8 Threads (like you started the same amount of processes as you have CPUs), you will see scheduling affecting this a lot.

Without any Code (including the data or (prefearbly) random data), we cannot say anything regarding the cause for this issue.

**Comment by SEUleaderYang** [comment]
Hello, Thank you for your reply!  This problem happen before I load the dataset using Dataloader, it happens when I try to read data from json and png according to the setup function, here is the git of a code demo https://github.com/SEUleaderYang/Ubuntu.git,  in addition, when I use a single GPU, it does not report errors despite the slow network training, when I use a multi-card GPU, not only does the data read time spike, but there is an out of cuda memory situation

**Comment by justusschock** [comment]
Can you give us a stacktrace of the error? I briefly looked at your code and I could not find anything obvious there. Are you by chance hitting any memory limits on your RAM? Note that if for one GPU you need 10GB of RAM, you need N*10GB of RAM for N GPUs and if RAM is nearly filled and the OS starts swapping, things really can take some time.

The easiest workaround would be to only load the json in your dataset's init and load the images on the fly in your getitem as you need them

**Comment by SEUleaderYang** [comment]
Sorry to bother you as I found the problem.  My dataset and code are on the hard drives of two separate hosts on the server, so I'm reading the data over the network, which results in excessive network load when multiple GPUs read the data at the same time, making the transfer extremely slow

**Comment by justusschock** [comment]
No worries and glad you found the issue. It may make sense to copy it on a local drive before training then :)
