### ISSUE TITLE
WandB iframe cannot be used inside Lighting App

### ISSUE THREAD

**Issue by robert-s-lee** [Lightning-AI/lightning#14218]
## 🐛 Bug

WandB iframe cannot be used inside Lighting App

### To Reproduce

The below example shows Neptune and Comet.  W&B will fail with `samesite` issue.
```
import lightning as L
import fsspec

class Flow(L.LightningFlow):
	def __init__(self):
			super().__init__()
	def run(self):
		pass
	def configure_layout(self):
		return([
			{'name':'neptune', 'content':'https://neptune.ai'},
			{'name':'w&b', 'content':'https://wandb.ai'},
			{'name':'comet', 'content':'https://comet.com'},
		])
if __name__ == "__main__":
	app = L.LightningApp(Flow())
```

### Expected behavior

<img width="1790" alt="Screen Shot 2022-08-15 at 4 52 46 PM" src="https://user-images.githubusercontent.com/6315124/184716528-4e39524b-f37f-44c7-a398-2740edb0ed16.png">

<img width="1788" alt="Screen Shot 2022-08-15 at 4 54 27 PM" src="https://user-images.githubusercontent.com/6315124/184716665-d152c1f7-e21d-416b-b7ef-51edc196d3e0.png">
<img width="1790" alt="Screen Shot 2022-08-15 at 4 54 40 PM" src="https://user-images.githubusercontent.com/6315124/184716668-eabb4cfb-120c-41e8-ab06-5236ae985c5b.png">

### Environment

(lai) base> python collect_env_details.py

* CUDA:
        - GPU:               None
        - available:         False
        - version:           None
* Lightning:
        - lightning:         2022.8.9
        - lightning-app:     0.5.5
        - lightning-cloud:   0.5.0
        - pytorch-lightning: 1.7.1
        - torch:             1.12.1
        - torchmetrics:      0.9.3
* Packages:
        - absl-py:           1.2.0
        - aiobotocore:       2.1.2
        - aiohttp:           3.8.1
        - aioitertools:      0.10.0
        - aiosignal:         1.2.0
        - altair:            4.2.0
        - anyio:             3.6.1
        - appnope:           0.1.3
        - argon2-cffi:       21.3.0
        - argon2-cffi-bindings: 21.2.0
        - asgiref:           3.5.2
        - asttokens:         2.0.7
        - async-timeout:     4.0.2
        - attrs:             22.1.0
        - backcall:          0.2.0
        - backports.zoneinfo: 0.2.1
        - beautifulsoup4:    4.11.1
        - bleach:            5.0.1
        - blinker:           1.5
        - botocore:          1.23.24
        - cachetools:        5.2.0
        - certifi:           2022.6.15
        - cffi:              1.15.1
        - charset-normalizer: 2.1.0
        - click:             8.1.3
        - commonmark:        0.9.1
        - croniter:          1.3.5
        - debugpy:           1.6.2
        - decorator:         5.1.1
        - deepdiff:          5.8.1
        - defusedxml:        0.7.1
        - dnspython:         2.2.1
        - docutils:          0.15.2
        - email-validator:   1.2.1
        - entrypoints:       0.4
        - executing:         0.9.1
        - fastapi:           0.79.0
        - fastjsonschema:    2.16.1
        - frozenlist:        1.3.1
        - fsspec:            2022.1.0
        - gitdb:             4.0.9
        - gitpython:         3.1.27
        - google-auth:       2.10.0
        - google-auth-oauthlib: 0.4.6
        - grpcio:            1.47.0
        - h11:               0.13.0
        - httptools:         0.4.0
        - idna:              3.3
        - importlib-metadata: 4.12.0
        - importlib-resources: 5.9.0
        - ipykernel:         6.15.1
        - ipython:           8.4.0
        - ipython-genutils:  0.2.0
        - ipywidgets:        7.7.1
        - itsdangerous:      2.1.2
        - jedi:              0.18.1
        - jinja2:            3.0.3
        - jmespath:          0.10.0
        - jsonschema:        4.9.1
        - jupyter-client:    7.3.4
        - jupyter-core:      4.11.1
        - jupyterlab-pygments: 0.2.2
        - jupyterlab-widgets: 1.1.1
        - lightning:         2022.8.9
        - lightning-app:     0.5.5
        - lightning-cloud:   0.5.0
        - lit-bashwork:      0.0.2
        - lxml:              4.9.1
        - markdown:          3.4.1
        - markupsafe:        2.1.1
        - matplotlib-inline: 0.1.3
        - mistune:           0.8.4
        - multidict:         6.0.2
        - nbclient:          0.6.6
        - nbconvert:         6.5.3
        - nbformat:          5.4.0
        - nest-asyncio:      1.5.5
        - notebook:          6.4.12
        - numpy:             1.23.1
        - oauthlib:          3.2.0
        - ordered-set:       4.1.0
        - orjson:            3.7.11
        - packaging:         21.3
        - pandas:            1.4.3
        - pandocfilters:     1.5.0
        - parso:             0.8.3
        - pexpect:           4.8.0
        - pickleshare:       0.7.5
        - pillow:            9.2.0
        - pip:               22.1.2
        - pkgutil-resolve-name: 1.3.10
        - prometheus-client: 0.14.1
        - prompt-toolkit:    3.0.30
        - protobuf:          3.19.4
        - psutil:            5.9.1
        - ptyprocess:        0.7.0
        - pure-eval:         0.2.2
        - py:                1.11.0
        - pyarrow:           9.0.0
        - pyasn1:            0.4.8
        - pyasn1-modules:    0.2.8
        - pycparser:         2.21
        - pydantic:          1.9.1
        - pydeck:            0.7.1
        - pydeprecate:       0.3.2
        - pygments:          2.12.0
        - pyjwt:             2.4.0
        - pympler:           1.0.1
        - pyparsing:         3.0.9
        - pyrsistent:        0.18.1
        - python-dateutil:   2.8.2
        - python-dotenv:     0.20.0
        - python-multipart:  0.0.5
        - pytorch-lightning: 1.7.1
        - pytz:              2022.1
        - pytz-deprecation-shim: 0.1.0.post0
        - pyyaml:            6.0
        - pyzmq:             23.2.0
        - requests:          2.28.1
        - requests-oauthlib: 1.3.1
        - rich:              12.5.1
        - rsa:               4.7.2
        - s3fs:              2022.1.0
        - semver:            2.13.0
        - send2trash:        1.8.0
        - setuptools:        61.2.0
        - six:               1.16.0
        - smmap:             5.0.0
        - sniffio:           1.2.0
        - soupsieve:         2.3.2.post1
        - stack-data:        0.3.0
        - starlette:         0.19.1
        - starsessions:      1.3.0
        - streamlit:         1.11.1
        - streamlit-autorefresh: 0.0.1
        - tensorboard:       2.10.0
        - tensorboard-data-server: 0.6.1
        - tensorboard-plugin-wit: 1.8.1
        - terminado:         0.15.0
        - tinycss2:          1.1.1
        - toml:              0.10.2
        - toolz:             0.12.0
        - torch:             1.12.1
        - torchmetrics:      0.9.3
        - tornado:           6.2
        - tqdm:              4.64.0
        - traitlets:         5.3.0
        - typing-extensions: 4.3.0
        - tzdata:            2022.1
        - tzlocal:           4.2
        - ujson:             5.4.0
        - urllib3:           1.26.11
        - uvicorn:           0.17.6
        - uvloop:            0.16.0
        - validators:        0.20.0
        - watchgod:          0.8.2
        - wcwidth:           0.2.5
        - webencodings:      0.5.1
        - websocket-client:  1.3.3
        - websockets:        10.3
        - werkzeug:          2.2.2
        - wheel:             0.37.1
        - widgetsnbextension: 3.6.1
        - wrapt:             1.14.1
        - yarl:              1.8.1
        - zipp:              3.8.1
* System:
        - OS:                Darwin
        - architecture:
                - 64bit
                - 
        - processor:         i386
        - python:            3.8.13
        - version:           Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.141.32~1/RELEASE_X86_64

**Comment by manangoel99** [comment]
Hi @robert-s-lee ! Engineer from W&B here. W&B pages cannot be embedded as iframes in other web pages.
However, we do allow embedding W&B reports like the ones available at https://wandb.me/fc

**Comment by robert-s-lee** [comment]
@manangoel99 and @awaelchli   Could this be a general solution so each app does not need to be hacked?

TY https://github.com/S0PEX. cut and paste from below. 

 https://github.com/heartexlabs/label-studio/issues/2596#issuecomment-1220951473 

I ran into to the same issue yesterday and would like to inform you that there is no need to modify the src or container image.
When you are serving your services through a reverse proxy you can just rewrite the X-Frame-Options field in the header.

This basically works on all common proxies
E.g header_down for Caddy (https://caddyserver.com/docs/caddyfile/directives/reverse_proxy)

reverse_proxy {
    header_down X-Frame-Options "allow-from https://your-domain.gg"
}
Analogous in nginx using proxy_hide_header (https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_hide_header).

Same exists in traefik and etc.
