### ISSUE TITLE
Add documentation for `Trainer.datamodule`

### ISSUE THREAD

**Issue by KralaBenjamin** [Lightning-AI/lightning#14211]
## 📚 Documentation

The possibility of accessing the datamodule via the trainer is not documented, but is only made apparent via texts in forums such as stackoverflow or github.
It should also be documented that the data module should not be exchanged during the training process.

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging PyTorch Lightning, Transformers, and Hydra.

cc @borda @rohitgr7 @carmocca @awaelchli @ananthsub @ninginthecloud @jjenniferdai

**Comment by awaelchli** [comment]
First I think it could be added here: https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#properties
And then also be mentioned perhaps here: https://pytorch-lightning.readthedocs.io/en/stable/data/datamodule.html?highlight=datamodule

A PR on this would be very welcomed if you are looking to contribute!
