### ISSUE TITLE
ReduceLROnPlateau with horovod

### ISSUE THREAD

**Issue by BigodF** [Lightning-AI/lightning#14236]
When I use torch.optim.lr_scheduler.ReduceLROnPlateau with horovod to train my net, horovod will check weather my lr_scheduler is pytorch_lightning.utilities.types ._LRScheduler or not, just like following (HorovodStrategy.set_up function in pytorch_lightning.strategies.horovod):
```python
        lr_scheduler_configs = self.lr_scheduler_configs
        for config in lr_scheduler_configs:
            scheduler = config.scheduler
            assert isinstance(scheduler, _LRScheduler))
            scheduler.base_lrs = [lr * self.world_size for lr in scheduler.base_lrs]
```
But，ReduceLROnPlateau does not inherent torch.optim.lr_scheduler._LRScheduler.
Anyone knows how to use ReduceLROnPlateau with horovod?

this is my optimizer and lr_scheduler in LightningModule's configure_optimizers function:
```python
        optimizer, (sch, sch_val) = get_opt_sch_bertfinetune(self, conf, self.args, None, total_steps=total_steps, val_metric_mode='min')
        # linear warm-up lr scheduler
        sch = {
            'scheduler': sch, # torch.optim.lr_schedule._LRScheduler, is ok with horovod assert check
            'interval': 'step'
        }
        # ReduceLROnPlateau
        sch_val = {
            'scheduler': sch_val, #  torch.optim.lr_scheduler.ReduceLROnPlateau
            'monitor': self.val_metric_name,
            'frequency': 1,
        }

        return [optimizer], [sch, sch_val]
```

_Originally posted by @BigodF in https://github.com/Lightning-AI/lightning/discussions/14176_

cc @awaelchli

**Comment by awaelchli** [comment]
Thanks for the report. It is going to be fixed by #14215
