### ISSUE TITLE
Wrong warnings module used in lightning module

### ISSUE THREAD

**Issue by roytseng-tw** [Lightning-AI/lightning#14231]
## 🐛 Bug

https://github.com/Lightning-AI/lightning/blob/2622989b108368813fdd3850b002fd1ad69988c2/src/pytorch_lightning/core/module.py#L41
https://github.com/Lightning-AI/lightning/blob/2622989b108368813fdd3850b002fd1ad69988c2/src/pytorch_lightning/core/module.py#L280-L282

L280-L282 intend to use python warnings module instead of the one defined in pytorch lightning.

### To Reproduce

Use multiple loggers:
`pl.trainer(loggers=[logger1, logger2], ...)`

### Expected behavior

Since `pytorch_lightning.utilities.warnings` isn't used anywhere in the file, the solution will be:
1. remove the wrong warnings import.
2. add `import warnings`

### Environment

Doesn't really matter.

- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
- PyTorch Lightning Version (e.g., 1.5.0):
- Lightning App Version (e.g., 0.5.2):
- PyTorch Version (e.g., 1.10):
- Python version (e.g., 3.9):
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Running environment of LightningApp (e.g. local, cloud):
- Any other relevant information:

### Additional context

cc @awaelchli @edward-io @borda @ananthsub @rohitgr7 @kamil-kaczmarek @Raalsky @Blaizzy @carmocca @justusschock @ninginthecloud @jjenniferdai

**Comment by awaelchli** [comment]
@roytseng-tw I see what you mean. Your report is however incomplete. This is the repro:

```py
    model = BoringModel()
    trainer = Trainer(
        logger=[TensorBoardLogger("."), TensorBoardLogger(".")]
    )
    model.trainer = trainer
    model.logger
```

```
Traceback (most recent call last):
  File "/Users/adrian/repositories/lightning/examples/pl_bug_report/bug_report_model.py", line 57, in <module>
    run()
  File "/Users/adrian/repositories/lightning/examples/pl_bug_report/bug_report_model.py", line 53, in run
    model.logger
  File "/Users/adrian/miniconda3/envs/lightning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'BoringModel' object has no attribute 'logger'. Did you mean: 'loggers'?

```

1. We should fix this by importing warnings correctly as you said (thanks!!), and release this in 1.7.x
2. We should get rid of the code completely because the deprecation phase is over in 1.8. 

Thanks for raising this issue!
