### ISSUE TITLE
Explain that `configure_layout` URLs get embedded in iframes

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#14230]
### Motivation

The user does not know what to do when an iframe can't display the contents. 

<img width="506" alt="Screenshot 2022-08-16 at 6 09 59 PM" src="https://user-images.githubusercontent.com/5495193/184887910-e7271597-9669-4e59-8308-60d2e0ff9344.png">

### Pitch

A) The frontend can display a useful message instead of a blank page

B) Add a sentence to the docs that says https links should be preferred over http. And that the source can still prevent that the content be embedded, which is out of our control (I assume). 

### Alternatives

Raise an error or emit a warning. This would lead to false positives, as we can't (?) know if the iframe or external site will allow the url or not. Or maybe we can know it in advance? In this case, we should warn on the Python side too. 

### Additional context

[Discussed on Slack
](https://pytorch-lightning.slack.com/archives/CRBLFHY79/p1660651533273409)

cc @borda @rohitgr7 @krishnakalyan3 @hhsecond @williamFalcon 
______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging PyTorch Lightning, Transformers, and Hydra.

**Comment by awaelchli** [comment]
@alecmerdler You know this maybe: If such an error occurs, or the link is not accessible in the iframe, can our frontend display something helpful instead of the blank page? What are the best practices in your opinion here?

**Comment by alecmerdler** [comment]
@awaelchli I wish, we wanted to do something similar to show loading spinners. Unfortunately, modern browsers have strict security features that prevent the external page from accessing the contents of an `iframe` (except through very specific channels, which we use to pass the Lightning app state back and forth).

**Comment by williamFalcon** [comment]
yes, let’s show a warning @awaelchli. don’t rely on docs as the first line of usability
