### ISSUE TITLE
Error when resuming checkpoint that have stateful LightningDataModule in ddp setting 

### ISSUE THREAD

**Issue by khiem2105** [Lightning-AI/lightning#14241]
## 🐛 Bug
Resuming checkpoint that contains a LightningDataModule in ddp setting give RuntimeError: Default process group has not been initialized, please make sure to call init_process_group

### To Reproduce
    class RandomDataset(Dataset):
      def __init__(self, size, num_samples):
          self.len = num_samples
          self.data = torch.randn(num_samples, size)
  
      def __getitem__(self, index):
          return self.data[index]
  
      def __len__(self):
          return self.len

    class BoringDataModule(pl.LightningDataModule):
      def __init__(self, num_samples, dim):
          super(BoringDataModule, self).__init__()
          self.num_samples = num_samples
          self.dim = dim
      
      def setup(self, stage=None):
          if stage == "fit" or stage is None:
              self.train_set = RandomDataset(self.dim, self.num_samples)
              self.val_set = RandomDataset(self.dim, self.num_samples)
          if stage == "test" or stage is None:
              self.test_set = RandomDataset(self.dim, self.num_samples)
  
      def train_dataloader(self):
          return DataLoader(self.train_set, batch_size=32, num_workers=16)
      
      def val_dataloader(self):
          return DataLoader(self.val_set, batch_size=32, num_workers=16)
  
      def test_dataloader(self):
          return DataLoader(self.test_set, batch_size=32, num_workers=16)
  
      def state_dict(self):
          return self.__dict__
  
      def load_state_dict(self, state_dict):
          self.__dict__.update(state_dict)
          self.setup()

    # init model
    model = BoringModel()

    callback = ModelCheckpoint(
        save_last=True
    )

    # Initialize a trainer
    trainer = pl.Trainer(
        max_epochs=1, 
        callbacks=[ModelCheckpoint(save_last=True)],
        logger=False,
        accelerator="gpu",
        devices=4,
        strategy="ddp"
    )

    # Train the model ⚡
    trainer.fit(model, BoringDataModule(128, 32))

    # load model from checkpoint
    m = BoringModel.load_from_checkpoint(checkpoint_path="...") 
    # Give error
      File "test.py", line 115, in test_x
      model = BoringModel.load_from_checkpoint("checkpoints/epoch=1-step=2.ckpt")
    File "/home/huynhtankhiem/clustering_image/venv/lib/python3.7/site-packages/pytorch_lightning/core/saving.py", line 143, in load_from_checkpoint
      **kwargs,
    File "/home/huynhtankhiem/clustering_image/venv/lib/python3.7/site-packages/pytorch_lightning/core/saving.py", line 184, in _load_from_checkpoint
      checkpoint = pl_load(checkpoint_path, map_location=map_location)
    File "/home/huynhtankhiem/clustering_image/venv/lib/python3.7/site-packages/pytorch_lightning/utilities/cloud_io.py", line 47, in load
      return torch.load(f, map_location=map_location)
    File "/home/huynhtankhiem/clustering_image/venv/lib/python3.7/site-packages/torch/serialization.py", line 712, in load
      return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
    File "/home/huynhtankhiem/clustering_image/venv/lib/python3.7/site-packages/torch/serialization.py", line 1049, in _load
      result = unpickler.load()
    File "/home/huynhtankhiem/clustering_image/venv/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 780, in __setstate__
      self.process_group = _get_default_group()
    File "/home/huynhtankhiem/clustering_image/venv/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 430, in _get_default_group
      "Default process group has not been initialized, "
    RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

### Expected behavior
Checkpoint should be resumed without error

### Environment
* CUDA:
	- GPU:
		- Tesla T4
		- Tesla T4
		- Tesla T4
		- Tesla T4
	- available:         True
	- version:           10.2
* Lightning:
	- lightning-bolts:   0.5.0
	- lightning-flash:   0.7.5
	- pytorch-lightning: 1.7.0
	- torch:             1.12.1
	- torch-tb-profiler: 0.4.0
	- torchmetrics:      0.9.3
	- torchvision:       0.13.1
* Packages:
	- absl-py:           1.2.0
	- aiohttp:           3.8.1
	- aiosignal:         1.2.0
	- alembic:           1.8.1
	- analytics-python:  1.4.0
	- anyio:             3.6.1
	- astunparse:        1.6.3
	- async-timeout:     4.0.2
	- asynctest:         0.13.0
	- attrs:             22.1.0
	- autopage:          0.5.1
	- backcall:          0.2.0
	- backoff:           1.10.0
	- bcrypt:            3.2.2
	- cachetools:        5.2.0
	- certifi:           2022.6.15
	- cffi:              1.15.1
	- charset-normalizer: 2.1.0
	- click:             8.1.3
	- cliff:             3.10.1
	- cmaes:             0.8.2
	- cmd2:              2.4.2
	- colorlog:          6.6.0
	- cryptography:      37.0.4
	- cycler:            0.11.0
	- debugpy:           1.6.2
	- decorator:         5.1.1
	- docstring-parser:  0.14.1
	- entrypoints:       0.4
	- faiss-gpu:         1.7.2
	- fastapi:           0.79.0
	- ffmpy:             0.3.0
	- flatbuffers:       1.12
	- fonttools:         4.34.4
	- frozenlist:        1.3.1
	- fsspec:            2022.7.1
	- gast:              0.4.0
	- google-api-core:   2.8.2
	- google-auth:       2.9.1
	- google-auth-oauthlib: 0.4.6
	- google-cloud-core: 2.3.2
	- google-cloud-storage: 2.5.0
	- google-crc32c:     1.3.0
	- google-pasta:      0.2.0
	- google-resumable-media: 2.3.3
	- googleapis-common-protos: 1.56.4
	- gradio:            3.1.4
	- greenlet:          1.1.2
	- grpcio:            1.47.0
	- h11:               0.12.0
	- h5py:              3.7.0
	- httpcore:          0.15.0
	- httpx:             0.23.0
	- idna:              3.3
	- importlib-metadata: 4.12.0
	- importlib-resources: 5.9.0
	- ipykernel:         6.15.1
	- ipython:           7.34.0
	- jedi:              0.18.1
	- jinja2:            3.1.2
	- joblib:            1.1.0
	- jsonargparse:      4.13.1
	- jupyter-client:    7.3.4
	- jupyter-core:      4.11.1
	- keras:             2.9.0
	- keras-preprocessing: 1.1.2
	- kiwisolver:        1.4.4
	- libclang:          14.0.6
	- lightning-bolts:   0.5.0
	- lightning-flash:   0.7.5
	- linkify-it-py:     1.0.3
	- llvmlite:          0.39.0
	- mako:              1.2.1
	- markdown:          3.4.1
	- markdown-it-py:    2.1.0
	- markupsafe:        2.1.1
	- matplotlib:        3.5.2
	- matplotlib-inline: 0.1.3
	- mdit-py-plugins:   0.3.0
	- mdurl:             0.1.1
	- monotonic:         1.6
	- multidict:         6.0.2
	- nest-asyncio:      1.5.5
	- numba:             0.56.0
	- numpy:             1.21.6
	- oauthlib:          3.2.0
	- opt-einsum:        3.3.0
	- optuna:            2.10.1
	- orjson:            3.7.11
	- packaging:         21.3
	- pandas:            1.3.5
	- paramiko:          2.11.0
	- parso:             0.8.3
	- pbr:               5.9.0
	- pexpect:           4.8.0
	- pickleshare:       0.7.5
	- pillow:            9.2.0
	- pip:               22.2.2
	- prettytable:       3.3.0
	- prompt-toolkit:    3.0.30
	- protobuf:          3.19.4
	- psutil:            5.9.1
	- ptyprocess:        0.7.0
	- pyasn1:            0.4.8
	- pyasn1-modules:    0.2.8
	- pycparser:         2.21
	- pycryptodome:      3.15.0
	- pydantic:          1.9.2
	- pydeprecate:       0.3.2
	- pydub:             0.25.1
	- pygments:          2.12.0
	- pynacl:            1.5.0
	- pynndescent:       0.5.7
	- pyparsing:         3.0.9
	- pyperclip:         1.8.2
	- python-dateutil:   2.8.2
	- python-multipart:  0.0.5
	- pytorch-lightning: 1.7.0
	- pytz:              2022.1
	- pyyaml:            6.0
	- pyzmq:             23.2.0
	- requests:          2.28.1
	- requests-oauthlib: 1.3.1
	- rfc3986:           1.5.0
	- rsa:               4.9
	- scikit-learn:      1.0.2
	- scipy:             1.7.3
	- seaborn:           0.11.2
	- setuptools:        47.1.0
	- six:               1.16.0
	- sniffio:           1.2.0
	- sqlalchemy:        1.4.40
	- starlette:         0.19.1
	- stevedore:         3.5.0
	- tensorboard:       2.9.1
	- tensorboard-data-server: 0.6.1
	- tensorboard-plugin-wit: 1.8.1
	- tensorflow:        2.9.1
	- tensorflow-estimator: 2.9.0
	- tensorflow-io-gcs-filesystem: 0.26.0
	- termcolor:         1.1.0
	- threadpoolctl:     3.1.0
	- torch:             1.12.1
	- torch-tb-profiler: 0.4.0
	- torchmetrics:      0.9.3
	- torchvision:       0.13.1
	- tornado:           6.2
	- tqdm:              4.64.0
	- traitlets:         5.3.0
	- typing-extensions: 4.3.0
	- uc-micro-py:       1.0.1
	- umap-learn:        0.5.3
	- urllib3:           1.26.11
	- uvicorn:           0.18.2
	- wcwidth:           0.2.5
	- werkzeug:          2.2.1
	- wheel:             0.37.1
	- wrapt:             1.14.1
	- yarl:              1.8.1
	- zipp:              3.8.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         
	- python:            3.7.12
	- version:           SMP Debian 4.19.249-2 (2022-06-30)

- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
- PyTorch Lightning Version (e.g., 1.5.0):
- Lightning App Version (e.g., 0.5.2):
- PyTorch Version (e.g., 1.10):
- Python version (e.g., 3.9):
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Running environment of LightningApp (e.g. local, cloud):
- Any other relevant information:

### Additional context
I'm running the script on a google cloud platform virtual machine

cc @carmocca @awaelchli @borda @ananthsub @ninginthecloud @jjenniferdai @rohitgr7 @justusschock @kaushikb11 @akihironitta

**Comment by khiem2105** [comment]
In fact I can resume training like:

  ```
  # Resume training
  m = BoringModel()
  dm = BoringDataModule(128, 32)
  
  trainer = Trainer(
    max_epochs=1, 
    callbacks=[callback],
    logger=False,
    accelerator="gpu",
    devices=4,
    strategy="ddp")
 
trainer.fit(m, dm, ckpt_path="...")
```
But the error occurs when I want to load only the model from checkpoint to do some inference using ```BoringModel.load_from_checkpoint()``` like above

**Comment by awaelchli** [comment]
@khiem2105 Can you explain why you are doing this?

```py
    def state_dict(self):
        return self.__dict__

    def load_state_dict(self, state_dict):
        self.__dict__.update(state_dict)
        self.setup()
```

By returning `self.__dict__`  you return all the attributes, including the dataloaders. The reason you see the error is because part of the dataloaders is the sampler, which when using ddp is a distributed sampler. 

It is not best practice to implement `state_dict` and `load_state_dict` this way. Please only return extra state, not `__dict__`, and definitely not the dataloaders. 


```py
    def state_dict(self):  # keep this as the default implementation
        return {}

    def load_state_dict(self, state_dict):
        # self.__dict__.update(state_dict)
        self.setup()
```

**Comment by khiem2105** [comment]
Hi,
I return ```self.__dict__``` in order to save the training, validation and test set indexes in the checkpoint so that when I resume the checkpoint the model will be training on the same portions of data like before. I didn't know that the distributed sampler is also an attribute of the LightningDataModule
If I understand correctly I can do that by returning ```"train_idx": [np array], "val_idx": [np_array], "test_idx": [np_array]} in the ```state_dict()``` method ?

**Comment by awaelchli** [comment]
Okay, that makes a bit more sense. I think you can do that like you said. 

Btw, you can split your dataset using this function from torch: [`torch.utils.data.random_split`]( https://pytorch.org/docs/stable/data.html#torch.utils.data.random_split)
There you can supply a generator with a seed, so if you reload your script it will always create the same split and you don't have to implement any state_dict methods. This is the recommended way by torch to handle your dataset splits. 

```py
train, val, test = torch.utils.data.random_split(dataset, [10, 10, 10], generator=torch.Generator().manual_seed(42))
```

**Comment by khiem2105** [comment]
That is more cleaner! Thank you very much!!

**Comment by awaelchli** [comment]
You are welcome. Let me know if you have any more questions.
