### ISSUE TITLE
Raise error if build config is incompatible with cloud compute

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#14278]
## 🚀 Feature

Generate an error when a custom image is specified through the build config and the default cloud compute is selected.

### Motivation

#14125
https://github.com/Lightning-AI/lightning/issues/14230#issuecomment-1216707414

### Pitch

Validate the setting of `Work.cloud_compute` and `Work.build_config`. If it is incompatible (e.g. custom image + default cpu), raise an error. 

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging PyTorch Lightning, Transformers, and Hydra.

cc @borda @tchaton @rohitgr7

**Comment by hhsecond** [comment]
Reducing priority since platform is still accepting a custom image for the "default" compute configuration. The backend changes for implementing this and reducing cost of running works is going to happen only in few weeks.

**Comment by hhsecond** [comment]
Reducing priority since platform is still accepting a custom image for the "default" compute configuration. The backend changes for implementing this and reducing cost of running works is going to happen only in few weeks.

**Comment by awaelchli** [comment]
@hhsecond Would you have a quick look at #14929? It's a very simple addition and could be the placeholder until the backend either supports the custom image or adds an error message of its own. What do you think?
