### ISSUE TITLE
BackboneFinetuning train_bn does not work

### ISSUE THREAD

**Issue by sirtris** [Lightning-AI/lightning#14277]
## 🐛 Bug

Setting the `train_bn` argument in the `pytorch_lightning.callbacks.BackboneFinetuning` callback to `False` does not work.

### To Reproduce

Running a model with the `BackboneFinetuning` setting `train_bn` to `True|False` results in the same behavior. 

### Expected behavior

There should be a difference in the train/val metric.

### Additional context

Looking at the code of the `BackboneFinetuning` callback reveals that:
```python
def freeze_before_training(self, pl_module: "pl.LightningModule") -> None:
        self.freeze(pl_module.backbone)
```

The definition of the `freeze` function has `train_bn = True` as a default argument. Therefor the code above should be:

```python
def freeze_before_training(self, pl_module: "pl.LightningModule") -> None:
        self.freeze(pl_module.backbone, train_bn=self.train_bn)
``` 

Should I make a pull request for this issue?

**Comment by rohitgr7** [comment]
duplicate https://github.com/Lightning-AI/lightning/issues/13902?

**Comment by sirtris** [comment]
Yes, sorry it is indeed a duplicate.
