### ISSUE TITLE
Force enable tqdm in Google Colab

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#14327]
## 🚀 Feature

Recently, Google Colab deactivated tqdm progress bars in Jupyter notebooks. We currently get this message from Google:

<img width="277" alt="image" src="https://user-images.githubusercontent.com/5495193/185766464-a511b631-7a56-4f4e-8298-a917a1b1ce9f.png">

### Motivation

Users don't see a progress bar despite our docs saying that it is enabled by default. 

### Pitch

Force enable the tqdm widgets when in Colab. We can detect whether the code is running in Google Colab. 

```py
from google.colab import output
output.enable_custom_widget_manager()
```

### Alternatives

x

### Additional context

Users reported this on Slack for the first time. 

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging PyTorch Lightning, Transformers, and Hydra.

cc @tchaton @rohitgr7 @awaelchli

**Comment by rohitgr7** [comment]
very weird, they just disabled it totally with no warning at all when someone's running the code.

**Comment by awaelchli** [comment]
Yes, and the code snippet they show does not work. It's not possible to re-enable the tqdm bar this way :( 
If anyone has ideas

**Comment by carmocca** [comment]
Let's show a warning suggesting the current workaround: https://github.com/googlecolab/colabtools/issues/3023#issuecomment-1221568628

Then we remove it after they fix it properly

**Comment by kaushikb11** [comment]
@awaelchli `TQDMProgressBar` seems to be working now on Colab.

Could you confirm? [Notebook](https://colab.research.google.com/github/Lightning-AI/lightning/blob/master/examples/pl_bug_report/bug_report_model.ipynb)
