### ISSUE TITLE
traning_step missing optimizer_idx if only one optimizer provided

### ISSUE THREAD

**Issue by icedpanda** [Lightning-AI/lightning#14323]
## 🐛 Bug

I'm doing experiments that may or may not require multiple optimizers for additional modules.

However, the `training_step` only has `optimizer_idx` if multiple optimizers are provided and prompt an error if only one optimizer exists.

`TypeError: training_step() missing 1 required positional argument: 'optimizer_idx'`

### To Reproduce
```python
def configure_optimizers(self):
    optimizer = optim.Adam(
        filter(
            lambda p: p.requires_grad,
            self.parameters()),
        lr=self.lr,)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
    )
    scheduler_config = {
        "scheduler": scheduler,
        "monitor": "val/rec/epoch_loss",
        "interval": "epoch",
        "frequency": 1,
    }
    if self.is_use_some_modules:
        pre_optimizer = optim.SGD(
            filter(
                lambda p: p.requires_grad,
                self.parameters()),
            lr=self.lr_for_other_modules,)
        optimizers = [optimizer, pre_optimizer]
        return optimizers, scheduler_config
    return {"optimizer": optimizer, "lr_scheduler": scheduler_config}

def training_step(self, batch, batch_idx, optimizer_idx):
     if optimizer_idx == 0:
        # do forward
      if self.is_use_some_modules and optimizer_idx == 1:
        # do something else 

```

### Expected behavior

Able to test different numbers of optimizers without changing the `training_step`.

### Environment

- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
- PyTorch Lightning Version: 1.6.4
- PyTorch Version: 1.11.0
- Python version: 3.9
- OS (e.g., Linux): Linux

### Additional context

cc @borda @tchaton @justusschock @awaelchli @carmocca @ananthsub @ninginthecloud @jjenniferdai @rohitgr7

**Comment by awaelchli** [comment]
@icedpanda We cover your use case like this:

```py
def training_step(self, batch, batch_idx, optimizer_idx=0):

```

I'm not sure whether the positional arg should be accepted regardless. But it can be discussed.

**Comment by rohitgr7** [comment]
yes... whenever this happens user needs to change the code to make it compatible with the configuration. Changing this would be great tbh, avoids code updates, but this might break a lot of existing projects, although we can inspect the signature.

same for `dataloader_idx` for val/test/predict.

**Comment by carmocca** [comment]
I vote towards no dynamic injection of arguments based on signatures. The [suggested fix](https://github.com/Lightning-AI/lightning/issues/14323#issuecomment-1221381049) is very simple and pythonic

**Comment by rohitgr7** [comment]
cool! let's close this then.
