### ISSUE TITLE
TPU-related docs are somewhat confusing

### ISSUE THREAD

**Issue by dinhanhx** [Lightning-AI/lightning#14330]
## 📚 Documentation

In [Trainer class api](https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.trainer.trainer.Trainer.html), 
![image](https://user-images.githubusercontent.com/38489776/185774461-fedf381a-b50b-4dd2-bb6b-b0e7ccadb85e.png)
it said not to use accelerator parameter and will be removed in 1.7.0 (current stable version is 1.7.1), BUT `tpu_cores` said to use `accelator`.
![image](https://user-images.githubusercontent.com/38489776/185774488-ab43a0e4-db4d-41db-b250-de270217cc6d.png)
In [Accelerator: TPU Training](https://pytorch-lightning.readthedocs.io/en/stable/accelerators/tpu.html) (also stable version), all the examples use `accelerator='tpu'`.
![image](https://user-images.githubusercontent.com/38489776/185774573-aa744330-f39f-4d78-9c20-479e63106a38.png)

I don't really know which one to follow. And when I head to, [What is a Strategy?](https://pytorch-lightning.readthedocs.io/en/stable/extensions/strategy.html)
![image](https://user-images.githubusercontent.com/38489776/185774697-570cc41c-d3b5-4d86-be48-7733ff7dde1b.png)
I don't really understand why we need `strategy="ddp_spawn"` here when without it, the model is still trained on 8 cores?
Moreover, [Learn more]() of TPU links to examples that don't use any TPU strategy?
![image](https://user-images.githubusercontent.com/38489776/185774757-f5ce79a4-7ba5-4faf-bdbd-15d7ea228e3b.png)

This example should use `precision='bf16'`
![image](https://user-images.githubusercontent.com/38489776/185774787-9b55c134-06ad-4be8-a142-58547c071b27.png)

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging PyTorch Lightning, Transformers, and Hydra.

cc @borda @carmocca @JackCaoG @steventk-g @Liyang90 @rohitgr7 @kaushikb11

**Comment by rohitgr7** [comment]
> it said not to use accelerator parameter and will be removed in 1.7.0 (current stable version is 1.7.1), BUT tpu_cores said to use accelator.

it says passing strategy arguments ('ddp', dp', etc..) to accelerator is deprecated, not the complete parameter.

> I don't really understand why we need strategy="ddp_spawn" here when without it, the model is still trained on 8 cores?

yes, but it depends upon `devices` if you don't set the `strategy` flag explicitly. With `devices=8`, it uses `ddp_spawn` else trains on one TPU core.

> This example should use precision='bf16'

yes, it will through a warning and use `bf16`. But it's a little weird, maybe we should deprecate 16 for TPU and remove it later?
it was added [here](https://github.com/Lightning-AI/lightning/pull/10026) by @carmocca

**Comment by carmocca** [comment]
> maybe we should deprecate 16 for TPU and remove it later?

I had the same question in https://github.com/Lightning-AI/lightning/pull/10020#discussion_r731919838 (the comment liked as "fixed" by https://github.com/Lightning-AI/lightning/pull/10026). But I did not end up deprecating it to "ease transition between accelerator environments" (https://github.com/Lightning-AI/lightning/pull/10026/files#diff-2d97e0bfd5a239885ea0702336cbf3f6dbdaee6a5e255f5ca4da15cb5e260ea9R613)

I somewhat lean towards deprecation in case it ever becomes supported. The docs should be updated regardless of this decision

**Comment by rohitgr7** [comment]
> But I did not end up deprecating it to "ease transition between accelerator environments" 

you mean someone changing from CPU or GPU to TPU?

**Comment by carmocca** [comment]
Yes

**Comment by dinhanhx** [comment]
Re @

> it says passing strategy arguments ('ddp', dp', etc..) to accelerator is deprecated, not the complete parameter.
This was on me. I misread the sentences. It means passing strategy **options**.

Thanks for the rest
