### ISSUE TITLE
Failing (flaky?) test in GPU CI

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lightning#14347]
## 🐛 Bug

```python
>           work = group.broadcast([tensor], opts)
E           RuntimeError: Input tensor data type is not supported for NCCL process group: BFloat16

/home/AzDevOps_azpcontainer/.local/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py:1197: RuntimeError
----------------------------- Captured stderr call -----------------------------
initializing deepspeed distributed: GLOBAL_RANK: 1, MEMBER: 2/2
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
=========================== short test summary info ============================
FAILED strategies/test_deepspeed_strategy.py::test_deepspeed_with_bfloat16_precision
```

### To Reproduce

https://dev.azure.com/Lightning-AI/lightning/_build/results?buildId=90723&view=logs&j=3f274fac-2e11-54ca-487e-194c91f3ae9f&t=7ba6ccc2-87f1-5d8a-85e1-a52b03435dd6&l=1003

### Expected behavior

Green CI

### Environment

Current master

cc @tchaton @rohitgr7 @carmocca @akihironitta @borda

**Comment by otaj** [comment]
https://github.com/NVIDIA/nccl/issues/476 - we need NCCL 2.10.3+, however we have 2.9.9 in our CUDA image

**Comment by carmocca** [comment]
What I don't understand is why this started showing now

**Comment by akihironitta** [comment]
Reopening this issue as I still see the same error in #13137.

**Comment by otaj** [comment]
I think we can safely close this as proper NCCL version is installed in the docker images now
