### ISSUE TITLE
tuner "binsearch" does not reset dataloaders on failure

### ISSUE THREAD

**Issue by yaniv-SX** [Lightning-AI/lightning#14361]
## 🐛 Bug

The tuner has the ability to find the largest fitting batch size through binary search.
On each successful attempt, the tuner increases the batch size and **resets the dataloaders** with the new batch size.
However, on each failed attempt, the tuner decreases the batch size but **does not reset the dataloaders**.

This results in the tuner to continuously fail at finding a smaller batch size after the first failed attempt.
In order to solve this, the tuner needs to reset the dataloaders not only on success, but on failure as well.

### To Reproduce

Simply run a tuning with "binsearch" and notice that the final batch size is always the one before the first failure.
For simplicity, the _init_val_ can be set to a very large number and the final batch size returned will be 1.

cc @akihironitta @borda @rohitgr7

**Comment by rohitgr7** [comment]
true! I think there's an existing issue. Will fix it and close both :)
