### ISSUE TITLE
Metrics summary argument to `WandbLogger.__init__`

### ISSUE THREAD

**Issue by vad13irt** [Lightning-AI/lightning#14388]
## 🚀 Feature

I offer to add a new argument for metrics summary in the `WandbLogger.__init__` method. I know that metrics summary can be easily inserted, please refer to this [amazing guide](https://docs.wandb.ai/guides/integrations/lightning#log-the-min-max-of-your-metric) or this code snippet:

```py    
    def validation_step(self, batch, batch_idx):
        if trainer.global_step == 0: 
            wandb.define_metric('val_accuracy', summary='max')
```

However, if I have a lot of metrics, e.g. 10, I need to copy this line of code 
```py 
wandb.define_metric('val_accuracy', summary='max')
 ```
which makes my `training_step` or `validation_step` function very messy. 

### Solution

I offer to `summary_metrics` argument, which can be given with dictionaries of summary settings, for example, I need to summarize F1 score, Precision, and Recall, so my `summary_metrics` argument will be given with:

```py
summary_metrics = {
"validation_f1": {"summary": "max"},
"validation_precision": {"summary": "max"},
"validation_accuracy": {"summary": "max"},
}

wandb_logger = WandbLogger(..., summary_metrics=summary_metrics)
```

Such an approach can make your `LightningModule` clearer and it will do what it must!

If you have some questions, feel free to ask them!

cc @borda @awaelchli @morganmcg1 @borisdayma @scottire @manangoel99

**Comment by carmocca** [comment]
This proposal should be addressed in the `wandb` repository, where they could overload `define_metric` to support `dict`s or add a `define_metrics` method for collections (I am not a wandb contributor maintainer though!)

You could also do:

```python
for metric, kwargs in summary_metrics.items():
    wandb.define_metric(metric, **kwargs)
```

Which would be very short too.

**Comment by carmocca** [comment]
Also, I would suggest that you define them in the `on_validation_start` instead of in `validation_step` checking the `global_step`

**Comment by vad13irt** [comment]
Thank you for your feedback, @carmocca! You provided more clear examples of how to use it correctly, however, my `LightningModule` code still has these extra lines, so I would prefer to endure them from `LightningModule` and add the necessary functionality for metrics summary to the `WandbLogger`.

**Comment by carmocca** [comment]
`WandbLogger` is just a thin bridge between PL and `wandb`. This functionality is part of the wandb library: https://github.com/wandb/wandb/blob/939c8c754b2346c5fa74692a30496af85773c6a9/wandb/sdk/wandb_run.py#L2264. For this reason, I propose that you open this feature request in their repository instead.

**Comment by manangoel99** [comment]
Hi @vad13irt ! Engineer from W&B here, This is an interesting feature request which I will add as a request internally. Thank you for brining this up

**Comment by vad13irt** [comment]
Thank you, @manangoel99! Waiting to see this functionality as soon as possible 😉 !
