### ISSUE TITLE
Page linked in the doc is empty

### ISSUE THREAD

**Issue by JulesGM** [Lightning-AI/lightning#14393]
[accelerators/gpu_advanced.html](https://pytorch-lightning.readthedocs.io/en/latest/accelerators/gpu_advanced.html), referred from [accelerators/gpu.html](https://pytorch-lightning.readthedocs.io/en/latest/accelerators/gpu.html) as "Advanced", which itself is a very visible page, is empty.

cc @borda @rohitgr7 @justusschock @kaushikb11 @awaelchli @akihironitta

**Comment by krishnakalyan3** [comment]
@carmocca it would be best if we remove this page right?

**Comment by Borda** [comment]
Seem that the cross-link does not work, but you are right that it otherwise duplicated page
https://github.com/Lightning-AI/lightning/blob/master/docs/source-pytorch/accelerators/gpu_advanced.rst#L16

**Comment by rohitgr7** [comment]
the cross link is not added correctly.
