### ISSUE TITLE
Compatibility with PyTorch when the distributed package is not available

### ISSUE THREAD

**Issue by pierocor** [Lightning-AI/lightning#14403]
## 🐛 Bug

From v1.7.0 Lightning is not compatible anymore with PyTorch when the distributed package is not available. 
For example, commits [35841613c](https://github.com/Lightning-AI/lightning/commit/35841613c7caf060208e9763f27e866e292a9b6b) and [c600f987c](https://github.com/Lightning-AI/lightning/commit/c600f987c) import from `torch.distributed` without checking if `torch.distributed.is_available()`.
Is this a bug or the intended behavior?

### To Reproduce
Install PyTorch from source setting `USE_DISTRIBUTED=0` then install pytorch-lightning>=1.7.0.

```
$ python -c "import pytorch_lightning as plt"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/x86_64/pytorch-lightning/1.7.2/lib/python3.9/site-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/x86_64/pytorch-lightning/1.7.2/lib/python3.9/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/x86_64/pytorch-lightning/1.7.2/lib/python3.9/site-packages/pytorch_lightning/callbacks/callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/x86_64/pytorch-lightning/1.7.2/lib/python3.9/site-packages/pytorch_lightning/utilities/types.py", line 26, in <module>
    from torch._C._distributed_c10d import ProcessGroup
ModuleNotFoundError: No module named 'torch._C._distributed_c10d'; 'torch._C' is not a package
```

### Expected behavior

Successfully import pytorch-lightning.

### Environment

- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): None
- PyTorch Lightning Version (e.g., 1.5.0): 1.7.2
- Lightning App Version (e.g., 0.5.2): 
- PyTorch Version (e.g., 1.10): 1.12
- Python version (e.g., 3.9): 3.9.7
- OS (e.g., Linux): Linux
- CUDA/cuDNN version: 11.6
- GPU models and configuration: 
- How you installed PyTorch (`conda`, `pip`, source): SOURCE
- If compiling from source, the output of `torch.__config__.show()`:
- PyTorch built with:
  - GCC 11.2
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash N/A)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.4.1, CXX_COMPILER=/mpcdf/soft/SLE_15/packages/x86_64/gcc/11.2.0/bin/g++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, USE_CUDA=1, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,
- Running environment of LightningApp (e.g. local, cloud):
- Any other relevant information:

cc @awaelchli @rohitgr7 @akihironitta

**Comment by carmocca** [comment]
Sorry for the inconvenience. Yes, this is a bug.

Would you like to open a PR with a fix?

**Comment by pierocor** [comment]
Yes, I'll open a PR in the next days.
