### ISSUE TITLE
Fix `lightning --version` cmd

### ISSUE THREAD

**Issue by manskx** [Lightning-AI/lightning#14410]
## 🐛 Bug

`lightning --version` doesn't work.
it gets this error:

```
WARNING: Lightning Commands are a beta feature and APIs aren't stable yet.
Traceback (most recent call last):
  File "/Users/mansy/src/lightning-hpo/venv/bin/lightning", line 8, in <module>
    sys.exit(main())
  File "/Users/mansy/src/lightning/src/lightning_app/cli/lightning_cli.py", line 54, in main
    app_command()
  File "/Users/mansy/src/lightning/src/lightning_app/cli/lightning_cli.py", line 357, in app_command
    url, api_commands = _retrieve_application_url_and_available_commands(hparams.app_id)
  File "/Users/mansy/src/lightning/src/lightning_app/utilities/cli_helpers.py", line 113, in _retrieve_application_url_and_available_commands
    raise Exception(f"Provide an application name, id or url with --app_id=X. Found {lightningapp_names}")
Exception: Provide an application name, id or url with --app_id=X. Found [......]

``` 

### To Reproduce

`pip install -e .`
`lightning --version`

### Expected behavior

Showing lightning version

### Environment
* Lightning:
        - lightning:         2022.8.26
        - lightning-app:     0.5.7
        - lightning-cloud:   0.5.3
        - lightning-hpo:     0.0.1
        - pytorch-lightning: 1.7.2
        - torch:             1.12.1
        - torchmetrics:      0.9.3
        - torchvision:       0.10.0

cc @tchaton @rohitgr7

**Comment by krishnakalyan3** [comment]
I was unable to reproduce this issue.

**Comment by manskx** [comment]
> I was unable to reproduce this issue.

@krishnakalyan3 Did you try the released version of lightning or the current master ?
The issue is with the master of lightning, not the released one.

**Comment by krishnakalyan3** [comment]
I am on the master branch

**Comment by rohitgr7** [comment]
tried on master and it's failing with the same error.

**Comment by krishnakalyan3** [comment]
![image](https://user-images.githubusercontent.com/4648995/187097345-2ddc71e8-4558-403d-ae57-f34cef105bbe.png)

**Comment by manskx** [comment]
> ![image](https://user-images.githubusercontent.com/4648995/187097345-2ddc71e8-4558-403d-ae57-f34cef105bbe.png)

@krishnakalyan3 This is an old version of lightning. I guess it's not installed from the source. 
Could you do `pip install -e .` then try `lightning --version`
