### ISSUE TITLE
DDP Support in Notebooks when Launching SLURM (or similar) Jobs

### ISSUE THREAD

**Issue by jgbos** [Lightning-AI/lightning#14421]
## 🚀 Feature

For `ddp`, set `_SubprocessScriptLauncher.is_interactive_compatible()` to `True` when multiprocessing is handled by SLURM.  This will allow users to launch jobs from the notebook.

### Motivation

Currently a user cannot launch jobs from a notebook because of this check.  If I hard code the `True` value I am able to launch jobs via notebooks without any issues.

### Pitch

```python
class _SubprocessScriptLauncher(_Launcher):
    ...
    @property
    def is_interactive_compatible(self) -> bool:
        if multiprocessing_handled_by_slurm:
           return True
        return False
```

I am unsure when `_SubprocessScriptLauncher.is_interactive_compatible` is called if the processing environment is known.

cc @borda @justusschock @kaushikb11 @awaelchli @akihironitta @rohitgr7

**Comment by awaelchli** [comment]
Hi
I am a bit perplexed by this request. How exactly are you executing your jupyter notebooks in slurm?

> Currently a user cannot launch jobs from a notebook because of this check

This is very well the intention. When multiprocessing is handled by SLURM, it means you, the user, and Lightning, should not launch any processes. 

I'm pretty sure we won't do what you are pitching. The `_SubprocessScriptLauncher` does what it says, it can launch a script from within itself and the emphasis here is on script. 

The only ddp support we have in interactive environments is through the multiprocessing launcher and the fork start method `Trainer(strategy="ddp_notebook" | "ddp_fork")`.

**Comment by jgbos** [comment]
I use [Submitit](https://github.com/facebookincubator/submitit).  I can load a notebook on the cluster and launch jobs via the notebook.  Really great feature and something I utilize quite a bit.

But yeah, I wasn't sure if you detected that "multiprocessing is handled by slurm" (from the logs) before checking if you could run in interactive mode.  I can check out `ddp_notebook`, I remember trying that awhile ago and it did not work.

**Comment by jgbos** [comment]
Oh shoot, I'm a moron.  It does work, I had a bad settings.

**Comment by awaelchli** [comment]
@jgbos Glad you found this out yourself. Let us know if you have any further questions.
