### ISSUE TITLE
track_grad_norm raises MisconfigurationException when batch size cannot be inferred

### ISSUE THREAD

**Issue by m-decoster** [Lightning-AI/lightning#14496]
## 🐛 Bug

When the batch size cannot be inferred, `track_grad_norm` raises a `MisconfigurationException` and cannot be used.

### To Reproduce

See https://colab.research.google.com/gist/m-decoster/bae7a67f6b71825015581f3bb8cfa8c3/bug_report_model.ipynb.
You can remove the line `track_grad_norm=2` in the `Trainer` construction and the code will run.

### Expected behavior

This is normal behavior, but there should be a way to track gradient norms with a custom Batch class.

### Environment

Google Colab

cc @carmocca @edward-io @ananthsub @rohitgr7 @kamil-kaczmarek @Raalsky @Blaizzy @akihironitta

**Comment by rohitgr7** [comment]
you can override log_grad_norm to overcome this:
```py
class LitModel(LightningModule):
    def log_grad_norm(self, grad_norm_dict):
        self.log_dict(grad_norm_dict, on_step=True, on_epoch=True, prog_bar=False, logger=True, batch_size=your_batch_size)
```
