### ISSUE TITLE
Fine tune T5 for a classification, but this error appears: "ValueError: You have to specify either decoder_input_ids or decoder_inputs_embeds"

### ISSUE THREAD

**Issue by Felonious-Spellfire** [Lightning-AI/lightning#14521]
## 📚 Documentation

This error appears while trying to fine-tune T5 for a classification:

`ValueError: You have to specify either decoder_input_ids or decoder_inputs_embeds`

09/05/2022 Update: Edited ticket until the user replies

cc @Felonious-Spellfire

**Comment by awaelchli** [comment]
If the user replies, let's follow up on asking which code base they run. It is likely that they use [lightning-transformers](https://github.com/Lightning-AI/lightning-transformers), and we can address potential doc- or other issues there.

**Comment by uakarsh** [comment]
Hi @Felonious-Spellfire, I think this issue seems familiar to this [link](https://github.com/huggingface/transformers/issues/3626). For your reference, can you look at this [issue](https://github.com/huggingface/transformers/issues/16234) as well, if that helps?
