### ISSUE TITLE
Arguments to _ _ init _ _() in Loops

### ISSUE THREAD

**Issue by Felonious-Spellfire** [Lightning-AI/lightning#14524]
## 📚 Documentation

Update content for Loops: https://pytorch-lightning.readthedocs.io/en/latest/extensions/loops.html

to better explain the arguments to _ _ init _ _()

Adrian commented: 

when you subclass the Loop base class, you can choose whatever init arguments you want. Whatever is required by your loop, you can pass it in there. Or you can subclass an existing loop and change its init method.

cc @borda @Felonious-Spellfire @carmocca @justusschock

**Comment by awaelchli** [comment]
Closing, as loops are now protected API, and not meant to be extended by users. Loop customization is only available in 1.9.x.
