### ISSUE TITLE
Replace mentions of `.type_as()` in our docs

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#14554]
## 📚 Documentation

As a follow up to #2585, we should consider removing mentions of the `.type_as()` syntax in our docs and replace it with best practices for device placement and type conversion. 

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging PyTorch Lightning, Transformers, and Hydra.

cc @borda @rohitgr7 @Felonious-Spellfire

**Comment by nsarang** [comment]
`Tensor.to` can be used as a safe replacement for `type_as`. It also accepts another tensor as input.

From the [documentation](https://pytorch.org/docs/1.11/generated/torch.Tensor.to.html):

> torch.to(other, non_blocking=False, copy=False) → [Tensor](https://pytorch.org/docs/1.11/tensors.html#torch.Tensor)
Returns a Tensor with same [torch.dtype](https://pytorch.org/docs/1.11/tensor_attributes.html#torch.torch.dtype) and [torch.device](https://pytorch.org/docs/1.11/tensor_attributes.html#torch.torch.device) as the Tensor other. When non_blocking, tries to convert asynchronously with respect to the host if possible, e.g., converting a CPU Tensor with pinned memory to a CUDA Tensor. When copy is set, a new Tensor is created even when the Tensor already matches the desired conversion.

**Comment by amrutha1098** [comment]
Hey @awaelchli can i work on this issue ? I would like to contribute .

**Comment by awaelchli** [comment]
@amrutha1098 Yes, that would be greatly appreciated! And please let me know if you need any further guidance regarding this issue or the contribution process.

**Comment by amrutha1098** [comment]
Hi @awaelchli , I have submitted the PR with the changes. Please let me know if any changes are required. 
Thank you for you help !!
