### ISSUE TITLE
Automatic LR finder for DDP

### ISSUE THREAD

**Issue by dhananjaisharma10** [Lightning-AI/lightning#14624]
## 🚀 Feature

Currently, `auto_lr_find` is only supported for a single GPU. It would be good to have this support for a DDP environment. This is mentioned in the Lightning docs [here](https://pytorch-lightning.readthedocs.io/en/stable/advanced/training_tricks.html?highlight=LEARNING%20RATE%20FINDER#learning-rate-finder).

### Motivation

The motivation is quite simple. A lot of people use multi-GPU environments to train their models. Having an automatic LR finder for this will help them.

### Pitch

None.

### Alternatives

None.

### Additional context

Discussed this issue already in the PL Slack channel with @rohitgr7, @krshrimali and @awaelchli.

cc @borda @justusschock @kaushikb11 @awaelchli @akihironitta @rohitgr7

**Comment by krshrimali** [comment]
Thanks, @dhananjaisharma10 for creating the issue! For anyone else who wants this feature, feel free to put a thumbs up to the issue and let us know 🔥 There is an opened PR where @rohitgr7 is working on adding this feature: https://github.com/Lightning-AI/lightning/pull/11089.
