### ISSUE TITLE
Lightning update serves an error although installs successfully

### ISSUE THREAD

**Issue by likethecognac** [Lightning-AI/lightning#14658]
### Environment

- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
- PyTorch Lightning Version (e.g., 1.5.0):
- Lightning App Version (e.g., 0.5.2):
- PyTorch Version (e.g., 1.10):
- Python version (e.g., 3.9):
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Running environment of LightningApp (e.g. local, cloud):
- Any other relevant information:

**Comment by krshrimali** [comment]
Hi, @likethecognac - Thanks for creating the issue. Could you please share what's the error? I'll need just a bit more info about the error, and rest assured - we'll try to help out as soon as possible. :)
