### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by akihironitta** [Lightning-AI/lightning#14652]
## 🚀 Feature
This is a tracking issue to support Python 3.11 released on 2022-10-03.

### Additional context
- [PEP 664 – Python 3.11 Release Schedule](https://peps.python.org/pep-0664/)
- [What’s New In Python 3.11](https://docs.python.org/3.11/whatsnew/3.11.html)

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging PyTorch Lightning, Transformers, and Hydra.

cc @borda @carmocca

**Comment by awaelchli** [comment]
Regarding PyTorch's support of 3.11, updates can be found here: https://github.com/pytorch/pytorch/issues/86566

**Comment by akihironitta** [comment]
Looking at the linked PyTorch's GH issue, I think we can start working on this. The instability issue they mention only applies to their conda CI.

**Comment by mrembalski** [comment]
Hi there! Does this have a planned date of release?

**Comment by Borda** [comment]
> Hi there! Does this have a planned date of release?

We are happy to add it, but in this case, we are very dependent on PyToch, see: https://github.com/pytorch/pytorch/issues/86566

**Comment by mrembalski** [comment]
> > Hi there! Does this have a planned date of release?
> 
> We are happy to add it, but in this case, we are very dependent on PyToch, see: [pytorch/pytorch#86566](https://github.com/pytorch/pytorch/issues/86566)

Sorry, I did not know that. Thank you for explaining.

**Comment by eric-01001000** [comment]
PyTorch is now Python 3.11 compatible, it would be great to get a release date here as well.
