### ISSUE TITLE
How to use bitsandbytes

### ISSUE THREAD

**Issue by turian** [Lightning-AI/lightning#14701]
## 📚 Documentation

The docs on [8-bit precision](https://pytorch-lightning.readthedocs.io/en/1.6.1/advanced/precision.html#bit-optimizer) say you can use bitsandbytes, and "Although, Lightning doesn’t support it out of the box yet but you can still use it by configuring it in your [LightningModule](https://pytorch-lightning.readthedocs.io/en/1.6.1/api/pytorch_lightning.core.LightningModule.html#pytorch_lightning.core.LightningModule) and setting Trainer(precision=32)."

What does that mean? Shouldn't `precision=8`? Otherwise, how do you "configure" bitsandbytes in your LightningModule?

cc @borda @rohitgr7 @Felonious-Spellfire

**Comment by awaelchli** [comment]
@turian What the docs were trying to say by Trainer(precision=32) is, leave the precision setting on the default in the Trainer and then configure your third-party library to use the precision from them, i.e., use their functions to cast inputs, convert operations, and so on. 

We should remove the mention to bitsandbytes in our docs, it looks like this project is dead. We can mention others if you have any suggestions?

**Comment by turian** [comment]
@awaelchli Doesn't seem like bitandbytes is dead, it's just owned by @TimDettmers now: https://github.com/TimDettmers/bitsandbytes

Last commit 16 hours ago, last release 2 days ago.

**Comment by awaelchli** [comment]
Oh ok, my bad, I was reading that it is no longer supported. In this case, we can link to the new repository and maybe add a small snippet how to configure the optimizer and layers.
