### ISSUE TITLE
lightning merlin dependency issues

### ISSUE THREAD

**Issue by zlapp** [Lightning-AI/lightning#14729]
## 🐛 Bug

I was not able to install merlin along with lightning

### To Reproduce

```
conda create -n lai_merlin python=3.8
conda activate lai_merlin
```
requirements.txt:

```
lightning
merlin-systems
merlin-core
merlin-models
nvtabular
transformers4rec[pytorch,nvtabular]
```
Run:
```
pip install -r requirements.txt
```

### Expected behavior

```
ERROR: Cannot install lightning and transformers4rec[nvtabular,pytorch]==0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    transformers4rec[nvtabular,pytorch] 0.1 depends on torchmetrics==0.3.2; extra == "pytorch"
    pytorch-lightning 1.6.5 depends on torchmetrics>=0.4.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by carmocca** [comment]
You can try using `pytorch_lightning<=1.3`, which allows for `torchmetrics==0.3.2`. Otherwise, this `transformers4rec` package will need to update its dependency

**Comment by Borda** [comment]
> You can try using `pytorch_lightning<=1.3`, which allows for `torchmetrics==0.3.2`. Otherwise, this `transformers4rec` package will need to update its dependency

I agree this shall be rather addressed on transformers4rec side as they pin very old version with several known bugs...

**Comment by carmocca** [comment]
I notice that you installed `lightning`. This is really just a wrapper for our separate packages. If you are interested in running apps with PyTorch Lightning inside in a specific version, you can install the two packages separately:

```bash
$ pip install pytorch-lightning==1.3
...
$ pip install lightning-app
...
$ pip freeze | grep lightning
lightning-app==0.6.0
lightning-cloud==0.5.3
lightning-utilities==0.3.0
pytorch-lightning==1.3.0
```
