### ISSUE TITLE
User can't disable _sanity_check before training

### ISSUE THREAD

**Issue by AlexWang1900** [Lightning-AI/lightning#14774]
### First check

- [X] I'm sure this is a bug.
- [X] I've added a descriptive title to this bug.
- [X] I've provided clear instructions on how to reproduce the bug.
- [X] I've added a code sample.
- [X] I've provided any other important info that is required.

### Bug description

When training IRTR tasks, validation is way long than one can imagine, and sanity check before training took so long, and not necessary for every run.
for example : https://github.com/dandelin/ViLT
When training finetune_irtr_coco_randaug , the image text retrieval task. and validation took 30~ hours using 2 2080TIs, 
It is unacceptable for me to wait 30~ hours for sanity check.

### How to reproduce the bug

```python
https://github.com/dandelin/ViLT
following the project's description,do a task on:
Finetune on COCO IR/TR
prepare data then run:

export MASTER_ADDR=$DIST_0_IP
export MASTER_PORT=$DIST_0_PORT
export NODE_RANK=$DIST_RANK
python run.py with data_root=<ARROW_ROOT> num_gpus=<NUM_GPUS> num_nodes=<NUM_NODES> task_finetune_irtr_coco_randaug per_gpu_batchsize=<BS_FITS_YOUR_GPU> load_path="<YOUR_WEIGHT_ROOT>/vilt_200k_mlm_itm.ckpt"

ex)
python run.py with data_root=/data2/dsets/dataset num_gpus=8 num_nodes=1 task_finetune_irtr_coco_randaug per_gpu_batchsize=4 load_path="weights/vilt_200k_mlm_itm.ckpt"
```

### Error messages and logs

```

# Error messages and logs here please

```
![bug](https://user-images.githubusercontent.com/60679873/190947180-c042080a-b862-4d61-8cec-5aeb2f6e1174.png)

it took 34~ hours 

### Important info

```

#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):

```
- PyTorch Lightning Version :1.7.6
- python: 3.9
- os:ubuntu 22.04
- GPU: 2 2080TIs
- Pytorch version: 1.10.0
- CUDA: 11.3
- How you installed Lightning: get code then python setup.py develop

**Comment by DuinoDu** [comment]
Set [num_sanity_val_steps](https://github.com/Lightning-AI/lightning/blob/master/src/pytorch_lightning/trainer/trainer.py#L349) to 0 can disable _sanity_check before training.

May it help.

**Comment by AlexWang1900** [comment]
Great! that helps!!!
