### ISSUE TITLE
WandbLogger documentation includes unwatch() method. There is no unwatch method in the source code

### ISSUE THREAD

**Issue by suyash-811** [Lightning-AI/lightning#14865]
I was taking a look at the WandbLogger documentation: https://pytorch-lightning.readthedocs.io/en/latest/extensions/generated/pytorch_lightning.loggers.WandbLogger.html?highlight=wandblogger

The documentation suggests to use the unwatch() method to remove any hooks inserted by wandb.watch()
![image](https://user-images.githubusercontent.com/59940049/191935706-db10e1a0-0f0b-47c6-90f1-37649751d418.png)
However, there is no unwatch method in the WandbLogger source code (as far as i could see)

I would love to edit this out of the documentation, but i'm not sure how i can do it. Hence creating this good-first-issue.
Thanks, and i apologize if i raised this issue in an incorrect way.

**Comment by awaelchli** [comment]
Hey @suyash-811 
I think this line should be `wandb_logger.experiment.unwatch(model)`. 

> I would love to edit this out of the documentation, but i'm not sure how i can do it. Hence creating this good-first-issue.

Thanks a lot for offering a contribution. You can find it in the docstring for WandbLogger in `src/pytorch_lightning/loggers/wandb.py`

To make an edit, I suggest you:

1. Fork the Lightning repository
2. Clone that fork to your local computer
3. Create a new branch with git
4. Make the change locally
5. Then push it to your fork
6. When you go back to GitHub, it will show you a notification at the top where you can open a PR from your fork to the main repo here. 

For more guidelines about contributing, you can read here: https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md

> Thanks, and i apologize if i raised this issue in an incorrect way

This is the BEST way to raise an issue like this <3

**Comment by suyash-811** [comment]
@awaelchli thanks for the encouraging reply. I changed the docstring, and have created a PR for the same. Was a great experience to contribute to open-source for the first time. Hope to do more eventually :)

**Comment by awaelchli** [comment]
Nice work! More help is always appreciated. Your PR will get merged soon :)
