### ISSUE TITLE
SLURMEnvironment fails to parse the root node address in certain case

### ISSUE THREAD

**Issue by senarvi** [Lightning-AI/lightning#14896]
### First check

- [X] I'm sure this is a bug.
- [X] I've added a descriptive title to this bug.
- [X] I've provided clear instructions on how to reproduce the bug.
- [X] I've added a code sample.
- [X] I've provided any other important info that is required.

### Bug description

SLURM may contract the list of addresses in the `SLURM_NODELIST` environment variable. For example, if a job gets assigned to the nodes `linux1` and `linux2`, the environment variable will contain `linux[1,2]`.

[SLURMEnvironment.main_address()](https://github.com/Lightning-AI/lightning/blob/master/src/lightning_lite/plugins/environments/slurm_environment.py#L53) will split the string at commas and take the first one, so the root node will be set to `linux[1`.

### How to reproduce the bug

```python
1. Create a SLURM cluster with nodes linux1 and linux2. Not sure if you also have to configure the partition like this:

    PartitionName=linux Nodes=linux[1,2]

2. Submit a training job to multiple nodes.

3. Observe the `root_node` variable in `SLURMEnvironment.main_address()`.
```

### Error messages and logs

```

# Error messages and logs here please

```

### Important info

```

#- Lightning Component: SLURMEnvironment
#- PyTorch Lightning Version: 1.7.7
#- SLURM Version: 21.08.7

```

### More info

The `[` character is not allowed in domain names, so the obvious solution would be to replace

    root_node = slurm_nodelist.split(" ")[0].split(",")[0]

with

    root_node = slurm_nodelist.split(" ")[0].split(",")[0].replace("[", "")

**Comment by awaelchli** [comment]
Hey @senarvi 
Thanks for reporting this. It looks like we need to support parsing names of the form `linux[1-9]`, `linux[01-09]`, `linux[1,2]`, `linux[2,3-5]` and so on. We're only interested in the first node, as this one is determined the "main" one. 

Would you be interested looking into these cases and to make a contribution?

**Comment by senarvi** [comment]
> Hey @senarvi Thanks for reporting this. It looks like we need to support parsing names of the form `linux[1-9]`, `linux[01-09]`, `linux[1,2]`, `linux[2,3-5]` and so on. Are there other patterns I have missed? We're only interested in the first node, as this one is determined the "main" one.
> 
> Would you be interested looking into these cases and to make a contribution?

@awaelchli That's a good point. At least the patterns that you mentioned are valid. Those are probably the most common ones. I don't know if e.g. `[1-9]linux` or `[linux,unix][1-9]` are valid. Maybe it's best to use a regular expression, something like this:

    re.sub("\[(.*?)[,-].*?\]", "\\1", x)

I'll create a pull request tomorrow. I'm not sure what this is for, but I'll keep it there:

    slurm_nodelist.split(" ")[0]

**Comment by awaelchli** [comment]
Fantastic, this regex looks great, I think this could work yes. 

> I'm not sure what this is for, but I'll keep it there:
> 
> slurm_nodelist.split(" ")[0]

Probably because we wanted to support the format "host0 host1 host3" with space separation instead of commas.

**Comment by senarvi** [comment]
@awaelchli sorry, but this was not the source of my problems at all. I completely missed that there is the function [resolve_root_node_address()](https://github.com/Lightning-AI/lightning/blob/master/src/lightning_lite/plugins/environments/slurm_environment.py#L137) that does the same thing as my regex. It's maybe slightly more complex, but I guess it's better not to touch it now that it's working.

**Comment by awaelchli** [comment]
Yes you are right, silly I missed this too. Perhaps the name of that function is a bit misleading. If this is not the source of the problem, what exactly is it that is misbehaving on your end? Do processes hang / not start? If so, please have a quick look at the troubleshooting page I added in this PR, #14873, maybe it helps.

**Comment by senarvi** [comment]
The problem was in how I launch the SLURM job. I think it's clear now. Thanks!
