### ISSUE TITLE
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found 

### ISSUE THREAD

**Issue by bhaktatejas922** [Lightning-AI/lightning#14985]
### Bug description

GLIBCXX_3.4.21 isnt found. I already conda installed libgcc. I tried this https://github.com/BVLC/caffe/issues/4953#:~:text=Mar%2030%2C%202021-,try%3A,not%20doing%20multiprocessing%20code.%20For%20me%20that%20gave%20me%20pickle%20errors.,-%E2%9D%A4%EF%B8%8F

and I can train without an exception being thrown, however my training time per iteration exponentially grows and grows until the job crashes. Time estimate for an epoch starts at 17 min, then keeps increasing to 2hrs and more until it crashes. I think this is due to this fix not being ideal but I'm not sure. 

I'm trying to train on a slurm cluster. 

conda 22.9.0

### Error messages and logs

```

# Error messages and logs here please

```
```
Traceback (most recent call last):
  File "/home/tbhakta/anaconda3/envs/cart-38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tbhakta/anaconda3/envs/cart-38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/tef/cartographer/src/main.py", line 8, in <module>
    import pytorch_lightning as pl
  File "/home/tbhakta/anaconda3/envs/cart-38/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/tbhakta/anaconda3/envs/cart-38/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py", line 26, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "/home/tbhakta/anaconda3/envs/cart-38/lib/python3.8/site-packages/pytorch_lightning/callbacks/pruning.py", line 30, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/home/tbhakta/anaconda3/envs/cart-38/lib/python3.8/site-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/home/tbhakta/anaconda3/envs/cart-38/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 41, in <module>
    from pytorch_lightning.loggers import Logger, LoggerCollection
  File "/home/tbhakta/anaconda3/envs/cart-38/lib/python3.8/site-packages/pytorch_lightning/loggers/__init__.py", line 23, in <module>
    from pytorch_lightning.loggers.tensorboard import TensorBoardLogger
  File "/home/tbhakta/anaconda3/envs/cart-38/lib/python3.8/site-packages/pytorch_lightning/loggers/tensorboard.py", line 26, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/tbhakta/anaconda3/envs/cart-38/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/home/tbhakta/anaconda3/envs/cart-38/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 9, in <module>
    from tensorboard.compat.proto.event_pb2 import SessionLog
  File "/home/tbhakta/anaconda3/envs/cart-38/lib/python3.8/site-packages/tensorboard/compat/proto/event_pb2.py", line 8, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/home/tbhakta/anaconda3/envs/cart-38/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/tbhakta/anaconda3/envs/cart-38/lib/python3.8/site-packages/google/protobuf/pyext/_message.cpython-38-x86_64-linux-gnu.so)
slurmstepd: error: *** STEP 129460.0 ON s02-rtx22 CANCELLED AT 2022-10-03T15:20:16 ***
```

### Environment

```

#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0): pytorch-lightning           1.7.6
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10): Tried 1.10, 1.13
#- Python version (e.g., 3.9): tried on 3.8 and 3.10
#- OS (e.g., Linux): Redhat
#- CUDA/cuDNN version: Cuda 11.7
#- GPU models and configuration: RTX5000's 
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud): slurm

```
`➜ pip list
Package                            Version
---------------------------------- -------------------
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.9.12
anaconda-project                   0.8.3
argh                               0.26.2
asn1crypto                         1.3.0
astroid                            2.3.3
astropy                            4.0
atomicwrites                       1.3.0
attrs                              19.3.0
autopep8                           1.4.4
Babel                              2.8.0
backcall                           0.1.0
backports.functools-lru-cache      1.6.4
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
beautifulsoup4                     4.8.2
bitarray                           1.2.1
bkcharts                           0.2
bleach                             3.1.0
bokeh                              1.4.0
boto                               2.49.0
Bottleneck                         1.3.2
certifi                            2019.11.28
cffi                               1.14.0
chardet                            3.0.4
Click                              7.0
cloudpickle                        1.3.0
clyent                             1.2.2
colorama                           0.4.3
conda                              22.9.0
conda-build                        3.18.11
conda-package-handling             1.7.3
conda-verify                       3.4.2
contextlib2                        0.6.0.post1
cryptography                       2.8
cycler                             0.10.0
Cython                             0.29.15
cytoolz                            0.10.1
dask                               2.11.0
decorator                          4.4.1
defusedxml                         0.6.0
diff-match-patch                   20181111
distributed                        2.11.0
docutils                           0.16
entrypoints                        0.3
et-xmlfile                         1.0.1
fastcache                          1.1.0
filelock                           3.0.12
flake8                             3.7.9
Flask                              1.1.1
fsspec                             0.6.2
future                             0.18.2
gevent                             1.4.0
glob2                              0.7
gmpy2                              2.0.8
greenlet                           0.4.15
h5py                               2.10.0
HeapDict                           1.0.1
html5lib                           1.0.1
hypothesis                         5.5.4
idna                               2.8
imageio                            2.6.1
imagesize                          1.2.0
importlib-metadata                 1.5.0
intervaltree                       3.0.2
ipykernel                          5.1.4
ipython                            7.12.0
ipython-genutils                   0.2.0
ipywidgets                         7.5.1
isort                              4.3.21
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.14.1
jeepney                            0.4.2
Jinja2                             2.11.1
joblib                             0.14.1
json5                              0.9.1
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     5.3.4
jupyter-console                    6.1.0
jupyter-core                       4.6.1
jupyterlab                         1.2.6
jupyterlab-server                  1.0.6
keyring                            21.1.0
kiwisolver                         1.1.0
lazy-object-proxy                  1.4.3
libarchive-c                       2.8
lief                               0.9.0
llvmlite                           0.31.0
locket                             0.2.0
lxml                               4.5.0
MarkupSafe                         1.1.1
matplotlib                         3.1.3
mccabe                             0.6.1
mistune                            0.8.4
mkl-fft                            1.0.15
mkl-random                         1.1.0
mkl-service                        2.3.0
mock                               4.0.1
more-itertools                     8.2.0
mpmath                             1.1.0
msgpack                            0.6.1
multipledispatch                   0.6.0
navigator-updater                  0.2.1
nbconvert                          5.6.1
nbformat                           5.0.4
networkx                           2.4
nltk                               3.4.5
nose                               1.3.7
notebook                           6.0.3
numba                              0.48.0
numexpr                            2.7.1
numpy                              1.18.1
numpydoc                           0.9.2
olefile                            0.46
openpyxl                           3.0.3
packaging                          20.1
pandas                             1.0.1
pandocfilters                      1.4.2
parso                              0.5.2
partd                              1.1.0
path                               13.1.0
pathlib2                           2.3.5
pathtools                          0.1.2
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             7.0.0
pip                                20.0.2
pkginfo                            1.5.0.1
pluggy                             0.13.1
ply                                3.11
prometheus-client                  0.7.1
prompt-toolkit                     3.0.3
psutil                             5.6.7
ptyprocess                         0.6.0
py                                 1.8.1
pycodestyle                        2.5.0
pycosat                            0.6.3
pycparser                          2.19
pycrypto                           2.6.1
pycurl                             7.43.0.5
pydocstyle                         4.0.1
pyflakes                           2.1.1
Pygments                           2.5.2
pylint                             2.4.4
pyodbc                             4.0.0-unsupported
pyOpenSSL                          19.1.0
pyparsing                          2.4.6
pyrsistent                         0.15.7
PySocks                            1.7.1
pytest                             5.3.5
pytest-arraydiff                   0.3
pytest-astropy                     0.8.0
pytest-astropy-header              0.1.2
pytest-doctestplus                 0.5.0
pytest-openfiles                   0.4.0
pytest-remotedata                  0.3.2
python-dateutil                    2.8.1
python-jsonrpc-server              0.3.4
python-language-server             0.31.7
pytz                               2019.3
PyWavelets                         1.1.1
pyxdg                              0.26
PyYAML                             5.3
pyzmq                              18.1.1
QDarkStyle                         2.8
QtAwesome                          0.6.1
qtconsole                          4.6.0
QtPy                               1.9.0
requests                           2.22.0
rope                               0.16.0
Rtree                              0.9.3
ruamel-yaml                        0.15.87
scikit-image                       0.16.2
scikit-learn                       0.22.1
scipy                              1.4.1
seaborn                            0.10.0
SecretStorage                      3.1.2
Send2Trash                         1.5.0
setuptools                         45.2.0.post20200210
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.14.0
snowballstemmer                    2.0.0
sortedcollections                  1.1.2
sortedcontainers                   2.1.0
soupsieve                          1.9.5
Sphinx                             2.4.0
sphinxcontrib-applehelp            1.0.1
sphinxcontrib-devhelp              1.0.1
sphinxcontrib-htmlhelp             1.0.2
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.2
sphinxcontrib-serializinghtml      1.1.3
sphinxcontrib-websupport           1.2.0
spyder                             4.0.1
spyder-kernels                     1.8.1
SQLAlchemy                         1.3.13
statsmodels                        0.11.0
sympy                              1.5.1
tables                             3.6.1
tblib                              1.6.0
terminado                          0.8.3
testpath                           0.4.4
toolz                              0.10.0
tornado                            6.0.3
tqdm                               4.42.1
traitlets                          4.3.3
ujson                              1.35
unicodecsv                         0.14.1
urllib3                            1.25.8
watchdog                           0.10.2
wcwidth                            0.1.8
webencodings                       0.5.1
Werkzeug                           1.0.0
wheel                              0.34.2
widgetsnbextension                 3.5.1
wrapt                              1.11.2
wurlitzer                          2.0.0
xlrd                               1.2.0
XlsxWriter                         1.2.7
xlwt                               1.3.0
xmltodict                          0.12.0
yapf                               0.28.0
zict                               1.0.0
zipp                               2.2.0`

**Comment by otaj** [comment]
Hi, thank you for reporting the issue. This looks very weird, are you sure, the `pip list` was run in the same environment you are running your script in? Because it looks, like you not only don't have `protobuf` installed (which is the package emitting the error), it also looks like you don't even have `lightning` or `pytorch-lightning` installed. Can you please check your `pip list` is done from the same environment in which you are experiencing this error?

**Comment by Vishu26** [comment]
This is an error I once encountered with `opencv`. Solved it by installing `opencv-python-headless`. Note sure if it is the same for you.

**Comment by bhaktatejas922** [comment]
@otaj I mustve pasted the wrong env, sorry. I moved down to python3.9 and the issue went away. Thanks
