### ISSUE TITLE
Add option to not flatten config in WandbLogger.log_hyperparams

### ISSUE THREAD

**Issue by zephyap** [Lightning-AI/lightning#14988]
## 🚀 Feature

Reopening [issue #9264](https://github.com/Lightning-AI/lightning/issues/9264): Make the config flattening that happens in WandbLogger.log_hyperparams optional.

### Motivation

Similar to the original issue, flattening the config makes it harder to re-use later.

From the original issue:
> Wandb support nested config by default. Furthermore, by flattening the configuration it makes it more difficult to load an experiment from a wandb run – instead of taking the config directly from the run, you have to un-flatten it first (or really, not use log_hyperparams and instead do it manually).

### Pitch

Add `flatten: bool = True` as a kwarg in `log_hyperparams.`

### Alternatives

- Creating custom logger subclasses that do not flatten the config
  - Feels hacky, does not keep up well with new loggers being added.
- Writing our own function to unflatten the config
  - Seems like a workable alternative, albeit a roundabout one. It adds one more moving piece to the system in order for configs to be reused, so my preference would still be to not flatten it at all, if possible.

cc @borda @awaelchli @morganmcg1 @borisdayma @scottire @parambharat

**Comment by dsuess** [comment]
This would be a great feature to add. Note that since #2458, Wandb has added support to properly display non-flattened configs in their UI. Since we often don't control where `log_hyperparams` gets called, I think a init-argument to toggle this behaviour would be handy.

**Comment by mattcleigh** [comment]
Inspecting the hyperparameters on the wandb website is certainly easier without flattening, as it is presented as a collapsible dropdown list. I would definitely  support adding in a `flatten_hyperparams` argument in the wandb logger init, or just removing the flattening step all together.

**Comment by zephyap** [comment]
I'm still interested in this! But I understand if the team doesn't have time to work on it

**Comment by awaelchli** [comment]
Another user who discovered this: #17558
Anyone here wants to send a PR to update the parameter sanitization not to flatten the dicts?
