### ISSUE TITLE
Can one add callback after initializing trainer

### ISSUE THREAD

**Issue by junwang-wish** [Lightning-AI/lightning#15009]
In the 1.7.7 documentation, there isn't anywhere that mentions the possibility of adding custom callback after initializing trainer.

This is example when custom callbacks need to be dynamically generated depending on command line args:

```python
cli = LightningCLI(run=False)
cli.trainer.callbacks.append(CustomCalBack())
cli.trainer.predict(cli.model, cli.datamodule)
```

Is this the recommended way to dynamically inject callbacks?

**Comment by mauvilsa** [comment]
If CustomCalBack is not meant to be configurable doing it like this looks fine to me. To have a configurable always present callback do like https://pytorch-lightning.readthedocs.io/en/stable/cli/lightning_cli_expert.html#configure-forced-callbacks

**Comment by iamlockelightning** [comment]
Sorry to interrupt by bringing this up. I wonder how to append new callbacks after initializing trainer in `lightning==2.0.0`, since there seems nothing like `trainer.callbacks.append`?
