### ISSUE TITLE
Re-evaluate CUDA NVML and fork checks after torch 1.13 release

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#15010]
## 🚀 Reminder

This is a reminder that we added code in #14984 and #14631 that will potentially become obsolete depending on what 1.13 contains. 

- If https://github.com/pytorch/pytorch/pull/85951 lands and makes it into 1.13, we're good and can remove the code when we drop support for 1.12. There is already a note about it in the source code. 
- If https://github.com/pytorch/pytorch/pull/85951 gets pushed to 1.14, we might have to bump our internal checks. 

cc @justusschock @awaelchli @speediedan @carmocca

**Comment by carmocca** [comment]
This can be closed now, right @awaelchli? The checks are for 2.0 now
