### ISSUE TITLE
Keep a LightningWork "Hot" Until Run Method is Called

### ISSUE THREAD

**Issue by alecmerdler** [Lightning-AI/lightning#15015]
## 🚀 Feature

When running a Lightning App in the cloud, Work machines are instantiated lazily once their `run()` method is called for the first time. Spinning up a Work machine has a non-trivial time cost (>1 min). It would be nice if the Work machine could be spun up non-lazily, so that the first call to the `run()` method is fast.

### Motivation

Say I am building a speech recognition app. The architecture design that I've chosen uses a pool of dynamic `SpeechRecognizer` Works. As requests come into the app (via custom Lightning Commands), the Flow calls `self.speech_recognizer.run(request)` which kicks off the Work to run the model against the input. This means the first request will not complete until the Work machine has spun up.

### Pitch

The specific API doesn't matter much to me, but something like this would work:

```python
class App(LightningFlow):
    ...
    def run(self):
        if not self.speech_recognizer.hot():
            self.speech_recognizer.warm()

        self.speech_recognizer.run(request)
```

### Alternatives

Some would suggest using the `run()` method to create a long-running inference API endpoint, instead of running the model on each call. That defeats the purpose of some of the core value propositions of the Lightning Framework. The `run()` method is much simpler and the Framework already provides all the underlying networking between the Flow/Works. I shouldn't have to write another HTTP server on top of using Lightning when it already provides a much simpler Python interface.

### Additional context

N/A

**Comment by alecmerdler** [comment]
@tchaton Yes, my current workaround is to issue a dummy `run()` call. It makes the code look ugly, though. Let me know if you would like help implementing this feature or gathering more feedback!

**Comment by tchaton** [comment]
Hey @alecmerdler.

Yes, we are definitely planning to add this new feature, but it is quite technical which is why it wasn't terminated.
