### ISSUE TITLE
Split out `CloudRuntime.dispatch` into multiple methods

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#15012]
## Proposed refactor

Split out CloudRuntime.dispatch into multiple methods. 

### Motivation

This makes the code easier to read and test. Specifically, when testing individual setup stages of this runtime, we can mock out individual parts that are irrelevant for execution/testing.

### Additional context

This first came up here: #14929

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging PyTorch Lightning, Transformers, and Hydra.

**Comment by heytanay** [comment]
Hi @awaelchli, can I take up this issue?
