### ISSUE TITLE
Slurm Autorequeue Doesn't Work for Job Arrays

### ISSUE THREAD

**Issue by Queuecumber** [Lightning-AI/lightning#15022]
### Bug description

It looks like the slurm auto-requeue doesn't work right when a job is part of a job array. I started noticing weird bugs where my jobs would ask to requeue at "weird" times or they would "fail to requeue" but then mysteriously restart or they wouldn't requeue at all. The common thread is that I was using job arrays to manage a batch of related experiments automatically. 

It looks like when this happens you need to make sure you tell `scontrol` to requeue the specific array job which can be found with the environment variables `SLURM_ARRAY_JOB_ID` and `SLURM_ARRAY_TASK_ID` so you would do something like `scontrol requeue $SLURM_ARRAY_JOB_ID_$SLURM_ARRAY_TASK_ID`. What lightning was doing was requeueing the entire job which was trying to get both of the jobs in the array back on the queue and causing weird issues.

Fixing this seems to be really simple, just detect if those array variables are set and make a different call to `scontrol`. I will PR this ASAP because it's suddenly become mission critical for me (long story), what is your deadline for getting a feature into 1.8?

ref
https://github.com/facebookincubator/submitit/blob/main/submitit/slurm/slurm.py#L187
https://github.com/facebookincubator/submitit/blob/4cf1462d7216f9dcc530daeb703ce07c37cf9d72/submitit/slurm/slurm.py#L192
https://github.com/facebookincubator/submitit/blob/4cf1462d7216f9dcc530daeb703ce07c37cf9d72/submitit/core/job_environment.py#L82
https://github.com/Lightning-AI/lightning/blob/master/src/pytorch_lightning/trainer/connectors/signal_connector.py#L82

### How to reproduce the bug

```python
* Try to run an array job using lightning and with autorequeue enabled
* Wait a while, if you're unlucky weird stuff will happen
```

### Environment

```

#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): 
#- PyTorch Lightning Version (e.g., 1.5.0): 1.8.0.dev0 (built myself from master)
#- Lightning App Version (e.g., 0.5.2): 
#- PyTorch Version (e.g., 1.10): 1.12.1+cu116
#- Python version (e.g., 3.9): 3.8.10
#- OS (e.g., Linux): Linux
#- CUDA/cuDNN version: 
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source): 
#- Running environment of LightningApp (e.g. local, cloud): 

```

**Comment by Queuecumber** [comment]
Additional ref: https://slurm.schedmd.com/job_array.html#scontrol

**Comment by tchaton** [comment]
Hey @Queuecumber. Great catch !

Would you be interested to make a contribution with a fix ?

**Comment by Queuecumber** [comment]
> I will PR this ASAP because it's suddenly become mission critical for me (long story), what is your deadline for getting a feature into 1.8?

I will try to do this tomorrow depending on my availability, if it doesn't happen tomorrow it would have to be on Tuesday

**Comment by Queuecumber** [comment]
I'll try to get to this tomorrow but if it doesn't happen then it will have to be Tuesday

**Comment by Queuecumber** [comment]
I found time to do it tonight, will test on a real cluster some time this weekend, please take a look when you can
