### ISSUE TITLE
Support PyTorch 1.13

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#15050]
## 🚀 Feature

Start testing 1.13 nightly to be ready for the next PyTorch release.

### Motivation

Soon there will be a release of PyTorch 1.13. To be ready for it, I propose to start testing 1.13 nightly against our test suite.

### Pitch

- Open a PR updating the requirements, CI configuration etc. 
- Run the test suite.
- Start fixing issues and tests 

### Additional context

Related: #15010

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging PyTorch Lightning, Transformers, and Hydra.

**Comment by awaelchli** [comment]
@carmocca @akihironitta if you have any comments or suggestions, please feel free to edit the description directly :)

**Comment by carmocca** [comment]
1.13 will be released in ~3 weeks.
