### ISSUE TITLE
Option to select multiple apps in the UI and perform an action

### ISSUE THREAD

**Issue by rohitgr7** [Lightning-AI/lightning#15077]
## 🚀 Feature

It'd be really cool to allow users to select multiple apps using the checkbox and perform delete/stop actions on all of them at once.

![Screenshot 2022-10-11 at 4 27 06 PM](https://user-images.githubusercontent.com/30778939/195074719-55c83025-7a13-48f5-b467-1f67571e9e9b.png)

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging PyTorch Lightning, Transformers, and Hydra.

**Comment by awaelchli** [comment]
This was recently added! 🎉
