### ISSUE TITLE
Improve OmegaConf support in LightningCLI

### ISSUE THREAD

**Issue by catalys1** [Lightning-AI/lightning#15109]
## 🚀 Feature

There are a few things that I wish would work in the LightningCLI (in conjunction with OmegaConf):

1. Variable interpolation across all configs and commandline parameters. I know this isn't supported by `jsonargparse` (as discussed in #13607), but it would really be a useful feature.
2. In the same kind of vein, if you provide a value in a config file, and then try to overwrite it from the commandline, the config file value gets passed to OmegaConf resolvers instead of the commandline override. It would be nice if the override happened first.

### Motivation

LightningCLI + OmegaConf provides a pretty nice way of doing configurable experimentation. However, there are some things that seem like they should work but don't, or would be very nice but aren't supported; particularly with respect to OmegaConfs variable interpolation and custom resolvers (which I use pretty extensively). These are things that Hydra handles nicely, but I prefer to use LightningCLI as it is more closely coupled and a little easier to use.

### Pitch

I don't know the internals of the library, but it seems to me like an initial merge step, where all provided configs and commandline arguments are put into a single OmegaConf dictionary which is than used for everything downstream, would be one possible way to address this.

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging PyTorch Lightning, Transformers, and Hydra.

cc @borda @carmocca @mauvilsa

**Comment by carmocca** [comment]
I added 3rd party as the suggestions apply to the code in https://github.com/omni-us/jsonargparse, which is what powers the `LightningCLI`. cc @mauvilsa

**Comment by mauvilsa** [comment]
I have had this in mind even from when the OmegaConf support was first added. And I agree and do want to improve it. Just note that it is not simple to implement. Internally this is just argparse which can't be switched to using an OmegaConf dictionary. Also there is a conflicting need, see [jsonargparse #31 [comment]](https://github.com/omni-us/jsonargparse/issues/31#issuecomment-1271457039). For usability it makes sense that each command line argument is validated at each position independently of the rest of the arguments. If for example an argument is `--some.key=${some.other.key.non.str.type}` then the validation would fail. This just makes the implementation even harder.

@catalys1 I did not understand point (2). Can you please rephrase and maybe add an example to illustrate what you mean.

**Comment by Borda** [comment]
@catalys1 @carmocca can we consider this resolved? :)

**Comment by catalys1** [comment]
Sure :)

**Comment by mauvilsa** [comment]
I managed to implement an improved omegaconf's variable interpolation in jsonargparse. It supports interpolation across configs and command line arguments, so the example in https://github.com/Lightning-AI/pytorch-lightning/issues/15109#issuecomment-1279236333 would work. Please have a look and test https://github.com/omni-us/jsonargparse/pull/765
