### ISSUE TITLE
Invisible text on lightning.ai hiring page

### ISSUE THREAD

**Issue by Atharva-Phatak** [Lightning-AI/lightning#15160]
### Bug description

The email link under "Want to work at Lightning?" is in white and is not visible when one sees it. 

I am attaching a screenshot here. I tested with different browsers as well. Same issue. 

![image](https://user-images.githubusercontent.com/42376808/196320080-cefa4471-cea8-49ea-b021-f5fb6c19f2af.png)

One can see from the image that the email is white.

Seems like a minor CSS issue, or is it meant to be this way?

### Error messages and logs

```

# Error messages and logs here please

```

### Environment

```

#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):

```

**Comment by awaelchli** [comment]
@yurijmikhalevich or @boodland is this something you could help with? I believe @Atharva-Phatak accessed this page: https://www.pytorchlightning.ai/support

**Comment by Atharva-Phatak** [comment]
@awaelchli Yes that was the page that I accessed looks like the text is rendered as white :).
