### ISSUE TITLE
PTL to ONNX export() got an unexpected keyword argument 'example_outputs'

### ISSUE THREAD

**Issue by davodogster** [Lightning-AI/lightning#15181]
### Bug description

Im using torch version 1.12 and received this error when trying to convert this SMP Timm DeepLab model:
![image](https://user-images.githubusercontent.com/46079516/196570945-3a793c59-e3ba-420d-bd03-57510f3a4cc3.png)

![image](https://user-images.githubusercontent.com/46079516/196570612-9c2c6d1a-b540-4794-a802-56db1691d0a4.png)

![image](https://user-images.githubusercontent.com/46079516/196571426-13f5d581-7d3f-4920-8f50-42dc9bf91389.png)

How to reproduce:

![image](https://user-images.githubusercontent.com/46079516/196570856-1841ee2b-e69f-4c85-b3a3-5e9b44a3015d.png)

Do you know how to fix this? Thanks, Sam

### Error messages and logs

```

# Error messages and logs here please

```

### Environment

![image](https://user-images.githubusercontent.com/46079516/196571383-0c9edb47-742f-4f3c-9ee0-357bd16bb324.png)

**Comment by rohitgr7** [comment]
this issue got fixed in v1.5.7: https://github.com/Lightning-AI/lightning/pull/11116

mind try that, or we always recommend using the latest release :)

**Comment by davodogster** [comment]
Thanks that seemed to work
![image](https://user-images.githubusercontent.com/46079516/197907815-23c0e395-ae2d-4ca9-8796-fb9da611c94f.png)

![image](https://user-images.githubusercontent.com/46079516/197907872-76be3f2c-cc1e-4136-9050-f87234de913c.png)

**Comment by davodogster** [comment]
@rohitgr7 Hi Rohit, the Hitman, Gupta and @awaelchli Do you know how I can successfully load and use the model? It was trained in segmentation_models.pytorch with lightning (v 1.5.4)
This code fails:
![image](https://user-images.githubusercontent.com/46079516/198905189-b35e5f90-7883-4d2a-ab65-59c32e65e9c5.png)

Thanks, Sam

**Comment by rohitgr7** [comment]
you might have to provide a sample input for these models.
Check this: https://github.com/qubvel/segmentation_models.pytorch/issues/272#issuecomment-718460540

**Comment by davodogster** [comment]
Hi @rohitgr7 thanks for the reply! I figured it out recently and was able to load the model and use it for inference like this:

![image](https://user-images.githubusercontent.com/46079516/199104146-d5873cdd-2928-4f17-8125-8722104a4496.png)

I was surprised that it worked but the predictions seem legitimate

**Comment by rohitgr7** [comment]
cool! feel free to close this issue if you are good on your side :)
