### ISSUE TITLE
Provide CLI entry points for Lightning Lite launcher

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#15190]
### Motivation

This is a follow up work after #14992 lands. Right now, the cli can only be launched this way:

```
python -m lightning_lite.cli [file.py] ...
```

Which is not the intended way, as it is cumbersome and not easy to remember, hence more work is needed. 

### Pitch

We need two CLIs:

1. Integration into the main lightning cli (not to be confused with LightningCLI). 

    ```
    lightning run lite [file.py] ...
    ```
    (just for illustration, naming is up for discussion)
    This implementation should have checks that the lightning_lite package is installed, and then call into the cli module directly. What needs to be discussed is how and where the argument parsing is handled. 

2. A standalone CLI. Why? Because a user will have the option to _only_ install lightning-lite, and hence will not get the full lightning cli from the app package. The usage should however be similar or even not identical. 

### Additional context

This is a required follow up to #14992

**Comment by Atharva-Phatak** [comment]
Is this open. I would like to take this up :)

**Comment by awaelchli** [comment]
Closing this as not needed. Should we decide to have a standalone package, we can reopen this.
