### ISSUE TITLE
Why is lightning pulling in a pypi dep that does not have source available?

### ISSUE THREAD

**Issue by colemickens** [Lightning-AI/lightning#15236]
### Bug description

I'm trying to update `lightning` in nixpkgs, and now it's failing to build because it need `lightning-cloud`.

1. Why?
2. Where is the source for it?

### Error messages and logs

```

# Error messages and logs here please

```

### Environment

```

#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):

```

**Comment by colemickens** [comment]
Not only that, but however it's packaged manages to be incompatible with all of our default python package processors too.

**Comment by colemickens** [comment]
```
       >   File "/build/lightning-cloud-0.5.0/nix_run_setup", line 8, in <module>
       >     exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
       >   File "setup.py", line 28, in <module>
       >     with open('requirements.txt') as f:
       > FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

so, the pypi package comes with a setup.py that doesn't work... am I getting this right?

**Comment by awaelchli** [comment]
Hi @colemickens 
Could you include more details in the section "How to reproduce the bug" and the environment details please?

Not sure why this is happening. @hhsecond Do you have some idea what could be happening here?

**Comment by colemickens** [comment]
It's okay, I solved it by pulling source from pypi, my mistake. I'll close
this when I'm back at my machine
