### ISSUE TITLE
WandbLogger shouldn't start wandb run in `__init__`

### ISSUE THREAD

**Issue by tshu-w** [Lightning-AI/lightning#15233]
### Bug description

According to the [document](https://pytorch-lightning.readthedocs.io/en/1.7.0/debug/debugging_basic.html#run-all-your-model-code-once-quickly), when using `fast_dev_run`, loggers should be disabled. However, the WandbLogger starts `run` in `__init__` and then is disabled, which causes an empty run in the dashboard.

https://github.com/Lightning-AI/lightning/blob/90e1a0ecf03ee63d59fdaa383a5a33773322a5a6/src/pytorch_lightning/loggers/wandb.py#L349-L351

### How to reproduce the bug

```python
from pytorch_lightning.loggers import WandbLogger

wandb_logger = WandbLogger(project="MNIST")
```

### Environment

* Lightning:
	- lightning-bolts:   0.5.0
	- pytorch-lightning: 1.7.7
	- pytorch-metric-learning: 1.6.2
	- torch:             1.12.1+cu113
	- torchmetrics:      0.10.0
	- torchtext:         0.13.1
	- torchvision:       0.13.1+cu113
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.9.13
	- version:           #185-Ubuntu SMP Tue Mar 29 17:40:04 UTC 2022

### More info

cc @manangoel99

**Comment by awaelchli** [comment]
I don't think we can solved this properly, at least I don't have any ideas atm. The logic 

```py
 if _WANDB_GREATER_EQUAL_0_12_10: 
     wandb.require("service") 
     _ = self.experiment 
```

is needed to work well with multiprocessing. We've gone back and forth on this already several times. I believe the value of having wandb work well with multiprocessing is higher than having an empty fast_dev_run experiment right now.

**Comment by manangoel99** [comment]
I agree @awaelchli because putting this logic elsewhere may cause multiple runs to be spawned in multiprocessing which would be worse in my opinion

**Comment by tshu-w** [comment]
After reading #https://github.com/Lightning-AI/lightning/issues/11602, I fully understand the problem and it seems we have no better way unless adding a hook.
