### ISSUE TITLE
Make auto_scale_batch_size error message more informative

### ISSUE THREAD

**Issue by PaulLerner** [Lightning-AI/lightning#15276]
### The issue

Hi, 
From #3233, I understand that the current error message for `auto_scale_batch_size` misconfiguration message dates back from a time where `LightningDataModule` did not exist. The message is still the same today: ["Field {self._batch_arg_name} not found in both `model` and `model.hparams`"](https://github.com/Lightning-AI/lightning/blob/master/src/pytorch_lightning/callbacks/batch_size_finder.py#L153). Typically "Field batch_size..."

This message is misleading. I thought that I needed to add a `batch_size` attribute to my model because the tuning would be independent of data module or something.

### How to fix
I’m new to lightning so I’m not sure how to phrase this (that’s why I’m opening an issue instead of a PR). How about: f"Field {self._batch_arg_name} not found in `{model.__class__.__name__}`, `datamodule.__class__.__name__`, nor their `hparams` attributes." ?

**Comment by PaulLerner** [comment]
Update: looking at https://github.com/Lightning-AI/lightning/blob/56ca4aafee73403c82811b37d2b9f83e48e5d12e/src/pytorch_lightning/utilities/parsing.py#L306 it seems tricky to access the datamodule class name. Perhaps a more generic message like f"Field {self._batch_arg_name} not found in `model`, `datamodule`, nor their `hparams` attributes." is sufficient.

**Comment by awaelchli** [comment]
@PaulLerner Your proposal seems fine to me. Let's go for the simple solution first, which should already be an improvement and we can think of ways to make it even better. 
Would you be interested to work on it?

**Comment by PaulLerner** [comment]
Yes I can open a PR! 
While I’m at it, maybe I should also update the docstring of Trainer. It states, for `auto_scale_batch_size`: "The result will be stored in self.batch_size in the LightningModule" but it is actually done with `lightning_setattr`. So the correct doc should state: "The result will be stored in self.batch_size in the LightningModule or LightningDataModule depending on your setup."  ?
