### ISSUE TITLE
Drop PyTorch 1.9 support

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lightning#15346]
## Proposed refactor

See title

### Motivation

PyTorch 1.13 is released today Oct 27 (at least that's the plan).
We already support it and test it.

### Pitch

To follow our previous support window of 4 versions, drop 1.9 with PL 1.8

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging PyTorch Lightning, Transformers, and Hydra.

cc @carmocca @akihironitta @borda @justusschock @awaelchli @rohitgr7

**Comment by Borda** [comment]
let's proceed with this one after #15128
