### ISSUE TITLE
gradio WebSocket disconnects after 255 seconds

### ISSUE THREAD

**Issue by KogayIrina** [Lightning-AI/lightning#15363]
### Bug description

I ran a lightning app in the cloud on Sunday, and it worked perfectly with my model taking about 700 seconds to generate an image, but yesterday I noticed that gradio WebSocket disconnected after 255 seconds. This is always reproducible

![image](https://user-images.githubusercontent.com/63745301/198286352-3f380bb8-781b-483f-b6aa-9a39d96931ad.png)

### How to reproduce the bug

```python
1. Run this app in the lightning cloud: https://github.com/Lightning-AI-Dev/Awesome-Lightning/blob/main/src/discoart-app/app.py
2. Type your prompt
3. Choose the model (for example, portrait_generator_v1.5)
4. Wait for 255 seconds
5. See an error in the Image `gradio component`
```

### Error messages and logs

```

Connection errored out.

```

### Environment

```

#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud): cloud

```

**Comment by awaelchli** [comment]
We could try to use .queue() when launching the Gradio interface. The [docs](https://gradio.app/docs/#launch-header) for .launch() say (the one we currently use):

> enable_queue:  (use .queue() method instead.) if True, inference requests will be served through a queue instead of with parallel threads. Required for longer inference times (> 1min) to prevent timeout.

**Comment by KogayIrina** [comment]
Hi, @awaelchli !
Thanks a lot for your suggestion. It finally works, and I am very happy ^_^
Thank you for your time; I appreciate it!
