### ISSUE TITLE
Windows CI job hangs for app tests

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#15386]
## Bug

The windows job `app-pytest (windows-2022, lightning, 3.9, latest)` passes but hangs at exit. 
Example record: https://github.com/Lightning-AI/lightning/actions/runs/3339574899/jobs/5528694636

- not flaky
- on all current PRs
- all tests pass
- only this job hangs

Possible causes:
- A server that keeps running and doesn't let pytest terminate
- A non-daemon thread that keeps running and doesn't let Python exit the process

cc @carmocca @akihironitta @borda

**Comment by carmocca** [comment]
cc @tchaton to provide more details as he spent a long time debugging already

**Comment by awaelchli** [comment]
I was looking at past PRs that modified code in proximity of "threads". Could investigate whether this PR had any influence (storage orchestrator): https://github.com/Lightning-AI/lightning/pull/15235

**Comment by awaelchli** [comment]
I just say this PR: #15385
Now my investigation is flawed as I believed my fix worked. In reality, the original job configuration that hanged didn't even run anymore! 

Bad timing :(
