### ISSUE TITLE
NeptuneDeprecationWarning for neptune.init in NeptuneLogger

### ISSUE THREAD

**Issue by wouterzwerink** [Lightning-AI/lightning#15394]
### Bug description

The PyTorch lightning class `pytorch_lightning.loggers.NeptuneLogger` is a wrapper for the neptune-client logger. In this class, `neptune.init` is used. This function is deprecated and support for it will end in neptune-client==1.0.0. `neptune.init_run` should be used instead. This would remove the deprecation warning allows the NeptuneLogger to keep working with future neptune-client versions.

### How to reproduce the bug

```python
Initialise the `pytorch_lightning.loggers.NeptuneLogger` with a recent version of `neptune-client` installed. A NeptuneDeprecationWarning will be shown.
```

### Error messages and logs

```
NeptuneDeprecationWarning: `init` is deprecated, use `init_run` instead. We'll end support of it in `neptune-client==1.0.0`.
```

### Environment

```

#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):

```

cc @Blaizzy

**Comment by awaelchli** [comment]
@wouterzwerink It looks like we missed this. Thanks for bringing it up. Would you be interested in contributing this change, by opening PR with the changed API call? 😃
