### ISSUE TITLE
Mock imports while loading LightningApp

### ISSUE THREAD

**Issue by manskx** [Lightning-AI/lightning#15428]
## 🚀 Feature

As part of this: https://github.com/Lightning-AI/lightning/pull/15019

If some imports are not found, they can be mocked and load the app() to set the CloudCompute before launching the app

Inspiration: https://github.com/Lightning-AI/lightning-app/issues/372

Note: We should also change the temporary fix we did on the backend and allow users to only update the frontend servers through releases

**Comment by awaelchli** [comment]
I believe this was completed by @ethanwharris
