### ISSUE TITLE
`MyNet.load_from_checkpoint` should return an instance of type `MyNet`

### ISSUE THREAD

**Issue by dyollb** [Lightning-AI/lightning#15467]
## Proposed refactor

`MyNet.load_from_checkpoint` currently returns an instance of type `LightningModule`.
It would be nice if it would return an instance of type `MyNet`.

### Motivation

This seems to make sense from an API point of view, and helps IDE's and static type checkers with code accessing properties/methods of type `MyNet`. 

### Pitch
```
class MyNet(pl.LightningModule):
  
    @property
    def num_classes(self):
        return self._model.out_channels

mynet = MyNet.load_from_checkpoint(file_path)
if mynet.num_classes > 2:
  print("hello world")
```

mypy should not complain about code like the (pseudo-code) above. 

### Additional context

cc @borda @justusschock @awaelchli @rohitgr7

**Comment by awaelchli** [comment]
@dyollb This can be achieved with typing.TypeVar. Here is a quick sketch:

```py
LM = TypeVar["LM"]

    @classmethod
    def load_from_checkpoint(
        cls: LM,
        ...
    ) -> LM:

```

Would you be interested to investigate and contribute this?

**Comment by dyollb** [comment]
I had a quick try but didn't figure out how to do it, because load_from_checkpoint is defined in the mixin class ModelIO.

**Comment by awaelchli** [comment]
Let's see if someone else from the community wants to give this a try. If nobody takes it, I will take a look too <3

**Comment by carmocca** [comment]
This can be done by just using the `Self` type from https://peps.python.org/pep-0673/
