### ISSUE TITLE
Support partial installation of the lightning package

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lightning#15505]
## 🚀 Feature

`PACKAGE_NAME=lightning pip install .` (also `pip install .`) installs ALL dependencies. This can be very heavy in terms of dependencies.

`PACKAGE_NAME=pytorch pip install .` installs `pytorch_lightning`. But then you cannot use the new import style of `lightning.pytorch`

I propose that the latter does install both `pytorch_lightning` and `lightning`. But only with PyTorch's dependencies.

Lightning's `__init__.py` will need `hasattr` checks to avoid the root imports breaking

### Motivation

New style imports without the dependency hell

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging PyTorch Lightning, Transformers, and Hydra.

cc @carmocca @akihironitta @borda

**Comment by Borda** [comment]
I think we can allow installation of full lighting code, but just with PL dependencies, as if we allow installation part of PL and/or App side or `lightning`, it is not complemented in your sire-packages but replacement (AFAIK), so you may end up with half broken package with almost no signed why/what happened unless you know these principles...

**Comment by carmocca** [comment]
Why would there be a conflict? Each would have its own imports

**Comment by awaelchli** [comment]
I believe this was implemented in #18386. Close?
