### ISSUE TITLE
Doc site access for Lightning AI site delivers a 404 

### ISSUE THREAD

**Issue by Felonious-Spellfire** [Lightning-AI/lightning#15519]
### Bug description

Accessing the Lightning AI doc site from the main menu delivers a 404. 

![lightning-ai_doc_404](https://user-images.githubusercontent.com/16614915/199860375-45e0c706-689a-464c-b634-db29a0db2a01.png)

If you refresh your browser it takes you to the site, but the URL changes for the site.

![lightning-ai_doc_404_after_refresh](https://user-images.githubusercontent.com/16614915/199860597-e58a422e-caf8-45e2-90d8-3e03f8695523.png)

### Error messages and logs

```

# Error messages and logs here please

```

### Environment

```

#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):

```

**Comment by rohitgr7** [comment]
this seems to be fixed now :)
