### ISSUE TITLE
Forks cannot build docs

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lightning#15528]
### Bug report

#15486 added the need for secrets in our docs workflow.
All PRs from forks that need to build the docs are blocked.
This is because GitHub actions do not share secrets with forks.

### Motivation

Contributors are blocked

### Pitch

Choose one of:

a) Avoid the need for secrets by making the template public (no longer need _target)
b) Port docs build setup to Azure
c) yolo it and remove the docs workflows from the required checks. open to breaking master

### Additional context

See https://github.com/Lightning-AI/lightning/pull/15510#issuecomment-1302869870
______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging PyTorch Lightning, Transformers, and Hydra.

cc @borda @rohitgr7 @tchaton

**Comment by Borda** [comment]
This is now as this effectively ban all contributions to app's codebase :otter:
