### ISSUE TITLE
Use `monkeypatch.chdir` instead of `os.chdir` in tests

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#15576]
### Motivation

Many of the tests under tests/tests_app use the following pattern:

```py
cwd = os.getcwd()
os.chdir(new_cwd)

# some test code

os.chdir(cwd)
```

This is not ideal. If any one of these tests fails, the current working directory remains to what it was set in the beginning of the code. This can cause subsequent tests to fail for unrelated reasons.

### Pitch

Use 

```py
monkeypatch.chdir(new_cwd)
```

instead.

cc @tchaton 

cc @borda @justusschock @awaelchli

**Comment by heytanay** [comment]
Hi, I would like to fix this issue, can I take it up?

**Comment by Borda** [comment]
> Hi, I would like to fix this issue, can I take it up?

Sure, looking forward to it 🚀
