### ISSUE TITLE
Using the ModelCheckpoint callback with WandbLogger raises an error

### ISSUE THREAD

**Issue by manangoel99** [Lightning-AI/lightning#15624]
### Bug description

Using the ModelCheckpoint callback with the WandbLogger raises the following exception
```
  File "/opt/conda/envs/lightning/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 579, in fit
    call._call_and_handle_interrupt(
  File "/opt/conda/envs/lightning/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/conda/envs/lightning/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 621, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/conda/envs/lightning/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1058, in _run
    results = self._run_stage()
  File "/opt/conda/envs/lightning/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1137, in _run_stage
    self._run_train()
  File "/opt/conda/envs/lightning/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1160, in _run_train
    self.fit_loop.run()
  File "/opt/conda/envs/lightning/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.on_advance_end()
  File "/opt/conda/envs/lightning/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 295, in on_advance_end
    self.trainer._call_callback_hooks("on_train_epoch_end")
  File "/opt/conda/envs/lightning/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1340, in _call_callback_hooks
    fn(self, self.lightning_module, *args, **kwargs)
  File "/opt/conda/envs/lightning/lib/python3.9/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 312, in on_train_epoch_end
    self._save_topk_checkpoint(trainer, monitor_candidates)
  File "/opt/conda/envs/lightning/lib/python3.9/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 369, in _save_topk_checkpoint
    self._save_monitor_checkpoint(trainer, monitor_candidates)
  File "/opt/conda/envs/lightning/lib/python3.9/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 652, in _save_monitor_checkpoint
    self._update_best_and_save(current, trainer, monitor_candidates)
  File "/opt/conda/envs/lightning/lib/python3.9/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 703, in _update_best_and_save
    self._save_checkpoint(trainer, filepath)
  File "/opt/conda/envs/lightning/lib/python3.9/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 381, in _save_checkpoint
    logger.after_save_checkpoint(proxy(self))
  File "/opt/conda/envs/lightning/lib/python3.9/site-packages/pytorch_lightning/loggers/wandb.py", line 515, in after_save_checkpoint
    self._scan_and_log_checkpoints(checkpoint_callback)
  File "/opt/conda/envs/lightning/lib/python3.9/site-packages/pytorch_lightning/loggers/wandb.py", line 595, in _scan_and_log_checkpoints
    artifact = wandb.Artifact(name=f"model-{self.experiment.id}", type="model", metadata=metadata)
  File "/opt/conda/envs/lightning/lib/python3.9/site-packages/wandb/sdk/wandb_artifacts.py", line 164, in __init__
    metadata = _normalize_metadata(metadata)
  File "/opt/conda/envs/lightning/lib/python3.9/site-packages/wandb/sdk/wandb_artifacts.py", line 98, in _normalize_metadata
    Dict[str, Any], json.loads(json.dumps(util.make_safe_for_json(metadata)))
  File "/opt/conda/envs/lightning/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/opt/conda/envs/lightning/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/conda/envs/lightning/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/conda/envs/lightning/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Tensor is not JSON serializable
```

This is most likely because the monitoring variable sent to the WandbLogger is now of type `torch.Tensor` instead of float.

### How to reproduce the bug

```python
from torchvision.datasets import MNIST
from torchvision import transforms
from torch.utils.data import DataLoader, random_split
import wandb
transform = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize((0.1307,), (0.3081,))])

dataset = MNIST(root="./MNIST", download=True, transform=transform)
training_set, validation_set = random_split(dataset, [55000, 5000])

training_loader = DataLoader(training_set, batch_size=64, shuffle=True)
validation_loader = DataLoader(validation_set, batch_size=64)

import torch
from torch.nn import Linear, CrossEntropyLoss, functional as F
from torch.optim import Adam
from torchmetrics.functional import accuracy
from pytorch_lightning import LightningModule

class MNIST_LitModule(LightningModule):

    def __init__(self, n_classes=10, n_layer_1=128, n_layer_2=256, lr=1e-3):
        '''method used to define our model parameters'''
        super().__init__()

        # mnist images are (1, 28, 28) (channels, width, height)
        self.layer_1 = Linear(28 * 28, n_layer_1)
        self.layer_2 = Linear(n_layer_1, n_layer_2)
        self.layer_3 = Linear(n_layer_2, n_classes)

        # loss
        self.loss = CrossEntropyLoss()

        # optimizer parameters
        self.lr = lr

        # save hyper-parameters to self.hparams (auto-logged by W&B)
        self.save_hyperparameters()

    def forward(self, x):
        '''method used for inference input -> output'''

        batch_size, channels, width, height = x.size()

        # (b, 1, 28, 28) -> (b, 1*28*28)
        x = x.view(batch_size, -1)

        # let's do 3 x (linear + relu)
        x = self.layer_1(x)
        x = F.relu(x)
        x = self.layer_2(x)
        x = F.relu(x)
        x = self.layer_3(x)

        return x

    def training_step(self, batch, batch_idx):
        '''needs to return a loss from a single batch'''
        _, loss, acc = self._get_preds_loss_accuracy(batch)

        # Log loss and metric
        self.log('train_loss', loss)
        self.log('train_accuracy', acc)

        return loss

    def validation_step(self, batch, batch_idx):
        '''used for logging metrics'''
        preds, loss, acc = self._get_preds_loss_accuracy(batch)

        # Log loss and metric
        self.log('val_loss', loss)
        self.log('val_accuracy', acc)

        # Let's return preds to use it in a custom callback
        return preds

    def test_step(self, batch, batch_idx):
        '''used for logging metrics'''
        _, loss, acc = self._get_preds_loss_accuracy(batch)

        # Log loss and metric
        self.log('test_loss', loss)
        self.log('test_accuracy', acc)
    
    def configure_optimizers(self):
        '''defines model optimizer'''
        return Adam(self.parameters(), lr=self.lr)
    
    def _get_preds_loss_accuracy(self, batch):
        '''convenience function since train/valid/test steps are similar'''
        x, y = batch
        logits = self(x)
        preds = torch.argmax(logits, dim=1)
        loss = self.loss(logits, y)
        acc = accuracy(preds, y)
        return preds, loss, acc

model = MNIST_LitModule(n_layer_1=128, n_layer_2=128)

from pytorch_lightning.callbacks import ModelCheckpoint

checkpoint_callback = ModelCheckpoint(monitor='val_accuracy', mode='max')

from pytorch_lightning.loggers import WandbLogger
from pytorch_lightning import Trainer

wandb_logger = WandbLogger(project='MNIST', # group runs in "MNIST" project
                           log_model='all') # log all new checkpoints during training

from pytorch_lightning.callbacks import Callback
 
class LogPredictionsCallback(Callback):
    
    def on_validation_batch_end(
        self, trainer, pl_module, outputs, batch, batch_idx, dataloader_idx):
        """Called when the validation batch ends."""
 
        # `outputs` comes from `LightningModule.validation_step`
        # which corresponds to our model predictions in this case
        
        # Let's log 20 sample image predictions from first batch
        if batch_idx == 0:
            n = 20
            x, y = batch
            images = [img for img in x[:n]]
            captions = [f'Ground Truth: {y_i} - Prediction: {y_pred}' for y_i, y_pred in zip(y[:n], outputs[:n])]
            
            # Option 1: log images with `WandbLogger.log_image`
            wandb_logger.log_image(key='sample_images', images=images, caption=captions)

            # Option 2: log predictions as a Table
            columns = ['image', 'ground truth', 'prediction']
            data = [[wandb.Image(x_i), y_i, y_pred] for x_i, y_i, y_pred in list(zip(x[:n], y[:n], outputs[:n]))]
            wandb_logger.log_table(key='sample_table', columns=columns, data=data)

log_predictions_callback = LogPredictionsCallback()

trainer = Trainer(
    logger=wandb_logger,                    # W&B integration
    callbacks=[log_predictions_callback,    # logging of sample predictions
               checkpoint_callback],        # our model checkpoint callback
    max_epochs=5, accelerator="gpu", devices=1)                           # number of epochs
trainer.fit(model, training_loader, validation_loader)
wandb.finish()
```

### Error messages and logs

```

# Error messages and logs here please

```

### Environment

* CUDA:
        - GPU:
                - Tesla T4
                - Tesla T4
        - available:         True
        - version:           11.7
* Lightning:
        - lightning:         1.9.0.dev0
        - lightning-api-access: 0.0.1
        - lightning-cloud:   0.5.11
        - lightning-lite:    1.8.0.post1
        - lightning-utilities: 0.3.0
        - pytorch-lightning: 1.8.0.post1
        - torch:             1.13.0
        - torchmetrics:      0.10.2
        - torchvision:       0.14.0
* Packages:
        - absl-py:           1.3.0
        - aiobotocore:       2.4.0
        - aiohttp:           3.8.3
        - aioitertools:      0.11.0
        - aiosignal:         1.3.1
        - anyio:             3.6.2
        - arrow:             1.2.3
        - async-timeout:     4.0.2
        - attrs:             22.1.0
        - beautifulsoup4:    4.11.1
        - blessed:           1.19.1
        - botocore:          1.27.59
        - cachetools:        5.2.0
        - certifi:           2022.9.24
        - charset-normalizer: 2.1.1
        - click:             8.1.3
        - commonmark:        0.9.1
        - croniter:          1.3.7
        - deepdiff:          6.2.1
        - dnspython:         2.2.1
        - docker-pycreds:    0.4.0
        - email-validator:   1.3.0
        - fastapi:           0.86.0
        - fire:              0.4.0
        - frozenlist:        1.3.3
        - fsspec:            2022.11.0
        - gitdb:             4.0.9
        - gitpython:         3.1.29
        - google-auth:       2.14.1
        - google-auth-oauthlib: 0.4.6
        - grpcio:            1.50.0
        - h11:               0.14.0
        - httptools:         0.5.0
        - idna:              3.4
        - importlib-metadata: 5.0.0
        - inquirer:          2.10.0
        - itsdangerous:      2.1.2
        - jinja2:            3.1.2
        - jmespath:          1.0.1
        - lightning:         1.9.0.dev0
        - lightning-api-access: 0.0.1
        - lightning-cloud:   0.5.11
        - lightning-lite:    1.8.0.post1
        - lightning-utilities: 0.3.0
        - markdown:          3.4.1
        - markupsafe:        2.1.1
        - multidict:         6.0.2
        - numpy:             1.23.4
        - nvidia-cublas-cu11: 11.10.3.66
        - nvidia-cuda-nvrtc-cu11: 11.7.99
        - nvidia-cuda-runtime-cu11: 11.7.99
        - nvidia-cudnn-cu11: 8.5.0.96
        - oauthlib:          3.2.2
        - ordered-set:       4.1.0
        - orjson:            3.8.1
        - packaging:         21.3
        - pathtools:         0.1.2
        - pillow:            9.3.0
        - pip:               22.3.1
        - promise:           2.3
        - protobuf:          3.20.3
        - psutil:            5.9.4
        - pyasn1:            0.4.8
        - pyasn1-modules:    0.2.8
        - pydantic:          1.10.2
        - pygments:          2.13.0
        - pyjwt:             2.6.0
        - pyparsing:         3.0.9
        - python-dateutil:   2.8.2
        - python-dotenv:     0.21.0
        - python-editor:     1.0.4
        - python-multipart:  0.0.5
        - pytorch-lightning: 1.8.0.post1
        - pyyaml:            6.0
        - readchar:          4.0.3
        - requests:          2.28.1
        - requests-oauthlib: 1.3.1
        - rich:              12.6.0
        - rsa:               4.9
        - s3fs:              2022.11.0
        - sentry-sdk:        1.10.1
        - setproctitle:      1.3.2
        - setuptools:        65.5.1
        - shortuuid:         1.0.10
        - six:               1.16.0
        - smmap:             5.0.0
        - sniffio:           1.3.0
        - soupsieve:         2.3.2.post1
        - starlette:         0.20.4
        - starsessions:      1.3.0
        - tensorboard:       2.11.0
        - tensorboard-data-server: 0.6.1
        - tensorboard-plugin-wit: 1.8.1
        - termcolor:         2.1.0
        - torch:             1.13.0
        - torchmetrics:      0.10.2
        - torchvision:       0.14.0
        - tqdm:              4.64.1
        - traitlets:         5.5.0
        - typing-extensions: 4.4.0
        - ujson:             5.5.0
        - urllib3:           1.26.12
        - uvicorn:           0.18.3
        - uvloop:            0.17.0
        - wandb:             0.13.5
        - watchfiles:        0.18.1
        - wcwidth:           0.2.5
        - websocket-client:  1.4.2
        - websockets:        10.4
        - werkzeug:          2.2.2
        - wheel:             0.38.4
        - wrapt:             1.14.1
        - yarl:              1.8.1
        - zipp:              3.10.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         
        - python:            3.9.13
        - version:           #1 SMP Debian 4.19.260-1 (2022-09-29)

cc @awaelchli @morganmcg1 @borisdayma @scottire @manangoel99

**Comment by awaelchli** [comment]
This is the same issue as #15543, correct?
