### ISSUE TITLE
No module named 'pytorch_lightning.metrics'

### ISSUE THREAD

**Issue by Manjuphoenix** [Lightning-AI/lightning#15661]
### Bug description

Im using pytorch version 1.8.1 on Google Colab pro to train CNN model and while trying to calculate the accuracy I wanted to use the pytorch_lightning's metrics module. But while trying to import the **accuracy** function I'm getting the output as below:

ModuleNotFoundError                       Traceback (most recent call last)

[<ipython-input-32-9402f1fd719c>](https://localhost:8080/#) in <module>
      3 from PIL import Image
      4 from pathlib import Path
----> 5 from pytorch_lightning.metrics.functional import accuracy
      6 
      7 

ModuleNotFoundError: No module named 'pytorch_lightning.metrics'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

### How to reproduce the bug

```python
from pytorch_lightning.metrics.functional import accuracy
```

### Error messages and logs

---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

[<ipython-input-32-9402f1fd719c>](https://localhost:8080/#) in <module>
      3 from PIL import Image
      4 from pathlib import Path
----> 5 from pytorch_lightning.metrics.functional import accuracy
      6 
      7 

ModuleNotFoundError: No module named 'pytorch_lightning.metrics'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

### Environment

```

#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):: LightningModule
#- PyTorch Lightning Version (e.g., 1.5.0): 1.8.1
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10): 1.12.1+cu113
#- Python version (e.g., 3.9): 3.7.15
#- OS (e.g., Linux): Linux
#- CUDA/cuDNN version: 11.2
#- GPU models and configuration: GPU name = A100-SXM4-40GB
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud): Google Colab pro

```

**Comment by awaelchli** [comment]
@Manjuphoenix The metrics module got removed from pytorch_lightning a very long time ago. You must be looking at an outdated tutorial or documentation. Could you tell us where you saw this?

Please install the [torchmetrics](https://torchmetrics.readthedocs.io/en/stable/) package and import your metrics from there. Hope this helps

**Comment by Manjuphoenix** [comment]
I was going through a youtube tutorial of the Lightning AI official channel link: [https://www.youtube.com/watch?v=DbESHcCoWbM]
Thanks for the update, will surely follow up with torchmetrics @awaelchli
