### ISSUE TITLE
LightningCLI does not recognize arguments when importing annotations from __future__

### ISSUE THREAD

**Issue by rusmux** [Lightning-AI/lightning#15741]
### Bug description

I'm using Python 3.8 and to make it compatible with annotations from Python 3.9, I do an import:

```Python
from __future__ import annotations
```

But with this import, the LightningCLI gives me an error that my arguments are not recognized. Neither from the CLI nor from the yaml configuration files. See the minimal example below.

 I've spent several days trying to figure out what the problem is.

### How to reproduce the bug

```python
"""Run ``--help`` on this script with and without commenting the import.
When importing, there is no ``path`` argument in the model section.
"""

# from __future__ import annotations

from pytorch_lightning.cli import LightningCLI
from pytorch_lightning import LightningModule


class Model(LightningModule):

    def __init__(self, path: str) -> None:
        super().__init__()


if __name__ == "__main__":
    LightningCLI(Model)
```

### Error messages and logs

Without import:

```
<class '__main__.Model'>:
  --model CONFIG        Path to a configuration file.
  --model.path PATH     (required, type: str)
```

With import:

```
<class '__main__.Model'>:
  --model CONFIG        Path to a configuration file.
```

### Environment

```
Lightning Component: LightningCLI
PyTorch Lightning Version: 1.8.2
PyTorch Version: 1.12.1
Python version: 3.8
OS: MacOS
How you installed Lightning: pip
```

cc @carmocca @mauvilsa

**Comment by carmocca** [comment]
Thanks for reporting! This is a known issue and is tracked in https://github.com/omni-us/jsonargparse/issues/120 already. Closing this as a duplicate

**Comment by mauvilsa** [comment]
@rusmux support for future annotations in jsonargparse has been implemented. Can you please try it out? Just install as:

```
pip3 install "jsonargparse[signatures] @ https://github.com/omni-us/jsonargparse/zipball/future-annotations"
```

**Comment by rusmux** [comment]
@mauvilsa It's working on my machine. Thank you!
