### ISSUE TITLE
Incorrect type hints for LightningModule.save_hyperparameters and hparams

### ISSUE THREAD

**Issue by adamjstewart** [Lightning-AI/lightning#15781]
### Bug description

Both `LightningModule.save_hyperparameters` and `LightningModule.hparams` seem to have type `Union[torch._tensor.Tensor, torch.nn.modules.module.Module]`. I would expect the former to be `Callable` and the latter to be an `AttributeDict`.

### How to reproduce the bug

```python
import pytorch_lightning as pl


class LitMNIST(pl.LightningModule):
    def __init__(self, layer_1_dim: int = 128, learning_rate: float = 1e-2):
        super().__init__()
        reveal_type(self.save_hyperparameters)
        self.save_hyperparameters()
        reveal_type(self.hparams)
        self.hparams.layer_1_dim
        self.hparams["learning_rate"]
```

### Error messages and logs

The above code should not have any mypy errors. However, it has several. `reveal_type` was added to see what type mypy thinks everything should be.
```console
$ mypy --strict test.py
test.py:7: note: Revealed type is "Union[torch._tensor.Tensor, torch.nn.modules.module.Module]"
test.py:8: error: "Tensor" not callable  [operator]
test.py:9: note: Revealed type is "Union[torch._tensor.Tensor, torch.nn.modules.module.Module]"
test.py:10: error: Item "Tensor" of "Union[Tensor, Module]" has no attribute "layer_1_dim"  [union-attr]
test.py:11: error: Value of type "Union[Tensor, Module]" is not indexable  [index]
test.py:11: error: Invalid index type "str" for "Union[Tensor, Module]"; expected type "Union[None, int, slice, Tensor, List[Any], Tuple[Any, ...]]"  [index]
Found 4 errors in 1 file (checked 1 source file)
```

### Environment

```

#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): LightningModule
#- PyTorch Lightning Version (e.g., 1.5.0): 1.8.2
#- Lightning App Version (e.g., 0.5.2): N/A
#- PyTorch Version (e.g., 1.10): 1.12.1
#- Python version (e.g., 3.9): 3.10.8
#- OS (e.g., Linux): macOS and Linux
#- CUDA/cuDNN version: N/A
#- GPU models and configuration: N/A
#- How you installed Lightning(`conda`, `pip`, source): Spack
#- Running environment of LightningApp (e.g. local, cloud): local

```

### More info

This issue has been present ever since PyTorch first added public type hints (PyTorch 1.11, March 2022). Since `self.hparams` is repeatedly accessed throughout every `LightningModule`, this currently requires type ignores in hundreds of places in TorchGeo.

cc @borda @carmocca

**Comment by awaelchli** [comment]
@adamjstewart Our signature for `save_hyperparameters` has the return type annotated as None.
It might be because `__getattr__` from `nn.Module` has type `Union[Tensor, 'Module']`. I'm not sure what can be done here, any ideas?

**Comment by carmocca** [comment]
We weren't able to find a solution to `nn.Module.__getattr__` return annotations and in fact have many ignores around the codebase because of it. I don't think there's any feasible solution

**Comment by adamjstewart** [comment]
Hmm, what you're saying makes sense. I was going to open an issue with mypy with a simple reproducer and ask for advice, but I can't seem to reproduce this behavior. The following code:
```python
import torch.nn as nn

class Foo(nn.Module):
    def bar(self, x: int) -> int:
        return x

y = Foo()
reveal_type(y.bar)
z = 2
z = y.bar(1)
```
passes all checks:
```console
$ mypy --strict test.py
test.py:8: note: Revealed type is "def (x: builtins.int) -> builtins.int"
Success: no issues found in 1 source file
```
If what you're saying is true, shouldn't `reveal_type` show the function signature for `__getattr__`, and shouldn't mypy complain that the type of `z` changed from `int` to `Union[Tensor, Module]`?

**Comment by carmocca** [comment]
Here's the relevant issue upstream: https://github.com/pytorch/pytorch/issues/81462

**Comment by adamjstewart** [comment]
Thanks, I'll close this issue and follow that discussion.

**Comment by adamjstewart** [comment]
I'm not sure if something was fixed in PyTorch or Lightning or mypy, but there are much fewer errors with the above sample code now:
```console
$ mypy --strict test.py
test.py:7: note: Revealed type is "def (*args: Any, *, ignore: Union[typing.Sequence[builtins.str], builtins.str, None] =, frame: Union[types.FrameType, None] =, logger: builtins.bool =)"
test.py:9: note: Revealed type is "typing.MutableMapping[Any, Any]"
test.py:10: error: "MutableMapping[Any, Any]" has no attribute "layer_1_dim"  [attr-defined]
Found 1 error in 1 file (checked 1 source file)
```
This is using:

* PyTorch 1.13.1
* Lightning 1.9.3
* Python 3.10.8
* mypy 1.0.0

So `self.hparams["foo"]` passes all typing tests, but `self.hparams.foo` still doesn't. Is the latter something that could be fixed? It would also be great if the type of these was int/float instead of Any, but that might not be possible since it can't be known a priori.

**Comment by noamsgl** [comment]
Any solutions for this yet? Any suggestions better than doing `self.hparams["learning_rate"]`?

```

class UnetLightningModule(pl.LightningModule):
    """A vanilla U-Net lightning module."""

    def __init__(self, config: dict):
        super().__init__()

        # this line allows to access init params with 'self.hparams' attribute
        # also ensures init params will be stored in ckpt
        self.save_hyperparameters(config)
        self.learning_rate = self.hparams.learning_rate
```
Error:

```
$> pipenv run pre-commit run mypy --all-files
...
error: "MutableMapping[Any, Any]" has no attribute "learning_rate"
...
```
