### ISSUE TITLE
 [CLI] init_args is not properly discarded when class_path changes

### ISSUE THREAD

**Issue by glothe** [Lightning-AI/lightning#15796]
### Bug description

When loading a config and overriding a `class_path` from the CLI, the `init_args` are not properly ignored (even though a warning is correctly issued). If the argument of the new class do not match does of the previous one, a `'Configuration check failed :: No action for destination key "..." to check its value.'` is raised.

I haven't been able to reproduce this in jsonargparse only, so I'm posting this here. Let me know if there is a more appropriate place!

### How to reproduce the bug

```python
Using the following script:

from pytorch_lightning import LightningModule
from pytorch_lightning.cli import LightningCLI

class BaseCls:
    pass

class A(BaseCls):
    def __init__(self, a: int = 0):
        pass

class B(BaseCls):
    def __init__(self, b: int = 0):
        pass

class Model(LightningModule):
    def __init__(self, cls: BaseCls):
        super().__init__()
        print(cls)

    def test_dataloader(self):
        return

    def test_step(self):
        return

cli = LightningCLI(model_class=Model, subclass_mode_model=True)
```

Providing `cls=A` with a suitable value for `a`, then overriding that with `B` yields an error:
```
python test.py test --model=Model --model.init_args.cls=A --model.init_args.cls.init_args.a=0 --model.init_args.cls=B --model.init_args.cls.init_args.b=0
```

Even though the parser claims that `A.a` was dropped, it looks like it wasn't (see error message below). I have tried to reproduce this mistake only with jsonargparse only without much success: the argument is correctly ignored as claimed.

Even though this particular use case is not very realistic, it becomes a problem when loading a previous config that has been generated with `cls=A`, but then we override that with `B`:
```
python test.py test --model=Model --model.init_args.cls=A --print_config > test.yaml
python test.py test --config=test.yaml --model.init_args.cls=B
```

The commands above generate the same error message.

### Error messages and logs

```
[...]/.venv/lib/python3.8/site-packages/jsonargparse/typehints.py:855: UserWarning: Due to class_path change from '__main__.A' to '__main__.B', discarding init_args: {'a': 0}.
  warnings.warn(
usage: test.py [-h] [-c CONFIG] [--print_config[=flags]] {fit,validate,test,predict,tune} ...
test.py: error: Parser key "model": Problem with given class_path "__main__.Model":
  - Parser key "cls": Problem with given class_path "__main__.B":
    - 'Configuration check failed :: No action for destination key "a" to check its value.'
```

The content of the `test.yaml` file is
```
main:
  cls:
    class_path: A
    init_args:
      a: 0
```

### Environment

```

#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0): 1.8.2
#- jsonargparse version: 4.17.0
#- PyTorch Version (e.g., 1.10): 1.11.0
#- Python version (e.g., 3.9): 3.8.12
#- OS (e.g., Linux): Ubuntu 18.04
#- How you installed Lightning(`conda`, `pip`, source): poetry 
#- Running environment of LightningApp (e.g. local, cloud): ec2 instance

```

cc @carmocca @mauvilsa

**Comment by mauvilsa** [comment]
Thank you for reporting! I have been able to reproduce the problem and will look into why this is happening.

**Comment by mauvilsa** [comment]
I have created a pull request (https://github.com/omni-us/jsonargparse/pull/199) that fixes the issue described above. Though, there is a slightly different case which still is not fixed, a class within a list. Probably we shouldn't close this issue until this similar case is resolved.

**Comment by mauvilsa** [comment]
@glothe is the bug resolved? Can this issue be closed?

**Comment by glothe** [comment]
@mauvilsa Yes! Sorry for not getting back to you sooner but it looks like this bug was resolved very quickly!
