### ISSUE TITLE
Incorrect error message: Trainer is already configured with a `BatchSizeFinder` callback

### ISSUE THREAD

**Issue by davidgilbertson** [Lightning-AI/lightning#15855]
### Bug description

I have a trainer with a `LearningRateFinder` callback. In trying to get it to work, I've set `auto_lr_find=True,` on the trainer and have called `trainer.tune()` (I don't know what I'm doing, as you can probably tell).

The bug is that the error message says "`BatchSizeFinder` callback", when it should say "`LearningRateFinder` callback".

Offending code is here: https://github.com/Lightning-AI/lightning/blob/master/src/pytorch_lightning/tuner/tuning.py#L299-L303 as at version 1.8.3.post1.

BTW, I'm finding the docs around `auto_lr_find`, `LearningRateFinder`, `trainer.tune()`, `trainer.tuner.lr_find()` and when/where I can set `max_lr` and `min_lr`, and which methods update the model and which don't all quite confusing. Also `_LRFinder` is internal, so not documented (on the website) but returned to the user so probably should be public and exposed as `LrFinderResults` or something?

### Error messages and logs

```

# Error messages and logs here please

```

cc @borda

**Comment by Al3xDo** [comment]
Hi @awaelchli, I would like to work on this issue.

**Comment by Al3xDo** [comment]
Hi @Borda , If there are two callbacks (BatchSizeFinder and LearningRateFinder) in trainer callbacks, should we print both callback names? Or should we print one name first and after the user fixed it, we print another one ?

The offending code: 

    if any(isinstance(cb, (BatchSizeFinder, LearningRateFinder)) for cb in trainer.callbacks):
        raise MisconfigurationException(
            "Trainer is already configured with a `BatchSizeFinder` callback. Please remove it if you"
            " want to use tuner."
        )
