### ISSUE TITLE
[lightning_utilities] Missed py.typed file causes type hinting errors

### ISSUE THREAD

**Issue by AlexanderVanEck** [Lightning-AI/lightning#15889]
### Bug description

Hello PyTorch team 👋  Thank you for maintaining this amazing package, the latest releases have been excellent and a joy to use 🙇‍♂️ 

When upgrading to the latest version of pytorch-lightning (1.8) I've stumbled upon a type checking problem with `rank_zero_only`. It uncovered a bug in the type checker `pyright` but it is also related to a missed `py.typed` file in the `lightning_utilities` package.

Would you please add this file to `lightning_utilities` so that its types may be used by other libraries?

### How to reproduce the bug

See https://github.com/microsoft/pyright/issues/4253 for context

### Environment

```

#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0): 1.8
#- Lightning App Version (e.g., 0.5.2): n/a
#- PyTorch Version (e.g., 1.10): n/a
#- Python version (e.g., 3.9): n/a
#- OS (e.g., Linux): n/a
#- CUDA/cuDNN version: n/a
#- GPU models and configuration: n/a
#- How you installed Lightning(`conda`, `pip`, source): n/a
#- Running environment of LightningApp (e.g. local, cloud): n/a

```

**Comment by Borda** [comment]
@AlexanderVanEck great finding, would you mind opening a PR on https://github.com/Lightning-AI/utilities to fix it? :rabbit:
