### ISSUE TITLE
Running validation and modelcheckpoint at each n training steps and at end of training.

### ISSUE THREAD

**Issue by JeromeC-B** [Lightning-AI/lightning#15897]
## 🚀 Feature

Hello!

I'm trying to run my validation loop each n training steps, and at the end of training. When early stopping is not used, if the total training steps is 100, and val_check_interval = 40, then the validation loop will not be called at the end of training. Right now, I added some code on the on_epoch_end() in my pl_model to make it work.

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging PyTorch Lightning, Transformers, and Hydra.

**Comment by Borda** [comment]
Hello, you shall be able to use `val_check_interval`, pls see the [docs](https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.trainer.trainer.Trainer.html#pytorch_lightning.trainer.trainer.Trainer.params.val_check_interval)

**Comment by JeromeC-B** [comment]
Hi!
I see how I was uncleared in my issue. I updated it.

**Comment by JeromeC-B** [comment]
@ashwinb

**Comment by JeromeC-B** [comment]
@awaelchli

**Comment by awaelchli** [comment]
@JeromeC-B There is currently no way to configure running validation at irregular intervals. To enable this, a user would [need to customize the loop](https://pytorch-lightning.readthedocs.io/en/stable/extensions/loops.html#overriding-the-default-loops).

**Comment by JeromeC-B** [comment]
Hi, thank you!
