### ISSUE TITLE
Trainer: AttributeError: 'Trainer' object has no attribute '_accelerator_connector

### ISSUE THREAD

**Issue by gioannides** [Lightning-AI/lightning#15892]
### Bug description

Loading pickled model checkpoints that use `Trainer` throw `AttributeError: 'Trainer' object has no attribute '_accelerator_connector' ` error when loaded from pickle and attempted to be used (e.g. for inference)

### How to reproduce the bug

Load pickled model checkpoint and attempt to use it.

### Error messages and logs

'Trainer' object has no attribute '_accelerator_connector

**Comment by Borda** [comment]
@gioannides what I see it hall be there, but why would you need to access the protected attribute? :otter: 
Also, could you share a reproducible example to see what you are trying to achieve?

**Comment by awaelchli** [comment]
It seems that somehow the Trainer got pickled into your checkpoint. This should never happen. Would you mind sharing your code?

**Comment by RomanKees** [comment]
I encountered this issue after loading a checkpoint of a NeuralProphet model. The solution that worked for me was to use the model.restore_trainer() method on the unpickled model: https://github.com/ourownstory/neural_prophet/blob/b8d6498eedfb501b8d701b3f73c4e498423b22d0/neuralprophet/forecaster.py#L2847
Similar logic may apply for other architectures.

**Comment by noor-malaika** [comment]
> I encountered this issue after loading a checkpoint of a NeuralProphet model. The solution that worked for me was to use the model.restore_trainer() method on the unpickled model: https://github.com/ourownstory/neural_prophet/blob/b8d6498eedfb501b8d701b3f73c4e498423b22d0/neuralprophet/forecaster.py#L2847 Similar logic may apply for other architectures.

thank you!
i was trying to fix the same issue, none of the fixes worked but this got me right.
-> first i unpickled the model
-> before making predictions called model.restore_trainer()
.
and it went fine
