### ISSUE TITLE
clipboard not working in the PythonServer component

### ISSUE THREAD

**Issue by aniketmaurya** [Lightning-AI/lightning#15906]
### Bug description

PythonServer components create an API doc and clipboard for copying the code and the sample response doesn't work.

https://www.loom.com/share/7c29e270dc364bd2993ca57f2c9177f5

**Comment by Borda** [comment]
@aniketmaurya is is still happening with the latest `lightning`?

**Comment by hhsecond** [comment]
@aniketmaurya this had been fixed. Closing the issue but feel free to reopen if you have the same issue again
