### ISSUE TITLE
Train a pl.LightningModule from within a pl.Callback

### ISSUE THREAD

**Issue by gianmarcoaversanoenx** [Lightning-AI/lightning#15967]
### Description & Motivation

In a project, I need to evaluate some metrics during training. Thus, I use a `pl.Callback`! Very natural. However, these metrics are evaluated by quickly training another model (`pl.LightninModule`), using a `pl.Trainer`. This  creates a `pl.Trainer` nested in another running `pl.Trainer` via a `pl.Callback`.

```python
trainer = pl.Trainer(
    ...,
    # this callback will log some metrics after training another model
    callbacks=[MyCallback()],
)
```

While training, all is good until `MyCallback` runs. And it runs fine. However, after it does, I get:

```
def _call_lightning_datamodule_hook(
        self,
        hook_name: str,
        *args: Any,
        **kwargs: Any,
    ) -> Any:
        if self.datamodule is None:
>           raise TypeError("No `LightningDataModule` is available to call hooks on.")
E           TypeError: No `LightningDataModule` is available to call hooks on.
```

If `MyCallback` does not use a (nested) `pl.Trainer` to train the model the estimates the metrics, I do not get this error. Any reason why this happens? How do I fix it?

### Pitch

Update documentation to explain why this is not possible or make this possible.

**Comment by awaelchli** [comment]
The  callback system and Trainer are not designed for this use case, and it is unlikely that we will be able to support it, sorry. This would be too complex. 

We now have [Fabric](https://lightning.ai/docs/fabric/stable/), which allows users to take control and write their training loop however they want. This adds flexibility where the Trainer is too static, and we recommend Fabric when your training loop is not standard. Your use case would probably fall into that category when you need to nest multiple training loops into each other. 

For this reason, I will close the stale issue.
