### ISSUE TITLE
FSDP showing no memory decrease

### ISSUE THREAD

**Issue by clarkbab** [Lightning-AI/lightning#15976]
### Bug description

Hi,

I'm currently training a 3D segmentation model on large medical images. I'm using the pytorch-lightning 'fsdp_native' strategy but seeing no memory footprint decrease when moving from a single GPU to multiple GPUs.

I have tried with and without recursively wrapping the model using `FullyShardedDataParallel` (with `size_based_auto_wrap_policy.min_num_params=10`) inside `def configure_sharded_model` callback. I check memory usage using `nvidia-smi` and `torch.cuda.memory_allocated()`. Results:

With `FullyShardedDataParallel` wrapping inside `def configure_sharded_model`:
  - 1 GPU: 46GB (`torch.cuda.memory_allocated()`) and 79GB (`nvidia-smi`).
  - 2 GPUs: 46GB (`torch.cuda.memory_allocated()`) and 80GB (`nvidia-smi`).
With no wrapping:
  - 1 GPU: 24GB (`torch.cuda.memory_allocated()`) and 39GB (`nvidia-smi`).
  - 2 GPUs: 24GB (`torch.cuda.memory_allocated()`) and 37GB (`nvidia-smi`).

From what I can see there is no improvement in memory usage. Also, almost double the memory is used when we recursively wrap the model! Are there any ways to make sure `FSDP` is running properly?

Thanks,
Brett

 

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
@clarkbab Thanks for reporting. Can you share the code? We need something to work with :) 

This
`size_based_auto_wrap_policy.min_num_params=10`
looks suspiciously wrong. 

Please have a look here how to define the policy for your needs:
```py

def custom_auto_wrap_policy(
     module: nn.Module,
     recurse: bool,
     unwrapped_params: int,
     # These are customizable for this policy function.
     min_num_params: int = int(1e8),
) -> bool:
    return unwrapped_params >= min_num_params
    # Configure a custom min_num_params
my_auto_wrap_policy = functools.partial(custom_auto_wrap_policy, min_num_params=1e5)
```

In your specific case, you can do:
```py
my_auto_wrap_policy = functools.partial(size_based_auto_wrap_policy, min_num_params=1e5)
```


This is from the [FSDP docs](https://pytorch.org/docs/1.13/fsdp.html). Note that the API will change again in the next version of pytorch. We need to update our own docs to show these use cases for user 👍

**Comment by clarkbab** [comment]
Hi @awaelchli, closing this out as segmentation model was "activation-heavy" and benefitted from activation checkpointing rather than parameter sharding. Thanks for your help!

**Comment by karthikiitm87** [comment]
Hi @clarkbab, may I please know how did you solve this issue? I am facing the similar issue and not able to understand where I am going wrong. I could not understand on what you meant by benefitted from activtaion checkpointing?
