### ISSUE TITLE
WandbLogger add Artifact name selection and save by reference

### ISSUE THREAD

**Issue by ShuAiii** [Lightning-AI/lightning#15990]
### Description & Motivation

The model artifact is currently saved as:

```python
artifact = wandb.Artifact(name=f"model-{self.experiment.id}", type="model", metadata=metadata)
```
https://github.com/Lightning-AI/lightning/blob/1657ea8a39c3795e1276c491eff4f13b06a06e61/src/pytorch_lightning/loggers/wandb.py#L599

This results in obscure names such as: `model-3j2t0k7n` that is hard to refer back to the experiment (without looking at the lineages).

There is no current option to log the model by reference. So the model Artifact is always uploaded to WandB.
https://github.com/Lightning-AI/lightning/blob/1657ea8a39c3795e1276c491eff4f13b06a06e61/src/pytorch_lightning/loggers/wandb.py#L600 

### Pitch

For the naming issue, add the option to save the model by experiment name. This makes sense because there should be a 1-to-1 relationship between the experiment and the model. As long as experiment names are uniquely defined within a project, things should be okay.

```python
artifact = wandb.Artifact(name=f"model-{self.experiment.name}", type="model", metadata=metadata)
```

On log by reference point, add a flag to choose to log the Artifact by reference or not.

```python
artifact = wandb.Artifact(name=f"model-", type="model", metadata=metadata)

if log_by_reference:
    artifact.add_reference(p, name="model.ckpt")
else:
    artifact.add_file(p, name="model.ckpt")

self.experiment.log_artifact(artifact, aliases=[tag])
```

cc @borda @awaelchli @morganmcg1 @borisdayma @scottire @manangoel99

**Comment by manangoel99** [comment]
Thank you for raising this @ShuAiii !  Engineer from W&B here.
We've been thinking of adding a new argument to the `WandbLogger` for users to be provide custom model checkpoint names. 
Could you elaborate a little more on what you're thinking about the adding artifacts by reference bit? Currently the way we find model checkpoints is by using the ModelCheckpoint callback and fetching the paths from that. In my understanding adding an artifact by reference requires the URI to that file which I'm not entirely sure is what the ModelCheckpoint callback will be returning.

**Comment by manangoel99** [comment]
Ah! I didn't know PL could save directly to a S3 bucket. This can be implemented as well.
I'm getting started on this PR

**Comment by ShuAiii** [comment]
@manangoel99 Awesome!
