### ISSUE TITLE
Dict specified val_dataloader, test_dataloader and predict_dataloader

### ISSUE THREAD

**Issue by kotchin** [Lightning-AI/lightning#16015]
### Description & Motivation

Conveniently, a DataModule can return a `train_dataloader()` which is a dict, where the name of a dataset is a key and the value is the dataloader.
This is unfortunately not possible with `val_dataloader()`, `test_dataloader()` and `predict_dataloader()`. Yet this could be particularly interesting from a logging perspective allowing for the DataModule to name the datasets and reuse those names when logging the data from the LitModule.

Perhaps there is a specific reason for why this hasn't been implemented or can't be implemented, but it's not obvious to me.

I have tested the dict based approaches above and the documentation in [DataModule.from_datasets()](https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.core.LightningDataModule.html#pytorch_lightning.core.LightningDataModule.from_datasets) also reflects that impossibility.

Edit: typo

cc @borda @justusschock @awaelchli

**Comment by awaelchli** [comment]
Support for dictionary in the eval steps was added in https://github.com/Lightning-AI/lightning/pull/16726 :) 
(release notes: https://github.com/Lightning-AI/lightning/releases/tag/2.0.0)

**Comment by awaelchli** [comment]
Support for this will be added with https://github.com/Lightning-AI/lightning/pull/17163
cc @carmocca

**Comment by carmocca** [comment]
It's not clear to me what this issue requests. Support for multiple dataloaders has existed for a while, but they are run sequentially during evaluation.

#17163 removes this sequential constraint for `.validate()` and `.test()`

But the top post doesn't explicitly state that the problem is running sequentiallly

**Comment by kotchin** [comment]
@carmocca this issue requests the same dict based dataloader support for val_dataloader, test_dataloader and predict_dataloader as exists for train_dataloader.

Specifically, when setting up a LightningDataModule, a train_dataloader can return a dict, where a key can correspond to a dataloader.
For val_dataloader, test_dataloader and predict_dataloader, this is not possible. At best, one can return a list of dataloaders, but this breaks a possible naming potential of each of the dataloaders in the list.

One example is that if I want my val_dataloader to contain 3 different dataloaders "val_dataloader A", "val_dataloader B" and "val_dataloader C", the only thing I can get is a list of dataloaders, but I can't reuse any name or any definition to what each dataloader is, so if by any chance the order of the dataloaders is changed, this can't be automatically detected/accounted for my the LightningModule.

This is why the dict based train_dataloader is convenient, it allows to return:
```
{"dataloader A": dataloader_A, "dataloader B": dataloader_B, "dataloader C": dataloader_C}
```
instead of 
`[dataloader_A, dataloader_B, dataloader_C]`

The question is mostly why this dict based dataloader organization is only available for train_dataloader and not the other methods.

**Comment by carmocca** [comment]
A dict can be returned at least in version 2.0. Try playing around with this script:

```python
import os

import torch
from torch.utils.data import DataLoader, Dataset

from lightning.pytorch import LightningModule, Trainer


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def test_step(self, batch, batch_idx, dataloader_idx=0):
        print(dataloader_idx, batch_idx, batch)

    def test_dataloader(self):
        return {"A": DataLoader(RandomDataset(32, 64), batch_size=2), "B": DataLoader(RandomDataset(32, 64), batch_size=2)}

def run():
    model = BoringModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_test_batches=1,
        barebones=True,
    )
    trainer.test(model)


if __name__ == "__main__":
    run()
```

But the dataloaders will be consumed sequentially (during validate, test and predict), and the dictionary keys are not included in the batch. Perhaps you meant that you are interested in consuming them using a different mode: https://lightning.ai/docs/pytorch/stable/data/iterables.html#multiple-iterables

Example:

```python
    def test_dataloader(self):
        from lightning.pytorch.utilities import CombinedLoader
        dataloaders = {"A": DataLoader(RandomDataset(32, 64), batch_size=2), "B": DataLoader(RandomDataset(32, 64), batch_size=2)}
        return CombinedLoader(dataloaders, mode="max_size_cycle")
```

Which in 2.0.1 raises:

```python
ValueError: `trainer.test()` only supports the `CombinedLoader(mode="sequential")` mode.
```

But I just implemented support in master with #17163 if this is blocking you

**Comment by carmocca** [comment]
The `from_datasets` method needs an update though. Good catch.

**Comment by ringohoffman** [comment]
FWIW, I and many others are are thoroughly confused about the lack of parity between `train_dataloader` and `val_dataloader` when returning `dict` of `DataLoader`:

* https://github.com/Lightning-AI/pytorch-lightning/discussions/12048
* https://github.com/Lightning-AI/pytorch-lightning/discussions/5782
* https://github.com/Lightning-AI/pytorch-lightning/issues/4358
* https://github.com/Lightning-AI/pytorch-lightning/issues/5701
* https://lightning.ai/forums/t/name-of-dataloader-in-case-of-multiple-dataloaders/900

Why does `dataloader_idx` have to be an `int`? Why not just provide the key of the corresponding `dataloader`?  It's much more intelligible to have conditions based on the `str` keys of the `dict` returned by `validation_step` than it is an integer index.
