### ISSUE TITLE
LightningCLI parser_mode not activated for `default_config_files` specified per subcommand

### ISSUE THREAD

**Issue by vedal** [Lightning-AI/lightning#16021]
### Bug description

When Specifying `default_config_files` per subcommand, as specified in [this example](https://pytorch-lightning.readthedocs.io/en/latest/cli/lightning_cli_advanced_2.html#set-default-config-files), it seems`parser_mode="omegaconf"` is not activated.

### How to reproduce the bug

`example_LightningCLI.yaml`

```
directory: foo/bar
trainer:
    default_root_dir: ${directory}
```

`example_LightningCLI.py`
```python

import pytorch_lightning as pl
from pytorch_lightning.cli import LightningCLI
from torch.utils.data import DataLoader
from torchvision import transforms
from torchvision.datasets import MNIST

class MyModel(pl.LightningModule):
    def __init__(self):
        super(MyModel, self).__init__()
    
    def training_step(self, batch, batch_idx):
        return None
    
    def configure_optimizers(self):
        return

class MyDataModule(pl.LightningDataModule):
    def train_dataloader(self):
        return DataLoader(MNIST("./", train=False, download=True, transform=transforms.ToTensor()))


class MyLightningCLI(LightningCLI):
    #https://github.com/Lightning-AI/lightning/issues/13558#issue-1296328078
    def add_arguments_to_parser(self, parser):
        parser.add_argument('--directory', type = str)

def cli_main():
    cli = MyLightningCLI(
        model_class=MyModel,
        datamodule_class=MyDataModule,
        parser_kwargs={
            "parser_mode": "omegaconf",
            # WARNING: no variable interpolation when below line is uncommented
            "fit": {"default_config_files": ["example_LightningCLI.yaml"]}
        },
    )

if __name__ == "__main__":
    cli_main()
```

Running this command:
`python example_LightningCLI.py fit --print_config --config example_LightningCLI.yaml | grep root_dir`
gives:
`default_root_dir: ${directory}`

Instead, uncommenting the specified line gives
`default_root_dir: foo/bar`

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): LightningCLI
#- PyTorch Lightning Version (e.g., 1.5.0): 1.8.4.post0
#- Lightning App Version (e.g., 0.5.2): -
#- PyTorch Version (e.g., 1.10): 1.13.0
#- Python version (e.g., 3.9): 3.8.5
#- OS (e.g., Linux): Linux
#- CUDA/cuDNN version: cu116
#- GPU models and configuration: -
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud): -
# omegaconf==2.3.0
# jsonargparse==4.18.0
```

</details>

cc @carmocca @mauvilsa

**Comment by mauvilsa** [comment]
I tried this with the latest version of lightning in master and the latest release of jsonargparse 4.18.0 and the results is as expected: `default_root_dir: foo/bar`. In the environment I see lighting `1.8.3.post1`. Why not using the latest? Anyway, don't know what the problem is.

**Comment by vedal** [comment]
@mauvilsa thanks for trying to reproduce this. I simplified the example a bit further to ensure we're on the same page
Installed a new environment with fresh pip-installs did not help.

Then, installing lightning from current master 18a4638, and replacing import 
``` 
lightning.pytorch.cli import LightningCLI
```
solved the issue.
