### ISSUE TITLE
Recent project name in WandbLogger ignores env var WANDB_PROJECT

### ISSUE THREAD

**Issue by elgalu** [Lightning-AI/lightning#16028]
### Bug description

This change https://github.com/Lightning-AI/lightning/pull/14145/files#diff-fb7a6ccc19c8344d78090c02d77175ad3f9699a8bc0e4ab26345855023ce3c12R37-R42 didn't take into account Weights and Biases users using the `WANDB_PROJECT` environmental variable to set the project name https://docs.wandb.ai/guides/track/advanced/environment-variables

### How to reproduce the bug

```python
export WANDB_PROJECT=my-project-name
# launch training job
```

### Error messages and logs

Result: `WANDB_PROJECT` gets ignored and overwritten by the new default `project: str = "lightning_logs",` https://github.com/Lightning-AI/lightning/blob/46548337def198216b4e3000ef08b06c9c11816d/src/pytorch_lightning/loggers/wandb.py#L302

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): Trainer
#- PyTorch Lightning Version (e.g., 1.5.0): 1.8.4.post0
#- PyTorch Version (e.g., 1.10): 1.12.1
#- Python version (e.g., 3.9): 3.8.13
#- OS (e.g., Linux): Linux
#- CUDA/cuDNN version: 515.65.01 CUDA Version: 11.7
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud): local
```

</details>

cc @awaelchli @morganmcg1 @borisdayma @scottire @manangoel99

**Comment by awaelchli** [comment]
@elgalu Thanks for reporting. I think we want to keep the default at lightning_logs, but perhaps need to handle the special case of the env var.

**Comment by awaelchli** [comment]
Are you interested in making a contribution? :)

**Comment by elgalu** [comment]
Maybe someone from WandB with experience in not hard-coding project names https://github.com/wandb/wandb/commit/238d3a6b51397305d60916fac851d2bae5ccc1e4 like @raubitsj

**Comment by manangoel99** [comment]
Hi! I can take this one
