### ISSUE TITLE
About ModelCheckpoint 

### ISSUE THREAD

**Issue by OldWheat** [Lightning-AI/lightning#16061]
### 📚 Documentation

From the document https://pytorch-lightning.readthedocs.io/en/latest/common/checkpointing_intermediate.html, I only can understand how to save checkpoints for each step, so can you give a example that save checkpoint for each epoch?

I do confused about this, and I hope you can answer me about this.

cc @awaelchli

**Comment by awaelchli** [comment]
@OldWheat By default, checkpointing happens every time validation runs, and by default validation runs at the end of every epoch. So checkpointing happens every epoch normally. [Here are the different ways](https://pytorch-lightning.readthedocs.io/en/latest/common/checkpointing_intermediate.html#save-checkpoints-by-condition) you can control when to save a checkpoint.
