### ISSUE TITLE
Make INFO-level logs not red in PyCharm

### ISSUE THREAD

**Issue by davidgilbertson** [Lightning-AI/lightning#16081]
### Description & Motivation

In PyCharm, informational messages from Lightning are printed in red, which doesn't look great and obscures real errors.

This is because the logger is printing to `stderr` and PyCharm by default makes that red.
![image](https://user-images.githubusercontent.com/4443482/207949633-1795c65a-05c0-4b00-8972-acf7fca2cad2.png)

### Pitch

You can fix this by tweaking your root logger to print to `stdout` for `INFO` and below, and `stderr` for everything else. All the other loggers will inherit from this

In `pytorch_lightning/__init__.py`:
```py
_logger = logging.getLogger(__name__)
_logger.setLevel(logging.INFO)

# log lower levels to stdout
stdout_handler = logging.StreamHandler(stream=sys.stdout)
stdout_handler.addFilter(lambda rec: rec.levelno <= logging.INFO)
_logger.addHandler(stdout_handler)

# log higher levels to stderr (red)
stderr_handler = logging.StreamHandler(stream=sys.stderr)
stderr_handler.addFilter(lambda rec: rec.levelno > logging.INFO)
_logger.addHandler(stderr_handler)
```

Which then prints like so:
![image](https://user-images.githubusercontent.com/4443482/207949475-839bb61f-b0ef-4dd6-9a45-6d24d3a4f35f.png)

cc @borda @justusschock

**Comment by awaelchli** [comment]
I'm not sure if there is a real reason behind why we default to stderr. Sounds good to me, we can give this a try.

**Comment by davidgilbertson** [comment]
It's actually a [Python default](https://docs.python.org/3/library/logging.handlers.html#logging.StreamHandler), nothing Lightning has done specifically.

If you're feeling really fancy, you can define a handler that will log in the appropriate color for each level:
```py
class ColorHandler(logging.StreamHandler):
    # https://en.wikipedia.org/wiki/ANSI_escape_code#Colors
    GRAY8 = "38;5;8"
    GRAY7 = "38;5;7"
    ORANGE = "33"
    RED = "31"
    WHITE = "0"

    def emit(self, record):
        # Don't use white for any logging, to help distinguish from user print statements
        level_color_map = {
            logging.DEBUG: self.GRAY8,
            logging.INFO: self.GRAY7,
            logging.WARNING: self.ORANGE,
            logging.ERROR: self.RED,
        }

        csi = f"{chr(27)}["  # control sequence introducer
        color = level_color_map.get(record.levelno, self.WHITE)

        print(f"{csi}{color}m{record.msg}{csi}m")

logging.getLogger(__name__).addHandler(ColorHandler())
```

**Comment by Borda** [comment]
> If you're feeling really fancy, you can define a handler that will log in the appropriate color for each level:

sounds cool to me, mind sending a draft PR? :rabbit:

**Comment by davidgilbertson** [comment]
Sorry I've got a full study schedule, I'm trying not to get too bogged down in other things for now. When I've finished learning AI and have a job then I'll be able to contribute more :)

**Comment by Borda** [comment]
> When I've finished learning AI and have a job then I'll be able to contribute more :)

sure no problem, no rush :)

**Comment by carmocca** [comment]
Logging to stderr is usually on purpose for libraries/frameworks. The main benefit is that it uses a different stream than the regular prints/logs that are generated from the user code.

This decision is mainly a "stylistic standard" but changing it would be an unavoidable breaking change.

For example, I've written PL scripts where I print results relevant to my experiment (to `stdout`) and pipe the command into a text file (`python script.py > out.txt`). Doing this change would break such workflow and would make it difficult to separate user logs from library logs.

The same can be said for colored logs. Many terminals do not support rendering so adding them can add intentionally annoying lines in between the valuable messages for the color output. Maybe this is fine as long as we adhere to the requirements in https://no-color.org. Still, a too-colorful choice can be distracting so I would ask for examples of how some experiment logs would show first.

**Comment by davidgilbertson** [comment]
Ah, that's a good point about libraries printing to stderr as a way to split user/3rd party logs. And thanks for letting me know about NO_COLOR.

Re the colourfulness, for the most part it makes the output less colourful (I do this in my own project to modify the output of all packages) since most things are 'info' and I see them 800 times a day.

Example of how PL looks to me:
![image](https://user-images.githubusercontent.com/4443482/208759638-50fa7057-b67a-4419-be02-8c7b64fb1277.png)

Compared to the default (in PyCharm, which renders stderr red)
![image](https://user-images.githubusercontent.com/4443482/208760112-32851967-fcd4-4a82-b8fa-b9ca3c1251e4.png)


As a side-effect, this highlights places where a package is using `print` (first two lines) but should perhaps be using `logging.info()`.

Adapted code to write to stderr and respect `NO_COLOR`:
```py
class ColorHandler(logging.StreamHandler):
    # https://en.wikipedia.org/wiki/ANSI_escape_code#Colors
    GRAY8 = "38;5;8"
    GRAY7 = "38;5;7"
    ORANGE = "33"
    RED = "31"
    WHITE = "0"

    def emit(self, record):
        # We don't use white for any logging, to help distinguish from user print statements
        level_color_map = {
            logging.DEBUG: self.GRAY8,
            logging.INFO: self.GRAY7,
            logging.WARNING: self.ORANGE,
            logging.ERROR: self.RED,
        }

        csi = f"{chr(27)}["  # control sequence introducer
        color = level_color_map.get(record.levelno, self.WHITE)

        self.stream.write(f"{csi}{color}m{record.msg}{csi}m\n")


# See https://no-color.org/
if not os.environ.get("NO_COLOR"):
    logging.getLogger().addHandler(ColorHandler())
```

Implementing would still be quite a task as those greys don't print the same in all terminals so there's a lot of testing to be done to get things just right, while being mindful of accessibility contrast guidelines.

**Comment by carmocca** [comment]
It's probably more involved than that, because in the wild people use really different terminals. I suggest looking at the [`rich.Console`](https://github.com/Textualize/rich/blob/5d3e44bbc6c1907f0a63dad118c86e079055f3be/rich/console.py) implementation as a reference. If you cmd+F for "color" in the file, you'll see several interesting details.

If you are feeling brave, feel free to open a PR for color support specifically and we can discuss details there.
