### ISSUE TITLE
Torch sees GPU but does not use it

### ISSUE THREAD

**Issue by ThatGuyCalledJesse** [Lightning-AI/lightning#16102]
### Bug description

When I use ``torch.cuda.device_count()``
it returns 1, which is correct
But then when using Lightning, it shows this in terminal
``LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
``

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
@ThatGuyCalledJesse That's correct. If you have one GPU, then Lightning can only use one and that's device with index 0. 
If you had multiple GPUs, it would show:

`LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0, 1]`

etc.

**Comment by ThatGuyCalledJesse** [comment]
I am so sorry, it's a very beginner mistake

**Comment by yotamcons** [comment]
I made the same mistake, thank you for asking.
What bothered me was the "local rank" which i couldn't figure out. This calls for better logging, especially in the uncomfortable new filed of gpu computations.

**Comment by ejkitchen** [comment]
Please keep this thread up because I made the exact same assumption as the original poster. I know CUDA devices start at 0 but I was still thrown off by this message.
