### ISSUE TITLE
RuntimeError: PARSeq is not attached to a `Trainer`.

### ISSUE THREAD

**Issue by naveenkumarkr723** [Lightning-AI/lightning#16157]
### Bug description

i was trying to convert Parseq model to Direct TRT conversion without using ONNX model
.
this is model file
https://github.com/baudm/parseq/releases/download/v1.0.0/parseq-bb5792a6.pt
https://github.com/baudm/parseq#pretrained-models-via-torch-hub  ---> this model code 

https://pytorch.org/TensorRT/getting_started/getting_started_with_python_api.html  ---> iam following this link to convert TRT from parseq

```py
/usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py:256: UserWarning: 'norm' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  warnings.warn("'{}' was found in ScriptModule constants, "
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In [15], line 3
      1 enabled_precisions = {torch.float32, torch.float32}  
----> 3 trt_ts_module = torch_tensorrt.compile(
      4                                     model, inputs=inputs, enabled_precisions=enabled_precisions)

File /usr/local/lib/python3.8/dist-packages/torch_tensorrt/_compile.py:124, in compile(module, ir, inputs, enabled_precisions, **kwargs)
    119     if module_type == _ModuleType.nn:
    120         logging.log(
    121             logging.Level.Info,
    122             "Module was provided as a torch.nn.Module, trying to script the module with torch.jit.script. In the event of a failure please preconvert your module to TorchScript",
    123         )
--> 124         ts_mod = torch.jit.script(module)
    125     return torch_tensorrt.ts.compile(
    126         ts_mod, inputs=inputs, enabled_precisions=enabled_precisions, **kwargs
    127     )
    128 elif target_ir == _IRType.fx:

File /usr/local/lib/python3.8/dist-packages/torch/jit/_script.py:1286, in script(obj, optimize, _frames_up, _rcb, example_inputs)
   1284 if isinstance(obj, torch.nn.Module):
   1285     obj = call_prepare_scriptable_func(obj)
-> 1286     return torch.jit._recursive.create_script_module(
   1287         obj, torch.jit._recursive.infer_methods_to_compile
   1288     )
   1290 if isinstance(obj, dict):
   1291     return create_script_dict(obj)

File /usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py:473, in create_script_module(nn_module, stubs_fn, share_types, is_tracing)
    471 assert not isinstance(nn_module, torch.jit.RecursiveScriptModule)
    472 check_module_initialized(nn_module)
--> 473 concrete_type = get_module_concrete_type(nn_module, share_types)
    474 if not is_tracing:
    475     AttributeTypeIsSupportedChecker().check(nn_module)

File /usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py:424, in get_module_concrete_type(nn_module, share_types)
    420     return nn_module._concrete_type
    422 if share_types:
    423     # Look into the store of cached JIT types
--> 424     concrete_type = concrete_type_store.get_or_create_concrete_type(nn_module)
    425 else:
    426     # Get a concrete type directly, without trying to re-use an existing JIT
    427     # type from the type store.
    428     concrete_type_builder = infer_concrete_type_builder(nn_module, share_types)

File /usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py:365, in ConcreteTypeStore.get_or_create_concrete_type(self, nn_module)
    360 def get_or_create_concrete_type(self, nn_module):
    361     """
    362     Infer a ConcreteType from this `nn.Module` instance. Underlying JIT
    363     types are re-used if possible.
    364     """
--> 365     concrete_type_builder = infer_concrete_type_builder(nn_module)
    367     nn_module_type = type(nn_module)
    368     if nn_module_type not in self.type_store:

File /usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py:273, in infer_concrete_type_builder(nn_module, share_types)
    271 overloads = getattr(nn_module, "__overloads__", {})
    272 # update with any annotated overloads
--> 273 overloads.update(get_overload_name_mapping(get_overload_annotations(nn_module, ignored_properties)))
    274 for name, overloaded_names in overloads.items():
    275     concrete_type_builder.add_overload(name, overloaded_names)

File /usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py:639, in get_overload_annotations(mod, jit_ignored_properties)
    637 if name in jit_ignored_properties:
    638     continue
--> 639 item = getattr(mod, name, None)
    640 if not callable(item):
    641     continue

File /usr/local/lib/python3.8/dist-packages/pytorch_lightning/core/module.py:179, in LightningModule.trainer(self)
    176 @property
    177 def trainer(self) -> "pl.Trainer":
    178     if not self._jit_is_scripting and self._trainer is None:
--> 179         raise RuntimeError(f"{self.__class__.__qualname__} is not attached to a `Trainer`.")
    180     return self._trainer

RuntimeError: PARSeq is not attached to a `Trainer`.
```

please provide me solution as much as possible , i hope u can solve it  @vanpelt @ozen @ashwinb @srush @f4hy 
thanks 

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0): 2.8
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10): 1.12.0+cu113
#- Python version (e.g., 3.9): 3.8.10
#- OS (e.g., Linux):  Linux
#- CUDA/cuDNN version: cuda_11.4.r11.4/compiler.30188945_0
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>
torch-tensorrt) (4.3.0)

**Comment by naveenkumarkr723** [comment]
https://pytorch.org/TensorRT/getting_started/getting_started_with_python_api.html   this was the link which i referred for converting parseq to TRT

**Comment by carmocca** [comment]
Have you tried the following?

```python
model = YourLightningModule()
compiled_model = model.to_torchscript()
trt_ts_module = torch_tensorrt.compile(compiled_model)
```

**Comment by naveenkumarkr723** [comment]
tried below code but still getting this error
similar way u suggested but got the error can u go throuh once
========================================
import torch
import torch_tensorrt

model = torch.hub.load('baudm/parseq', 'parseq', pretrained=True, refine_iters=0).eval()

compiled_model = model.to_torchscript()

trt_ts_module = torch_tensorrt.compile(model)

==========================================================

RuntimeError                              Traceback (most recent call last)
Cell In [31], line 8
      4 model = torch.hub.load('baudm/parseq', 'parseq', pretrained=True, refine_iters=0).eval()
      6 compiled_model = model.to_torchscript()
----> 8 trt_ts_module = torch_tensorrt.compile(model)
      9 trt_ts_module

File /usr/local/lib/python3.8/dist-packages/torch_tensorrt/_compile.py:124, in compile(module, ir, inputs, enabled_precisions, **kwargs)
    119     if module_type == _ModuleType.nn:
    120         logging.log(
    121             logging.Level.Info,
    122             "Module was provided as a torch.nn.Module, trying to script the module with torch.jit.script. In the event of a failure please preconvert your module to TorchScript",
    123         )
--> 124         ts_mod = torch.jit.script(module)
    125     return torch_tensorrt.ts.compile(
    126         ts_mod, inputs=inputs, enabled_precisions=enabled_precisions, **kwargs
    127     )
    128 elif target_ir == _IRType.fx:

File /usr/local/lib/python3.8/dist-packages/torch/jit/_script.py:1286, in script(obj, optimize, _frames_up, _rcb, example_inputs)
   1284 if isinstance(obj, torch.nn.Module):
   1285     obj = call_prepare_scriptable_func(obj)
-> 1286     return torch.jit._recursive.create_script_module(
   1287         obj, torch.jit._recursive.infer_methods_to_compile
   1288     )
   1290 if isinstance(obj, dict):
   1291     return create_script_dict(obj)

File /usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py:473, in create_script_module(nn_module, stubs_fn, share_types, is_tracing)
    471 assert not isinstance(nn_module, torch.jit.RecursiveScriptModule)
    472 check_module_initialized(nn_module)
--> 473 concrete_type = get_module_concrete_type(nn_module, share_types)
    474 if not is_tracing:
    475     AttributeTypeIsSupportedChecker().check(nn_module)

File /usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py:424, in get_module_concrete_type(nn_module, share_types)
    420     return nn_module._concrete_type
    422 if share_types:
    423     # Look into the store of cached JIT types
--> 424     concrete_type = concrete_type_store.get_or_create_concrete_type(nn_module)
    425 else:
    426     # Get a concrete type directly, without trying to re-use an existing JIT
    427     # type from the type store.
    428     concrete_type_builder = infer_concrete_type_builder(nn_module, share_types)

File /usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py:365, in ConcreteTypeStore.get_or_create_concrete_type(self, nn_module)
    360 def get_or_create_concrete_type(self, nn_module):
    361     """
    362     Infer a ConcreteType from this `nn.Module` instance. Underlying JIT
    363     types are re-used if possible.
    364     """
--> 365     concrete_type_builder = infer_concrete_type_builder(nn_module)
    367     nn_module_type = type(nn_module)
    368     if nn_module_type not in self.type_store:

File /usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py:273, in infer_concrete_type_builder(nn_module, share_types)
    271 overloads = getattr(nn_module, "__overloads__", {})
    272 # update with any annotated overloads
--> 273 overloads.update(get_overload_name_mapping(get_overload_annotations(nn_module, ignored_properties)))
    274 for name, overloaded_names in overloads.items():
    275     concrete_type_builder.add_overload(name, overloaded_names)

File /usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py:639, in get_overload_annotations(mod, jit_ignored_properties)
    637 if name in jit_ignored_properties:
    638     continue
--> 639 item = getattr(mod, name, None)
    640 if not callable(item):
    641     continue

File /usr/local/lib/python3.8/dist-packages/pytorch_lightning/core/module.py:179, in LightningModule.trainer(self)
    176 @property
    177 def trainer(self) -> "pl.Trainer":
    178     if not self._jit_is_scripting and self._trainer is None:
--> 179         raise RuntimeError(f"{self.__class__.__qualname__} is not attached to a `Trainer`.")
    180     return self._trainer

RuntimeError: PARSeq is not attached to a `Trainer`.

**Comment by carmocca** [comment]
Your example is not what I suggested in my previous message, you need to pass the `compiled_model` to `tensorrt`, not the `model`
