### ISSUE TITLE
ERROR: No matching distribution found for lai-sphinx-theme

### ISSUE THREAD

**Issue by LJoson** [Lightning-AI/lightning#16158]
### 📚 Documentation

I want to know if lai-sphinx-theme is an open-source project？ because when I try to use `pip install -e . --quiet -r requirements/app/docs.txt`, gives the following,
```
ERROR: Could not find a version that satisfies the requirement lai-sphinx-theme (from versions: none)
ERROR: No matching distribution found for lai-sphinx-theme
```

cc @borda @tchaton

**Comment by nohalon** [comment]
I'm having the same issue

**Comment by carmocca** [comment]
The sphinx theme is not open source, so external contributors cannot install it. You can use the PR CI to let it build it for you and see your changes.

For staff, the installation steps need to be updated.

**Comment by Borda** [comment]
yes, we are working on making this template accessible to contributors so they can easily debug docs locally... :otter: 
cc: @yurijmikhalevich
