### ISSUE TITLE
Multiple Loggers : Only first mentioned logger used as default insider Trainer.fit()

### ISSUE THREAD

**Issue by kamranisg** [Lightning-AI/lightning#16238]
### Bug description

In the event of using Multiple Loggers inside the Trainer, we pass loggers as a List. I found that multiple loggers are not being used upon calling the Trainer.fit() function. Since any lightning hook or function can access the loggers except init, I see that only the first mentioned logger is being used as default.

### How to reproduce the bug

```python
from pytorch_lightning.loggers import TensorBoardLogger, WandbLogger

logger1 = TensorBoardLogger(save_dir="tb_logs", name="my_model")
logger2 = WandbLogger(save_dir="tb_logs", name="my_model")
trainer = Trainer(logger=[logger1, logger2])

```ruby
print(logger)
# Output
[<pytorch_lightning.loggers.tensorboard.TensorBoardLogger object at 0x7fe12d9d9970>, <pytorch_lightning.loggers.wandb.WandbLogger object at 0x7fe12d9f12b0>]

trainer.fit(model=model,datamodule=datmodule)
print(self.logger)
# Output : Issue
<pytorch_lightning.loggers.tensorboard.TensorBoardLogger object at 0x7fe12d9d9970>
```

```ruby
# Inside Model module 

def training_step(self,batch: Any, batch_idx: int):
        print(self.logger)
        print(self.logger[1])

# OUTPUT
<pytorch_lightning.loggers.tensorboard.TensorBoardLogger object at 0x7fe12d9d9970>
Error: 
TypeError: 'TensorBoardLogger' object is not subscriptable
```

_

**Issue: Turns out self.logger takes the 1st logger(index 0) by default and raises error on calling 2nd logger(index 1)**
_

Line: 2148  [https://github.com/Lightning-AI/lightning/blob/ae14f9d1b355859b258d5bacaeff74917fc8cc74/src/pytorch_lightning/trainer/trainer.py#L112](url)

What worked for me by changing the following inside trainer.py

```ruby
#What's Wrong : 
    @property
    def logger(self) -> Optional[Logger]:
        return self.loggers[0] if len(self.loggers) > 0 else None
```

```ruby
#What worked  
@property
    def logger(self) -> Optional[Logger]:
        return self.loggers if len(self.loggers) > 0 else None
```
```


### Error messages and logs

```
# Error messages and logs here please
```

```ruby
Error: 
TypeError: 'TensorBoardLogger' object is not subscriptable
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0): 1.8.3.post1   pypi_0   
#- PyTorch Version: 1.13.0   py3.9_cuda11.7_cudnn8.5.0_0    
#- Python version: 3.9.15
#- CUDA/cuDNN version: 11.7.1
```

</details>

### More info

@

cc @awaelchli @borda @Blaizzy

**Comment by awaelchli** [comment]
@kamranisg I think the issue is that you have a typo, it should be:

```python
print(self.logger)  # access the first logger
print(self.loggers[1])  # access multiple loggers (plural)
```

Does that make sense?

**Comment by kamranisg** [comment]
Yes, Thanks !!
Indeed it was a typo. It works with `self.loggers[1]`


But I took the idea from the documentation of torch lightning which still stays 
`self.logger[0]` and not `self.loggers[0]` to access the indexed logger among multiple loggers. 
```ruby
class MyModule(LightningModule):
    def any_lightning_module_function_or_hook(self):
        some_img = fake_image()
        # Option 1
        self.logger.experiment[0].add_image("generated_images", some_img, 0)
        # Option 2
        self.logger[0].experiment.add_image("generated_images", some_img, 0)
```

Link: [https://pytorch-lightning.readthedocs.io/en/1.6.1/common/loggers.html](url)

Is this correct in the documentation?

**Comment by carmocca** [comment]
No. Would you like to open a PR with the fix?

**Comment by kamranisg** [comment]
Yes, I would like to.
