### ISSUE TITLE
Pytest failure w. Horovod

### ISSUE THREAD

**Issue by yhl48** [Lightning-AI/lightning#16235]
### Bug description

A lot of test cases fail due to erroneous module imports, one example being https://github.com/Lightning-AI/lightning/blob/c4ddc068c90d9913b0de97a01446bf287710526c/tests/tests_pytorch/utilities/migration/test_migration.py#L24

Just wondering if this is a temporary problem that is intentionally being overlooked? Been trying to fix #16188 but it is difficult to do so with so many test errors.

cc @borda

**Comment by awaelchli** [comment]
@yhl48 That's not intentional. I suspect there is something wrong with your local installation. Did you follow the instructions in the `tests/readme.md` file?

**Comment by yhl48** [comment]
Yes there was some problem with Horovod installation but the issue has been resolved now, thanks. A problem that persists is with backward compatibility testing with old checkpoints, in which there is always an ImportPathMismatchError
```
E   _pytest.pathlib.ImportPathMismatchError: ('simple_classif_training', '/home/user/pytorch-lightning/tests/legacy/simple_classif_training.py', PosixPath('/home/user/pytorch-lightning/tests/legacy/checkpoints/1.8.4/simple_classif_training.py'))
```

Could you please advise?

**Comment by carmocca** [comment]
@yhl48 I don't know what is causing that exactly, but you can open a draft PR with your changes so that we see the progress and CI shows any issues.

**Comment by Borda** [comment]
As Horovod was moved to a separate package from 2.0 let's assume this as resolved... :rabbit:
