### ISSUE TITLE
Deepspeed checkpoint cannot be loaded for my model

### ISSUE THREAD

**Issue by davidavdav** [Lightning-AI/lightning#16277]
### Bug description

I am training a [whisper](https://huggingface.co/docs/transformers/v4.25.1/en/model_doc/whisper#transformers.WhisperForConditionalGeneration) model using the lightning trainer.  If I add the option `strategy="deepspeed_stage_3_offload"` to `pytorch_lightning.Trainer()`, then `trainer.fit()` goes well, but the checkpoint is saved in a way that I can't load. 

Using the file `zero_to_fp32.py` in the saved checkpoint directory to produce a model results in an un-loadable file. 

Using [this script](https://pytorch-lightning.readthedocs.io/en/latest/advanced/model_parallel.html#collating-single-file-checkpoint-for-deepspeed-zero-stage-3) loading the produced model gives this error:
```
RuntimeError: Error(s) in loading state_dict for Whisper:
        Missing key(s) in state_dict: "model.proj_out.weight". 
```

See also the discussion in this [closed issue](https://github.com/Lightning-AI/lightning/issues/10964). 

### How to reproduce the bug

```python
from transformers import WhisperForConditionalGeneration
import pytorch_lightning as pl

class Whisper(pl.LightningModule):
    def __init__(self, model)
        super().__init__()
        self.model = model

   ...



model_card = "openai/whisper-base"
model = WhisperForConditionalGeneration.from_pretrained(model_card)

trainer = pl.Trainer(accelerator='gpu', precision=16, strategy="deepspeed_stage_3_offload")
trainer.fit(model=whisper, train_dataloaders=...)

With a proper data loader, train_step() etc.
```

### Error messages and logs

```
RuntimeError: Error(s) in loading state_dict for Whisper:
        Missing key(s) in state_dict: "model.proj_out.weight". 
```

### Environment

* CUDA:
	- GPU:
		- NVIDIA GeForce RTX 3090
	- available:         True
	- version:           11.7
* Lightning:
	- lightning-utilities: 0.5.0
	- pytorch-lightning: 1.8.6
	- torch:             1.13.0
	- torchaudio:        0.13.1
	- torchmetrics:      0.11.0
* Packages:
	- aiohttp:           3.8.3
	- aiosignal:         1.2.0
	- antlr4-python3-runtime: 4.8
	- anyio:             3.6.2
	- appdirs:           1.4.4
	- argon2-cffi:       21.3.0
	- argon2-cffi-bindings: 21.2.0
	- asttokens:         2.0.8
	- async-timeout:     4.0.2
	- attrs:             22.1.0
	- audioread:         3.0.0
	- babel:             2.10.3
	- backcall:          0.2.0
	- beautifulsoup4:    4.11.1
	- bitarray:          2.6.1
	- bleach:            5.0.1
	- certifi:           2022.9.24
	- cffi:              1.15.1
	- charset-normalizer: 2.1.1
	- click:             8.1.3
	- colorama:          0.4.6
	- comm:              0.1.2
	- cython:            0.29.32
	- datasets:          2.6.1
	- debugpy:           1.6.4
	- decorator:         5.1.1
	- deepspeed:         0.7.7
	- defusedxml:        0.7.1
	- dill:              0.3.5.1
	- distlib:           0.3.6
	- docopt:            0.6.2
	- entrypoints:       0.4
	- evaluate:          0.4.0
	- executing:         1.1.1
	- fairseq:           1.0.0a0+d6855ba
	- fastjsonschema:    2.16.2
	- ffmpeg-python:     0.2.0
	- filelock:          3.8.0
	- flashlight:        1.0.0
	- frozenlist:        1.3.1
	- fsspec:            2022.10.0
	- future:            0.18.2
	- gitdb:             4.0.9
	- gitpython:         3.1.29
	- hjson:             3.1.0
	- huggingface-hub:   0.10.1
	- hydra-core:        1.0.7
	- idna:              3.4
	- importlib-metadata: 5.2.0
	- importlib-resources: 5.10.0
	- ipykernel:         6.19.4
	- ipython:           8.5.0
	- ipython-genutils:  0.2.0
	- ipywidgets:        8.0.3
	- jedi:              0.18.1
	- jinja2:            3.1.2
	- jiwer:             2.5.1
	- joblib:            1.2.0
	- jsonschema:        4.17.1
	- julia:             0.5.7
	- jupyter:           1.0.0
	- jupyter-client:    7.4.8
	- jupyter-console:   6.4.4
	- jupyter-core:      5.1.0
	- jupyter-events:    0.5.0
	- jupyter-server:    2.0.4
	- jupyter-server-terminals: 0.4.3
	- jupyterlab-pygments: 0.2.2
	- jupyterlab-widgets: 3.0.4
	- lark:              0.11.3
	- levenshtein:       0.20.2
	- librosa:           0.9.2
	- lightning-utilities: 0.5.0
	- llvmlite:          0.39.1
	- lxml:              4.9.1
	- markupsafe:        2.1.1
	- matplotlib-inline: 0.1.6
	- mistune:           2.0.4
	- more-itertools:    9.0.0
	- multidict:         6.0.2
	- multiprocess:      0.70.13
	- multiprocessing-logging: 0.3.3
	- nbclassic:         0.4.8
	- nbclient:          0.7.2
	- nbconvert:         7.2.7
	- nbformat:          5.7.1
	- nest-asyncio:      1.5.6
	- ninja:             1.11.1
	- notebook:          6.5.2
	- notebook-shim:     0.2.2
	- num2words:         0.5.12
	- numba:             0.56.4
	- numpy:             1.23.4
	- nvidia-cublas-cu11: 11.10.3.66
	- nvidia-cuda-nvrtc-cu11: 11.7.99
	- nvidia-cuda-runtime-cu11: 11.7.99
	- nvidia-cudnn-cu11: 8.5.0.96
	- omegaconf:         2.0.6
	- packaging:         21.3
	- pandas:            1.5.1
	- pandocfilters:     1.5.0
	- parso:             0.8.3
	- pexpect:           4.8.0
	- pickleshare:       0.7.5
	- pillow:            9.2.0
	- pip:               20.0.2
	- pkg-resources:     0.0.0
	- pkgutil-resolve-name: 1.3.10
	- platformdirs:      2.5.4
	- pooch:             1.6.0
	- portalocker:       2.6.0
	- prometheus-client: 0.15.0
	- prompt-toolkit:    3.0.31
	- protobuf:          3.20.1
	- psutil:            5.9.3
	- ptyprocess:        0.7.0
	- pure-eval:         0.2.2
	- py-cpuinfo:        9.0.0
	- pyarmor:           7.7.0
	- pyarrow:           10.0.0
	- pycparser:         2.21
	- pydantic:          1.10.4
	- pygments:          2.13.0
	- pykaldi:           0.2.2
	- pyparsing:         3.0.9
	- pyrsistent:        0.19.2
	- python-dateutil:   2.8.2
	- python-json-logger: 2.0.4
	- pytorch-lightning: 1.8.6
	- pytz:              2022.5
	- pyyaml:            6.0
	- pyzmq:             24.0.1
	- qtconsole:         5.4.0
	- qtpy:              2.3.0
	- rapidfuzz:         2.13.7
	- regex:             2022.9.13
	- requests:          2.28.1
	- resampy:           0.4.2
	- responses:         0.18.0
	- sacrebleu:         2.3.1
	- sacremoses:        0.0.53
	- scikit-learn:      1.2.0
	- scipy:             1.9.3
	- send2trash:        1.8.0
	- setproctitle:      1.3.2
	- setuptools:        44.0.0
	- six:               1.16.0
	- smmap:             5.0.0
	- sniffio:           1.3.0
	- soundfile:         0.11.0
	- soupsieve:         2.3.2.post1
	- spraaklab-text:    0.1.0
	- stack-data:        0.5.1
	- tabulate:          0.9.0
	- tensorboardx:      2.5.1
	- terminado:         0.17.1
	- text-unidecode:    1.3
	- threadpoolctl:     3.1.0
	- tinycss2:          1.2.1
	- tokenizers:        0.13.1
	- torch:             1.13.0
	- torchaudio:        0.13.1
	- torchmetrics:      0.11.0
	- tornado:           6.2
	- tqdm:              4.64.1
	- traitlets:         5.8.0
	- transformers:      4.25.1
	- transitions:       0.9.0
	- typing-extensions: 4.4.0
	- urllib3:           1.26.12
	- uvloop:            0.17.0
	- virtualenv:        20.17.0
	- wcwidth:           0.2.5
	- webencodings:      0.5.1
	- websocket-client:  1.4.2
	- websockets:        10.4
	- wheel:             0.38.4
	- whisper:           1.0
	- widgetsnbextension: 4.0.4
	- worderrorrate:     0.1.1
	- xxhash:            3.1.0
	- yarl:              1.8.1
	- zipp:              3.10.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.8.10
	- version:           #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022

cc @awaelchli

**Comment by davidavdav** [comment]
Yes, sorry about that, too pre-occupied with my models...

**Comment by awaelchli** [comment]
Thanks for reporting. We have several similar issues (e.g., #15694), and will look at deepspeed checkpoint loading as a whole very soon.

**Comment by mileseverett** [comment]
Is there any update on this?

**Comment by tbright17** [comment]
Is there any update on this?

**Comment by MaveriQ** [comment]
@awaelchli I have a similar, but not exactly the same, problem. 

The issue I am facing is to be able to continue training (with deepspeed), after loading a checkpoint that was saved with deepspeed. I am putting it here so that when you look into deepspeed integration with lightning, you can have a look at this issue as well. Thanks

**Comment by awaelchli** [comment]
Fixed in deepspeed:  https://github.com/microsoft/DeepSpeed/pull/3825
