### ISSUE TITLE
save_on_train_epoch_end=True same behavior as save_on_train_epoch_end=False

### ISSUE THREAD

**Issue by DianeBouchacourt** [Lightning-AI/lightning#16284]
### Bug description

I believe setting `save_on_train_epoch_end=True` still runs checkpointing after the validation loop.

I have put a breakpoint in the module function `on_save_checkpoint()` and it is called only after validation even with `save_on_train_epoch_end=True`. 
Also I have written my own class to debug by looking into on_train_epoch_end function:
```py
class MyCKPT(ModelCheckpoint):
    def on_train_epoch_end(self, trainer, pl_module) -> None:
        """Save a checkpoint at the end of the training epoch."""
        if not self._should_skip_saving_checkpoint(trainer) and self._save_on_train_epoch_end:
            monitor_candidates = self._monitor_candidates(trainer)
            if self._every_n_epochs >= 1 and (trainer.current_epoch + 1) % self._every_n_epochs == 0:
                self._save_topk_checkpoint(trainer, monitor_candidates)
            self._save_last_checkpoint(trainer, monitor_candidates)
```
Similarly trying both `save_on_train_epoch_end=True` and `save_on_train_epoch_end=False`, the above function is called once validation is ran. 

I use version '1.6.0'

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by gavrieladler** [comment]
Hi, we are seeing similar behavior (version 1.7.7, trying to make the time to check in 1.9.0). We switched from running checkpointing every validation (`save_on_train_epoch_end=False`) to running checkpointing only on epoch end (`save_on_train_epoch_end=True`), and our `on_save_checkpoint` callbacks were, as a result, no longer triggered.

**Comment by awaelchli** [comment]
Sorry for the late response. This has been fixed a while ago. Can't pinpoint in which commit exactly, because it's so long ago. But let me know if you still see issues. Thanks :)
