### ISSUE TITLE
Fix autodoc build warnings for Fabric API reference

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#16316]
### 📚 Documentation

In our DeepSpeed strategy, we have conditional imports like this:

```py
if TYPE_CHECKING:
    import deepspeed

def some_method(x: `deepspeed.something"):
    ...

```

Sphinx autodoc does not like that. There are warnings when we generate the api docs:

```
WARNING: Cannot resolve forward reference in type annotations of "lightning_fabric.plugins.precision.DeepSpeedPrecision.backward": name 'deepspeed' is not defined
[960](https://github.com/Lightning-AI/lightning/actions/runs/3878948627/jobs/6615629448#step:8:961)
WARNING: Cannot resolve forward reference in type annotations of "lightning_fabric.strategies.DeepSpeedStrategy.setup_module": name 'deepspeed' is not defined
[961](https://github.com/Lightning-AI/lightning/actions/runs/3878948627/jobs/6615629448#step:8:962)
WARNING: Cannot resolve forward reference in type annotations of "lightning_fabric.strategies.DeepSpeedStrategy.setup_module_and_optimizers": name 'deepspeed' is not defined
[962](https://github.com/Lightning-AI/lightning/actions/runs/3878948627/jobs/6615629448#step:8:963)
WARNING: Cannot resolve forward reference in type annotations of "lightning_fabric.strategies.XLAStrategy.process_dataloader": name 'MpDeviceLoader' is not defined
[963](https://github.com/Lightning-AI/lightning/actions/runs/3878948627/jobs/6615629448#step:8:964)
/home/runner/work/lightning/lightning/docs/source-pytorch/fabric/api/api_reference.rst:78:<autosummary>:1: ERROR: 
```

In #16291 we had to exclude these classes from the API reference to make the build pass. We need to figure out a way to either fix the reference errors or ignore them.

cc @borda @carmocca @justusschock @awaelchli

**Comment by baskrahmer** [comment]
Disabling the -W flag in the sphinx-build command should make the build pass. The problem of this approach is that by doing so, potential other warnings could be missed by the CI, which is probably why this setting is turned on right now.

A solution for this could be setting the lowercase -w flag which writes all warnings to a file, and then in a separate GH workflow check if there are unexpected warnings in this file.

Ideally a [setting like this](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-suppress_warnings) could be used to filter warnings out using just Sphinx and without custom logic, but I could not get something like this to work. Also other settings in the Sphinx config file didn't help.

@awaelchli any thoughts on this?

**Comment by awaelchli** [comment]
Thanks for looking into it. I think that unless absolutely necessary, we would prefer to raise all warnings without ignoring them. This is because more often than not, they reveal real issues that should be fixed. Nonetheless, I'll check out your PR to see what could be done. Thanks for exploring these solutions.
