### ISSUE TITLE
resume training falid

### ISSUE THREAD

**Issue by ZHAIXINGZHAIYUE** [Lightning-AI/lightning#16362]
### Bug description

resume traning failed, when every_n_train_steps is equal to val_check_interval 

### How to reproduce the bug

```python
checkpoint_callback = ModelCheckpoint(
        ***
        every_n_train_steps=config['val_check_interval'],
    )
    trainer = pl.Trainer(
        ***
        val_check_interval=config['val_check_interval'],

    )
```
```


### Error messages and logs

```
    def validation_epoch_end(self, outputs):
        # pdb.set_trace()
        imgs = np.vstack(outputs) 

  File "/data_local/trainer.py", line 1342, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/data_local//train.py", line 90, in validation_epoch_end
    imgs = np.vstack(outputs)

outputs is empty
```


### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>


### More info

_No response_

**Comment by awaelchli** [comment]
Closing due to lack of provided information. 

If `validation_epoch_end` doesn't receive outputs, it is probably because none were returned in the `validation_step`.
