### ISSUE TITLE
Typo breaks mlflow logger in 1.9.0

### ISSUE THREAD

**Issue by markdjwilliams** [Lightning-AI/lightning#16411]
### Bug description

This [line](https://github.com/Lightning-AI/lightning/blob/898a236681def29aec9ce77e02fc5a15dd5d9cb3/src/pytorch_lightning/loggers/mlflow.py#L250) of code appears to be broken in 1.9.0 as it erroneously passes the value of the parameter where it should be providing the name:

```py
params_list.append(Param(key=v, value=v))
```

This should instead likely be:

```py
params_list.append(Param(key=k, value=v))
```

### How to reproduce the bug

```
from collections import OrderedDict
from lightning.pytorch.loggers import MLFlowLogger

params = OrderedDict()
params["a"] = 1

MLFlowLogger().log_hyperparams(params)
```

### Error messages and logs

```
TypeError: expected string or bytes-like object
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0): 1.9.0
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux): Linux
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source): source
#- Running environment of LightningApp (e.g. local, cloud): local
```

</details>

cc @borda

**Comment by awaelchli** [comment]
@markdjwilliams Great that you spotted it. A PR with the fix would be greatly appreciated if you are interested :)

**Comment by markdjwilliams** [comment]
Thank you for taking a look. I'm not sure if there's any test coverage here, but there's a chance that this should even be:

```
params_list.append(Param(key=k, value=str(v)))
```

.... as I can see that mlflow's `Param` class does seem to expect to be working with only string values:

https://github.com/mlflow/mlflow/blob/2487179a9f239024667946e7d31706a91f2536b8/mlflow/entities/param.py

https://github.com/mlflow/mlflow/blob/2487179a9f239024667946e7d31706a91f2536b8/mlflow/utils/autologging_utils/client.py

**Comment by awaelchli** [comment]
This code was added in this PR: #15915
Let's ask to double check:
@schmidt-jake Have you used the code with different types for these parameters? Would you mind quickly reviewing the bugfix PR from @BrianPulfer https://github.com/Lightning-AI/lightning/pull/16418

**Comment by Borda** [comment]
@BrianPulfer mind commenting here so we can sign the issue to you? :otter:

**Comment by BrianPulfer** [comment]
> @BrianPulfer mind commenting here so we can sign the issue to you? otter

Yes sure!

**Comment by awaelchli** [comment]
@schmidt-jake There isn't a "formal" way through GitHub to request your review. If you agree with the change, then we will merge it after adding a test. There was also a question from https://github.com/Lightning-AI/lightning/issues/16411#issuecomment-1387587525 whether the value should be converted to string. But I think that's only necessary for unsupported types. This can be addressed separately if needed.
