### ISSUE TITLE
Drop Python 3.7 support

### ISSUE THREAD

**Issue by akihironitta** [Lightning-AI/lightning#16415]
### Outline & Motivation

One of the main reasons we've supported 3.7 is, AFAIK, because Google Colab had 3.7 as its default runtime. Now that Google Colab upgraded the Python version to 3.8, we could start considering removal of our 3.7 support.

### Additional context

References:
- https://github.com/googlecolab/colabtools/issues/3246
- https://github.com/pytorch/pytorch/issues/80513
  - Maybe, we should wait for PyTorch to drop 3.7 support first?

cc @carmocca @akihironitta @borda @lantiga

**Comment by carmocca** [comment]
I would wait until tue release after the 27th of June: https://endoflife.date/python

**Comment by akihironitta** [comment]
Sure, we can keep 3.7 until its final patch release. Just wanted to bring this up as we're free to drop the support now as we follow NEP29. https://pytorch-lightning.readthedocs.io/en/stable/versioning.html#python-support

PyTorch 2.0 plans to drop 3.7 support (https://github.com/pytorch/pytorch/issues/80513#issuecomment-1396166181), so to me, it sounds reasonable for us to do so, too

**Comment by carmocca** [comment]
PyTorch dropped 3.7 with https://github.com/pytorch/pytorch/pull/93155, so we can move forward with this.
