### ISSUE TITLE
DDP stuck

### ISSUE THREAD

**Issue by brian-gyh** [Lightning-AI/lightning#16417]
### Bug description

After epoch 0, epoch 1 was stuck.
![image](https://user-images.githubusercontent.com/104077097/213119487-81a00537-2bce-4cc7-bff2-de1af45ba7db.png)

### How to reproduce the bug

```python
https://github.com/bytedance/music_source_separation

This problem will occur after modifying this project to adapt to lightning 1.8.6.If you remove the @rank_zero_only(line 171) in "https://github.com/bytedance/music_source_separation/blob/master/bytesep/callbacks/musdb18.py" will not get stuck.
```

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0): 1.8.6
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10):  1.10.0
#- Python version (e.g., 3.9): 3.8.13
#- OS (e.g., Linux): linux
#- CUDA/cuDNN version: cuda11.3_cudnn8.2.0_0
#- GPU models and configuration: ddp, gpus=2
#- How you installed Lightning(`conda`, `pip`, source): pip 
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
Yes, absolutely. You can do

```py
if trainer.global_rank == 0:
    # only on process 0 print info
    print(...)
    logging.log(...)
```

This is the recommended way :))

**Comment by brian-gyh** [comment]
Ok, thank you for your suggestion. I'll try it.

**Comment by brian-gyh** [comment]
Hi, thank you very much for your suggestion. It's no problem. However, I'm still curious about why it can run normally in version 1.2.1, but it will get stuck after it is adapted to version 1.8.6, because the program musdb.py has no change in the two versions.
