### ISSUE TITLE
Training stuck at logging?

### ISSUE THREAD

**Issue by SpaceHunterInf** [Lightning-AI/lightning#16421]
Greetings,

I've run into this issue multiple times. In my script, I load, train, and save the model multiple times. I do this routine about 10 times. However, at some random point, the script just stucks. And it always stuck at this point after the missing file logger. 
![image](https://user-images.githubusercontent.com/30568250/213245004-5e848cf3-9fa1-498d-a469-62bfd6d52838.png)

In addition, I can no longer do anything at this point. The Ctrl+C will not terminate the process either. Neither does the programme give me any error message. Do you have any clue about this?

I am running on version 1.7.7, using strategy ddp. I am on Linux with 2 1080Ti, cuda 12.0.

Thank you very much.

**Comment by awaelchli** [comment]
@SpaceHunterInf It looks like there might be a race condition of some sort. I suggest to add a `trainer.strategy.barrier()` at the end or beginning of your loop when a new stage of training begins. Also, you could double check that the logging folder is correct by printing `trainer.log_dir` and making sure this always is the same folder across all processes per training stage.
