### ISSUE TITLE
WandbLogger should have a log_dir method

### ISSUE THREAD

**Issue by turian** [Lightning-AI/lightning#16461]
### Description & Motivation

When you are instrumenting lightning code with multiple possible loggers, the logical place to put it is `log_dir` not `save_dir`. However, WandbLogger doesn't have `log_dir`, which means your code gets flaggy if you want to support it.

### Pitch

Consistent logging API is one of the thorns in lightning's side. log_dir is the obvious log dump location so WandbLogger should expose that property.

Our primary logger in Wandb, and we use the log_table method with media objects. This doesn't exist in CSV and Tensorboard. We save the media to disk. Right now our code is like this:

```
        if self.args.logger == "wandb":
            outdir = self.logger.save_dir
        else:
            outdir = self.logger.log_dir
```

and we want our code to be like this:

```
        outdir = self.logger.log_dir
```

### Alternatives

Add `if` statements to detect the logger each time you log something without a `log_` call.

**Comment by awaelchli** [comment]
@turian For now, you can use `trainer.log_dir` to avoid the if-else checks. The inconsistency will be resolved as part of the work in #14188.
