### ISSUE TITLE
Support `Fabric.save/load_hyperparameters`

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#16478]
### Description & Motivation

We introduced `fabric.save/load` to save full checkpoints through the strategies. However, sometimes it is more convenient to save and load metadata separately (on every rank) before the full training state gets restored. For example, for inference or for instantiating a model before training.

See for example the usage of model instantiation and handling of configuration in nano GPT: https://github.com/Lightning-AI/nanoGPT

### Pitch

Support the following on the Fabric object:

```py
def save_hyperparameters(self, path, hparams: dict) -> None:
    if rank == 0:
        torch.save(obj, hparams)

def load_hyperparameters(self, path) -> dict:
    return torch.load(path)
```

### Alternatives

Let user handle hyperparameters manually.

### Additional context

Idea spawned in discussion with @justusschock 

cc @borda @tchaton @justusschock @awaelchli @carmocca

**Comment by carmocca** [comment]
What hparams are we talking about? If we don't recommend subclassing the Fabric object in the future, then what's the benefit of this?

**Comment by justusschock** [comment]
@carmocca Imagine something like `LightningModule.load_from_checkpoint` but with fabric using deepspeed or fsdp.
There are two kinds of parameters we need to save here:
- The actual (sharded) weights which are different per rank
- The parameters for instantiate classes (init args for model and optimizer)

The latter one is the same for all ranks and should be loaded independently of the actual sharded checkpoint to enable something like this:


```python
hyper_params = fabric.load_hyperparameters(ckpt_path) # only loads init args as they are in a separate file, will have same result on each rank
model = MyFancyModel(**hyper_params['model'])
optimizer = AdamW(**hyper_params['optimizer'], model.parameters())

... # do setup etc so that after this model is sharded already

state = {'model': model, 'optimizer': optimizer}
fabric.load(ckpt_path, state) # will load actual weights and optimizer states, might be different on each rank with sharded strategies
```

**Comment by awaelchli** [comment]
@justusschock I don't yet know how we would handle ckpt_path. For some strategies, this might be a file but for others, it might be a folder. Should saving this side-by-side with the regular checkpoint be left to the user? Or should it be possible to give the exact same `ckpt_path` to both save methods?
