### ISSUE TITLE
Method to check whether a Fabric model was set up already

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#16484]
### Description & Motivation

Currently, if you pass a model to Fabric.setup() that has already been wrapped/set up, you get an error. This is currently expected, because there are several reasons and edge cases where this would be invalid usage. However, the only way to check whether a model is set up already is with an instance check on a protected class:

```py
already_set_up = isinstance(model, _FabricModel)
```

There are valid use case where such a check comes up. For example:

You build a trainer that has a fit method with the following implementation.

```py
model, optimizer = fabric.setup(model, optimizer)
for epoch in range(epochs):
    self.train(model, optimizer)
    self.validate(model)
```

This trainer has a validate() method that can either be called separately, or internally within the fit loop. Hence, the validate() method needs to check whether the model was already set up.

### Pitch

Introduce `Fabric.is_setup()`, or function `is_setup()`.

```py
assert not is_setup(model)
model = fabric.setup(model)
assert is_setup(model)
```

### Alternatives

There are two alternatives:

**Alternative 1**
Make the `Fabric.setup()` a no-op when a model is passed in that was already set up. However, there are problematic edge cases, that break the contract with the strategies. For example, when setup is called with a model that is already set up, but an optimizer that is not set up yet:
```py
model = setup(model)
model = setup(model, optimizer)  # what should happen?
```
OR
If a model is set up twice but with different optimizers
```py
model, optimizer1 = setup(model, optimizer1)
model, optimizer2 = setup(model, optimizer2)
```

**Alternative 2**
The example I gave with the shared validation loop could also be re-written like this:

```py
def train(model, optimizer):
    ...

def validate(model):
    model = fabric.setup(model)
    return self._validate(model)
    
def _validate(model):
    # this assumes the passed in model is already set up

def fit(model):
    model, optimizer = fabric.setup(model, optimizer)
    for epoch in range(epochs):
        self.train(model, optimizer)
        self._validate(model)  # call _validate(), not validate()

```

### Additional context

cc @borda @tchaton @justusschock @awaelchli @carmocca @pietrolesci

**Comment by carmocca** [comment]
Would a property work too?

Do we need separate `is_*_setup` functions for the different components that can be set-up?

**Comment by awaelchli** [comment]
A property wouldn't work. You wouldn't be able to check `model.is_setup()` if model is an nn.Module (and therefore not set up). It would either have to be a function

```py
def is_setup(module) -> bool:
    return isinstance(module, _FabricModule)
```
or a (static) method on the Fabric object:
```py
def is_setup(self, module) -> bool:
    return isinstance(_FabricModule)
```

**Comment by Atharva-Phatak** [comment]
Is this open can I take this up ? Also amazing work with fabric 📦

**Comment by awaelchli** [comment]
Thank you @Atharva-Phatak! Happy to let you take this. We need to decide whether to make this a function or a method. What are your thoughts? Also @justusschock @carmocca I would make it a function.

On another note, I'm generally not so pleased about the name of "setup". We use it as an action/verb, but it is backwards because in English, the verb is actually spelled "set up", and "setup" is the noun. This makes it awkward when using Fabric.setup, but is even more cringe when we have something like `is_setup` as a function name 😅

**Comment by Atharva-Phatak** [comment]
A function would be much better since it would be independent of the fabric class. For the name, may I suggest the name ```check_state``` ?

**Comment by carmocca** [comment]
I agree with choosing a function. I wouldn't go with changing the "setup" name. It's widely used in software projects, including this one. It's familiar even if it's not the most natural English name to read

**Comment by justusschock** [comment]
I also agree with this being a function. Similar to @carmocca , I'd keep the `setup` terminology.

@Atharva-Phatak with state usually we mean something different as this isn't really about the internal state but more whether a specific function call has already happened. 
Also it should be something with `is_X` so that returning a bool actually makes sense.

**Comment by pietrolesci** [comment]
Hi there, my two cents: `lightning.fabric.is_wrapped`.

I think that a module-level function (like in `torch.is_tensor`) would be great and I think that `is_wrapped` is a pretty explanatory name for it since we are wrapping `nn.Module`s in Fabric (also, wrapping in "fabric" has also a nice physical sound to it :)).

```python
def is_wrapped(module: Union[nn.Module, _FabricModule) -> bool:
    ...
```

**Comment by awaelchli** [comment]
I think this is a good alternative too. I like it.

**Comment by Atharva-Phatak** [comment]
@awaelchli Sounds good. I will get cracking on this.

**Comment by Atharva-Phatak** [comment]
@awaelchli Should I also include this check in the Fabric class in the train or validate function ? or let the user check it?

**Comment by awaelchli** [comment]
There isn't really much to do in the fabric class. It is primarily for the user. Maybe we have some internal places where it can be used, but at the end of the day it's just an instance check disguised as a function  :))
