### ISSUE TITLE
Expose process group backend choice in Fabric CLI

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#16507]
### Description & Motivation

Currently, the backend for the process group can be chosen via the Strategy, for example:

```py
fabric = Fabric(strategy=DDPStrategy(process_group_backend="gloo"), ...)
```

However, this hardcoded setting prevents one to specify a different strategy from the CLI:

```bash
# fails, not allowed
lightning run model --strategy deepspeed train.py 
```

We don't currently allow the CLI to overwrite anything that is not the default in the Fabric constructor.
This is a request from an early Fabric tester.

### Pitch

Expose the process group backend as a CLI argument:

```bash
lightning run model --strategy ddp --pg_backend gloo train.py 
```

Pro:
- addresses above use case
Con:
- Not compatible with all strategies. Connector would get more complex and error prone for validation

### Alternatives

**Alternative 1:**
Could also expose it as explicit strategy shorthand names:

```bash
lightning run model --strategy ddp train.py 
lightning run model --strategy ddp_gloo train.py 
lightning run model --strategy ddp_nccl train.py 
```

Pro:
- No compatibility testing required, as names are explicit
Con:
- Number of names increases two-fold due to the combinations

**Alternative 2:**
Expose it through an environment variable as we have done before (but removed it because it was unused and undocumented)

cc @borda @carmocca @justusschock @awaelchli

**Comment by awaelchli** [comment]
I would wait with this, until we see more use cases where this surfaces as an inconvenience/need.

**Comment by carmocca** [comment]
If we choose this over a package that supports instantiating classes (hydra, jsonargparse, ...) then I would prefer "Alternative 1"
