### ISSUE TITLE
Latest versions not available on Conda

### ISSUE THREAD

**Issue by DomInvivo** [Lightning-AI/lightning#16522]
### Bug description

Versions 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6 and 1.9.0 are missing from [conda](https://anaconda.org/conda-forge/pytorch-lightning/files). See [the PR](https://github.com/conda-forge/pytorch-lightning-feedstock/pull/116) for the conda package of lightning.

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
Thanks for reporting. @Borda maybe could you double check the linked PR on conda. Thx

**Comment by hadim** [comment]
I opened a new PR on the feedstock and added the appropriate dep bumps at https://github.com/conda-forge/pytorch-lightning-feedstock/pull/117

Please review and merge.

**Comment by Borda** [comment]
Hello, an apology for the confusion and delays from our side... at the end, we have finished adding all `1.8.{1,2,3,4,5,6}` releases and also fixed/merged https://github.com/conda-forge/pytorch-lightning-feedstock/pull/116 and https://github.com/conda-forge/pytorch-lightning-feedstock/pull/115 Anyway, thank you for all your effort and help! :rabbit:
