### ISSUE TITLE
Proper extraction of `state_dict` for `fsdp` strategy

### ISSUE THREAD

**Issue by SpirinEgor** [Lightning-AI/lightning#16526]
### Outline & Motivation

For now, [`FSDP`](https://github.com/Lightning-AI/lightning/blob/master/src/pytorch_lightning/strategies/fsdp.py#L74) uses default implementation from `Strategy` to get model state dict: [`Strategy.lightning_module_state_dict`](https://github.com/Lightning-AI/lightning/blob/master/src/pytorch_lightning/strategies/strategy.py#L450). But, like creating an optimizer, this returns an empty ordered dict. This affects, for example, the ModelCheckpoint callback, there is no model weight in the saved checkpoints.

### Pitch

We need a custom implementation to get model state dict when the user uses the `FSDP` strategy (add the `lightning_module_state_dict` method into the `FSDPStrategy` class). I found 2 workarounds, first one is pretty straightforward and replicates the optimizer initialization behavior:
```python
def lightning_module_state_dict(self) -> Dict[str, Any]:
    """Returns model state."""
    assert self.lightning_module.trainer.model is not None
    wrapped_state_dict = self.lightning_module.trainer.model.state_dict()
    return {k.replace("_forward_module.", ""): v for k, v in wrapped_state_dict}
```

But I'm not sure if this is the correct way to get sharded state dict together. Following documentation from [PyTorch](https://pytorch.org/docs/stable/fsdp.html#torch.distributed.fsdp.FullyShardedDataParallel.state_dict), we need to use the `state_dict_type` context manager to unshard the model. This implementation should be like this:
```python
def lightning_module_state_dict(self) -> Dict[str, Any]:
    """Returns model state."""
    assert self.lightning_module.trainer.model is not None
    model = self.lightning_module.trainer.model
    full_state_dict_config = FullStateDictConfig(rank0_only=True)
    with FSDP.state_dict_type(model, StateDictType.FULL_STATE_DICT, full_state_dict_config):
        wrapped_state_dict = sharded_module.state_dict()
    return {k.replace("_forward_module.", ""): v for k, v in wrapped_state_dict}
```

### Additional context

1. For both suggested implementations, I remove the prefix `_forward_module` from the state dict. This is due to wrapping the user model into `_LightningModuleWrapperBase`.
2. For the second option there is also an option to specify offloading into the CPU. This is useful when a model is too large to fit on a single GPU.

cc @awaelchli @carmocca

**Comment by SpirinEgor** [comment]
I did a little research about this problem. Appears that in version `1.9.0` this problem was handled by `DDPFullyShardedStrategy`: there are [special proxy class](https://github.com/Lightning-AI/lightning/blob/1.9.0/src/pytorch_lightning/strategies/fully_sharded.py#L43) and overridden [`lightning_module_state_dict`](https://github.com/Lightning-AI/lightning/blob/1.9.0/src/pytorch_lightning/strategies/fully_sharded.py#L153).

But after this, #16400 completely removes this class and #16490 only removes prefix, without proper workaround with sharded model.

I will make a PR to fix this 👌

**Comment by w2ex** [comment]
Hi, this is an import issue due to fairscale's fsdp being deprecated, and not being able to use fsdp alongside model checkpointing makes it useless. So thank you @SpirinEgor for your PR. Do we know when this correction is gonna be available in a stable release ?

**Comment by SpirinEgor** [comment]
Hi!
Well, you can see our discussion in PR, there are some open questions.
I want to do well right away, but I don’t get the necessary feedback from the Lightning team 😞
I will make quick workaround, this should help with checkpointing in near future

**Comment by awaelchli** [comment]
Hey @SpirinEgor and @w2ex 

After the 2.0 release next week, I plan to dedicate some time to look into the open issues around FSDP and DeepSpeed. We can work together to get your PR over the finish line and then we can cherry-pick it back into the 1.9.x (LTS) stable version as well. Sorry for the delay, because we are busy with the 2.0 efforts, and thank you for the patience!

**Comment by carmocca** [comment]
Relevant link on how to checkpoint with FSDP: https://github.com/pytorch/pytorch/blob/0a0f107b50e88df8b7c0f626b17156f86e63c1ca/torch/distributed/checkpoint/examples/fsdp_checkpoint_example.py
