### ISSUE TITLE
Support setup for torch DataPipes

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#16603]
### Description & Motivation

When working with torchdata's DataPipes in distributed settings, the user can use DataLoader2 to run the pipe with a specific [reading service](https://pytorch.org/data/beta/dataloader2.html#readingservice) that applies sharding of the data pipe correctly. For example:

```py
# multiprocessing in a single node
from torchdata.dataloader2 import DataLoader2
from torchdata.dataloader2 import PrototypeMultiProcessingReadingService

service = PrototypeMultiProcessingReadingService(num_workers=5)
dataloader = DataLoader2(datapipe, reading_service=service)

# distributed/multi-gpu/multi-node
from torchdata.dataloader2 import DistributedReadingService

service = DistributedReadingService()
dataloader = DataLoader2(datapipe, reading_service=service)
```

However, this does not mix well with Lightning as the user would have to change the reading service when switching from one strategy to another.

### Pitch

Similar to what we do with the injection of the DistributedSampler for the regular DataLoader, add the reading service for the datapipe automatically for the user.
```py

fabric = Fabric(...)

dataloader = DataLoader2(datapipe)

# sets up the reading service for distributed training
dataloader = fabric.setup_dataloader(dataloader)

```

### Additional context

If you are interested in learning more about torchdata, here is a good [YouTube video by PyTorch](https://www.youtube.com/watch?v=65DvI3YrFW8) that introduces the main concepts an values.

cc @borda @justusschock @awaelchli @carmocca

**Comment by awaelchli** [comment]
In Lightning Trainer yes, because it supports arbitrary iterables. But we don't have any correctness tests. In Fabric, the `setup_dataloaders()` method does not support DataLoader2 atm.

**Comment by np-22** [comment]
Is there any update or plan to support Dataloader2? Thanks!

**Comment by awaelchli** [comment]
The future of torchdata is very unclear. The maintenance has paused, here is the official statement: https://github.com/pytorch/data/issues/1196

I suggest we wait until we know about future plans. For now, users use datapipes/dataloader2 with Lightning by configuring them manually.
