### ISSUE TITLE
CI fails uploading coverage report

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#16617]
### Bug description

Codecov upload fails with the following message:

```
[2023-01-31T21:37:27.017Z] ['error'] There was an error running the uploader: Flags must consist only of alphanumeric characters, '_', '-', or '.' and not exceed 45 characters. Received ${COVERAGE_SCOPE},cpu,pytest,python3.10
```

This happens for all CPU runs (fabric, pytorch, app).

### How to reproduce the bug

See a recent run here:

https://github.com/Lightning-AI/lightning/actions/runs/4058544132/jobs/6985592303

cc @carmocca @akihironitta @borda

**Comment by awaelchli** [comment]
The error is confusing, because COVERAGE_SCOPE=lightning_fabric, so all flags follow the requirements in the error message.

**Comment by akihironitta** [comment]
I think it's literally `${COVERAGE_SCOPE}` 😆 I'm not too confident, but we need to replace it with `${{ env.COVERAGE_SCOPE }}`.

**Comment by Borda** [comment]
> we need to replace it with `${{ env.COVERAGE_SCOPE }}`

or replace it with outputs... :otter:

**Comment by awaelchli** [comment]
I just noticed another failure in the GPU CI for PL and Fabric:

https://dev.azure.com/Lightning-AI/lightning/_build/results?buildId=133485&view=logs&j=3f274fac-2e11-54ca-487e-194c91f3ae9f&t=52d5efce-740d-5403-d28f-0b2f846bfb92&l=229
```

==> Collecting reports
    + /__w/2/s/tests/tests_pytorch/coverage.xml bytes=603351
==> Appending environment variables
    + linux
    + azure
==> Uploading
    .url https://codecov.io/
    .query commit=d8cce4a6ee8eddf897537a156be857da8416e6f2&branch=HEAD&name=GPU-coverage&flags=gpu%2Cpytest&package=py2.1.12
    Gzipping contents..
    Compressed contents to 37363 bytes
    Pinging Codecov...
Error: Could not determine repo and owner
```

This might be tricky to fix since there is no indication of where it is looking for this information.

**Comment by Borda** [comment]
> This might be tricky to fix since there is no indication of where it is looking for this information.

just fixed it as it was missing `CODECOV_TOKEN` among secrets... :otter:
