### ISSUE TITLE
dependencies issue working with torch and pytorch_lightning. 

### ISSUE THREAD

**Issue by nkay28** [Lightning-AI/lightning#16654]
### Bug description

I have trouble getting all needed packages to be compatible to run ResNet transfer learning. I trying the import from one of the sample lightening notebooks anf got error. And then trying to install the recommended packages got following incompatibility issue.       
command: 
`! pip install --quiet "torchmetrics>=0.7, <0.12" "seaborn" "ipython[notebook]>=8.0.0, <8.9.0" "pytorch-lightning>=1.4, <1.9" "torchmetrics >=0.11.0" "setuptools==65.6.3" "pandas" "torchvision" "torch>=1.8.1, <1.14.0"
`
Issue: 
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 8.0.1 requires pydantic<1.8.0,>=1.7.1, but you have pydantic 1.10.4 which is incompatible.
spacy 3.0.1 requires pydantic<1.8.0,>=1.7.1, but you have pydantic 1.10.4 which is incompatible.
lightning 1.9.0.dev0 requires lightning-utilities<1.0,>=0.4.2, but you have lightning-utilities 0.3.0 which is incompatible.
conda-repo-cli 1.0.27 requires clyent==1.2.1, but you have clyent 1.2.2 which is incompatible.
conda-repo-cli 1.0.27 requires nbformat==5.4.0, but you have nbformat 5.7.0 which is incompatible.
```

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
@nkay28 You have torchmetrics specified twice, once with torchmetrics>=0.7, <0.12 and once with torchmetrics >=0.11.0. Also, I suggest to remove setuptools==65.6.3 which could limit the pip dep resolver.

**Comment by nkay28** [comment]
thank you very much. Resolved.

**Comment by nkay28** [comment]
Thank you very much. Resolved.
