### ISSUE TITLE
Native FSDP and MixedPrecision inconsistent behaviour

### ISSUE THREAD

**Issue by w2ex** [Lightning-AI/lightning#16687]
### Bug description

When using `MixedPrecisionPlugin` alongside `fsdp` (Fairscale), the memory is reduced as expected compared to full precision. However, when using `fsdp_native`, no memory gain is observed, as if the training is performed in full precision.

Running the code below on 2 RTX 3090, I observe in Full Prec, for both `fsdp` and `fsdp_native` a constant memory usage of 5515MiB * 2.
With `fsdp` and `MixedPrecisionPlugin` activated, the memory usage is 3457MiB * 2.
With `fsdp_native` and `MixedPrecisionPlugin`, the memory usage is 5515MiB * 2 (exactly the same as Full Prec)

This is an issue since `fsdp` being deprecated in favour of `fsdp_native`, it will lead to a regression for the maximum batch size for those using Fairscale FSDP up until now.

### How to reproduce the bug

```python
from torch import optim, nn, utils, Tensor
from torchvision.datasets import FakeData
from torchvision.transforms import ToTensor
import pytorch_lightning as pl
from pytorch_lightning.plugins.precision import MixedPrecisionPlugin
import timm


model = timm.create_model('resnet18', num_classes=10)

# define the LightningModule
class DummyModel(pl.LightningModule):
    def __init__(self, model, lr):
        super().__init__()
        self.model = model
        self.lr = lr
        self.loss_func = nn.CrossEntropyLoss()

    def training_step(self, batch, batch_idx):
        x, y = batch
        z = self.model(x)
        loss = self.loss_func(z, y)
        self.log("train_loss", loss)
        return loss

    def configure_optimizers(self):
        optimizer = optim.Adam(self.trainer.model.parameters(), lr=self.lr)
        return optimizer

pl_model = DummyModel(model, 1e-6)

dataset = FakeData(size=100000, transform=ToTensor())
train_loader = utils.data.DataLoader(dataset, batch_size=100)

trainer = pl.Trainer(limit_train_batches=1000, max_epochs=100, accelerator='gpu', strategy='fsdp_native', plugins=[MixedPrecisionPlugin(16, device='cuda')])
trainer.fit(model=pl_model, train_dataloaders=train_loader)
```

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): Trainer, LightningModule
#- PyTorch Lightning Version (e.g., 1.5.0): 1.9.0
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10): 1.13.1+cu117
#- Python version (e.g., 3.9): 3.9
#- OS (e.g., Linux): Linux
#- CUDA/cuDNN version: 11.7
#- GPU models and configuration: NVidia GeForce RTX 3080
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud): local
```

</details>

cc @awaelchli @carmocca

**Comment by awaelchli** [comment]
@w2ex This looks like a configuration/validation issue to me. With FSDP, you would need to set the `FSDPPrecision` plugin, not the regular `MixedPrecisionPlugin`. We can probably add an error/validation for this.

You should be able to validate this by just setting `precision=16` or `precision="bf16"` in the trainer rather than passing in the plugin object. And then you should see the memory reduction.

```py
trainer = pl.Trainer(limit_train_batches=1000, max_epochs=100, accelerator='gpu', strategy='fsdp_native', precision=16)
```

**Comment by awaelchli** [comment]
If you are interested in the code, here is why you saw this "silent" behavior:

https://github.com/Lightning-AI/lightning/blob/1288e4ccc4baf73d7b25f52a448685ac6c4f592a/src/lightning/pytorch/strategies/fsdp.py#L174-L180

**Comment by w2ex** [comment]
Indeed, this seems to solve the issue ! Sorry for creating the issue, I was not aware of the existence of `FSDPMixedPrecisionPlugin`.
Thanks for your quick answer.
