### ISSUE TITLE
Change the command to initialize DDP subprocess with Hydra

### ISSUE THREAD

**Issue by zihaozou** [Lightning-AI/lightning#16694]
### Description & Motivation

Hi, 

the current behavior to initialize DDP subprocesses with Hydra is [here](https://github.com/Lightning-AI/lightning/blob/accd2b9e61063ba3c683764043030545ed87c71f/src/lightning/fabric/strategies/launchers/subprocess_script.py#L159), which overrides the hydra.run.dir with os.getcwd(). 

This is assuming the os.getcwd() will return the output directory that Hydra assigned. However, since Hydra 1.2, Hydra will keep the cwd as the project directory by default. This command will result in logging the subprocess in the project directory. 

### Pitch

Logging the DDP subprocess correctly in the output directory created by Hydra

### Alternatives

use:
```
os_cwd = hydra.core.hydra_config.HydraConfig.get()['runtime']['output_dir']
os_cwd = f'"{os_cwd}"'

```
instead

cc @borda @justusschock @awaelchli

**Comment by awaelchli** [comment]
@zihaozou Thanks for the request.

I remember we had changed the behavior once around this (#11617) but had to revert it (#15737).
It looks like this is about the same thing, but I'm not sure.
