### ISSUE TITLE
Dockerfile with Jupyter Server cannot be established

### ISSUE THREAD

**Issue by bboyleonp666** [Lightning-AI/lightning#16728]
### Bug description

I tried to build a docker image following dockers/README.md with Jupyter Server.
But after creating the image, I found the Jupyter Server cannot be established.

### How to reproduce the bug

```python
$ git clone https://github.com/Lightning-AI/lightning.git
$ cd lightning
$ git checkout 1.9.1
$ docker build -t pytorch-lightning:v1.9.1 -f dockers/nvidia/Dockerfile --build-arg LIGHTNING_VERSION=1.9.1 .
$ docker run --rm -it --gpus=all -p 8888:8888 pytorch-lightning:v1.9.1
```

### Error messages and logs

```
# Error messages and logs here please
[C 08:01:01.863 NotebookApp] Bad config encountered during initialization: The 'contents_manager_class' trait of a NotebookApp instance expected a subclass of notebook.services.contents.manager.ContentsManager or jupyter_server.contents.services.managers.ContentsManage, not the JupytextContentsManager JupytextContentsManager.
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

### More info

Since I do not have PyTorch or PyTorch-Lightning pre-install, the environment script does not work for me.
But I am currently using **Ubuntu 20.04**

**Comment by bboyleonp666** [comment]
I have found one solution for this issue.
By replacing the `jupyter lab` with `jupyter notebook` in dockers/nvidia/Dockerfile, this problem will be solved.
Since _jupyter-lab_ is a more powerful tool than _jupyter-notebook_, I think it could be a good replacement to fix this issue.
And _ipywidgets_ is installed to fix the the dependency of jupyterlab.

This works fine in both _v1.9.0_ and _v1.9.1_, while other versions are not tested yet.

```
@@ -49,7 +49,8 @@ RUN \
    rm -rf lightning && \
    pip list

RUN pip install jupyterlab[all] -U
RUN pip install jupyterlab[all] -U && \
    pip install ipywidgets

ENV PYTHONPATH="/workspace"

@@ -63,4 +64,4 @@ RUN \
    python -c "import torch; assert torch.__version__.startswith('$TORCH_VERSION'), torch.__version__" && \
    python -c "import pytorch_lightning as pl; print(pl.__version__)"

CMD ["jupyter", "notebook", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root"]
CMD ["jupyter", "lab", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root"]
```

**Comment by voidful** [comment]
this issue can also be fixed by edit the config file manually https://github.com/Project-MONAI/MONAI/issues/5777#issuecomment-1359460325

**Comment by awaelchli** [comment]
@bboyleonp666 or @voidful anyone want to send a PR to update the instructions in our readme?
