### ISSUE TITLE
Unexpected DDP behaviour for slurm users using the interactive mode

### ISSUE THREAD

**Issue by zhjohnchan** [Lightning-AI/lightning#16730]
### Bug description

For slurm users using the `interactive` mode, the cluster just performs like a single machine. The DDP can not be initialized after `pytorch-lightning >= 1.8`.

### How to reproduce the bug

```
The DDP works in `pytorch-lightning<=1.7.7`:

>> srun --job-name=train --gres=gpu:4 -p p-A100 --pty bash
>> pip install pytorch-lightning==1.7.7
>> python main.py

and fails in `pytorch-lightning>=1.8.0`:

>> srun --job-name=train --gres=gpu:4 -p p-A100 --pty bash
>> pip install pytorch-lightning>=1.8.0
>> python main.py
```

### Error messages and logs

For `pytorch-lightning<=1.7.7`, it outputs
```
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4
```

and for `pytorch-lightning>=1.8.0`, it outputs
```
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

### More info

It might relate to the capture of the envoriment variables and could be fixed by recognizing the `interactive` mode.

cc @borda

**Comment by awaelchli** [comment]
@zhjohnchan Have you tried setting the job name to "bash"?

**Comment by awaelchli** [comment]
We should explicitly document this in a separate section how to use interactive mode.

**Comment by awaelchli** [comment]
@zhjohnchan Were you successful by setting the name?

**Comment by zhjohnchan** [comment]
@awaelchli Sorry for the late reply. Setting `job name` to `bash` fixed the problem.

Thanks for your help so much.

**Comment by xyniu1** [comment]
thanks for the answer! I was stuck on this for a long time before I found this solution.

Just out of curiosity, why is it necessary to set job name to bash?

**Comment by SebastienGardoll** [comment]
While the documentation of Pytorch Lightning of the version 2.5.0.post0 indicates that it works by naming the SLURM job "bash" or "interactive" ([here](https://lightning.ai/docs/pytorch/stable/clouds/cluster_advanced.html#interactive-mode)), it only works with the job name "interaction"!
