### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by pan24n** [Lightning-AI/lightning#16758]
### Bug description

When I run the autoencoder.py program in the pl_basics directory, I get the error:
Traceback (most recent call last):
  File "autoencoder.py", line 193, in <module>
    cli_main()
  File "autoencoder.py", line 188, in cli_main
    print(predictions[0])
TypeError: 'NoneType' object is not subscriptable

### How to reproduce the bug

```python
python autoencoder.py --trainer.accelerator 'gpu' --trainer.devices 2
```

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
@pan24n Sorry for the late response.
I verified that this will work with Lightning 2.0, and that the predictions get printed.
This is because in the new version, we change the default from ddp-spawn to ddp.
