### ISSUE TITLE
Introduce AimLogger

### ISSUE THREAD

**Issue by JustinGoheen** [Lightning-AI/lightning#16768]
### Description & Motivation

The feature request is to add a custom Logger to support [Aim](https://aimstack.io) users.

### Pitch

Add a custom Logger.

### Alternatives

Create as a Lightning component that is maintained outside of the core package.

cc @borda

**Comment by JustinGoheen** [comment]
please assign this to me if approved.

**Comment by tshu-w** [comment]
Hi, this is a duplicate of https://github.com/Lightning-AI/lightning/issues/13176 and https://github.com/Lightning-AI/lightning/issues/3985.

**Comment by JustinGoheen** [comment]
refer to this [issue comment](https://github.com/Lightning-AI/lightning/issues/13176#issuecomment-1140624765) in #13176.
