### ISSUE TITLE
When using debug training data, the program stops and the data cannot be read

### ISSUE THREAD

**Issue by cl-cqupt** [Lightning-AI/lightning#16875]
### Bug description

![$5A7IBHTY5XM_}CH__GZU5I](https://user-images.githubusercontent.com/117440320/221411446-987e79ac-6d14-4cb8-9efc-175dc5c737cf.png)

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
Hi 
Could you please provide a bit more information about what is not working? It would be very helpful if you could fill out the section "How to reproduce the bug" and the verison of Lightning you tried. Without this information we won't be able to help  unfortunately, and we would have to close the issue.

And sorry for the late response, this fell through the cracks.
