### ISSUE TITLE
neptune.new deprecation warning with NeptuneLogger

### ISSUE THREAD

**Issue by wouterzwerink** [Lightning-AI/lightning#16887]
### Bug description

When using the latest versions of pytorch-lightning and neptune-client from conda-forge, I get a deprecation warning.

### How to reproduce the bug

```python
Simply creating a NeptuneLogger should give the error already.
```

### Error messages and logs

```bash
/home/micromamba/lib/python3.10/site-packages/pytorch_lightning/loggers/neptune.py:39: NeptuneDeprecationWarning: You're importing the Neptune client library via the deprecated `neptune.new` module, which will be removed in a future release. Import directly from `neptune` instead.
  from neptune import new as neptune
```

### Environment

<details>
  <summary>Current environment</summary>

```
- Lightning Component: NeptuneLogger
- neptune-client: 1.0.1
- pytorch-lightning: 1.9.3
- PyTorch: 1.13.1
- Python: 3.10
```

</details>

### More info

https://docs.neptune.ai/setup/neptune-client_1-0_release_changes/

cc @justusschock @awaelchli @Blaizzy

**Comment by Blaizzy** [comment]
Hi @wouterzwerink 

Prince here,

Don't worry; this warning shouldn't stop you from logging to Neptune or break your workflow. 

This warning is appearing only because we have a new major release of our client (v1.0.0), and we are currently working on updating all neptune integrations.
