### ISSUE TITLE
Add `max_size` mode to `CombinedLoader`

### ISSUE THREAD

**Issue by janpawlowskiof** [Lightning-AI/lightning#16917]
### Description & Motivation

`CombinedLoader` currently supports `min_size` and `max_size_cycle` modes.

Let's say i want to track dev metrics on multiple datasets (that are of different lengths).
Currently there seems to bo no proper way to do this, as `min_size` will skip some batches of longer dataloaders, and `max_size_cycle` will repeat some batches of shorter dataloaders. (Unless I am missing something in which case, please correct me)

A `max_size` mode (or however this mode would be called), which yields batches from dataloader that are not yet depleted would allow for this.

### Pitch

Expected behaviour of said mode:

For a given code:
```
dataloaders  = {
    f"dl_0": torch.tensor([0]), 
    f"dl_1": torch.tensor([10, 11]), 
    f"dl_2": torch.tensor([100, 101, 102]), 
}
lengths = {dl_name: len(dl) for dl_name, dl in dataloaders.items()}

print(f"Given dataloaders of lengths: {lengths}")

print("batches in min_size mode:")
for batch in CombinedLoader(loaders=dataloaders, mode="min_size"):
    print("\t", batch)

print("batches in max_size_cycle mode:")
for batch in CombinedLoader(loaders=dataloaders, mode="max_size_cycle"):
    print("\t", batch)

print("(THE INTERESTING PART) batches in max_size mode:")
for batch in CombinedLoader(loaders=dataloaders, mode="max_size"):
    print("\t", batch)

```

Output would be:
```
Given dataloaders of lengths: {'dl_0': 1, 'dl_1': 2, 'dl_2': 3}
batches in min_size mode:
	 {'dl_0': tensor(0), 'dl_1': tensor(10), 'dl_2': tensor(100)}
batches in max_size_cycle mode:
	 {'dl_0': tensor(0), 'dl_1': tensor(10), 'dl_2': tensor(100)}
	 {'dl_0': tensor(0), 'dl_1': tensor(11), 'dl_2': tensor(101)}
	 {'dl_0': tensor(0), 'dl_1': tensor(10), 'dl_2': tensor(102)}
(THE INTERESTING PART) batches in max_size mode:
	 {'dl_0': tensor(0), 'dl_1': tensor(10), 'dl_2': tensor(100)}
	 {'dl_1': tensor(11), 'dl_2': tensor(101)}
	 {'dl_2': tensor(102)}
```

### Additional context

If this seems like a worthy addition, I'd be willing to try and add this in a PR.

cc @borda @justusschock @awaelchli

**Comment by awaelchli** [comment]
@carmocca would this fit well into the refactored CombinedLoader?

**Comment by carmocca** [comment]
It would fit super well!

It's basically the "max_size_cycle" implementation without these lines: https://github.com/Lightning-AI/lightning/blob/aa7fa3a0ce1507f96ee28c7eac9f12b3f435f81a/src/lightning/pytorch/utilities/combined_loader.py#L57-L59

The only difficulty is that the design suggests that the exhausted iterable keys aren't even included instead of filling them with `None` (`{'dl_0': None, 'dl_1': None, 'dl_2': tensor(100)}`)
To do that, we would need a customized `tree_filtered_unflatten(flattened, spec, filter=None)` that returns the expected batch structure but filters out the Nones. But it shouldn't be hard to write.

@janpawlowskiof I'm happy to guide your implementation if you want to start a PR!

**Comment by janpawlowskiof** [comment]
I'd be happy to! Will write here once I will have something to show, which is hopefully sooner than later :smile:

**Comment by janpawlowskiof** [comment]
Having spent some time thinking about this I came to the conclusion that returning `None`s is a better design.

While it makes a lot of sense not to include keys of exhausted iterables, when using dict, it makes no sense to only return data from non-exhausted iterables when using list/tuples, because then there is no way to identify which iterables provided what. Also when using NamedTuples you simply must fill in the fields with `None`.

Because of this I think that the consistent behavior of always returning `None` for exhaused iterable makes more sense.

--------------------

The changes to code are quite minimal, here's a PR with said changes. [#16939](https://github.com/Lightning-AI/lightning/pull/16939).
Also it's my first time contributing (hopefully out of many), please correct me if I did something incorrectly along the way.
