### ISSUE TITLE
The progress bar is not fully displayed

### ISSUE THREAD

**Issue by THUliuxinlong** [Lightning-AI/lightning#16937]
### Bug description

![image](https://user-images.githubusercontent.com/71317281/222706958-61733dbc-2329-4f54-bc18-85943aa9474a.png)

```
def training_step(self, batch, batch_idx):
        loss = self._step(batch)
        self.log("train_loss", loss, on_step=True, prog_bar=True, logger=True)

        return {"loss": loss}
```    

![image](https://user-images.githubusercontent.com/71317281/222755740-61a0478f-a966-46a7-98e6-36fcca816108.png)

When I used rich, I had a similar problem with the limited length of the progress bar.

### How to reproduce the bug

```
import time
from tqdm import *

description = 'process bar test ************************** process bar test'

for i in tqdm(range(100), desc=description, dynamic_ncols=True):
        time.sleep(0.01)

for i in tqdm(range(100), desc=description, ncols=150):
    time.sleep(0.01)
```

![image](https://user-images.githubusercontent.com/71317281/222871206-4545f12a-34d3-4f65-9451-0c15779227cb.png)

My tests seem to show a problem with parameter of tqdm('dynamic_ncols=True'). I wonder if this has anything to do with my use of the ssh interpreter or pycharm.

**Comment by awaelchli** [comment]
This is generally an issue when [running inside the PyCharm console](https://github.com/tqdm/tqdm/issues/307#issuecomment-258391869). Possible workaround: https://github.com/tqdm/tqdm/issues/307#issuecomment-532498793 (or just run in a regular terminal outside PyCharm).
