### ISSUE TITLE
Cannot use multiple Gpus properly.

### ISSUE THREAD

**Issue by LuPaoPao** [Lightning-AI/lightning#16954]
### Bug description

I've set up to use 8 gpus and to use ddp, but I'm actually only using 1 gpu, I don't know why.

My core code:
![图片](https://user-images.githubusercontent.com/36125195/222945496-147fce2f-c5a8-4a0e-8868-69cb417a9975.png)

The log:
![图片](https://user-images.githubusercontent.com/36125195/222945583-9cf7a2b5-3952-42c2-b5bf-b2803340e8b6.png)
![图片](https://user-images.githubusercontent.com/36125195/222945600-ee490db7-75cc-4ba8-bf78-73a9faec7788.png)

The usage of CUDA:
![图片](https://user-images.githubusercontent.com/36125195/222945678-7cebb18a-158b-4172-8cb2-bc3a2355a2e9.png)

The envs:
pytorch-lightning==1.6.0
torch==1.9.0+cu111

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
@LuPaoPao Is your EMACallback perhaps accidentally moving the model to GPU 0? Since you are running pytorch_lightning=1.6.0, did you try upgrading to a patch release, for example, 1.6.5?
