### ISSUE TITLE
Add torch.compile tests with Fabric

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lightning#16971]
### Outline & Motivation

2.0 CI for Fabric is already setup: https://github.com/Lightning-AI/lightning/commit/fca69e68dacb85daf4261824eb505365eb89a19e

### Pitch

Add tests that use Fabric and `torch.compile`. Ensure basic functionality works.

cc @carmocca @justusschock @awaelchli @borda

**Comment by awaelchli** [comment]
What do you need me to test? That an OptimizedModule can be passed to the setup method of Fabric? Or do you mean we should `torch.compile` a Fabric training loop function?
