### ISSUE TITLE
WandbLogger model artifacts do not have `best` aliases when using `save_top_k`> 0

### ISSUE THREAD

**Issue by DrSleep** [Lightning-AI/lightning#16979]
### Bug description

When using WandbLogger and ModelCheckpoint with `save_top_k` > 0, the model artifacts on Wandb do not have `best` aliases -- instead they only show `best_k` and `latest` aliases for the last model artifact that was uploaded to WandB. Note that this artifact version may not be the actual best, but only one of the `best_k`.

### How to reproduce the bug

As per the reproduction code below, this happens because `_scan_checkpoints` override the `best` model tag with `best_k`. 

The below code is an extension of `test_scan_checkpoints` `tests/tests_pytorch/loggers/test_logger.py`

```python
from pathlib import Path
import random
import tempfile
from unittest.mock import patch

from lightning.pytorch.loggers.utilities import _scan_checkpoints

checkpoint_callback_mock = patch("lightning.pytorch.callbacks.ModelCheckpoint")
save_top_k = 5
# Randomly assign one of the checkpoints to be the best
best_i = random.randint(0, max(save_top_k - 1, 0))
with tempfile.TemporaryDirectory() as tmpdir:
    best_k_models = {}
    for i in range(save_top_k):
        ckpt_path = Path(tmpdir) / f"{i}.ckpt"
        ckpt_path.write_text("")
        best_k_models[ckpt_path] = i
        if i == best_i:
            checkpoint_callback_mock.best_model_path = ckpt_path
            checkpoint_callback_mock.best_model_score = i
    checkpoint_callback_mock.best_k_models = best_k_models
    logged_model_time = {}
    checkpoints = _scan_checkpoints(checkpoint_callback_mock, logged_model_time)

    # This passes because the number of checkpoints is correct
    assert len(checkpoints) == save_top_k

    if save_top_k > 0:
        # This fails because the tag is now `best_k`
        assert checkpoints[best_i][-1] == "best"
```

### Error messages and logs

```
assert checkpoints[best_i][-1] == "best"
AssertionError
```

### Environment

<details>
  <summary>Current environment</summary>
I used the latest code on master from this commit: b2b6449be7b50973ab3f1d7fce6d72cb96c3b75f

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

### More info

In its current form it is unclear to me what is the usefulness of the `best_k` alias altogether when logging to Wandb: as per the Wandb conventions, the tags/aliases are unique for an artifact in the sense that two different versions of the same artifact can not have the same tag (if ModelCheckpoint outputted an ordering of checkpoints based on the score instead, then tags `best_1`, `best_2`, `best_3`, etc, could be useful).

As a possible solution to resolve this bug, I think resorting back to the following logic makes sense:

```python
     aliases = ["latest", "best"] if p == checkpoint_callback.best_model_path else ["latest"]
```

cc @awaelchli @morganmcg1 @borisdayma @scottire @parambharat

**Comment by parambharat** [comment]
Hi @DrSleep , Thanks for raising this issue. I have tested and fixed this issue. Please review this [PR](https://github.com/Lightning-AI/lightning/pull/17121) and let me know if this fixes the issue. 
Here's a sample [wandb workspace ](https://wandb.ai/parambharat/wandb-lightning) that has the corresponding [artifacts.](https://wandb.ai/parambharat/wandb-lightning/artifacts)
Here's a [colab](https://colab.research.google.com/drive/1jx3KmLgrsxjxHPv88Ek6PjPJvAah-lvV?usp=sharing) to reproduce the runs in the workspace above.

**Comment by DrSleep** [comment]
Hi, @parambharat , yes, this works perfect. Thank you!
