### ISSUE TITLE
Allow setting `size_based_auto_wrap_policy` with an integer

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#16991]
### Description & Motivation

Today, the user needs to define this to set the policy based on a different layer size:

```py
from torch.distributed.fsdp.wrap import size_based_auto_wrap_policy
my_auto_wrap_policy = partial(size_based_auto_wrap_policy, min_num_params=1e3)

strategy=FSDPStrategy(auto_wrap_policy=my_auto_wrap_policy)
```

Some older docs even suggest this:

```py
def custom_auto_wrap_policy(
    module: nn.Module,
    recurse: bool,
    unwrapped_params: int,
    # These are customizable for this policy function.
     min_num_params: int = int(1e8),
) -> bool:
     return unwrapped_params >= min_num_params

my_auto_wrap_policy = partial(size_based_auto_wrap_policy, min_num_params=1e3)

strategy=FSDPStrategy(auto_wrap_policy=my_auto_wrap_policy)
```

But this is cumbersome, and leads to [user error and confusion](https://discordapp.com/channels/1077906959069626439/1082712643921526884).

### Pitch

Allow passing the minimum layer size for wrapping as an integer, which internally then gets translated to a policy:

```py
strategy=FSDPStrategy(min_auto_wrap_size=1e5)
```

This would apply both to Fabric and Trainer.

cc @borda @carmocca @justusschock @awaelchli

**Comment by carmocca** [comment]
I think this is brittel considering that the FSDP API is regularly changing, and limited considering that this supports a specific check (greater or equal).

Additionally, the FSDP API already supports multiple wrapping policies that make this easy: https://github.com/pytorch/pytorch/blob/v2.0.0-rc5/torch/distributed/fsdp/wrap.py

Particularly, the `lambda_auto_wrap_policy` and `size_based_auto_wrap_policy`
