### ISSUE TITLE
Calling module hooks before callback hooks?

### ISSUE THREAD

**Issue by bilelomrani1** [Lightning-AI/lightning#17040]
### Bug description

I have a `LightningModule` that estimates some weights tensor in its `on_fit_start` method. These weights are used in the loss function to reweigh the different classes. The weights are computed on the training set, so the module must be attached to a trainer when estimating them, they cannot be assigned in the `__init__`. 

```python
class MyModule(pl.LightningModule):
    ...
    def on_fit_start(self):
        self.weights = self.compute_weights()

    def training_step(self, batch, batch_idx):
        ...
        loss = F.cross_entropy(input=logits, target=labels, weight=self.weights)
```

There is an issue when using the `LearningRateFinder` callback because the callback tries to compute the loss before the module's `on_fit_start` method is called:

```
...
AttributeError: 'MyModule' object has no attribute 'weights'
```

In the trainer, the callback hooks are called before the module hooks:
```python
        ...
        # hook
        if self.state.fn == TrainerFn.FITTING:
            call._call_callback_hooks(self, "on_fit_start")
            call._call_lightning_module_hook(self, "on_fit_start")
```
Is there a specific reason why? If so, what would be the appropriate place to initialize the `weights`?

cc @carmocca @awaelchli @borda @justusschock

**Comment by carmocca** [comment]
Can you try the [`setup`](https://lightning.ai/docs/pytorch/stable/common/lightning_module.html#setup) hook?

**Comment by bilelomrani1** [comment]
Works perfectly, thank you very much for your help, I should invest more time into the documentation.
