### ISSUE TITLE
how to import the ModelCheckpoint callback after using the pip install lightning ?

### ISSUE THREAD

**Issue by shamanez** [Lightning-AI/lightning#17048]
### Bug description

I install pytorch_lightinng with the pip install lightning==1.9.4.

from pytorch_lightning.callbacks import ModelCheckpoint

The above command works well.

But how can I change it when using the lighting? 

**from lightning.callbacks import ModelCheckpoint**

Gives the following error

**ModuleNotFoundError: No module named 'lightning.callbacks'**

### How to reproduce the bug

```python
from lightning.callbacks import ModelCheckpoint
```

### Error messages and logs

```
# Error messages and logs here please
```
**ModuleNotFoundError: No module named 'lightning.callbacks'**

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Version (e.g., 1.94):
#- GPU models and configuration:
#- How you installed Lightning(`pip`):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
Hi

It needs to be 

```
from lightning.pytorch.callbacks import ModelCheckpoint
```

You can remember it this way: `pytorch_lightning = lightning.pytorch`
Hope this helps :)

**Comment by shamanez** [comment]
Thanks you save a lot of time. Will there be updates in the tutorials as
well ?

**Comment by awaelchli** [comment]
Yes absolutely, the work on this has already started (https://github.com/Lightning-AI/tutorials/pull/222). 
Let me know if you have any other questions about this.
