### ISSUE TITLE
Model Summary without implementing 'forward' method in the pl.LightningModule class

### ISSUE THREAD

**Issue by varskann** [Lightning-AI/lightning#17083]
### Bug description

I am trying to set up a framework where I keep my Model (nn.Module class) independent of the LightningModule. Even though I implement the forward method inside the Base PyTorch Model class, I am unable to use '_self.example_input_array_' attribute to generate the model summary

### How to reproduce the bug

```python
from torch import nn
from torch.nn import functional as F

class MNISTModel(nn.Module):
    def __init__(self, hidden_size=64):
        super().__init__()
        # self.example_input_array = torch.Tensor(32, 1, 28, 28)
        # Set our init args as class attributes
        self.hidden_size = hidden_size

        # Hardcode some dataset specific attributes
        self.num_classes = 10
        self.dims = (1, 28, 28)
        channels, width, height = self.dims

        # Define PyTorch model
        self.model = nn.Sequential(
            nn.Flatten(),
            nn.Linear(channels * width * height, hidden_size),
            nn.ReLU(),
            nn.Dropout(0.1),
            nn.Linear(hidden_size, hidden_size),
            nn.ReLU(),
            nn.Dropout(0.1),
            nn.Linear(hidden_size, self.num_classes),
            )

    def forward(self, x):
        x = self.model(x)
        return F.log_softmax(x, dim=1)

class LitMNIST(pl.LightningModule):
    def __init__(self, model, learning_rate=2e-4):
        super().__init__()
        # self.save_hyperparameters()
        self.learning_rate = learning_rate
        self.model = model

        self.example_input_array = torch.Tensor(32, 1, 28, 28)
    def training_step(...):
        ...
```

### Error messages and logs

```
Traceback (most recent call last):
  File "/Users/kanishkvarshney/Desktop/Workspace/Code/e2e_mnist/mnist_wrap/train.py", line 116, in <module>
    trainer.fit(mnist_model, datamodule=mnist_data)
  File "/opt/anaconda3/envs/dev/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/opt/anaconda3/envs/dev/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/anaconda3/envs/dev/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/anaconda3/envs/dev/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1097, in _run
    self._call_callback_hooks("on_fit_start")
  File "/opt/anaconda3/envs/dev/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1394, in _call_callback_hooks
    fn(self, self.lightning_module, *args, **kwargs)
  File "/opt/anaconda3/envs/dev/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_summary.py", line 59, in on_fit_start
    model_summary = self._summary(trainer, pl_module)
  File "/opt/anaconda3/envs/dev/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_summary.py", line 73, in _summary
    return summarize(pl_module, max_depth=self._max_depth)
  File "/opt/anaconda3/envs/dev/lib/python3.8/site-packages/pytorch_lightning/utilities/model_summary/model_summary.py", line 431, in summarize
    return ModelSummary(lightning_module, max_depth=max_depth)
  File "/opt/anaconda3/envs/dev/lib/python3.8/site-packages/pytorch_lightning/utilities/model_summary/model_summary.py", line 189, in __init__
    self._layer_summary = self.summarize()
  File "/opt/anaconda3/envs/dev/lib/python3.8/site-packages/pytorch_lightning/utilities/model_summary/model_summary.py", line 246, in summarize
    self._forward_example_input()
  File "/opt/anaconda3/envs/dev/lib/python3.8/site-packages/pytorch_lightning/utilities/model_summary/model_summary.py", line 278, in _forward_example_input
    model(input_)
  File "/opt/anaconda3/envs/dev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/anaconda3/envs/dev/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 674, in forward
    return super().forward(*args, **kwargs)
  File "/opt/anaconda3/envs/dev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 201, in _forward_unimplemented
    raise NotImplementedError
NotImplementedError

```

### Environment

* CUDA:
	- GPU:               None
	- available:         False
	- version:           None
* Lightning:
	- efficientnet-pytorch: 0.6.3
	- lightning-bolts:   0.6.0.post1
	- lightning-utilities: 0.7.0
	- pytorch-lightning: 1.9.4
	- segmentation-models-pytorch: 0.2.1
	- torch:             1.11.0
	- torchmetrics:      0.11.3
	- torchsummary:      1.5.1
	- torchvision:       0.12.0
* System:
	- OS:                Darwin
	- architecture:
		- 64bit
		- 
	- processor:         i386
	- python:            3.8.13
	- version:           Darwin Kernel Version 21.6.0: Mon Dec 19 20:44:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_X86_64

cc @borda @awaelchli

**Comment by awaelchli** [comment]
Hey @varskann 

So the error already tells us what's wrong. If the LightningModule doesn't implement forward(), the model summary can't work. You would have to add this to your LM:

```py
def forward(self, x):
    return self.model(x)
```

**Comment by varskann** [comment]
@awaelchli  Yes I got the issue, but wouldn't that be just redundant?  Given I already have defined the 'forward' method in my Actual Model

**Comment by awaelchli** [comment]
Hey @varskann 
In your simple case, we could make Lightning an "AI" so that it can smartly figure out that it has to pass the inputs through your `self.model` attribute. But in general, that's not possible. What if we had a LightningModule that had this:


```
class ComplicatedAutoencoder(LightningModule):
    def __init__(self, hidden_size=64):
        super().__init__()
        self.encoder = Encoder()
        self.decoder = Decoder()
        self.refinement = Refinement()
```
Here we have three submodules/layers, but without the definition of forward, we don't know how to pass a tensor through these! We don't even know how these three modules are being composed. 

Maybe we could explore this idea:
We could allow any submodule to define the `example_input_array` attribute. If a submodule has this defined, we pass the inputs through the submodule independently. Need to think about what edge cases need to be handled. So for the example above, if encoder, decoder, and refinement would all define the proper example_input_array, we could feed these individually and report the ModelSummary.

**Comment by varskann** [comment]
Hey, 
@awaelchli thanks for the detailed explanation. 
But even in this case, with multiple models/sub-modules, wouldn't it be easier / straightforward to pass the example input through the respective 'forward' methods of each model(nn.Module). 
Different naming for `example_input_array_<submodule>`  for Sub Module implemented should do the trick. Let me know your thoughts.

**Comment by awaelchli** [comment]
No, that won't work. You need to think this through: The implementation of the forward method can be very arbitrary. It may use only a subset of the modules defined, or it may use a submodule more than once with different input shapes. We can also not make any assumptions that somehow these submodules are chained sequentially. You can basically add an arbitrary functional transform between modules that changes the input shapes. 

The current implementation in the model summary accounts for all that correctly by collecting the intermediate input and output tensor shapes.

**Comment by awaelchli** [comment]
Closing this since the proposal isn't possible to implement in the way it is described. It would make too many assumptions.
