### ISSUE TITLE
MLFlow logger default 'save_dir' doc and code consistency

### ISSUE THREAD

**Issue by lcaquot94** [Lightning-AI/lightning#17092]
### 📚 Documentation

In MLFLow Logger, doc and code are not consistent

Dov version says : A path to a local directory where the MLflow runs get saved. Defaults to **./mlflow** if tracking_uri is not provided. Has no effect if tracking_uri is provided.

But code set default value to **'./mlruns'**

cc @borda

**Comment by Borda** [comment]
@lcaquot94 could you pls send a PR with a suggested update? :rabbit:
