### ISSUE TITLE
`pytorch-lightning` is also installed when `pip install lightning`

### ISSUE THREAD

**Issue by Ttayu** [Lightning-AI/lightning#17099]
### Bug description

Congratulations on the release of lightning2.0.
I tried to install it immediately, but pytorch-lightning was installed as well as lightning.
This was not confirmed with lightning 1.9.3.
Is this expected behavior?

### How to reproduce the bug

```python
pip install --dry-run lightning
```
### Error messages and logs

```
Would install
Jinja2-3.1.2
MarkupSafe-2.1.2
PyJWT-2.6.0
PyYAML-6.0
Pygments-2.14.0
aiohttp-3.8.4
aiosignal-1.3.1
anyio-3.6.2
arrow-1.2.3
async-timeout-4.0.2
attrs-22.2.0
beautifulsoup4-4.11.2
blessed-1.20.0
certifi-2022.12.7
charset-normalizer-3.1.0
click-8.1.3
cmake-3.26.0
croniter-1.3.8
dateutils-0.6.12
deepdiff-6.2.3
dnspython-2.3.0
email-validator-1.3.1
fastapi-0.88.0
filelock-3.10.0
frozenlist-1.3.3
fsspec-2023.3.0
h11-0.14.0
httpcore-0.16.3
httptools-0.5.0
httpx-0.23.3
idna-3.4
inquirer-3.1.3
itsdangerous-2.1.2
lightning-2.0.0  <--
lightning-cloud-0.5.31
lightning-utilities-0.8.0
lit-15.0.7
markdown-it-py-2.2.0
mdurl-0.1.2
mpmath-1.3.0
multidict-6.0.4
networkx-3.0
numpy-1.24.2
nvidia-cublas-cu11-11.10.3.66
nvidia-cuda-cupti-cu11-11.7.101
nvidia-cuda-nvrtc-cu11-11.7.99
nvidia-cuda-runtime-cu11-11.7.99
nvidia-cudnn-cu11-8.5.0.96
nvidia-cufft-cu11-10.9.0.58
nvidia-curand-cu11-10.2.10.91
nvidia-cusolver-cu11-11.4.0.1
nvidia-cusparse-cu11-11.7.4.91
nvidia-nccl-cu11-2.14.3
nvidia-nvtx-cu11-11.7.91
ordered-set-4.1.0
orjson-3.8.7
packaging-23.0
psutil-5.9.4
pydantic-1.10.6
python-dateutil-2.8.2
python-dotenv-1.0.0
python-editor-1.0.4
python-multipart-0.0.6
pytorch-lightning-2.0.0 <--
pytz-2022.7.1
readchar-4.0.4
requests-2.28.2
rfc3986-1.5.0
rich-13.3.2
six-1.16.0
sniffio-1.3.0
soupsieve-2.4
starlette-0.22.0
starsessions-1.3.0
sympy-1.11.1
torch-2.0.0
torchmetrics-0.11.4
tqdm-4.65.0
traitlets-5.9.0
triton-2.0.0
typing_extensions-4.5.0
ujson-5.7.0
urllib3-1.26.15
uvicorn-0.21.0
uvloop-0.17.0
watchfiles-0.18.1
wcwidth-0.2.6
websocket-client-1.5.1
websockets-10.4
yarl-1.8.2
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0): 2.0
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0): 2.0
#- Python version (e.g., 3.9): 3.10.8
#- OS (e.g., Linux): Ubuntu22.04
#- CUDA/cuDNN version: 11.7
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
Hi
I find this counter-intuitive too, but I think this was to maximize compatibility for users with existing code that use the `pytorch_lightning` imports. If you don't want it, you can safely `pip uninstall` this package. 

@Borda @carmocca @justusschock Please fill in the details in case I'm oversimplifying the answer here.

**Comment by adamjstewart** [comment]
Probably unrelated, but I noticed that there's no `MANIFEST.in` for `lightning` (unlike all other namespaces) when working on #17100.

**Comment by Ttayu** [comment]
> Hi I find this counter-intuitive too, but I think this was to maximize compatibility for users with existing code that use the `pytorch_lightning` imports. If you don't want it, you can safely `pip uninstall` this package.
> 
> @Borda @carmocca @justusschock Please fill in the details in case I'm explaining the wrong reasons.

I agree that compatibility is a good thing. but I think that users who want to keep compatibility should use the old pytorch-lightning and fixed version. and also the docs are not fully maintained, which may cause confusion for new users who use Lightning. (Because it has been decided to completely migrate to Lightning.)

**Comment by Borda** [comment]
yes, as requested in #16921 we append PL to lightning as there is zero additional dependency
also, it is installed without a specified version, so it pulls what is on PyPI or you have in the local cache from past installations you can adjust the needed version
```
pip install lightning pytorch-lightning==1.8.6
```
or to be aligned you can
```
pip install lightning --upgrade-strategy=eager
```

**Comment by awaelchli** [comment]
Okay, so closing this since it is expected and planned. In the future, once pytorch-lightning is no longer supported, this won't be installed anymore together.

**Comment by adamgayoso** [comment]
How much longer will releases be made under both names?
