### ISSUE TITLE
pytorch lightning Version of pytorch

### ISSUE THREAD

**Issue by wsy-yjys** [Lightning-AI/lightning#17117]
### Bug description

Can you give me a list of corresponding versions of pytorch_lightning and pytorch? My pytorch version is 1.10.0, and I don't know which version of pytorch_lightning should be installed

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by wsy-yjys** [comment]
when I run the following code, meet this the bug 
```
>>>import pytorch_lightning as pl
AttributeError: module 'distutils' has no attribute 'version'
```

**Comment by awaelchli** [comment]
Hey @wsy-yjys 
There is a compatibility matrix here: https://lightning.ai/docs/pytorch/stable/versioning.html#compatibility-matrix
For torch 1.10, you should be able to install pytorch_lightning from 1.5 up to 1.9. Let me know if that helps.

**Comment by wsy-yjys** [comment]
I got it, thank you
