### ISSUE TITLE
`torch.save(pl_module)` error with PL 2.0

### ISSUE THREAD

**Issue by yhl48** [Lightning-AI/lightning#17124]
### Bug description

The error arises when pickling a model with torch.save(). The source is this line from PyTorch DataLoader

https://github.com/pytorch/pytorch/blob/92eb9d363a7110a43746cc3e704a393837d5047c/torch/utils/data/dataloader.py#L658

PL and PyTorch versions == 2.0.

Specifically, it looks like the error occurs when torch.save() is called in `on_train_epoch_end` in a `Callback` class.
### How to reproduce the bug

```
from typing import Tuple
import os
import torch
import pytorch_lightning as pl
from torch.utils.data import DataLoader
from pytorch_lightning.callbacks import Callback

class CustomCallback(Callback):
    def __init__(self) -> None:
        super().__init__()
    
    def on_train_epoch_end(self, trainer: pl.Trainer, pl_module: pl.LightningModule):
        # executed every epoch of the training
        with open(os.path.join(os.getcwd(), "min_repro.pkl"), "wb") as fb:
            torch.save(pl_module, fb)


class CustomPL(pl.LightningModule):
    def __init__(self, model: torch.nn.Module):
        super().__init__()
        self._model = model

    def configure_optimizers(self) -> torch.optim:
        opt = torch.optim.Adam(self.parameters(), lr=3e-4)
        return opt

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self._model(x)

    def training_step(self, x: Tuple[torch.Tensor, ...], batch_idx: int) -> torch.Tensor:
        ypred = self(x)
        loss = torch.mean((ypred - torch.zeros_like(ypred)) ** 2)
        return loss


pl_module = CustomPL(torch.nn.Linear(1, 1))
data = torch.randn(10, 1)
dloader = DataLoader(data, batch_size=10)
trainer = pl.Trainer(callbacks=[CustomCallback()], max_epochs=4)
trainer.fit(pl_module, dloader)

```

Hoping to get some pointers from the developers to see if this is an actual issue concerning PL, or is it more of a PyTorch issue?

On that note, the relevant PyTorch code has not been changed since at least PyTorch 1.3 so I am guessing there have been some backward incompatible changes in PL 2.0

https://github.com/pytorch/pytorch/blob/49444c3e546bf240bed24a101e747422d1f8a0ee/torch/utils/data/dataloader.py#L646

### Error messages and logs

```
NotImplementedError: ('{} cannot be pickled', '_SingleProcessDataLoaderIter')
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @justusschock @awaelchli

**Comment by carmocca** [comment]
I'll look into this. Note however that serializing an `nn.Module` (or `pl.LightningModule`) is strongly discouraged. You should instead serialize the `pl_module.state_dict()`

You can work around this error by patching it in the meantime:

```python
def getstate_patch(*_):
    return {}
from torch.utils.data.dataloader import _BaseDataLoaderIter
_BaseDataLoaderIter.__getstate__ = getstate_patch
```

**Comment by yhl48** [comment]
Thanks for the workaround!

**Comment by carmocca** [comment]
Opened a PR in #17130
