### ISSUE TITLE
Multiple callback instances

### ISSUE THREAD

**Issue by yhl48** [Lightning-AI/lightning#17149]
### 📚 Documentation

```
class Counter(Callback):
    def __init__(self, what="epochs", verbose=True):
        self.what = what
        self.verbose = verbose
        self.state = {"epochs": 0, "batches": 0}

    @property
    def state_key(self):
        # note: we do not include `verbose` here on purpose
        return self._generate_state_key(what=self.what)

    def on_train_epoch_end(self, *args, **kwargs):
        if self.what == "epochs":
            self.state["epochs"] += 1

    def on_train_batch_end(self, *args, **kwargs):
        if self.what == "batches":
            self.state["batches"] += 1

    def load_state_dict(self, state_dict):
        self.state.update(state_dict)

    def state_dict(self):
        return self.state.copy()


# two callbacks of the same type are being used
trainer = Trainer(callbacks=[Counter(what="epochs"), Counter(what="batches")])
```

The code above is quoted directly from https://lightning.ai/docs/pytorch/stable/extensions/callbacks.html as an example to support multiple instances of the callback to the `Trainer`. 

In the example, `self._generate_state_key(what=self.what)` is used, which is a protected method from the parent `Callback` class. I am just wondering if it would be better to provide a public method in the parent class to expose that functionality? Thanks.

cc @borda

**Comment by awaelchli** [comment]
I think that's a good suggestion! I don't mind making this public. But note, in general I think we would advise users to construct their own key directly. The code is basically very trivial:

```py
    def _generate_state_key(self, **kwargs: Any) -> str:
        return f"{self.__class__.__qualname__}{repr(kwargs)}"
```

I think we could also just inline this code in the docs example. That's probably the cleanest!
