### ISSUE TITLE
A bug about RichProgressBar

### ISSUE THREAD

**Issue by Rich-XGK** [Lightning-AI/lightning#17141]
### Bug description

Here is the problem：
    When I use the configure_callbacks() method to add the RichProgressBar without using callbacks=[RichProgressBar()] in making a Trainer instance, the following error will be reported:
    callbacks/progress/rich_progress.py:155 in render                                                   │
│                                                                                                  │
│   152 │   │   │   self._metrics = metrics                                                        │
│   153 │   │                                                                                      │
│   154 │   │   def render(self, task: "Task") -> Text:                                            │
│ ❱ 155 │   │   │   assert isinstance(self._trainer.progress_bar_callback, RichProgressBar)        │
│   156 │   │   │   if (                                                                           │
│   157 │   │   │   │   self._trainer.state.fn != "fit"                                            │
│   158 │   │   │   │   or self._trainer.sanity_checking                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError
    But when I use callbacks=[LitProgressBar()] in making a Trainer instance, the problem is solved and the RichProgressBar self-defined callback overwrites the default RichProgressBar callback normally.
    And this problem did not occur in using TqdmProgressBar.

### How to reproduce the bug

```python
class LitProgressBar(pl_callbacks.RichProgressBar):
    def __init__(
        self,
        refresh_rate: int = 1,
        leave: bool = True,
        theme: RichProgressBarTheme = RichProgressBarTheme(
            description="green_yellow",
            progress_bar="green1",
            progress_bar_finished="green1",
            progress_bar_pulse="#6206E0",
            batch_progress="green_yellow",
            time="grey82",
            processing_speed="grey82",
            metrics="grey82",
        ),
        console_kwargs: Optional[Dict[str, Any]] = None,
    ) -> None:
        super().__init__(refresh_rate, leave, theme, console_kwargs)


class ToLightning(pl.LightningModule):
    def __init__(
        self,
        model: nn.Module,
        criterion: nn.Module,
        optimizer: optim.Optimizer,
        scheduler: optim.lr_scheduler._LRScheduler,
        metric: Metric,
        train_loader: Union[DataLoader, GeometricDataLoader],
        val_loader: Union[DataLoader, GeometricDataLoader],
        args: Namespace,
    ) -> None:
        super().__init__()
        self.model = model
        self.criterion = criterion
        self.optimizer = optimizer
        self.scheduler = scheduler
        self.metric = metric
        self.train_loader = train_loader
        self.val_loader = val_loader
        self.args = args

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.model(x)

    def _run_step(self, batch_data: Union[Iterable[torch.Tensor], GeometricData]) -> torch.Tensor:
        if isinstance(batch_data, GeometricData):
            coordinates = batch_data.xyz
            coordinates_pred = self.model(batch_data)
            loss = self.criterion(coordinates_pred, coordinates, batch_data)
        else:
            inputs, targets = batch_data
            outputs = self.model(inputs)
            loss = self.criterion(outputs, targets)
        self.metric(outputs, targets)
        return loss

    def training_step(self, batch_data: Union[Iterable[torch.Tensor], GeometricData], batch_idx: int) -> torch.Tensor:
        train_loss = self._run_step(batch_data)
        self.log("train_loss", train_loss.item(), on_step=False, on_epoch=True, logger=True, sync_dist=True)
        return train_loss

    def on_train_epoch_end(self) -> None:
        train_metric = self.all_gather(self.metric.compute()).mean()
        self.log("train_metric", train_metric, on_step=False, on_epoch=True, logger=True, sync_dist=True)
        # The .reset() method of the metric will automatically be called at the end of an epoch.

    def validation_step(self, batch_data: Union[Iterable[torch.Tensor], GeometricData], batch_idx: int) -> torch.Tensor:
        val_loss = self._run_step(batch_data)
        self.log("val_loss", val_loss.item(), on_step=False, on_epoch=True, logger=True, sync_dist=True)
        return val_loss

    def on_validation_epoch_end(self) -> None:
        val_metric = self.all_gather(self.metric.compute()).mean()
        self.log("val_metric", val_metric, on_step=False, on_epoch=True, logger=True, sync_dist=True)

    def test_step(self, batch_data: Union[Iterable[torch.Tensor], GeometricData], batch_idx: int) -> torch.Tensor:
        test_loss = self._run_step(batch_data)
        self.log("test_loss", test_loss.item(), on_step=False, on_epoch=True, logger=True, sync_dist=True)
        return test_loss

    def on_test_epoch_end(self) -> None:
        test_metric = self.all_gather(self.metric.compute()).mean()
        self.log("test_metric", test_metric, on_step=False, on_epoch=True, logger=True, sync_dist=True)

    def train_loader(self) -> Union[DataLoader, GeometricDataLoader]:
        return self.train_loader

    def val_loader(self) -> Union[DataLoader, GeometricDataLoader]:
        return self.val_loader

    def configure_optimizers(self) -> optim.Optimizer:
        return self.optimizer

    def configure_scheduler(self) -> optim.lr_scheduler._LRScheduler:
        return self.scheduler

    def configure_callbacks(self) -> Union[Sequence[pl.Callback], pl.Callback]:
        rich_progress_bar = LitProgressBar()
        return [rich_progress_bar]

# in train script：

def main():
    args = utils.get_args("./config.yaml")
    torch.set_float32_matmul_precision('high')  # Sets the internal precision of float32 matrix multiplications.
    train_set = CIFAR10(
        root="/mnt/device/home/Rich/DataSets",
        train=True,
        transform=Compose([ToTensor(), Resize(224), Normalize(mean=[0.458, 0.456, 0.406], std=[0.229, 0.224, 0.225])]),
        download=False,
    )
    val_set = CIFAR10(
        root="/mnt/device/home/Rich/DataSets",
        train=False,
        transform=Compose([ToTensor(), Resize(224), Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])]),
        download=False,
    )
    train_loader = DataLoader(train_set, batch_size=args.train_batch_size, shuffle=True, num_workers=4)
    val_loader = DataLoader(val_set, batch_size=args.train_batch_size, shuffle=False, num_workers=4)
    model = AlexNet(num_classes=10, dropout=0.4)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=args.lr)
    scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=10, gamma=args.gamma)
    metric = Accuracy(task="multiclass", num_classes=10)
    trainer = Trainer(
        accelerator="cuda",  # auto, cpu, cuda, hpu, ipu, mps, tpu.
        strategy="ddp",
        devices=[2],
        max_epochs=args.epochs,
        # callbacks=[utils.LitProgressBar()],
    )
    model = utils.ToLightning(model, criterion, optimizer, scheduler, metric, train_loader, val_loader, args)
    trainer.fit(model, train_loader, val_loader)
```

### Error messages and logs

```
# Error messages and logs here please
```
HPU available: False, using: 0 HPUs
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7]

  | Name      | Type               | Params
-------------------------------------------------
0 | model     | AlexNet            | 57.0 M
1 | criterion | CrossEntropyLoss   | 0     
2 | metric    | MulticlassAccuracy | 0     
-------------------------------------------------
57.0 M    Trainable params
0         Non-trainable params
57.0 M    Total params
228.179   Total estimated model params size (MB)
Sanity Checking DataLoader 0:  50%|███████████████████████████████████████████████████████████████▌                                                               | 1/2 [00:03<00:03,  3.19s/it]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/pytorch_lightning/tra │
│ iner/call.py:42 in _call_and_handle_interrupt                                                    │
│                                                                                                  │
│    39 │   """                                                                                    │
│    40 │   try:                                                                                   │
│    41 │   │   if trainer.strategy.launcher is not None:                                          │
│ ❱  42 │   │   │   return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer,    │
│    43 │   │   else:                                                                              │
│    44 │   │   │   return trainer_fn(*args, **kwargs)                                             │
│    45                                                                                            │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/pytorch_lightning/str │
│ ategies/launchers/subprocess_script.py:92 in launch                                              │
│                                                                                                  │
│    89 │   │   """                                                                                │
│    90 │   │   if not self.cluster_environment.creates_processes_externally:                      │
│    91 │   │   │   self._call_children_scripts()                                                  │
│ ❱  92 │   │   return function(*args, **kwargs)                                                   │
│    93 │                                                                                          │
│    94 │   def kill(self, signum: _SIGNUM) -> None:                                               │
│    95 │   │   for proc in self.procs:                                                            │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/pytorch_lightning/tra │
│ iner/trainer.py:559 in _fit_impl                                                                 │
│                                                                                                  │
│    556 │   │   │   model_provided=True,                                                          │
│    557 │   │   │   model_connected=self.lightning_module is not None,                            │
│    558 │   │   )                                                                                 │
│ ❱  559 │   │   self._run(model, ckpt_path=ckpt_path)                                             │
│    560 │   │                                                                                     │
│    561 │   │   assert self.state.stopped                                                         │
│    562 │   │   self.training = False                                                             │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/pytorch_lightning/tra │
│ iner/trainer.py:935 in _run                                                                      │
│                                                                                                  │
│    932 │   │   # ----------------------------                                                    │
│    933 │   │   # RUN THE TRAINER                                                                 │
│    934 │   │   # ----------------------------                                                    │
│ ❱  935 │   │   results = self._run_stage()                                                       │
│    936 │   │                                                                                     │
│    937 │   │   # ----------------------------                                                    │
│    938 │   │   # POST-Training CLEAN UP                                                          │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/pytorch_lightning/tra │
│ iner/trainer.py:976 in _run_stage                                                                │
│                                                                                                  │
│    973 │   │   │   return self.predict_loop.run()                                                │
│    974 │   │   if self.training:                                                                 │
│    975 │   │   │   with isolate_rng():                                                           │
│ ❱  976 │   │   │   │   self._run_sanity_check()                                                  │
│    977 │   │   │   with torch.autograd.set_detect_anomaly(self._detect_anomaly):                 │
│    978 │   │   │   │   self.fit_loop.run()                                                       │
│    979 │   │   │   return None                                                                   │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/pytorch_lightning/tra │
│ iner/trainer.py:1005 in _run_sanity_check                                                        │
│                                                                                                  │
│   1002 │   │   │   call._call_callback_hooks(self, "on_sanity_check_start")                      │
│   1003 │   │   │                                                                                 │
│   1004 │   │   │   # run eval step                                                               │
│ ❱ 1005 │   │   │   val_loop.run()                                                                │
│   1006 │   │   │                                                                                 │
│   1007 │   │   │   call._call_callback_hooks(self, "on_sanity_check_end")                        │
│   1008                                                                                           │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/pytorch_lightning/loo │
│ ps/utilities.py:174 in _decorator                                                                │
│                                                                                                  │
│   171 │   │   else:                                                                              │
│   172 │   │   │   context_manager = torch.no_grad                                                │
│   173 │   │   with context_manager():                                                            │
│ ❱ 174 │   │   │   return loop_run(self, *args, **kwargs)                                         │
│   175 │                                                                                          │
│   176 │   return _decorator                                                                      │
│   177                                                                                            │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/pytorch_lightning/loo │
│ ps/evaluation_loop.py:115 in run                                                                 │
│                                                                                                  │
│   112 │   │   │   │   │   self._store_dataloader_outputs()                                       │
│   113 │   │   │   │   previous_dataloader_idx = dataloader_idx                                   │
│   114 │   │   │   │   # run step hooks                                                           │
│ ❱ 115 │   │   │   │   self._evaluation_step(batch, batch_idx, dataloader_idx)                    │
│   116 │   │   │   except StopIteration:                                                          │
│   117 │   │   │   │   # this needs to wrap the `*_step` call too (not just `next`) for `datalo   │
│   118 │   │   │   │   break                                                                      │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/pytorch_lightning/loo │
│ ps/evaluation_loop.py:380 in _evaluation_step                                                    │
│                                                                                                  │
│   377 │   │   self.batch_progress.increment_processed()                                          │
│   378 │   │                                                                                      │
│   379 │   │   hook_name = "on_test_batch_end" if trainer.testing else "on_validation_batch_end   │
│ ❱ 380 │   │   call._call_callback_hooks(trainer, hook_name, output, *step_kwargs.values())       │
│   381 │   │   call._call_lightning_module_hook(trainer, hook_name, output, *step_kwargs.values   │
│   382 │   │                                                                                      │
│   383 │   │   trainer._logger_connector.on_batch_end()                                           │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/pytorch_lightning/tra │
│ iner/call.py:190 in _call_callback_hooks                                                         │
│                                                                                                  │
│   187 │   │   fn = getattr(callback, hook_name)                                                  │
│   188 │   │   if callable(fn):                                                                   │
│   189 │   │   │   with trainer.profiler.profile(f"[Callback]{callback.state_key}.{hook_name}")   │
│ ❱ 190 │   │   │   │   fn(trainer, trainer.lightning_module, *args, **kwargs)                     │
│   191 │                                                                                          │
│   192 │   if pl_module:                                                                          │
│   193 │   │   # restore current_fx when nested context                                           │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/pytorch_lightning/cal │
│ lbacks/progress/rich_progress.py:507 in on_validation_batch_end                                  │
│                                                                                                  │
│   504 │   │   if self.is_disabled:                                                               │
│   505 │   │   │   return                                                                         │
│   506 │   │   if trainer.sanity_checking:                                                        │
│ ❱ 507 │   │   │   self._update(self.val_sanity_progress_bar_id, batch_idx + 1)                   │
│   508 │   │   elif self.val_progress_bar_id is not None:                                         │
│   509 │   │   │   self._update(self.val_progress_bar_id, batch_idx + 1)                          │
│   510 │   │   self.refresh()                                                                     │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/pytorch_lightning/cal │
│ lbacks/progress/rich_progress.py:427 in _update                                                  │
│                                                                                                  │
│   424 │   │   │   leftover = current % self.refresh_rate                                         │
│   425 │   │   │   advance = leftover if (current == total and leftover != 0) else self.refresh   │
│   426 │   │   │   self.progress.update(progress_bar_id, advance=advance, visible=visible)        │
│ ❱ 427 │   │   │   self.refresh()                                                                 │
│   428 │                                                                                          │
│   429 │   def _should_update(self, current: int, total: Union[int, float]) -> bool:              │
│   430 │   │   return current % self.refresh_rate == 0 or current == total                        │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/pytorch_lightning/cal │
│ lbacks/progress/rich_progress.py:339 in refresh                                                  │
│                                                                                                  │
│   336 │                                                                                          │
│   337 │   def refresh(self) -> None:                                                             │
│   338 │   │   if self.progress:                                                                  │
│ ❱ 339 │   │   │   self.progress.refresh()                                                        │
│   340 │                                                                                          │
│   341 │   def on_train_start(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule") ->    │
│   342 │   │   self._init_progress(trainer)                                                       │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/rich/progress.py:1535 │
│ in refresh                                                                                       │
│                                                                                                  │
│   1532 │   def refresh(self) -> None:                                                            │
│   1533 │   │   """Refresh (render) the progress information."""                                  │
│   1534 │   │   if not self.disable and self.live.is_started:                                     │
│ ❱ 1535 │   │   │   self.live.refresh()                                                           │
│   1536 │                                                                                         │
│   1537 │   def get_renderable(self) -> RenderableType:                                           │
│   1538 │   │   """Get a renderable for the progress display."""                                  │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/rich/live.py:221 in   │
│ refresh                                                                                          │
│                                                                                                  │
│   218 │   def refresh(self) -> None:                                                             │
│   219 │   │   """Update the display of the Live Render."""                                       │
│   220 │   │   with self._lock:                                                                   │
│ ❱ 221 │   │   │   self._live_render.set_renderable(self.renderable)                              │
│   222 │   │   │   if self.console.is_jupyter:  # pragma: no cover                                │
│   223 │   │   │   │   try:                                                                       │
│   224 │   │   │   │   │   from IPython.display import display                                    │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/rich/live.py:203 in   │
│ renderable                                                                                       │
│                                                                                                  │
│   200 │   │   Returns:                                                                           │
│   201 │   │   │   RenderableType: Displayed renderable.                                          │
│   202 │   │   """                                                                                │
│ ❱ 203 │   │   renderable = self.get_renderable()                                                 │
│   204 │   │   return Screen(renderable) if self._alt_screen else renderable                      │
│   205 │                                                                                          │
│   206 │   def update(self, renderable: RenderableType, *, refresh: bool = False) -> None:        │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/rich/live.py:98 in    │
│ get_renderable                                                                                   │
│                                                                                                  │
│    95 │                                                                                          │
│    96 │   def get_renderable(self) -> RenderableType:                                            │
│    97 │   │   renderable = (                                                                     │
│ ❱  98 │   │   │   self._get_renderable()                                                         │
│    99 │   │   │   if self._get_renderable is not None                                            │
│   100 │   │   │   else self._renderable                                                          │
│   101 │   │   )                                                                                  │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/rich/progress.py:1539 │
│ in get_renderable                                                                                │
│                                                                                                  │
│   1536 │                                                                                         │
│   1537 │   def get_renderable(self) -> RenderableType:                                           │
│   1538 │   │   """Get a renderable for the progress display."""                                  │
│ ❱ 1539 │   │   renderable = Group(*self.get_renderables())                                       │
│   1540 │   │   return renderable                                                                 │
│   1541 │                                                                                         │
│   1542 │   def get_renderables(self) -> Iterable[RenderableType]:                                │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/rich/progress.py:1544 │
│ in get_renderables                                                                               │
│                                                                                                  │
│   1541 │                                                                                         │
│   1542 │   def get_renderables(self) -> Iterable[RenderableType]:                                │
│   1543 │   │   """Get a number of renderables for the progress display."""                       │
│ ❱ 1544 │   │   table = self.make_tasks_table(self.tasks)                                         │
│   1545 │   │   yield table                                                                       │
│   1546 │                                                                                         │
│   1547 │   def make_tasks_table(self, tasks: Iterable[Task]) -> Table:                           │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/rich/progress.py:1568 │
│ in make_tasks_table                                                                              │
│                                                                                                  │
│   1565 │   │                                                                                     │
│   1566 │   │   for task in tasks:                                                                │
│   1567 │   │   │   if task.visible:                                                              │
│ ❱ 1568 │   │   │   │   table.add_row(                                                            │
│   1569 │   │   │   │   │   *(                                                                    │
│   1570 │   │   │   │   │   │   (                                                                 │
│   1571 │   │   │   │   │   │   │   column.format(task=task)                                      │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/rich/progress.py:1573 │
│ in <genexpr>                                                                                     │
│                                                                                                  │
│   1570 │   │   │   │   │   │   (                                                                 │
│   1571 │   │   │   │   │   │   │   column.format(task=task)                                      │
│   1572 │   │   │   │   │   │   │   if isinstance(column, str)                                    │
│ ❱ 1573 │   │   │   │   │   │   │   else column(task)                                             │
│   1574 │   │   │   │   │   │   )                                                                 │
│   1575 │   │   │   │   │   │   for column in self.columns                                        │
│   1576 │   │   │   │   │   )                                                                     │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/rich/progress.py:524  │
│ in __call__                                                                                      │
│                                                                                                  │
│    521 │   │   │   │   if timestamp + self.max_refresh > current_time:                           │
│    522 │   │   │   │   │   return renderable                                                     │
│    523 │   │                                                                                     │
│ ❱  524 │   │   renderable = self.render(task)                                                    │
│    525 │   │   self._renderable_cache[task.id] = (current_time, renderable)                      │
│    526 │   │   return renderable                                                                 │
│    527                                                                                           │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/pytorch_lightning/cal │
│ lbacks/progress/rich_progress.py:155 in render                                                   │
│                                                                                                  │
│   152 │   │   │   self._metrics = metrics                                                        │
│   153 │   │                                                                                      │
│   154 │   │   def render(self, task: "Task") -> Text:                                            │
│ ❱ 155 │   │   │   assert isinstance(self._trainer.progress_bar_callback, RichProgressBar)        │
│   156 │   │   │   if (                                                                           │
│   157 │   │   │   │   self._trainer.state.fn != "fit"                                            │
│   158 │   │   │   │   or self._trainer.sanity_checking                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /mnt/device/home/Rich/WorkSpace/DL-Sample/train.py:53 in <module>                                │
│                                                                                                  │
│   50                                                                                             │
│   51                                                                                             │
│   52 if __name__ == "__main__":                                                                  │
│ ❱ 53 │   main()                                                                                  │
│   54                                                                                             │
│                                                                                                  │
│ /mnt/device/home/Rich/WorkSpace/DL-Sample/train.py:49 in main                                    │
│                                                                                                  │
│   46 │   │   # callbacks=[utils.LitProgressBar()],                                               │
│   47 │   )                                                                                       │
│   48 │   model = utils.ToLightning(model, criterion, optimizer, scheduler, metric, train_load    │
│ ❱ 49 │   trainer.fit(model, train_loader, val_loader)                                            │
│   50                                                                                             │
│   51                                                                                             │
│   52 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/pytorch_lightning/tra │
│ iner/trainer.py:520 in fit                                                                       │
│                                                                                                  │
│    517 │   │   """                                                                               │
│    518 │   │   model = _maybe_unwrap_optimized(model)                                            │
│    519 │   │   self.strategy._lightning_module = model                                           │
│ ❱  520 │   │   call._call_and_handle_interrupt(                                                  │
│    521 │   │   │   self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule,  │
│    522 │   │   )                                                                                 │
│    523                                                                                           │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/pytorch_lightning/tra │
│ iner/call.py:64 in _call_and_handle_interrupt                                                    │
│                                                                                                  │
│    61 │   │   │   │   logger.finalize("failed")                                                  │
│    62 │   except BaseException as exception:                                                     │
│    63 │   │   trainer.state.status = TrainerStatus.INTERRUPTED                                   │
│ ❱  64 │   │   _call_callback_hooks(trainer, "on_exception", exception)                           │
│    65 │   │   trainer.strategy.on_exception(exception)                                           │
│    66 │   │   for logger in trainer.loggers:                                                     │
│    67 │   │   │   logger.finalize("failed")                                                      │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/pytorch_lightning/tra │
│ iner/call.py:190 in _call_callback_hooks                                                         │
│                                                                                                  │
│   187 │   │   fn = getattr(callback, hook_name)                                                  │
│   188 │   │   if callable(fn):                                                                   │
│   189 │   │   │   with trainer.profiler.profile(f"[Callback]{callback.state_key}.{hook_name}")   │
│ ❱ 190 │   │   │   │   fn(trainer, trainer.lightning_module, *args, **kwargs)                     │
│   191 │                                                                                          │
│   192 │   if pl_module:                                                                          │
│   193 │   │   # restore current_fx when nested context                                           │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/pytorch_lightning/cal │
│ lbacks/progress/rich_progress.py:574 in on_exception                                             │
│                                                                                                  │
│   571 │   │   self._stop_progress()                                                              │
│   572 │                                                                                          │
│   573 │   def on_exception(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule", excep   │
│ ❱ 574 │   │   self._stop_progress()                                                              │
│   575 │                                                                                          │
│   576 │   def configure_columns(self, trainer: "pl.Trainer") -> list:                            │
│   577 │   │   return [                                                                           │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/pytorch_lightning/cal │
│ lbacks/progress/rich_progress.py:554 in _stop_progress                                           │
│                                                                                                  │
│   551 │                                                                                          │
│   552 │   def _stop_progress(self) -> None:                                                      │
│   553 │   │   if self.progress is not None:                                                      │
│ ❱ 554 │   │   │   self.progress.stop()                                                           │
│   555 │   │   │   # # signals for progress to be re-initialized for next stages                  │
│   556 │   │   │   self._progress_stopped = True                                                  │
│   557                                                                                            │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/rich/progress.py:1160 │
│ in stop                                                                                          │
│                                                                                                  │
│   1157 │                                                                                         │
│   1158 │   def stop(self) -> None:                                                               │
│   1159 │   │   """Stop the progress display."""                                                  │
│ ❱ 1160 │   │   self.live.stop()                                                                  │
│   1161 │   │   if not self.console.is_interactive:                                               │
│   1162 │   │   │   self.console.print()                                                          │
│   1163                                                                                           │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/rich/live.py:150 in   │
│ stop                                                                                             │
│                                                                                                  │
│   147 │   │   │   with self.console:                                                             │
│   148 │   │   │   │   try:                                                                       │
│   149 │   │   │   │   │   if not self._alt_screen and not self.console.is_jupyter:               │
│ ❱ 150 │   │   │   │   │   │   self.refresh()                                                     │
│   151 │   │   │   │   finally:                                                                   │
│   152 │   │   │   │   │   self._disable_redirect_io()                                            │
│   153 │   │   │   │   │   self.console.pop_render_hook()                                         │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/rich/live.py:221 in   │
│ refresh                                                                                          │
│                                                                                                  │
│   218 │   def refresh(self) -> None:                                                             │
│   219 │   │   """Update the display of the Live Render."""                                       │
│   220 │   │   with self._lock:                                                                   │
│ ❱ 221 │   │   │   self._live_render.set_renderable(self.renderable)                              │
│   222 │   │   │   if self.console.is_jupyter:  # pragma: no cover                                │
│   223 │   │   │   │   try:                                                                       │
│   224 │   │   │   │   │   from IPython.display import display                                    │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/rich/live.py:203 in   │
│ renderable                                                                                       │
│                                                                                                  │
│   200 │   │   Returns:                                                                           │
│   201 │   │   │   RenderableType: Displayed renderable.                                          │
│   202 │   │   """                                                                                │
│ ❱ 203 │   │   renderable = self.get_renderable()                                                 │
│   204 │   │   return Screen(renderable) if self._alt_screen else renderable                      │
│   205 │                                                                                          │
│   206 │   def update(self, renderable: RenderableType, *, refresh: bool = False) -> None:        │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/rich/live.py:98 in    │
│ get_renderable                                                                                   │
│                                                                                                  │
│    95 │                                                                                          │
│    96 │   def get_renderable(self) -> RenderableType:                                            │
│    97 │   │   renderable = (                                                                     │
│ ❱  98 │   │   │   self._get_renderable()                                                         │
│    99 │   │   │   if self._get_renderable is not None                                            │
│   100 │   │   │   else self._renderable                                                          │
│   101 │   │   )                                                                                  │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/rich/progress.py:1539 │
│ in get_renderable                                                                                │
│                                                                                                  │
│   1536 │                                                                                         │
│   1537 │   def get_renderable(self) -> RenderableType:                                           │
│   1538 │   │   """Get a renderable for the progress display."""                                  │
│ ❱ 1539 │   │   renderable = Group(*self.get_renderables())                                       │
│   1540 │   │   return renderable                                                                 │
│   1541 │                                                                                         │
│   1542 │   def get_renderables(self) -> Iterable[RenderableType]:                                │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/rich/progress.py:1544 │
│ in get_renderables                                                                               │
│                                                                                                  │
│   1541 │                                                                                         │
│   1542 │   def get_renderables(self) -> Iterable[RenderableType]:                                │
│   1543 │   │   """Get a number of renderables for the progress display."""                       │
│ ❱ 1544 │   │   table = self.make_tasks_table(self.tasks)                                         │
│   1545 │   │   yield table                                                                       │
│   1546 │                                                                                         │
│   1547 │   def make_tasks_table(self, tasks: Iterable[Task]) -> Table:                           │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/rich/progress.py:1568 │
│ in make_tasks_table                                                                              │
│                                                                                                  │
│   1565 │   │                                                                                     │
│   1566 │   │   for task in tasks:                                                                │
│   1567 │   │   │   if task.visible:                                                              │
│ ❱ 1568 │   │   │   │   table.add_row(                                                            │
│   1569 │   │   │   │   │   *(                                                                    │
│   1570 │   │   │   │   │   │   (                                                                 │
│   1571 │   │   │   │   │   │   │   column.format(task=task)                                      │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/rich/progress.py:1573 │
│ in <genexpr>                                                                                     │
│                                                                                                  │
│   1570 │   │   │   │   │   │   (                                                                 │
│   1571 │   │   │   │   │   │   │   column.format(task=task)                                      │
│   1572 │   │   │   │   │   │   │   if isinstance(column, str)                                    │
│ ❱ 1573 │   │   │   │   │   │   │   else column(task)                                             │
│   1574 │   │   │   │   │   │   )                                                                 │
│   1575 │   │   │   │   │   │   for column in self.columns                                        │
│   1576 │   │   │   │   │   )                                                                     │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/rich/progress.py:524  │
│ in __call__                                                                                      │
│                                                                                                  │
│    521 │   │   │   │   if timestamp + self.max_refresh > current_time:                           │
│    522 │   │   │   │   │   return renderable                                                     │
│    523 │   │                                                                                     │
│ ❱  524 │   │   renderable = self.render(task)                                                    │
│    525 │   │   self._renderable_cache[task.id] = (current_time, renderable)                      │
│    526 │   │   return renderable                                                                 │
│    527                                                                                           │
│                                                                                                  │
│ /mnt/device/home/Rich/miniconda3/envs/PyTorch/lib/python3.10/site-packages/pytorch_lightning/cal │
│ lbacks/progress/rich_progress.py:155 in render                                                   │
│                                                                                                  │
│   152 │   │   │   self._metrics = metrics                                                        │
│   153 │   │                                                                                      │
│   154 │   │   def render(self, task: "Task") -> Text:                                            │
│ ❱ 155 │   │   │   assert isinstance(self._trainer.progress_bar_callback, RichProgressBar)        │
│   156 │   │   │   if (                                                                           │
│   157 │   │   │   │   self._trainer.state.fn != "fit"                                            │
│   158 │   │   │   │   or self._trainer.sanity_checking  

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by darkestfloyd** [comment]
FYI This issue still exists on version 2.1.1

**Comment by insomniaaac** [comment]
FYI This issue still exists on version 2.5.0
