### ISSUE TITLE
TypeError: `model` must be a `LightningModule` (my model inherits from one)

### ISSUE THREAD

**Issue by danbider** [Lightning-AI/lightning#17153]
### Bug description

maybe i'm missing something, but passing a model to trainer yields the following `TypeError`
```
TypeError: `model` must be a `LightningModule` or `torch._dynamo.OptimizedModule`, got `HeatmapTracker`
```
but `model`, in my case, is an instance of a `LightningModule`. 

to reproduce my specific example
```
git clone https://github.com/danbider/lightning-pose.git
cd lightning-pose
pip install -r requirements.txt # hope these are fine for PL 2.0
git checkout hotfix/jaxtyping
pytest tests/models
```
but just try calling `trainer.fit` on any model that is an instance of `LightningModule` and tell me if i'm missing something

### Error messages and logs

```
TypeError: `model` must be a `LightningModule` or `torch._dynamo.OptimizedModule`, got `HeatmapTracker`
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by carmocca** [comment]
@danbider I just tried the steps above but I'm getting a segfault (core dumped).

Any chance you can provide a simpler way to reproduce the issue?

**Comment by carmocca** [comment]
I found the problem. You are missing imports in your library.

`import lightning.pytorch` != `import pytorch_lightning`

These cannot be mixed, as they are rooted in different classes. You must use only one way of importing.

So the problem comes from this mixup in your library: https://github.com/danbider/lightning-pose/blob/8ae2325eff04fb6ac971e0dab81888dad90d8b83/lightning_pose/models/base.py#L4


Notice how this fails

```python
from unittest.mock import Mock

from lightning import LightningModule
from lightning_pose.models.heatmap_tracker import HeatmapTracker

model = HeatmapTracker(1, Mock())
print(isinstance(model, LightningModule))
```
