### ISSUE TITLE
How to transfer a tensor  on cpu to the multiple gpu devices?

### ISSUE THREAD

**Issue by emilyemliyM** [Lightning-AI/lightning#17164]
### Bug description

If I make a a new torch.tensor during the network model, like torch.ones()
And I have two gpus,

SO how to move the cpu tensor to the 2 gpus?

### How to reproduce the bug

```python
If I make a a new torch.tensor during the network model, like torch.ones()
And I have two gpus,

SO how to move the cpu tensor to the 2 gpus?
```

### Error messages and logs

If I make a a new torch.tensor during the network model, like torch.ones()
And I have two gpus,

SO how to move the cpu tensor to the 2 gpus?

### Environment

pytorchlightning 1.2.5

**Comment by awaelchli** [comment]
Using

```py
new_tensor = torch.ones(2, 2, device=self.device)
```

`self.device` is available in LightningModule hooks (e.g., training_step).

Docs:
https://lightning.ai/docs/pytorch/stable/advanced/speed.html#transferring-tensors-to-device
https://lightning.ai/docs/pytorch/stable/starter/converting.html#remove-any-cuda-or-to-device-calls
