### ISSUE TITLE
`ModelCheckpoint` not saving if `self.automatic_optimization = False`

### ISSUE THREAD

**Issue by sssilvar** [Lightning-AI/lightning#17167]
### Bug description

When using the `ModelCheckpoint` callback, and if I'm using my own optimization scheme, meaning `self.automatic_optimization = False` in my `LightningModule`, no model is saved.

## Explaination
`global_step` does not increase automatically making the following condition false all the time: https://github.com/Lightning-AI/lightning/blob/01834c8529a7b92705f4c9323051237ccf054e7c/src/lightning/pytorch/callbacks/model_checkpoint.py#L300

### How to reproduce the bug

```python
class LitTabularVAE(pl.LightningModule):
    def __init__(self, ...):
        super().__init__()
        self.automatic_optimization = False

mo_ckpt = ModelCheckpoint(monitor='val_loss')
trainer = pl.Trainer(logger=logger, callbacks=[mo_ckpt])
trainer.fit(model, datamodule=data_module)


`
```

### Error messages and logs

```
# Error messages and logs here please
```
None. There should be at least a warning that no model was saved. 

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component: ModelCheckpoint
#- PyTorch Lightning Version: '2.0.0'
```

</details>

cc @awaelchli @borda

**Comment by bwdeng20** [comment]
I wa stuck by a similar problem this afternoon and I finally figured it out.

To everyone who has encountered a similar problem:
- In short, make sure your optimizers are wrapped by `LightningOptimizer` before calling `step()`
- In detail, the `global_step`  is associated with `trainer.fit_loop.epoch_loop .manual_optimization.optim_step_progress`, which controls the `global_step` and only updates it if the used `YourLightningModule.optimizers()` are all wrapped by `Lightning.pytorch.core.optimizer.LightningOptimizer`

**Comment by awaelchli** [comment]
@bwdeng20 Sorry for the late response. I would be curious what was the reason the optimizer wasn't wrapped by LightningOptimizer initially in your code? In manual optimization, per our docs, the user should call `self.optimizers()` in the training step method and then work with the optimizer returned there, which counts the steps.

**Comment by Crazy-LittleBoy** [comment]
> I wa stuck by a similar problem this afternoon and I finally figured it out.
> 
> To everyone who has encountered a similar problem:
> 
> * In short, make sure your optimizers are wrapped by `LightningOptimizer` before calling `step()`
> * In detail, the `global_step`  is associated with `trainer.fit_loop.epoch_loop .manual_optimization.optim_step_progress`, which controls the `global_step` and only updates it if the used `YourLightningModule.optimizers()` are all wrapped by `Lightning.pytorch.core.optimizer.LightningOptimizer`

thx, bro
