### ISSUE TITLE
FP8 mixed precision via nvidia's Transformer Engine

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lightning#17172]
### Description & Motivation

Support https://docs.nvidia.com/deeplearning/transformer-engine/user-guide/index.html

### Pitch

Write a precision plugin using the library above that is enabled via:
- `precision="8-mixed"`
- `precision="8-mixed-transformer-engine"`

Why both? So that if PyTorch implements this, we can switch the implementation for the `"8-mixed"` key but keep the "8-mixed-transformer-engine"` key without breaking changes

The implementation is straightforward. The library only requires enabling an autocast context manager

### Alternatives

Don't implement this until it's vendored by PyTorch, if that ever happens.

cc @borda @carmocca @justusschock @awaelchli

**Comment by awaelchli** [comment]
> The library only requires enabling an autocast context manager

There is one more thing. The user needs to replace their layers with the custom ones from the library. What's the plan here? Will the plugin implement the `init_context()` manager? On the other hand, one might not want to replace all layers. If this is left to the user, then there is a lot less value in adding the plugin.

**Comment by carmocca** [comment]
Yes, we'll need to implement a replacement mechanism. The plugin can have a flag to disable it if necessary

**Comment by carmocca** [comment]
Actually `convert_module` might be a better fit than `init_context` if we prefer replacing existing layers than patching the `torch.nn` classes.

**Comment by SinanAkkoyun** [comment]
Hello, are there any estimations on when/if at all this will be implemented?

And is it known how fast the inference speedup really is on an H100? That would really help me, thanks!

**Comment by nanand2** [comment]
Any update on support for this?

**Comment by carmocca** [comment]
@nanand2 Our access to H100s is very limited so we haven't merged this yet. However, the branch https://github.com/Lightning-AI/lightning/tree/carmocca/transformer-engine should be usable if you want to play with it right now

**Comment by nanand2** [comment]
Great, thanks!
