### ISSUE TITLE
W&B Logger - How to log a histogram? 

### ISSUE THREAD

**Issue by RylanSchaeffer** [Lightning-AI/lightning#17171]
### 📚 Documentation

Lightning AI has a W&B logger (https://lightning.ai/docs/pytorch/latest/extensions/generated/pytorch_lightning.loggers.WandbLogger.html), but the documentation doesn't specify how to log a W&B Histogram. Can someone please add documentation explaining how to do that?

cc @borda

**Comment by hynky1999** [comment]
The lighting wandb wrapper doesn't support wand.plot which you need for histograms. So I think it's not just a docs issues. However the implementation should be straightforward.

**Comment by hynky1999** [comment]
The WandbLogger exposes experiment property. That is your global wandb object with some insurances (only runs on rank0). 

So something like this should work.

```
logger = WandbLogger(project="debug")
import numpy as np
scores = np.random.rand(100, 1)
hist_plot = wandb.plot.histogram(table, "scores")
logger.experiment.log({"histogram": hist_plot})
```
Which created this chart.
![Screenshot_20230322_220652](https://user-images.githubusercontent.com/39408646/227038316-d14f83b3-3f92-4298-9c62-ab093a979f61.png)


In model the logger should be accessible as ```self.logger```.
