### ISSUE TITLE
Upgrade NeptuneLogger to use newly released "neptune" package, not old neptune-client

### ISSUE THREAD

**Issue by angadkalra** [Lightning-AI/lightning#17184]
### Description & Motivation

Neptune has provided a major release to neptune 1.0, while lightning is still using neptune-client. Please consider upgrading the lightning code to use "neptune" instead of "neptune-client".

cc @borda @Blaizzy

**Comment by awaelchli** [comment]
Hi @angadkalra 
This was recently merged here: #16761
Is this what you were looking for?

**Comment by angadkalra** [comment]
> Hi @angadkalra This was recently merged here: #16761 Is this what you were looking for?

Looks like thats it! Thanks!
