### ISSUE TITLE
training_batch_end does not seem to be called in lightning 2.0

### ISSUE THREAD

**Issue by idc9** [Lightning-AI/lightning#17187]
### Bug description

The new [documentation](https://lightning.ai/docs/pytorch/latest/upgrade/from_1_9.html) says `training_step_end` should be replaced with `training_batch_end`. However, the `training_batch_end` function does not seem to be called. In the below example I implmented training_batch_end such that it will throw an error when it is called. The code runs fine i.e. training_batch_end() isn't called. 

### How to reproduce the bug

```python
python
import os

import torch
from torch.utils.data import DataLoader, Dataset

from lightning.pytorch import LightningModule, Trainer


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)
    
    def training_batch_end(self, outputs):
        # Code should break!
        1 / 0 

def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    test_data = DataLoader(RandomDataset(32, 64), batch_size=2)

    model = BoringModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        limit_test_batches=1,
        num_sanity_val_steps=0,
        max_epochs=1,
        enable_model_summary=False,
    )
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
    trainer.test(model, dataloaders=test_data)


if __name__ == "__main__":
    run()
```

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

lightning 2.0, python 3.8.12

cc @borda

**Comment by carmocca** [comment]
The documentation is wrong, it should say `on_train_batch_end`

The list of hooks can be found at https://lightning.ai/docs/pytorch/latest/common/lightning_module.html#hooks

Would you like to open a PR fixing the documentation?

**Comment by idc9** [comment]
done https://github.com/Lightning-AI/lightning/pull/17188

**Comment by webpolis** [comment]
@carmocca just wondering, what's the order of execution in latest Lightning versions vs 1.9.2?

Trainer's Callback `on_train_batch_end` and then `LightningModule`.`on_train_batch_end` ?

I'm trying to port https://github.com/BlinkDL/RWKV-LM to a most recent Lightning version and according to its code, it seems the old `training_step_end` was running first. Am I right?

**Comment by carmocca** [comment]
You can find the list here: https://lightning.ai/docs/pytorch/stable/common/lightning_module.html#hooks. For the same name, Callback goes first.

Yes, `training_step_end` was running first. Can you share its implementation?
