### ISSUE TITLE
Warning says to upgrade checkpoint via "--file", running command says "unrecognized arguments: --file"

### ISSUE THREAD

**Issue by drscotthawley** [Lightning-AI/lightning#17220]
### Bug description

Warning message printed by `.load_from_checkpoint` says 

```
Lightning automatically upgraded your loaded checkpoint from v1.7.4 to v1.9.0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file ../../checkpoints/stacked-diffae-more-310k.ckpt`
```
Upon running the suggested command, one obtains the error message:

```
usage: upgrade_checkpoint.py [-h] [--extension EXTENSION] path
upgrade_checkpoint.py: error: unrecognized arguments: --file
```

### How to reproduce the bug

```python
Do exactly what the warning message says
```

### Error messages and logs

```
upgrade_checkpoint.py: error: unrecognized arguments: --file
```

### Environment

<details>
  <summary>Current environment</summary>

```
lightning-utilities        0.6.0.post0
pytorch-lightning          1.9.2
torch                      1.13.1
torchaudio                 0.13.1
torchmetrics               0.11.1
torchvision                0.14.1
Installed via pip
CentOS
NVIDIA A10
Python 3.10.1
```

</details>

### More info

The 'workaround' (if you can call it that) for users is easy: we just remove the "--file" part, which the "usage" message does not include.

If this has already been fixed in a newer lightning, apologies, feel free to close. 

cc @borda

**Comment by carmocca** [comment]
Would you like to send a PR with your suggested workaround?

**Comment by ryan597** [comment]
I also came across this bug after updating to 2.0.  I went ahead and made a pull request for the changes you suggested if that's okay.
