### ISSUE TITLE
Setting `accelerator=None` breaks, not passing argument works

### ISSUE THREAD

**Issue by jlehrer1** [Lightning-AI/lightning#17255]
### Bug description

The default for the `pl.Trainer` is to set `accelerator=None` and handle the default downstream. However, if the user passes `None` directly or in a conditional such as 
```
trainer = pl.Trainer(
    accelerator="gpu" if torch.cuda.is_available() else None,
    devices=1 if torch.cuda.is_available() else None
)
```

This errors with 
```
Traceback (most recent call last):
  File "/src/main.py", line 36, in <module>
    trainer = pl.Trainer(
  File "/home/user/micromamba/lib/python3.9/site-packages/pytorch_lightning/utilities/argparse.py", line 69, in insert_env_defaults
    return fn(self, **kwargs)
  File "/home/user/micromamba/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 393, in __init__
    self._accelerator_connector = _AcceleratorConnector(
  File "/home/user/micromamba/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 140, in __init__
    self._check_config_and_set_final_flags(
  File "/home/user/micromamba/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 221, in _check_config_and_set_final_flags
    raise ValueError(
ValueError: You selected an invalid accelerator name: `accelerator=None`. Available names are: auto, cpu, cuda, hpu, ipu, mps, tpu.
```
Strangely, if I just leave the argument out entirely then training proceeds as normal. This is a very strange bug and something I've only experienced on the latest version of lightning.

### How to reproduce the bug

Instantiate a trainer object and call `.fit(model, data)`

### Environment

* CUDA:
        - GPU:               None
        - available:         False
        - version:           11.2
* Lightning:
        - lightning:         2.0.1
        - lightning-cloud:   0.5.32
        - lightning-utilities: 0.8.0
        - pytorch-lightning: 2.0.1
        - torch:             1.13.0.post200
        - torchmetrics:      0.11.4
        - torchvision:       0.14.0a0+2ba5a5d
* Packages:
        - aiohttp:           3.8.4
        - aiosignal:         1.3.1
        - anyio:             3.6.2
        - appdirs:           1.4.4
        - arrow:             1.2.3
        - async-timeout:     4.0.2
        - attrs:             22.2.0
        - beautifulsoup4:    4.12.0
        - blessed:           1.20.0
        - boto3:             1.26.104
        - botocore:          1.29.104
        - brotlipy:          0.7.0
        - certifi:           2022.12.7
        - cffi:              1.15.1
        - charset-normalizer: 2.1.1
        - click:             8.1.3
        - colorama:          0.4.6
        - conda:             22.11.1
        - conda-package-handling: 2.0.2
        - conda-package-streaming: 0.7.0
        - croniter:          1.3.8
        - cryptography:      38.0.4
        - datasets:          2.11.0
        - dateutils:         0.6.12
        - deepdiff:          6.3.0
        - dill:              0.3.6
        - dnspython:         2.3.0
        - docker-pycreds:    0.4.0
        - email-validator:   1.3.1
        - fastapi:           0.88.0
        - filelock:          3.10.7
        - frozenlist:        1.3.3
        - fsspec:            2023.3.0
        - gitdb:             4.0.10
        - gitpython:         3.1.31
        - h11:               0.14.0
        - httpcore:          0.16.3
        - httptools:         0.5.0
        - httpx:             0.23.3
        - huggingface-hub:   0.13.3
        - idna:              3.4
        - inquirer:          3.1.3
        - itsdangerous:      2.1.2
        - jinja2:            3.1.2
        - jmespath:          1.0.1
        - libmambapy:        1.1.0
        - lightning:         2.0.1
        - lightning-cloud:   0.5.32
        - lightning-utilities: 0.8.0
        - mamba:             1.1.0
        - markdown-it-py:    2.2.0
        - markupsafe:        2.1.2
        - mdurl:             0.1.2
        - multidict:         6.0.4
        - multiprocess:      0.70.14
        - numpy:             1.23.5
        - ordered-set:       4.1.0
        - orjson:            3.8.9
        - packaging:         23.0
        - pandas:            1.5.3
        - pathtools:         0.1.2
        - pillow:            9.2.0
        - pip:               22.3.1
        - pluggy:            1.0.0
        - protobuf:          4.22.1
        - psutil:            5.9.4
        - pyarrow:           11.0.0
        - pycosat:           0.6.4
        - pycparser:         2.21
        - pydantic:          1.10.7
        - pygments:          2.14.0
        - pyjwt:             2.6.0
        - pyopenssl:         22.1.0
        - pysocks:           1.7.1
        - python-dateutil:   2.8.2
        - python-dotenv:     1.0.0
        - python-editor:     1.0.4
        - python-multipart:  0.0.6
        - pytorch-lightning: 2.0.1
        - pytz:              2023.3
        - pyyaml:            6.0
        - readchar:          4.0.5
        - regex:             2023.3.23
        - requests:          2.28.1
        - responses:         0.18.0
        - rfc3986:           1.5.0
        - rich:              13.3.3
        - ruamel.yaml:       0.17.21
        - ruamel.yaml.clib:  0.2.7
        - s3transfer:        0.6.0
        - scipy:             1.9.3
        - sentry-sdk:        1.18.0
        - setproctitle:      1.3.2
        - setuptools:        65.5.1
        - six:               1.16.0
        - sklearn:           0.0.post1
        - smmap:             5.0.0
        - sniffio:           1.3.0
        - soupsieve:         2.4
        - starlette:         0.22.0
        - starsessions:      1.3.0
        - tenacity:          8.2.2
        - tokenizers:        0.13.2
        - toolz:             0.12.0
        - torch:             1.13.0.post200
        - torchmetrics:      0.11.4
        - torchvision:       0.14.0a0+2ba5a5d
        - tqdm:              4.64.1
        - traitlets:         5.9.0
        - transformers:      4.27.4
        - typing-extensions: 4.4.0
        - ujson:             5.7.0
        - urllib3:           1.26.13
        - uvicorn:           0.21.1
        - uvloop:            0.17.0
        - wandb:             0.14.0
        - watchfiles:        0.19.0
        - wcwidth:           0.2.6
        - websocket-client:  1.5.1
        - websockets:        10.4
        - wheel:             0.38.4
        - xxhash:            3.2.0
        - yarl:              1.8.2
        - zstandard:         0.19.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - 
        - processor:         x86_64
        - python:            3.9.15
        - version:           #1 SMP PREEMPT Sat Jul 3 21:50:16 UTC 2021

### More info

This is running in a docker container. The Dockerfile is below:'
```
FROM anibali/pytorch:1.13.0-cuda11.8
USER root

WORKDIR /src

RUN sudo apt-get update
RUN sudo apt-get install -y wget && rm -rf /var/lib/apt/lists/*

RUN sudo apt-get --allow-releaseinfo-change update && \
    sudo apt-get install -y --no-install-recommends \
    curl \
    sudo \
    vim

RUN pip install lightning \
    wandb \
    sklearn \
    boto3 \ 
    tenacity \ 
    pandas \
    datasets \
    transformers

COPY . .
```

cc @justusschock @awaelchli @borda

**Comment by awaelchli** [comment]
The default is not None anymore, [it is "auto"](https://github.com/Lightning-AI/lightning/blob/65eb3e7c456dc572d909362157ee2d29e99e2276/src/lightning/pytorch/trainer/trainer.py#L93). The error you see is from us, the Trainer, and it says that None is not a valid value. 

> ValueError: You selected an invalid accelerator name: `accelerator=None`. Available names are: auto, cpu, cuda, hpu, ipu, mps, tpu.

The available names you can pass in are
accelerator="auto"
accelerator="cpu"
accelerator="cuda"
etc.

In Lightning < 2.0, [the default was None](https://github.com/Lightning-AI/lightning/blob/10914848504d758455d1b56fbae6e7c1b765bb90/src/pytorch_lightning/trainer/trainer.py#LL152C8-L152C63) and acted as "auto".

**Comment by awaelchli** [comment]
@jlehrer1 Does my answer resolve your concerns?
