### ISSUE TITLE
CLI config: streategy `class_path` give value error

### ISSUE THREAD

**Issue by knoriy** [Lightning-AI/lightning#17254]
### Bug description

Is this an expected behaviour when configuring a lightning CLI:

```
trainer:
  strategy:
    - class_path: pytorch_lightning.strategies.DDPStrategy
      init_args:
        find_unused_parameters: True
```
Error:
```
test.py [options] fit: error: Parser key "trainer.strategy":
  Does not validate against any of the Union subtypes
  Subtypes: (<class 'str'>, <class 'pytorch_lightning.strategies.strategy.Strategy'>)
  Errors:
    - Expected a <class 'str'>
    - Not a valid Strategy
    Subclass types expect one of:
    - a class path (str)
    - a dict with class_path entry
    - a dict without class_path but with init_args entry (class path given previously)
  Given value type: <class 'list'>
  Given value: [{'class_path': 'pytorch_lightning.strategies.DDPStrategy', 'init_args': {'find_unused_parameters': True}}]
```

### How to reproduce the bug

```python
# main.py
from lightning.pytorch.cli import LightningCLI

# simple demo classes for your convenience
from lightning.pytorch.demos.boring_classes import DemoModel, BoringDataModule


def cli_main():
    cli = LightningCLI(DemoModel, BoringDataModule)
    # note: don't call fit!!


if __name__ == "__main__":
    cli_main()


config:

```
seed_everything: true
trainer:
  strategy:
    - class_path: pytorch_lightning.strategies.DDPStrategy
      init_args:
        find_unused_parameters: True

```
```

### Error messages and logs

```
test.py [options] fit: error: Parser key "trainer.strategy":
  Does not validate against any of the Union subtypes
  Subtypes: (<class 'str'>, <class 'pytorch_lightning.strategies.strategy.Strategy'>)
  Errors:
    - Expected a <class 'str'>
    - Not a valid Strategy
    Subclass types expect one of:
    - a class path (str)
    - a dict with class_path entry
    - a dict without class_path but with init_args entry (class path given previously)
  Given value type: <class 'list'>
  Given value: [{'class_path': 'pytorch_lightning.strategies.DDPStrategy', 'init_args': {'find_unused_parameters': True}}]
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @carmocca @mauvilsa

**Comment by mauvilsa** [comment]
There is no bug. The problem is just that the config file is wrong. The type for strategy is `Union[str, Strategy]`, see the CLI's `--help` output or see [trainer.py#L94](https://github.com/Lightning-AI/lightning/blob/9b69d512d97707124e2865883397f2a1fd859c2a/src/lightning/pytorch/trainer/trainer.py#L94). In the config a list is given, which is not expected.

**Comment by knoriy** [comment]
Thank you for getting back to me. I see what you mean. In this case, what would be the appropriate way to configure the init args from the `config.yaml`?

Would it not also be best to maintain a uniform manner of using `class_paths` for controlling PL builtins as demonstrated in the [doc](https://lightning.ai/docs/pytorch/stable/cli/lightning_cli_advanced.html)?

I would appreciate your comment.

**Comment by mauvilsa** [comment]
Not sure what you mean. The fix is only removing the dash `-` before the class_path:

```python
trainer:
  strategy:
    class_path: pytorch_lightning.strategies.DDPStrategy
    init_args:
      find_unused_parameters: True
```
Unfortunately it is not immediately obviously from the error that this is the problem. The issue is that the code is generic for all type annotations. When there is a `Union`, the error for each type in the `Union` is shown. The indentation in the error is wrong and that I can fix. But not sure how to make it more obvious.

**Comment by knoriy** [comment]
Thank you for clarifying. I understand what you mean.
