### ISSUE TITLE
Parameters to `MixedPrecisionPlugin` are not validated and do not match doc string

### ISSUE THREAD

**Issue by akreuzer** [Lightning-AI/lightning#17288]
### Bug description

The `precision` parameter to `MixedPrecisionPlugin` changed in the upgrade to Lightning 2.0
Beforehand the expected values were `16, "16", "bf16"`, and now they are `"16-mixed", "bf16-mixed"`.

The first problem is that this does not match the doc-string of the function. So it would be necessary to update that.

The second problem is that if one inputs the previously valid precision parameter results in a silently decreased performance. In detail, if `precision` is set to `16` no gradient scaler is selected in the `__init__` function, see https://github.com/Lightning-AI/lightning/blob/c2d9ec4e1b9ab32b222630f3d094e657c65324f8/src/lightning/pytorch/plugins/precision/amp.py#L44-L49
However, types a still changed, see
https://github.com/Lightning-AI/lightning/blob/c2d9ec4e1b9ab32b222630f3d094e657c65324f8/src/lightning/pytorch/plugins/precision/amp.py#L101-L104

Thus gradients do not match.

It would be best if the parameter are just validated in the __init__ function.

### What version are you seeing the problem on?

2.0+

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @carmocca @justusschock @awaelchli

**Comment by carmocca** [comment]
I agree. Would you like to open a PR?

**Comment by akreuzer** [comment]
Yes I can do a PR. (I will probably need one or two weeks to find some time.)
