### ISSUE TITLE
Page to tutorials overview page no longer exists

### ISSUE THREAD

**Issue by gkroiz** [Lightning-AI/lightning#17286]
### 📚 Documentation

As of [commit #9b168dc](https://github.com/Lightning-AI/lightning/commit/9b168dcf9bd763eb7cf7c71cf18469bdd0de9cc4), `tutorials.rst` was deleted. Was this intended? https://lightning.ai/docs/pytorch/latest/tutorials.html no longer exists and can easily be accessed when clicking on `Hands-on Examples` at the bottom of https://lightning.ai/docs/pytorch/latest/

cc @borda

**Comment by Borda** [comment]
Good catch, lets me revert it in #17311
