### ISSUE TITLE
The tensor storage device in the custom loss function is different from the model

### ISSUE THREAD

**Issue by ZedRover** [Lightning-AI/lightning#17299]
### Bug description

I didn't find any problems at first when I tried to use a custom loss function, but when I tried to create a new tensor in the forward function of the loss function, I got an error

`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`

### What version are you seeing the problem on?

2.0+

### How to reproduce the bug

```python
class AvgReturnTop10Loss(nn.Module):
    def __init__(self, alpha=5):
        super(AvgReturnTop10Loss, self).__init__()
        self.alpha = alpha

    def forward(self, y_pred: torch.Tensor, y_true: torch.Tensor) -> torch.Tensor:
        errors = torch.pow(y_true - y_pred, 2)

        top_10_percent = int(y_pred.size(0) * 0.1)
        _, indices = torch.topk(y_pred, top_10_percent)

        penalty_factor = torch.ones(
            y_pred.size(0), dtype=torch.float32, 
        ) # error occur from this line

        weighted_errors = penalty_factor * errors

        loss = torch.mean(torch.abs(weighted_errors))
        return loss
```

### Error messages and logs

```
# Error messages and logs here please
```
File "xxx/common.py", line 203, in forward
    weighted_errors = penalty_factor * errors
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### Environment

<details>
  <summary>Current environment</summary>

* CUDA:
        - GPU:
                - NVIDIA GeForce RTX 3080 Ti
                - NVIDIA GeForce RTX 3080 Ti
                - NVIDIA GeForce RTX 3080 Ti
                - NVIDIA GeForce RTX 3080 Ti
        - available:         True
        - version:           11.7
* Lightning:
        - audtorch:          0.6.4
        - lightning:         2.0.0
        - lightning-cloud:   0.5.31
        - lightning-utilities: 0.8.0
        - pytorch-lightning: 2.0.0
        - torch:             2.0.0+cu117
        - torchaudio:        2.0.1+cu117
        - torchmetrics:      0.11.4
        - torchsort:         0.1.9
        - torchvision:       0.15.1+cu117
* Packages:
        - absl-py:           1.4.0
        - aiohttp:           3.8.4
        - aiohttp-cors:      0.7.0
        - aiosignal:         1.3.1
        - alembic:           1.10.2
        - anyio:             3.6.2
        - appdirs:           1.4.4
        - argon2-cffi:       21.3.0
        - argon2-cffi-bindings: 21.2.0
        - arrow:             1.2.3
        - asttokens:         2.0.5
        - astunparse:        1.6.3
        - async-timeout:     4.0.2
        - attrs:             22.2.0
        - audeer:            1.19.0
        - audiofile:         1.2.1
        - audioread:         3.0.0
        - audmath:           1.2.1
        - audtorch:          0.6.4
        - autogluon.common:  0.7.0
        - autogluon.core:    0.7.0
        - autogluon.eda:     0.7.0
        - autogluon.features: 0.7.0
        - autogluon.tabular: 0.7.0
        - backcall:          0.2.0
        - bandit:            1.7.5
        - beautifulsoup4:    4.11.2
        - black:             23.1.0
        - bleach:            6.0.0
        - blessed:           1.20.0
        - boto3:             1.26.94
        - botocore:          1.29.94
        - bottle:            0.12.25
        - cachetools:        5.3.0
        - certifi:           2022.12.7
        - cffi:              1.15.1
        - charset-normalizer: 2.1.1
        - click:             8.1.3
        - cloudpickle:       2.2.1
        - cmaes:             0.9.1
        - cmake:             3.25.0
        - colorful:          0.5.5
        - colorlog:          6.7.0
        - comm:              0.1.2
        - contourpy:         1.0.7
        - convertdate:       2.4.0
        - croniter:          1.3.8
        - cycler:            0.11.0
        - dask:              2023.3.1
        - dateutils:         0.6.12
        - debugpy:           1.5.1
        - decorator:         5.1.1
        - deepdiff:          6.3.0
        - defusedxml:        0.7.1
        - distlib:           0.3.6
        - distributed:       2023.3.1
        - dnspython:         2.3.0
        - docker-pycreds:    0.4.0
        - email-validator:   1.3.1
        - entrypoints:       0.4
        - executing:         0.8.3
        - fast-soft-sort:    0.1
        - fastapi:           0.88.0
        - fastjsonschema:    2.16.3
        - featuretools:      1.23.0
        - filelock:          3.9.0
        - flatbuffers:       23.3.3
        - fonttools:         4.39.2
        - fqdn:              1.5.1
        - frozenlist:        1.3.3
        - fsspec:            2023.3.0
        - gast:              0.4.0
        - gitdb:             4.0.10
        - gitpython:         3.1.31
        - glances:           3.3.1.1
        - google-api-core:   2.11.0
        - google-auth:       2.16.2
        - google-auth-oauthlib: 0.4.6
        - google-pasta:      0.2.0
        - googleapis-common-protos: 1.58.0
        - gpustat:           1.0.0
        - greenlet:          2.0.2
        - grpcio:            1.51.3
        - h11:               0.14.0
        - h5py:              3.8.0
        - heapdict:          1.0.1
        - hijri-converter:   2.2.4
        - holidays:          0.21.13
        - html2text:         2020.1.16
        - httpcore:          0.16.3
        - httptools:         0.5.0
        - httpx:             0.23.3
        - idna:              3.4
        - importlib-metadata: 6.1.0
        - importlib-resources: 5.12.0
        - inquirer:          3.1.3
        - ipykernel:         6.19.2
        - ipython:           8.10.0
        - ipython-genutils:  0.2.0
        - ipywidgets:        8.0.4
        - isoduration:       20.11.0
        - itsdangerous:      2.1.2
        - jedi:              0.18.1
        - jinja2:            3.1.2
        - jmespath:          1.0.1
        - joblib:            1.2.0
        - jsonpointer:       2.3
        - jsonschema:        4.17.3
        - jupyter:           1.0.0
        - jupyter-client:    7.4.9
        - jupyter-console:   6.6.3
        - jupyter-core:      5.3.0
        - jupyter-events:    0.6.3
        - jupyter-server:    2.5.0
        - jupyter-server-terminals: 0.4.4
        - jupyterlab-pygments: 0.2.2
        - jupyterlab-widgets: 3.0.5
        - keras:             2.11.0
        - kiwisolver:        1.4.4
        - korean-lunar-calendar: 0.3.1
        - lazy-loader:       0.1
        - libclang:          15.0.6.1
        - librosa:           0.10.0.post2
        - lightgbm:          3.3.5
        - lightning:         2.0.0
        - lightning-cloud:   0.5.31
        - lightning-utilities: 0.8.0
        - lit:               15.0.7
        - llvmlite:          0.39.1
        - locket:            1.0.0
        - mako:              1.2.4
        - markdown:          3.4.1
        - markdown-it-py:    2.2.0
        - markupsafe:        2.1.2
        - matplotlib:        3.6.3
        - matplotlib-inline: 0.1.6
        - mdurl:             0.1.2
        - missingno:         0.5.2
        - mistune:           2.0.5
        - modin:             0.19.0
        - modin-spreadsheet: 0.1.2
        - mpi4py-mpich:      3.1.2
        - mpmath:            1.2.1
        - msgpack:           1.0.5
        - multidict:         6.0.4
        - mypy-extensions:   1.0.0
        - nbclassic:         0.5.3
        - nbclient:          0.7.2
        - nbconvert:         7.2.10
        - nbformat:          5.7.3
        - nest-asyncio:      1.5.6
        - networkx:          2.8.8
        - notebook-shim:     0.2.2
        - numba:             0.56.4
        - numpy:             1.23.5
        - nvidia-ml-py:      11.495.46
        - oauthlib:          3.2.2
        - opencensus:        0.11.2
        - opencensus-context: 0.1.3
        - opt-einsum:        3.3.0
        - optuna:            3.1.0
        - optuna-dashboard:  0.9.0
        - ordered-set:       4.1.0
        - orjson:            3.8.7
        - packaging:         23.0
        - pandas:            1.5.3
        - pandocfilters:     1.5.0
        - parso:             0.8.3
        - partd:             1.3.0
        - pathspec:          0.11.1
        - pathtools:         0.1.2
        - pbr:               5.11.1
        - pexpect:           4.8.0
        - phik:              0.12.3
        - pickleshare:       0.7.5
        - pillow:            9.3.0
        - pip:               23.0.1
        - platformdirs:      2.5.2
        - plumbum:           1.8.1
        - pooch:             1.6.0
        - prometheus-client: 0.16.0
        - prompt-toolkit:    3.0.36
        - protobuf:          3.19.6
        - psutil:            5.9.0
        - ptyprocess:        0.7.0
        - pure-eval:         0.2.2
        - py-spy:            0.3.14
        - pyarrow:           11.0.0
        - pyasn1:            0.4.8
        - pyasn1-modules:    0.2.8
        - pybind11:          2.10.4
        - pycparser:         2.21
        - pydantic:          1.10.6
        - pygments:          2.14.0
        - pyjwt:             2.6.0
        - pymeeus:           0.5.12
        - pyparsing:         3.0.9
        - pypi-search:       1.2.1
        - pyrsistent:        0.19.3
        - python-dateutil:   2.8.2
        - python-dotenv:     1.0.0
        - python-editor:     1.0.4
        - python-json-logger: 2.0.7
        - python-multipart:  0.0.6
        - pytorch-lightning: 2.0.0
        - pytz:              2022.7.1
        - pyyaml:            6.0
        - pyzmq:             25.0.1
        - qtconsole:         5.4.1
        - qtpy:              2.3.0
        - ray:               2.3.0
        - readchar:          4.0.5
        - requests:          2.28.1
        - requests-oauthlib: 1.3.1
        - resampy:           0.4.2
        - rfc3339-validator: 0.1.4
        - rfc3986:           1.5.0
        - rfc3986-validator: 0.1.1
        - rich:              13.3.2
        - rpyc:              4.1.5
        - rsa:               4.9
        - s3transfer:        0.6.0
        - scikit-learn:      1.2.2
        - scipy:             1.10.1
        - seaborn:           0.12.2
        - send2trash:        1.8.0
        - sentry-sdk:        1.17.0
        - setproctitle:      1.3.2
        - setuptools:        65.6.3
        - six:               1.16.0
        - smart-open:        6.3.0
        - smmap:             5.0.0
        - sniffio:           1.3.0
        - sortedcontainers:  2.4.0
        - soundfile:         0.12.1
        - soupsieve:         2.4
        - soxr:              0.3.4
        - sqlalchemy:        2.0.7
        - stack-data:        0.2.0
        - starlette:         0.22.0
        - starsessions:      1.3.0
        - stevedore:         5.0.0
        - sweetviz:          2.1.4
        - sympy:             1.11.1
        - tabulate:          0.9.0
        - tblib:             1.7.0
        - tensorboard:       2.11.2
        - tensorboard-data-server: 0.6.1
        - tensorboard-plugin-wit: 1.8.1
        - tensorflow:        2.11.0
        - tensorflow-estimator: 2.11.0
        - tensorflow-io-gcs-filesystem: 0.31.0
        - termcolor:         2.2.0
        - terminado:         0.17.1
        - threadpoolctl:     3.1.0
        - tinycss2:          1.2.1
        - tomli:             2.0.1
        - toolz:             0.12.0
        - torch:             2.0.0+cu117
        - torchaudio:        2.0.1+cu117
        - torchmetrics:      0.11.4
        - torchsort:         0.1.9
        - torchvision:       0.15.1+cu117
        - tornado:           6.2
        - tqdm:              4.65.0
        - traitlets:         5.7.1
        - triton:            2.0.0
        - typing-extensions: 4.4.0
        - ujson:             5.7.0
        - unidist:           0.2.2
        - uri-template:      1.2.0
        - urllib3:           1.26.13
        - uvicorn:           0.21.1
        - uvloop:            0.17.0
        - virtualenv:        20.21.0
        - wandb:             0.14.0
        - watchfiles:        0.18.1
        - wcwidth:           0.2.5
        - webcolors:         1.12
        - webencodings:      0.5.1
        - websocket-client:  1.5.1
        - websockets:        10.4
        - werkzeug:          2.2.3
        - wheel:             0.38.4
        - widgetsnbextension: 4.0.5
        - woodwork:          0.22.0
        - wrapt:             1.15.0
        - yarl:              1.8.2
        - zict:              2.2.0
        - zipp:              3.15.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.9.16
        - version:           #1 SMP Mon Oct 19 16:18:59 UTC 2020

</details>

**Comment by awaelchli** [comment]
Hey @ZedRover 

In your code, replace this line of code:

```py
        penalty_factor = torch.ones(
            y_pred.size(0), dtype=torch.float32, 
        ) # error occur from this line
```
with

```py
        penalty_factor = torch.ones(
            y_pred.size(0), dtype=torch.float32, device=y_pred.device
        ) # error occur from this line
```

Since this question is unrelated to Lightning, and I am confident that my modification will solve your problem, I'm closing the issue but let me know if it doesn't work.
