### ISSUE TITLE
Make STEP_OUTPUT Mapping[str,Any] instead of Dict[str,Any]

### ISSUE THREAD

**Issue by alicanb** [Lightning-AI/lightning#17290]
### Description & Motivation

Hello,

We are maintaining a project based on lightning where we are enforcing type hints. One minor headache we have at the moment is we are returning TypedDicts as `{train,validation}_step` outputs, which is not consistent with STEP_OUTPUT, which is `Dict[str,Any]`.

### Pitch

I would like to change `STEP_OUTPUT` to `Union[Tensor,Mapping[str, Any]`, which is consistent with TypedDicts, and also I think is more appropriate. I don't think this would break anything, am I overlooking something? 

### Alternatives

Leave it as is?

cc @justusschock @awaelchli @borda

**Comment by carmocca** [comment]
We'd accept this contribution
