### ISSUE TITLE
load_from_checkpoint does not work as expected

### ISSUE THREAD

**Issue by liujuncn** [Lightning-AI/lightning#17304]
### Bug description

I want to load a trained checkpoint to "gpu" in colab, but it seems that load_from_checkpoint loads two copies, and the device of the model is "cpu".

![Screenshot from 2023-04-08 18-37-50](https://user-images.githubusercontent.com/902005/230716732-19222895-bed5-4855-909d-efd018fc57fd.png)

The memory of both host and gpu is occupied.

![Screenshot from 2023-04-08 18-38-07](https://user-images.githubusercontent.com/902005/230716777-26a103c7-d8b6-4b73-9a23-30810accc2cc.png)

If i use:
`model.to(torch.device('cuda'))`

subsequent model predict will report the following error:
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)

How to solve this problem？

### What version are you seeing the problem on?

2.0+

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by ryan597** [comment]
Currently the object is created and returned without using `map_location` at all.
The checkpoint is mapped, but this doesn't seem to affect the model created and returned later.

https://github.com/Lightning-AI/lightning/blob/fd4697c62c059fc7b9946e84d91625ecb6efdbe5/src/lightning/pytorch/core/saving.py#L51-L92

I think this works to fix it
```python
import torch
...
def _load_from_checkpoint(
...
    if issubclass(cls, pl.LightningModule):
        storage = _load_state(cls, checkpoint, strict=strict, **kwargs)
        restore_location = torch.serialization._get_restore_location(map_location)

        if isinstance(map_location, dict):
            return restore_location(storage, map_location.get(str(storage.device)))

        return restore_location(storage, map_location)
```

**Comment by liujuncn** [comment]
@ryan597 Yes, it can be loaded to cuda device, but  still report the error when predicting:

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)

If using cpu to predict, it works but slowly.

**Comment by ryan597** [comment]
Have you moved the data to the gpu?

**Comment by liujuncn** [comment]
yes, you are right. I forget to move the data to gpu.
