### ISSUE TITLE
Docs has a formatting bug

### ISSUE THREAD

**Issue by sugatoray** [Lightning-AI/lightning#17339]
### 📚 Documentation

The Quiz 6.1 has an html bug, that messes up the formatting.

Source: <https://lightning.ai/pages/courses/deep-learning-fundamentals/unit-6-overview-essential-deep-learning-tips-tricks/unit-6.1-model-checkpointing-and-early-stopping/>

<img width="932" alt="image" src="https://user-images.githubusercontent.com/10201242/231366973-d5a08685-9689-47dd-9752-b1388814ba1c.png">

cc @borda

**Comment by sugatoray** [comment]
Accessed from Chrome browser on Apple M1 Pro Macbook.

**Comment by carmocca** [comment]
cc @rasbt @adamjkuhn

**Comment by rasbt** [comment]
Arg, thanks for the note. Is this something you can fix on your end @adamjkuhn? Happy to help if there is anything I can do.

**Comment by awaelchli** [comment]
It looks like it was fixed, so I'm closing the issue. Thanks for reporting!

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/5495193/233696786-b747f1bb-25f5-46b7-92d8-50e34a2284b9.png">
