### ISSUE TITLE
Add a performance warning to pl.Trainer parameter detect_anomaly.

### ISSUE THREAD

**Issue by One-sixth** [Lightning-AI/lightning#17359]
### Description & Motivation

This detect_anomaly parameter greatly affects performance and is usually only used in debugging.  
Sometimes after debugging, user forget setting detect_anomaly to False, resulting in a performance loss during training.   
Hope add a warning to notice user that detect_anomaly flag will cause performance lose.  

In my experiment, the train speed when detect_anomaly is turned off is 2.5x when it is turned on.

### Pitch

Add a performance warning when detect_anomaly enabled.

cc @borda @justusschock @awaelchli

**Comment by awaelchli** [comment]
I am not opposed to this. Since the flag is only meant for debugging stability. 
@carmocca @justusschock any objection to this?

**Comment by carmocca** [comment]
I agree. @One-sixth Would you like to contribute it?

**Comment by One-sixth** [comment]
@carmocca Yes, I opened a PR.
