### ISSUE TITLE
Update Fabric tests with devices=1 where necessary

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#17371]
### Outline & Motivation

In 2.0, the defaults for accelerator, devices, strategy were all switched to "auto". This causes a problem for many tests that instantiate fabric like so

```py
fabric = Fabric()
```

and previously were assuming this would run on the CPU (devices=1). However, after 2.0, if you run this "cpu" test on a machine with one or multiple GPUs, lots are failing because of the auto setting switching to multi-gpu ddp. Another effect is that all tests that experinence this issue and are not marked as standalone will lead to the test suite hanging. 

It is annoying that we can't run CPU tests on a GPU machine.

### Pitch

Update all tests that are meant to run on the CPU with devices=1.

cc @justusschock @awaelchli @carmocca @borda

**Comment by ryan597** [comment]
Hi @awaelchli, I can do this.
On my computer there is 1 failing in `tests/test_fabric`
```
FAILED tests/tests_fabric/test_fabric.py::test_backward_model_input_required - 
  RuntimeError: Expected all tensors to be on the same device, but found at least two devices, 
  cuda:0 and cpu! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
```

Can you clarify, is it to change all the tests that setup as `fabric = Fabric()` such that they always run on CPU or that they will make use of the GPU if it is there anyways?
eg. in the above failed test, the offending line is 
```python
  loss = model0(torch.randn(1, 1)).sum()
```
which can be fixed by passing the current device to the tensor, forcing the fabric device as CPU or marking the accelerator to run both if available?
```python
# run on current device
  loss = model0(torch.randn(1, 1, device=fabric.device)).sum()

# OR  run on CPU only
  fabric = Fabric(accelerator="cpu")

# OR  set the accelerator to run if both
@pytest.mark.parametrize("accelerator", ["cpu", pytest.param("cuda", marks=RunIf(min_cuda_gpus=1))])
...
  loss = model0(torch.randn(1, 1, device=fabric.device)).sum()
```

**Comment by carmocca** [comment]
pro-tip: If you comment this line https://github.com/Lightning-AI/lightning/blob/97a61868fb5ff605a857b266a9b2a44b2330da71/tests/tests_fabric/conftest.py#L137 and open a PR, GPU CI will run all tests (not just those marked with `@RunIF(min_cuda_devices=...)`

This should uncover all the failing tests without having a GPU locally.

**Comment by ryan597** [comment]
I do have a local GPU, so it's actually confusing me why those tests do not fail for me at all (and they are not being skipped). Is it that they are failing on multi-GPU machines?

**Comment by awaelchli** [comment]
To see more tests fail, you need to run on a machine with two GPUs (is what I did). @carmocca 's trick will reveal that in our CI too, it runs on 2 Gpus

**Comment by sorenwacker** [comment]
Why don't you set the `CUDA_VISIBLE_DEVICES` environment variable to an emtpy string, then all the tests should ingnore the GPUs.

**Comment by Borda** [comment]
> Why don't you set the `CUDA_VISIBLE_DEVICES` environment variable to an emtpy string, then all the tests should ingnore the GPUs.

Well, that is what I wanted to do too lol
