### ISSUE TITLE
OOM because of `deepspeed_stage_2`

### ISSUE THREAD

**Issue by 980202006** [Lightning-AI/lightning#17392]
### Bug description

I'm using lightning on an 8-card A100. At the beginning, my GPU memory is full, which leads to OOM during validation. But when I use deepspeed_stage_2, I get an OOM at the beginning of training. Why is this happening when all other parameters are the same?
I just set the strategy to deepspeed_stage_2.

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by Borda** [comment]
@980202006, could you pls share what lightning version you are using?

**Comment by awaelchli** [comment]
I'm closing the issue due to lack of infos. 
Happy to help @980202006 if you could share the version of lightning, deepspeed, and a code example of what you are trying to do.
