### ISSUE TITLE
Skipping batches with `precision=16`

### ISSUE THREAD

**Issue by HendrikLaux** [Lightning-AI/lightning#17407]
### Bug description

This is related to [Issue #15688](https://github.com/Lightning-AI/lightning/issues/15688). It is more of a suggestion on a workaround for a known bug (see the linked issue and several similar ones) rather than a new bug. Feel free to edit my issue if it is incorrect.

When using precision=16 in the pl.Trainer, skipping batches by returning `None` in the `LightningModule.training_step()` does not work. 

Returning `None` will produce the following error:

> RuntimeError: unscale_() has already been called on this optimizer since the last update().

The workaround mentioned in [Issue #15688](https://github.com/Lightning-AI/lightning/issues/15688) is to do the following in `training_step`:
`return torch.tensor(0.0,requires_grad=True,device=self.device)`

which used work fine at least for the purpose of skipping batches with AMP.

However, apart from the problem of falsifying the actual loss values, this does not work in Version 2.0+ anymore. 
I am using `lightning==2.0.1.post0` and returning the above mentioned tensor causes the following exception:

> AssertionError: No inf checks were recorded for this optimizer.

---

The only thing that works for me (in version 2.0+) is to implement a custom `MixedPrecisionPlugin` overriding `optimizer_step()` replacing:
`if not _optimizer_handles_unscaling(optimizer)` 
with
`if not _optimizer_handles_unscaling(optimizer) and not skipped_backward`

to skip `self.scaler.unscale_(optimizer)` in case of a `None` loss. This plugin is given to the `lightning.Trainer` via:
`plugins=[CustomMixedPrecisionPlugin(precision="16-mixed", device="cuda")]`.

The training continues to run with this and, from what I can judge, without any difference compared to the workaround with the returned zero-loss tensor in the 1.x versions. However I am a bit afraid of not fully understanding the other implications of making this change.

If there are None, I would suggest changing the implementation of the `MixedPrecisionPlugin` to not call `self.scaler.unscale_(optimizer)` in case of a None loss, which would then be an easy fix for the problem of not being able to skip batches with mixed precision training. If the changes constitute a problem on another end (that I can't see without diving deep into lightning's code), I am open to further suggestions and willing to help wherever I can.

---

For anyone looking for a quick workaround, this is the full code of the custom plugin:
```
from lightning.fabric.plugins.precision.amp import _optimizer_handles_unscaling
from lightning.fabric.utilities.exceptions import MisconfigurationException
from lightning.pytorch.plugins import MixedPrecisionPlugin
from torch.optim.lbfgs import LBFGS


class CustomMixedPrecisionPlugin(MixedPrecisionPlugin):

    def optimizer_step(  # type: ignore[override]
        self,
        optimizer,
        model,
        closure,
        **kwargs,
    ):
        if self.scaler is None:
            # skip scaler logic, as bfloat16 does not require scaler
            return super().optimizer_step(optimizer, model=model, closure=closure, **kwargs)
        if isinstance(optimizer, LBFGS):
            raise MisconfigurationException("AMP and the LBFGS optimizer are not compatible.")
        closure_result = closure()

        # EDIT: moved this to the top
        skipped_backward = closure_result is None

        # EDIT: added the second condition
        if not _optimizer_handles_unscaling(optimizer) and not skipped_backward:
            # Unscaling needs to be performed here in case we are going to apply gradient clipping.
            # Optimizers that perform unscaling in their `.step()` method are not supported (e.g., fused Adam).
            # Note: `unscale` happens after the closure is executed, but before the `on_before_optimizer_step` hook.
            self.scaler.unscale_(optimizer)

        self._after_closure(model, optimizer)
        # in manual optimization, the closure does not return a value
        if not model.automatic_optimization or not skipped_backward:
            # note: the scaler will skip the `optimizer.step` if nonfinite gradients are found
            step_output = self.scaler.step(optimizer, **kwargs)
            self.scaler.update()
            return step_output
        return closure_result

```

which can be added to the trainer using:

```
trainer = lightning.Trainer(
    (...)
    plugins=[CustomMixedPrecisionPlugin(precision="16-mixed", device="cuda")]
)
```
---

### What version are you seeing the problem on?

2.0+

### How to reproduce the bug

```python
Training a model with mixed-16 precision and returning `torch.tensor(0.0,requires_grad=True,device=self.device)` or `None` in `LightningModule.training_step()`
```

cc @carmocca @justusschock @awaelchli

**Comment by ipoletaev** [comment]
Let's try to fix this one? :)

**Comment by darkestpigeon** [comment]
A minimal example to reproduce the problem:
```
import torch
from torch import nn
import pytorch_lightning as pl


class ExampleModule(pl.LightningModule):

    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(1, 16),
            nn.ReLU(),
            nn.Linear(16, 1)
        )

    def forward(self, x):
        return self.net(x[..., None])[..., 0]

    def training_step(self, batch, batch_idx):
        if batch_idx in (8, 9):
            return None
        X, y = batch
        loss = (y - self(X)).square().mean()
        self.log('train_loss', loss, prog_bar=True)
        return loss

    def train_dataloader(self):
        while True:
            X = torch.randn(16)
            y = -1.2 + X**2 - 2.1*torch.sin(X)
            yield X, y

    def configure_optimizers(self):
        return torch.optim.RAdam(self.parameters())


def main():
    pl_module = ExampleModule()
    trainer = pl.Trainer(accelerator='gpu', precision='16-mixed')
    trainer.fit(pl_module)


if __name__ == '__main__':
    main()
```

The problem can be fixed by modifying the [`optimizer_step`](https://github.com/Lightning-AI/lightning/blob/master/src/lightning/pytorch/plugins/precision/amp.py#L64`) function:
```
    def optimizer_step(  # type: ignore[override]
        self,
        optimizer: Optimizable,
        model: "pl.LightningModule",
        closure: Callable[[], Any],
        **kwargs: Any,
    ) -> Any:
        if self.scaler is None:
            # skip scaler logic, as bfloat16 does not require scaler
            return super().optimizer_step(optimizer, model=model, closure=closure, **kwargs)
        if isinstance(optimizer, LBFGS):
            raise MisconfigurationException("AMP and the LBFGS optimizer are not compatible.")
        closure_result = closure()
####### Bug fix ###
        if closure_result is None:
            return
#######

        if not _optimizer_handles_unscaling(optimizer):
            # Unscaling needs to be performed here in case we are going to apply gradient clipping.
            # Optimizers that perform unscaling in their `.step()` method are not supported (e.g., fused Adam).
            # Note: `unscale` happens after the closure is executed, but before the `on_before_optimizer_step` hook.
            self.scaler.unscale_(optimizer)

        self._after_closure(model, optimizer)
        skipped_backward = closure_result is None
        # in manual optimization, the closure does not return a value
        if not model.automatic_optimization or not skipped_backward:
            # note: the scaler will skip the `optimizer.step` if nonfinite gradients are found
            step_output = self.scaler.step(optimizer, **kwargs)
            self.scaler.update()
            return step_output
        return closure_result
```

Works fine for me, but not sure this will remain correct in all cases. Perhaps someone with more expertise can take a look?

**Comment by Crazy-LittleBoy** [comment]
> thx, it works for me.
