### ISSUE TITLE
Trainer.strategy Error

### ISSUE THREAD

**Issue by jacksparrow-firstmate** [Lightning-AI/lightning#17445]
### Bug description

Sample from https://lightning.ai/docs/pytorch/stable/accelerators/gpu_intermediate.html:
from lightning.pytorch.strategies import DDPStrategy

# Explicitly specify the process group backend if you choose to
ddp = DDPStrategy(process_group_backend="nccl")

# Configure the strategy on the Trainer
trainer = Trainer(strategy=ddp, accelerator="gpu", devices=8)

My code:
from lightning.pytorch.strategies import DDPStrategy
ddp = DDPStrategy(process_group_backend="gloo")

# training
trainer = pl.Trainer(
    strategy=ddp,
    devices=2,
    accelerator="gpu",
    max_epochs=3,
    callbacks=[TQDMProgressBar(refresh_rate=20)],
)

Error :
ValueError: You selected an invalid strategy name: `strategy=<lightning.pytorch.strategies.ddp.DDPStrategy object at 0x0000019B575B6070>`. It must be either a string or an instance of `pytorch_lightning.strategies.Strategy`. Example choices: auto, ddp, ddp_spawn, deepspeed, ... Find a complete list of options in our documentation at https://lightning.ai

on Windows "RuntimeError: Distributed package doesn't have NCCL built in"
how to fix this issue? thank you !

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by jacksparrow-firstmate** [comment]
PyTorch Lightning Version: 2.0.1

**Comment by awaelchli** [comment]
@jacksparrow-firstmate Could it be that you have mixed up the imports? 
Are you mixing imports like this?

```py
import pytorch_lightning as pl
from lightning.pytorch.strategies import DDPStrategy

pl.Trainer(...)
```
If this is the case, please change `import pytorch_lightning as pl` to `import lightning.pytorch as pl`.


Could you share the full runnable code with imports please?

**Comment by jacksparrow-firstmate** [comment]
![image](https://user-images.githubusercontent.com/72544699/235214198-315eba86-5eda-43bb-a9b7-f1cf0fe4b9ff.png)

thank u very much！I have solved this problem on WSL2. However, under the "ddp" strategy, my verification result will be printed twice, which seems to be verified on two gpus at the same time, I only want to verify once, how to solve this problem?
Also, I want to do validation after training for N epochs, what do I need to do in this case?

**Comment by jacksparrow-firstmate** [comment]
![image](https://user-images.githubusercontent.com/72544699/235220031-c2965a92-86eb-424e-82d3-bd0b87b3c123.png)
New question, after I use two 3090 for training, the speed of each epoch is getting slower and slower. One GPU and one epoch only need 2:20min. What should I do in this situation?

**Comment by jacksparrow-firstmate** [comment]
@awaelchli sorry for bothering u, please help me to fix this

**Comment by awaelchli** [comment]
You can print a value on one rank only, for example using 

```py
if self.trainer.global_rank == 0:
    print(...)
```

Your iteration speed over the epoch seems relatively stable, around 1.4 sec/iteration. The iteration speed per process won't change significantly if you increase the number of devices. There will be some communication overhead. The iteration speed should roughly stay the same, while the epoch size per device should shrink by factor 1 / num_gpus.

**Comment by jacksparrow-firstmate** [comment]
@awaelchli thank you for ur response,  code training with one gpu fixes everything = =, maybe I need nvlink
