### ISSUE TITLE
pytorch_lightning.utilities.upgrade_checkpoint() fail in case of NO GPU

### ISSUE THREAD

**Issue by ThommySte** [Lightning-AI/lightning#17481]
### Bug description

Hi,
we uses Comet and download new modell. By starting the Comet with downloaded models we got the message the checkpoints are outdated. We tried to convert, but also the suggest `upgrade_checkpoint` failed because on the VM has no GPU assigned. All this happen in creation in Dockerfiles (since we uses COMET).

Finally the only way to solve the issue was to patch 
`pytorch_lightning.utilities.upgrade_checkpoint()`
in an quite hacky way:
`sed -i 's/torch.load(file)/torch.load(file,map_location="cpu")/g' /usr/local/lib/python3.10/dist-packages/pytorch_lightning/utilities/upgrade_checkpoint.py`
Here we patch line #63
from: `checkpoint = torch.load(file)`
to `checkpoint = torch.load(file,map_location='cpu')`

This really not nice and not fault tolerant. So the idea is to have a more configuarebale approach to run tools without have a GPU.

Thanks, Thomas

### What version are you seeing the problem on?

1.9.5

### Error messages and logs

Upgrade checkpoint break

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @awaelchli

**Comment by awaelchli** [comment]
@ThommySte 
What is the error you get? From which version to which version did you upgrade the checkpoint? It would be good to know this at least so we can reproduce that error.

In your message, you referenced this issue https://github.com/Lightning-AI/lightning/pull/63, but could you provide the full link please?

Changing the `map_location='cpu'` is possible, but I would still like to see where it goes wrong. Thanks!

**Comment by ThommySte** [comment]
Hi,
I have retried-  First the installation of comet pick a version below 2.0:
`Collecting pytorch-lightning<2.0.0,>=1.6.4 (from unbabel-comet)
Downloading pytorch_lightning-1.9.5-py3-none-any.whl (829 kB) `

I run the the upgrade in Ubuntu:2204 Docker build.
The error is:
```
20:05:07  Traceback (most recent call last):
20:05:07    File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
20:05:07  [0m[91m    return _run_code(code, main_globals, None,
20:05:07    File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
20:05:07  [0m[91m    exec(code, run_globals)
20:05:07  [0m[91m  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/utilities/upgrade_checkpoint.py", line 90, in <module>
20:05:07  [0m[91m    main()
20:05:07    File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/utilities/upgrade_checkpoint.py", line 86, in main
20:05:07      _upgrade(args)
20:05:07    File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/utilities/upgrade_checkpoint.py", line 63, in _upgrade
20:05:07      checkpoint = torch.load(file)
20:05:07    File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 809, in load
20:05:07  [0m[91m    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
20:05:07    File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1172, in _load
20:05:07  [0m[91m    result = unpickler.load()
20:05:07    File "/usr/lib/python3.10/pickle.py", line 1213, in load
20:05:07  [0m[91m    dispatch[key[0]](self)
20:05:07    File "/usr/lib/python3.10/pickle.py", line 1254, in load_binpersid
20:05:07  [0m[91m    self.append(self.persistent_load(pid))
20:05:07    File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1142, in persistent_load
20:05:07  [0m[91m    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
20:05:07    File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1116, in load_tensor
20:05:07  [0m[91m    wrap_storage=restore_location(storage, location),
20:05:07    File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 217, in default_restore_location
20:05:07  [0m[91m    result = fn(storage, location)
20:05:07    File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 182, in _cuda_deserialize
20:05:07      device = validate_cuda_device(location)
20:05:07    File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 166, in validate_cuda_device
20:05:07      raise RuntimeError('Attempting to deserialize object on a CUDA '
20:05:07  RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
20:05:07  [0mThe command '/bin/sh -c python3 -m pytorch_lightning.utilities.upgrade_checkpoint /models/eamt22-cometinho-da/checkpoints/model.ckpt &&     python3 -m pytorch_lightning.utilities.upgrade_checkpoint /models/wmt22-comet-da/checkpoints/model.ckpt &&     rm *.tar.gz &&     find /models/ -name "model.bak" -exec rm {} \;' returned a non-zero code: 1
```
The the hacky patch is enabled the upgrade succeed and the patched checkpoints can be used in COMET

**Comment by ThommySte** [comment]
I want to add -  setting map_location='cpu' is not the best solution. Maybe make it configurable or add a reliable detection mechanism is maybe better.

**Comment by awaelchli** [comment]
Thanks for posting the error. I suspected this and just wanted to make sure it is due to there being tensors in CUDA. So my suggestion is:
- We allow user to convert a checkpoint saved with cuda tensor on a cpu only machine.
- If we detect torch.cuda.is_available() == False, we set the map_location to cpu and inform the user. 
- Additionally, we can make it configurable (as you suggested 🎉 ), because it could be that user converts the checkpoints on a machine with not enough GPU memory available and would prefer conversion to cpu

What do you think?

**Comment by ThommySte** [comment]
Thanks, @awaelchli,

for your fast response around my reported issue.
We discussed internally and my colleague agreed that the "configurable" approach fit best in the issue we are facing. Since we use models some others (COMET) have created - we have no way influence the model itself. 
I'm not fully sure regarding "`detect torch.cuda.is_available()`" fits for our problem -  because after installing Comet by using PIP also CUDA is downloaded into the image (but not used -  maybe have to ask the COMET development to make this also configurable on COMET side) -  as described we run it in a virtualized docker container without any GPU on our clusters.
