### ISSUE TITLE
List of Callbacks Raises `ValueError("Expected a parent")`

### ISSUE THREAD

**Issue by amirkhas** [Lightning-AI/lightning#17485]
### Bug description

If the callbacks list, passing to the trainer, has more than one element, it raises the error `ValueError("Expected a parent")`. 
If you pass any of those elements alone the code runs fine. 

p.s. I'm already importing like this: `import lightning.pytorch as pl` which is version >=2. specific.

### What version are you seeing the problem on?

2.0+

### Error messages and logs

```
# Error messages and logs here please
```
`ValueError: Expected a parent`

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @awaelchli

**Comment by carmocca** [comment]
Can you share your code?

I've seen this happen when `lightning.pytorch` and `pytorch_lightning` imports are mixed together. You need to use only one of them. This includes the callback parent

```
import lightning.pytorch as lp
import pytorch_lightning as pl

class MyCallback(pl.Callback):
    ...

trainer = lp.Trainer(callbacks=MyCallback)  # bad!
```

**Comment by turian** [comment]
@carmocca I had this bug and your suggestion fixed it

**Comment by awaelchli** [comment]
@carmocca Do you think we could inspect sys.modules and detect whether there are both pytorch_lightning and lightning loaded, and warn the user? Not sure whether that would help.

**Comment by turian** [comment]
@awaelchli I mean, better warnings are always great.

**Comment by mimbres** [comment]
https://github.com/Lightning-AI/lightning/issues/17485#issuecomment-1524198677 

> Can you share your code?
> 
> I've seen this happen when `lightning.pytorch` and `pytorch_lightning` imports are mixed together. You need to use only one of them. This includes the callback parent
> 
> ```python
> import lightning.pytorch as lp
> import pytorch_lightning as pl
> 
> class MyCallback(pl.Callback):
>     ...
> 
> trainer = lp.Trainer(callbacks=MyCallback())  # bad!
> ```
this also solved a similar bug for learning rate monitor callbacks

**Comment by carmocca** [comment]
> @carmocca Do you think we could inspect sys.modules and detect whether there are both pytorch_lightning and lightning loaded, and warn the user? Not sure whether that would help.

I feel like that's too strong of a check. Imagine you are in a team of data scientist who share utility python packages and two packages use lightning, each with a type of import. This check would break their code just on import even if they don't mix the classes. Fixing it might also be out of the control of the person who just tried to import it.

I think it would be simpler that we add a specific check for this in `is_overridden` and `_maybe_unwrap_optimized`

**Comment by amirkhas** [comment]
> Can you share your code?
> 
> I've seen this happen when `lightning.pytorch` and `pytorch_lightning` imports are mixed together. You need to use only one of them. This includes the callback parent
> 
> ```python
> import lightning.pytorch as lp
> import pytorch_lightning as pl
> 
> class MyCallback(pl.Callback):
>     ...
> 
> trainer = lp.Trainer(callbacks=MyCallback())  # bad!
> ```

That solved my error. Thanks!

**Comment by davidgilbertson** [comment]
I'm seeing this error with the Optuna `PyTorchLightningPruningCallback`. They extend `pytorch_lightning.callbacks.callback.Callback` and I can't control that, but I'm using the new `lightning` package and don't want to change that.

My rather hacky workaround is this:
```py
import lightning
import optuna

class PatchedCallback(
    optuna.integration.PyTorchLightningPruningCallback, lightning.Callback
):
    pass
```

I think since there's going to be two lightnings floating around for years, instance checks should be updated to be `if isinstance(obj, (old_pl.Callback, new_pl.Callback))`, before eventually being reverted after a suitable deprecation period.

Also, will the fix https://github.com/Lightning-AI/lightning/pull/17548 just mean that I get an error if I use a package that is still on old Lightning? Or is it assuming direct use of the class and it doesn't handle the inheritance case?

**Comment by Lezcool** [comment]
could you please fix the error msg for this? The error message is useless. in my case, it raised `TypeError: __init__() got an unexpected keyword argument ‘gpus’` after the ValueError("Expected a parent"), but I didn't even pass gpus args. And it took so long to find this thread.

**Comment by redfave** [comment]
> The check for mixed imports implemented by [@carmocca](https://github.com/carmocca) fails to detect and warn users in at least some configurations of old/new imports.

I've got exactly trapped by this.
The `PyTorchLightningPruningCallback` from `optuna.integration.pytorch_lightning ` uses the new package name.
`MlflowModelCheckpointCallback` from `mlflow.pytorch` uses the old package name.
Lightning raises `ValueError("Expected a parent")` and there is nothing I can do about it from my app.

I just hope the mlflow community picks [PR 11372](https://github.com/mlflow/mlflow/pull/11372) up again, to resolve this.
