### ISSUE TITLE
The UI is a bug

### ISSUE THREAD

**Issue by fractaldna22** [Lightning-AI/lightning#17508]
### Bug description

This is insanity. Ive been plagued by the side effects of simply importing lightning for almost a year now, desperate to find out what is causing the issue not knowing it was lightning. 

Upon importing lighting the entire traceback hander of google colab is replaced with a truly abhorrent, unsightly degradation of the superior Ipython default tracebacks.  The default tracebacks provide hyperlinks to jump to the line that triggered the exception, its very neat and efficient.

Lightning destroys that replacing it with COSMIC SANS MS RED AND GREEN FONT  UNDERLINES EVERYTHING AND REMOVES CLICKABILITY FOR ANY PART OF THE EXCEPTION. 

This makes it impossible to troubleshoot and spend what little time we're allotted in the current colab subscriptions just digging through lines trying to even find what the exception is, as it no longer even underlines the problematic line in the cell block nor links to it in the cell output. 

Why is this accepted? Why is this okay or chosen? Its trash.  I recommend you remove this TB-replacement with whatever "colorful" tacky crap you have included in Lightning for NO REASON.  

Its NOT CUTE. it's NOT useful. It's not Lightning. 
It's a bug of decision making, NOT a feature

This is just from one line of one function  that imports seed everything from Lightning where the PL lightning module or trainer isnt even used, Only the seed function:

Ill also post screenshots of the difference. 
Good traceback:
<img width="328" alt="image" src="https://user-images.githubusercontent.com/37323518/235016497-60cfb482-c98a-4bf3-8bd7-0f105a401654.png">
Bad traceback:
<img width="435" alt="image" src="https://user-images.githubusercontent.com/37323518/235017147-3e97e9d3-2a95-4095-b582-9d2eef30823d.png">

I literally spent many, many days, weeks even, lamenting the fact i could not figure out what in the world could be trolling me so hard that it takes away my ability to resolve errors and depletes my compute allotment and results in nights where I dont even get to run the actual model all because of this HORRIBLE traceback handler that someone simply insisted to impose on the world for god knows why.  Is this a contractual obligation? If not, remove this!

### What version are you seeing the problem on?

v1_6, v1_7, v1_8, v1_9, v2_0, master

### How to reproduce the bug

```python
#1.
asofpjats  # trigger exception, run cell

#2
"""
Correct traceback handler with links to the exception and non-offensive and efficient
"""

#3.
import pytorch_lightning

#4.
stjijt  # trigger exception, run cell

#5.

"""                                            Traceback
|___________________Traceback Handler has been replaced with literal Doom ______________________
| #unrelated code to the error that leads you down a wild goose chase                                                                                                 | "we replace the sys.excepthook with the original"
| sys.excepthook = orig_excepthook()                                                                                                 | #actually nothing original about it and remains green and red nightmare text
|                                                                                        | 
|          |
|
||  |
|
on line 8949604
```

### Error messages and logs

Here is a traceback, where lighting is allowed to be imported by not commenting out import seed_all:

```markdown
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py:3553 in run_code        │
│                                                                                                  │
│   3550 │   │   │   │   elif async_ :                                                             │
│   3551 │   │   │   │   │   await eval(code_obj, self.user_global_ns, self.user_ns)               │
│   3552 │   │   │   │   else:                                                                     │
│ ❱ 3553 │   │   │   │   │   exec(code_obj, self.user_global_ns, self.user_ns)                     │
│   3554 │   │   │   finally:                                                                      │
│   3555 │   │   │   │   # Reset our crash handler in place                                        │
│   3556 │   │   │   │   sys.excepthook = old_excepthook                                           │ # What is this?? why does every error  
#########################################################   #print this out when its unrelated to the actual 
                                                                                                                            # exception? Because its a bug thats why
│ in <cell line: 8>:11                                                                             │
│ in <module>:1                                                                                    │
│                                                                                                  │
│ /content/stable-diffusion/helpers/render.py:15 in <module>                                       │
│                                                                                                  │
│    12 import pathlib                                                                             │
│    13 import torchvision.transforms as T                                                         │
│    14                                                                                            │
│ ❱  15 from .generate import generate, add_noise                                                  │
│    16 from .prompt import sanitize                                                               │
│    17 from .animation import DeformAnimKeys, sample_from_cv2, sample_to_cv2, anim_frame_warp,    │
│    18 from .depth import DepthModel                                                              │
│                                                                                                  │
│ /content/stable-diffusion/helpers/generate.py:8 in <module>                                      │
│                                                                                                  │
│     5 import torchvision.transforms.functional as TF                                             │
│     6 from pytorch_lightning import seed_everything    │ < ------------------- Here, This is the line
│     7 import os                                                                                  │
│ ❱   8 from ldm.models.diffusion.plms import PLMSSampler                                          │
│     9 from ldm.models.diffusion.ddim import DDIMSampler                                          │
│    10 from k_diffusion.external import CompVisDenoiser, CompVisVDenoiser                         │
│    11 from torch import autocast                  
```

commented out:

```py
/content/stable-diffusion
helpers.render.render_animation
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)

/content/stable-diffusion/helpers/generate.py in <module>
      **6 #from pytorch_lightning import seed_everything**    #  <------------- Commented out line
      7 import os
----> 8 from ldm.models.diffusion.plms import PLMSSampler
      9 from ldm.models.diffusion.ddim import DDIMSampler
     10 from k_diffusion.external import CompVisDenoiser, CompVisVDenoiser

ModuleNotFoundError: No module named 'ldm'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by carmocca** [comment]
Hi! Unfortunately, your quest must continue because this isn't caused by lightning exactly.

This traceback formatting looks to be coming from `rich`: https://rich.readthedocs.io/en/stable/traceback.html#traceback-handler

Lightning does offer a [`RichProgressBar`](https://github.com/Lightning-AI/lightning/blob/master/src/lightning/pytorch/callbacks/progress/rich_progress.py#L25) but it doesn't enable this traceback handler, in fact, the rich dependency is optional. Lightning doesn't install it by default.
Something you could try to verify is to uninstall `rich` and run your code. Colab includes `rich` by default in their environment

It's possible that your environment is set up to use the traceback handler automatically: https://rich.readthedocs.io/en/stable/traceback.html#automatic-traceback-handler
and maybe importing `rich` (through lightning) enables it automatically.

The question would be which precise package is enabling this traceback handler. I opened a Colab that does `import lightning; raise ValueError` and couldn't reproduce the change.

**Comment by fractaldna22** [comment]
> Hi! Unfortunately, your quest must continue because this isn't caused by lightning exactly.
> 
> This traceback formatting looks to be coming from `rich`: https://rich.readthedocs.io/en/stable/traceback.html#traceback-handler
> 
> Lightning does offer a [`RichProgressBar`](https://github.com/Lightning-AI/lightning/blob/master/src/lightning/pytorch/callbacks/progress/rich_progress.py#L25) but it doesn't enable this traceback handler, in fact, the rich dependency is optional. Lightning doesn't install it by default. The `RichProgressBar` is not enabled by default.
> 
> Something you could try to verify is to uninstall `rich` and run your code. Colab includes `rich` by default in their environment
> 
> It's possible that your environment is set up to use the traceback handler automatically: https://rich.readthedocs.io/en/stable/traceback.html#automatic-traceback-handler and maybe importing `rich` (through lightning) enables it automatically.
> 
> The question would be which precise package is enabling this traceback handler. I opened a Colab that does `import lightning; raise ValueError` and couldn't reproduce the issue.

Hi, thanks for the reply.  Did you say that by defining a rule that raises a ValueError if lightning is imported, prevents the issue? Or that you were unable to reproduce the issue no matter what you tried?

**Comment by carmocca** [comment]
> Or that you were unable to reproduce the issue no matter what you tried?

This

>  i don't see why lightning should be including it. It's not useful, does lightning really need rich

lightning doesn't install it by default, you can check this by doing

```bash
pip list | grep rich
pip install lightning
pip list | grep rich
```
