### ISSUE TITLE
Inspecting models prior to attaching to trainer fails

### ISSUE THREAD

**Issue by SkafteNicki** [Lightning-AI/lightning#17517]
### Bug description

I wanted to inspect a `LightningModule` prior to training, getting a list of all methods.
However, this is currently not possible because the inspection will fail on the `trainer` attribute of the module with this runtime error:
https://github.com/Lightning-AI/lightning/blob/ce3701bfc0c3af9689618283824756cbd4807ca2/src/lightning/pytorch/core/module.py#L198-L199

After attaching a trainer (through `trainer.fit`) everything works as expected.

I clearly understand why the error is raised, but I wonder if it could be replaced with a warning + returning `None`.

### What version are you seeing the problem on?

v2_0

### How to reproduce the bug

```python
from lightning.pytorch.demos.boring_classes import BoringModel
import inspect
model = BoringModel()
inspect.getmembers(m, inspect.ismethod)
```

### Error messages and logs

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[5], line 1
----> 1 inspect.getmembers(model, inspect.ismethod)

File ~\Anaconda3\envs\dev\lib\inspect.py:469, in getmembers(object, predicate)
    464 for key in names:
    465     # First try to get the value via getattr.  Some descriptors don't
    466     # like calling their __get__ (see bug #1785), so fall back to
    467     # looking in the __dict__.
    468     try:
--> 469         value = getattr(object, key)
    470         # handle the duplicate key
    471         if key in processed:

File ~\Anaconda3\envs\dev\lib\site-packages\lightning\pytorch\core\module.py:200, in LightningModule.trainer(self)
    198     return _TrainerFabricShim(fabric=self._fabric)  # type: ignore[return-value]
    199 if not self._jit_is_scripting and self._trainer is None:
--> 200     raise RuntimeError(f"{self.__class__.__qualname__} is not attached to a `Trainer`.")
    201 return self._trainer

RuntimeError: BoringModel is not attached to a `Trainer`.
```

### Environment

<details>
  <summary>Current environment</summary>

* CUDA:
        - GPU:
                - NVIDIA GeForce GTX 1060
        - available:         True
        - version:           11.8
* Lightning:
        - lightning:         2.0.2
        - lightning-cloud:   0.5.34
        - lightning-utilities: 0.8.0
        - pytorch-lightning: 2.0.2
        - torch:             2.0.0+cu118
        - torchaudio:        2.0.1+cu118
        - torchmetrics:      0.11.4
        - torchvision:       0.15.1+cu118
* Packages:
        - aiohttp:           3.8.4
        - aiosignal:         1.3.1
        - ansicon:           1.89.0
        - anyio:             3.6.2
        - arrow:             1.2.3
        - asttokens:         2.0.5
        - async-timeout:     4.0.2
        - attrs:             23.1.0
        - backcall:          0.2.0
        - beautifulsoup4:    4.12.2
        - black:             23.3.0
        - blessed:           1.20.0
        - certifi:           2022.12.7
        - charset-normalizer: 2.1.1
        - cleanlab:          2.3.1
        - click:             8.1.3
        - colorama:          0.4.6
        - coverage:          7.2.4
        - croniter:          1.3.14
        - dateutils:         0.6.12
        - decorator:         5.1.1
        - deepdiff:          6.3.0
        - exceptiongroup:    1.1.1
        - executing:         0.8.3
        - fastapi:           0.88.0
        - filelock:          3.9.0
        - frozenlist:        1.3.3
        - fsspec:            2023.4.0
        - h11:               0.14.0
        - idna:              3.4
        - iniconfig:         2.0.0
        - inquirer:          3.1.3
        - ipython:           8.12.0
        - isort:             5.12.0
        - itsdangerous:      2.1.2
        - jedi:              0.18.1
        - jinja2:            3.1.2
        - jinxed:            1.2.0
        - joblib:            1.2.0
        - lightning:         2.0.2
        - lightning-cloud:   0.5.34
        - lightning-utilities: 0.8.0
        - markdown-it-py:    2.2.0
        - markupsafe:        2.1.2
        - matplotlib-inline: 0.1.6
        - mdurl:             0.1.2
        - mpmath:            1.2.1
        - multidict:         6.0.4
        - mypy-extensions:   1.0.0
        - networkx:          3.0
        - numpy:             1.24.1
        - ordered-set:       4.1.0
        - packaging:         23.1
        - pandas:            2.0.1
        - parso:             0.8.3
        - pathspec:          0.11.1
        - pickleshare:       0.7.5
        - pillow:            9.3.0
        - pip:               23.0.1
        - pl-cross:          0.0.0
        - platformdirs:      3.5.0
        - pluggy:            1.0.0
        - prompt-toolkit:    3.0.36
        - psutil:            5.9.5
        - pure-eval:         0.2.2
        - pydantic:          1.10.7
        - pygments:          2.15.1
        - pyjwt:             2.6.0
        - pytest:            7.3.1
        - python-dateutil:   2.8.2
        - python-editor:     1.0.4
        - python-multipart:  0.0.6
        - pytorch-lightning: 2.0.2
        - pytz:              2023.3
        - pyyaml:            6.0
        - readchar:          4.0.5
        - requests:          2.28.1
        - rich:              13.3.4
        - ruff:              0.0.263
        - scikit-learn:      1.2.2
        - scipy:             1.10.1
        - setuptools:        66.0.0
        - six:               1.16.0
        - sniffio:           1.3.0
        - soupsieve:         2.4.1
        - stack-data:        0.2.0
        - starlette:         0.22.0
        - starsessions:      1.3.0
        - sympy:             1.11.1
        - termcolor:         2.3.0
        - threadpoolctl:     3.1.0
        - tomli:             2.0.1
        - torch:             2.0.0+cu118
        - torchaudio:        2.0.1+cu118
        - torchmetrics:      0.11.4
        - torchvision:       0.15.1+cu118
        - tqdm:              4.65.0
        - traitlets:         5.7.1
        - typing-extensions: 4.4.0
        - tzdata:            2023.3
        - urllib3:           1.26.13
        - uvicorn:           0.21.1
        - wcwidth:           0.2.5
        - websocket-client:  1.5.1
        - websockets:        11.0.2
        - wheel:             0.38.4
        - yarl:              1.9.2
* System:
        - OS:                Windows
        - architecture:
                - 64bit
                - WindowsPE
        - processor:         Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
        - python:            3.10.11
        - version:           10.0.19045

</details>

cc @carmocca @justusschock @awaelchli @borda

**Comment by awaelchli** [comment]
Hi

If it helps, you can work around it by attaching a fake trainer like so:
```py
model._trainer = object()
```
and the inspection should work. I'm not sure about the reason why it is an error, but to some degree, it makes sense to give a meaningful message rather than returning None and the user getting a NoneTypeError in a different place. 
cc @carmocca

**Comment by SkafteNicki** [comment]
Alright, I am fine with the work around.
To be fair, I also think it make sense that an error is raised here and my use case is probably a corner case. 
Just wanted to check what the intention was.
Feel free to close issue.

**Comment by carmocca** [comment]
It's an error because we use `lightning_module.trainer` everywhere and mypy would force us to use an assert or isisntance check to make sure it is not None and that's quite annoying to add. Closing!
