### ISSUE TITLE
FSDP : The optimizer does not seem to reference any FSDP parameters.

### ISSUE THREAD

**Issue by KevinCrp** [Lightning-AI/lightning#17515]
### Bug description

Hi,

I'm trying to use the FSDP strategy

```python
strategy = FSDPStrategy()
```
When I launch the training I get that error :
> ValueError: The optimizer does not seem to reference any FSDP parameters. HINT: Make sure to create the optimizer after setting up the model by referencing 'self.trainer.model.parameters()' in the 'configure_optimizers()' hook.

I tried to have ```self.trainer.model.parameters()``` in ```configure_optimizers()``` but i get the same problem.

How can I solve it?

### What version are you seeing the problem on?

v2_0

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0): 2.0.0
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0): 1.12.0
#- Python version (e.g., 3.9): 3.8
#- OS (e.g., Linux): Ubuntu
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source): conda
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @awaelchli @carmocca

**Comment by awaelchli** [comment]
Hey @KevinCrp 
Could you try installing Lightning from master and using PyTorch 2.0. We made some improvements here:  #17309

**Comment by KevinCrp** [comment]
Hi, Thanks for your help,

Just to correct my previous post, I was already on PyTorch 2.0.0 (not 1.12.0).

I have installed Lightning from the master.
But I have always had the same issue ``ValueError: The optimizer does not seem to reference any FSDP parameters. HINT: Make sure to create the optimizer after setting up the model by referencing "self.trainer.model.parameters()" in the "configure_optimizers()" hook.``

I tried to change `self.parameters()` by `self.trainer.model.parameters` and I get `ValueError: 
 you tried to log -1 which is currently not supported. Try a dict or a scalar/tensor.`

Before trying to use FSDP all worked fine, with the DDP strategy.

**Comment by jyperion** [comment]
How can this be made to work with Lightning CLI? CLI uses optimizer = instantiate_class(self.model.parameters(), optimizer_init) in line 621 of the cli.py file.

**Comment by tginart** [comment]
I am still having this issue. Any fixes?

**Comment by awaelchli** [comment]
@tginart What exactly is your issue?
Did you follow the instructions of the error message:

> ValueError: The optimizer does not seem to reference any FSDP parameters. HINT: Make sure to create the optimizer after setting up the model by referencing 'self.trainer.model.parameters()' in the 'configure_optimizers()' hook.

It says reference the parameters via `self.trainer.model.parameters()` in `configure_optimizers`. Did you do it? Note that these improvements are only available in the latest Lightning version, so make sure you are updated. If you still got issues, please post a new Bug report issue with detailed steps and code to reproduce. Thank you!
