### ISSUE TITLE
`Fabric` not working with more than 1 GPU device.

### ISSUE THREAD

**Issue by VolodyaCO** [Lightning-AI/lightning#17546]
### Bug description

I'm trying a pretty simple example from `Fabric` on a machine with 8 A100s. I define a `Fabric` object with `devices=2` inside a python session run from a docker container. When I try to set up a model and an optimizer, I get a `RuntimeError: Default process group has not been initialized, please make sure to call init_process_group` message.

### What version are you seeing the problem on?

v2_0

### How to reproduce the bug

```python
import torch.nn as nn
import torch
from lightning.fabric import Fabric

fabric=Fabric(devices=2). # works just fine with `devices=1`
encoder = nn.Sequential(nn.Linear(28 * 28, 64), nn.ReLU(), nn.Linear(64, 3))
params = encoder.parameters()
optimizer = torch.optim.Adam(params, lr=1e-3)

model, opt = fabric.setup(encoder, optimizer)
```

### Error messages and logs

```
You are using a CUDA device ('NVIDIA A100-SXM4-80GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[8], line 1
----> 1 model, opt = fabric.setup(encoder, optimizer)

File /usr/local/lib/python3.8/dist-packages/lightning/fabric/fabric.py:198, in Fabric.setup(self, module, move_to_device, *optimizers)
    196 # Let accelerator/plugin wrap and connect the models and optimizers
    197 if optimizers:
--> 198     module, optimizers = self._strategy.setup_module_and_optimizers(  # type: ignore[assignment]
    199         module, list(optimizers)
    200     )
    201 else:
    202     module = self._strategy.setup_module(module)

File /usr/local/lib/python3.8/dist-packages/lightning/fabric/strategies/strategy.py:122, in Strategy.setup_module_and_optimizers(self, module, optimizers)
    114 def setup_module_and_optimizers(
    115     self, module: Module, optimizers: List[Optimizer]
    116 ) -> Tuple[Module, List[Optimizer]]:
    117     """Set up a model and multiple optimizers together.
    118 
    119     The returned objects are expected to be in the same order they were passed in. The default implementation will
    120     call :meth:`setup_module` and :meth:`setup_optimizer` on the inputs.
    121     """
--> 122     module = self.setup_module(module)
    123     optimizers = [self.setup_optimizer(optimizer) for optimizer in optimizers]
    124     return module, optimizers

File /usr/local/lib/python3.8/dist-packages/lightning/fabric/strategies/ddp.py:117, in DDPStrategy.setup_module(self, module)
    115 def setup_module(self, module: Module) -> DistributedDataParallel:
    116     """Wraps the model into a :class:`~torch.nn.parallel.distributed.DistributedDataParallel` module."""
--> 117     return DistributedDataParallel(module=module, device_ids=self._determine_ddp_device_ids(), **self._ddp_kwargs)

File /usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py:625, in DistributedDataParallel.__init__(self, module, device_ids, output_device, dim, broadcast_buffers, process_group, bucket_cap_mb, find_unused_parameters, check_reduction, gradient_as_bucket_view, static_graph)
    622     self.output_device = _get_device_index(output_device, True)
    624 if process_group is None:
--> 625     self.process_group = _get_default_group()
    626 else:
    627     self.process_group = process_group

File /usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py:697, in _get_default_group()
    693 """
    694 Getting the default process group created by init_process_group
    695 """
    696 if not is_initialized():
--> 697     raise RuntimeError(
    698         "Default process group has not been initialized, "
    699         "please make sure to call init_process_group."
    700     )
    701 return GroupMember.WORLD

RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
```

### Environment

* CUDA:
	- GPU:
		- NVIDIA A100-SXM4-80GB
		- NVIDIA A100-SXM4-80GB
		- NVIDIA A100-SXM4-80GB
		- NVIDIA A100-SXM4-80GB
		- NVIDIA A100-SXM4-80GB
		- NVIDIA A100-SXM4-80GB
		- NVIDIA A100-SXM4-80GB
		- NVIDIA A100-SXM4-80GB
	- available:         True
	- version:           11.7
* Lightning:
	- lightning:         2.0.1.post0
	- lightning-cloud:   0.5.33
	- lightning-utilities: 0.8.0
	- pytorch-lightning: 2.0.1.post0
	- tensorly-torch:    0.4.0
	- torch:             2.0.0
	- torchmetrics:      0.11.4
	- torchvision:       0.15.1
* Packages:
	- aiofiles:          22.1.0
	- aiohttp:           3.8.4
	- aiohttp-cors:      0.7.0
	- aiosignal:         1.3.1
	- aiosqlite:         0.18.0
	- alembic:           1.10.3
	- anyio:             3.6.2
	- argcomplete:       3.0.5
	- argon2-cffi:       21.3.0
	- argon2-cffi-bindings: 21.2.0
	- arrow:             1.2.3
	- asttokens:         2.2.1
	- async-timeout:     4.0.2
	- attrs:             22.2.0
	- babel:             2.12.1
	- backcall:          0.2.0
	- beautifulsoup4:    4.12.0
	- bleach:            6.0.0
	- blessed:           1.20.0
	- cachetools:        5.3.0
	- certifi:           2022.12.7
	- cffi:              1.15.1
	- charset-normalizer: 3.1.0
	- click:             8.1.3
	- cloudpickle:       2.2.1
	- cloup:             2.0.0.post1
	- cmake:             3.26.0
	- colorful:          0.5.5
	- comm:              0.1.2
	- contourpy:         1.0.7
	- croniter:          1.3.14
	- cycler:            0.11.0
	- databricks-cli:    0.17.6
	- dateutils:         0.6.12
	- debugpy:           1.6.6
	- decorator:         5.1.1
	- deepdiff:          6.3.0
	- defusedxml:        0.7.1
	- dill:              0.3.6
	- distlib:           0.3.6
	- docker:            6.0.1
	- entrypoints:       0.4
	- executing:         1.2.0
	- fastapi:           0.88.0
	- fastjsonschema:    2.16.3
	- filelock:          3.10.0
	- flask:             2.2.3
	- fonttools:         4.39.3
	- frozenlist:        1.3.3
	- fsspec:            2023.4.0
	- gitdb:             4.0.10
	- gitpython:         3.1.31
	- google-api-core:   2.11.0
	- google-auth:       2.17.1
	- googleapis-common-protos: 1.59.0
	- gpustat:           1.0.0
	- graphviz:          0.20.1
	- greenlet:          2.0.2
	- grpcio:            1.53.0
	- gunicorn:          20.1.0
	- h11:               0.14.0
	- idna:              3.4
	- importlib-metadata: 4.13.0
	- importlib-resources: 5.12.0
	- inquirer:          3.1.3
	- ipykernel:         6.22.0
	- ipython:           8.11.0
	- ipython-genutils:  0.2.0
	- itsdangerous:      2.1.2
	- jedi:              0.18.2
	- jinja2:            3.1.2
	- joblib:            1.2.0
	- json5:             0.9.11
	- jsonschema:        4.17.3
	- jupyter-client:    8.1.0
	- jupyter-core:      5.3.0
	- jupyter-events:    0.6.3
	- jupyter-server:    2.5.0
	- jupyter-server-fileid: 0.8.0
	- jupyter-server-terminals: 0.4.4
	- jupyter-server-ydoc: 0.8.0
	- jupyter-ydoc:      0.2.3
	- jupyterlab:        3.6.2
	- jupyterlab-pygments: 0.2.2
	- jupyterlab-server: 2.20.0
	- kiwisolver:        1.4.4
	- lightning:         2.0.1.post0
	- lightning-cloud:   0.5.33
	- lightning-utilities: 0.8.0
	- lit:               16.0.0
	- llvmlite:          0.39.1
	- mako:              1.2.4
	- markdown:          3.4.3
	- markdown-it-py:    2.2.0
	- markupsafe:        2.1.2
	- matplotlib:        3.7.1
	- matplotlib-inline: 0.1.6
	- mdurl:             0.1.2
	- mistune:           2.0.5
	- mlflow:            2.2.2
	- mpmath:            1.3.0
	- msgpack:           1.0.5
	- multidict:         6.0.4
	- nbclassic:         0.5.3
	- nbclient:          0.7.2
	- nbconvert:         7.2.10
	- nbformat:          5.8.0
	- nest-asyncio:      1.5.6
	- networkx:          3.0
	- nose:              1.3.7
	- notebook:          6.5.3
	- notebook-shim:     0.2.2
	- numba:             0.56.4
	- numpy:             1.20.3
	- nvidia-cublas-cu11: 11.10.3.66
	- nvidia-cuda-cupti-cu11: 11.7.101
	- nvidia-cuda-nvrtc-cu11: 11.7.99
	- nvidia-cuda-runtime-cu11: 11.7.99
	- nvidia-cudnn-cu11: 8.5.0.96
	- nvidia-cufft-cu11: 10.9.0.58
	- nvidia-curand-cu11: 10.2.10.91
	- nvidia-cusolver-cu11: 11.4.0.1
	- nvidia-cusparse-cu11: 11.7.4.91
	- nvidia-ml-py:      11.495.46
	- nvidia-nccl-cu11:  2.14.3
	- nvidia-nvtx-cu11:  11.7.91
	- oauthlib:          3.2.2
	- opencensus:        0.11.2
	- opencensus-context: 0.1.3
	- ordered-set:       4.1.0
	- orquestra-sdk:     0.46.1.dev11+gc1c7a12
	- packaging:         23.0
	- pandas:            2.0.0
	- pandocfilters:     1.5.0
	- parso:             0.8.3
	- pexpect:           4.8.0
	- pickleshare:       0.7.5
	- pillow:            9.5.0
	- pip:               20.0.2
	- pip-api:           0.0.30
	- pkgutil-resolve-name: 1.3.10
	- platformdirs:      3.1.1
	- prometheus-client: 0.16.0
	- prompt-toolkit:    3.0.38
	- protobuf:          4.22.1
	- psutil:            5.9.4
	- ptyprocess:        0.7.0
	- pure-eval:         0.2.2
	- py-spy:            0.3.14
	- pyarrow:           11.0.0
	- pyasn1:            0.4.8
	- pyasn1-modules:    0.2.8
	- pycparser:         2.21
	- pydantic:          1.10.7
	- pygments:          2.14.0
	- pyjwt:             2.6.0
	- pyparsing:         3.0.9
	- pyrsistent:        0.19.3
	- python-dateutil:   2.8.2
	- python-editor:     1.0.4
	- python-json-logger: 2.0.7
	- python-multipart:  0.0.6
	- pytorch-lightning: 2.0.1.post0
	- pytz:              2022.7.1
	- pyyaml:            6.0
	- pyzmq:             25.0.2
	- querystring-parser: 1.2.4
	- ray:               2.3.0
	- readchar:          4.0.5
	- requests:          2.28.2
	- rfc3339-validator: 0.1.4
	- rfc3986-validator: 0.1.1
	- rich:              13.3.4
	- rsa:               4.9
	- scikit-learn:      1.2.2
	- scipy:             1.10.1
	- send2trash:        1.8.0
	- setuptools:        45.2.0
	- shap:              0.41.0
	- six:               1.16.0
	- slicer:            0.0.7
	- smart-open:        6.3.0
	- smmap:             5.0.0
	- sniffio:           1.3.0
	- soupsieve:         2.4
	- sqlalchemy:        2.0.9
	- sqlparse:          0.4.3
	- stack-data:        0.6.2
	- starlette:         0.22.0
	- starsessions:      1.3.0
	- sympy:             1.11.1
	- tabulate:          0.9.0
	- tensorly:          0.8.1
	- tensorly-torch:    0.4.0
	- terminado:         0.17.1
	- threadpoolctl:     3.1.0
	- tinycss2:          1.2.1
	- tomli:             2.0.1
	- torch:             2.0.0
	- torchmetrics:      0.11.4
	- torchvision:       0.15.1
	- tornado:           6.2
	- tqdm:              4.65.0
	- traitlets:         5.9.0
	- triton:            2.0.0
	- typing-extensions: 4.5.0
	- tzdata:            2023.3
	- urllib3:           1.26.15
	- uvicorn:           0.21.1
	- virtualenv:        20.21.0
	- wcwidth:           0.2.6
	- webencodings:      0.5.1
	- websocket-client:  1.5.1
	- websockets:        11.0.1
	- werkzeug:          2.2.3
	- wheel:             0.34.2
	- wrapt:             1.15.0
	- y-py:              0.5.9
	- yarl:              1.8.2
	- ypy-websocket:     0.8.4
	- zipp:              3.15.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.8.10
	- version:           #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023

cc @carmocca @justusschock @awaelchli

**Comment by awaelchli** [comment]
@VolodyaCO 
For multi-device training, you have to call 
```py
fabric.launch()
```
to launch and init each process, or use any of the other methods to launch.
You can follow the documentation [here](https://lightning.ai/docs/fabric/stable/fundamentals/launch.html) for distributed launch.

**Comment by awaelchli** [comment]
There is probably a way to give a better error message, but I need to think about the edge cases.

**Comment by carmocca** [comment]
It could simply check that `.launch()/CLI/.run()` was called before `.setup()` for distributed strategies

**Comment by VolodyaCO** [comment]
Thanks for your answer @awaelchli! It works if I put the code in a script and run it. However, if I run from an ipython session, it fails. Is it intended to fail there?:
```python
In [1]: import torch.nn as nn
   ...: import torch
   ...: from lightning.fabric import Fabric

In [2]: fabric=Fabric(devices=2)

In [3]: encoder = nn.Sequential(nn.Linear(28 * 28, 64), nn.ReLU(), nn.Linear(64, 3))

In [4]: params = encoder.parameters()

In [5]: optimizer = torch.optim.Adam(params, lr=1e-3)

In [6]: fabric.launch()
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------

You are using a CUDA device ('NVIDIA A100-SXM4-80GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision

In [7]: model, opt = fabric.setup(encoder, optimizer)
You are using a CUDA device ('NVIDIA A100-SXM4-80GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[7], line 1
----> 1 model, opt = fabric.setup(encoder, optimizer)

File /usr/local/lib/python3.8/dist-packages/lightning/fabric/fabric.py:198, in Fabric.setup(self, module, move_to_device, *optimizers)
    196 # Let accelerator/plugin wrap and connect the models and optimizers
    197 if optimizers:
--> 198     module, optimizers = self._strategy.setup_module_and_optimizers(  # type: ignore[assignment]
    199         module, list(optimizers)
    200     )
    201 else:
    202     module = self._strategy.setup_module(module)

File /usr/local/lib/python3.8/dist-packages/lightning/fabric/strategies/strategy.py:122, in Strategy.setup_module_and_optimizers(self, module, optimizers)
    114 def setup_module_and_optimizers(
    115     self, module: Module, optimizers: List[Optimizer]
    116 ) -> Tuple[Module, List[Optimizer]]:
    117     """Set up a model and multiple optimizers together.
    118 
    119     The returned objects are expected to be in the same order they were passed in. The default implementation will
    120     call :meth:`setup_module` and :meth:`setup_optimizer` on the inputs.
    121     """
--> 122     module = self.setup_module(module)
    123     optimizers = [self.setup_optimizer(optimizer) for optimizer in optimizers]
    124     return module, optimizers

File /usr/local/lib/python3.8/dist-packages/lightning/fabric/strategies/ddp.py:117, in DDPStrategy.setup_module(self, module)
    115 def setup_module(self, module: Module) -> DistributedDataParallel:
    116     """Wraps the model into a :class:`~torch.nn.parallel.distributed.DistributedDataParallel` module."""
--> 117     return DistributedDataParallel(module=module, device_ids=self._determine_ddp_device_ids(), **self._ddp_kwargs)

File /usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py:625, in DistributedDataParallel.__init__(self, module, device_ids, output_device, dim, broadcast_buffers, process_group, bucket_cap_mb, find_unused_parameters, check_reduction, gradient_as_bucket_view, static_graph)
    622     self.output_device = _get_device_index(output_device, True)
    624 if process_group is None:
--> 625     self.process_group = _get_default_group()
    626 else:
    627     self.process_group = process_group

File /usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py:697, in _get_default_group()
    693 """
    694 Getting the default process group created by init_process_group
    695 """
    696 if not is_initialized():
--> 697     raise RuntimeError(
    698         "Default process group has not been initialized, "
    699         "please make sure to call init_process_group."
    700     )
    701 return GroupMember.WORLD

RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
```

**Comment by awaelchli** [comment]
Ipython should not be used to run DDP. This is not supported.

**Comment by qiqiApink** [comment]
I have the same issue. I called fabric.launch(), but this still doesn't work.

**Comment by awaelchli** [comment]
@qiqiApink Could you please provide more information? Preferably in a new issue. Thank you.
