### ISSUE TITLE
DDP does not work if model has no parameters

### ISSUE THREAD

**Issue by surya-narayanan** [Lightning-AI/lightning#17556]
### Bug description

I have a model that can run for 1 GPU, but doesn't work on 2 GPUs.

`RuntimeError: DistributedDataParallel is not needed when a module doesn't have any parameter that requires a gradient`

I see online that this error relates to a case where someone is forward propagating but not training. I am training, and have train dataloaders- so I’m not able to understand why I am facing this issue. Any thoughts?

### What version are you seeing the problem on?

master

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by surya-narayanan** [comment]
update, it seems by setting `self.model=some_arbitrary_model`, I was able to get the model to train, but I'm not sure why.

**Comment by awaelchli** [comment]
@surya-narayanan Your model doesn't have any parameters, correct? If you do `list(model.parameters())` it probably returns an empty list. You probably have a bug in the way you compose your modules.

**Comment by surya-narayanan** [comment]
Hmm, so I do define a list of parameters in my configure_optimizers function. 

```
def configure_optimizers(self):
        params = list()

        params.extend(list(self.encoder.parameters()))
        params.extend(list(self.decoder.parameters()))

        optimizer = AdamW(params, lr=5e-5)

        return optimizer
```

should I add a `self.parameters = params` somewhere within? Would that help?

**Comment by surya-narayanan** [comment]
So the `self.encoder` and `self.decoder` are not `nn.Modules` but other custom classes that have `nn.Module` objects. So the more honest code would be 

```
def configure_optimizers(self):
        params = list()

        params.extend(list(self.encoder.model.parameters()))
        params.extend(list(self.decoder.model.parameters()))

        optimizer = AdamW(params, lr=5e-5)

        return optimizer
```

Would you say that's a problem?

Btw, printing out `model.parameters`, prints `[]` as expected

**Comment by awaelchli** [comment]
I don't think this is a very PyTorch-friendly way of working with models. I strongly suggest that you include your encoder and decoder as proper submodules under LightnignModule. You could hack around this by overriding `self.parameters()`, `state_dict` etc. but I don't think it is worth it to work against PyTorch. 

The easiest would be to make your encoder and decoder classes nn.Modules.

**Comment by awaelchli** [comment]
The entire LightningModule gets wrapped in to DDP: https://pytorch.org/docs/stable/generated/torch.nn.parallel.DistributedDataParallel.html#torch.nn.parallel.DistributedDataParallel

So yes, it applies to all submodules in LightningModule.

**Comment by surya-narayanan** [comment]
it seems even if i do 

`self.encoder, self.decoder = [transformer.AutoModel(i) for i in mylist]`, 

it seems the models are not being moved to my cuda device even though my encoder and decoder are nn.Modules

**Comment by awaelchli** [comment]
This is a very error-prone way of using list unpacking into the two attributes. What if the length of mylist is anything other than 2?

If you want to put modules in a list, make sure to use `torch.nn.ModuleList`. 
https://pytorch.org/docs/stable/generated/torch.nn.ModuleList.html

**Comment by surya-narayanan** [comment]
Cool, I'm going to close this issue then, and reopen / open another one if something comes up. Thanks for the prompt response and orthogonal help, @awaelchli, @Borda :)
