### ISSUE TITLE
Concurrent distributed training runs on a SLURM cluster with `srun`

### ISSUE THREAD

**Issue by dcfidalgo** [Lightning-AI/lightning#17550]
### Description & Motivation

When doing a parameter sweep (HPO), you often want to run multiple training runs concurrently. In our use case, the training runs use the `ddp` strategy (1 node, 4 GPUs) and are executed on a SLURM cluster.

We reserve the required resources via `sbatch` and then run the single training runs via `srun`. With this approach, we cannot use the [SLURM ClusterEnvironment](https://github.com/Lightning-AI/lightning/blob/master/src/lightning/fabric/plugins/environments/slurm.py#L31) since the [main address](https://github.com/Lightning-AI/lightning/blob/master/src/lightning/fabric/plugins/environments/slurm.py#L56) is determined by the first entry of the `SLURM_NODELIST`, which is the list of nodes for the whole job (sbatch), not the job step (srun).

From a single training run, we saw that using the SLURM ClusterEnvironment is a bit faster, which is also expected. So we would like to use it for our parameter sweeps as well.

### Pitch

We would like to be able to specify the main address manually when creating a [SLURMEnvironment](https://github.com/Lightning-AI/lightning/blob/master/src/lightning/fabric/plugins/environments/slurm.py#L31) instance, something like:
```python
concurrent_slurm_env = SLURMEnvironment(main_address="localhost")
trainer = Trainer(plugins=concurrent_slurm_env)
```

### Alternatives

Alternatively one could try to extract the main address from the `SLURM_STEP_NODELIST` env variable (not available on all SLURM clusters), or via the `scontrol` command.

### Additional context

If you think this feature request is reasonable, I would be more than happy to provide a PR.

cc @borda @awaelchli

**Comment by awaelchli** [comment]
I think this is reasonable request @dcfidalgo. If we are exposing the main address, I suggest also exposing the main port. These should be optional. A PR for this would be very welcomed!

I'm not familiar enough with SLURM to comment on whether SLURM_STEP_NODELIST should be auto-detected.
