### ISSUE TITLE
_FastApiMockRequest class method property is raised instead of returned

### ISSUE THREAD

**Issue by bkiat1123** [Lightning-AI/lightning#17580]
### Bug description

Nothing complicated, just a typo, should return instead of raise the property.

https://github.com/Lightning-AI/lightning/blob/54e8095a78eafad3f4e16b799198b7bce8d327d2/src/lightning/app/api/http_methods.py#L38-L74

### What version are you seeing the problem on?

master

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
@bkiat1123 I'm not sure I understand. What is your proposal exactly?

**Comment by bkiat1123** [comment]
@awaelchli 

Return the method property instead of raising it.

From
```
@property 
def method(self): 
   raise self._method 
```

to 

```
@property 
def method(self): 
   return self._method 
```

**Comment by awaelchli** [comment]
Would you like to send a PR for this?
