### ISSUE TITLE
RFC: Future of init context managers in Fabric

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#17581]
### Description & Motivation

Recently, #17488 was merged with the following changes in summary:

- `Fabric.init()`: managing the device and precision part that Fabric.init_module() does
- Undeprecated `fabric.sharded_model()`
- Renamed the `Strategy.init_module` and `Precision.init_module` to just `init_context()`
- Renamed `Strategy.init_sharded_context` without backward compatibility

These points work against the preparation work done in #17462 to provide a unified, strategy-agnostic way of initializing the model, and the PR didn't provide much motivation to for this overhaul. The main point was given in the documentation: "Using these separately can provide more control for expert users".

Here are my concerns and why #17488 should be reverted, or partially reverted.

**Concern 1: There are multiple ways of doing the same thing now.**
`Fabric.init()`, `Fabric.init_module()` have overlapping functionality. They can both be used to initialize the module and control how tensors are created. "Which one should be used?" is what the user could ask. The ambiguous name "init" doesn't help here. Furthermore, `Fabric.init()`'s implementation is tied to the strategy because it calls `Strategy.init_context()`, but why should the strategy decide how tensors are created outside the model? There is a lack of motivation through examples and use cases. From a documentation perspective, personally, I would find myself struggling to explain the differences to a newcomer.

**Concern 2: `Fabric.init()` is redundant.**
PyTorch accepts device and dtype attributes everywhere and has plenty of flexibility when it comes to tensor creation this way. With the `fabric.device` property, you can already create tensors directly on the device. In my opinion, this is an unneeded PyTorch abstraction layer. The cost is that it increases the API surface of Fabric, and makes the user study the differences between the overlapping features of the context managers. It is unclear to me why this feature was promoted as "more flexibility for expert users" when in reality the choice of dtype and device is tied to the strategy. 

**Concern 3: `Fabric.init` is a misleading name**
Generally speaking, method names should be communicating the action they perform on the object or what they are meant to return. Here, without knowing any further context, `Fabric.init()` communicates that it initializes Fabric itself, which is of course wrong. The previous name `Fabric.init_module()` was better, because the user is forced to study its return type to understand the intentions. You can't pass in the model as an argument, because that would lead to an error and thus the user will understand that this is actually a context manager.

**Concern 4: The `sharded_model` API is misleading and misunderstood.**
One motivation behind the original PR #17462 was to provide a better-named API for instantiating modules, where both the name and the functionality would be agnostic to the strategy/device choice. This meant the `Fabric.sharded_model()` context had to be discouraged in favor of the more generalized `Fabric.init_module()`. Confusions like https://github.com/Lightning-AI/lightning/pull/17488#pullrequestreview-1414249897 are the prime example that there exists a misunderstanding of what `Fabric.sharded_model()` does. Hint: It does NOT shard the model!

**Concern 5: It is unclear where empty weight initialization /  deferred init should be implemented now.**
The motivation in #17462 was to have a unified model instantiation context that would take care of efficient initialization, and potentially deferred/lazy instantiation if it made sense given the strategy. Where should this feature be added now? To only some of the context managers, to all of them? It is very unclear to me what the future of this feature is now. 

### Pitch

My proposal to address the concerns is:

1. Discuss the above concerns and align on the future to provide a more focused API.
2. Discourage the use of the `sharded_model()` by reverting that part in #17488. 
3. Either revert the addition of `Fabric.init()` or keep it at least undocumented/protected until there is a strong demand for it.

### Alternatives

A) An alternative would be to find better-fitting names for the context managers discussed here, but it would only address the concerns partially. There would still be a lot of open questions. 

B) Instead of `Fabric.init()`, provide a standalone function/context manager (pseudo code):

```py
@contextmanager
def init(device, dtype):
    torch.set_default_tensor_dtype(dtype)
    with device:
        yield
    ...
```

### Additional context

Requesting review from @carmocca @lantiga @justusschock 

We should align on this before 2.1, because after that it will be too late to change any of these APIs.

**Comment by carmocca** [comment]
> Renamed Strategy.init_sharded_context without backward compatibility

This is safe because this hook comes from a protected interface: `_Sharded`

> There are multiple ways of doing the same thing now.

> is redundant.

`init` and `init_module` have overlapping functionality by design: one is just a wrapper over the other. We recommend `init_module` as the plug-n-go option in the docs: https://lightning.ai/docs/fabric/latest/api/fabric_methods.html#init-module.

The strategy decides this because it controls the accelerator (device) and precision (dtype).
> the choice of dtype and device is tied to the strategy.

`.init()` has a few advantages over recommending `fabric.device`.
- discoverability: having a fabric method for it allows the user to learn they can do this, it's not well known for most pytorch users that you can use torch.device as a context manager, especially non-experts.
- compatibility: using torch.device as a context manager requires checking your torch version. Init can do it for you
- dtype support: by going through the strategy, the dtype is also set. currently there's no `with torch.float16` support.
- future-proofing: if in the future there's new enhancements to initialization that depend on the strategy, we can simply add them to `.init()` (via `.strategy.init_context()`) and both this method and `.init_module()` get the benefit.

> is a misleading name

Sounds good! Let's change it with a clearer alternative.

> The previous name

`.init_module()` is unchanged and still our recommended solution. #17488 doesn't intend to change it functionally.

> The sharded_model API is misleading and misunderstood.

Sounds good, we can add back the deprecation for `sharded_model`. It's true that it's hard to see any users enabling that context manager exclusively.

> unclear where empty weight initialization / deferred init should be implemented now.

I don't see how its (possible) implementation changes based on #17488. At the level of the strategy the changes are just in the method names. Would you mind clarifying this?

Happy to address your concerns!

**Comment by awaelchli** [comment]
@carmocca Thanks for looking at this feedback. I opened #17607 which adds back the deprecation and reverts a few things while keeping `Fabric.init()` separated.

> The strategy decides this because it controls the accelerator (device) and precision (dtype).

The strategy should decide how to init the module yes, but this decision (device/precision) may not be the right decision for just arbitrary tensor instantiation outside the module. The functionality overlaps for something that should be kept separate, this is my main complaint here. While the introduction of init_module() was fairly motivated with clear example usages (e.g. in lit-llama), the introduction and design for `Fabric.init()` was not motivated at all by practical use cases.

**Comment by awaelchli** [comment]
> This is safe because this hook comes from a protected interface: _Sharded

The class is protected, but it's added to the public interface of every strategy, and the method itself is public. I personally would prefer to just remove it, but after 2.0 we have strict rules and to make an exception here would be very arbitrary.

**Comment by carmocca** [comment]
> The strategy should decide how to init the module yes, but this decision (device/precision) may not be the right decision for just arbitrary tensor instantiation outside the module. The functionality overlaps for something that should be kept separate, this is my main complaint here

I don't fully grasp this argument. The practical use would be to replace Lit-LLaMa's `EmptyInitOnDevice` (currently -quantization and -empty) for non-modules where you don't care about the sharded logic, or modules if you don't want to run the sharded logic for whatever reason.

> The class is protected, but it's added to the public interface of every strategy, and the method itself is public. I personally would prefer to just remove it, but after 2.0 we have strict rules and to make an exception here would be very arbitrary.

These methods are not meant to be called externally. The only breakage would be in somebody extending our strategies and overriding the method. These are very experimental APIs and we should prefer future UX and clarity over a very slim chance of breakage which would only impact super expert users who are very deep into the framework.

**Comment by awaelchli** [comment]
For an alternative name for `Fabric.init`, I propose `Fabric.init_tensor`.
