### ISSUE TITLE
ZeRORuntimeException: 

### ISSUE THREAD

**Issue by picard314** [Lightning-AI/lightning#17603]
### Bug description

Hi dear develops,

I met the log:

ZeRORuntimeException: You are using ZeRO-Offload with a client provided 
optimizer (<class 'torch.optim.adamw.AdamW'>) which in most cases will yield 
poor performance. Please either use deepspeed.ops.adam.DeepSpeedCPUAdam or set 
an optimizer in your ds-config 
(https://www.deepspeed.ai/docs/config-json/#optimizer-parameters). If you 
really want to use a custom optimizer w. ZeRO-Offload and understand the 
performance impacts you can also set <"zero_force_ds_cpu_optimizer": false> in 
your configuration file.

by running

model = MyModel()
trainer = Trainer(accelerator="gpu", devices=4, strategy="deepspeed_stage_3_offload", precision=16)
trainer.fit(model)

The version of installed pytorch-lightning is 1.9.0. 

I am looking forward to your reply. Thanks so much!

Best,
Picard314

### What version are you seeing the problem on?

v1.9

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @awaelchli

**Comment by carmocca** [comment]
You can avoid this by doing

```python
trainer.strategy.config["zero_force_ds_cpu_optimizer"] = False
```

Related refactor: #17472

**Comment by picard314** [comment]
> You can avoid this by doing
> 
> ```python
> trainer = Trainer(strategy="deepspeed_stage_3_offload", ...)
> trainer.strategy.config["zero_force_ds_cpu_optimizer"] = False
> trainer.fit(model)
> ```
> 
> Related refactor: #17472


Hi @carmocca 

Thanks！It works but another “AttributeError” occurs：

AttributeError: `Trainer.root_gpu` was deprecated in v1.6 and is no longer 
accessible as of v1.8. Please use `Trainer.strategy.root_device.index` instead.

The breakpoint is at 

"~/anaconda3/envs/Tav/lib/python3.8/site-packages/pytorch_lightning/_graveyard/trainer.py:53"

Could you please aid me again..

Best,
Picard314

**Comment by carmocca** [comment]
Can you find where in your code `trainer.root_gpu` is getting called? You can replace it with `trainer.strategy.root_device.index` as the error suggests.

If you cannot modify the code, then you'll probably need to install an older `pytorch_lightning` version that can run it

**Comment by picard314** [comment]
> Can you find where in your code `trainer.root_gpu` is getting called? You can replace it with `trainer.strategy.root_device.index` as the error suggests.
> 
> If you cannot modify the code, then you'll probably need to install an older `pytorch_lightning` version that can run it

Ah, yes. I just found where the problem is on my own script. Thanks for your patient for the slack me : )

By the way, the script is running currently without error occurring but logs seems to have seized without proceeding. I worry the server (NVIDIA GeForce RTX 3090, 2 GPUs) I use may be slow in implementing deep speed or my task is still not running correctly.

I shall be most grateful if you may take a glance at my logs starting from trainer.fit(model). Thanks~
[logs starting from trainer.fit.txt](https://github.com/Lightning-AI/lightning/files/11447633/logs.starting.from.trainer.fit.txt)

Best,
Picard314

**Comment by picard314** [comment]
Hi dear @carmocca , again

Now I have finished debugging and my task is running all well. Thanks again for your kind support!

Cheers,
Picard314
