### ISSUE TITLE
Support true half-precision in Trainer

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#17609]
### Description & Motivation

We recently added the `HalfPrecision` plugin in Fabric. The usage looks like this:

```py
fabric = Fabric(precision="16-true")
# or
fabric = Fabric(precision="bf16-true")
```

This feature is not exclusive to Fabric and can easily be added to Trainer as well.

### Pitch

Support the following:

```py
trainer = Trainer(precision="16-true")
# or
trainer = Trainer(precision="bf16-true")
```

To support this, we need to add the HalfPrecision plugin and minor modifications to the DeepSpeedPrecision and FSDPPrecision plugins. 

### Additional context

This change should also include/close #17727

cc @borda @carmocca @justusschock @awaelchli

**Comment by carmocca** [comment]
This will also unblock quantization and using flash attention with the Trainer. We should do this before 2.1
