### ISSUE TITLE
Runtime error during model deserialization on "mps"

### ISSUE THREAD

**Issue by alisterburt** [Lightning-AI/lightning#17618]
### Bug description

during `LightningModule.load_from_checkpoint()` I'm running into
`torch.UntypedStorage(): Storage device not recognized: mps `

https://github.com/teamtomo/fidder/actions/runs/4957678926/jobs/8869653169?pr=23#step:6:105

This is with a model checkpoint saved from an mps training run pre-2.0. The deserialisation is happening on a CI runner on ubuntu. I do not see the same error when deserialising the model locally, I suspect this problem may be specific to deserialising an mps checkpoint on linux

### What version are you seeing the problem on?

v2.0

cc @awaelchli @justusschock

**Comment by awaelchli** [comment]
@alisterburt You can pass `map_location="cpu"` when loading. Does this solve the issue?
