### ISSUE TITLE
Loading a model from torch.hub leads to a pickle related error

### ISSUE THREAD

**Issue by onurbagoren** [Lightning-AI/lightning#17637]
### Bug description

As an input to my model, I am using the output of the MiDaS monocular depth output. For this, I initialize it as such in the constructor in my model:
`self.mono_depth = torch.hub.load("intel-isl/MiDaS", self.model_type).eval()`

I then use it in the dataloader as such to generate the mono-depth prediction:
```
with torch.no_grad():
    mono_depth_out = self.mono_depth(img)
    mono_depth_out = torch.nn.functional.interpolate(mono_depth_out.unsqueeze(1), size=img.shape[-2:], mode="bicubic", align_corners=False,).squeeze(0)
```

For the trainer, I initialize it as such:
```
checkpoint_callback = ModelCheckpoint(
        dirpath="/home/obagoren/log", save_last=True
    )
    trainer = pl.Trainer(max_steps=2e5, callbacks=[checkpoint_callback], gpus=[0, 1])
    trainer.fit(model)
```
In the `trainer.fit(model)` line, I get the following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/obagoren/miniconda3/envs/vair_env/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/obagoren/miniconda3/envs/vair_env/lib/python3.10/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
ModuleNotFoundError: No module named 'midas'
```

For the data loader, I am using 64 workers and a batch size of 16. 

I am lost as to how to resolve this issue, as when I try to debug, the debugger does not step into `trainer.fit(model)`. I was wondering if anyone has come across this issue, and whether there is a working solution to it. Thank you!

### What version are you seeing the problem on?

v1.9

### How to reproduce the bug

```python
class Model(pl.LightningModule):
    def __init__(self,....):
        self.model_type = model_type
        print('Mono depth loaded')
        self.mono_depth = torch.hub.load("intel-isl/MiDaS", self.model_type).eval()

    ....

    def training_step(self, batch, batch_idx):
        x, y = batch
        with torch.no_grad():
        with torch.no_grad():
            mono_depth_out = self.mono_depth(img)
            mono_depth_out = torch.nn.functional.interpolate(mono_depth_out.unsqueeze(1), size=img.shape[-2:], mode="bicubic", align_corners=False,).squeeze(0)

        ....
        return loss


             
        mono_depth =
```

### Error messages and logs

```

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/obagoren/miniconda3/envs/vair_env/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/obagoren/miniconda3/envs/vair_env/lib/python3.10/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
ModuleNotFoundError: No module named 'midas'
```

### Environment

<details>
  <summary>Current environment</summary>

* CUDA:
	- GPU:
		- NVIDIA RTX A6000
		- NVIDIA RTX A6000
	- available:         True
	- version:           11.7
* Lightning:
	- lightning-utilities: 0.8.0
	- pytorch-lightning: 1.9.3
	- torch:             2.0.0
	- torchaudio:        2.0.0
	- torchmetrics:      0.11.4
	- torchvision:       0.15.0
* Packages:
	- accelerate:        0.18.0
	- addict:            2.4.0
	- aiohttp:           3.8.4
	- aiosignal:         1.3.1
	- appdirs:           1.4.4
	- asttokens:         2.2.1
	- async-timeout:     4.0.2
	- attrs:             23.1.0
	- backcall:          0.2.0
	- backports.functools-lru-cache: 1.6.4
	- blinker:           1.6.2
	- brotlipy:          0.7.0
	- certifi:           2023.5.7
	- cffi:              1.15.1
	- charset-normalizer: 2.0.4
	- click:             8.1.3
	- cloudpickle:       2.0.0
	- colorama:          0.4.6
	- configargparse:    1.5.3
	- contourpy:         1.0.7
	- cryptography:      39.0.1
	- cycler:            0.11.0
	- cytoolz:           0.12.0
	- dash:              2.9.3
	- dash-core-components: 2.0.0
	- dash-html-components: 2.0.0
	- dash-table:        5.0.0
	- dask:              2022.7.0
	- datasets:          2.11.0
	- debugpy:           1.5.1
	- decorator:         5.1.1
	- diffusers:         0.15.1
	- dill:              0.3.6
	- docker-pycreds:    0.4.0
	- einops:            0.6.1
	- entrypoints:       0.4
	- executing:         1.2.0
	- fastjsonschema:    2.16.3
	- filelock:          3.9.0
	- flask:             2.3.2
	- fonttools:         4.39.3
	- frozenlist:        1.3.3
	- fsspec:            2022.11.0
	- gitdb:             4.0.10
	- gitpython:         3.1.31
	- gmpy2:             2.1.2
	- h5py:              3.8.0
	- huggingface-hub:   0.13.4
	- idna:              3.4
	- imagecodecs:       2021.8.26
	- imageio:           2.19.3
	- importlib-metadata: 6.6.0
	- ipykernel:         6.15.0
	- ipython:           8.12.0
	- ipywidgets:        8.0.6
	- itsdangerous:      2.1.2
	- jedi:              0.18.2
	- jinja2:            3.1.2
	- joblib:            1.2.0
	- jsonschema:        4.17.3
	- jupyter-client:    7.3.4
	- jupyter-core:      4.12.0
	- jupyterlab-widgets: 3.0.7
	- kiwisolver:        1.4.4
	- kornia:            0.6.12
	- lightning-utilities: 0.8.0
	- locket:            1.0.0
	- markupsafe:        2.1.1
	- matplotlib:        3.7.1
	- matplotlib-inline: 0.1.6
	- mkl-fft:           1.3.1
	- mkl-random:        1.2.2
	- mkl-service:       2.4.0
	- mpmath:            1.2.1
	- multidict:         6.0.4
	- multiprocess:      0.70.14
	- nbformat:          5.7.0
	- nest-asyncio:      1.5.6
	- networkx:          2.8.4
	- numpy:             1.23.5
	- open3d:            0.17.0
	- packaging:         23.1
	- pandas:            2.0.0
	- parso:             0.8.3
	- partd:             1.2.0
	- pathtools:         0.1.2
	- pexpect:           4.8.0
	- pickleshare:       0.7.5
	- pillow:            9.4.0
	- pip:               23.0.1
	- plotly:            5.14.1
	- pooch:             1.4.0
	- prompt-toolkit:    3.0.38
	- protobuf:          4.22.3
	- psutil:            5.9.0
	- ptyprocess:        0.7.0
	- pure-eval:         0.2.2
	- pyarrow:           11.0.0
	- pycparser:         2.21
	- pygments:          2.15.1
	- pykernel:          0.1.6
	- pyopenssl:         23.0.0
	- pyparsing:         3.0.9
	- pyquaternion:      0.9.9
	- pyrsistent:        0.19.3
	- pysocks:           1.7.1
	- python-dateutil:   2.8.2
	- pytorch-lightning: 1.9.3
	- pytz:              2023.3
	- pywavelets:        1.4.1
	- pyyaml:            6.0
	- pyzmq:             23.2.0
	- regex:             2023.3.23
	- requests:          2.28.1
	- responses:         0.18.0
	- scikit-image:      0.19.3
	- scikit-learn:      1.2.2
	- scipy:             1.10.0
	- sentry-sdk:        1.20.0
	- setproctitle:      1.3.2
	- setuptools:        66.0.0
	- six:               1.16.0
	- smmap:             5.0.0
	- stack-data:        0.6.2
	- sympy:             1.11.1
	- tenacity:          8.2.2
	- threadpoolctl:     3.1.0
	- tifffile:          2021.7.2
	- timm:              0.6.13
	- tinycudann:        1.7
	- toolz:             0.12.0
	- torch:             2.0.0
	- torchaudio:        2.0.0
	- torchmetrics:      0.11.4
	- torchvision:       0.15.0
	- tornado:           6.1
	- tqdm:              4.65.0
	- traitlets:         5.9.0
	- triton:            2.0.0
	- typing-extensions: 4.5.0
	- tzdata:            2023.3
	- urllib3:           1.26.15
	- wandb:             0.15.0
	- wcwidth:           0.2.6
	- werkzeug:          2.3.4
	- wheel:             0.38.4
	- widgetsnbextension: 4.0.7
	- xxhash:            3.2.0
	- yarl:              1.9.1
	- zipp:              3.15.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.10.11
	- release:           5.15.0-71-generic

</details>

**Comment by awaelchli** [comment]
This is purely a PyTorch limitation due to spawning worker processes for the DataLoader. Closing the issue since it is unrelated to Lightning. Here is a hint at what to do:

```py
import torch
from torch.utils.data import DataLoader, Dataset


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)
        # Don't do this:
        # self.model = torch.hub.load("intel-isl/MiDaS", "MiDaS_small")
        # Do this:
        self.model = None

    def __getitem__(self, index):
        # Do this:
        # load model on first batch (this is inside worker process)
        if self.model is None:
            self.model = torch.hub.load("intel-isl/MiDaS", "MiDaS_small")

        return self.data[index]

    def __len__(self):
        return self.len


def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2, num_workers=2)
    for _ in train_data:
        pass


if __name__ == "__main__":
    run()

```
