### ISSUE TITLE
Loosen check on model step output types from `dict` to `Mapping`

### ISSUE THREAD

**Issue by qdbp** [Lightning-AI/lightning#17649]
### Description & Motivation

I want to be able to use custom classes that implement the `Mapping` interface as step outputs, and lightning should be able to work with them. `isinstance(..., dict)` is unnecessarily restrictive.

### Pitch

by example: line 63 of `loops/optimization/automatic.py` should go from this:
```
       if isinstance(training_step_output, dict):
```
to this:
```
      if isinstance(training_step_output, Mapping)
```

etc. This should (unless I am missing something) be a backward-compatible, mechanical change.

I think this change is in line with Pythonic design principles: duck typing and depending on abstractions, not concretions.

### Additional context

I wanted to use a class like this:
```
@dataclass(kw_only=True)
class HomogeneousAttrDataclass(Generic[T], Mapping[str, T]):

    def __iter__(self) -> Iterator[str]:
        return iter(it.name for it in fields(self))

    def __len__(self) -> int:
        return len(fields(self))

    def __getitem__(self, key: str) -> T:
        return getattr(self, key)
```

to be able to use nice IDE-supported dataclasses as step output types in my model, but found that lightning shuts that down with the `isinstance` check. There is a way to work around this by subclassing dict directly and then "hotwiring" the dict methods to point to dataclass fields (or whatever custom mapping impl people might want to use), but it's really ugly.

cc @borda

**Comment by Borda** [comment]
Sounds good to me 🐿️

**Comment by nik777** [comment]
Hi, @awaelchli
I would like to give it a try. Please assign.

**Comment by nik777** [comment]
@awaelchli do we need a test for it? Also I somehow managed to unassign myself so please assign me again :-).

**Comment by awaelchli** [comment]
We would need a test for this yes, but we can help with that later on your PR if you struggle.
