### ISSUE TITLE
Instantiating any Trainer just completely stalls Python

### ISSUE THREAD

**Issue by actuallyaswin** [Lightning-AI/lightning#17660]
### Bug description

I'm not sure how to describe my issue other than saying that Python3 just stalls whenever I try to create a Lightning Trainer class.

I have a script which I was developing up until a month ago, then I took a break, and just yesterday back to editing. It is possible that my CUDA version, Lightning version, or Python installation paths may have been changed within that month because I am on a shared device.

But as of now, the Trainer class is not working for me at all. I went to just do a simple test in a command-line interpreter; by just running:

```
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from lightning import Trainer
>>> t = Trainer()
```

The interpreter just hangs there without printing anything; I can't even get a KeyboardInterrupt through. So even though Ctrl+C doesn't work, I can still exit using Ctrl+Z.

I found this to be the case for both `lightning-2.0.2` and `lightning-2.0.0`. All other usages of lightning in my script (i.e., for LightningModules or LightningDataModules) work just like normal. It's just the Trainer that's having a problem.

Any advice on debugging or fixing this would be greatly appreciated.

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): Trainer
#- PyTorch Lightning Version (e.g., 1.5.0): 2.0.2
#- PyTorch Version (e.g., 2.0): 2.0.1
#- Python version (e.g., 3.9): 3.8.10
#- OS (e.g., Linux): Linux
#- CUDA/cuDNN version: CUDA Version: 12.1
#- GPU models and configuration: NVIDIA A40
#- How you installed Lightning(`conda`, `pip`, source): pip3
#- Running environment of LightningApp (e.g. local, cloud): local
```

</details>

**Comment by actuallyaswin** [comment]
Closing this issue as I resolved it by closing all running instances of Python in the system (e.g., `pgrep "python" | xargs kill`) then tried again. I had background processes running Jupyter Lab and Tensorboard and once I killed those, the Trainer() object now correctly initializes.

**Comment by awaelchli** [comment]
Thanks @actuallyaswin for letting us know what the solution was.
