### ISSUE TITLE
Automatically convert input to accelerator in forward(x)

### ISSUE THREAD

**Issue by 3top1a** [Lightning-AI/lightning#17688]
### Description & Motivation

As outlined in [this issue](https://github.com/pytorch/pytorch/issues/101935), it might be beneficial to automatically transfer input data of the modes forward function to the defined accelerator.

### Pitch

- Automatically transfer input data to accelerator before calling the models forward function

### Alternatives

You could also mention this in the docs

### Additional context

- https://github.com/pytorch/pytorch/issues/101935

cc @borda

**Comment by awaelchli** [comment]
@3top1a This is already implemented in Lightning. Tensors and collection of tensors (list, tuple, dict etc.) get converged automatically before the input reaches the `training_step`. You can test this yourself by `print(batch.device)` or similar in the training step hook.
