### ISSUE TITLE
load_from_checkpoint crashes when the module contains extra_state 

### ISSUE THREAD

**Issue by wjaskowski** [Lightning-AI/lightning#17695]
### Bug description

`LightningModule.load_from_checkpoint` fails with
```
saving.py", line 92, in _load_from_checkpoint
    map_location = list(state_dict.values())[0].device
AttributeError: 'dict' object has no attribute 'device'
```
when the pytorch Model contains `extra_state`.

### What version are you seeing the problem on?

v2.0

### How to reproduce the bug

```python
import pytorch_lightning as pl
import numpy as np
import torch
from torch.nn import MSELoss
from torch.optim import Adam
from torch.utils.data import DataLoader, Dataset
import torch.nn as nn


class SimpleDataset(Dataset):
    def __init__(self):
        X = np.arange(10000)
        y = X * 2
        X = [[_] for _ in X]
        y = [[_] for _ in y]
        self.X = torch.Tensor(X)
        self.y = torch.Tensor(y)

    def __len__(self):
        return len(self.y)

    def __getitem__(self, idx):
        return {"X": self.X[idx], "y": self.y[idx]}


class MyModel(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.fc = nn.Linear(1, 1)
        self.criterion = MSELoss()

    def forward(self, inputs_id, labels=None):
        outputs = self.fc(inputs_id)
        loss = 0
        if labels is not None:
            loss = self.criterion(outputs, labels)
        return loss, outputs

    def train_dataloader(self):
        dataset = SimpleDataset()
        return DataLoader(dataset, batch_size=1000)

    def training_step(self, batch, batch_idx):
        input_ids = batch["X"]
        labels = batch["y"]
        loss, outputs = self(input_ids, labels)
        return {"loss": loss}

    def configure_optimizers(self):
        optimizer = Adam(self.parameters())
        return optimizer

    # This causes the loading bug!
    def get_extra_state(self):
        return {"key": "value"}

    def set_extra_state(self, state):
        pass


if __name__ == '__main__':
    model = MyModel()
    trainer = pl.Trainer(max_epochs=1)
    trainer.fit(model)
    trainer.save_checkpoint("/tmp/checkpoint.ckpt")

    model = MyModel.load_from_checkpoint("/tmp/checkpoint.ckpt")
```

### Error messages and logs

```
Traceback (most recent call last):
  File "/tmp/bug.py", line 70, in <module>
    model = MyModel.load_from_checkpoint("/tmp/checkpoint.ckpt")
  File "lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 1531, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "lib/python3.10/site-packages/pytorch_lightning/core/saving.py", line 92, in _load_from_checkpoint
    map_location = list(state_dict.values())[0].device
AttributeError: 'dict' object has no attribute 'device'
```

### Environment

<details>
  <summary>Current environment</summary>

* CUDA:
	- GPU:               None
	- available:         False
	- version:           None
* Lightning:
	- lightning-utilities: 0.8.0
	- pytorch-lightning: 2.0.2
	- torch:             2.0.1
	- torchdata:         0.6.1
	- torchmetrics:      0.10.3
	- torchvision:       0.15.2
* Packages:
	- absl-py:           1.4.0
	- aiohttp:           3.8.4
	- aiosignal:         1.3.1
	- antlr4-python3-runtime: 4.9.3
	- astor:             0.8.1
	- async-timeout:     4.0.2
	- attrs:             21.4.0
	- bandit:            1.7.5
	- bitsandbytes:      0.38.1
	- black:             22.12.0
	- bleach:            6.0.0
	- boto3:             1.26.136
	- botocore:          1.29.136
	- cachetools:        5.3.0
	- certifi:           2023.5.7
	- cfgv:              3.3.1
	- charset-normalizer: 3.1.0
	- click:             8.1.3
	- cognitive-complexity: 1.3.0
	- cohesion:          1.0.0
	- colorama:          0.4.6
	- coverage:          5.5
	- cython:            0.29.34
	- dataclasses-json:  0.5.7
	- ddt:               1.4.4
	- decopatch:         1.4.10
	- deprecated:        1.2.13
	- distlib:           0.3.6
	- document-service-client: 8.0.62
	- docutils:          0.20
	- due-evaluator:     0.1.5
	- eradicate:         2.2.0
	- execnet:           1.9.0
	- filelock:          3.12.0
	- flake8:            4.0.1
	- flake8-2020:       1.6.1
	- flake8-absolute-import: 1.0.0.1
	- flake8-assertive:  1.3.0
	- flake8-bandit:     3.0.0
	- flake8-black:      0.3.6
	- flake8-bugbear:    21.4.3
	- flake8-builtins:   1.5.3
	- flake8-codeclimate: 0.3.0
	- flake8-cognitive-complexity: 0.1.0
	- flake8-comprehensions: 3.10.1
	- flake8-docstrings: 1.6.0
	- flake8-eradicate:  1.3.0
	- flake8-executable: 2.1.3
	- flake8-fixme:      1.1.1
	- flake8-gl-codeclimate: 0.1.6
	- flake8-isort:      4.2.0
	- flake8-mutable:    1.2.0
	- flake8-plugin-utils: 1.3.2
	- flake8-polyfill:   1.0.2
	- flake8-print:      4.0.1
	- flake8-pytest-style: 1.4.4
	- flake8-quotes:     3.2.0
	- flake8-requirements: 1.4.0
	- flake8-simplify:   0.14.6
	- flake8-tuple:      0.4.1
	- flake8-use-fstring: 1.4
	- flaky:             3.7.0
	- frozenlist:        1.3.3
	- fsspec:            2023.5.0
	- garlic:            0.13.7
	- gitdb:             4.0.10
	- gitpython:         3.1.31
	- google-auth:       2.18.0
	- google-auth-oauthlib: 1.0.0
	- graphql-core:      3.2.3
	- grpcio:            1.54.2
	- huggingface-hub:   0.14.1
	- humanfriendly:     10.0
	- hydra-core:        1.2.0
	- hypothesis:        6.10.1
	- identify:          2.5.24
	- idna:              3.4
	- importlib-metadata: 6.6.0
	- iniconfig:         2.0.0
	- intervaltree:      3.1.0
	- isort:             5.12.0
	- jaraco.classes:    3.2.3
	- jinja2:            3.1.2
	- jmespath:          1.0.1
	- jsonlines:         3.1.0
	- keyring:           23.13.1
	- kornia:            0.6.12
	- lightning-utilities: 0.8.0
	- makefun:           1.15.1
	- markdown:          3.4.3
	- markdown-it-py:    2.2.0
	- markupsafe:        2.1.2
	- marshmallow:       3.19.0
	- marshmallow-enum:  1.5.1
	- mccabe:            0.6.1
	- mdurl:             0.1.2
	- memray:            1.7.0
	- minio:             7.1.4
	- more-itertools:    8.14.0
	- mpmath:            1.3.0
	- multidict:         6.0.4
	- multimethod:       1.9.1
	- mypy:              0.982
	- mypy-extensions:   1.0.0
	- networkx:          3.1
	- nodeenv:           1.8.0
	- numpy:             1.24.3
	- oauthlib:          3.2.2
	- omegaconf:         2.2.3
	- packaging:         23.1
	- pandas:            2.0.1
	- pandas-vet:        0.2.3
	- pathspec:          0.11.1
	- pbr:               5.11.1
	- pep8-naming:       0.11.1
	- pillow:            9.5.0
	- pip:               23.0.1
	- pip-licenses:      3.5.5
	- pkginfo:           1.9.6
	- platformdirs:      3.5.1
	- pluggy:            1.0.0
	- portalocker:       2.7.0
	- pre-commit:        2.20.0
	- protobuf:          4.23.0
	- psutil:            5.9.5
	- ptable:            0.9.2
	- py:                1.11.0
	- pyasn1:            0.5.0
	- pyasn1-modules:    0.3.0
	- pycodestyle:       2.8.0
	- pydeprecate:       0.3.2
	- pydocstyle:        6.3.0
	- pyflakes:          2.4.0
	- pygments:          2.15.1
	- pytest:            7.1.3
	- pytest-cases:      3.6.14
	- pytest-cov:        2.11.1
	- pytest-lazy-fixture: 0.6.3
	- pytest-xdist:      3.3.0
	- python-dateutil:   2.8.2
	- pytorch-lightning: 2.0.2
	- pytz:              2023.3
	- pyyaml:            6.0
	- readme-renderer:   37.3
	- regex:             2023.5.5
	- requests:          2.30.0
	- requests-oauthlib: 1.3.1
	- requests-toolbelt: 1.0.0
	- rfc3986:           2.0.0
	- rich:              13.3.5
	- rsa:               4.9
	- s3transfer:        0.6.1
	- schema-fragments:  0.10.1
	- scipy:             1.10.1
	- scspell3k:         2.2
	- sentencepiece:     0.1.99
	- setuptools:        66.0.0
	- sgqlc:             16.1
	- six:               1.16.0
	- smmap:             5.0.0
	- snowballstemmer:   2.2.0
	- sortedcontainers:  2.4.0
	- stevedore:         5.1.0
	- sympy:             1.12
	- tensorboard:       2.13.0
	- tensorboard-data-server: 0.7.0
	- textdistance:      4.2.0
	- tilt-lm:           1.4.0
	- tilt-model:        0.3.4
	- tokenizers:        0.12.1
	- toml:              0.10.2
	- tomli:             2.0.1
	- torch:             2.0.1
	- torchdata:         0.6.1
	- torchmetrics:      0.10.3
	- torchvision:       0.15.2
	- tqdm:              4.65.0
	- transformers:      4.19.4
	- twine:             3.4.2
	- typed-json-dataclass: 1.2.1
	- typeguard:         2.13.3
	- types-deprecated:  1.2.9.2
	- types-pyyaml:      6.0.12.9
	- typing-extensions: 4.5.0
	- typing-inspect:    0.8.0
	- tzdata:            2023.3
	- urllib3:           1.26.15
	- virtualenv:        20.23.0
	- webencodings:      0.5.1
	- werkzeug:          2.3.4
	- wheel:             0.38.4
	- wrapt:             1.15.0
	- yarl:              1.9.2
	- zipp:              3.15.0
* System:
	- OS:                Darwin
	- architecture:
		- 64bit
		-
	- processor:         arm
	- python:            3.10.11
	- release:           22.5.0
	- version:           Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000

</details>

### More info

The problem is in this line: https://github.com/Lightning-AI/lightning/blob/56377d9b1f8dc4ebfeeaf18b81ce712c434d79e7/src/lightning/pytorch/core/saving.py#L93

The problem is that the `state_dict` first element is now `_extra_state` (see https://github.com/pytorch/pytorch/blob/main/torch/nn/modules/module.py#L98) and the first element is used to get the device.

I might be completely wrong but why I don't get why the `map_location` is fetched from the `state_dict`. Shouldn't it be just the `map_location` argument provided by the caller?

cc @awaelchli @carmocca @justusschock @borda

**Comment by awaelchli** [comment]
The `Module.get_extra_state` and `Module.set_extra_state`  are not so well known, which is why I guess nobody has thought if it so far. But adding an extra condition for this is certainly possible. Contributions welcome!

**Comment by wjaskowski** [comment]
With pleasure but I need to understand one thing: why is the `storage` sent to the device of the `state_dict` https://github.com/Lightning-AI/lightning/blob/56377d9b1f8dc4ebfeeaf18b81ce712c434d79e7/src/lightning/pytorch/core/saving.py#L93-L95 

Why is the function argument (`map_location`) not used instead?
https://github.com/Lightning-AI/lightning/blob/56377d9b1f8dc4ebfeeaf18b81ce712c434d79e7/src/lightning/pytorch/core/saving.py#L52-L55

**Comment by carmocca** [comment]
@wjaskowski Because `Module.to(...)` only supports passing a `torch.device` whereas 
 `torch.load(map_location=...)` also supports functions and dictionaries. If you make the change you'll see the tests added in https://github.com/Lightning-AI/lightning/pull/17308 fail
