### ISSUE TITLE
Mounts item on Glossary page not formatted correctly

### ISSUE THREAD

**Issue by Felonious-Spellfire** [Lightning-AI/lightning#17698]
### 📚 Documentation

Go to the Glossary page: https://lightning.ai/docs/app/stable/glossary/

Scroll down to the Mounts entry on the page. The formatting is incorrect.

To fix the issue go to: https://github.com/Lightning-AI/lightning/blob/master/docs/source-app/glossary/index.rst

And change the Mounts entry from this:

.. displayitem::
   :header: Mounts
   :description: Mount Cloud Data
   :col_css: col-md-6
   :button_link: mount.html
   :height: 180

to this:

.. displayitem::
   :header: Mounts
   :description: Mount Cloud Data
   :col_css: col-md-12
   :button_link: mount.html
   :height: 100

cc @borda

**Comment by kaustubh-s1** [comment]
Hi, can I take this up of nobody's working on it.

**Comment by rhiga2** [comment]
Hi, is this being worked on? I can look at this issue

**Comment by Borda** [comment]
> Hi, is this being worked on? I can look at this issue

Sure, go ahead. Thank you
