### ISSUE TITLE
Broken link to Lightning App API page

### ISSUE THREAD

**Issue by Felonious-Spellfire** [Lightning-AI/lightning#17697]
### 📚 Documentation

On this page in the docs: https://lightning.ai/docs/app/stable/core_api/lightning_app/#lightning-app-api

the link to the Lightning App API, at the bottom of the page, throws a 404 when you click the link: https://lightning.ai/docs/app/stable/core_api/lightning_app/lightning_app.html

cc @borda

**Comment by YashPolu** [comment]
@awaelchli can I work on this? thank you

**Comment by Tribhuvan0** [comment]
Hi @Felonious-Spellfire, I want to work on it, can you please let me know how I can fix it. I tried to figure out it my own but couldn't get an idea

**Comment by Borda** [comment]
> I tried to figure out it my own but couldn't get an idea

could we find where is this link referred to in the source code?
or what would be the best replacement for this expected page?

**Comment by cverrier** [comment]
> could we find where is this link referred to in the source code?

The link seems to be referred [in this `.rst` file](https://github.com/Lightning-AI/lightning/blob/4dfc09c2fe5cf4a66b6ec69e4189fe0ac2a92fb8/docs/source-app/core_api/lightning_app/index.rst?plain=1#L88). Hope it helps!

**Comment by VictorPrins** [comment]
Hi, I was about to start a PR fixing this, but I noticed there are a few more broken links on the Lightning Apps docs. I found these:

- The logo in the left top corner
- The "SERVE AND DEPLOY" example on the homepage (https://lightning.ai/docs/app/stable/)
- The "SCALE AND BUILD A PRODUCT" example on the homepage
- The link of this issue

Is Lightning Apps still being actively maintained? If so, I'll happily fix all of these. Thanks!

**Comment by Borda** [comment]
> Is Lightning Apps still being actively maintained? If so, I'll happily fix all of these. Thanks!

yes, so you help would be very welcome!

**Comment by VictorPrins** [comment]
It seems I'm not able to view the changes I made. The docs can't be built locally (#16158) and the CI docs preview only includes the Fabric and PyTorch docs (https://pytorch-lightning--18904.org.readthedocs.build/en/18904/). How should I proceed?

**Comment by Borda** [comment]
> CI docs preview only includes the Fabric and PyTorch docs

let me add also App
