### ISSUE TITLE
Argument `_ddp_params_and_buffers_to_ignore` is not properly propagated to `DistributedDataParallel`

### ISSUE THREAD

**Issue by cecabert** [Lightning-AI/lightning#17703]
### Bug description

When setting `LightningModule._ddp_params_and_buffers_to_ignore` to some values, the argument will not be properly propagated to the `DistributedDataParallel` class, therefore being ignored.

The issue lies in the constructor of the wrapping class: `_LightningModuleWrapperBase`. The lightning module gets assigned to `self._forward_module` whereas the DDP parameters' names to be ignored are mapped to `module.<original name>` instead of `_forward_module.<original name>` [#L76](https://github.com/Lightning-AI/lightning/blob/0cc458e237c19a725d57ed33b3abe90dd7a0d3a4/src/lightning/pytorch/overrides/base.py#L76)

### What version are you seeing the problem on?

master

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @justusschock @awaelchli

**Comment by awaelchli** [comment]
This will be solved with #17531 where the wrapper gets removed.
