### ISSUE TITLE
load and resume from checkpoint with deepspeed stage 2 

### ISSUE THREAD

**Issue by sachinya00** [Lightning-AI/lightning#17704]
### Bug description

After model training the model checkpoint is saved under checkpoint directory and contains below files. 
```
mp_rank_00_model_states.pt
zero_pp_rank_0_mp_rank_00_optim_states.pt
zero_pp_rank_1_mp_rank_00_optim_states.pt
zero_pp_rank_2_mp_rank_00_optim_states.pt
zero_pp_rank_3_mp_rank_00_optim_states.pt
```
To load the checkpoint using `load_from_checkpoint` I've added the below code to the **LightningModule** and able to load it successfully. 
```
    def on_load_checkpoint(self, checkpoint) -> None:
        """Fix the checkpoint loading issue for deepspeed."""
        if "state_dict" in checkpoint:
            return
        state_dict = checkpoint['module']
        state_dict = {k.partition('module.')[2]: state_dict[k] for k in state_dict.keys()}
        checkpoint['state_dict'] = state_dict
        return
```
However, when trying to `resume_from_checkpoint`, I'm getting below error. 
```
   results = self._run(model, ckpt_path=self.ckpt_path)
  File "/root/anaconda3/envs/pytorch_faiss/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1228, in _run
    self._restore_modules_and_callbacks(ckpt_path)
  File "/root/anaconda3/envs/pytorch_faiss/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1141, in _restore_modules_and_callbacks
    self._checkpoint_connector.restore_model()
  File "/root/anaconda3/envs/pytorch_faiss/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 171, in restore_model
    self.trainer._call_lightning_module_hook("on_load_checkpoint", self._loaded_checkpoint)
  File "/root/anaconda3/envs/pytorch_faiss/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1595, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/app/vectsearch/model/modules.py", line 260, in on_load_checkpoint
    state_dict = checkpoint['module']
KeyError: 'module'
```
More information on the keys present in the model_states file:
```dict_keys(['module', 'buffer_names', 'optimizer', 'param_shapes', 'frozen_param_shapes', 'frozen_param_fragments', 'lr_scheduler', 'data_sampler', 'random_ltd', 'sparse_tensor_module_names', 'skipped_steps', 'global_steps', 'global_samples', 'dp_world_size', 'mp_world_size', 'ds_config', 'ds_version', 'epoch', 'global_step', 'pytorch-lightning_version', 'loops', 'callbacks', 'lr_schedulers', 'hparams_name', 'hyper_parameters'])```

Keys in 4 optim_states:
```dict_keys(['buffer_names', 'param_shapes', 'frozen_param_shapes', 'frozen_param_fragments', 'lr_scheduler', 'global_samples', 'ds_config', 'ds_version', 'epoch', 'global_step', 'pytorch-lightning_version', 'loops', 'callbacks', 'lr_schedulers', 'hparams_name', 'hyper_parameters'])```

DeepSpeed config:
```  ds_config=DeepSpeedStrategy(stage=2, offload_optimizer=False, offload_parameters=False, logging_level=logging.INFO, load_full_weights=True)```

How to modify the code to load the checkpoint and also resume from it ?

### Environment

- PyTorch Lightning Version 1.6.5
- Torch 1.13.0
- Python version 3.8
- CUDA Version: 11.4
- 4 NVIDIA A100-SXM4-40GBs
- Deepspeed 0.9.1

cc @awaelchli

**Comment by leng-yue** [comment]
Seems like the checkpoint behavior is not proper on both deepspeed, sharded DDP, and FSDP.

**Comment by awaelchli** [comment]
Here is a bit more info:
https://lightning.ai/docs/pytorch/stable/advanced/model_parallel.html
Section: "Collating Single File Checkpoint for DeepSpeed ZeRO Stage 3"

This way, you can make the DeepSpeed checkpoint a single file and then load it with `Model.load_from_checkpoint`.

**Comment by paruul** [comment]
I am running into the same problem, while trying to restart my training. I am already using `trainer.fit`   but it still doesn't work. Here are some environment details:

deepspeed                 0.10.0                   pypi_0    pypi
pytorch-lightning         1.8.6                    pypi_0    pypi
Python 3.9.16

**Comment by chazo1994** [comment]
I wan

> @sachinya00 We've fixed several of these issues since Lightning 1.6.5 came out (already a year old). If you upgrade your version, you should be able to resume training with `trainer.fit(..., ckpt_path="path/to/deepspeed/checkpoint")` without problems. Note that loading sharded checkpoints like DeepSpeed ZerO via `Model.load_from_checkpoint` is not supported at all. The recommended way to do it is through the Trainer as I just pointed out.

I resume training from deepspeed sharded checkpoint with specifying ckpt_path to deepspeed checkpoint folder. However, this error was raised: "IsADirectoryError: [Errno 21] Is a directory:". Note that, I want to load both model weights and optimizer states.
