### ISSUE TITLE
Documentation clarification for best practices LightningDataModule

### ISSUE THREAD

**Issue by dsm-72** [Lightning-AI/lightning#17718]
### Description & Motivation

Please clarify the following:

1. Whether the expected methods `prepare_data` and `setup` should return self.

e.g.

```python
my_dm = MyDataModule(...).prepare_data().setup()
```

or

```python
my_dm = MyDataModule(...)
my_dm.prepare_data()
my_dm.setup()
```

2. How to best include a `collate_fn` if used in conjunction with `DataLoader` e.g.

```python
# inside MyDataModule(pl.LightningDataModule)

def train_dataloader(self):
    return DataLoader(..., collate_fn = self.collate_fn)


def collate_fn(self, batch):
    # create batch
    return X, y
```

### Pitch

Just clarify best practices

cc @borda

**Comment by awaelchli** [comment]
The DataModule is explained [here](https://lightning.ai/docs/pytorch/stable/data/datamodule.html#lightningdatamodule-api) and we show that prepare_data() and setup() are hooks. The user doesn't call them, therefore returning `self` wouldn't make sense. 

We show how a dataloader is used in the examples there. It should be clear that if you return a dataloader from the `*_dataloader` hooks, then you can of course also return one with a collate_fn defined. Feel free to specify the collate function any way you want. Probably in most cases it won't be a method though, but rather just a function. 

```py
def train_dataloader(self):
    return DataLoader(..., collate_fn=collate_fn)

def collate_fn(samples):
    return torch.stack(samples)

```
