### ISSUE TITLE
run_training_epoch takes longer with more epochs

### ISSUE THREAD

**Issue by nilsleh** [Lightning-AI/lightning#17725]
### Bug description

I have a LightningModule, DataModule and Trainer that I am using on a Regression Problem. I have observed that as epochs increase, the iterations/s on the tqdm bar decrease significantly by a factor of about 2-5. To look into this I used the SimpleProfiler and recorded run_training_epoch at each epoch inside on_train_epoch_end():

```
run_training_epoch = self.trainer.profiler.recorded_durations["run_training_epoch"][-1]
self.log("run_training_epoch", run_training_epoch)
```

![Screenshot from 2023-05-25 16-38-47](https://github.com/Lightning-AI/lightning/assets/35272119/a5c175b8-f833-4146-abb5-952dcd48a8b7)

The optimization step and update of a single batch seems to be fairly consistent, so I wondering what else would cause this since I would expect an epoch to take as long regardless of how far one is into training. 

### What version are you seeing the problem on?

v2.0

### How to reproduce the bug

```python
Google colab notebook: https://colab.research.google.com/drive/1TSbXBNKZGaEKcX102lM-SaLQw-R8Nc-O?usp=sharing
```

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @tchaton @borda

**Comment by stde** [comment]
The cause of the slowdown appears to be in the logging. Profiling the methods revealed that logger.save [here](https://github.com/Lightning-AI/lightning/blob/master/src/lightning/pytorch/trainer/connectors/logger_connector/logger_connector.py#L109)  called by `update_train_step_metrics` gets slower and slower.  I assume  this is because all logs are saved and not just the delta. If we are doing a lot of batch updates and the individual batch updates are fast in small models this takes up more and more time.

**Comment by carmocca** [comment]
The CSVLogger implementation could be updated to append new rows. The logic is at https://github.com/Lightning-AI/lightning/blob/master/src/lightning/fabric/loggers/csv_logs.py#L228-L231 if somebody wants to work on it

**Comment by JustinGoheen** [comment]
I can work this after quantization if nobody else takes it.

**Comment by awaelchli** [comment]
@JustinGoheen I only just now saw your comment sorry. We discussed internally that we want to prioritize it and so I took it up immediately.
