### ISSUE TITLE
Utility to let rank 0 do work while other ranks wait

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#17733]
### Description & Motivation

We often see this pattern, for example when downloading data on rank 0 only:

```py
if fabric.global_rank == 0:
    # download data on rank 0 only

fabric.barrier()  # all processes sync here
```

The barrier is important so processes don't fall out of sync, but it is easy to forget.

### Pitch

Provide a utility (function or method) context manager that combines both the rank check and the barrier:

```py
with fabric.rank_zero_only:
   # download data on rank 0 only

# all processes sync here
```
The barrier would simply reside in the `__exit__` of the context manager. A similar one could be for `node_zero_only`.

### Alternatives

Not do it. Leave the code as is. Con: Error prone if one forgets the barrier.

### Additional context

Motivated by workarounds like #17732

Full example based on the linked issue:

```py
import lightning as L
import torch; import torchvision as tv

fabric = L.Fabric()
fabric.launch()

model = tv.models.resnet18()
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)
model, optimizer = fabric.setup(model, optimizer)

with fabric.rank_zero_only:
    # download data
	tv.datasets.CIFAR10("data", download=True, train=True, transform=tv.transforms.ToTensor())

dataset = tv.datasets.CIFAR10("data", download=False, train=True, transform=tv.transforms.ToTensor())

dataloader = torch.utils.data.DataLoader(dataset, batch_size=8)
dataloader = fabric.setup_dataloaders(dataloader)

model.train()
num_epochs = 10
for epoch in range(num_epochs):
    for batch in dataloader:
        inputs, labels = batch
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = torch.nn.functional.cross_entropy(outputs, labels)
        fabric.backward(loss)
        optimizer.step()
        print(loss.data)
```

cc @borda @awaelchli @carmocca @justusschock

**Comment by carmocca** [comment]
Can you rewrite the example in #17732 using this utility? Assuming it existed

**Comment by awaelchli** [comment]
Yes sure, I think it would look like this. 


```py
import lightning as L
import torch; import torchvision as tv

fabric = L.Fabric()
fabric.launch()

model = tv.models.resnet18()
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)
model, optimizer = fabric.setup(model, optimizer)

with fabric.rank_zero_only:
    # download data
	tv.datasets.CIFAR10("data", download=True, train=True, transform=tv.transforms.ToTensor())

dataset = tv.datasets.CIFAR10("data", download=False, train=True, transform=tv.transforms.ToTensor())

dataloader = torch.utils.data.DataLoader(dataset, batch_size=8)
dataloader = fabric.setup_dataloaders(dataloader)

model.train()
num_epochs = 10
for epoch in range(num_epochs):
    for batch in dataloader:
        inputs, labels = batch
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = torch.nn.functional.cross_entropy(outputs, labels)
        fabric.backward(loss)
        optimizer.step()
        print(loss.data)
```

**Comment by carmocca** [comment]
Looks good!

The downloading dataset does not need `train=True, transform=...`.
And I wouldn't call it `rank_zero_only` because in Trainer that's a property. Unless it can double as a property and a context manager. 

I think this could be useful depending on the implementation of what's used. For instance, if `CIFAR10` was an expensive object to initialize, you'd want to add `if not fabric.rank_zero_only`

**Comment by awaelchli** [comment]
An alternative solution, that might even be more useful, is to just ensure that rank 0 enters the call first, completes it, and then the rest of the processes go through. This would avoid the need to duplicate the code. So I think I will refine my proposal to this:

```
with fabric.rank_0_first():
    # rank >0 will run this only once rank 0 has exited the context manager.
	tv.datasets.CIFAR10("data", download=True, train=True, transform=tv.transforms.ToTensor())
```

The implementation is pretty simple:

```py
def rank_zero_first():
    if rank > 0:
        barrier()
    yield
    if rank == 0:
        barrier()
    barrer()
```

**Comment by carmocca** [comment]
That won't work if you need to run different code per rank, for instance, if `download=True` always ran instead of checking that it has downloaded already then you'd need to modify the argument based on the rank.

**Comment by awaelchli** [comment]
The torchvision datasets don't download multiple times if the files already exist. The download=True is a bit misleading. So the example above would work using the 2nd method because rank 0 gets to download the files completely before any other process loads them.

**Comment by carmocca** [comment]
I know, my comment above was assuming this wasnt the case, as is for many naively implemented datasets or download scripts from the community
