### ISSUE TITLE
Fabric callback hooks and externally registered callbacks

### ISSUE THREAD

**Issue by lightningforever** [Lightning-AI/lightning#17755]
### Description & Motivation

It is currently not possible to observe the lifecycle of a Fabric training loop unless the user adds callback logic to their code. At the minimum, it requires to import the callback and make a call to `fabric.call`:

```py
from my_package import MonitorCallback

fabric = Fabric(callbacks=[MonitorCallback()]

...
optimizer.step()
fabric.call("on_after_optimizer_step")
```

The need to modify the code is a limitation compared to the Trainer, which 1) can load [callbacks configured from entry points](https://lightning.ai/docs/pytorch/stable/extensions/entry_points.html#entry-points) and 2) has the training loop encapsulated, so the user doesn't need to call hooks.

### Pitch

1. Add the ability to load callbacks from entry points the same way Trainer does it.
2. Offer Fabric-specific callback methods for

- before and after `Fabric.setup()` gets called
- before and after optimizer step gets called
- before and after backward gets called

These hooks get called automatically by Fabric if the user defines the methods:

```py
if callable(getattr(callback, "on_after_optimizer_step", None)):
    callback.on_after_optimizer_step()
```

This will enable external applications to observe state and lifecycle of a Fabric training loop. 

cc @borda @tchaton @justusschock @awaelchli @carmocca

**Comment by carmocca** [comment]
This is a very bundled-like solution to a problem that Fabric can already solve calling `fabric.call()` (as the top-post already showcases)

Hiding these callback calls from the user is not fabric-like but trainer-like. The user is meant to control the training loop.
This automation adds the foot-gun that if you run your Fabric code in an environment that has installed one of the packages that registers a `Callback` through entry-points, then your script is going to unknowingly run extra code that might make it fail or silently perform worse.

It also sets the precedent of hard-coding hook names throughout Fabric methods.

`on_after_optimizer_step` is a hook that doesn't exist in the base Callback interface. So it wouldn't even be useful for existing PL callbacks.

A different solution that doesn't require changing the loop could be to write a strategy wrapper that overrides `optimizer_step` for some other strategy. This would still require a manual opt-in in the Fabric `init`
