### ISSUE TITLE
Prediction Dataloader Conversion

### ISSUE THREAD

**Issue by YashwanthReddy27** [Lightning-AI/lightning#17769]
### Bug description

When i run the predict function of trainer it is loading the predict_dataloader automatically but it is not able to convert the input into the required format when i run validation func of trainer the val_dataloader is called automatically in this case its wroking properly in both i used the same dataset

### What version are you seeing the problem on?

v1.8

### How to reproduce the bug

```python
you have to write a fecth.py for fetching the datamodules
 data_module=fetch_data_module(config=config)
trainer.predict(model=module,datamodule=data_module,return_predictions=True, ckpt_path=str(ckpt_path))
```

### Error messages and logs

```
# Error messages and logs here please  File "/home/uif23257/miniconda3/envs/rvt/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/uif23257/miniconda3/envs/rvt/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
TypeError: conv2d() received an invalid combination of arguments - got (dict, Parameter, NoneType, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (dict, Parameter, NoneType, tuple of (int, int), tuple of (int, int), tuple of (int, int), int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (dict, Parameter, NoneType, tuple of (int, int), tuple of (int, int), tuple of (int, int), int)
```

### Environment

conda create -y -n rvt python=3.9 pip
conda activate rvt

### More info

<img width="958" alt="Screenshot 2023-06-07 104601" src="https://github.com/Lightning-AI/lightning/assets/120050286/b4daad58-26bb-4270-81d1-a3516ea8e54c">
<img width="958" alt="Screenshot 2023-06-07 121052" src="https://github.com/Lightning-AI/lightning/assets/120050286/35c77c0e-2576-437c-b885-04057e205e8a">

**Comment by awaelchli** [comment]
When you call `trainer.predict(model)`, it will call `model.predict_step()` and by default, if not implemented by the user, it just redirects to `model.forward()`. You will have to override `LightningModulel.predict_step`, the same way you would do for training step, to define how the input is fed to the model and the prediction generated.
