### ISSUE TITLE
About Dataloader

### ISSUE THREAD

**Issue by aiyb1314** [Lightning-AI/lightning#17772]
### Bug description

We don't have to use Dataloader when building modules

### What version are you seeing the problem on?

v2.0

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
Hi @aiyb1314 
You didn't provide any information about the problem you are facing. Or did you have a question? Please fill out the sections so we can help. Thanks!

**Comment by aiyb1314** [comment]
In pytorch lightning Trainer, you can use train_dataset instead of train_dataloader

**Comment by awaelchli** [comment]
Here is a simple example for what @justusschock explained. I believe this is what you were looking for? 

```py
import torch
from torch.utils.data import Dataset

from lightning.pytorch import LightningModule, Trainer


class MyDataset(Dataset):
    def __init__(self, batch_size, num_samples):
        self.data = [torch.rand(batch_size, 32) for _ in range(num_samples)]

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self) -> int:
        return len(self.data)


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        assert isinstance(batch, torch.Tensor)
        assert batch.shape == (6, 32)
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    batch_size = 6
    num_samples = 10
    train_data = MyDataset(batch_size, num_samples)

    model = BoringModel()
    trainer = Trainer(max_epochs=1)
    trainer.fit(model, train_data)


if __name__ == "__main__":
    run()

```

**Comment by aiyb1314** [comment]
My idea is that the batch data will change each time the batch data is read, that is, his dataset will change as the training process

**Comment by aiyb1314** [comment]
And how does the above approach invoke the test procedure

**Comment by aiyb1314** [comment]
Sorry, I may not have made my requirements clear. What I need is that the amount of data taken out is different each time, and it needs to be updated together with training. In other words, I adjust the amount of data required for training through training

**Comment by aiyb1314** [comment]
Can this be achieved?

**Comment by awaelchli** [comment]
> Sorry, I may not have made my requirements clear.

This makes it incredibly hard for us to help, and is very inefficient :( 
Let's give this one more attempt :) 

> What I need is that the amount of data taken out is different each time, and it needs to be updated together with training. In other words, I adjust the amount of data required for training through training

Yes this can be achieved. For example, you can define a LightningModule like this to assemble a new dataset every epoch and you can choose which data or how much you want (pseudo code):

```py

class MyModel(LightningModule):
    ...
    def train_dataloader(self):
        dataset = MyDataset(amount_of_data=get_amount_of_data(self.current_epoch))
        return DataLoader(dataset, batch_size=2)


def get_amount_of_data(epoch):
    # here determine how much or what type of data you want to use depending on the epoch
    pass

...
model = MyModel()
trainer = Trainer(
...
    # every epoch, call train_dataloader() to return a new dataloader
    reload_dataloaders_every_n_epochs=1,
)
trainer.fit(model)
```

If you need more implementation help, consider heading over to our forums: https://lightning.ai/forums/. If you have a feature request, please make sure to open a new issue and fill out all the required information.

**Comment by aiyb1314** [comment]
For each step, there is a function to reload the data.

**Comment by awaelchli** [comment]
Closing this now. If you have any further questions, let me know or post on the Lightning forum: https://lightning.ai/forums
