### ISSUE TITLE
LightningModule: predict_step has different signature than other steps

### ISSUE THREAD

**Issue by adamjstewart** [Lightning-AI/lightning#17786]
### Outline & Motivation

In the documentation, `(train|validation|test|predict)_step` all accept the same arguments. However, they have very different function signatures. This makes it confusing to subclass as I need to be careful about using different type signatures for each step. Some consistency would be nice.

### Pitch

All steps should be consistent. Either:
```python
def *_step(self, *args: Any, **kwargs: Any) -> Optional[STEP_OUTPUT]:
```
or:
```python
def *_step(self, batch: Any, batch_idx: int, dataloader_idx: int = 0) -> Any:
```
Personally I prefer the latter, as it makes it more clear what arguments will be passed and what types they can be.

cc @justusschock @awaelchli @carmocca @borda

**Comment by carmocca** [comment]
Good catch. Yes, the `predict_step` signature needs an update.

However, to be technically correct, it has to be `*args, **kwargs` because it supports the `def predict_step(dataloader_iter)` flavor.
