### ISSUE TITLE
There  are some wrongly used codes in your tutorials in your website. Maybe you could make me clear.

### ISSUE THREAD

**Issue by onbigion13** [Lightning-AI/lightning#17796]
### Bug description

Hey dudes. I found something hard understading in using the awesome Lightning. let say, there is a parameter named `MyNet`, which is a class inherited from `nn.Module`, in my class's constructor functoin. My classs, named `MyModule`, is inherited from `LightningModule`, When I save a ckpt of my object instantiated from `MyModule`, let's call it `model`. How can I only load the weights of `MyNet`? 

Well, the is an example in your website, [https://lightning.ai/docs/pytorch/stable/common/checkpointing_basic.html#lightningmodule-from-checkpoint](url),
In the  page, you raise an example usage of ckpt loading. 

```
class Encoder(nn.Module):
    ...


class Decoder(nn.Module):
    ...


class Autoencoder(pl.LightningModule):
    def __init__(self, encoder, decoder, *args, **kwargs):
        ...


autoencoder = Autoencoder(Encoder(), Decoder())
```

Then you taught a way to load ckpt of Encoder and Decoder,
```
checkpoint = torch.load(CKPT_PATH)
encoder_weights = checkpoint["encoder"]
decoder_weights = checkpoint["decoder"]
```

But how does  `checkpoint` contain the keys `"encoder"` and `"decoder"` ?  If we  print the keys of  `checkpoint`,  we can see that there are all the modules' `__name__` as keys of `checkpoint`. There is no way for us to load the weights of `Encoder` and `Decoder`,  Unless traverse the keys and stae_dicts in `checkpoint`  and truncate  the keys to mach he keys in `MyNet` 's state_dict. 

Right?

### What version are you seeing the problem on?

v2.0

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

### More info

Thank's for you  efforts to give researchers so awesome Pytorch Lightning!

cc @borda

**Comment by arijit-hub** [comment]
Hi @onbigion13 ,

I also agree with you that the tutorial is a bit misleading and needs fixing.

The documented tutorial doesn't work.

Anyhow, the current working version of this work is to use the method proposed here: https://github.com/Lightning-AI/lightning/issues/11494#issuecomment-1046378568

_Side Note_: 

Instead of using this (as suggested in the comment):
```{python}
prod_model.load_state_dict(lightning_checkpoint["state_dict"])
```

Use the following:

```{python}
prod_model.load_state_dict(lightning_checkpoint["state_dict"], strict = True)
```

I hope this helps whoever is trying to train a GAN or VAE model and is stuck with just using the Generator/Encoder part after training.

**Comment by onbigion13** [comment]
> Hi @onbigion13 ,
> 
> I also agree with you that the tutorial is a bit misleading and needs fixing.
> 
> The documented tutorial doesn't work.
> 
> Anyhow, the current working version of this work is to use the method proposed here: [#11494 (comment)](https://github.com/Lightning-AI/pytorch-lightning/issues/11494#issuecomment-1046378568)
> 
> _Side Note_:
> 
> Instead of using this (as suggested in the comment):
> 
> ```
> pred_model.load_state_dict(lightning_checkpoint["state_dict"])
> ```
> 
> Use the following:
> 
> ```
> pred_model.load_state_dict(lightning_checkpoint["state_dict"], strict = False)
> ```
> 
> I hope this helps whoever is trying to train a GAN or VAE model and is stuck with just using the Generator/Encoder part after training.

Thanks for your replying, feel sorry for late reply to you. I have gotten your advice. thanks again.

**Comment by Borda** [comment]
> I also agree with you that the tutorial is a bit misleading and needs fixing.

yes we plan to revisit them, would you be interested helping resolve issues?

**Comment by arijit-hub** [comment]
Hi @Borda ,

I think it is fixed in the  [new documentation](https://lightning.ai/docs/pytorch/stable/common/checkpointing_basic.html#nn-module-from-checkpoint), so nothing for me to fix :smile:.  

@onbigion13 no worries at all. I am happy you could fix your issue !

**Comment by onbigion13** [comment]
> Hi @Borda ,
> 
> I think it is fixed in the [new documentation](https://lightning.ai/docs/pytorch/stable/common/checkpointing_basic.html#nn-module-from-checkpoint), so nothing for me to fix 😄.
> 
> @onbigion13 no worries at all. I am happy you could fix your issue !

Thanks, you guys did a great job.
