### ISSUE TITLE
Simple checkpoint loading bug when providing extra state

### ISSUE THREAD

**Issue by joel99** [Lightning-AI/lightning#17809]
### Bug description

I recently started running into an issue loading checkpoints, snagging on the following line in 
> lightning/pytorch/core/saving.py(93)_load_from_checkpoint()

```
if issubclass(cls, pl.LightningModule):
 89             storage = _load_state(cls, checkpoint, strict=strict, **kwargs)
 90             state_dict = checkpoint["state_dict"]
 91             if not state_dict:
 92                 raise ValueError(f"The state dict in {checkpoint_path!r} contains no parameters.")
 93  ->         map_location = list(state_dict.values())[0].device
 94             assert isinstance(storage, pl.LightningModule)
 95             return storage.to(map_location)
```
The particular sampled item form the state dict was a piece of extra state metadata I was loading into the checkpoint with the `get_extra_state` and `set_extra_state` hooks. A workaround is to update this [0] index to [1].

### What version are you seeing the problem on?

v2.0

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @awaelchli

**Comment by awaelchli** [comment]
@joel99 Thanks for reporting. This is a duplicate issue of #17695, there is more info there if you are interested.
