### ISSUE TITLE
GAN.training_step() is not accepting optimizer_idx even though it is specified in the training_step

### ISSUE THREAD

**Issue by J-SUPHA** [Lightning-AI/lightning#17801]
### Bug description

The `training_step` method in my `GAN` model isn't receiving the `optimizer_idx` argument when there are multiple optimizers. This causes my training to fail. It seems that even when I define an optimizer_idx in my Training step it is not picking it up under the hood. I have tried toggling self.automatic_optimiziation but run into other problems. Do not understand what is going on here. If there any other information that you need please let me know

### What version are you seeing the problem on?

v2.0, master

### How to reproduce the bug

```python
### To Reproduce

I am using PyTorch Lightning v2.0.3 and my code is as follows:


import torch
from torch import nn
import torch.nn.functional as F
import pytorch_lightning as pl


class Discriminator(nn.Module):
    def __init__(self):
        super().__init__()
        # Simple CNN
        self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
        self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.conv2_drop = nn.Dropout2d()
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, 1)

    def forward(self, x):
        x = F.relu(F.max_pool2d(self.conv1(x), 2))
        x = F.relu(F.max_pool2d(self.conv2_drop(self.conv2(x)), 2))
        # Flatten the tensor so it can be fed into the FC layers
        x = x.view(-1, 320)
        x = F.relu(self.fc1(x))
        x = F.dropout(x, training=self.training)
        x = self.fc2(x)
        return torch.sigmoid(x)


class Generator(nn.Module):
    def __init__(self, latent_dim):
        super().__init__()
        self.lin1 = nn.Linear(latent_dim, 7*7*64)  # [n, 256, 7, 7]
        self.ct1 = nn.ConvTranspose2d(64, 32, 4, stride=2) # [n, 64, 16, 16]
        self.ct2 = nn.ConvTranspose2d(32, 16, 4, stride=2) # [n, 16, 34, 34]
        self.conv = nn.Conv2d(16, 1, kernel_size=7)  # [n, 1, 28, 28]

    def forward(self, x):
        # Pass latent space input into linear layer and reshape
        x = self.lin1(x)
        x = F.relu(x)
        x = x.view(-1, 64, 7, 7)
        x = self.ct1(x)
        x = F.relu(x)
        x = self.ct2(x)
        x = F.relu(x)
        return self.conv(x)


class GAN(pl.LightningModule):
    def __init__(self, latent_dim=100, lr=0.0002):
        super().__init__()
        self.save_hyperparameters()
        self.generator = Generator(latent_dim=self.hparams.latent_dim)
        self.discriminator = Discriminator()
        self.validation_z = torch.randn(6, self.hparams.latent_dim)
        self.automatic_optimization = False

    def forward(self, z):
        return self.generator(z)

    def adversarial_loss(self, y_hat, y):
        return F.binary_cross_entropy(y_hat, y)

    def training_step(self, batch, batch_idx, optimizer_idx):
        real_imgs, _ = batch
        z = torch.randn(real_imgs.size(0), self.hparams.latent_dim)
        z = z.type_as(real_imgs)

 
        if (optimizer_idx ==0):
           fake_imgs = self.generator(z) # I have tried self(z) as well
           y_hat = self.discriminator(fake_imgs)
            
            
           y = torch.ones(real_imgs.size(0),1)
           y = y.type_as(real_imgs)
           g_loss = self.adversarial_loss(y_hat, y)
            
           log_dict = {"g_loss":g_loss}
           return {"loss": g_loss, "progress_bar": log_dict, "log": log_dict}
        
        # train the discriminator max log(D(x)) + log(1-D(G(z)))
        if (optimizer_idx ==1):
            # how well can it label as real and how well can it label as fake
            y_hat_real = self.discriminator(real_imgs)
            y_real = torch.ones(real_imgs.size(0),1)
            y_real = y_real.type_as(real_imgs)
            
            real_loss = self.adversarial_loss(y_hat_real, y_real)
            
            y_hat_fake = self.discriminator(self(z).detach())
            
            y_fake = torch.zeros(real_imgs.size(0),1)
            y_fake = y_fake.type_as(real_imgs)
            
            fake_loss = self.adversarial_loss(y_hat_fake, y_fake)
            
            d_loss = (real_loss+ fake_loss) / 2
            log_dict = {"d_loss":d_loss}
            return {"loss": d_loss, "progress_bar": log_dict, "log": log_dict}
    
    def configure_optimizers(self):
        lr = self.hparams.lr
        opt_g = torch.optim.Adam(self.generator.parameters(), lr=self.hparams.lr)
        opt_d = torch.optim.Adam(self.discriminator.parameters(), lr=self.hparams.lr)
        return [opt_g, opt_d],[] # empty list for schedulers
    
    def plot_imgs(self):
        z = self.validation_z.type_as(self.generator.lin1.weight)
        sample_imgs = self(z).cpu()
        print('epoch', self.current_epoch)
        fig = plt.figure()
        for i in range(sample_imgs.size(0)):
            plt.subplot(2, 3, i+1)
            plt.tight_layout()
            plt.imshow(sample_imgs.detach()[i, 0,:,:], cmap='gray_r', interpolation='none')
            plt.title('Generated Data')
            plt.xticks([])
            plt.yticks([])
            plt.axis('off')
        plt.show()
        
            
    
    def on_epoch_end(self):
        self.plot_imgs();

dm = MNISTDataModule()
model = GAN()
trainer = pl.Trainer(max_epochs=20, accelerator="auto")
trainer.fit(model,dm)
```

### Error messages and logs

```
----> 1 trainer.fit(model,dm)

12 frames
[/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py](https://ai7misug2br-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230606-060135-RC00_538140384#) in fit(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    529         model = _maybe_unwrap_optimized(model)
    530         self.strategy._lightning_module = model
--> 531         call._call_and_handle_interrupt(
    532             self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    533         )

[/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/call.py](https://ai7misug2br-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230606-060135-RC00_538140384#) in _call_and_handle_interrupt(trainer, trainer_fn, *args, **kwargs)
     40         if trainer.strategy.launcher is not None:
     41             return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
---> 42         return trainer_fn(*args, **kwargs)
     43 
     44     except _TunerExitException:

[/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py](https://ai7misug2br-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230606-060135-RC00_538140384#) in _fit_impl(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    568             model_connected=self.lightning_module is not None,
    569         )
--> 570         self._run(model, ckpt_path=ckpt_path)
    571 
    572         assert self.state.stopped

[/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py](https://ai7misug2br-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230606-060135-RC00_538140384#) in _run(self, model, ckpt_path)
    973         # RUN THE TRAINER
    974         # ----------------------------
--> 975         results = self._run_stage()
    976 
    977         # ----------------------------

[/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py](https://ai7misug2br-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230606-060135-RC00_538140384#) in _run_stage(self)
   1016                 self._run_sanity_check()
   1017             with torch.autograd.set_detect_anomaly(self._detect_anomaly):
-> 1018                 self.fit_loop.run()
   1019             return None
   1020         raise RuntimeError(f"Unexpected state {self.state}")

[/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loops/fit_loop.py](https://ai7misug2br-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230606-060135-RC00_538140384#) in run(self)
    199             try:
    200                 self.on_advance_start()
--> 201                 self.advance()
    202                 self.on_advance_end()
    203                 self._restarting = False

[/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loops/fit_loop.py](https://ai7misug2br-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230606-060135-RC00_538140384#) in advance(self)
    352         self._data_fetcher.setup(combined_loader)
    353         with self.trainer.profiler.profile("run_training_epoch"):
--> 354             self.epoch_loop.run(self._data_fetcher)
    355 
    356     def on_advance_end(self) -> None:

[/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loops/training_epoch_loop.py](https://ai7misug2br-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230606-060135-RC00_538140384#) in run(self, data_fetcher)
    131         while not self.done:
    132             try:
--> 133                 self.advance(data_fetcher)
    134                 self.on_advance_end()
    135                 self._restarting = False

[/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loops/training_epoch_loop.py](https://ai7misug2br-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230606-060135-RC00_538140384#) in advance(self, data_fetcher)
    218                     batch_output = self.automatic_optimization.run(trainer.optimizers[0], kwargs)
    219                 else:
--> 220                     batch_output = self.manual_optimization.run(kwargs)
    221 
    222         self.batch_progress.increment_processed()

[/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loops/optimization/manual.py](https://ai7misug2br-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230606-060135-RC00_538140384#) in run(self, kwargs)
     88         self.on_run_start()
     89         with suppress(StopIteration):  # no loop to break at this level
---> 90             self.advance(kwargs)
     91         self._restarting = False
     92         return self.on_run_end()

[/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loops/optimization/manual.py](https://ai7misug2br-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230606-060135-RC00_538140384#) in advance(self, kwargs)
    107 
    108         # manually capture logged metrics
--> 109         training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
    110         del kwargs  # release the batch from memory
    111         self.trainer.strategy.post_training_step()

[/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/call.py](https://ai7misug2br-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230606-060135-RC00_538140384#) in _call_strategy_hook(trainer, hook_name, *args, **kwargs)
    285 
    286     with trainer.profiler.profile(f"[Strategy]{trainer.strategy.__class__.__name__}.{hook_name}"):
--> 287         output = fn(*args, **kwargs)
    288 
    289     # restore current_fx when nested context

[/usr/local/lib/python3.10/dist-packages/pytorch_lightning/strategies/strategy.py](https://ai7misug2br-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230606-060135-RC00_538140384#) in training_step(self, *args, **kwargs)
    365         with self.precision_plugin.train_step_context():
    366             assert isinstance(self.model, TrainingStep)
--> 367             return self.model.training_step(*args, **kwargs)
    368 
    369     def post_training_step(self) -> None:
### GAN.training_step() missing 1 required positional argument: 'optimizer_idx'
```

### Environment

<details>
  <summary>Current environment</summary>
<p>
* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           11.8
* Lightning:
	- torch:             2.0.1+cu118
	- torchaudio:        2.0.2+cu118
	- torchdata:         0.6.1
	- torchsummary:      1.5.1
	- torchtext:         0.15.2
	- torchvision:       0.15.2+cu118
* Packages:
	- absl-py:           1.4.0
	- alabaster:         0.7.13
	- albumentations:    1.2.1
	- altair:            4.2.2
	- anyio:             3.6.2
	- appdirs:           1.4.4
	- argon2-cffi:       21.3.0
	- argon2-cffi-bindings: 21.2.0
	- array-record:      0.2.0
	- arviz:             0.15.1
	- astropy:           5.2.2
	- astunparse:        1.6.3
	- attrs:             23.1.0
	- audioread:         3.0.0
	- autograd:          1.5
	- babel:             2.12.1
	- backcall:          0.2.0
	- beautifulsoup4:    4.11.2
	- bleach:            6.0.0
	- blis:              0.7.9
	- blosc2:            2.0.0
	- bokeh:             2.4.3
	- branca:            0.6.0
	- build:             0.10.0
	- cachecontrol:      0.12.11
	- cached-property:   1.5.2
	- cachetools:        5.3.0
	- catalogue:         2.0.8
	- certifi:           2022.12.7
	- cffi:              1.15.1
	- chardet:           4.0.0
	- charset-normalizer: 2.0.12
	- chex:              0.1.7
	- click:             8.1.3
	- cloudpickle:       2.2.1
	- cmake:             3.25.2
	- cmdstanpy:         1.1.0
	- colorcet:          3.0.1
	- colorlover:        0.3.0
	- community:         1.0.0b1
	- confection:        0.0.4
	- cons:              0.4.5
	- contextlib2:       0.6.0.post1
	- contourpy:         1.0.7
	- convertdate:       2.4.0
	- cryptography:      40.0.2
	- cufflinks:         0.17.3
	- cupy-cuda11x:      11.0.0
	- cvxopt:            1.3.0
	- cvxpy:             1.3.1
	- cycler:            0.11.0
	- cymem:             2.0.7
	- cython:            0.29.34
	- dask:              2022.12.1
	- datascience:       0.17.6
	- db-dtypes:         1.1.1
	- dbus-python:       1.2.16
	- debugpy:           1.6.6
	- decorator:         4.4.2
	- defusedxml:        0.7.1
	- distributed:       2022.12.1
	- dlib:              19.24.1
	- dm-tree:           0.1.8
	- docutils:          0.16
	- dopamine-rl:       4.0.6
	- duckdb:            0.7.1
	- earthengine-api:   0.1.350
	- easydict:          1.10
	- ecos:              2.0.12
	- editdistance:      0.6.2
	- en-core-web-sm:    3.5.0
	- entrypoints:       0.4
	- ephem:             4.1.4
	- et-xmlfile:        1.1.0
	- etils:             1.2.0
	- etuples:           0.3.8
	- exceptiongroup:    1.1.1
	- fastai:            2.7.12
	- fastcore:          1.5.29
	- fastdownload:      0.0.7
	- fastjsonschema:    2.16.3
	- fastprogress:      1.0.3
	- fastrlock:         0.8.1
	- filelock:          3.12.0
	- firebase-admin:    5.3.0
	- flask:             2.2.4
	- flatbuffers:       23.3.3
	- flax:              0.6.9
	- folium:            0.14.0
	- fonttools:         4.39.3
	- frozendict:        2.3.7
	- fsspec:            2023.4.0
	- future:            0.18.3
	- gast:              0.4.0
	- gdal:              3.3.2
	- gdown:             4.6.6
	- gensim:            4.3.1
	- geographiclib:     2.0
	- geopy:             2.3.0
	- gin-config:        0.5.0
	- glob2:             0.7
	- google:            2.0.3
	- google-api-core:   2.11.0
	- google-api-python-client: 2.84.0
	- google-auth:       2.17.3
	- google-auth-httplib2: 0.1.0
	- google-auth-oauthlib: 1.0.0
	- google-cloud-bigquery: 3.9.0
	- google-cloud-bigquery-storage: 2.19.1
	- google-cloud-core: 2.3.2
	- google-cloud-datastore: 2.15.1
	- google-cloud-firestore: 2.11.0
	- google-cloud-language: 2.9.1
	- google-cloud-storage: 2.8.0
	- google-cloud-translate: 3.11.1
	- google-colab:      1.0.0
	- google-crc32c:     1.5.0
	- google-pasta:      0.2.0
	- google-resumable-media: 2.5.0
	- googleapis-common-protos: 1.59.0
	- googledrivedownloader: 0.4
	- graphviz:          0.20.1
	- greenlet:          2.0.2
	- grpcio:            1.54.0
	- grpcio-status:     1.48.2
	- gspread:           3.4.2
	- gspread-dataframe: 3.0.8
	- gym:               0.25.2
	- gym-notices:       0.0.8
	- h5netcdf:          1.1.0
	- h5py:              3.8.0
	- holidays:          0.25
	- holoviews:         1.15.4
	- html5lib:          1.1
	- httpimport:        1.3.0
	- httplib2:          0.21.0
	- humanize:          4.6.0
	- hyperopt:          0.2.7
	- idna:              3.4
	- imageio:           2.25.1
	- imageio-ffmpeg:    0.4.8
	- imagesize:         1.4.1
	- imbalanced-learn:  0.10.1
	- imgaug:            0.4.0
	- importlib-resources: 5.12.0
	- imutils:           0.5.4
	- inflect:           6.0.4
	- iniconfig:         2.0.0
	- intel-openmp:      2023.1.0
	- ipykernel:         5.5.6
	- ipython:           7.34.0
	- ipython-genutils:  0.2.0
	- ipython-sql:       0.4.1
	- ipywidgets:        7.7.1
	- itsdangerous:      2.1.2
	- jax:               0.4.10
	- jaxlib:            0.4.10+cuda11.cudnn86
	- jieba:             0.42.1
	- jinja2:            3.1.2
	- joblib:            1.2.0
	- jsonpickle:        3.0.1
	- jsonschema:        4.3.3
	- jupyter-client:    6.1.12
	- jupyter-console:   6.1.0
	- jupyter-core:      5.3.0
	- jupyter-server:    1.24.0
	- jupyterlab-pygments: 0.2.2
	- jupyterlab-widgets: 3.0.7
	- kaggle:            1.5.13
	- keras:             2.12.0
	- kiwisolver:        1.4.4
	- korean-lunar-calendar: 0.3.1
	- langcodes:         3.3.0
	- lazy-loader:       0.2
	- libclang:          16.0.0
	- librosa:           0.10.0.post2
	- lightgbm:          3.3.5
	- lit:               16.0.5
	- llvmlite:          0.39.1
	- locket:            1.0.0
	- logical-unification: 0.4.5
	- lunarcalendar:     0.0.9
	- lxml:              4.9.2
	- markdown:          3.4.3
	- markdown-it-py:    2.2.0
	- markupsafe:        2.1.2
	- matplotlib:        3.7.1
	- matplotlib-inline: 0.1.6
	- matplotlib-venn:   0.11.9
	- mdurl:             0.1.2
	- minikanren:        1.0.3
	- missingno:         0.5.2
	- mistune:           0.8.4
	- mizani:            0.8.1
	- mkl:               2019.0
	- ml-dtypes:         0.1.0
	- mlxtend:           0.14.0
	- more-itertools:    9.1.0
	- moviepy:           1.0.3
	- mpmath:            1.3.0
	- msgpack:           1.0.5
	- multipledispatch:  0.6.0
	- multitasking:      0.0.11
	- murmurhash:        1.0.9
	- music21:           8.1.0
	- natsort:           8.3.1
	- nbclient:          0.7.4
	- nbconvert:         6.5.4
	- nbformat:          5.8.0
	- nest-asyncio:      1.5.6
	- networkx:          3.1
	- nibabel:           3.0.2
	- nltk:              3.8.1
	- notebook:          6.4.8
	- numba:             0.56.4
	- numexpr:           2.8.4
	- numpy:             1.22.4
	- oauth2client:      4.1.3
	- oauthlib:          3.2.2
	- opencv-contrib-python: 4.7.0.72
	- opencv-python:     4.7.0.72
	- opencv-python-headless: 4.7.0.72
	- openpyxl:          3.0.10
	- opt-einsum:        3.3.0
	- optax:             0.1.5
	- orbax-checkpoint:  0.2.1
	- osqp:              0.6.2.post8
	- packaging:         23.1
	- palettable:        3.3.3
	- pandas:            1.5.3
	- pandas-datareader: 0.10.0
	- pandas-gbq:        0.17.9
	- pandocfilters:     1.5.0
	- panel:             0.14.4
	- param:             1.13.0
	- parso:             0.8.3
	- partd:             1.4.0
	- pathlib:           1.0.1
	- pathy:             0.10.1
	- patsy:             0.5.3
	- pexpect:           4.8.0
	- pickleshare:       0.7.5
	- pillow:            8.4.0
	- pip:               23.1.2
	- pip-tools:         6.13.0
	- platformdirs:      3.3.0
	- plotly:            5.13.1
	- plotnine:          0.10.1
	- pluggy:            1.0.0
	- polars:            0.17.3
	- pooch:             1.6.0
	- portpicker:        1.3.9
	- prefetch-generator: 1.0.3
	- preshed:           3.0.8
	- prettytable:       0.7.2
	- proglog:           0.1.10
	- progressbar2:      4.2.0
	- prometheus-client: 0.16.0
	- promise:           2.3
	- prompt-toolkit:    3.0.38
	- prophet:           1.1.3
	- proto-plus:        1.22.2
	- protobuf:          3.20.3
	- psutil:            5.9.5
	- psycopg2:          2.9.6
	- ptyprocess:        0.7.0
	- py-cpuinfo:        9.0.0
	- py4j:              0.10.9.7
	- pyarrow:           9.0.0
	- pyasn1:            0.5.0
	- pyasn1-modules:    0.3.0
	- pycocotools:       2.0.6
	- pycparser:         2.21
	- pyct:              0.5.0
	- pydantic:          1.10.7
	- pydata-google-auth: 1.7.0
	- pydot:             1.4.2
	- pydot-ng:          2.0.0
	- pydotplus:         2.0.2
	- pydrive:           1.3.1
	- pyerfa:            2.0.0.3
	- pygame:            2.3.0
	- pygments:          2.14.0
	- pygobject:         3.36.0
	- pymc:              5.1.2
	- pymeeus:           0.5.12
	- pymystem3:         0.2.0
	- pyopengl:          3.1.6
	- pyparsing:         3.0.9
	- pyproject-hooks:   1.0.0
	- pyrsistent:        0.19.3
	- pysocks:           1.7.1
	- pytensor:          2.10.1
	- pytest:            7.2.2
	- python-apt:        0.0.0
	- python-dateutil:   2.8.2
	- python-louvain:    0.16
	- python-slugify:    8.0.1
	- python-utils:      3.5.2
	- pytz:              2022.7.1
	- pytz-deprecation-shim: 0.1.0.post0
	- pyviz-comms:       2.2.1
	- pywavelets:        1.4.1
	- pyyaml:            6.0
	- pyzmq:             23.2.1
	- qdldl:             0.1.7
	- qudida:            0.0.4
	- regex:             2022.10.31
	- requests:          2.27.1
	- requests-oauthlib: 1.3.1
	- requests-unixsocket: 0.2.0
	- requirements-parser: 0.5.0
	- rich:              13.3.4
	- rpy2:              3.5.5
	- rsa:               4.9
	- scikit-image:      0.19.3
	- scikit-learn:      1.2.2
	- scipy:             1.10.1
	- scs:               3.2.3
	- seaborn:           0.12.2
	- send2trash:        1.8.0
	- setuptools:        67.7.2
	- shapely:           2.0.1
	- six:               1.16.0
	- sklearn-pandas:    2.2.0
	- smart-open:        6.3.0
	- sniffio:           1.3.0
	- snowballstemmer:   2.2.0
	- sortedcontainers:  2.4.0
	- soundfile:         0.12.1
	- soupsieve:         2.4.1
	- soxr:              0.3.5
	- spacy:             3.5.2
	- spacy-legacy:      3.0.12
	- spacy-loggers:     1.0.4
	- sphinx:            3.5.4
	- sphinxcontrib-applehelp: 1.0.4
	- sphinxcontrib-devhelp: 1.0.2
	- sphinxcontrib-htmlhelp: 2.0.1
	- sphinxcontrib-jsmath: 1.0.1
	- sphinxcontrib-qthelp: 1.0.3
	- sphinxcontrib-serializinghtml: 1.1.5
	- sqlalchemy:        2.0.10
	- sqlparse:          0.4.4
	- srsly:             2.4.6
	- statsmodels:       0.13.5
	- sympy:             1.11.1
	- tables:            3.8.0
	- tabulate:          0.8.10
	- tblib:             1.7.0
	- tenacity:          8.2.2
	- tensorboard:       2.12.2
	- tensorboard-data-server: 0.7.0
	- tensorboard-plugin-wit: 1.8.1
	- tensorflow:        2.12.0
	- tensorflow-datasets: 4.9.2
	- tensorflow-estimator: 2.12.0
	- tensorflow-gcs-config: 2.12.0
	- tensorflow-hub:    0.13.0
	- tensorflow-io-gcs-filesystem: 0.32.0
	- tensorflow-metadata: 1.13.1
	- tensorflow-probability: 0.20.1
	- tensorstore:       0.1.36
	- termcolor:         2.3.0
	- terminado:         0.17.1
	- text-unidecode:    1.3
	- textblob:          0.17.1
	- tf-slim:           1.1.0
	- thinc:             8.1.9
	- threadpoolctl:     3.1.0
	- tifffile:          2023.4.12
	- tinycss2:          1.2.1
	- toml:              0.10.2
	- tomli:             2.0.1
	- toolz:             0.12.0
	- torch:             2.0.1+cu118
	- torchaudio:        2.0.2+cu118
	- torchdata:         0.6.1
	- torchsummary:      1.5.1
	- torchtext:         0.15.2
	- torchvision:       0.15.2+cu118
	- tornado:           6.3.1
	- tqdm:              4.65.0
	- traitlets:         5.7.1
	- triton:            2.0.0
	- tweepy:            4.13.0
	- typer:             0.7.0
	- types-setuptools:  67.8.0.0
	- typing-extensions: 4.5.0
	- tzdata:            2023.3
	- tzlocal:           4.3
	- uritemplate:       4.1.1
	- urllib3:           1.26.15
	- vega-datasets:     0.9.0
	- wasabi:            1.1.1
	- wcwidth:           0.2.6
	- webcolors:         1.13
	- webencodings:      0.5.1
	- websocket-client:  1.5.1
	- werkzeug:          2.3.0
	- wheel:             0.40.0
	- widgetsnbextension: 3.6.4
	- wordcloud:         1.8.2.2
	- wrapt:             1.14.1
	- xarray:            2022.12.0
	- xarray-einstats:   0.5.1
	- xgboost:           1.7.5
	- xlrd:              2.0.1
	- yellowbrick:       1.5
	- yfinance:          0.2.18
	- zict:              3.0.0
	- zipp:              3.15.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.10.12
	- release:           5.15.107+
	- version:           #1 SMP Sat Apr 29 09:15:28 UTC 2023

</p>

</details>

### More info

Training done on the MNIST data module

cc @borda

**Comment by awaelchli** [comment]
@J-SUPHA With the transition from Lightning 1.9 to 2.0, we changed how optimization works for multiple optimizers. From now on, multiple optimizers are only supported in manual optimization. You are half-way there, you already set `self.automatic_optimization=False`. Now, you need to remove the optimizer_idx argument from training step and get the optimizers using `opt1, opt2 = self.optimizers()`. 

We have a full GAN example with this in our repo: https://github.com/Lightning-AI/lightning/blob/2af57c702a039cbb86d38cd61718fa467b346329/examples/pytorch/domain_templates/generative_adversarial_net.py#L135

This should help you get it running 🎉

**Comment by J-SUPHA** [comment]
Thank you!
