### ISSUE TITLE
Backend "String", "auto" support with trainer for external plugins

### ISSUE THREAD

**Issue by jerome-habana** [Lightning-AI/lightning#17810]
### Bug description

String/auto support to trainer classes is missing for external plugins to support additional backends.

Eg: post installation of lightning-habana plugins, we cannot instantiate Trainer classes as shown next
Trainer(accelerator="hpu") or Trainer(accelerator="auto"). Only object based instantiation is possible as Trainer(accelerator=HPUAccelerator())

This needs to be resolved in the accelerator connector. Also, external plugins (strategies/accelerators) needs to be plumbed into the code wherever required.
Eg: the helper prints during training is misleading
"HPU available: True, using: 0 HPUs"

### What version are you seeing the problem on?

v2.0, master

### How to reproduce the bug

```python
#pip install lightning-habana lightning

from lightning.pytorch import Trainer
from lightning_habana.pytorch.accelerator import HPUAccelerator

def test_accelerator_selected():
    trainer = Trainer(accelerator=HPUAccelerator())
    assert isinstance(trainer.accelerator, HPUAccelerator)
```

### Error messages and logs

```
# Error messages and logs here please
```
E       assert False
E        +  where False = isinstance(<lightning.pytorch.accelerators.hpu.HPUAccelerator object at 0x7f1a83062fa0>, HPUAccelerator)
E        +    where <lightning.pytorch.accelerators.hpu.HPUAccelerator object at 0x7f1a83062fa0> = <lightning.pytorch.trainer.trainer.Trainer object at 0x7f1a83017fd0>.accelerator

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @jerome-habana

**Comment by jerome-habana** [comment]
@Borda @awaelchli - any updates to this ?

**Comment by awaelchli** [comment]
@jerome-habana These lines of code should already ensure that `Trainer(accelerator="hpu")` works:

https://github.com/Lightning-AI/lightning/blob/6eae2310d6dae086596e5bdddd08e8cd3884336e/src/lightning/pytorch/trainer/connectors/accelerator_connector.py#L701-L702

and

https://github.com/Lightning-AI/lightning/blob/6eae2310d6dae086596e5bdddd08e8cd3884336e/src/lightning/pytorch/trainer/connectors/accelerator_connector.py#L349-L350

and

https://github.com/Lightning-AI/lightning/blob/6eae2310d6dae086596e5bdddd08e8cd3884336e/src/lightning/pytorch/trainer/connectors/accelerator_connector.py#L424

This line of code supports `Trainer(accelerator="auto")` to select the HPU accelerator if available:

https://github.com/Lightning-AI/lightning/blob/6eae2310d6dae086596e5bdddd08e8cd3884336e/src/lightning/pytorch/trainer/connectors/accelerator_connector.py#L349-L350

I am not sure what would be left to do. Is something not working?

**Comment by jerome-habana** [comment]
> @jerome-habana These lines of code should already ensure that `Trainer(accelerator="hpu")` works:
> 
> https://github.com/Lightning-AI/lightning/blob/6eae2310d6dae086596e5bdddd08e8cd3884336e/src/lightning/pytorch/trainer/connectors/accelerator_connector.py#L701-L702
> 
> and
> 
> https://github.com/Lightning-AI/lightning/blob/6eae2310d6dae086596e5bdddd08e8cd3884336e/src/lightning/pytorch/trainer/connectors/accelerator_connector.py#L349-L350
> 
> and
> 
> https://github.com/Lightning-AI/lightning/blob/6eae2310d6dae086596e5bdddd08e8cd3884336e/src/lightning/pytorch/trainer/connectors/accelerator_connector.py#L424
> 
> This line of code supports `Trainer(accelerator="auto")` to select the HPU accelerator if available:
> 
> https://github.com/Lightning-AI/lightning/blob/6eae2310d6dae086596e5bdddd08e8cd3884336e/src/lightning/pytorch/trainer/connectors/accelerator_connector.py#L349-L350
> 
> I am not sure what would be left to do. Is something not working?

Thanks @awaelchli . The issue is due to the accelerator class being used for reference.
Strategies and accelerator are imported from lightning_habana, but post trainer initialization and acccelerator/strategy registration, the class instance changes.
lightning_habana.pytorch.accelerators.hpu.HPUAccelerator to lightning.pytorch.accelerators.hpu.HPUAccelerator
So do we ask users to check for the lightning instances always ?

**Comment by awaelchli** [comment]
It looks like there is an import issue. Here in this line:
https://github.com/Lightning-AI/lightning/blob/66293758c0192955148e8b4bd9dd156927c23503/src/lightning/pytorch/utilities/imports.py#L45

the value `_LIGHTNING_HABANA_AVAILABLE` will be false because `_try_import_module` will fail to import the module due to:

```
cannot import name 'LightningDataModule' from partially initialized module 'lightning.pytorch' (most likely due to a circular import)
```
So the circular import issue needs to be resolved for lightning to be able to import the module and make the `accelerator="hpu"` choice available. 
cc @Borda

**Comment by awaelchli** [comment]
The same issue as here: https://github.com/Lightning-AI/lightning/issues/17897
