### ISSUE TITLE
Is it possible to add TBPTT back?

### ISSUE THREAD

**Issue by 3zhang** [Lightning-AI/lightning#17848]
### Description & Motivation

I'm currently training a time series encoder-decoder model with ~600 input length. The training speed is painfully slow.

cc @borda

**Comment by awaelchli** [comment]
@3zhang 
Thanks for the request! This was a feature that wasn't used by many users and made the internals of the Trainer quite difficult to read, which is why we removed it. But it's actually not very hard to implement directly in the LightningModule. We discuss this in our release notes here: https://github.com/Lightning-AI/lightning/releases/tag/2.0.0 
Here is a sketch how you could implement it with manual optimization.


Before:
```py
import lightning as L

class LitModel(L.LightningModule):

    def __init__(self):
        super().__init__()
        self.truncated_bptt_steps = 10
        self.my_rnn = ...
        
    def training_step(self, batch, batch_idx, hiddens):
        ...
        loss, hiddens = self.my_rnn(..., hiddens)
        ...
        return loss, hiddens
```
Now:

```
import lightning as L

class LitModel(L.LightningModule):

    def __init__(self):
        super().__init__()
        
         # 1. Switch to manual optimization
        self.automatic_optimization = False
        
        self.truncated_bptt_steps = 10
        self.my_rnn = ...
        
    # 2. Remove the `hiddens` argument
    def training_step(self, batch, batch_idx):
        optimizer = self.optimizers()
        
        # 3. Split the batch in chunks along the time dimension
        split_batches = split_batch(batch, self.truncated_bptt_steps)
        
        hiddens = ...  # 3. Choose the initial hidden state
        for split_batch in range(split_batches):
            # 4. Perform the optimization in a loop
            loss, hiddens = self.my_rnn(split_batch, hiddens)
            self.backward(loss)
            optimizer.step()
            optimizer.zero_grad()
            
            # 5. "Truncate"
            hiddens = hiddens.detach()
        
        # 6. Remove the return of `hiddens`
        # Returning loss in manual optimization is not needed
        return None
```

Let me know your thoughts.

**Comment by 3zhang** [comment]
> ```python
> split_batch
> ```

What is the `split_batch` function?

**Comment by 3zhang** [comment]
> @3zhang Thanks for the request! This was a feature that wasn't used by many users and made the internals of the Trainer quite difficult to read, which is why we removed it. But it's actually not very hard to implement directly in the LightningModule. We discuss this in our release notes here: https://github.com/Lightning-AI/lightning/releases/tag/2.0.0 Here is a sketch how you could implement it with manual optimization.
> 
> Before:
> 
> ```python
> import lightning as L
> 
> class LitModel(L.LightningModule):
> 
>     def __init__(self):
>         super().__init__()
>         self.truncated_bptt_steps = 10
>         self.my_rnn = ...
>         
>     def training_step(self, batch, batch_idx, hiddens):
>         ...
>         loss, hiddens = self.my_rnn(..., hiddens)
>         ...
>         return loss, hiddens
> ```
> 
> Now:
> 
> ```python
> import lightning as L
> 
> class LitModel(L.LightningModule):
> 
>     def __init__(self):
>         super().__init__()
>         
>          # 1. Switch to manual optimization
>         self.automatic_optimization = False
>         
>         self.truncated_bptt_steps = 10
>         self.my_rnn = ...
>         
>     # 2. Remove the `hiddens` argument
>     def training_step(self, batch, batch_idx):
>         optimizer = self.optimizers()
>         
>         # 3. Split the batch in chunks along the time dimension
>         split_batches = split_batch(batch, self.truncated_bptt_steps)
>         
>         hiddens = ...  # 3. Choose the initial hidden state
>         for split_batch in range(split_batches):
>             # 4. Perform the optimization in a loop
>             loss, hiddens = self.my_rnn(split_batch, hiddens)
>             self.backward(loss)
>             optimizer.step()
>             optimizer.zero_grad()
>             
>             # 5. "Truncate"
>             hiddens = hiddens.detach()
>         
>         # 6. Remove the return of `hiddens`
>         # Returning loss in manual optimization is not needed
>         return None
> ```
> 
> Let me know your thoughts.

What is the `split_batch` function?

**Comment by awaelchli** [comment]
@3zhang This is just a placeholder for you to implement depending on how you have batched your data. For the truncated backpropagation, you take your samples and split them into chunks along the time dimension. Then each of these is fed as input to the RNN and backpropagation only happens over that chunk of the sequence. An example implementation of split_batch could be:

```py
def split_batch(batch, length):
    # Assuming your batch has dimensions (B, T, ...)
    return torch.split(batch, length, dim=1)
```

**Comment by awaelchli** [comment]
@3zhang Were you successful? Did the answers help?
