### ISSUE TITLE
No module named 'lightening' even after module shows as installed

### ISSUE THREAD

**Issue by dorienh** [Lightning-AI/lightning#17855]
### Bug description

I am on Python 3.10.12 environment (OS 13.x), this also occurred in a 3.10.9 venv. 

Clear jupyter notebook kernel: 

```
!pip3 install lightning
!pip3 list

```
shows: 

```
torch               2.0.1
torchmetrics        0.11.4
jupyter_core        5.3.1
lightning           2.0.3
lightning-cloud     0.5.36
lightning-utilities 0.8.0
```

Then I do: 

`import lightening as L`

(I am trying to avoid `pytorch_lightening` as this clashes with `pytorch-forecasting` module I want to use)

```
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[11], line 6
----> 6 import lightening as L

ModuleNotFoundError: No module named 'lightening'
```

I am a bit at a loss... Python 3.10 should be supported. The module lists as installed, but the import does not work. 

### What version are you seeing the problem on?

v2.0

**Comment by dorienh** [comment]
Well this in embarrassing. Lightening is spelled without -e lightning...  

`import lightning as L`

**Comment by lightningforever** [comment]
Hi @dorienh 
Did fixing the spelling error resolve your import issue?

**Comment by dorienh** [comment]
Yes.
