### ISSUE TITLE
Auto increment version for CSVLogger likeTensorBoardLogger in Fabric

### ISSUE THREAD

**Issue by dinhanhx** [Lightning-AI/lightning#17886]
### Description & Motivation

TensorBoardLogger auto increments next version, but CSVLogger doesn't, which I believe it's inconsistent.
```python
from lightning.fabric.loggers import TensorBoardLogger

logger = TensorBoardLogger("throw_away")
logger.log_metrics({"loss": 0.235, "acc": 0.75})
logger.finalize("success")
``` 
When running twice, it will create `version_0` then `version_1` folders.

However, 
```python
from lightning.fabric.loggers import CSVLogger

logger = CSVLogger("throw_away")
logger.log_metrics({"loss": 0.235, "acc": 0.75})
logger.finalize("success")
```

will give off the warning: /opt/conda/lib/python3.10/site-packages/lightning/fabric/loggers/csv_logs.py:186: UserWarning: Experiment logs directory throw_away/lightning_logs/version_0 exists and is not empty. Previous log files in this directory will be deleted when the new ones are saved!
  rank_zero_warn(

### Pitch

Given the following code, 
```python
from lightning.fabric.loggers import CSVLogger

logger = CSVLogger("throw_away")
logger.log_metrics({"loss": 0.235, "acc": 0.75})
logger.finalize("success")
```
When running this code twice (or again), the logger should create the next `version_{}` folder instead of warning.

cc @borda @carmocca @justusschock @awaelchli

**Comment by ManoBharathi93** [comment]
@dinhanhx  your pitch is also giving the same warnings when they run consecutive time. 

After viewing the Implementation of csvlogger. I understood it's warning message that indicates previous version will be deleted and new version will be saved in that same directory.

@Borda  what do you think this feature has to be work on ? If yes can I work on this feature  ?

**Comment by ManoBharathi93** [comment]
@dinhanhx 

<img width="866" alt="image" src="https://github.com/Lightning-AI/lightning/assets/88357044/1c4a49e9-eebc-4e8c-bafd-afedf2a406e6">

I have added this feature to my local repository and i will  give pull request.. If  maintainers accepts and merge soon you will get this feature  for you to use..

**Comment by awaelchli** [comment]
This is already working as described on master. I am not getting the warning and new folders get created when running this code multiple times. 

<img width="346" alt="image" src="https://github.com/Lightning-AI/lightning/assets/5495193/6c782aed-be05-444f-aaf5-e46340ec197e">

Could you please check by installing master? 
See this fix that was merged recently: https://github.com/Lightning-AI/lightning/pull/17139

**Comment by awaelchli** [comment]
This should have been fixed by https://github.com/Lightning-AI/lightning/pull/17139 but apparently the fix was not correct. I'll take a look.
