### ISSUE TITLE
TPU guide for Fabric

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#17973]
### 📚 Documentation

Write a full guide for running on TPUs with Fabric. 

- Installation 
- How to use the accelerator
- Launching processes
- Where to use mark_step()
- Potential pitfalls and how to avoid them (recompilation etc)
...

cc @borda @carmocca @JackCaoG @steventk-g @Liyang90

**Comment by carmocca** [comment]
@awaelchli #17492 exists

**Comment by awaelchli** [comment]
Okay that's great. Can I edit the issue to add these items there?

**Comment by carmocca** [comment]
Yes of course!
