### ISSUE TITLE
Using `load_from_checkpoint` to load a GPU checkpoint on a CPU-only machine 

### ISSUE THREAD

**Issue by marcimarc1** [Lightning-AI/lightning#17974]
### 📚 Documentation

Hi, 

I used `Model.load_from_checkpoint(path)` and received an error message `RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False.` (python 3.10 pl version 2.0.4)
A simple fix is to pass
`    model = Model.load_from_checkpoint(
        path,
        map_location=torch.device("cpu") if not torch.cuda.is_available() else None,
    )`
as a keyword argument to the function. 
This was trial and error, and my idea would be to include it into the docs. 
WDYT?

cc @borda @awaelchli

**Comment by awaelchli** [comment]
@marcimarc1 How about we automate this completely within the `load_from_checkpoint` function? If CPU is the only accelerator available, we simply set `map_location="cpu"`? I think this makes sense, then the user doesn't have to even think to go to the docs.

**Comment by marcimarc1** [comment]
Hi @awaelchli, 
Thanks for the quick response. 
I can dig into the code and make this feature available if it is wanted.

**Comment by awaelchli** [comment]
That would be very helpful yes. I suggest that internally in the load_from_checkpoint function, we simply set `map_location="cpu"` if we detect that `torch.cuda.device_count() = 0`. I'd be happy to review it if you send a PR.

**Comment by leng-yue** [comment]
Is there an API we can detect all accelerators available? When we are using ROCm or Mac, the device_count may be 0 while there are some other accelerators available.

**Comment by marcimarc1** [comment]
I observed it on my mac

**Comment by daturkel** [comment]
Sorry to comment on an old issue, but I'm finding I still need to manually set `map_location` in order to load a gpu checkpoint while on a CPU. Can you confirm what version of lightning this fix is available in?

**Comment by awaelchli** [comment]
The change landed in lightning 2.1+. Tip: You can see the version in which a commit/PR appeared if you click on the merged commit at the bottom and then look for the tag (2.1.0 in this case) near the commit message.

**Comment by daturkel** [comment]
<img width="799" alt="Screen Shot 2023-10-20 at 8 48 38 AM" src="https://github.com/Lightning-AI/lightning/assets/1828387/3a83ca89-a76f-4de3-a505-66408417aaa2">

@awaelchli I see now, thank you! And we're still on 2.0.x so that explains why this wasn't working yet.
