### ISSUE TITLE
CLI in lightning v2 does not correctly override keys in nested dictionaries

### ISSUE THREAD

**Issue by cristianregep** [Lightning-AI/lightning#18029]
### Summary
In pytorch_lightning 1.7.7 (with jsonargparse[signatures]==4.14.1) overriding arguments from the command line in nested dictionaries used to work, but in pytorch lightning 2.0.4 (jsonargparse[signatures,typing-extensions]==4.21.2) it doesn't anymore. What actually happens when overriding a nested key is that it writes it to the top level dictionary, but the key is constructed in such a way as to reflect the nesting.

The CLI may have not been actually supporting this behaviour explicitly, and I may have stumbled upon it by trial and error last year. If that is the case It would help if you could let me know what best practice would be.

### Example 

I have a model that takes as input a dictionary: 
```python
from pytorch_lightning.cli import LightningCLI
from pytorch_lightning import LightningModule

class MyModel(LightningModule):    
    def __init__(self, data: dict):
        super().__init__()
        self.data = data
        
cli = LightningCLI(model_class=MyModel, run=False, subclass_mode_model=True)
print(cli.config.model.init_args.data)
```
The config file  defines the data dictionary as being nested 

```python
model: 
  class_path: MyModel
  init_args:      
    data:      
      training_split:
        batch_size: 3
``` 

I ran the above with `python run.py -c config.yaml --model.init_args.data.training_split.batch_size 6` and I'm looking for what the print statement on the last line says:
- with pytorch_lightning 1.7.7 I get `{'training_split': {'batch_size': 6}}`
- with pytorch_lightning 2.0.4 I get `{'training_split': {'batch_size': 3}, 'training_split.batch_size': '6'}`

 

### What version are you seeing the problem on?

v2.0

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

* CUDA:
        - GPU:
                - NVIDIA A100-SXM4-80GB
                - NVIDIA A100-SXM4-80GB
                - NVIDIA A100-SXM4-80GB
                - NVIDIA A100-SXM4-80GB
                - NVIDIA A100-SXM4-80GB
                - NVIDIA A100-SXM4-80GB
                - NVIDIA A100-SXM4-80GB
                - NVIDIA A100-SXM4-80GB
        - available:         True
        - version:           11.7
* Lightning:
        - lightning-utilities: 0.9.0
        - pytorch-lightning: 2.0.4
        - torch:             2.0.1
        - torchmetrics:      1.0.0
* Packages:
        - aiohttp:           3.8.4
        - aiosignal:         1.3.1
        - async-timeout:     4.0.2
        - attrs:             23.1.0
        - certifi:           2023.5.7
        - charset-normalizer: 3.2.0
        - cmake:             3.26.4
        - docstring-parser:  0.15
        - filelock:          3.12.2
        - frozenlist:        1.3.3
        - fsspec:            2023.6.0
        - idna:              3.4
        - importlib-resources: 6.0.0
        - jinja2:            3.1.2
        - jsonargparse:      4.21.2
        - lightning-utilities: 0.9.0
        - lit:               16.0.6
        - markupsafe:        2.1.3
        - mpmath:            1.3.0
        - multidict:         6.0.4
        - networkx:          3.1
        - numpy:             1.25.1
        - nvidia-cublas-cu11: 11.10.3.66
        - nvidia-cuda-cupti-cu11: 11.7.101
        - nvidia-cuda-nvrtc-cu11: 11.7.99
        - nvidia-cuda-runtime-cu11: 11.7.99
        - nvidia-cudnn-cu11: 8.5.0.96
        - nvidia-cufft-cu11: 10.9.0.58
        - nvidia-curand-cu11: 10.2.10.91
        - nvidia-cusolver-cu11: 11.4.0.1
        - nvidia-cusparse-cu11: 11.7.4.91
        - nvidia-nccl-cu11:  2.14.3
        - nvidia-nvtx-cu11:  11.7.91
        - packaging:         23.1
        - pip:               23.1.2
        - pytorch-lightning: 2.0.4
        - pyyaml:            6.0
        - requests:          2.31.0
        - setuptools:        67.8.0
        - sympy:             1.12
        - torch:             2.0.1
        - torchmetrics:      1.0.0
        - tqdm:              4.65.0
        - triton:            2.0.0
        - typeshed-client:   2.3.0
        - typing-extensions: 4.7.1
        - urllib3:           2.0.3
        - wheel:             0.38.4
        - yarl:              1.9.2
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.10.12
        - release:           5.4.0-124-generic
        - version:           #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022

</details>

**Comment by cristianregep** [comment]
After reading this https://github.com/omni-us/jsonargparse/issues/236 in the jsonargparse I realise this is deliberate . Will rewrite with data classes

**Comment by awaelchli** [comment]
@cristianregep Should we close the issue after your findings, or is there something Lightning could improve here? Sorry that I couldn't reply earlier.

**Comment by cristianregep** [comment]
Thank you. I'll close it.
