### ISSUE TITLE
Don't re-instantiate the dataloader if the sampler is not changed to distributed sampler

### ISSUE THREAD

**Issue by function2-llx** [Lightning-AI/lightning#18106]
### Description & Motivation

I'm trying to use a custom batch sampler. 

### Pitch

As #18023 discusses, it will fail during the re-instantiation of the dataloader and batch sampler.

### Alternatives

When user provides a custom batch sampler, which is exclusive with the `sampler` argument of the data loader, they will probably take care of the distributed sampling over batches. It seems that the dataloader needs to be re-instantiated when the sampler is changed to the distributed sampler. 
https://github.com/Lightning-AI/lightning/blob/7116a9f9bb07193add28bcf15041764575fa5bab/src/lightning/fabric/fabric.py#L354-L359
Then I guess the line of `dataloader = _update_dataloader(dataloader, sampler)` can be put under the `if` clause to avoid the seemingly unnecessary re-instantiation of the dataloader and the potential exception.
If this solution is feasible, I'm willing to help open a PR.

cc @borda @carmocca @justusschock @awaelchli

**Comment by awaelchli** [comment]
@function2-llx Thank you for opening the ticket. 

The intention here was that the user would have to set `use_distributed_sampler=False` explicitly if they want to have a custom sampler. But even if set to False, we still re-instantiate the dataloader, which shouldn't be necessary. 

I think the logic should rather be this:

```py
# sampler = dataloader.sampler
if use_distributed_sampler and self._requires_distributed_sampler(dataloader):
    sampler = self._get_distributed_sampler(dataloader, **self._strategy.distributed_sampler_kwargs)

    # the dataloader needs to be re-instantiated because we want to update the input arguments (e.g., sampler)
    dataloader = _update_dataloader(dataloader, sampler)
```

Is this also what you were proposing?

**Comment by carmocca** [comment]
IIRC the dataloader needs to be reinstantiated anyways for other features like automatically setting `shuffle`. We have extensive tests about this behaviour so changing this should show what breaks with the failing tests.

**Comment by function2-llx** [comment]
@awaelchli Yes, this is exactly what I'm proposing. 

As for the concern mentioned by @carmocca , I've checked the code and here are my thoughts:

1. The re-instantiation of the dataloader is achieved by getting arguments for the constructor of the dataloader and calling the constructor:

https://github.com/Lightning-AI/lightning/blob/2af425328a64faac492d4c248b55d799668aa79c/src/lightning/fabric/utilities/data.py#L74-L76

2. In function `_get_dataloader_init_args_and_kwargs`, the `sampler` and `batch_sampler` arguments are updated here:

https://github.com/Lightning-AI/lightning/blob/2af425328a64faac492d4c248b55d799668aa79c/src/lightning/fabric/utilities/data.py#L130-L134

3. The job of function `_dataloader_init_kwargs_resolve_sampler` seems to re-instantiate the batch sampler from the dataloader if it exists, either by `__pl_saved_args` or the updated sampler passed in:

https://github.com/Lightning-AI/lightning/blob/2af425328a64faac492d4c248b55d799668aa79c/src/lightning/fabric/utilities/data.py#L173-L244

 Therefore, I feel that it's fine to skip the re-instantiation of the dataloader if the sampler is not changed. Please correct me if I made any mistake.
