### ISSUE TITLE
Calling self.save_hyperparameters in Constructor Preventing Training Start

### ISSUE THREAD

**Issue by arashno** [Lightning-AI/lightning#18103]
### Bug description

When utilizing self.save_hyperparameters inside the constructor of a module in the PyTorch Lightning library, the training process fails to start, and the training_step method is not invoked, causing the training to hang indefinitely. However, the configure_optimizer method is still being called.

If the line containing self.save_hyperparameters is commented out, the training runs without any problems.

PyTorch Lightning version: both 2.0.4 and 2.0.5
PyTorch version: 2.0.1+cu118
Python version: 3.9.13
Operating System: Rocky Linux 8

### What version are you seeing the problem on?

v2.0

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
@arashno Thanks for reporting. Would you mind sharing the code example? Make sure you're not saving large objects like entire models as hyperparameters. If you have a model as parameter, make sure to ignore it like so:

```py
def __init__(self, model, param1, param2):
    super().__init__()
    self.save_hyperparameters(ignore=["model"])
```

**Comment by arashno** [comment]
Ignoring the module fixed the issue. Thank you!
However, it was printing a message showing that it automatically ignores the model parameter which was not completely true.

**Comment by awaelchli** [comment]
Thank you for confirmin @arashno. You should have seen the following message:

> UserWarning: Attribute 'model2' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['model2'])`.

The warning here is just a suggestion, we don't do it automatically. Is this what you were seeing?
