### ISSUE TITLE
Adding Apple Silicon GPU Acceleration examples

### ISSUE THREAD

**Issue by NripeshN** [Lightning-AI/lightning#18133]
### Description & Motivation

We could add Apple silicon GPU support for the examples of lightning-AI.

### Pitch

Add MPS support for the examples.

### Additional context

Had Created a pull request https://github.com/Lightning-AI/lightning/pull/18127 for this.

cc @borda

**Comment by awaelchli** [comment]
Thanks @NripeshN for sending the PR 🎉
