### ISSUE TITLE
ImportError: cannot import name 'ProgressBarBase' from 'pytorch_lightning.callbacks.progress'

### ISSUE THREAD

**Issue by fu-hanghang** [Lightning-AI/lightning#18146]
### Bug description

Hello, when I try to train a model, I failed to import 'ProgressBarBase', the message shows below:
`Traceback (most recent call last):
  File "D:\LoFTR-master\train.py", line 8, in <module>
    import pytorch_lightning as pl
  File "C:\Users\Administrator\.conda\envs\patch\lib\site-packages\pytorch_lightning\__init__.py", line 21, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "C:\Users\Administrator\.conda\envs\patch\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 23, in <module>
    from pytorch_lightning.callbacks.progress import ProgressBar, ProgressBarBase
ImportError: cannot import name 'ProgressBarBase' from 'pytorch_lightning.callbacks.progress' (C:\Users\Administrator\.conda\envs\patch\lib\site-packages\pytorch_lightning\callbacks\progress\__init__.py)
`
I tried both update to the newest version and to 1.3.5 version,none of them works.
Which really confused me for a long time, please help me, tks.

### What version are you seeing the problem on?

v1.6, v2.0

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @borda

**Comment by awaelchli** [comment]
Hey @fu-hanghang 
The ProgressBarBase got renamed to ProgressBar in Lightning 2.0 #11908 

The correct import is:
```
from pytorch_lightning.callbacks.progress import ProgressBar 
```
