### ISSUE TITLE
When using the "Build your own Trainer" example for Fabric, memory randomly doubles with HF transformers setup.

### ISSUE THREAD

**Issue by ElleLeonne** [Lightning-AI/lightning#18166]
### Bug description

https://github.com/Lightning-AI/lightning/blob/master/examples/fabric/build_your_own_trainer/trainer.py

I believe there's a memory leak somewhere in the "build your own trainer" example.

I'm having a problem tracking this down. I'm using a transformers model that's been fairly customized, and Fabric to give me more control over the training loop than what HF allows, since they try to enforce strict input datatypes that I need to get away from longterm. I borrowed the example provided and set up my Lightning module and trainer.

Then, I init my transformer model and apply peft's 8-bit and LoRA transformations before constructing the lightning module

```
training_config = {
    "max_epochs": 100,
    "checkpoint_frequency": 5,
    "validation_frequency": 5,
    "plugins": Precision(), #To disable Lightning's automated precision
    "accelerator": "cpu" if torch.backends.mps.is_built() else "auto"}

lora_config = LoraConfig(**lora_config)
model = prepare_model_for_int8_training(model)
model = PeftModel(model, lora_config)
model = TrainingModule(**module_config)
```

And this works great! For about 35 batches (full training would require like 60k batches)
At that point, the model parameters randomly double and forces my GPU OOM.

I'm using a 4090 laptop GPU, and the base model takes up about 8.2gb, so doubling the memory just barely exceeds capacity.

`print(torch.cuda.memory_summary(device=None, abbreviated=False))`

Running cuda memory summary shows that the memory is allocated but not used by Pytorch.

![image](https://github.com/Lightning-AI/lightning/assets/87243032/912c98e4-b1d1-4beb-ba35-cb405ee9715f)

I'm just having trouble locating what's even happening. It SEEMS like the model is getting duplicated in memory, but the only callbacks I see in the basic loop are training start/stop and epoch start/stop. I'm not using gradient accumulation.

There's no reason _anything_ should be happening at a random step like 35.

```
class TrainingModule(L.LightningModule):
    def __init__(self, model, base_dataclass=None, length=1281167, learning_rate=3e-4, min_lr=1e-6, base_lora_config=None, processor=None):
        #We should probably shard off the optimizer information too at some point, this is clunky
        super().__init__()
        self.num_classes = model.config.num_classes
        self.model = model
        self.loss_fn = torch.nn.CrossEntropyLoss()
        self.base_dataclass = base_dataclass
        self.lr = learning_rate
        self.min_lr = min_lr
        self.length = length
        self.base_lora = base_lora_config
        self.processor = processor
        del model

    def forward(self, x: torch.Tensor):
        with torch.no_grad(): #Don't track preprocessing gradients
            x = x.squeeze(0)
            x = self.processor(x, self.base_dataclass) if self.processor is not None else x
        return self.model(x)

    def training_step(self, batch, batch_idx: int):
        x, y = batch
        dataclass = self(x)
        dataclass.logits = dataclass.logits.unsqueeze(0)
        loss = self.loss_fn(dataclass.logits, y)
        accuracy_train = accuracy(dataclass.logits.argmax(-1), y, num_classes=self.num_classes, task="multiclass", top_k=1)
        del dataclass
        #print(torch.cuda.memory_summary(device=None, abbreviated=False))
        return {"loss": loss, "accuracy": accuracy_train}

    def configure_optimizers(self):
        optim = torch.optim.Adam(self.parameters(), lr=1e-4)
        return optim, {"scheduler": ParabolicLRScheduler(optim, self.min_lr, self.lr, self.length),
                       "monitor": "val_accuracy",
                       "interval": "epoch",
                       "frequency": 1}
    
    def validation_step(self, *args, **kwargs):
        return self.training_step(*args, **kwargs)
```

I've made minor edits to the trainer, so maybe that's helpful. I'm going to see if I can't replicate this with a pretrained model so that I can upload an open-source version of the code for testing.

Fabric is EXACTLY what I was looking for. A great stepping stone between Huggingface and a fully proprietary system, just gotta figure out what's going wrong.

### What version are you seeing the problem on?

master

### How to reproduce the bug

```python
Use a huggingface model, with a LoRA adapter, and the example training script @ https://github.com/Lightning-AI/lightning/blob/master/examples/fabric/build_your_own_trainer/trainer.py
```

### Error messages and logs

```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 88.00 MiB. GPU 0 has a total capacty of 15.70 GiB of which 16.25 MiB is free. Including non-PyTorch memory, this process has 15.67 GiB memory in use. Of the allocated memory 13.74 GiB is allocated by PyTorch, and 1.62 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### Environment

<details>
  <summary>Current environment</summary>

```
* CUDA:
	- GPU:
		- NVIDIA GeForce RTX 4090 Laptop GPU
	- available:         True
	- version:           12.1
* Lightning:
	- lightning:         2.0.6
	- lightning-cloud:   0.5.37
	- lightning-utilities: 0.9.0
	- pytorch-lightning: 2.0.6
	- pytorch-triton:    2.1.0+9e3e10c5ed
	- torch:             2.1.0.dev20230721+cu121
	- torchaudio:        2.1.0.dev20230722+cu121
	- torchmetrics:      1.0.1
	- torchvision:       0.16.0.dev20230722+cu121
* Packages:
	- accelerate:        0.21.0
	- aiohttp:           3.8.5
	- aiosignal:         1.3.1
	- annotated-types:   0.5.0
	- anyio:             3.7.1
	- arrow:             1.2.3
	- async-timeout:     4.0.2
	- attrs:             23.1.0
	- backoff:           2.2.1
	- beautifulsoup4:    4.12.2
	- blessed:           1.20.0
	- certifi:           2022.12.7
	- charset-normalizer: 2.1.1
	- click:             8.1.6
	- croniter:          1.4.1
	- datasets:          2.14.0
	- dateutils:         0.6.12
	- deepdiff:          6.3.1
	- dill:              0.3.7
	- fastapi:           0.100.0
	- filelock:          3.9.0
	- frozenlist:        1.4.0
	- fsspec:            2023.4.0
	- h11:               0.14.0
	- huggingface-hub:   0.16.4
	- idna:              3.4
	- inquirer:          3.1.3
	- itsdangerous:      2.1.2
	- jinja2:            3.1.2
	- lightning:         2.0.6
	- lightning-cloud:   0.5.37
	- lightning-utilities: 0.9.0
	- markdown-it-py:    3.0.0
	- markupsafe:        2.1.2
	- mdurl:             0.1.2
	- minlora:           0.1.0
	- mpmath:            1.2.1
	- multidict:         6.0.4
	- multiprocess:      0.70.15
	- networkx:          3.0rc1
	- numpy:             1.24.1
	- ordered-set:       4.1.0
	- packaging:         23.1
	- pandas:            2.0.3
	- peft:              0.4.0
	- pillow:            9.3.0
	- pip:               23.1.2
	- psutil:            5.9.5
	- pyarrow:           12.0.1
	- pydantic:          2.0.3
	- pydantic-core:     2.3.0
	- pygments:          2.15.1
	- pyjwt:             2.8.0
	- python-dateutil:   2.8.2
	- python-editor:     1.0.4
	- python-multipart:  0.0.6
	- pytorch-lightning: 2.0.6
	- pytorch-triton:    2.1.0+9e3e10c5ed
	- pytz:              2023.3
	- pyyaml:            6.0.1
	- readchar:          4.0.5
	- regex:             2023.6.3
	- requests:          2.28.1
	- rich:              13.4.2
	- safetensors:       0.3.1
	- setuptools:        67.8.0
	- six:               1.16.0
	- sniffio:           1.3.0
	- soupsieve:         2.4.1
	- starlette:         0.27.0
	- starsessions:      1.3.0
	- sympy:             1.11.1
	- tokenizers:        0.13.3
	- torch:             2.1.0.dev20230721+cu121
	- torchaudio:        2.1.0.dev20230722+cu121
	- torchmetrics:      1.0.1
	- torchvision:       0.16.0.dev20230722+cu121
	- tqdm:              4.65.0
	- traitlets:         5.9.0
	- transformers:      4.31.0
	- typing-extensions: 4.7.1
	- tzdata:            2023.3
	- urllib3:           1.26.13
	- uvicorn:           0.23.1
	- wcwidth:           0.2.6
	- websocket-client:  1.6.1
	- websockets:        11.0.3
	- wheel:             0.38.4
	- xxhash:            3.2.0
	- yarl:              1.9.2
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.11.4
	- release:           6.2.0-26-generic
	- version:           #26-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 23:39:54 UTC 2023

#- Lightning Component: Fabric, LightningModule:
#- PyTorch Lightning Version 2.0.6:
#- PyTorch Version (e.g., 2.1.0):
#- Python version (e.g., 3.11.4):
#- OS (Linux):
#- CUDA/cuDNN version: 12.1
#- GPU models and configuration: RTX 4090 Laptop
#- How you installed Lightning: pip
#- Running environment of LightningApp (e.g. local, cloud): local
```

</details>

### More info

I've included everything else in the initial paragraphs. Thanks

cc @carmocca @justusschock @awaelchli @borda

**Comment by awaelchli** [comment]
Hi @ElleLeonne 
Thanks for opening the issue. 
I'll help debug this as much as I can. However, with only this description

> Use a huggingface model, with a LoRA adapter, and the example training script @ https://github.com/Lightning-AI/lightning/blob/master/examples/fabric/build_your_own_trainer/trainer.py

I think it would take me a bit too long and I might not run into the same problem than you have. It would be perfect if you could share the full code, but fully I understand if it's not possible.

Since you describe a random memory duplication at an arbitrary step, it could be difficult to find what's wrong. This is just a regular training step right? You're not transitioning from training stage to validation or vice versa at this step number?

> Fabric is EXACTLY what I was looking for. A great stepping stone between Huggingface and a fully proprietary system, just gotta figure out what's going wrong.

We're very happy to hear this! Glad you found the trainer template useful and I'd be interested to take a look at the modifications you made too.

**Comment by ElleLeonne** [comment]
Yes, it's just a random step, which is why it's so odd. I spent like twelve hours today trying to pinpoint the issue but failed.

Currently trying to overwrite HF's trainer to see if's my model somehow (even though that alone is just a refactor of one that was working before) so I guess I'll report back tomorrow.

**Comment by ElleLeonne** [comment]
Alright, still happening in HF's trainer, which though I understand is still built on top of Pytorch Lightning, probably means I need to pick over the tensor logic before considering a migration. Thanks for hearing me out regardless.
