### ISSUE TITLE
AttributeError: 'DDPStrategy' object has no attribute 'strategy_name'

### ISSUE THREAD

**Issue by zhiqiangdon** [Lightning-AI/lightning#18205]
### Bug description

For pytorch-lightning==2.0.6, `DDPStrategy` object has no attribute `strategy_name`, but other strategies like `SingleDeviceStrategy`, `FSDPStrategy` have attribute `strategy_name`.

### What version are you seeing the problem on?

v2.0

### How to reproduce the bug

```python
Install pytorch-lightning==2.0.6.

from pytorch_lightning.strategies import DDPStrategy, SingleDeviceStrategy, FSDPStrategy
s = SingleDeviceStrategy()
print(s.strategy_name) # works well.
s = FSDPStrategy()
print(s.strategy_name) # works well.
s = DDPStrategy("gpu")
print(s.strategy_name) # raises attribute error.
```

### Error messages and logs

```
AttributeError: 'DDPStrategy' object has no attribute 'strategy_name'
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @justusschock @awaelchli

**Comment by awaelchli** [comment]
Hi @zhiqiangdon 

Could you show me how you rely on this attribute in your code? What's the use case? The attribute is not defined on the base class, only on certain classes and we stopped relying on it in Lightning itself as it is legacy (we now have a different mechanism to assign the string name to a strategy). 

If you need to check whether your trainer is using a particular strategy type, the recommended way is:

```
if isinstance(trainer.strategy, DDPStrategy):
    # your code here
```

**Comment by zhiqiangdon** [comment]
Hi @awaelchli ,

Thanks for the quick response. I have switched to your suggested way (`if isinstance(trainer.strategy, DDPStrategy)`) in our codebase (https://github.com/autogluon/autogluon/pull/3419/files#diff-7f41a19ba5b4e0d17304cdd9a693ba5936d5e3d8c1cc455245a8bc9783ecacecR185). Basically, there are some strategy-specific logic in our code. BTW, I guess `DDPStrategy` is for both `ddp` and `ddp_spawn`. How do we know which strategy (`ddp` or `ddp_spawn`) is used given an initialized `trainer`?

**Comment by awaelchli** [comment]
@zhiqiangdon That's awesome, thanks a lot for making the upgrade 🥳 

Yes, DDPStrategy implements these two start methods. For a Trainer that runs on multiple devices, the default is
Lightning < 2.0: "ddp_spawn"
Lightning >=2.0: "ddp" unless in a Jupyter notebook, there it is "ddp_notebook".

Let me know if you have further questions about the upgrade. For reference, here are our release notes that describe the major user facing changes in detail: https://github.com/Lightning-AI/lightning/releases/tag/2.0.0#bc-changes

**Comment by zhiqiangdon** [comment]
Thanks!
