### ISSUE TITLE
`FileNotFoundError` when using latest Lightning and Neptune versions

### ISSUE THREAD

**Issue by ppries** [Lightning-AI/lightning#18224]
### Bug description

My team is experiencing the same problem across different projects: a `FileNotFoundError` when using `lightning==2.0.6` and `neptune==1.4.1`. It happens after a few epochs (even if we limit each epoch to 10 samples).

If I downgrade to `lightning=2.0.2` and `neptune-client==0.16.17` the exact same code works without any issues. (Uninstalling `neptune` first)

### What version are you seeing the problem on?

v2.0

### How to reproduce the bug

This is the closest I've been able to create a minimal example that reproduces the bug: https://github.com/ppries/lightning-neptune-bug

Running `train.py` from the linked repo in a Docker container built with the supplied Dockerfile on a G5 AWS EC2 instance triggers the error _most of the time_. 

### Error messages and logs

```
Traceback (most recent call last):
  File "lab/projects/jersey_number_detection/train.py", line 111, in main
    trainer.fit(lightning_model, datamodule=data_module)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/trainer.py", line 529, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/trainer.py", line 568, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/trainer.py", line 973, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/trainer.py", line 1016, in _run_stage
    self.fit_loop.run()
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/loops/fit_loop.py", line 202, in run
    self.on_advance_end()
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/loops/fit_loop.py", line 369, in on_advance_end
    call._call_callback_hooks(trainer, "on_train_epoch_end", monitoring_callbacks=True)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/call.py", line 193, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py", line 303, in on_train_epoch_end
    self._save_topk_checkpoint(trainer, monitor_candidates)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py", line 362, in _save_topk_checkpoint
    self._save_none_monitor_checkpoint(trainer, monitor_candidates)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py", line 671, in _save_none_monitor_checkpoint
    self._save_checkpoint(trainer, filepath)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py", line 372, in _save_checkpoint
    logger.after_save_checkpoint(proxy(self))
  File "/usr/local/lib/python3.8/dist-packages/lightning_utilities/core/rank_zero.py", line 32, in wrapped_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/loggers/neptune.py", line 507, in after_save_checkpoint
    self.run[f"{checkpoints_namespace}/{model_name}"] = File.from_stream(fp)
  File "/usr/local/lib/python3.8/dist-packages/neptune/metadata_containers/metadata_container.py", line 86, in inner_fun
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/neptune/metadata_containers/metadata_container.py", line 252, in __setitem__
    self.__getitem__(key).assign(value)
  File "/usr/local/lib/python3.8/dist-packages/neptune/handler.py", line 86, in inner_fun
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/neptune/handler.py", line 211, in assign
    self._container.define(self._path, value)
  File "/usr/local/lib/python3.8/dist-packages/neptune/metadata_containers/metadata_container.py", line 440, in define
    attr.process_assignment(neptune_value, wait=wait)
  File "/usr/local/lib/python3.8/dist-packages/neptune/attributes/attribute.py", line 66, in process_assignment
    return self.assign(value, wait=wait)
  File "/usr/local/lib/python3.8/dist-packages/neptune/attributes/atoms/file.py", line 30, in assign
    operation = UploadFile.of_file(
  File "/usr/local/lib/python3.8/dist-packages/neptune/internal/operation.py", line 206, in of_file
    value._save(operation_storage.upload_path / tmp_file_name)
  File "/usr/local/lib/python3.8/dist-packages/neptune/types/atoms/file.py", line 87, in _save
    self._file_composite.save(path)
  File "/usr/local/lib/python3.8/dist-packages/neptune/internal/types/file_types.py", line 127, in func
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/neptune/internal/types/file_types.py", line 158, in save
    with open(path, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/sunstone/.neptune/sync/run__3d7cc3a2-5ebb-47cb-8820-226edd303f41/exec-1691068691.477657-2023-08-03_13.18.11.477657/upload_path/model_checkpoints_epoch=0-step=1-1691069130.342012-2023-08-03_13.25.30.342012.bin'
```

### Environment

<details>
  <summary>Current environment</summary>

* CUDA:
        - GPU:
                - NVIDIA A10G
        - available:         True
        - version:           11.7
* Lightning:
        - lightning:         2.0.6
        - lightning-cloud:   0.5.37
        - lightning-utilities: 0.9.0
        - pytorch-lightning: 2.0.6
        - torch:             2.0.1
        - torchmetrics:      1.0.1
        - torchvision:       0.15.2
* Packages:
        - aiohttp:           3.8.5
        - aiosignal:         1.3.1
        - albumentations:    1.3.1
        - alembic:           1.11.1
        - annotated-types:   0.5.0
        - antlr4-python3-runtime: 4.9.3
        - anyio:             3.7.1
        - appdirs:           1.4.4
        - argon2-cffi:       21.3.0
        - argon2-cffi-bindings: 21.2.0
        - arrow:             1.2.3
        - asttokens:         2.2.1
        - async-lru:         2.0.3
        - async-timeout:     4.0.2
        - attrs:             23.1.0
        - awscli:            1.29.12
        - babel:             2.12.1
        - backcall:          0.2.0
        - backoff:           2.2.1
        - beautifulsoup4:    4.12.2
        - bleach:            6.0.0
        - blessed:           1.20.0
        - blinker:           1.6.2
        - boto3:             1.28.12
        - botocore:          1.31.12
        - bravado:           11.0.3
        - bravado-core:      6.1.0
        - certifi:           2023.5.7
        - cffi:              1.15.1
        - charset-normalizer: 3.1.0
        - click:             8.1.6
        - cloudpickle:       2.2.1
        - cmake:             3.26.3
        - colorama:          0.4.4
        - comm:              0.1.3
        - contourpy:         1.1.0
        - croniter:          1.4.1
        - cycler:            0.11.0
        - databricks-cli:    0.17.7
        - dateutils:         0.6.12
        - debugpy:           1.6.7
        - decorator:         5.1.1
        - deepdiff:          6.3.1
        - defusedxml:        0.7.1
        - docker:            6.1.3
        - docutils:          0.16
        - entrypoints:       0.4
        - exceptiongroup:    1.1.2
        - executing:         1.2.0
        - fastapi:           0.100.0
        - fastjsonschema:    2.18.0
        - filelock:          3.12.0
        - flask:             2.3.2
        - flatten-json:      0.1.13
        - fonttools:         4.41.1
        - fqdn:              1.5.1
        - frozenlist:        1.4.0
        - fsspec:            2023.6.0
        - future:            0.18.3
        - gitdb:             4.0.10
        - gitpython:         3.1.32
        - graphsurgeon:      0.4.5
        - greenlet:          2.0.2
        - gunicorn:          20.1.0
        - h11:               0.14.0
        - hydra-core:        1.3.2
        - idna:              3.4
        - imageio:           2.31.1
        - importlib-metadata: 6.8.0
        - importlib-resources: 6.0.0
        - inquirer:          3.1.3
        - ipykernel:         6.25.0
        - ipython:           8.12.2
        - isoduration:       20.11.0
        - itsdangerous:      2.1.2
        - jedi:              0.18.2
        - jinja2:            3.1.2
        - jmespath:          1.0.1
        - joblib:            1.3.1
        - json5:             0.9.14
        - jsonpointer:       2.4
        - jsonref:           1.1.0
        - jsonschema:        4.18.4
        - jsonschema-specifications: 2023.7.1
        - jupyter-client:    8.3.0
        - jupyter-core:      5.3.1
        - jupyter-events:    0.6.3
        - jupyter-lsp:       2.2.0
        - jupyter-server:    2.7.0
        - jupyter-server-terminals: 0.4.4
        - jupyterlab:        4.0.3
        - jupyterlab-pygments: 0.2.2
        - jupyterlab-server: 2.24.0
        - kiwisolver:        1.4.4
        - lazy-loader:       0.3
        - lightning:         2.0.6
        - lightning-cloud:   0.5.37
        - lightning-utilities: 0.9.0
        - lit:               16.0.5
        - mako:              1.2.0
        - markdown:          3.4.4
        - markdown-it-py:    3.0.0
        - markupsafe:        2.1.1
        - matplotlib:        3.7.2
        - matplotlib-inline: 0.1.6
        - mdurl:             0.1.2
        - mistune:           3.0.1
        - mlflow:            2.5.0
        - monotonic:         1.6
        - mpmath:            1.3.0
        - msgpack:           1.0.5
        - multidict:         6.0.4
        - nbclient:          0.8.0
        - nbconvert:         7.7.3
        - nbformat:          5.9.1
        - neptune:           1.4.0
        - nest-asyncio:      1.5.6
        - networkx:          3.1
        - notebook-shim:     0.2.3
        - numpy:             1.24.4
        - nvidia-cublas-cu11: 11.10.3.66
        - nvidia-cuda-cupti-cu11: 11.7.101
        - nvidia-cuda-nvrtc-cu11: 11.7.99
        - nvidia-cuda-runtime-cu11: 11.7.99
        - nvidia-cudnn-cu11: 8.5.0.96
        - nvidia-cufft-cu11: 10.9.0.58
        - nvidia-curand-cu11: 10.2.10.91
        - nvidia-cusolver-cu11: 11.4.0.1
        - nvidia-cusparse-cu11: 11.7.4.91
        - nvidia-nccl-cu11:  2.14.3
        - nvidia-nvtx-cu11:  11.7.91
        - oauthlib:          3.2.2
        - omegaconf:         2.3.0
        - onnx:              1.14.0
        - opencv-python-headless: 4.8.0.74
        - ordered-set:       4.1.0
        - overrides:         7.3.1
        - packaging:         23.1
        - pandas:            2.0.3
        - pandocfilters:     1.5.0
        - parso:             0.8.3
        - pexpect:           4.8.0
        - pickleshare:       0.7.5
        - pillow:            9.1.0
        - pip:               23.1.2
        - pkgutil-resolve-name: 1.3.10
        - platformdirs:      2.5.1
        - polygraphy:        0.36.2
        - prometheus-client: 0.17.1
        - prompt-toolkit:    3.0.39
        - protobuf:          4.23.4
        - psutil:            5.9.5
        - ptyprocess:        0.7.0
        - pure-eval:         0.2.2
        - pyarrow:           12.0.1
        - pyasn1:            0.5.0
        - pycparser:         2.21
        - pycuda:            2021.1
        - pydantic:          2.0.3
        - pydantic-core:     2.3.0
        - pygments:          2.15.1
        - pyjwt:             2.8.0
        - pyparsing:         3.0.9
        - python-dateutil:   2.8.2
        - python-editor:     1.0.4
        - python-json-logger: 2.0.7
        - python-multipart:  0.0.6
        - pytools:           2022.1.2
        - pytorch-lightning: 2.0.6
        - pytz:              2023.3
        - pywavelets:        1.4.1
        - pyyaml:            6.0.1
        - pyzmq:             25.1.0
        - qudida:            0.0.4
        - querystring-parser: 1.2.4
        - readchar:          4.0.5
        - referencing:       0.30.0
        - requests:          2.31.0
        - requests-oauthlib: 1.3.1
        - rfc3339-validator: 0.1.4
        - rfc3986-validator: 0.1.1
        - rfc3987:           1.3.8
        - rich:              13.4.2
        - rpds-py:           0.9.2
        - rsa:               4.7.2
        - s3transfer:        0.6.1
        - scikit-image:      0.21.0
        - scikit-learn:      1.3.0
        - scipy:             1.10.1
        - seaborn:           0.12.2
        - send2trash:        1.8.2
        - setuptools:        45.2.0
        - simplejson:        3.19.1
        - six:               1.16.0
        - smmap:             5.0.0
        - sniffio:           1.3.0
        - soupsieve:         2.4.1
        - sqlalchemy:        2.0.19
        - sqlparse:          0.4.4
        - stack-data:        0.6.2
        - starlette:         0.27.0
        - starsessions:      1.3.0
        - sunstone:          0.0.1
        - swagger-spec-validator: 3.0.3
        - sympy:             1.12
        - tabulate:          0.9.0
        - tensorrt:          8.2.4.2
        - terminado:         0.17.1
        - threadpoolctl:     3.2.0
        - tifffile:          2023.7.10
        - tinycss2:          1.2.1
        - tomli:             2.0.1
        - torch:             2.0.1
        - torchmetrics:      1.0.1
        - torchvision:       0.15.2
        - tornado:           6.3.2
        - tqdm:              4.65.0
        - traitlets:         5.9.0
        - triton:            2.0.0
        - typing-extensions: 4.7.1
        - tzdata:            2023.3
        - uff:               0.6.9
        - uri-template:      1.3.0
        - urllib3:           1.26.16
        - uvicorn:           0.23.1
        - wcwidth:           0.2.6
        - webcolors:         1.13
        - webencodings:      0.5.1
        - websocket-client:  1.6.1
        - websockets:        11.0.3
        - werkzeug:          2.3.6
        - wheel:             0.34.2
        - yarl:              1.9.2
        - zipp:              3.16.2
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                -
        - processor:         x86_64
        - python:            3.8.10
        - release:           5.15.0-1030-aws
        - version:           #34~20.04.1-Ubuntu SMP Tue Jan 24 15:16:46 UTC 2023

</details>

### More info

If possible and needed, I'm more than happy to contribute fixing this – but I have no idea where to begin right now.

cc @Blaizzy

**Comment by Blaizzy** [comment]
cc: @SiddhantSadangi
https://github.com/neptune-ai/neptune-client/issues/884#issuecomment-1621542173

**Comment by SiddhantSadangi** [comment]
@Raalsky is looking into this

**Comment by SiddhantSadangi** [comment]
We've just released a pre-release version of the client that should fix this: https://github.com/neptune-ai/neptune-client/releases/tag/1.5.0rc1

Could you please update your version of Neptune to `1.5.0rc1` and let us know if this works?
`pip install neptune==1.5.0rc1`

**Comment by ppries** [comment]
> We've just released a pre-release version of the client that should fix this: https://github.com/neptune-ai/neptune-client/releases/tag/1.5.0rc1
> 
> Could you please update your version of Neptune to `1.5.0rc1` and let us know if this works? `pip install neptune==1.5.0rc1`

Seems to work for the example repo 🙌 I will check it out in a real use-case tomorrow.

In the meanwhile, I'll close this issue as it doesn't seem to be related to Lightning.

Thanks for the help, @SiddhantSadangi!
