### ISSUE TITLE
How to print once rather not decided by number of used gpus

### ISSUE THREAD

**Issue by LogWell** [Lightning-AI/lightning#18232]
### Bug description

when I set
```
def train():
  print("check")
  
  trainer = pl.Trainer(
    ...
    devices=[0, 1, 2, 3],
    ...

if __name__ == '__main__':
    train()
```
and I found "check" will be printed 4 times.

### What version are you seeing the problem on?

v2.0

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
Hey @LogWell 

It can be done like this:
```py
trainer = pl.Trainer(devices=4)
if trainer.global_rank == 0:
    print("Only on main process")
```
Furthermore, in the LightningModule there is a [handy method](https://lightning.ai/docs/pytorch/stable/common/lightning_module.html#print) for printing too:
```py
# in a LightningModule
self.print("Only on main process")
```

In Lightning 2.1, there will be this convenient method as well.
```py
trainer.print("Only on main process")
```

We also have a forum if you have more questions like these 😃 
https://lightning.ai/forums/

**Comment by LogWell** [comment]
How do I modify it if I want to print before defining `trainer`?

**Comment by awaelchli** [comment]
@LogWell That wouldn't be possible, since the information of which process the print is carried out from is not available before the Trainer gets initialized. 

If for some reason it is critical for you to do this print before the trainer, you can consider setting trainer = `Trainer(strategy="ddp_spawn", devices=4)` which doesn't re-invoke the script.
