### ISSUE TITLE
Support loading checkpoints with empty `state_dict`

### ISSUE THREAD

**Issue by manipopopo** [Lightning-AI/lightning#18240]
### Description & Motivation

Currently loading checkpoints with empty `state_dict` will get `ValueError(f"The state dict in {checkpoint_path!r} contains no parameters.")`:

https://github.com/Lightning-AI/lightning/blob/c8062021dac9d47fde5cc50338c55c5dbb15e200/src/lightning/pytorch/core/saving.py#L98-L99

We may not need the check anymore since the `cpu` will be the device for the returned module when the `state_dict` is empty:

https://github.com/Lightning-AI/lightning/blob/c8062021dac9d47fde5cc50338c55c5dbb15e200/src/lightning/pytorch/core/saving.py#L98-L103

Could we remove the check above to allow loading checkpoints with empty `state_dict`?

### Pitch

Remove https://github.com/Lightning-AI/lightning/blob/c8062021dac9d47fde5cc50338c55c5dbb15e200/src/lightning/pytorch/core/saving.py#L98-L99 to allow loading checkpoints with empty `state_dict`.

cc @borda @awaelchli

**Comment by awaelchli** [comment]
@manipopopo Thanks for the request. Reading it just as it is, it doesn't make sense to me. What is the use case?

**Comment by manipopopo** [comment]
@awaelchli 

Our system can use some machine learning algorithms or rule-based algorithms that do not require any training (empty `state_dict`). We use `pl.LightningModule` to implement both kinds of algorithms. In the past, we could load checkpoints with empty `state_dict` using `pl.LightningModule.load_from_checkpoint`, but now we encounter errors with `pytorch_lightning` 2. The check that causes this error might have been used to determine the `device` from a `state_dict` that had at least one `Tensor`, but now it uses the `cpu` as the default `device` when there are no `Tensor`s in the `state_dict`. Can we still load checkpoints with empty `state_dict` like before (`pytorch_lightning` 1)?

**Comment by awaelchli** [comment]
It was introduced here not too long ago: #17308. I don't think it is strongly related to that PR, at least the device selection is independent. @ryan597 what do you think?

I see these options
a) Keep as is
b) Convert to warning
c) Remove the error

**Comment by ryan597** [comment]
Yeah I suppose if there is no state dict available then it could just return on the CPU as in that PR the state dict is just used to get the correct device for `map_location`. The error could be changed to a warning in that case.

**Comment by awaelchli** [comment]
Thanks for sending the PR so quickly.
