### ISSUE TITLE
Should the Trainer select all GPUs in a Jupyter environment?

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#18281]
### Discussion

The Trainer (and Fabric) support multi-GPU training in Jupyter notebooks, but with some tricky limitations. PyTorch does not officially support it and we have hacked around it with several tricks to make it work in certain cases. However, we've seen occasions where the user did everything right following [our recommendations](https://lightning.ai/docs/pytorch/latest/common/notebooks.html#multi-gpu-limitations) and we would still run into the infamous error

```
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```
or segmentation faults.

We check whether a bad cuda fork occurs
https://github.com/Lightning-AI/lightning/blob/b88b8b39370a54785599d7448afcd7f1596f462b/src/lightning/pytorch/strategies/launchers/multiprocessing.py#L99-L100

and print a friendly message to the user:

https://github.com/Lightning-AI/lightning/blob/b88b8b39370a54785599d7448afcd7f1596f462b/src/lightning/fabric/strategies/launchers/multiprocessing.py#L185-L189

But it seems that it is not robust enough (investigate?) and it is also quite hard to give good advice on it. 

**This poses the question of whether selecting all available GPUs is a good default in Jupyter notebooks.**

Proposal: `Trainer(devices="auto")` selects 1 GPU by default in Jupyter/interactive environment, even if multiple are available. A info message will inform the user that they can try `devices=8` but multi-GPU in Jupyter notebooks is considered experimental/unstable (your mileage may vary).

cc @borda @justusschock @awaelchli @carmocca

**Comment by carmocca** [comment]
If we can't or don't know how to investigate, then this could make sense.

Another non-breaking option is adding "If you aren't interested in using multiple devices, this error will disappear if you set `devices=1`" to the error message

**Comment by awaelchli** [comment]
To your point and also comment in https://github.com/Lightning-AI/lightning/pull/18291 I fear that a warning message would be easily overshadowed by the prompt and unhelpful error message we get  and can't control, for example the Segmentation faults (#18130) when a non-fork-friendly dataset is used for example.

I primarily worry about the onboarding experience of Lightning 2.0. Beginners or users who have adopted examples of Lightning in notebooks out there and install the latest version of Lightning will get these errors with a relatively high probability, since the requirements for getting ddp_notebook to work well are so narrow.

**Comment by justusschock** [comment]
Personally, I think we should do whatever "just works" as a default and since we know that multi-gpu can be tricky and error-prone in jupyter, I'd advocate to single GPU in this case as a default and raise a warning to inform the user.
