### ISSUE TITLE
lightning usage with bitsandbytes

### ISSUE THREAD

**Issue by mickeymickeymonkey** [Lightning-AI/lightning#18295]
### Description & Motivation

currently lightning allows training with fp16 and bf16/bf16-mixed. can these settings be used for training with bitandbytes' NF4 precision? 

### Pitch

if it's not possible to use lightning for NF4 finetuning, it would be nice to extend it to be able to allow using nf4 with Trainer. 

cc @borda @carmocca @justusschock @awaelchli

**Comment by carmocca** [comment]
Thanks for the suggestion. @JustinGoheen is looking into this

**Comment by JustinGoheen** [comment]
@carmocca I will open draft PR on this later today.
