### ISSUE TITLE
Checkpoints are not saved under specified directory

### ISSUE THREAD

**Issue by faizan1234567** [Lightning-AI/lightning#18313]
### Bug description

I am training a sentence classification model with Pytorch Lightning, however, it doesn't store checkpoints during training under a specified directory. When I check it after training it is empty. I am specifying checkpoints saving directories in a checkpoint callback function.

Secondly, I am using Early stopping callback with "valid/loss" as determining metric. But it doesn't recognize "valid/loss", however, it is mentioned in validation_step and logged. I don't what is wrong.

### What version are you seeing the problem on?

v1.6

### How to reproduce the bug

```python
@hydra.main(config_path = "./configs", config_name = "configs", version_base = None)
def main(cfg):
    logger.info(OmegaConf.to_yaml(cfg, resolve = True))
    logger.info(f"Using model: {cfg.model.name}")
    logger.info(f"using the tokenizer: {cfg.model.tokenizer}")
    # instantiate two instance like the dataset and model
    cola_dataset = Dataset(cfg.model.tokenizer, cfg.preprocess.batch, 
                           cfg.preprocess.max_length)
    cola_model = colaModel(cfg.model.name)

    root_dir = hydra.utils.get_original_cwd()

    # add model checkpoint and model early stoppoing callbacks
    checkpoint_callback = ModelCheckpoint(
        dirpath = f"{root_dir}/models", monitor = "valid/loss", mode = "min",
        filename = "best-checkpoint"
    )
    
    # to do: issue to resolve in early stopping callback
    early_stoppoing_callback = EarlyStopping(
        monitor = "valid/loss", patience = 3, verbose = True, mode = "min"
    )

    # adding wandb logger
    wandb_logger = WandbLogger(project = "MLOps - logging and experiment tracking",
                               entity = "engrfaizan-ai")
    

    # now create a trainer object
    trainer = pl.Trainer(
        logger = wandb_logger,
        max_epochs = cfg.training.max_epochs,
        log_every_n_steps = cfg.training.log_every_n_steps,
        deterministic = cfg.training.deterministic,
        callbacks = [checkpoint_callback, visualizationLogger(cola_dataset)],
        # limit_train_batches = cfg.training.limit_train_batches,
        # limit_val_batches = cfg.training.limit_val_batches
    ) 

    # start trainer
    trainer.fit(cola_model, cola_dataset)
    wandb.finish()



# ====================================================================
# model training code
'''
Author: Muhammad Faizan
-----------------------
python model.py
'''
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchmetrics
import wandb
import hydra
import numpy as np
import pandas as pd
import pytorch_lightning as pl
from transformers import AutoModelForSequenceClassification
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

class colaModel(pl.LightningModule):
    def __init__(self, model = "google/bert_uncased_L-2_H-128_A-2", lr = 3e-5):
        super(colaModel, self).__init__()
        self.lr = lr
        self.save_hyperparameters()

        self.num_classes = 2
        self.model = AutoModelForSequenceClassification.from_pretrained(model, num_labels= self.num_classes)
        # self.linear = nn.Linear(self.model.config.hidden_size, self.num_classes)
        

        self.train_accuracy_metric = torchmetrics.Accuracy(task = "binary")
        self.val_accuracy_metric = torchmetrics.Accuracy(task = "binary")
        self.f1_metric = torchmetrics.F1Score(num_classes = self.num_classes, task = "binary")
        self.precision_macro_metric = torchmetrics.Precision(
            average = "macro", num_classes = self.num_classes, task = "binary"
        )
        self.recall_macro_metric = torchmetrics.Recall(
            average = "macro", num_classes = self.num_classes, task = "binary"
        )

        self.precision_micro_metric = torchmetrics.Precision(average = "micro", task = "binary")
        self.recall_micro_metric = torchmetrics.Recall(average = "micro", task = "binary")
    
    def forward(self, input_ids, attention_mask, labels = None):
       outputs = self.model(input_ids = input_ids, attention_mask = attention_mask,
                       labels = labels)
       return outputs
    
    def training_step(self, batch, batch_index):

       outputs = self.forward(input_ids= batch["input_ids"], 
                              attention_mask= batch["attention_mask"],
                              labels= batch["label"])
       predictions = torch.argmax(outputs.logits, dim=1)
       train_acc = self.train_accuracy_metric(predictions, batch["label"])
       self.log("train/loss", outputs.loss, prog_bar = True, on_epoch = True)
       self.log("train/acc", train_acc, prog_bar = True, on_epoch = True)
       return outputs.loss 
    
    def validation_step(self, batch, batch_index):
        labels = batch["label"]
        outputs = self.forward(input_ids = batch["input_ids"],
                               attention_mask= batch["attention_mask"],
                               labels = labels)
        preds = torch.argmax(outputs.logits, 1)

        # calculate metrics
        valid_acc = self.val_accuracy_metric(preds, labels)
        precision_macro = self.precision_macro_metric(preds, labels)
        recall_macro = self.recall_macro_metric(preds, labels)
        precision_micro = self.precision_micro_metric(preds, labels)
        recall_micro = self.recall_micro_metric(preds, labels)
        f1 = self.f1_metric(preds, labels)

        # log all these metrics
        self.log("valid/loss", outputs.loss, prog_bar = True, on_step = True)
        self.log("valid/acc", valid_acc, prog_bar = True, on_epoch = True)
        self.log("valid/precision_macro", precision_macro, prog_bar = True, on_epoch = True)
        self.log("valid/recall_macro", recall_macro, prog_bar = True, on_epoch = True)
        self.log("valid/precision_micro", precision_micro , prog_bar = True, on_epoch = True)
        self.log("valid/recall_micro",recall_micro , prog_bar = True, on_epoch = True)
        self.log("valid/f1",f1 , prog_bar = True, on_epoch = True)
        return {"labels": labels, "logits": outputs.logits}
    
    def validation_epoch_end(self, outputs):
        
        labels = torch.cat([x["label"] for x in outputs])
        logits = torch.cat([x["logits"] for x in outputs])
        
        # plot confusino matrix on w&b
        self.logger.experiment.log(
            {
                "conf": wandb.plot.confusion_matrix(
            probs = logits.numpy(), y_true = labels.numpy()
                )
            }
        )
    
    def configure_optimizers(self):
        return torch.optim.Adam(self.model.parameters(), lr = self.hparams["lr"])
```

### Error messages and logs

```
RuntimeError: Early stopping conditioned on metric valid/loss which is not available. Pass in or modify your EarlyStopping callback to use any of the following: train/loss, train/loss_step, train/acc, train/acc_step, train/loss_epoch, `train/acc_epoch
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by ryan597** [comment]
Looks like your `EarlyStopping` callback is running before the validation step logs anything. Can you verify that the validation runs, maybe printing the `valid/loss` metric?

ps. in the code above early stopping is not in the callbacks in Trainer, so I'm assuming you edited it out by accident?

**Comment by faizan1234567** [comment]
Yes. I excluded it after it gave me an error. The problem is it works with the `Checkpoint` callback but it does not work with the `EarlyStopping`  callback. This is a strange issue. I will verify that

**Comment by faizan1234567** [comment]
@ryan597 I trained again for 2 epochs. I think the `validation_step` function doesn't run during training. This is the problem. I added a simple `print` function there but It does not print anything, which means this does not run. You can see the logs below:

`Epoch 0: 100%|████████████████████████████████████████████████████████████████████| 33/33 [06:36<00:00, 12.02s/it, loss=0.61, v_num=zj6j, train/loss_step=0.571, train/acc_step=0.750, train/loss_epoch=0.616, train/acc_epoch=0.699]C:\Users\faizan\anaconda3\envs\Mlops\lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py:378: UserWarning: `ModelCheckpoint(monitor='valid/loss')` could not find the monitored key in the returned metrics: ['train/loss', 'train/loss_step', 'train/acc', 'train/acc_step', 'train/loss_epoch', 'train/acc_epoch', 'epoch', 'step']. HINT: Did you call `log('valid/loss', value)` in the `LightningModule`?
  warning_cache.warn(m)
Epoch 1: 100%|███████████████████████████████████████████████████████████████████| 33/33 [12:40<00:00, 23.06s/it, loss=0.599, v_num=zj6j, train/loss_step=0.554, train/acc_step=0.766, train/loss_epoch=0.594, train/acc_epoch=0.717] 
wandb: Waiting for W&B process to finish... (success).`

**Comment by ryan597** [comment]
@faizan1234567 I just realized you haven't given it a validation dataset.

**Comment by faizan1234567** [comment]
Hi @ryan597, I am tried that but that gives me error.
`# start trainer
    cola_dataset.prepare()
    cola_dataset.setup()
    trainer.fit(cola_model, cola_dataset.train_dataloader(), cola_dataset.validation_dataloader())
    wandb.finish()`

and I modified dataset.py file as follow:

`import torch
import pytorch_lightning as pl

import datasets
from datasets import load_dataset
from transformers import AutoTokenizer

class Dataset(pl.LightningDataModule):
    def __init__(self, model = 'google/bert_uncased_L-2_H-128_A-2', batch_size = 32,
                 max_length = 128):
        super().__init__()
        self.batch_size = batch_size
        self.max_length = max_length
        self.tokenizer = AutoTokenizer.from_pretrained(model)
    
    # prepare dataset
    def prepare(self):
        cola_dataset = load_dataset('glue', 'cola')
        self.train_dataset = cola_dataset['train']
        self.validation_dataset = cola_dataset['validation']
        self.test_dataset = cola_dataset['test']

    # tokenize the text
    def tokenize(self, sample):
        return self.tokenizer(
            sample['sentence'],
            truncation = True, 
            padding = 'max_length',
            max_length = self.max_length)
    
    # process text and make read for loading...
    def setup(self, stage = None):
        if stage == "fit" or stage is None:
            self.train_dataset = self.train_dataset.map(self.tokenize, batched = True)
            self.train_dataset.set_format(type = "torch", 
                                        columns = ["input_ids", "attention_mask", "label"])
            
            self.validation_dataset = self.validation_dataset.map(self.tokenize, batched = True)
            self.validation_dataset.set_format(type = "torch", 
                                               columns = ["input_ids", "attention_mask", "label"],
                                               output_all_columns = True)
            
            self.test_dataset = self.test_dataset.map(self.tokenize, batched = True)
            self.test_dataset.set_format(type = "torch", 
                                         columns = ["input_ids", "attention_mask", "label"])
    # define training data loader       
    def train_dataloader(self):
        # set up the training dataset
        return torch.utils.data.DataLoader(self.train_dataset, batch_size = self.batch_size,
                                           shuffle = True, num_workers = 8)
    # define validation data loader
    def validation_dataloader(self):
        # set up the validation dataset 
        return torch.utils.data.DataLoader(self.validation_dataset, batch_size = self.batch_size,
                                           shuffle = False, num_workers = 8)
    
# to test run the script.
if __name__ == "__main__":
    # load the dataset
    dataset = Dataset()
    data = dataset.validation_dataloader()
    batch = next(iter(data))
    print(batch['input_ids'].shape, batch['label'].shape, batch['attention_mask'].shape)
    print(batch['input_ids'][0])
`

this is literally a headache tbh.

**Comment by faizan1234567** [comment]
Hi. fixed. updated validation_dataloader function name to val_dataloader. I didn't this small thing would give me a headache. Nobody could notice it lol
