### ISSUE TITLE
Inefficiency in Rich Progress bar

### ISSUE THREAD

**Issue by quintenroets** [Lightning-AI/lightning#18366]
### Description & Motivation

* The render method in lightning.pytorch.callbacks.progress.rich_progress.py (lines 170-172) currently uses string concatenation within a loop. 
* Given that the render method is called frequently, this inefficient approach can significantly impact performance.

```python
text = ""
for k, v in self._metrics.items():
    text += f"{k}: {round(v, 3) if isinstance(v, float) else v} "
return Text(text, justify="left", style=self._style)
```

### Pitch

I want to use the str.join method for creating the rendered text, as recommended by the Python documentation. 

Optionally, I would want to introduce the option for the user to see the metrics on separate lines. This could be achieved by using a different joining delimiter: e.g. "\n".join vs "".join.

### Additional context

* Python's string objects are immutable. Therefore, every string concatenation creates a new string object.
* Frequent string concatenations, especially inside loops, can lead to inefficiencies.
* [Python docs](https://docs.python.org/3/library/stdtypes.html#str): There is also no mutable string type, but [str.join()](https://docs.python.org/3/library/stdtypes.html#str.join) or [io.StringIO](https://docs.python.org/3/library/io.html#io.StringIO) can be used to efficiently construct strings from multiple fragments.

cc @borda

**Comment by Borda** [comment]
Sounds good to me; mind sending a PR with the proposed improvement?

**Comment by quintenroets** [comment]
> Sounds good to me; mind sending a PR with the proposed improvement?

Sure, I'm happy to work on it!

**Comment by quintenroets** [comment]
> Sounds good to me; mind sending a PR with the proposed improvement?

https://github.com/Lightning-AI/lightning/pull/18369

I created two commits:
1) Optimize the string joining
2) Make the delimiter configurable

I'm not sure if both commits belong in this PR, I would love to hear your thoughts on this.

**Comment by carmocca** [comment]
@quintenroets It would be better if you could keep those 2 changes separate, as the optimization could be considered a "fix".

Also, shouldn't the default delimiter be " " to be backwards compatible?

**Comment by quintenroets** [comment]
> @quintenroets It would be better if you could keep those 2 changes separate, as the optimization could be considered a "fix".
> 
> Also, shouldn't the default delimiter be `" "` to be backwards compatible?

Thank you for your feedback.
I will create two separate pull requests, both mentioning this issue.
You're right about the delimiter. Currently, each individual metric text ends with a blank space. It makes indeed more sense to  remove this space and move it to delimiter (make it " " by default)

**Comment by Borda** [comment]
you can keep this PR open with just one change and create a new PR with the other chnage
