### ISSUE TITLE
Fabric cannot launch with specified gpu indices

### ISSUE THREAD

**Issue by seraphzl** [Lightning-AI/lightning#18378]
### Bug description

Hi,

I launch fabric with specified gpu indices, and get RuntineError messges as follows.
How can I solve this issue? Thanks.

Software version:
```
deepspeed 0.10.0
lightning 2.0.7
pytorch 2.0.1
python 3.10.9
```

The code looks like:
```python
import lightning as L
fabric = L.Fabric(accelerator="cuda", devices="0,1,4,5", strategy='deepspeed')
fabric.launch()
```

The error messges and logs is:
```
[2023-08-24 07:56:20,780] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/home/xxx/test_fab.py", line 45, in <module>
    fabric.launch()
  File "/home/xxx/miniconda310/envs/ml/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 687, in launch
    return self._strategy.launcher.launch(function, *args, **kwargs)
  File "/home/xxx/miniconda310/envs/ml/lib/python3.10/site-packages/lightning/fabric/strategies/launchers/subprocess_script.py", line 92, in launch
    return function(*args, **kwargs)
  File "/home/xxx/miniconda310/envs/ml/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 776, in _run_with_setup
    self._strategy.setup_environment()
  File "/home/xxx/miniconda310/envs/ml/lib/python3.10/site-packages/lightning/fabric/strategies/ddp.py", line 113, in setup_environment
    self._setup_distributed()
  File "/home/xxx/miniconda310/envs/ml/lib/python3.10/site-packages/lightning/fabric/strategies/deepspeed.py", line 579, in _setup_distributed
    _validate_device_index_selection(self.parallel_devices)
  File "/home/xxx/miniconda310/envs/ml/lib/python3.10/site-packages/lightning/fabric/strategies/deepspeed.py", line 821, in _validate_device_index_selection
    raise RuntimeError(
RuntimeError: The selected device indices [0, 1, 4, 5] don't match the local rank values of processes. If you need to select GPUs at a specific index, set the `CUDA_VISIBLE_DEVICES` environment variable instead. For example: `CUDA_VISIBLE_DEVICES=0,1,4,5`.
```

### What version are you seeing the problem on?

v2.0

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9): 
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @carmocca @justusschock @awaelchli

**Comment by awaelchli** [comment]
@seraphzl This is expected, and is not supported by DeepSpeed. The error comes directly from Fabric and is informing you about the limitation. In addition, it suggests how you can select the devices via the environment variable. If you read the error message carefully:

```
RuntimeError: The selected device indices [0, 1, 4, 5] don't match the local rank values of processes. If you need to select GPUs at a specific index, set the `CUDA_VISIBLE_DEVICES` environment variable instead. For example: `CUDA_VISIBLE_DEVICES=0,1,4,5`.
```

So basically you remove the setting for `devices` and launch with `CUDA_VISIBLE_DEVICES=0,1,4,5 python train.py`

**Comment by awaelchli** [comment]
@seraphzl I'm closing the issue but if you have any further questions, don't hesitate to ask.

**Comment by seraphzl** [comment]
> @seraphzl This is expected, and is not supported by DeepSpeed. The error comes directly from Fabric and is informing you about the limitation. In addition, it suggests how you can select the devices via the environment variable. If you read the error message carefully:
> 
> ```
> RuntimeError: The selected device indices [0, 1, 4, 5] don't match the local rank values of processes. If you need to select GPUs at a specific index, set the `CUDA_VISIBLE_DEVICES` environment variable instead. For example: `CUDA_VISIBLE_DEVICES=0,1,4,5`.
> ```
> 
> So basically you remove the setting for `devices=[0, 1, 4, 5]` and launch with `CUDA_VISIBLE_DEVICES=0,1,4,5 python train.py`. Please let me know if that works.

@awaelchli Using the CUDA_VISIBLE_DEVICES environment setting to launch the training works. Thank you for reply.
