### ISSUE TITLE
ModelCheckpoint has parameter `every_n_train_steps` not `every_n_training_steps`

### ISSUE THREAD

**Issue by matthewpurri** [Lightning-AI/lightning#18388]
### 📚 Documentation

Hi, 

I found a small issue in the docs related to an incorrectly referred to class input:

The first bullet point of this [section](https://pytorch-lightning.readthedocs.io/en/1.6.1/common/checkpointing.html#when) states "When using iterative training which doesn’t have an epoch, you can checkpoint at every N training steps by specifying every_n_training_steps=N.". However the [ModelCheckpoint](https://lightning.ai/docs/pytorch/stable/_modules/lightning/pytorch/callbacks/model_checkpoint.html#ModelCheckpoint) class does not have a `every_n_training_steps` parameter but a `every_n_train_steps`.

cc @borda @carmocca @awaelchli

**Comment by awaelchli** [comment]
@matthewpurri It is great that you spotted this. Are you interested in sending a fix for it?

**Comment by matthewpurri** [comment]
Yup, I'd be happy to. Will send a revision shortly.

**Comment by matthewpurri** [comment]
Oops, I just realized that I was looking at an outdated version of the docs (v1.6.1) and in the latest version the correct attribute is used ([updated docs](https://github.com/Lightning-AI/lightning/blob/master/docs/source-pytorch/common/checkpointing_intermediate.rst)). 

Sorry for the needless doc update

**Comment by awaelchli** [comment]
Alright then, everything is in order. 
Thanks a lot for checking anyway!
