### ISSUE TITLE
Cosmic Ray Observatories Data Public

### ISSUE THREAD

**Issue by anukriti0009** [Lightning-AI/lightning#18384]
### Description & Motivation

Hello I am working with the datasets of Cosmic ray air showers, atmospheric data to use collected oxygen molecules, lightning showers from FD detector at nights and to study and analyse mass composition for nuclear medicine from modules like Fe(iron),protons,electromagnetic showers etc to load them into my files for pytorch tensor neural networks to use them for my own astrophysica with PennyLane.ai for quantum algorithms applications to build upon quantum functions, nodes and circuits from PennyLane and other important quantum machine learning, quantum deep learning modules for most physics analysis and processes mostly insides black holes and nebulas with an ambition to program them for interstellar missions.

### Pitch

This is my proposed project with PennyLane.ai for training my own black hole astrophysics based quantum computer with an intention to detect cosmic ray showers,lightning and thunder showers with the data of cosmic ray observatory like Auger with which I am collaboration.To use the auger prime upgraded data for Florescence detector and surface detector based showers to apply them on my detection methods for missions of space especially to collect space modules from black holes and nebulas which are potential habitable zones to colonise the universal entities.my mission is to collaborate with pytorch to deploy my models and tensors to create,analyze,sparse matrix missions and to study 26 dimensional universe according to existing Standard Model and Supersymmetry theories.With their particles and super partners like gravitons,gravitinous,higgs,higginos etc. to verify dark matter models and to implement these particles for my detection methods and techniques.I would like to add these datasets to my python based library astrophysica. 

I would like to share the repository with you which I am developing daily and adding my methods to develop a fully functional Quantum aerospace technology capable of utilising Telekinesis,Teleportation,cryptogtaphy,security,runnig with cosmic fuel from stars once they exhaust them,
[((https://github.com/anukriti0009/pennylane/blob/master/MY%20ASTROPHYSICA%20MISSION%20FOR%20BLACK%20HOLE%20EXPLORATION%20AND%20INTERSTELLAR%20ACHIEVEMENTS.txt))]

### Alternatives

I have found a wonderful paper to support my ideas of 26 dimensional and beyond universe to create detection systems, collection systems, cosmic accelerator names as voltx which is a flying saucer related to the evolution of a human taking inspiration from the Darwin theory of Human Evolution and natural selection to pursue and taking superhumanity to its heights and testing scientific projects on cosmic bodies like magnetars, pulsars to study mergers, to main the mergers and energies of these entities, to fix the rotation of planets, to maintain the temperature for human evolution and making ageing comparable to oldest trees and turtles which lives upto 250 years with the help of this missions and to restore the previous generations taking help from extraterrestial life to meet our past, present and future.
[meijer2014.pdf](https://github.com/Lightning-AI/lightning/files/12429164/meijer2014.pdf)

### Additional context

I would love to use tensors,plugins,metrics and the functionalities pytorch has to offer including the wonderful lighting platform to showcase my models and our networks on my website which is on implementation stage.Also I would like to implement my space laws and international laws for verification with my library astrophysica.
**https://anukriti0009.wixsite.com/adamevelaw**

cc @borda

**Comment by awaelchli** [comment]
Hi @anukriti0009 

This project looks wonderful and also challenging. It is great that you see value in using PyTorch and Lightning to accelerate training on your data.

Our GitHub page here is meant for proposals of new features, reports of bugs and general maintenance of the project. For discussion of projects, use cases and applications of Lightning or PyTorch I recommend our community [Discord](https://discord.com/invite/MWAEvnC5fU) or the [forum](https://lightning.ai/forums). There you might find people who are interested in the same topics and can join your discussion. You'll find channels where you can introduce yourself and share your work. 

Thanks for your interest in Lightning!
