### ISSUE TITLE
Weights and Biases Logger for Fabric

### ISSUE THREAD

**Issue by JustinGoheen** [Lightning-AI/lightning#18397]
### Description & Motivation

Enable a WandbLogger for Fabric

An MLE from W&B is interested using a [WandbLogger in Lit-GPT](https://github.com/Lightning-AI/lit-gpt/issues/440#issue-1856800235). The logger can be implemented into Fabric's Loggers for use in such projects, rather than at the project level.

cc @borda @awaelchli @morganmcg1 @borisdayma @scottire @parambharat @carmocca @justusschock

**Comment by awaelchli** [comment]
@JustinGoheen this feature request already exists: #17885
I suggest to close this ticket.
