### ISSUE TITLE
Example on "how to have untrainable parameters in the pl.LightningModule with DDP" or "example showing multiple resnets inside a DDP pl.LightningModule"?

### ISSUE THREAD

**Issue by LightingMc** [Lightning-AI/lightning#18457]
### Bug description

I am trying to have an ensemble learning network with fixed pre-trained backbones that aren't trainable and whose extracted features are getting passed into another learnable model. All of this happens inside the pl.LightningModule. I am trying to train via DDP.

I am looking for examples on "how to have untrainable parameters in the pl.LightningModule with DDP" or "example showing multiple resents inside a DDP pl.LightningModule"?

### What version are you seeing the problem on?

v1.6, v2.0

### How to reproduce the bug

```python
I am looking for an example code.
```

### Error messages and logs

```
# Error messages and logs here please
```
RuntimeError: It looks like your LightningModule has parameters that were not used in producing the loss returned by training_step. If this is intentional, you must enable the detection of unused parameters in DDP, either by setting the string value `strategy='ddp_find_unused_parameters_true'` or by setting the flag in the strategy with `strategy=DDPStrategy(find_unused_parameters=True)`.
,

### Environment

<details>
  <summary>Current environment</summary>

* CUDA:
	- GPU:
		- NVIDIA RTX A6000
		- NVIDIA RTX A6000
		- NVIDIA RTX A6000
		- NVIDIA RTX A6000
		- NVIDIA RTX A6000
		- NVIDIA RTX A6000
		- NVIDIA RTX A6000
		- NVIDIA RTX A6000
	- available:         True
	- version:           11.6
* Lightning:
	- facenet-pytorch:   2.5.3
	- lightning-utilities: 0.9.0
	- pytorch-lightning: 2.0.2
	- torch:             1.13.1
	- torchaudio:        0.13.1
	- torchmetrics:      0.11.4
	- torchvision:       0.14.1
* Packages:
	- absl-py:           1.4.0
	- aiohttp:           3.8.5
	- aiosignal:         1.3.1
	- antlr4-python3-runtime: 4.9.3
	- appdirs:           1.4.4
	- astroid:           2.15.6
	- astunparse:        1.6.3
	- async-timeout:     4.0.2
	- attrs:             23.1.0
	- bottleneck:        1.3.5
	- brotlipy:          0.7.0
	- cachetools:        5.3.1
	- certifi:           2022.12.7
	- cffi:              1.15.1
	- charset-normalizer: 2.0.4
	- click:             8.1.6
	- cloudpickle:       2.0.0
	- continuum:         1.2.7
	- contourpy:         1.0.5
	- cryptography:      38.0.4
	- cycler:            0.11.0
	- cytoolz:           0.12.0
	- dask:              2022.7.0
	- datasets:          2.14.4
	- dill:              0.3.7
	- dlutils:           0.0.12
	- dm-tree:           0.1.8
	- docker-pycreds:    0.4.0
	- dodgy:             0.2.1
	- dominate:          2.7.0
	- einops:            0.6.1
	- exceptiongroup:    1.1.3
	- facenet-pytorch:   2.5.3
	- filelock:          3.12.2
	- flake8:            5.0.4
	- flake8-polyfill:   1.0.2
	- flit-core:         3.6.0
	- fonttools:         4.25.0
	- frozenlist:        1.4.0
	- fsspec:            2022.11.0
	- gast:              0.5.4
	- gitdb:             4.0.10
	- gitpython:         3.1.32
	- google-auth:       2.22.0
	- google-auth-oauthlib: 1.0.0
	- grpcio:            1.56.2
	- h5py:              3.9.0
	- huggingface-hub:   0.16.4
	- hydra-core:        1.3.2
	- idna:              3.4
	- imagecodecs:       2021.8.26
	- imagehash:         4.3.1
	- imageio:           2.26.0
	- iniconfig:         2.0.0
	- isort:             5.12.0
	- joblib:            1.1.1
	- kiwisolver:        1.4.4
	- lazy-object-proxy: 1.9.0
	- lightning-utilities: 0.9.0
	- locket:            1.0.0
	- markdown:          3.4.4
	- markupsafe:        2.1.3
	- matplotlib:        3.6.2
	- mccabe:            0.7.0
	- mkl-fft:           1.3.1
	- mkl-random:        1.2.2
	- mkl-service:       2.4.0
	- multidict:         6.0.4
	- multiprocess:      0.70.15
	- munkres:           1.1.4
	- mypy:              1.5.1
	- mypy-extensions:   1.0.0
	- networkx:          2.8.4
	- ninja:             1.11.1
	- numexpr:           2.8.4
	- numpy:             1.23.5
	- nvidia-dali-cuda110: 1.29.0
	- oauthlib:          3.2.2
	- omegaconf:         2.3.0
	- opencv-python:     4.7.0.68
	- packaging:         22.0
	- pandas:            1.5.2
	- partd:             1.2.0
	- pathtools:         0.1.2
	- pep8-naming:       0.10.0
	- pillow:            9.3.0
	- pip:               23.0.1
	- platformdirs:      3.10.0
	- pluggy:            1.3.0
	- ply:               3.11
	- pooch:             1.4.0
	- prospector:        1.10.2
	- protobuf:          4.23.4
	- psutil:            5.9.5
	- pyarrow:           13.0.0
	- pyasn1:            0.5.0
	- pyasn1-modules:    0.3.0
	- pycodestyle:       2.9.1
	- pycparser:         2.21
	- pydeprecate:       0.3.2
	- pydocstyle:        6.3.0
	- pyeer:             0.5.5
	- pyflakes:          2.5.0
	- pylint:            2.17.5
	- pylint-celery:     0.3
	- pylint-django:     2.5.3
	- pylint-flask:      0.6
	- pylint-plugin-utils: 0.7
	- pyopenssl:         22.0.0
	- pyparsing:         3.0.9
	- pyqt5-sip:         12.11.0
	- pysocks:           1.7.1
	- pytest:            7.4.0
	- pytest-mock:       3.11.1
	- python-dateutil:   2.8.2
	- pytorch-lightning: 2.0.2
	- pytz:              2022.7
	- pywavelets:        1.4.1
	- pyyaml:            6.0
	- requests:          2.28.1
	- requests-oauthlib: 1.3.1
	- requirements-detector: 1.2.2
	- rsa:               4.9
	- safetensors:       0.3.1
	- scikit-image:      0.19.3
	- scikit-learn:      1.2.1
	- scipy:             1.10.0
	- semver:            3.0.1
	- sentry-sdk:        1.29.2
	- setoptconf-tmp:    0.3.1
	- setproctitle:      1.3.2
	- setuptools:        65.6.3
	- sip:               6.6.2
	- six:               1.16.0
	- smmap:             5.0.0
	- snowballstemmer:   2.2.0
	- solo-learn:        1.0.6
	- tensorboard:       2.13.0
	- tensorboard-data-server: 0.7.1
	- threadpoolctl:     2.2.0
	- tifffile:          2021.7.2
	- timm:              0.9.2
	- toml:              0.10.2
	- tomli:             2.0.1
	- tomlkit:           0.12.1
	- toolz:             0.12.0
	- torch:             1.13.1
	- torchaudio:        0.13.1
	- torchmetrics:      0.11.4
	- torchvision:       0.14.1
	- tornado:           6.2
	- tqdm:              4.64.1
	- typing-extensions: 4.4.0
	- urllib3:           1.26.14
	- wandb:             0.15.9
	- werkzeug:          2.3.6
	- wheel:             0.37.1
	- wrapt:             1.15.0
	- xxhash:            3.3.0
	- yacs:              0.1.6
	- yarl:              1.9.2
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.10.9
	- release:           5.15.0-82-generic
	- version:           #91-Ubuntu SMP Mon Aug 14 14:14:14 UTC 2023

</details>

cc @justusschock @awaelchli

**Comment by awaelchli** [comment]
@LightingMc Did you disable grad on these models/modules that you don't use? Here is a trivial example that explains this:


```py
import os

import torch
from torch.utils.data import DataLoader, Dataset

from lightning.pytorch import LightningModule, Trainer


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)
        # this layer 2 is "unused"
        self.layer2 = torch.nn.Linear(32, 2)
        # IMPORTANT: Without this, parameters get recorded by DDP and you get the error
        # self.layer2.requires_grad_(False)

    def training_step(self, batch, batch_idx):
        loss = self.layer(batch).sum()  #  + self.layer2(batch).sum()
        return loss

    def configure_optimizers(self):
        # note: we are passing in all params, including the one that is not used
        return torch.optim.SGD(self.parameters(), lr=0.1)


train_data = DataLoader(RandomDataset(32, 64), batch_size=2)

model = BoringModel()
trainer = Trainer(
    default_root_dir=os.getcwd(),
    max_epochs=1,
    enable_model_summary=False,
    accelerator="cpu",
    devices=2,
)
trainer.fit(model, train_data)



```

I can update the error message to include the remark that you should disable grad on modules that you don't use for producing the loss.

**Comment by LightingMc** [comment]
Hey, i was able to fix my issue. Not really sure why but defining the model like this was giving me errors wrt unused parameters.:

class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()


However, if I defined my models like this I stopped getting the error.

class BoringModel(LightningModule):
    def __init__(self):
        super(BoringModel,self).__init__()
