### ISSUE TITLE
Identity operator will be added to my onnx file

### ISSUE THREAD

**Issue by zhuyuanxiang** [Lightning-AI/lightning#18456]
### Bug description

I had write a multi-input and multi-output network, and I need to export it to onnx file.
When I used load_from_checkpoint(), the app will add identity operator in my onnx file, and the C++ app can't parse the onnx file.
I tried to use torch.load_state_dict, then the onnx file will be clean&clear. 
There is unnecessary operator in onnx file.

### What version are you seeing the problem on?

v2.0

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
@zhuyuanxiang Is there envidence that this is caused by Lightning? Wouldn't it be better to report this to onnx/pytorch?

**Comment by awaelchli** [comment]
@zhuyuanxiang Do you have any additional info on this? I'll close the ticket otherwise.
