### ISSUE TITLE
Too many files open error with reload_dataloaders_every_n_epochs and multiple gpus

### ISSUE THREAD

**Issue by tcolgan-mx** [Lightning-AI/lightning#18487]
### Bug description

With reload_dataloaders_every_n_epochs set and multiple gpus selected we get a too many files open error after several epochs.  If we only use one gpu or turn off the reload_dataloaders then this error goes away. 

With this simple example you can see that the number of open files (using `lsof`) grows every iteration by the 2x number of data loader workers (20). With the maximum number of open files set to 512 (`ulimit -n 512`) it can die as early as the sixth epoch whereas in this case of a limit of 2048 it takes ~45 epochs. 

It definitely seems related to the reloading of those dataloader workers but it's unclear if we can do any cleanup of them on our side.

### What version are you seeing the problem on?

v2.0

### How to reproduce the bug

```python
import os

import torch
import pytorch_lightning as pl

torch.manual_seed(0)
import random
random.seed(0)

from torch.utils.data import DataLoader
from torch.utils.data import Dataset
from torch.utils.data import TensorDataset

import torch.nn as nn
import torch.nn.functional as F

class LitModel(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.l1 = nn.Linear(28 * 28, 10)

    def forward(self, x):
        return torch.relu(self.l1(x.view(x.size(0), -1)))

    def training_step(self, batch, batch_idx):
        x, y = batch
        y_hat = self(x)
        loss = F.cross_entropy(y_hat, y)
        return loss

    def on_train_epoch_end(self):
        os.system(f'lsof -p {os.getpid()} -a -d ^mem -d ^cwd -d ^rtd -d ^txt -d ^DEL -w | wc -l')
        print(f"\t pid {os.getpid()}")
        return

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=0.02)

rand_dataset = TensorDataset(torch.rand(2048,28,28),torch.rand(2048).type(torch.LongTensor))
train_loader = DataLoader(rand_dataset,
                         batch_size=1024,
                         pin_memory=True,
                         shuffle=True,
                         num_workers=20,
                         persistent_workers=True,
                         drop_last=True)
trainer = pl.Trainer(
        max_epochs=500,
        devices=2,
        accelerator="gpu",
        reload_dataloaders_every_n_epochs=1
        )

model = LitModel()

trainer.fit(model, train_dataloaders=train_loader)
```

### Error messages and logs

Epoch 0: 100%|████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.06it/s, v_num=45]
217
         pid 3906310
224
         pid 3906286
Epoch 1: 100%|████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.31it/s, v_num=45]
257
         pid 3906310
264
         pid 3906286
Epoch 2: 100%|████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.23it/s, v_num=45]
297
         pid 3906310
304
         pid 3906286
Epoch 3: 100%|████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.24it/s, v_num=45]
337
         pid 3906310
344
         pid 3906286
Epoch 4: 100%|████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.26it/s, v_num=45]
384
         pid 3906286
377
         pid 3906310
Epoch 5: 100%|████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.25it/s, v_num=45]
417
         pid 3906310
424
         pid 3906286
Epoch 6: 100%|████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.27it/s, v_num=45]
457
         pid 3906310
464
         pid 3906286
Epoch 7:   0%|                                                                                                | 0/1 [00:00<?, ?it/s, v_num=45]
Traceback (most recent call last):
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/test_network.py", line 56, in <module>
    self._iterator = self._get_iterator()
  File "/venvs/bugreport/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
    trainer.fit(model, train_dataloaders=train_loader)
  File "/venvs/bugreport/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 532, in fit
    return _MultiProcessingDataLoaderIter(self)
  File "/venvs/bugreport/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1042, in __init__
    call._call_and_handle_interrupt(
  File "/venvs/bugreport/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 42, in _call_and_handle_interrupt
    w.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files

### Environment

<details>
  <summary>Current environment</summary>

* CUDA:
        - GPU:
                - NVIDIA RTX A6000
                - NVIDIA RTX A6000
        - available:         True
        - version:           11.7
* Lightning:
        - lightning-utilities: 0.9.0
        - pytorch-lightning: 2.0.7
        - torch:             2.0.1
        - torchaudio:        2.0.2
        - torchmetrics:      1.1.1
        - torchvision:       0.15.2
* Packages:
        - aiohttp:           3.8.5
        - aiosignal:         1.3.1
        - async-timeout:     4.0.3
        - attrs:             23.1.0
        - certifi:           2023.7.22
        - charset-normalizer: 3.2.0
        - cmake:             3.27.2
        - filelock:          3.12.3
        - frozenlist:        1.4.0
        - fsspec:            2023.9.0
        - idna:              3.4
        - jinja2:            3.1.2
        - lightning-utilities: 0.9.0
        - lit:               16.0.6
        - markupsafe:        2.1.3
        - mpmath:            1.3.0
        - multidict:         6.0.4
        - networkx:          3.1
        - numpy:             1.24.4
        - nvidia-cublas-cu11: 11.10.3.66
        - nvidia-cuda-cupti-cu11: 11.7.101
        - nvidia-cuda-nvrtc-cu11: 11.7.99
        - nvidia-cuda-runtime-cu11: 11.7.99
        - nvidia-cudnn-cu11: 8.5.0.96
        - nvidia-cufft-cu11: 10.9.0.58
        - nvidia-curand-cu11: 10.2.10.91
        - nvidia-cusolver-cu11: 11.4.0.1
        - nvidia-cusparse-cu11: 11.7.4.91
        - nvidia-nccl-cu11:  2.14.3
        - nvidia-nvtx-cu11:  11.7.91
        - packaging:         23.1
        - pillow:            10.0.0
        - pip:               23.2.1
        - pkg-resources:     0.0.0
        - pytorch-lightning: 2.0.7
        - pyyaml:            6.0.1
        - requests:          2.31.0
        - setuptools:        44.0.0
        - sympy:             1.12
        - torch:             2.0.1
        - torchaudio:        2.0.2
        - torchmetrics:      1.1.1
        - torchvision:       0.15.2
        - tqdm:              4.66.1
        - triton:            2.0.0
        - typing-extensions: 4.7.1
        - urllib3:           2.0.4
        - wheel:             0.41.2
        - yarl:              1.9.2
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.10
        - release:           5.15.0-78-generic
        - version:           #85~20.04.1-Ubuntu SMP Mon Jul 17 09:42:39 UTC 2023

</details>

### More info

Same error seen in python 3.10 and pytorch-lightning 2.0.8 as well as in ubuntu 22.04.

cc @justusschock @awaelchli @borda

**Comment by awaelchli** [comment]
@tcolgan-mx Thanks for reporting. Wouldn't this same limitation also occur when doing this in a regular PyTorch training loop (no Lightning)?

**Comment by tcolgan-mx** [comment]
@awaelchli I forgot to put that I'm definitely not sure if this is lighting issue/limitation or an underlying PyTorch issue. I thought I'd start here because we are using Lightning and the different behavior with one vs two gpus in conjunction with setting the reload_dataloaders_every_n_epochs to 1 (or greater than 0) is what we noticed (that was messed up in my original post btw and the example code had me testing setting it to 0).

I can try to see if this is replicated with only a pytroch training loop.

**Comment by awaelchli** [comment]
With `reload_dataloaders_every_n_epochs=0` the number of open files does not grow from epoch to epoch?

**Comment by tcolgan-mx** [comment]
Sorry I wasn't clear! 
With `reload_dataloaders_every_n_epochs=0` the number of open files will not grow from epoch to epoch. 
With `reload_dataloaders_every_n_epochs>0` the number of open files will grow from epoch to epoch if the number of gpus is 2.

**Comment by awaelchli** [comment]
I am able to reproduce this in raw PyTorch, so it's not caused by Lightning as best as I can tell:

```py
import os

import torch
from torch.utils.data import DataLoader, TensorDataset

rank = int(os.environ.get("RANK", "0"))
torch.cuda.set_device(rank)

dataset = TensorDataset(
    torch.rand(2048, 28, 28), 
    torch.rand(2048).type(torch.LongTensor)
)

def get_dataloader():
    return DataLoader(
        dataset,
        batch_size=1024,
        pin_memory=True,
        num_workers=4,
        persistent_workers=True,
    )

for epoch in range(100):
    dl = iter(get_dataloader())
    for x, y in dl:
        x.to(f"cuda:{rank}")
        y.to(f"cuda:{rank}")

    os.system(f"lsof -p {os.getpid()} -a -d ^mem -d ^cwd -d ^rtd -d ^txt -d ^DEL -w | wc -l")
    print(f"\t pid {os.getpid()}")

```

The combination of `pin_memory=True` and `persistent_workers=True` is causing this. Setting either of the two to False makes the issue disappear. 

It looks like there already exists an issue on PyTorch's page:
https://github.com/pytorch/pytorch/issues/91252
