### ISSUE TITLE
Support tracking the batches fetched by dataloader_iter in the progress bar

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#18498]
### Description & Motivation

The progress bar currently assumes that a single batch is processed in a `*_step` method. This is true in all cases except when the user controls the fetching from the `dataloader_iter` (undocumented experimental feature). If that iterator gets fetched more than once in a step, the progress bar falls out of sync as it will only track the step method calls. 

### Pitch

Support the tracking and display of total batch-level progress. 

### Alternatives

There is no alternative except leaving it in the current broken state.

### Additional context

This was raised by the NeMo team who use the dataloader_iter feature.

cc @borda @carmocca @awaelchli @justusschock

**Comment by awaelchli** [comment]
This was fixed by #18441, after rerunning a couple examples, I no longer see the progress bar misbehave. If there are specific issues NeMo is facing, I'll request a repro.

**Comment by carmocca** [comment]
Should we add tests to avoid regressions?
