### ISSUE TITLE
Fabric fail to use all the gpu on SLURM

### ISSUE THREAD

**Issue by jiaaoc** [Lightning-AI/lightning#18504]
### Bug description

I have 4 GPUs available and set the devices to be [0,1,2,3] or 4. 
However, after fabric.launch(), it seems that it only use one GPU.

This is the code:
```
print("Devices available:", torch.cuda.device_count())
print("Devices specified:", devices)

fabric = L.Fabric(devices=[0,1,2,3], precision=precision, strategy=strategy, accelerator='gpu')
print(fabric.world_size)
fabric.launch()
```

And this is the output:
```
Devices available: 4
Devices specified: 4
1
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------
```

### What version are you seeing the problem on?

master

### Environment

```
#- PyTorch Version (e.g., 2.0): 2.1
#- Python version (e.g., 3.9): 3.10
#- OS (e.g., Linux): Linux
#- CUDA/cuDNN version: 11.5
#- How you installed Lightning(`conda`, `pip`, source): pip

```

cc @awaelchli

**Comment by jiaaoc** [comment]
Setting the job name to bash works. But why is it necessary?

**Comment by awaelchli** [comment]
@jiaaoc You can use SLURM either to submit a job and then you use this setup:
https://lightning.ai/docs/fabric/stable/guide/multi_node/slurm.html#submit-a-training-script-to-slurm
OR you use it in interactive mode and then you set this setting: https://lightning.ai/docs/fabric/stable/guide/multi_node/slurm.html#interactive-mode

There is no other way how Lightning could detect whether it is running interactively or not unless the user sets these settings.

**Comment by awaelchli** [comment]
@jiaaoc Does this answer the question? Is it working?
