### ISSUE TITLE
Some outdated comments inconsistent with the code

### ISSUE THREAD

**Issue by 0x404** [Lightning-AI/lightning#18530]
### Outline & Motivation

https://github.com/Lightning-AI/lightning/blob/e958c6f1dcf05b70985c472a37c59ffefa223a40/src/lightning/pytorch/trainer/connectors/logger_connector/result.py#L299-L307

these comments are inconsistent with the usage of `_ResultCollection`, Since `_ResultCollection` has no device argument and positional argument follows keyword argument is also not allowed. 

cc @borda @justusschock @awaelchli

**Comment by awaelchli** [comment]
@0x404 Would you like to send a PR removing the typo?

**Comment by 0x404** [comment]
Sure:)
