### ISSUE TITLE
Export to ONNX

### ISSUE THREAD

**Issue by MarcoPrassel** [Lightning-AI/lightning#18568]
### Bug description

Hi, I'm trying to convert my model Detr to onnx ,  I followed the guide but I get this error: 
 
f"`torch>=2.0` requires `onnx` to be installed to use `{type(self).__name__}.to_onnx()`"

 I am working on Google Colab.

Can you help me?

### What version are you seeing the problem on?

master

### How to reproduce the bug

```python
checkpoint_path = '/content/lightning_logs/version_0/checkpoints/max.ckpt'
checkpoint = torch.load(checkpoint_path)

# Crea una nuova istanza del modello e assegna i pesi del checkpoint
model = Detr(lr=1e-4, lr_backbone=1e-5, weight_decay=1e-4)
model.load_state_dict(checkpoint['state_dict'])
model.to_onnx("test.onnx",  export_params=True)
```

### Error messages and logs

```
# Error messages and logs here please
```

ModuleNotFoundError: `torch>=2.0` requires `onnx` to be installed to use `Detr.to_onnx()`

   1362             )
   1361                 f"`torch>=2.0` requires `onnx` to be installed to use `{type(self).__name__}.to_onnx()`"
-> 1360             raise ModuleNotFoundError(
   1359         if _TORCH_GREATER_EQUAL_2_0 and not _ONNX_AVAILABLE:
   1358         """
[/usr/local/lib/python3.10/dist-packages/pytorch_lightning/core/module.py](https://localhost:8080/#) in to_onnx(self, file_path, input_sample, **kwargs)
1 frames

----> 1 model.to_onnx("test.onnx",  export_params=True)
[<ipython-input-35-52a0fa5ae486>](https://localhost:8080/#) in <cell line: 1>()
ModuleNotFoundError                       Traceback (most recent call last)

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
@MarcoPrassel You need to install the onnx package as the error tells you:
```
pip install onnx
```

**Comment by MarcoPrassel** [comment]
@awaelchli

**Comment by MarcoPrassel** [comment]
Thank you @awaelchli ,
I had installed onnx but the error was always present, now everything seems to be OK, although I get this error:
`Could not export to ONNX since neither `input_sample` nor `model.example_input_array` attribute is set.`
 I am not an expert,  this is the first time I use pytroch lightning, my goal is to export the model trained with Detr to the onnx format, can you explain how I can do this?

**Comment by awaelchli** [comment]
@MarcoPrassel Just pass in the input sample argument as suggested by the error message. Here are the docs with examples: https://lightning.ai/docs/pytorch/stable/deploy/production_advanced.html#compile-your-model-to-onnx
You can find these by just typing "onnx" in to the search bar.

**Comment by awaelchli** [comment]
Let me know if you have any more issues :)

**Comment by Lookforworld** [comment]
@awaelchli  
I have an erro when using  to_onnx() method.

The model's forward like this: 
```
def forward(self, windows_batch):
        insample_y = windows_batch["insample_y"]
        insample_mask = windows_batch["insample_mask"]
        futr_exog = windows_batch["futr_exog"]
        hist_exog = windows_batch["hist_exog"]
        stat_exog = windows_batch["stat_exog"]
                        ...
                        ...
```
I using the to_onnx() method like this:

```
trained_md.eval()
data_=trained_md.dataset
in_=iter(data_)
in_=next(in_)
input_names=[]
input_dict = {}
for itm in in_:
    if in_[itm] is not None:
        input_dict[itm] = in_[itm][-1:]
        input_names.append(itm)
in_=input_dict
trained_md.to_onnx(file_path='Nbx.onnx',
                   input_sample=in_,  
                   input_names=input_names,

```

Then give me an erro:

```
TypeError: NBEATSx.forward() missing 1 required positional argument: 'windows_batch'
```

How can I fix this issue?
