### ISSUE TITLE
DDP communication hooks with Fabric

### ISSUE THREAD

**Issue by patchmeifyoucan** [Lightning-AI/lightning#18581]
### 📚 Documentation

There are docs for a Lightning Trainer using more optimized gradient synchronization techniques as communication hooks:
https://pytorch-lightning.readthedocs.io/en/1.4.9/advanced/advanced_gpu.html#ddp-communication-hooks

How would I accomplish this using Fabric? Is it somehow possible to call `register_comm_hook`  on a Fabric module? Or do I have to use plain PyTorch for this kind of setup?

cc @borda

**Comment by awaelchli** [comment]
@patchmeifyoucan This is possible yes. You can call `register_comm_hook` on the PyTorch DDP wrapper which you can access through

```py
model = fabric.setup(...)
model._forward_module.register_comm_hook(...)
```
