### ISSUE TITLE
Incorrect batch dtype at `on_train_batch_start/end` using 16-mixed / FSDP

### ISSUE THREAD

**Issue by Sumith1896** [Lightning-AI/lightning#18612]
### Bug description

I have attached a minimal repro below. When using `16-mixed` precision and FSDPStrategy, `on_train_batch_start` and `on_train_batch_end` receives the batch in low prec `torch.float16`. A different hook `training_step` receives the correct `torch.float32` as expected.

```
    assert(batch[0].dtype == torch.float32)
AssertionError
```

### What version are you seeing the problem on?

master

### How to reproduce the bug

```python
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader

import lightning as L
from lightning.pytorch.strategies import FSDPStrategy
from lightning.pytorch.demos import Transformer, WikiText2


class LanguageModel(L.LightningModule):
    def __init__(self, vocab_size):
        super().__init__()
        self.model = Transformer(  # 1B parameters
            vocab_size=vocab_size,
            nlayers=32,
            nhid=4096,
            ninp=1024,
            nhead=64,
        )

    def on_train_batch_start(self, batch, batch_idx):
        ### ISSUE: this assertion fails, is torch.float16
        assert(batch[0].dtype == torch.float32) 
        return

    def training_step(self, batch):
        input, target = batch
        print(input.dtype, target.dtype) # returns torch.float32
        input, target = input.to(torch.int64), target.to(torch.int64)
        output = self.model(input, target)
        loss = F.nll_loss(output, target.view(-1))
        self.log("train_loss", loss, prog_bar=True)
        return loss

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=0.1)


L.seed_everything(42)

# Data
class CustomWikiText2(WikiText2):
    def __getitem__(self, idx):
        l, r = super().__getitem__(idx)
        return l.to(torch.float32), r.to(torch.float32)
dataset = CustomWikiText2()
train_dataloader = DataLoader(dataset)

# Model
model = LanguageModel(vocab_size=dataset.vocab_size)

# Strategy
strategy = FSDPStrategy()

# Trainer
trainer = L.Trainer(accelerator="cuda", devices=1, strategy=strategy, precision='16-mixed')
trainer.fit(model, train_dataloader)
trainer.print(torch.cuda.memory_summary())
```

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0): 2.0.9
#- Lightning App Version (e.g., 0.5.2): 2.1.0rc0
#- PyTorch Version (e.g., 2.0): 2.2.0.dev20230921+cu118
#- Python version (e.g., 3.9): 3.10
#- OS (e.g., Linux): Linux
#- CUDA/cuDNN version: 11.8
#- GPU models and configuration: A100
#- How you installed Lightning(`conda`, `pip`, source): pip/venv
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @awaelchli @carmocca

**Comment by awaelchli** [comment]
We have two choices we could make here. 

1) We keep the input conversion in float16 for mixed precision training, but set `cast_root_forward_inputs=False` (default is True) in https://github.com/Lightning-AI/lightning/blob/f1df76ce840119f7baee702ef2df1373e516f12f/src/lightning/pytorch/plugins/precision/fsdp.py#L113-L117 This will make it so that FSDP won't cast the tensor back to float32 (the weights dtype) when passing it into the training step. 

2) We don't convert the input to float16 for mixed precision training. This way, the dtype will be unchanged and appear as float32 both in the on_train_batch_start hook as well as in training_step / forward. 

1) is consistent with how the non-fsdp amp works in PL, while 2) is consistent with how it is in Fabric. This is rather more like a choice we have to make in terms of what is the convenient default. I could be convinced either way. But we should avoid redundant dtype conversions whenever possible.

@carmocca @justusschock do you have opinions?

**Comment by Sumith1896** [comment]
Thanks @awaelchli, I'm not too familiar with lightning internals / design philosophy to comment here, but a minor note is that for mixed-precision training, I would still expect to be in full precision at `on_train_batch_start` and `training_step` for all logging/training purposes.

**Comment by carmocca** [comment]
> while 2) is consistent with how it is in Fabric

If I understood the proposal, 2) advocates that we don't convert. But it seems like Fabric does convert https://github.com/Lightning-AI/lightning/blob/master/src/lightning/fabric/plugins/precision/amp.py#L64-L65. Did you mean the opposite?

I think option 2) is the closest to the standard PyTorch experience, so I would suggest that as I agree with @Sumith1896 

But why was this conversion added in the first place? Was there a specific reason? Would the users have to convert themselves then?

**Comment by awaelchli** [comment]
There is no right or wrong choice here. I presented two ways to resolve the unexpected difference in dtype between the two hooks and then I asked for opinions before I go and send a PR. That's all. 

> Did you mean the opposite?

In the text I initially wrote
"Option 1) is consistent with how the non-fsdp amp works in PL, while 2) is consistent with how it is in Fabric." but I had the options switched. I edited the post.  

> But why was this conversion added in the first place? Was there a specific reason? Would the users have to convert themselves then?

It was in LightningLite first and then it became Fabric. This is really up to the user. A cast would occur sooner or later anyway if the weights have a different dtype. 

Please note that this conversion is unique to FSDP as I described above. Tensors passe to the forward get converted. Other wrappers don't do this.

**Comment by Sumith1896** [comment]
Thank you so much for the fix @awaelchli!
