### ISSUE TITLE
Module variable is initialized twice

### ISSUE THREAD

**Issue by mfoglio** [Lightning-AI/lightning#18644]
### Bug description

I am not entirely sure this is a bug. For sure, this is a weird behavior that I have never experienced before. I think it may caused by some edge case I never encountered before, or by some "tricks" done by Torch Lightning either when importing or executing different threads.

I have a class called `BaseImageDataset` which extends `Dataset` and handles the files of my dataset. Specifically, it maps what I called `annotation_ids` (which are images filenames) to integers. The mapping is stored at the module level by the variable `_annotation_ids_str_to_int`. When initializing a `BaseImageDataset`, in the `__init__` method I have sure that all the annotation_ids are converted to integers and registered to `_annotation_ids_str_to_int`. I used some prints to verify that `_annotation_ids_str_to_int` is never empty at the end of the `__init__`.

Interestingly enough, when the method `__get_item__` is executed, `_annotation_ids_str_to_int` is empty and a KeyError exception is raised. I also printed `print('_annotation_ids_str_to_int', id(_annotation_ids_str_to_int))` and I noticed that when it raises the error, the `id` is not the same as before. Meaning that the object has been reinitialized (or at least it has been initialized more than once). However, according to PyCharm, the thread is still the same `MainThread` (so both instances of `_annotation_ids_str_to_int` seemed to have lived in the same thread).

One thing of note: in `LightningDataModule` I initialize instances of `BaseImageDataset` in two places: in the `__init__` and in the `setup()`. It seems that `id(_annotation_ids_str_to_int)` changes when moving from the `__init__` to the `setup()`. However, this should not cause any error *in theory* because 
- `_annotation_ids_str_to_int` is initialized inside the `__init__` of the `BaseImageDataset`
- `_annotation_ids_str_to_int` is defined at the module level, so it should exist just a single instance of it (if my understanding of Python modules is correct)

What do you think can cause the `_annotation_ids_str_to_int` to be empty in `__get_item__`?
 
```
import glob
import json
import os
import copy
from typing import Dict, List, Union

from bidict import bidict
import torch
from PIL import Image
from torch.utils.data import Dataset
from tqdm import tqdm

import utils

log = utils.get_pylogger(__name__)


_annotation_ids_str_to_int: Dict[str, int] = bidict()


class BaseImageDataset(Dataset):

    def __init__(
            self,
            path: str,
            annotation_ids: Union[None, List[int]],
            img_file_extension: str = '.jpg',
            metadata_file_extension: str = '.json',
    ):
        """ Takes care of loading json metadata and associated images.
        The dataset structure must be the following:
         - db
           - metadata
             - 00001.json
             - 00002.json
             - ...
           - images
             - 00001.jpg
             - 00002.jpg
             - ...
        :param path: path of the dataset folder
        :param annotation_ids: annotation ids to keep
        """
        self.images_dir_path = os.path.join(path, 'images')
        self.metadata_dir_path = os.path.join(path, 'metadata')
        self.img_file_extension = img_file_extension
        self.metadata_file_extension = metadata_file_extension
        self.annotation_ids = annotation_ids if annotation_ids is not None else self._load_annotation_ids()
        # Convert annotation ids
        self.annotation_ids = self._convert_annotation_ids_to_int(self.annotation_ids)
        # Sanity check
        self._sanity_check()
        # Store annotation_ids as numpy array to reduce memory usage across workers
        # More info here https://github.com/pytorch/pytorch/issues/13246
        # In brief, numpy reduces memory usage across workers
        # Using torch tensors seems even better so we switched from numpy to torch tensor
        self.annotation_ids = torch.tensor(
            self.annotation_ids,
            dtype=torch.int32
        )
        print('_annotation_ids_str_to_int', id(_annotation_ids_str_to_int))

    def __len__(self):
        return len(self.annotation_ids)

    def __getitem__(self, index: int, load_image: bool = True):
        print('_annotation_ids_str_to_int', id(_annotation_ids_str_to_int))
        annotation_id = self.annotation_ids[index]
        annotation_id_str = _annotation_ids_str_to_int.inverse[annotation_id.item()]
        image = self._load_image(annotation_id_str) if load_image else None
        metadata = self._load_metadata(annotation_id_str)
        return image, metadata

    def _load_image(self, annotation_id: int):
        return Image.open(os.path.join(self.images_dir_path, f'{annotation_id}{self.img_file_extension}')).convert('RGB')

    def _load_metadata(self, annotation_id: int):
        with open(os.path.join(self.metadata_dir_path, f'{annotation_id}{self.metadata_file_extension}'), 'r') as fp:
            return json.load(fp)

    def _sanity_check(self) -> List[int]:
        # Retrieves list of existing ids in folders
        images_annotation_ids = self._get_annotation_ids_from_folder(
            self.images_dir_path, self.img_file_extension
        )
        metadata_annotation_ids = self._get_annotation_ids_from_folder(
            self.metadata_dir_path, self.metadata_file_extension
        )
        # Check that annotation ids exist
        for annotation_id in tqdm(self.annotation_ids, desc="Sanity check"):
            annotation_id_str = _annotation_ids_str_to_int.inverse[annotation_id]
            assert annotation_id_str in images_annotation_ids
            assert annotation_id_str in metadata_annotation_ids

    def _load_annotation_ids(self):
        # Retrieves list of existing ids in folders
        images_annotation_ids = self._get_annotation_ids_from_folder(
            self.images_dir_path, self.img_file_extension
        )
        metadata_annotation_ids = self._get_annotation_ids_from_folder(
            self.metadata_dir_path, self.metadata_file_extension
        )
        assert sorted(images_annotation_ids) == sorted(metadata_annotation_ids)
        return images_annotation_ids

    def _get_annotation_ids_from_folder(self, dir_path: str, file_extension: str):
        annotation_ids = sorted([
            os.path.basename(file_path).replace(f'{file_extension}', '')
            for file_path in glob.glob(os.path.join(dir_path, f'*{file_extension}'))
        ])
        return annotation_ids

    def _convert_annotation_ids_to_int(self, annotation_ids):
        return [self._convert_annotation_id_to_int(annotation_id) for annotation_id in annotation_ids]

    @staticmethod
    def _convert_annotation_id_to_int(annotation_id: Union[int, str]) -> int:
        if annotation_id not in _annotation_ids_str_to_int:
            _annotation_ids_str_to_int[annotation_id] = len(_annotation_ids_str_to_int)
        return _annotation_ids_str_to_int[annotation_id]


if __name__ == '__main__':
    from matplotlib import pyplot as plt

    dataset = BaseImageDataset(
        path='data_superannotate',
        annotation_ids=None,
    )
    image, metadata = dataset[0]
    plt.imshow(image)
    plt.show()
    print(metadata)
```

### What version are you seeing the problem on?

v1.7

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- PyTorch Lightning Version (e.g., 1.5.0): 1.7.7
#- PyTorch Version (e.g., 2.0): 1.12.0
#- Python version (e.g., 3.9): 3.8
#- OS (e.g., Linux): macOS
#- CUDA/cuDNN version: N/A - I am using CPU
#- GPU models and configuration: N/A
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud): local
```

</details>

**Comment by awaelchli** [comment]
@mfoglio The code you shared points to a folder that does not exist, at least not when I run it. In this case, `_load_annotation_ids` returns an empty list and that's why you get an index out of bounds error in your `__getitem__`. A simple step through the debugger in the `__init__()` call will show you this. 

Since your question doesn't relate to Lightning, I'm closing the issue. But feel free to ask for help on the forum if you have questions about the PyTorch dataset or how to implement your use case. 

>  It seems that id(_annotation_ids_str_to_int) changes when moving from the __init__ to the setup()

Id() in Python returns the object id. This is not deterministic and the fact that it changes when you move the initialization of the object in a different place is completely expected. I'm not entirely sure what your intention is by checking the id of this dictionary.
