### ISSUE TITLE
Fabric leaks the default device on exception

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lightning#18705]
### Bug description

See reproduction below

### What version are you seeing the problem on?

master

### How to reproduce the bug

```python
import pytest
import torch

import lightning as L
from lightning.fabric.plugins import HalfPrecision


class MyPlugin(HalfPrecision):
    def init_context(self):
        # arbitrary error
        raise NotImplementedError


fabric = L.Fabric(devices=1, accelerator="cuda", plugins=MyPlugin("16-true"))

with pytest.raises(NotImplementedError):
    with fabric.init_module():
        pass

default_device = torch.tensor(0).device
assert default_device.type == "cpu", default_device
```

### Error messages and logs

The assertion fails

### Environment

Current master

### More info

This blocks https://github.com/Lightning-AI/lightning/pull/18704

**Comment by awaelchli** [comment]
Could this be resolved by resetting the device in a finally-block?

**Comment by carmocca** [comment]
I thought `torch.device` implemented `__exit__`. If not, then we would need to write our own context manager that does it

**Comment by carmocca** [comment]
Your example should be

```python
from contextlib import ExitStack
import pytest
import torch

ctx = ExitStack()
ctx.enter_context(torch.device("cuda:0"))

with pytest.raises(NotImplementedError):
    with ctx:
        raise NotImplementedError()

default_device = torch.tensor(0).device
assert default_device.type == "cpu", default_device
```

which does work as expected.

I found the cause of this issue. I'll open a PR
