### ISSUE TITLE
find_usable_cuda_devices always returns GPU 0

### ISSUE THREAD

**Issue by TheAeryan** [Lightning-AI/lightning#18720]
### Bug description

The function `find_usable_cuda_device` always returns the first GPU (index `0`), even though if it's being currently utilized and there exists another GPU (index `1`) with 0% utilization.

Reproducible example:
```python
>>>from pytorch_lightning.accelerators import find_usable_cuda_devices
>>>find_usable_cuda_devices(0)
[0]
```

Screen capture of `nvidia-smi`:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:AF:00.0 Off |                    0 |
| N/A   45C    P0    52W / 250W |  14642MiB / 16160MiB |     16%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  Off  | 00000000:D8:00.0 Off |                    0 |
| N/A   39C    P0    39W / 250W |    719MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

As you can see, the GPU 1 is currently free, but `find_usable_cuda_devices` returns `[0]` nonetheless.

### What version are you seeing the problem on?

v2.0

### How to reproduce the bug

```python
>>>from pytorch_lightning.accelerators import find_usable_cuda_devices
>>>find_usable_cuda_devices(0)
[0]
```

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

### More info

I am running this code inside a cluster with many GPUs, although the container my code is running in only has access to two GPUs. These two GPUs are mine alone (not shared with other users).

cc @justusschock @awaelchli

**Comment by awaelchli** [comment]
Hi @TheAeryan 

The docstring says at the very beginning:

>     A GPU is considered usable if we can successfully move a tensor to the device, and this is what this function
>     tests for each GPU on the system until the target number of usable devices is found.
> 
>     A subset of GPUs on the system might be used by other processes, and if the GPU is configured to operate in
>     'exclusive' mode (configurable by the admin), then only one process is allowed to occupy it.

Both of your GPUs are usable, and so if you do

```py
find_usable_cuda_devices(2)
```

the expectation is that it will return [0, 1]. 

`find_usable_cuda_devices(0)` shouldn't be a valid input, you can't request to find 0 usable GPU devices. This is an edge case we would want to fix.

**Comment by TheAeryan** [comment]
Sorry, it was `find_usable_cuda_devices(1)`. Nonetheless, if that's the intended behaviour, I suppose it is not a bug. Does Lightning provide any function to get a GPU with 0% util?

**Comment by awaelchli** [comment]
Hey @TheAeryan 
No problem, thanks for opening the question anyway, we found a small edge case I'm fixing here: https://github.com/Lightning-AI/lightning/pull/18722

No, we don't have a utility for what you need. I think what you want is this:

```py
free_gpus = [device_id for device_id in range(torch.cuda.device_count()) if torch.cuda.utilization(device_id) == 0]
```
