### ISSUE TITLE
Lightning requests changing strategy, but documentation does not tell me what the differences are

### ISSUE THREAD

**Issue by kaare-mikkelsen** [Lightning-AI/lightning#18728]
### 📚 Documentation

If I call torch.cuda.is_available() prior to creating a trainer with the default strategy, I get the following error:

> RuntimeError: Lightning can’t create new processes if CUDA is already initialized. Did you manually call torch.cuda.* functions, have moved the model to the device, or allocated memory on the GPU any other way? Please remove any such calls, or change the selected strategy. You will have to restart the Python kernel.

However, going to https://lightning.ai/docs/pytorch/stable/extensions/strategy.html, it is not clear what strategy would remove this problem. I have not had this issue before, so I assume that some portion of lightning has become more fussy about this. In fact, I must admit that the description of the strategies are pretty unhelpful. I am running a single model on a single gpu, so which strategy is that?

cc @borda @justusschock @awaelchli

**Comment by awaelchli** [comment]
Hey @kaare-mikkelsen 
In which version of Lightning did this happen and what arguments did you pass to the Trainer.

**Comment by kaare-mikkelsen** [comment]
Hello awaelchli

```
conda list lightning
\# packages in environment at /home/knox/.conda/envs/torc2:
\#
\# Name                    Version                   Build  Channel
lightning-utilities       0.9.0              pyhd8ed1ab_0    conda-forge
pytorch-lightning         2.0.9              pyhd8ed1ab_0    conda-forge
```

Trainer call looks like this:
```

trainerKeys={'deterministic':True,
             'logger':neptune_logger,
             'enable_progress_bar':True,
             'benchmark':True,
             'callbacks':[EarlyStopping(monitor="valKappa", mode="max",patience=10)]}


trainerKeys['accelerator']='gpu'
trainerKeys['devices']=1
trainerKeys['max_epochs']=30

trainer=pl.Trainer(**trainerKeys)
```
I call torch.cuda.is_available() in order to be able to run the same code on both gpu-enabled nodes and a laptop without a GPU installed.

**Comment by awaelchli** [comment]
@kaare-mikkelsen This error won't happen if you run on one GPU. You must have accidentally run with multiple GPUs and then this happened.

**Comment by kaare-mikkelsen** [comment]
@awaelchli 
Thank you. adding os.environ["CUDA_VISIBLE_DEVICES"]="1" to the top of my script makes the error go away.

**Comment by patel-zeel** [comment]
@kaare-mikkelsen I run into the same issue while running on multiple GPUs. I want to use multiple GPUs. How to handle the error?

**Comment by xakirasa** [comment]
Hi Patel, I run multiple GPUs, did you manage to solve this error?

**Comment by patel-zeel** [comment]
Nope @xakirasa.
