### ISSUE TITLE
Checkpointing sometimes generates file with name ended in "-v1"

### ISSUE THREAD

**Issue by TheAeryan** [Lightning-AI/lightning#18749]
### Bug description

I am using the `ModelCheckpoint` callback to periodically save checkpoints. I want to save the checkpoints with the best validation NLL, best validation MSE and, finally, the checkpoint with the most recent model weights (_last_ checkpoint). I have observed that the NLL and MSE checkpoints work just fine, but the _last_ checkpoint is sometimes saved with the name provided in the `filename` parameter of `ModelCheckpoint` whereas, other times, its name ends in `-v1.ckpt`. I have tried different things, such as using the parameter `save_top_k=1`, but no matter what I try the name of the _last_ checkpoint remains inconsistent.

### What version are you seeing the problem on?

v2.0

### How to reproduce the bug

```python
import pytorch_lightning as pl
from pytorch_lightning.loggers.tensorboard import TensorBoardLogger
from pytorch_lightning.callbacks import ModelCheckpoint

trainer = pl.Trainer(max_steps = 100000,
                     check_val_every_n_epoch = 10,
                     logger                  = TensorBoardLogger(args.logs_dir, name=id, 
                     version=""),
                     callbacks               = [ModelCheckpoint(monitor=None,										 
                                               every_n_epochs=1,											 
                                               dirpath=args.ckpt_dir,										 
                                               filename=id,										 										 
                                               save_on_train_epoch_end=True),
													 
                                               ModelCheckpoint(monitor='v_nll',											 
                                               every_n_epochs=1,															 
                                               dirpath=args.ckpt_dir,																 
                                               filename=id+"-nll",																 
                                               mode='min',																 
                                               save_top_k=1,																 
                                               save_on_train_epoch_end=False),
		
                                               ModelCheckpoint(monitor='v_mse',																 
                                               every_n_epochs=1,																 
                                               dirpath=args.ckpt_dir,															 
                                               filename=id+"-mse",																 
                                               mode='min',																 
                                               save_top_k=1,															 
                                               save_on_train_epoch_end=False)]
                         deterministic           = args.deterministic,
                         gradient_clip_val       = args.clip,
                         accelerator = "cuda")

trainer.fit(model, datamodule=dm)
```

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @carmocca @awaelchli

**Comment by awaelchli** [comment]
@TheAeryan Thanks, it would be very helpful if you could determine which of the three callback configurations is causing it. Note that the callback will avoid overwriting files, so if there is a name collision, it will add the suffix.

**Comment by TheAeryan** [comment]
@awaelchli The callback that is causing this is the `monitor=None` one. For the other two, the checkpoint is always saved with the correct name (`-nll` and `-mse`, without the `-v1`). I know that, on collision, Lightning saves the checkpoint with a name ended in `-v*` but I don't know why the collision is happening in the first place (I would expect that the old checkpoint is removed before saving the new one, so no collision is produced).

**Comment by amorehead** [comment]
@TheAeryan, have you tried setting `enable_version_counter=False` in your `ModelCheckpoint` `Callback` object with `monitor=None`? Lightning 2.1.0 (and perhaps earlier versions >= 2.0.0) introduced the `enable_version_counter` flag, I believe (https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html#lightning.pytorch.callbacks.ModelCheckpoint).

**Comment by TheAeryan** [comment]
I tried using `enable_version_counter=False` (had to update Lightning for that) and now the bug is solved! Thank you very much, @awaelchli and @amorehead. Closing the issue now.
