### ISSUE TITLE
Bad doc webpage layout

### ISSUE THREAD

**Issue by yuzhenmao** [Lightning-AI/lightning#18806]
### Bug description

For the webpage of the documentation of 2.1.0 version, its layout is bad (contents are shifted to the left) which makes the users difficult to read.
<img width="1220" alt="Screenshot 2023-10-16 at 6 55 48 PM" src="https://github.com/Lightning-AI/lightning/assets/57878927/5ea7b1b1-af03-4ff8-950a-084173d5e452">

### What version are you seeing the problem on?

master

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @borda

**Comment by awaelchli** [comment]
@yuzhenmao Could you try hard-refreshing the page (Ctrl + F5 or shift+ click refresh button in browser)? It was fixed a few days ago already.

**Comment by Borda** [comment]
I believe this was fixed, but it could be an artifact of your local browser cash...

**Comment by yuzhenmao** [comment]
Thanks! It is because of my local browser cash...
