### ISSUE TITLE
Docs website css is buggy

### ISSUE THREAD

**Issue by busFred** [Lightning-AI/lightning#18800]
### 📚 Documentation

Once the page got scrolled down, all the main content shifts left and cause some words completely unreadable.
![image](https://github.com/Lightning-AI/lightning/assets/32878707/a529aa2e-eeb2-49e6-b243-45ec7a575c91)

cc @borda

**Comment by awaelchli** [comment]
@busFred This was fixed a few days ago, but you'll need to full reload (reset cache) in your browser (Ctrl+F5 or Shift+click reload button in most browsers).
