### ISSUE TITLE
transformer engine (FP8) support for FSDP training

### ISSUE THREAD

**Issue by naveenkumarmarri** [Lightning-AI/lightning#18820]
### Description & Motivation

Nvidia transformer engine supports FP8 precision for training on H100. lightning has support for FP8 training through fabric. However, the support is not available when training model with FSDP. are there any plans to support this in near future?

### Pitch

Training with FSDP will allow to train large scale models

**Comment by carmocca** [comment]
Please see the discussion here: https://github.com/Lightning-AI/lightning/issues/18679#issuecomment-1769840856

**Comment by tonyf** [comment]
Is there support for this now? Looks like fsdp can be used with transformer-engine via lazy weight init according to https://github.com/Lightning-AI/pytorch-lightning/issues/18679#issuecomment-1992158625
