### ISSUE TITLE
Extra GPU usage in ddp and ddp-spawn

### ISSUE THREAD

**Issue by FANGAreNotGnu** [Lightning-AI/lightning#18845]
### Bug description

Hi there,

When I run ddp/ddp_spawn across multiple GPUs, there is always extra GPU usage. Each process always has an additional 366MiB usage on each GPU, starting from "initializating distributed" and lasting until the progress ends (for ddp_spawn only the main process has such issue). Such problem also appeared in 1.X version until I set auto_select_gpus=False as suggested in https://discuss.pytorch.org/t/distributed-data-parallel-training-extra-gpu-n-1-process-on-n-gpu-process-job/115023 and https://github.com/Lightning-AI/lightning/discussions/9864. But for 2.X there is no such options. And it's unclear to me where does the additional GPU usage come from.

The `nvidia-smi` output when I run with `ddp` and `ddp_spawn` respectively are attached below.

### What version are you seeing the problem on?

v2.0

### How to reproduce the bug

```python
https://github.com/autogluon/autogluon/blob/master/examples/automm/distillation/automm_distillation_glue.py
```

### Error messages and logs

ddp (ddp_find_unused_parameters_true):

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:16.0 Off |                    0 |
| N/A   39C    P0   125W / 300W |   7021MiB / 32768MiB |     39%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:00:17.0 Off |                    0 |
| N/A   40C    P0   128W / 300W |   7721MiB / 32768MiB |     35%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:00:18.0 Off |                    0 |
| N/A   39C    P0   123W / 300W |   6873MiB / 32768MiB |     39%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:00:19.0 Off |                    0 |
| N/A   39C    P0   110W / 300W |   9779MiB / 32768MiB |     34%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  Tesla V100-SXM2...  On   | 00000000:00:1A.0 Off |                    0 |
| N/A   40C    P0   119W / 300W |   9821MiB / 32768MiB |     36%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  Tesla V100-SXM2...  On   | 00000000:00:1B.0 Off |                    0 |
| N/A   41C    P0   128W / 300W |   9809MiB / 32768MiB |     38%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  Tesla V100-SXM2...  On   | 00000000:00:1C.0 Off |                    0 |
| N/A   40C    P0   126W / 300W |   6851MiB / 32768MiB |     40%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  Tesla V100-SXM2...  On   | 00000000:00:1D.0 Off |                    0 |
| N/A   40C    P0   124W / 300W |   7267MiB / 32768MiB |     38%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A   1145471      C   python3                          4452MiB |
|    0   N/A  N/A   1145789      C   ...conda/envs/ag/bin/python3      366MiB |
|    0   N/A  N/A   1145856      C   ...conda/envs/ag/bin/python3      366MiB |
|    0   N/A  N/A   1145920      C   ...conda/envs/ag/bin/python3      366MiB |
|    0   N/A  N/A   1145984      C   ...conda/envs/ag/bin/python3      366MiB |
|    0   N/A  N/A   1146051      C   ...conda/envs/ag/bin/python3      366MiB |
|    0   N/A  N/A   1146115      C   ...conda/envs/ag/bin/python3      366MiB |
|    0   N/A  N/A   1146179      C   ...conda/envs/ag/bin/python3      366MiB |
|    1   N/A  N/A   1145471      C   python3                           366MiB |
|    1   N/A  N/A   1145789      C   ...conda/envs/ag/bin/python3     5152MiB |
|    1   N/A  N/A   1145856      C   ...conda/envs/ag/bin/python3      366MiB |
|    1   N/A  N/A   1145920      C   ...conda/envs/ag/bin/python3      366MiB |
|    1   N/A  N/A   1145984      C   ...conda/envs/ag/bin/python3      366MiB |
|    1   N/A  N/A   1146051      C   ...conda/envs/ag/bin/python3      366MiB |
|    1   N/A  N/A   1146115      C   ...conda/envs/ag/bin/python3      366MiB |
|    1   N/A  N/A   1146179      C   ...conda/envs/ag/bin/python3      366MiB |
|    2   N/A  N/A   1145471      C   python3                           366MiB |
|    2   N/A  N/A   1145789      C   ...conda/envs/ag/bin/python3      366MiB |
|    2   N/A  N/A   1145856      C   ...conda/envs/ag/bin/python3     4304MiB |
|    2   N/A  N/A   1145920      C   ...conda/envs/ag/bin/python3      366MiB |
|    2   N/A  N/A   1145984      C   ...conda/envs/ag/bin/python3      366MiB |
|    2   N/A  N/A   1146051      C   ...conda/envs/ag/bin/python3      366MiB |
|    2   N/A  N/A   1146115      C   ...conda/envs/ag/bin/python3      366MiB |
|    2   N/A  N/A   1146179      C   ...conda/envs/ag/bin/python3      366MiB |
|    3   N/A  N/A   1145471      C   python3                           366MiB |
|    3   N/A  N/A   1145789      C   ...conda/envs/ag/bin/python3      366MiB |
|    3   N/A  N/A   1145856      C   ...conda/envs/ag/bin/python3      366MiB |
|    3   N/A  N/A   1145920      C   ...conda/envs/ag/bin/python3     7210MiB |
|    3   N/A  N/A   1145984      C   ...conda/envs/ag/bin/python3      366MiB |
|    3   N/A  N/A   1146051      C   ...conda/envs/ag/bin/python3      366MiB |
|    3   N/A  N/A   1146115      C   ...conda/envs/ag/bin/python3      366MiB |
|    3   N/A  N/A   1146179      C   ...conda/envs/ag/bin/python3      366MiB |
|    4   N/A  N/A   1145471      C   python3                           366MiB |
|    4   N/A  N/A   1145789      C   ...conda/envs/ag/bin/python3      366MiB |
|    4   N/A  N/A   1145856      C   ...conda/envs/ag/bin/python3      366MiB |
|    4   N/A  N/A   1145920      C   ...conda/envs/ag/bin/python3      366MiB |
|    4   N/A  N/A   1145984      C   ...conda/envs/ag/bin/python3     7252MiB |
|    4   N/A  N/A   1146051      C   ...conda/envs/ag/bin/python3      366MiB |
|    4   N/A  N/A   1146115      C   ...conda/envs/ag/bin/python3      366MiB |
|    4   N/A  N/A   1146179      C   ...conda/envs/ag/bin/python3      366MiB |
|    5   N/A  N/A   1145471      C   python3                           366MiB |
|    5   N/A  N/A   1145789      C   ...conda/envs/ag/bin/python3      366MiB |
|    5   N/A  N/A   1145856      C   ...conda/envs/ag/bin/python3      366MiB |
|    5   N/A  N/A   1145920      C   ...conda/envs/ag/bin/python3      366MiB |
|    5   N/A  N/A   1145984      C   ...conda/envs/ag/bin/python3      366MiB |
|    5   N/A  N/A   1146051      C   ...conda/envs/ag/bin/python3     7240MiB |
|    5   N/A  N/A   1146115      C   ...conda/envs/ag/bin/python3      366MiB |
|    5   N/A  N/A   1146179      C   ...conda/envs/ag/bin/python3      366MiB |
|    6   N/A  N/A   1145471      C   python3                           366MiB |
|    6   N/A  N/A   1145789      C   ...conda/envs/ag/bin/python3      366MiB |
|    6   N/A  N/A   1145856      C   ...conda/envs/ag/bin/python3      366MiB |
|    6   N/A  N/A   1145920      C   ...conda/envs/ag/bin/python3      366MiB |
|    6   N/A  N/A   1145984      C   ...conda/envs/ag/bin/python3      366MiB |
|    6   N/A  N/A   1146051      C   ...conda/envs/ag/bin/python3      366MiB |
|    6   N/A  N/A   1146115      C   ...conda/envs/ag/bin/python3     4282MiB |
|    6   N/A  N/A   1146179      C   ...conda/envs/ag/bin/python3      366MiB |
|    7   N/A  N/A   1145471      C   python3                           366MiB |
|    7   N/A  N/A   1145789      C   ...conda/envs/ag/bin/python3      366MiB |
|    7   N/A  N/A   1145856      C   ...conda/envs/ag/bin/python3      366MiB |
|    7   N/A  N/A   1145920      C   ...conda/envs/ag/bin/python3      366MiB |
|    7   N/A  N/A   1145984      C   ...conda/envs/ag/bin/python3      366MiB |
|    7   N/A  N/A   1146051      C   ...conda/envs/ag/bin/python3      366MiB |
|    7   N/A  N/A   1146115      C   ...conda/envs/ag/bin/python3      366MiB |
|    7   N/A  N/A   1146179      C   ...conda/envs/ag/bin/python3     4698MiB |
+-----------------------------------------------------------------------------+

```

ddp_spawn:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:16.0 Off |                    0 |
| N/A   35C    P0    67W / 300W |   2277MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:00:17.0 Off |                    0 |
| N/A   36C    P0    67W / 300W |   2323MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:00:18.0 Off |                    0 |
| N/A   36C    P0    66W / 300W |   2207MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:00:19.0 Off |                    0 |
| N/A   35C    P0    67W / 300W |   2215MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  Tesla V100-SXM2...  On   | 00000000:00:1A.0 Off |                    0 |
| N/A   36C    P0    68W / 300W |   2285MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  Tesla V100-SXM2...  On   | 00000000:00:1B.0 Off |                    0 |
| N/A   37C    P0    66W / 300W |   2305MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  Tesla V100-SXM2...  On   | 00000000:00:1C.0 Off |                    0 |
| N/A   36C    P0    67W / 300W |   2239MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  Tesla V100-SXM2...  On   | 00000000:00:1D.0 Off |                    0 |
| N/A   36C    P0    67W / 300W |   2237MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A   1155858      C   python3                           368MiB |
|    0   N/A  N/A   1156195      C   ...conda/envs/ag/bin/python3     1906MiB |
|    1   N/A  N/A   1155858      C   python3                           368MiB |
|    1   N/A  N/A   1156399      C   ...conda/envs/ag/bin/python3     1952MiB |
|    2   N/A  N/A   1155858      C   python3                           368MiB |
|    2   N/A  N/A   1156603      C   ...conda/envs/ag/bin/python3     1836MiB |
|    3   N/A  N/A   1155858      C   python3                           368MiB |
|    3   N/A  N/A   1156809      C   ...conda/envs/ag/bin/python3     1844MiB |
|    4   N/A  N/A   1155858      C   python3                           368MiB |
|    4   N/A  N/A   1157015      C   ...conda/envs/ag/bin/python3     1914MiB |
|    5   N/A  N/A   1155858      C   python3                           368MiB |
|    5   N/A  N/A   1157221      C   ...conda/envs/ag/bin/python3     1934MiB |
|    6   N/A  N/A   1155858      C   python3                           368MiB |
|    6   N/A  N/A   1157427      C   ...conda/envs/ag/bin/python3     1868MiB |
|    7   N/A  N/A   1155858      C   python3                           368MiB |
|    7   N/A  N/A   1157633      C   ...conda/envs/ag/bin/python3     1866MiB |
+-----------------------------------------------------------------------------+

```

### Environment

<details>                                                                                                        
  <summary>Current environment</summary>                                                                         
                                                                                                                 
* CUDA:                                                                                                          
        - GPU:                                                                                                   
                - Tesla V100-SXM2-32GB                                                                           
                - Tesla V100-SXM2-32GB                                                                           
                - Tesla V100-SXM2-32GB                                                                           
                - Tesla V100-SXM2-32GB                                                                           
                - Tesla V100-SXM2-32GB                                                                           
                - Tesla V100-SXM2-32GB                                                                           
                - Tesla V100-SXM2-32GB                                                                           
                - Tesla V100-SXM2-32GB                                                                           
        - available:         True                                                                                
        - version:           11.7                                                                                
* Lightning:                                                                                                     
        - lightning:         2.0.9.post0                                                                         
        - lightning-cloud:   0.5.42                                                                              
        - lightning-utilities: 0.9.0                                                                             
        - pytorch-lightning: 2.0.9.post0                                                                         
        - pytorch-metric-learning: 1.7.3                                                                         
        - torch:             2.0.1                                                                               
        - torchmetrics:      1.1.2                                                                               
        - torchvision:       0.15.2                                                                              
* Packages:                                                                                                      
        - absl-py:           2.0.0                                                                               
        - accelerate:        0.21.0                                                                              
        - addict:            2.4.0                                                                               
        - aiohttp:           3.8.6                                                                               
        - aiohttp-cors:      0.7.0                                                                               
        - aiosignal:         1.3.1                                                                               
        - aliyun-python-sdk-core: 2.14.0                                                                         
        - aliyun-python-sdk-kms: 2.16.2                                                                          
        - antlr4-python3-runtime: 4.9.3                                                                          
        - anyio:             3.7.1                                                                               
        - arrow:             1.3.0                                                                               
        - asttokens:         2.4.0                                                                               
        - async-timeout:     4.0.3                                                                               
        - attrs:             23.1.0                                                                              
        - autogluon:         0.8.3b20231016                                                                      
        - autogluon.common:  0.8.3b20231016                                                                      
        - autogluon.core:    0.8.3b20231016                                                                      
        - autogluon.eda:     0.8.3b20231016                                                                      
        - autogluon.features: 0.8.3b20231016                                                                     
        - autogluon.multimodal: 0.8.3b20231016                                                                   
        - autogluon.tabular: 0.8.3b20231016                                                                      
        - autogluon.timeseries: 0.8.3b20231016                                                                   
        - backcall:          0.2.0                                                                               
        - backoff:           2.2.1                                                                               
        - beautifulsoup4:    4.12.2                                                                              
        - black:             22.12.0                                                                             
        - blessed:           1.20.0                                                                              
        - blis:              0.7.11                                                                              
        - boto3:             1.28.64                                                                             
        - botocore:          1.31.64                                                                             
        - cachetools:        5.3.1                                                                               
        - catalogue:         2.0.10                                                                              
        - catboost:          1.2.2                                                                               
        - certifi:           2023.7.22                                                                           
        - cffi:              1.16.0                                                                              
        - charset-normalizer: 3.3.0                                                                              
        - click:             8.1.7                                                                               
        - cloudpathlib:      0.16.0                                                                              
        - cloudpickle:       3.0.0                                                                               
        - cmake:             3.27.7                                                                              
        - colorama:          0.4.6                                                                               
        - coloredlogs:       15.0.1                                                                              
        - colorful:          0.5.5                                                                               
        - combo:             0.1.3                                                                               
        - comm:              0.1.4                                                                               
        - confection:        0.1.3
        - contourpy:         1.1.1
        - crcmod:            1.7
        - croniter:          1.4.1
        - cryptography:      41.0.4
        - cycler:            0.12.1
        - cymem:             2.0.8
        - datasets:          2.14.5
        - dateutils:         0.6.12
        - decorator:         5.1.1
        - deepdiff:          6.6.0
        - defusedxml:        0.7.1
        - dill:              0.3.7
        - distlib:           0.3.7
        - evaluate:          0.4.1
        - exceptiongroup:    1.1.3
        - executing:         2.0.0
        - fastai:            2.7.13
        - fastapi:           0.103.2
        - fastcore:          1.5.29
        - fastdownload:      0.0.7
        - fastprogress:      1.0.3
        - filelock:          3.12.4
        - flaky:             3.7.0
        - flatbuffers:       23.5.26
        - fonttools:         4.43.1
        - frozenlist:        1.4.0
        - fsspec:            2023.6.0
        - future:            0.18.3
        - gdown:             4.7.1
        - gluonts:           0.13.6
        - google-api-core:   2.12.0
        - google-auth:       2.23.3
        - google-auth-oauthlib: 1.0.0
        - googleapis-common-protos: 1.61.0
        - gpustat:           1.1.1
        - graphviz:          0.20.1
        - grpcio:            1.59.0
        - h11:               0.14.0
        - huggingface-hub:   0.18.0
        - humanfriendly:     10.0
        - hyperopt:          0.2.7
        - idna:              3.4
        - imageio:           2.31.5
        - imodels:           1.3.18
        - importlib-metadata: 6.8.0
        - importlib-resources: 6.1.0
        - iniconfig:         2.0.0
        - inquirer:          3.1.3
        - ipython:           8.12.3
        - ipywidgets:        8.1.1
        - isort:             5.12.0
        - itsdangerous:      2.1.2
        - jedi:              0.19.1
        - jinja2:            3.1.2
        - jmespath:          0.10.0
        - joblib:            1.3.2
        - jsonschema:        4.17.3
        - jsonschema-specifications: 2023.7.1
        - jupyterlab-widgets: 3.0.9
        - kiwisolver:        1.4.5
        - langcodes:         3.3.0
        - lazy-loader:       0.3
        - lightgbm:          3.3.5
        - lightning:         2.0.9.post0
        - lightning-cloud:   0.5.42
        - lightning-utilities: 0.9.0
        - lit:               17.0.2
        - llvmlite:          0.41.0
        - markdown:          3.5
        - markdown-it-py:    3.0.0
        - markupsafe:        2.1.3
        - matplotlib:        3.6.3
        - matplotlib-inline: 0.1.6
        - mdurl:             0.1.2
        - missingno:         0.5.2
        - mlforecast:        0.9.3
        - mlxtend:           0.23.0
        - mmcv:              2.0.1
        - mmdet:             3.0.0
        - mmengine:          0.9.0
        - model-index:       0.1.11
        - mpmath:            1.3.0
        - msgpack:           1.0.7
        - multidict:         6.0.4
        - multiprocess:      0.70.15
        - murmurhash:        1.0.10
        - mypy:              1.6.0
        - mypy-extensions:   1.0.0
        - networkx:          3.1
        - nlpaug:            1.1.11
        - nltk:              3.8.1
        - nptyping:          2.4.1
        - numba:             0.58.0
        - numpy:             1.24.4
        - nvidia-cublas-cu11: 11.10.3.66
        - nvidia-cuda-cupti-cu11: 11.7.101
        - nvidia-cuda-nvrtc-cu11: 11.7.99
        - nvidia-cuda-runtime-cu11: 11.7.99
        - nvidia-cudnn-cu11: 8.5.0.96
        - nvidia-cufft-cu11: 10.9.0.58
        - nvidia-curand-cu11: 10.2.10.91
        - nvidia-cusolver-cu11: 11.4.0.1
        - nvidia-cusparse-cu11: 11.7.4.91
        - nvidia-ml-py:      12.535.108
        - nvidia-nccl-cu11:  2.14.3
        - nvidia-nvtx-cu11:  11.7.91
        - oauthlib:          3.2.2
        - omegaconf:         2.2.3
        - onnx:              1.13.1
        - onnxconverter-common: 1.14.0
        - onnxruntime-gpu:   1.15.1
        - opencensus:        0.11.3
        - opencensus-context: 0.1.3
        - opencv-python:     4.8.1.78
        - opendatalab:       0.0.10
        - openmim:           0.3.9
        - openxlab:          0.0.27
        - ordered-set:       4.1.0
        - oss2:              2.17.0
        - packaging:         23.2
        - pandas:            2.1.1
        - parso:             0.8.3
        - pathspec:          0.11.2
        - patsy:             0.5.3
        - pexpect:           4.8.0
        - phik:              0.12.3
        - pickleshare:       0.7.5
        - pillow:            9.5.0
        - pip:               23.3
        - platformdirs:      3.11.0
        - plotly:            5.17.0
        - pluggy:            1.3.0
        - preshed:           3.0.9
        - prometheus-client: 0.17.1
        - prompt-toolkit:    3.0.39
        - protobuf:          3.20.2
        - psutil:            5.9.6
        - ptyprocess:        0.7.0
        - pure-eval:         0.2.2
        - py-spy:            0.3.14
        - py4j:              0.10.9.7
        - pyarrow:           13.0.0
        - pyasn1:            0.5.0
        - pyasn1-modules:    0.3.0
        - pycocotools:       2.0.7
        - pycparser:         2.21
        - pycryptodome:      3.19.0
        - pydantic:          1.10.13
        - pygments:          2.16.1
        - pyjwt:             2.8.0
        - pymupdf:           1.21.1
        - pyod:              1.0.9
        - pyparsing:         3.1.1
        - pyrsistent:        0.19.3
        - pysocks:           1.7.1
        - pytesseract:       0.3.10
        - pytest:            7.4.2
        - pytest-mypy:       0.10.3
        - pytest-timeout:    2.2.0
        - python-dateutil:   2.8.2
        - python-editor:     1.0.4
        - python-multipart:  0.0.6
        - pytorch-lightning: 2.0.9.post0
        - pytorch-metric-learning: 1.7.3
        - pytz:              2023.3.post1
        - pywavelets:        1.4.1
        - pyyaml:            6.0.1
        - ray:               2.6.3
        - readchar:          4.0.5
        - referencing:       0.30.2
        - regex:             2023.10.3
        - requests:          2.28.2
        - requests-oauthlib: 1.3.1
        - responses:         0.18.0
        - rich:              13.4.2
        - rpds-py:           0.10.6
        - rsa:               4.9
        - ruff:              0.1.0
        - s3transfer:        0.7.0
        - safetensors:       0.4.0
        - scikit-image:      0.20.0
        - scikit-learn:      1.3.1
        - scipy:             1.9.1
        - seaborn:           0.12.2
        - sentencepiece:     0.1.99
        - seqeval:           1.2.2
        - setuptools:        60.2.0
        - shap:              0.41.0
        - shapely:           2.0.2
        - six:               1.16.0
        - skl2onnx:          1.15.0
        - slicer:            0.0.7
        - smart-open:        6.4.0
        - sniffio:           1.3.0
        - soupsieve:         2.5
        - spacy:             3.7.2
        - spacy-legacy:      3.0.12
        - spacy-loggers:     1.0.5
        - srsly:             2.4.8
        - stack-data:        0.6.3
        - starlette:         0.27.0
        - starsessions:      1.3.0
        - statsforecast:     1.4.0
        - statsmodels:       0.14.0
        - suod:              0.0.9
        - sympy:             1.12
        - tabpfn:            0.1.9
        - tabulate:          0.9.0
        - tenacity:          8.2.3
        - tensorboard:       2.14.1
        - tensorboard-data-server: 0.7.1
        - tensorboardx:      2.6.2.2
        - tensorrt:          8.5.3.1
        - termcolor:         2.3.0
        - terminaltables:    3.1.10
        - text-unidecode:    1.3
        - thinc:             8.2.1
        - threadpoolctl:     3.2.0
        - tifffile:          2023.9.26
        - timm:              0.9.7
        - tokenizers:        0.13.3
        - tomli:             2.0.1
        - toolz:             0.12.0
        - torch:             2.0.1
        - torchmetrics:      1.1.2
        - torchvision:       0.15.2
        - tqdm:              4.65.2
        - traitlets:         5.11.2
        - transformers:      4.31.0
        - triton:            2.0.0
        - typer:             0.9.0
        - types-python-dateutil: 2.8.19.14
        - types-requests:    2.31.0.6
        - types-setuptools:  68.2.0.0
        - types-urllib3:     1.26.25.14
        - typing-extensions: 4.8.0
        - tzdata:            2023.3
        - ujson:             5.8.0
        - urllib3:           1.26.17
        - uvicorn:           0.23.2
        - virtualenv:        20.21.0
        - vowpalwabbit:      9.8.0
        - wasabi:            1.1.2
        - wcwidth:           0.2.8
        - weasel:            0.3.3
        - websocket-client:  1.6.4
        - websockets:        11.0.3
        - werkzeug:          3.0.0
        - wheel:             0.41.2
        - widgetsnbextension: 4.0.9
        - window-ops:        0.0.14
        - xgboost:           1.7.6
        - xxhash:            3.4.1
        - yapf:              0.40.2
        - yarl:              1.9.2
        - yellowbrick:       1.5
        - zipp:              3.17.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.9.18
        - release:           5.15.0-1036-aws
        - version:           #40~20.04.1-Ubuntu SMP Mon Apr 24 00:21:13 UTC 2023

</details>

cc @justusschock @awaelchli

**Comment by awaelchli** [comment]
Hi @FANGAreNotGnu 
The example code is quite complex, sorry I don't have the bandwidth to debug it. The memory imbalance could be explained if some of your code is calling `.cuda()` or `.to()` manually placing the model on the wrong device.

I searched through the code base and found a few occurrences:

https://github.com/search?q=repo:autogluon/autogluon%20cuda()&type=code

And if you could also make the example a bit more minimal so that we can reproduce it shows the issue with Lightning, that would be very helpful.

**Comment by FANGAreNotGnu** [comment]
Thanks for your advice!
I found that there are three sources of the extra GPU usage (in our case):
    1. torch.cuda.mem_get_info
    2. lightning.pytorch.accelerators.find_usable_cuda_devices
    3. the line `model.to(device).eval()` in our realtime inference implementation.
