### ISSUE TITLE
Can't override Trainer defaults via env variables for LightningCLI

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#18874]
### Bug description

Using the env vars `PL_TRAINER_...` to override trainer defaults doesn't work if you are using the LightningCLI. This is because the cli handles the defaults differently and prioritizes them over the env variable. 

I need to make the logic to determine these settings consistent with how we do it in Fabric. 

### What version are you seeing the problem on?

v2.1

### How to reproduce the bug

```python
I will immediately work on it and know how to repro/fix it.
```

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @justusschock @awaelchli

**Comment by carmocca** [comment]
The CLI uses its own environment variables: https://lightning.ai/docs/pytorch/stable/cli/lightning_cli_advanced_2.html#run-from-environment-variables-directly

**Comment by awaelchli** [comment]
Good to know @carmocca. This feature is only enabled when you explicitly pass `parser_kwargs={"default_env": True}` to the CLI. For the fix I took a different approach now, because the env vars need to apply without the user having to change the code.
