### ISSUE TITLE
ModuleNotFoundError: No module named 'lightning' in lightning container image

### ISSUE THREAD

**Issue by GuyPozner** [Lightning-AI/lightning#18890]
### Bug description

`lightning.pytorch` module is installed in lightning container images as pytorch_lightning, thus it is not compatible with the documentation. 

In order for import to work in a container image, the import should be of the following form:

```python
from lightning.pytorch.loggers import CSVLogger
```

While the documentation states:

```python
from pytorch_lightning.loggers import CSVLogger
```

### What version are you seeing the problem on?

v2.1

### How to reproduce the bug

```python
docker run -it --rm pytorchlightning/pytorch_lightning:latest-py3.10-torch2.0-cuda12.0.1
python -c "from lightning.pytorch.loggers import CSVLogger"
```

### Error messages and logs

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lightning'
```

### Environment

<details>
  <summary>Current environment</summary>

* CUDA:
        - GPU:               None
        - available:         False
        - version:           11.7
* Lightning:
        - lightning-utilities: 0.9.0
        - pytorch-lightning: 2.1.0rc0
        - torch:             2.0.1
        - torchmetrics:      1.0.3
* Packages:
        - absl-py:           2.0.0
        - aiohttp:           3.8.5
        - aiosignal:         1.3.1
        - antlr4-python3-runtime: 4.9.3
        - anyio:             3.7.1
        - async-timeout:     4.0.3
        - attrs:             23.1.0
        - cachetools:        5.3.1
        - certifi:           2019.11.28
        - chardet:           3.0.4
        - charset-normalizer: 3.3.0
        - click:             8.1.7
        - cloudpickle:       2.2.1
        - cmake:             3.27.6
        - coloredlogs:       15.0.1
        - contourpy:         1.1.1
        - coverage:          7.3.1
        - cycler:            0.12.0
        - dbus-python:       1.2.16
        - deepspeed:         0.9.3
        - docstring-parser:  0.15
        - exceptiongroup:    1.1.3
        - fastapi:           0.103.2
        - filelock:          3.12.4
        - flatbuffers:       23.5.26
        - fonttools:         4.43.0
        - frozenlist:        1.4.0
        - fsspec:            2023.9.2
        - google-auth:       2.23.2
        - google-auth-oauthlib: 1.0.0
        - grpcio:            1.59.0
        - h11:               0.14.0
        - hjson:             3.1.0
        - humanfriendly:     10.0
        - hydra-core:        1.3.2
        - idna:              2.8
        - importlib-resources: 6.1.0
        - iniconfig:         2.0.0
        - jinja2:            3.1.2
        - joblib:            1.3.2
        - jsonargparse:      4.25.0
        - kiwisolver:        1.4.5
        - lightning-utilities: 0.9.0
        - lit:               17.0.2
        - markdown:          3.4.4
        - markdown-it-py:    3.0.0
        - markupsafe:        2.1.3
        - matplotlib:        3.7.3
        - mdurl:             0.1.2
        - mpmath:            1.3.0
        - multidict:         6.0.4
        - networkx:          3.1
        - ninja:             1.11.1
        - numpy:             1.26.0
        - nvidia-cublas-cu11: 11.10.3.66
        - nvidia-cuda-cupti-cu11: 11.7.101
        - nvidia-cuda-nvrtc-cu11: 11.7.99
        - nvidia-cuda-runtime-cu11: 11.7.99
        - nvidia-cudnn-cu11: 8.5.0.96
        - nvidia-cufft-cu11: 10.9.0.58
        - nvidia-curand-cu11: 10.2.10.91
        - nvidia-cusolver-cu11: 11.4.0.1
        - nvidia-cusparse-cu11: 11.7.4.91
        - nvidia-nccl-cu11:  2.14.3
        - nvidia-nvtx-cu11:  11.7.91
        - oauthlib:          3.2.2
        - omegaconf:         2.3.0
        - onnx:              1.14.1
        - onnxruntime:       1.16.0
        - packaging:         23.1
        - pandas:            2.1.1
        - pillow:            10.0.1
        - pip:               23.2.1
        - pluggy:            1.3.0
        - protobuf:          4.24.3
        - psutil:            5.9.5
        - py-cpuinfo:        9.0.0
        - pyasn1:            0.5.0
        - pyasn1-modules:    0.3.0
        - pydantic:          1.10.13
        - pygments:          2.16.1
        - pygobject:         3.36.0
        - pyparsing:         3.1.1
        - pytest:            7.4.0
        - pytest-cov:        4.1.0
        - pytest-random-order: 1.1.0
        - pytest-rerunfailures: 12.0
        - pytest-timeout:    2.1.0
        - python-apt:        2.0.1+ubuntu0.20.4.1
        - python-dateutil:   2.8.2
        - pytorch-lightning: 2.1.0rc0
        - pytz:              2023.3.post1
        - pyyaml:            6.0.1
        - requests:          2.22.0
        - requests-oauthlib: 1.3.1
        - requests-unixsocket: 0.2.0
        - rich:              13.5.3
        - rsa:               4.9
        - scikit-learn:      1.3.1
        - scipy:             1.11.3
        - setuptools:        59.5.0
        - six:               1.14.0
        - sniffio:           1.3.0
        - starlette:         0.27.0
        - sympy:             1.12
        - tensorboard:       2.14.1
        - tensorboard-data-server: 0.7.1
        - tensorboardx:      2.6.2.2
        - threadpoolctl:     3.2.0
        - tomli:             2.0.1
        - torch:             2.0.1
        - torchmetrics:      1.0.3
        - tqdm:              4.66.1
        - triton:            2.0.0
        - typeshed-client:   2.4.0
        - typing-extensions: 4.7.1
        - tzdata:            2023.3
        - urllib3:           1.25.8
        - uvicorn:           0.23.2
        - werkzeug:          3.0.0
        - wget:              3.2
        - wheel:             0.41.2
        - yarl:              1.9.2
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - 
        - processor:         x86_64
        - python:            3.10.13
        - release:           5.3.0-28-generic
        - version:           #30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020

</details>

**Comment by awaelchli** [comment]
Hey @GuyPozner 

To use the `import lightning.x.y` import, you need to install the lightning package: `pip install lightning`
If you want to use the `import pytorch_lightning.x.y` style, you need to install `pip install pytorch-lightning`

You can't mix and match them. Our documentation exclusively uses the new package imports with lightning. That's the new and recommended way.

**Comment by GuyPozner** [comment]
Hi @awaelchli,
Thanks for the fast response, I understood that. What I am thinking, is that if this is the recommended way to import, it should work as expected with the containers images that gets released. what do you think? have you reproduced the issue?

**Comment by awaelchli** [comment]
Sorry, which container images are you talking about?

**Comment by GuyPozner** [comment]
this container image: pytorchlightning/pytorch_lightning:latest-py3.10-torch2.0-cuda12.0.1

But I think that this is true for every container image.
