### ISSUE TITLE
TPU FSDP support for Fabric requires major refactoring of training script(s)

### ISSUE THREAD

**Issue by fabienGenhealth** [Lightning-AI/lightning#18926]
### Outline & Motivation

Looking into porting a Fabric training script that works with FSDP on GPUs to TPUs. The script is written with the Fabric API, and I was hoping that minimal changes would support running training with FSDP on TPUs. I've resolved a few problems and can now get to the point where Fabric complains about:

`TypeError: To use the `XLAFSDPStrategy` strategy, `.launch()` needs to be called with a function that contains the code to launch in processes.`

For FSDP on NCCL/CUDA, the script is started with torchrun, which creates the different processes, so the code is not organized in a function I could give to the fabric.launch() method. Refactoring is painful because of many variables defined in local scope, some of them which cannot be pickled. 

I assume that it is quite common to use fabric.launch() without function arguments across the fabric user base (I had not realized the method accepted a function after reading many tutorials and docs).

### Pitch

Would it be possible to support the launch method with no argument for FSDP TPU when the training script has already been started in multiple processes, or does XLA training require additional coordination between the processes that only a fabric process spawn can support?

cc @justusschock @awaelchli

**Comment by carmocca** [comment]
This restriction would be lifted with #18335. But it's unavoidable until then because XLA requires spawning processes.
I'll go ahead and close this, but feel free to track #18335 if rewriting into a function is a no-go for you.
