### ISSUE TITLE
ModelCheckpoint filename delimiters not working as expected

### ISSUE THREAD

**Issue by Anjum48** [Lightning-AI/lightning#18956]
### Bug description

In https://github.com/Lightning-AI/lightning/issues/17825 I raised the requirement to change the default delimiter for filenames

@giorgioskij kindly submitted a PR (https://github.com/Lightning-AI/lightning/pull/17999) to fix this however this is not working as expected.

The saved checkpoints still contain an "=" sign.

I think this issue is caused by `_format_checkpoint_name` being a `classmethod`: https://github.com/Lightning-AI/lightning/blob/3b05d833cc1ff7a40d175b9bce700905b8feeb1a/src/lightning/pytorch/callbacks/model_checkpoint.py#L518-L553

This means that `CHECKPOINT_EQUALS_CHAR ` will always default back to "=". The unit test fails to pick this up as is is calling `_format_checkpoint_name` directly:
https://github.com/Lightning-AI/lightning/blob/b30f1a995d58c2a1b5b75e98132276aa0514e850/tests/tests_pytorch/checkpointing/test_model_checkpoint.py#L434

Removing the `@classmethod` decorator and changing all `cls` to `self` fixes the issue for me

### What version are you seeing the problem on?

v2.1

### How to reproduce the bug

```python
checkpoint_callback = ModelCheckpoint(
    monitor='val_loss',
    dirpath='my/path/',
    filename='sample-mnist-{epoch:02d}-{val_loss:.2f}'
checkpoint_callback.CHECKPOINT_EQUALS_CHAR = ";"

trainer = Trainer(callbacks=[checkpoint_callback])
```

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @borda @carmocca @awaelchli

**Comment by Anjum48** [comment]
Am I using it incorrectly? What is the correct way of setting the property?

**Comment by Anjum48** [comment]
Ok I think I've got it.

The property is set using:
```python
ModelCheckpoint.CHECKPOINT_EQUALS_CHAR = ";"
checkpoint_callback = ModelCheckpoint(
    monitor='val_loss',
    dirpath='my/path/',
    filename='sample-mnist-{epoch:02d}-{val_loss:.2f}'
```

This is different to the NOTE section in the documentation https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html

**Comment by awaelchli** [comment]
As an immediate action, I suggest changing the docs note to use the class rather than the instance. Then as a next step discuss whether we just make `_format_checkpoint_name` an instance method for simplicity.
