### ISSUE TITLE
cast to float32 or float64 tensor when passing scalar to self.log

### ISSUE THREAD

**Issue by MF-FOOM** [Lightning-AI/lightning#18984]
### Bug description

https://github.com/Lightning-AI/lightning/pull/18686 made it such that all `ResultMetric` values are stored at `float32` or higher precision.

However, values passed in as floats to `self.log` still get auto-casted to a low precision type (if that's the default precision) via [`__to_tensor`](https://github.com/Lightning-AI/lightning/blob/1c86011dabaca211386be6acbee402c7bbda1f8c/src/lightning/pytorch/core/module.py#L454). This means that even though the internal result metric representation is precise, the values can loose precision before even reaching `ResultMetric`.

I'd suggest we modify `__to_tensor` to use a function like this (as introduced in https://github.com/Lightning-AI/lightning/pull/18686) to determine and set the dtype:

```py
def _get_default_dtype() -> torch.dtype:
    """The default dtype for new tensors, but no lower than float32."""
    dtype = torch.get_default_dtype()
    return dtype if dtype in (torch.float32, torch.float64) else torch.float32
```

### What version are you seeing the problem on?

v2.1

### Error messages and logs

N/A

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @carmocca

**Comment by MF-FOOM** [comment]
bump on this? i'm happy to implement, just want approval to go ahead with this

**Comment by carmocca** [comment]
Please go ahead @MF-FOOM! Sorry for the wait
