### ISSUE TITLE
Remove unnecessary `torch.cuda.manual_seed_all()` in `seed_everything()`

### ISSUE THREAD

**Issue by JalinWang** [Lightning-AI/lightning#19033]
### Outline & Motivation

In the function  `seed_everything()`, there is a call to `torch.cuda.manual_seed_all()`.

https://github.com/Lightning-AI/lightning/blob/4789905880fa11b96e761e321a4ad97c40d007fd/src/lightning/fabric/utilities/seed.py#L58-L59

However, I think we should remove it because:
1. We can't assume all the users have CUDA devices. Some will run on Apple Chip which requires `torch.mps.manual_seed(seed)`.
2. `torch.manual_seed()` has already done this: https://github.com/pytorch/pytorch/blob/140c54e6ccc5e97f1b7f1e0fcd3d8c6af7dd2ab2/torch/random.py#L39-L44
![image](https://github.com/Lightning-AI/lightning/assets/20621784/497571fd-fc5b-4274-aa4f-6ffe0d33b459)

cc @justusschock @awaelchli

**Comment by awaelchli** [comment]
@JalinWang Feel free to open a PR for this. For mps we will still have to call it manually because that was only recently added in PyTorch.

**Comment by JalinWang** [comment]
@awaelchli thanks for the timely reply. You are right this is a newly added feature in Pytorch( ~9 months )
![image](https://github.com/Lightning-AI/lightning/assets/20621784/5709b379-dc1c-4327-bd83-219a7977f747)
But I think there is no need to add `torch.mps.manual_seed()` here for setting MPS seed came with other parts of [MPS support in pytorch](https://github.com/pytorch/pytorch/commit/bdd8f518d7147e795d339a06ed895ef4df46b6f7). Users who want to run on Apple Chips must use the newer pytorch :)
