### ISSUE TITLE
Loading nn.Module from checkpoint doc fix

### ISSUE THREAD

**Issue by montehoover** [Lightning-AI/lightning#19047]
### 📚 Documentation

https://lightning.ai/docs/pytorch/stable/common/checkpointing_basic.html#nn-module-from-checkpoint shows the ability to directly retrieve nn.Module weights from a checkpoint if the module is given as an argument in the  LightningModule constructor. For example, it shows the following code for `encoder` and `decoder` as arguments:

```
checkpoint = torch.load(CKPT_PATH)
encoder_weights = checkpoint["encoder"]
decoder_weights = checkpoint["decoder"]
```

However, when I try to reproduce this I get the following error:
```
Traceback (most recent call last):
  File "C:\Users\monte\code\scratch\lightning_example.py", line 63, in <module>
    encoder_weights = checkpoint["encoder"]
KeyError: 'encoder'
```

It runs correctly if I add `self.save_hyperparameters()` to the constructor and update the checkpoint loading to be:

```
checkpoint = torch.load(CKPT_PATH)
encoder_weights = checkpoint["hyper_parameters"]["encoder"]
decoder_weights = checkpoint["hyper_parameters"]["decoder"]
```

Should the documentation be updated? 

Also, if there is documentation giving advice on the simplest way to take a pure Pytorch model, train it using Lightning, and get weights back for use in pure Pytorch I'd be interested in it. Thanks!

cc @borda

**Comment by awaelchli** [comment]
@montehoover I linked a pull request that fixes this example. The code should be:

```py
encoder_weights = {k: v for k, v in checkpoint["state_dict"] if k.startswith("encoder.")}
decoder_weights = {k: v for k, v in checkpoint["state_dict"] if k.startswith("decoder.")}
```
if we want to achieve what is described in the text.

**Comment by montehoover** [comment]
Thanks!
