### ISSUE TITLE
MPIEnvironment fails for MPI multi-node training at comm gather step of worker nodes

### ISSUE THREAD

**Issue by sohrabi1** [Lightning-AI/lightning#19062]
### Bug description

I am trying to do multi-node training using MPI and I get an error in [this line](https://github.com/Lightning-AI/lightning/blob/bf54a1de776c2fb4b6773349010cc42f516e0cac/src/lightning/fabric/plugins/environments/mpi.py#L108C40-L108C40) when mpi4py library gathers hostnames across machines.

```
    unique_hosts = sorted(set(all_hostnames))
TypeError: 'NoneType' object is not iterable
```

As far as I understand mpi4py comm would only give back the results of gather calls to the first process, so it makes sense to me that this function would fail on a worker node as gather will return None for all of them (even though hostname is actually discovered).
As the results are then communicated to all nodes in the following `self._comm_world.bcast(unique_hosts, root=0)` call, I could patch it for now by changing the code like this:

```python
        if all_hostnames:
            unique_hosts = sorted(set(all_hostnames))
        else:
            unique_hosts = []
```

### What version are you seeing the problem on?

v2.1

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
Hey @sohrabi1 I think your fix is correct! Would you be open to send a pull request with this change?

**Comment by sohrabi1** [comment]
Thanks a lot for the quick PR and merge! (and sorry for being offline).
