### ISSUE TITLE
Add methods for reset dataloader during custom training

### ISSUE THREAD

**Issue by rwbfd** [Lightning-AI/lightning#5302]
## 🚀 Feature
In the current version, there is no way (unless some hacking) to reattach new data loaders to the appropriate case. Such methods are needed for reinforcement learning. 

### Motivation

In reinforcement learning, it is very common to generate new data during the training process. However, currently, I see no way to attach these new data so that they can become proper ones. For example, if I am using TPU, after gathering the data, I might want to make it a PyTorch XLA type data loader. This can be done manually. However, this is rather against the design logic of PyTorch Lightning. In fact, in the PyTorch Lightning Bolt libraries, I believe such problems already occurs in their implementation. Since they are using a relatively simpler case, it is not yet that troublesome. However, once I try to add experience replay and self imitation learning, using their methods would be impossible.

I have implemented a version that can be found [my own fork](https://github.com/rwbfd/pytorch-lightning.git). However, this is pretty ugly as I have to attach the trainer to the LightningModule. It might also cause bugs. My big concern is that whether I have forgotten some post check steps. 

In any case, I think such a feature is essential for RL researchers, and I am looking forward to some suggestions.

**Comment by rohitgr7** [comment]
you can use `reload_dataloaders_every_epoch=True` flag in Trainer

**Comment by rwbfd** [comment]
@rohitgr7 But it is not even during an epoch. In reinforcement learning, it can happen that inside the big loop you have a small loop that uses different replay buffers, and that is only in one step.

**Comment by tchaton** [comment]
Hey @rwbfd,

Yes, it seems Lightning is lacking there. 
From your own fork, I can see you added `attach_data`. However, you didn't seem to use in the code.
Would you showing an example of where and how you would like to change datasets ?

Also, you would mind making a small PR with your tpu changes ?

Best,
T.C

**Comment by rwbfd** [comment]
Hey @tchaton, 

I will be glad to. However, it will take some time to test. Then I will make the PR. 

Also, I am changing some codes for PyTorch XLA. Hope that will help as well.

**Comment by tchaton** [comment]
Hey @rwbfd,

Check out this example: https://github.com/PyTorchLightning/pytorch-lightning/pull/5394/files

It is built out of https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/pl_bolts/datamodules/experience_source.py.

It should work just fine for your use-case.

Best,
T.C

**Comment by rwbfd** [comment]
@tchaton That is the exact example I check. However, my implementation is more complex. Therefore, it will not help me. In any case, I will try to work out a new version and the send a small PR.

**Comment by edenlightning** [comment]
Hey there @rwbfd! Any help needed?

**Comment by carmocca** [comment]
`loop.setup_data()` exists now (use at your own discretion) and for complex loop management, we suggest Fabric: https://lightning.ai/docs/fabric/stable/
