### ISSUE TITLE
Should truncated_bptt_steps take effect during validation phase?

### ISSUE THREAD

**Issue by colllin** [Lightning-AI/lightning#6539]
## 🐛 Bug

It appears that the Trainer flag `truncated_bptt_steps` doesn’t affect the validation phase.  Should it?  The problem I’m running into is that I need truncated_bptt_steps to virtually increase the length of the sequence I can fit into my GPU memory, but this purpose is defeated when the validation step doesn’t also make use of truncated_bptt_steps — in this case my memory is limited by my validation step, which attempts to process the full sequence in-memory.  

Is there a reason why validation step shouldn’t also make use of the truncated_bptt_steps flag?  Or is this just not finished yet?  I could probably manage to adapt the evaluation_loop code to copy the training_loop code regarding truncated_bptt_steps.  Would this be an acceptable addition?

See also: https://github.com/PyTorchLightning/pytorch-lightning/discussions/6483

## Please reproduce using the BoringModel

https://colab.research.google.com/drive/1JYAVdMy-UPg0Rzwpo3T9A-FmwrOdi_aR?usp=sharing

### Expected behavior

I expected the validation loop to also split the batch along the time dimension according to truncated_bptt_steps.

**Comment by edenlightning** [comment]
@ananyahjha93

**Comment by RomeroBarata** [comment]
I'm facing the same issue. Any updates on that?
