### ISSUE TITLE
[RFC] Support for Sharded Saving/Loading 

### ISSUE THREAD

**Issue by SeanNaren** [Lightning-AI/lightning#6691]
## 🚀 Feature

When integrating DeepSpeed/Fully Sharded, parameters are sharded across processes. This means when saving unless we consolidate onto one rank, there is the need to save on multiple processes.

In cases where the model is massive, saving to one rank is unfeasible. This happens on a per training type case (DeepSpeed/FSDP will have the option to save to one file from rank 0, or each process saves their own file). 

### Potential Solutions

Allow the TrainingType plugin to control the save checkpoint logic and the restore from checkpoint logic as should be done here: https://github.com/PyTorchLightning/pytorch-lightning/pull/6689 and in a follow-up PR

Unfortunately with the above approach when doing a load from sharded states, it's impossible to control how to load till distributed communications have been set up:

```python
model = BoringModel()
trainer = Trainer(plugins='ddp_fully_sharded')
trainer.fit(model, dm)

# In a later session

# Fails because we can't load a sharded set of checkpoints unless distributed setup is complete
BoringModel.load_from_checkpoint('my_model')

# Works because we can set up distributed communication and load a sharded state
trainer = Trainer(plugins='ddp_fully_sharded')
trainer.predict(model, dm)
```

I'm unsure of other solutions outside of using the Trainer, which limits our ability to run inference/test. I think we can try to limit as much exposure the TrainingTypePlugin has, so it's only responsible for saving/final changes to the checkpoint but this still ties model saving to the plugin which may be not preferred. 

cc @ananthsub @carmocca @tchaton

**Comment by min-xu-ai** [comment]
This is a really hard problem. Some issues to consider:

- optimizer state is also sharded, may need to be handled specially
- not all layers are always sharded the same way in nested FSDP
- sharded state is harder to work with when you run train and eval with different number of workers
- let rank 0 handling checkpoint is likely OK if the model size is not too huge, but proper care needs to be taken to avoid OOM on it.

my current thinking is still let rank0 handle checkpointing and assume model is not too huge. but that doesn't change the fact communicate needs to be setup before checkpoint load since in order to avoid OOM, we need to stream the data to all workers as we read it.

**Comment by SeanNaren** [comment]
Thanks @min-xu-ai, valuable info!

I think general consensus is to prefer saving everything on rank 0 first, and iterate towards sharded state.

This will still require the training type plugin being the source of saving. Fully sharded is slightly simpler as we can just use the `on_save` hook to modify the state dictionary, however for DeepSpeed we'll require overriding the save function itself.

**Comment by leezu** [comment]
> optimizer state is also sharded, may need to be handled specially

The checkpoint connector calls `deepspeed.runtime.zero.stage2.FP16_DeepSpeedZeroOptimizer.load_state_dict` which expects a list of states based on the state partitioning. But the loaded states only contain a single dictionary corresponding only to a single state partition used during the save-run.

https://github.com/PyTorchLightning/pytorch-lightning/blob/28103c67c2baa5810d8e76f77176361e3f61076b/pytorch_lightning/trainer/connectors/checkpoint_connector.py#L179-L182

https://github.com/microsoft/DeepSpeed/blob/dad26428e3f28898b8d0f5ace1b3df3e6db8f8e8/deepspeed/runtime/zero/stage2.py#L1828-L1837

which fails with `KeyError: 0` when trying to restore the loss_scaler.

> I think general consensus is to prefer saving everything on rank 0 first, and iterate towards sharded state. I think for DeepSpeed we'll do the reverse due to the current trajectory.

@SeanNaren would it be sensible to add checks on the pytorch-lightning side to fail early if pytorch-lightning attempts to restore deepspeed optimizer states? I guess below function is only applicable to zero3 and can't help here?

https://github.com/PyTorchLightning/pytorch-lightning/blob/28103c67c2baa5810d8e76f77176361e3f61076b/pytorch_lightning/plugins/training_type/deepspeed.py#L485-L488
