### ISSUE TITLE
Improve typing coverage

### ISSUE THREAD

**Issue by tchaton** [Lightning-AI/lightning#7037]
**Please make one PR per file!**

The list of pending files is can be found below here

https://github.com/Lightning-AI/lightning/blob/master/pyproject.toml#L39-L43

cc @borda @justusschock @awaelchli @akihironitta @rohitgr7

**Comment by Borda** [comment]
Duplicate to #5023

**Comment by akihironitta** [comment]
https://github.com/PyTorchLightning/pytorch-lightning/pull/7035#issue-615794299

> Open for discussion: Should we also type the tests? I don't think we have to!

I don't think we need type annotations in the tests, but we should run mypy to check if variables/functions of the package are correctly typed. What do you think?

**Comment by stancld** [comment]
After the chat with Eden, I'll tackle lightning.utilities :)

**Comment by stancld** [comment]
Hello @tchaton, I noticed new information about making one PR per file was added to the first comment. As I've been dealing with some mypy issues, my PR #7218 has become quite heavy. Is it, therefore, appropriate to close this PR, though already with a few reviews given, and open new ones separately for each file? Thanks :)

**Comment by otaj** [comment]
@kingjuno, you're more than welcome to help! We are closing this issue in favor of #13445  in order to promote better visibility, please feel free to comment there.
