### ISSUE TITLE
TensorBoardLogger does not store hparams inside a dataclass

### ISSUE THREAD

**Issue by sebp** [Lightning-AI/lightning#7568]
## Please reproduce using the BoringModel

When hyper-parameters are wrapped by a `dataclass` and passed to a LightningModule, the `TensorBoardLogger` will store a string representation of the entire `dataclass` as one hyper-parameter instead of the contents inside the `dataclass`:

![tensorboard](https://user-images.githubusercontent.com/74460/118401472-66e9b600-b655-11eb-8fa5-f19b20f57d78.png)

### To Reproduce

Use following [notebook](https://colab.research.google.com/drive/1DFqkyzt-qL5yyZ_IWDpcZV3BGZNVFzWA?usp=sharing)

### Expected behavior

The hyper-params should be unwrapped, as is done for dictionaries, such that the HPARAMS tab in Tensorboard shows individual hyper-params, e.g.:
- `model/n_inputs`
- `model/n_outputs`
- `training/learning_rate`

Since a `dataclass` can be converted to a dict via `datalcasses.asdict`, it shouldn't be too hard to add a another case to 
[LightningLoggerBase._flatten_dict](https://github.com/PyTorchLightning/pytorch-lightning/blob/e126649d19e85c449b007008361f10374878f2f4/pytorch_lightning/loggers/base.py#L240)

### Environment

* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.8.1+cu101
	- pytorch-lightning: 1.3.1
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.10
	- version:           #1 SMP Tue Apr 20 19:55:43 PDT 2021

**Comment by justusschock** [comment]
Hi @sebp ,

This kind of works as expected. Even converting them to a dict wouldn't really help since tensorboard does not allow nested dicts. The way it is designed is that `self.save_hyperparameters` saves a string representation of every argument you pass to it (or the `__init__` if you pass no arguments to `save_hyperparameters`). This ensures we only have dicts of depth 1. When automatically converting, you would still have nested dicts as hparams.

**Comment by sebp** [comment]
It does work for nested dicts, because the dict gets flattened before 
writing the results to TensorBoard, so {"model: {"n_outputs": 2, 
"n_inputs": 32}} gets logged at "model/n_outputs" _and_ "model/n_inputs".

See 
https://github.com/PyTorchLightning/pytorch-lightning/blob/aaccbeea2beb3b903428643d2ee520d2dd05b348/pytorch_lightning/loggers/tensorboard.py#L175

**Comment by justusschock** [comment]
Okay, Sorry I missed that. When I tried it with manually converting the data classes to dicts before it did not work, but I agree, that this is a use case we could integrate. Want to open a PR for that?
