### ISSUE TITLE
ProcessExitedException: process 1 terminated with signal SIGKILL

### ISSUE THREAD

**Issue by talhaanwarch** [Lightning-AI/lightning#7989]
I am trying to train BERT model for classification on TPU.
Here is colab link
https://colab.research.google.com/gist/talhaanwarch/3c7475bee6e1d4d032f7325ccc898a2a/urdunews-pl.ipynb?authuser=3
In this code I am defining transformer model into `PL` structure. This gives me `ProcessExitedException: process 1 terminated with signal SIGKILL` error.
If I define transformer out of PL structure, (like I can call it where I have called tokenizer), I did not get any error. but I could not specify 8 TPU cores. I have to choose one TPU core. The process becomes slow, but I can choose a large batch size.
When I define it in PL structure, I cant set large batch size and get error in small batch size even.
So what I the best place to define the model? And how can I resolve the error

GPU and CPU version of this code is working. I tried to reduce token length of BERT to 128 and batch size to 4. Because some user mention, it is because of OOM, but I could not resolve it

**Comment by kaushikb11** [comment]
Kind Reminder: While using 8 TPU cores, the effective batch size is `batch_size * 8`

**Comment by cyr0930** [comment]
Any clue about this problem? I have similar issue.

**Comment by talhaanwarch** [comment]
Yes, this arises because of batch size. Reduce the batch size
