### ISSUE TITLE
Testing URL links in docs & readme

### ISSUE THREAD

**Issue by Borda** [Lightning-AI/lightning#8107]
## 🚀 Feature

it may easily happen that some external links are not valid anymore so we shall test them all...

### Motivation

detect broken links in the process

### Alternatives

load the URLs via bs4? (a web scraping tool)
assert that the text you get back contains an expected string?

**Comment by shenoynikhil** [comment]
I can take this up!

**Comment by carmocca** [comment]
Re-opening as some links are not fixed yet: https://github.com/Lightning-AI/lightning/pull/16234#issuecomment-1371249765

**Comment by shenoynikhil** [comment]
Also, #16168 has not been merged yet.

**Comment by carmocca** [comment]
We might want to skip checking the links in the `CHANGELOG.md` files. They take a very long time.

**Comment by shenoynikhil** [comment]
I'm in the process of creating a PR for fixing the sphinx docs links. I can add that in that PR or should I create a separate one?

**Comment by carmocca** [comment]
Since the test workflow uses the `pull_request_target` event, I suggest you create a separate PR for anything that touches the workflow file.

**Comment by shenoynikhil** [comment]
> Since the test workflow uses the pull_request_target event, I suggest you create a separate PR for anything that touches the workflow file.


Sure!

**Comment by carmocca** [comment]
The step added in #16234 also checks the CHANGELOG because it's included inside our generated docs. So we will need to skip it both for the markdown link checker and the docs link checker.

**Comment by carmocca** [comment]
You can see the output in master's commit checks: https://github.com/Lightning-AI/lightning/actions/runs/3841963526/jobs/6542790017#step:9:774
