### ISSUE TITLE
prune Tune arguments from Trainer init - LearnRate & BatchSize as callback

### ISSUE THREAD

**Issue by Borda** [Lightning-AI/lightning#9103]
## 🚀 Feature

Move the `auto_scale_batch_size` and `auto_lr_find` to the `.tune` method

### Motivation

it is quite confusing setting some auto finds which needs to be called anyway with `.tune()` which uses another set of arguments.

### Pitch

As a naive user, I would expect that the tuning is executed at the begging of `.fit()`

### Alternatives

Also in such cases, the user is not much under control in which order they are called, for example, my use case is:
1. find the largest batch size
2. do something extra around the model
3. find the best LR

ad this moment I would need to create two Traner instances :(

I am also experiencing some OOM memory failer when I run Batch size and LR, have not the concrete case for debugging yet

### Additional context

The only justification would be usage with Lightning CLI

**Comment by ananthsub** [comment]
I see 3 options:
- keep as is
- move constructor arguments to specific method they apply to (applies to tune, fit, validate, test, predict as well)
- create separate objects for users to interact with: Trainer, Evaluator, Predictor, Tester

the last one is the most extreme, but i wanted to mention for completeness. between the first two, i prefer the second one. there's a similar conversation here: https://github.com/PyTorchLightning/pytorch-lightning/discussions/9006

**Comment by SkafteNicki** [comment]
Additional option: 
Move lr finder and batch scaler to callbacks, removing the `tune` method
`auto_scale_batch_size` and `auto_lr_find` could still exist, setting them to `True` would just add the corresponding callback.

**Comment by Borda** [comment]
> Move lr finder and batch scaler to callbacks, removing the `tune` method

I like this one and it may be the cleanest way as we don't add any other logic pattern/layer
