### ISSUE TITLE
Add the WandbLogger log_model parameter to MLFLowLogger

### ISSUE THREAD

**Issue by AlessioQuercia** [Lightning-AI/lightning#9138]
## 🚀 Feature

At the moment I am using both MLFlowLogger and WandbLogger, and I realized that MLFlowLogger is missing the log_model parameter (I also quickly checked the other loggers and it seems that WandbLogger is the only one having this parameter). Will it be possible to add the log_model parameter to MLFlowLogger (and perhaps to all the other loggers where this is applicable)?

### Motivation

Consistency among the different loggers: it would be nice to have this functionality available in all the loggers.

**Comment by AlessioQuercia** [comment]
I opened a PR (#9187) for this feature @tchaton, @rohitgr7. It seems that there are some failed tests that I did not have locally, I will try to solve them.

The feature is slightly different from the one in WandbLogger, since MLFlowLogger `log_artifact()` cannot log metadata and aliases. Therefore the logic is that metadata.yml and aliases.txt temp files are created and logged together with the checkpoint (3 artifacts per checkpoint) in the model/checkpoint/CHECKPOINT_NAME/ directory.

If you prefer to only log the checkpoint and discard the metadata and aliases info, I can simply delete the temporary folder part of the code and it should still work. Please, let me know if you have any other suggestions on how to manage this problem.

Best regards,
Alessio

**Comment by rohitgr7** [comment]
I think metadata is fine. Would it be a good idea to merge aliases into metadata as a simple key-value pair? in wandb as well maybe?

**Comment by AlessioQuercia** [comment]
It makes totally sense for MLFlow (in fact I wanted to put it inside metadata initially), but I don't know if it makes sense for wandb (there should be a specific space for aliases in wandb if I am not wrong).
