### ISSUE TITLE
integration template for external developers

### ISSUE THREAD

**Issue by Borda** [Lightning-AI/lightning#9315]
## 🚀 Feature

prepare a minimal repo that would introduce PL as submodule and allow anyone to setup compatibility checks with master

### Motivation

Simplify any external integration and notify users and/or PL contributors about eventual breaking changes

### Pitch

continues compatibility checks with external integrations

### Alternatives

- Set a repo that would have Pl as a submodule
- CI workflows:
  - regular sync for submodule and update latest master
  - running all included tests after each sync/update submodule
- consider messaging to Slack or mail

### Additional context

Any integrators will be responsible for writing relevant tests

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

**Comment by tchaton** [comment]
@daniellepintz Any thoughts on this ?

We are trying to imagine mechanism to increase Lightning reliability and I think Facebook could add its own Lightning dependent library like PyTorch Video to ensure minimal BC + notifications on test failure.

Best,
T.C

**Comment by haooooooqi** [comment]
Hi @tchaton,

I like the proposal here. The PTV team would like to cooperate to increase the reliability for the minimal repo. Could you remind us what would be the items you'd like us to improve/ modify for the PyTorch Lightning minimal version?

**Comment by daniellepintz** [comment]
@tchaton thanks for tagging me, I'm afraid I don't fully understand what is proposed here. Is my understanding correct that we want to create a new GitHub repo that will import PL?

>allow anyone to setup compatibility checks with master
what is meant by this exactly?

**Comment by tchaton** [comment]
Hey @daniellepintz. The idea is to have another repo running on Lightning master head and containing lightning ecosystem library tests such as pytorch video.

On nightly, we would pull the new changes from Lightning, run all tests and notify ecosystem libraries if there are some failing tests.

This should help Lightning to prevent BC or at least to get lightning users notified as soon as it happens.

Best,
T.C

**Comment by daniellepintz** [comment]
Thanks for the explanation! It seems like it has the potential to very useful. At the same time I feel it does introduce some overhead by having to maintain another repo, and I worry the number of failing tests may become overwhelming/noisy, similar to PL master CI. But take this with a grain of salt as I am very new to the team

**Comment by carmocca** [comment]
Done via the ecosystem-ci project
