### ISSUE TITLE
[RFC] Inter batch parallelism as a Loop

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lightning#9415]
## 🚀 Feature

Replace what was implemented as part of https://github.com/PyTorchLightning/pytorch-lightning/issues/8316 with an `InterBatchParalellismLoop`

### Motivation

One of the core pieces of the LightningModule is the `training_step`. Up until #8316, the assumption was that 1 batch maps to 1 training step call. Given this, the `training_step` is the smallest unit of works Lightning does as far as the loops know.

With #8316, the following is supported:

```python
def training_step(self, dataloader_iter):
    b1 = next(dataloader_iter)
    b2 = next(dataloader_iter):
    
    output = self(b1)
    ...
```

which means that one `training_step` consumes as many batches as necessary

Cons of this approach:
- No backward performance enhancements with automatic optimization.
- The batch index jumps by the number of batches consumed in the `training_step`. This could break all pieces that rely on the batch index. Given the example above, the batch index would jump from `0` to `2`.
- The code complexity has increased a lot with all the dataloader iterator abstractions to allow this. These abstractions leak to several components.
- The `training_step` needs to be adapted to this feature, meaning, you cannot switch it on-and-off easily. This is a problem in the context of using already written `LightningModules` from the community or other colleagues.
- The Loop are using a stopIteration mechanism to stop and the training step shouldn t raised it. 

### Pitch

To leverage and showcase the work done for "loop customization", an `InterBatchParallelismLoop` could be a great replacement to fix this. The user would opt-in and then the `training_step` would still keep the original signature (not taking an iterator anymore).

Very roughly:
```python
class InterBatchParallelismLoop(Loop):  # subclass `TrainingEpochLoop`?
    def __init__(parallel_batches: int):
        ...

    def advance():
        ...
        batches = self.fetch()
        for batch in batches:
            self.batch_loop.run(batch)
        ...

    def fetch():
        batches = []
        for n in self.parallel_batches:
            try:
                batches.append(next(self.dataloader_iter))
            except StopIteration:
                break
        return batches
```

Loop structure:

```python
FitLoop
    InterBatchParallelismLoop
        BatchLoop
            OptimizerLoop
            ManualLoop
```

### Alternatives

Not do this.
______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

cc @justusschock @awaelchli @tchaton @carmocca

**Comment by tchaton** [comment]
@yifuwang @ananthsub
