### ISSUE TITLE
Update Lightning-bolts documentation page

### ISSUE THREAD

**Issue by SeanNaren** [Lightning-AI/lightning#9640]
## 📚 Documentation

Related #9634 

After https://github.com/PyTorchLightning/lightning-bolts/issues/712 this page is outdated: https://pytorch-lightning.readthedocs.io/en/latest/ecosystem/bolts.html

We should update this page with information from the README/docs.

**Comment by tchaton** [comment]
Hey @SeanNaren.

Yes, I believe this part of the Lightning documentaiton needs to be updated as well ! 
Great catch !

Best,
T.C
