### ISSUE TITLE
Unable to use tpu_cores=8 on Kaggle

### ISSUE THREAD

**Issue by vigneshwaran** [Lightning-AI/lightning#9812]
## 🐛 Bug

I am not able to all cores from TPU v3-8. I am getting error, `Cannot replicate if number of devices (1) is different from 8`

## Packages:
 - torch-xla: nightly
 - lightning: 1.4.5

The issue is still unresolved which is mentioned here https://github.com/PyTorchLightning/pytorch-lightning/issues/7591#issuecomment-869208074

**Comment by Programmer-RD-AI** [comment]
hi I found similar errors 

#1587
#1703

Can you check these issues?
And tell me if these issues help you.
If it didn't I will check the error.

Regards

**Comment by vigneshwaran** [comment]
Yeah. The issue is similar to https://github.com/PyTorchLightning/pytorch-lightning/issues/1703#issuecomment-860766182. 
It is not solved yet.

**Comment by kaushikb11** [comment]
@vigneshwaran Could you share your notebook to reproduce the issue?

**Comment by daniellepintz** [comment]
same issue in #9712 https://app.circleci.com/pipelines/github/PyTorchLightning/pytorch-lightning/44836/workflows/20f3cc67-3596-4d27-8ecb-c909a3cf6577/jobs/132588/parallel-runs/0/steps/0-119

**Comment by kaushikb11** [comment]
@vigneshwaran Could you try it out again with master?

**Comment by carmocca** [comment]
For any future readers, the cause of this issue is described in https://lightning.ai/docs/pytorch/stable/accelerators/tpu_faq.html#how-to-resolve-the-replication-issue
