### ISSUE TITLE
Make custom samplers distributed automatically

### ISSUE THREAD

**Issue by ibro45** [Lightning-AI/lightning#9883]
### Pitch
In DDP mode, PL sets `DistributedSampler` under the hood. However, if you wish to use a custom sampler, then you need to set `Trainer(replace_sampler_ddp=False)` and wrap your custom sampler manually into `DistributedSampler` (https://github.com/PyTorchLightning/pytorch-lightning/issues/5145#issuecomment-745792060)

Instead of having to manually wrap a custom sampler, I think that this can be done under the hood too. For example, https://github.com/pytorch/pytorch/issues/23430#issuecomment-750037457 refers to Catalyst's wrapper for distributing custom samplers. I used it in vanilla PyTorch like this:

```python
from torch.utils.data.distributed import DistributedSampler
from catalyst.data.sampler import DistributedSamplerWrapper

dataset = ...
shuffle = ...
sampler = ...

# If DDP on
if torch.distributed.is_initialized():
    # If using a custom sampler make it distributed
    if sampler is not None:
        sampler = DistributedSamplerWrapper(sampler,
                                            shuffle=shuffle,
                                            num_replicas=communication.get_world_size(),
                                            rank=communication.get_rank())
    # If no custom sampler then just use the DistributedSampler
    else:
        sampler = DistributedSampler(dataset,
                                     shuffle=shuffle,
                                     num_replicas=communication.get_world_size(),
                                     rank=communication.get_rank())

# shuffle shouldn't be specified in DataLoader when using a sampler
shuffle = shuffle if sampler is None else None
dataloader = DataLoader(dataset, sampler=sampler, shuffle=shuffle, ...)
```

cc @borda @awaelchli @rohitgr7 @akihironitta @justusschock @ninginthecloud @tchaton

**Comment by tchaton** [comment]
Dear @ibro45,

Would you be interested in making a PR?

Best,
T.C
