### ISSUE TITLE
Support Python 3.10

### ISSUE THREAD

**Issue by akihironitta** [Lightning-AI/lightning#9980]
## 🚀 Feature
We should support Python 3.10 as Python 3.10 was released at the beginning of this month.

**Required dependencies supporting Python 3.10**
- [x] numpy>=1.21.0 https://numpy.org/news/#numpy-1210-release
- [x] torch>=1.11.0 https://github.com/pytorch/pytorch/issues/66424
- [x] tqdm
- [x] PyYAML
- [x] fsspec
- [x] tensorboard https://github.com/tensorflow/tensorboard/releases/tag/2.8.0
- [x] torchmetrics since its dependency `torch>=1.11` supports Python 3.10
- [x] pyDeprecate https://github.com/Borda/pyDeprecate/issues/18
- [x] packaging
- [x] typing-extensions

The above checklist is mainly based on PyPI badge on pypi.org
______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

cc @borda @carmocca @akihironitta @tchaton @rohitgr7

**Comment by Borda** [comment]
Let's try now when PT 1.11 is out... 🐰

**Comment by carmocca** [comment]
@akihironitta is this done?

**Comment by akihironitta** [comment]
@carmocca Will start working on it :)

**Comment by akihironitta** [comment]
TODO:
- [ ] Enable Python 3.10 in "full" CPU testing: #13829
- [ ] Enable Python 3.10 in "conda" CPU testing:
- [ ] Enable Python 3.10 in GPU testing

**Comment by carmocca** [comment]
I believe this can be closed now @akihironitta

**Comment by carmocca** [comment]
One follow-up improvement would be to use 3.10 in the mypy job cc @otaj

**Comment by function2-llx** [comment]
Hello, want to ask here if Python 3.10 is supported now? The badge seems not to include 3.10.

**Comment by carmocca** [comment]
It is! Would you like to open a PR updating the badge?

**Comment by function2-llx** [comment]
I'd love to!
